CREATE OR REPLACE TRIGGER MORE_MORE_CD_MOTIVO_RESULTADO
BEFORE INSERT ON PMS20_DEV.MOTIVO_RESULTADO
FOR EACH ROW
when (NEW.MORE_CD_MOTIVO_RESULTADO IS NULL)
BEGIN
    SELECT PMS20_DEV.SQ_MORE_CD_MOTIVO_RESULTADO.NEXTVAL INTO :NEW.MORE_CD_MOTIVO_RESULTADO FROM DUAL;
END;