CREATE OR REPLACE TRIGGER RERE_RERE_CD_RECEITA_RESULTADO
BEFORE INSERT ON PMS20_DEV.RECEITA_RESULTADO
FOR EACH ROW
when (NEW.RERE_CD_RECEITA_RESULTADO IS NULL)
BEGIN
    SELECT PMS20_DEV.SQ_RERE_CD_RECEITA_RESULTADO.NEXTVAL INTO :NEW.RERE_CD_RECEITA_RESULTADO FROM DUAL;
END;
