create or replace procedure usp_pms_carga_foto_dres as
     v_versao number;
     versao   varchar2(40);
begin
     v_versao := 0;
     versao   := '';
     --
     select max( t.num_versao )
     into v_versao
     from tb_bi_pms_dre_umkts_valid t;
     --
     if v_versao is null then
        v_versao := 1;
     elsif v_versao > 60 then
        delete from tb_bi_pms_dre_umkts_valid
        where v_versao = v_versao - 60;
        --
        commit;
     end if;
     --
     if v_versao >= 1 then
        v_versao := v_versao + 1;
     end if;
     --
     versao := 'v_' || to_char( sysdate, 'ddmmyyyy' ) || '-' || to_char( v_versao );
     --
     insert into tb_bi_pms_dre_umkts_valid
     select origem,
            cd_contrato_pratica,
            nome_contrato_pratica,
            dt_mes,
            umkt,
            sso,
            pratica,
            bm,
            categoria,
            moeda,
            pratica,
            login,
            login_mgr,
            nvl( cd_moeda_revenue, 1 ) cd_moeda_revenue,
            valor_receita_currency,
            valor_receita_brl,
            valor_fte_revenue,
            valor_cotacao_revenue,
            valor_ut_rate,
            valor_fte_ut_rate,
            valor_imposto_original,
            valor_imposto_convertido,
            cd_moeda_rev_out_sourc,
            valor_rev_out_sourc,
            valor_rev_out_sourc_brl,
            valor_cotacao_out_source,
            cd_moeda_rev_out_alloc,
            valor_rev_out_alloc,
            valor_rev_out_alloc_brl,
            valor_cotacao_out_alloc,
            valor_desp_rel_curr,
            valor_desp_rel_brl,
            valor_despfix_ratumkt_curr,
            valor_despfix_ratumkt_brl,
            vlr_despfix_lob_curr,
            vlr_despfix_lob_brl,
            vlr_desp_contab_inter,
            vlr_desp_contab_brl,
            vlr_quality_costs_brl,
            valor_desp_plan_curr,
            valor_desp_plan_brl,
            ' ',
            cd_moeda_cdir,
            valor_custo_dir_tce_curr,
            valor_custo_dir_tce_brl,
            valor_custo_dir_infra_curr,
            valor_custo_dir_infra_brl,
            valor_fte_cdir,
            valor_fte_ferias_cdir,
            valor_fte_licenca,
            valor_cotacao_cdir,
            cd_moeda_cind,
            valor_custo_ind_tce_curr,
            valor_custo_ind_tce_brl,
            valor_custo_ind_infra_curr,
            valor_custo_ind_infra_brl,
            valor_fte_cind,
            valor_fte_ferias_cind,
            valor_cotacao_cind,
            vlr_vacation_fte,
            cd_ti_recurso,
            nvl( nome_ti_recurso, ' ' ),
            valor_custo_unit_ti_rec,
            quant_ti_recursos,
            valor_custo_item,
            cd_moeda_custlic_ratumkt,
            valor_custlic_rateio_umkt,
            valor_custlic_rateio_umkt_brl,
            valor_cota_custlic_ratumkt,
            cd_moeda_custlic_ratprat,
            valor_custlic_rateio_prat,
            valor_custlic_ratprat_brl,
            valor_cota_custlic_ratprat,
            valor_hora_extra,
            valor_plantao,
            cd_moeda_custo_out_sourc,
            valor_custo_out_sourc,
            valor_custo_out_sourc_brl,
            valor_cota_custo_out_sourc,
            cd_moeda_custo_out_alloc,
            valor_custo_out_aloc,
            valor_custo_out_alloc_brl,
            valor_cota_custo_out_alloc,
            cd_moeda_lob_fixcost,
            vlr_cust_rat_lob_fixcost_brl,
            perc_receita_lob_fixcost,
            vlr_rec_lob_fixcost_curr,
            vlr_rec_lob_fixcost_brl,
            vlr_rec_clob_lobfixcost_curr,
            vlr_rec_clob_lobfixcost_brl,
            vlr_tot_fte_lob_fixcost,
            cd_moeda_custfix_ratprat,
            valor_custfix_rateio_prat,
            valor_tce_custfix_ratprat,
            valor_custinfra_fix_ratprat,
            valor_custfix_ratprat_brl,
            valor_tce_custfix_ratprat_brl,
            valor_cusinfra_fix_ratprat_brl,
            valor_custfix_lob_ferias,
            valor_fte_custfix_ratprat,
            vlr_fte_cusfix_ferias_ratprat,
            valor_cota_custfix_ratprat,
            cd_moeda_custfix_ratumkt,
            valor_custfix_rateio_umkt,
            valor_tce_custfix_ratumkt,
            valor_custinfra_fix_ratumkt,
            valor_custfix_rateio_umkt_brl,
            valor_tce_custfix_ratumkt_brl,
            valor_custinf_fix_ratumkt_brl,
            valor_custfix_umkt_ferias,
            valor_fte_custfix_ratumkt,
            vlr_fte_cusfix_ferias_ratumkt,
            valor_cota_custfix_ratumkt,
            vlr_tecsal_cdir_tce_curr,
            vlr_tecsal_cdir_tce_brl,
            vlr_tecsal_cdir_infra_curr,
            vlr_tecsal_cdir_infra_brl,
            vlr_tecsal_cind_tce_curr,
            vlr_tecsal_cind_tce_brl,
            vlr_tecsal_cind_infra_curr,
            vlr_tecsal_cind_infra_brl,
            tecsal_pr_ferias,
            vlr_tecsal_custlic_curr,
            vlr_tecsal_custlic_brl,
            tecsal_pr_aloc_licenca,
            vlr_tecsal_hora_extra,
            vlr_tecsal_plantao,
            vlr_tecsal_desp_curr,
            vlr_tecsal_desp_brl,
            vl_comiss_acel_curr,
            vl_comiss_acel_brl,
            vl_comiss_inv_curr,
            vl_comiss_inv_brl,
            vlr_custrat_mkt_curr,
            vlr_custrat_mkt_brl,
            vlr_custrat_dn_curr,
            vlr_custrat_dn_brl,
            vlr_custrat_ae_curr,
            vlr_custrat_ae_brl,
            vlr_cust_colab_mkt_curr,
            vlr_cust_colab_mkt_brl,
            vlr_cust_colab_dn_curr,
            vlr_cust_colab_dn_brl,
            vlr_cust_colab_ae_curr,
            vlr_cust_colab_ae_brl,
            vlr_desprat_mkt_trav_curr,
            valor_desprat_dn_trav_curr,
            valor_desprat_ae_trav_curr,
            vlr_desprat_mkt_oth_curr,
            valor_desprat_dn_oth_curr,
            valor_desprat_ae_oth_curr,
            vlr_desprat_mkt_trav_brl,
            valor_desprat_dn_trav_brl,
            valor_desprat_ae_trav_brl,
            vlr_desprat_mkt_oth_brl,
            valor_desprat_dn_oth_brl,
            valor_desprat_ae_oth_brl,
            vlr_desp_mkt_travel_curr,
            vlr_desp_mkt_travel_brl,
            vlr_desp_mkt_others_curr,
            vlr_desp_mkt_others_brl,
            vlr_desp_dn_travel_curr,
            vlr_desp_dn_travel_brl,
            vlr_desp_dn_others_curr,
            vlr_desp_dn_others_brl,
            vlr_desp_ae_travel_curr,
            vlr_desp_ae_travel_brl,
            vlr_desp_ae_others_curr,
            vlr_desp_ae_others_brl,
            trunc(sysdate),
            v_versao,
            versao
     from vw_bi_pms_consolida_dres;
     --
     commit;
end usp_pms_carga_foto_dres;