/*
 * @(#) AjusteReceitaAudId.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * AjusteReceitaAudId generated by hbm2java
 *
 * @author pricaldeira@ciandt.com
 * @since 14/06/2021 14:25:08
 * @version 14/06/2021 1.0 14:25:08
 */
@Embeddable
public class AjusteReceitaAudId implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "AjusteReceitaAudId.findAll".
     */
    public static final String FIND_ALL = "AjusteReceitaAudId.findAll";

    @Column(name = "AJRE_CD_AJUSTE_RECEITA", nullable = false, precision = 18, scale = 0)
    private Long codigoAjusteReceita;

    /**
     * Atributo gerado a partir da coluna REV.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "REV", nullable = false, insertable = false, updatable = false)
    private PMSRevisionEntity revinfo;

    /**
     * Construtor default.
     */
    public AjusteReceitaAudId() {
    }

    /**
     * Construtor com preenchimento da entidade.
     *
     * @param codigoAjusteReceita
     *            Valor do atributo codigoAjusteReceita;
     * @param codigoAjusteReceita
     * @param revinfo
     *            do atributo revinfo;
     */
    public AjusteReceitaAudId(Long codigoAjusteReceita,
                              PMSRevisionEntity revinfo) {
        this.codigoAjusteReceita = codigoAjusteReceita;
        this.revinfo = revinfo;
    }

    /**
     * Obtem o valor do atributo codigoAjusteReceita.<BR>
     *
     * @return Valor do atributo codigoAjusteReceita.
     */
    public Long getCodigoAjusteReceita() {
        return this.codigoAjusteReceita;
    }

    /**
     * Atualiza o valor do atributo codigoAjusteReceita.<BR>
     *
     * @param codigoAjusteReceita
     *            Novo valor para o atributo codigoAjusteReceita.
     */
    public void setCodigoAjusteReceita(Long codigoAjusteReceita) {
        this.codigoAjusteReceita = codigoAjusteReceita;
    }

    /**
     * Obtem o valor do atributo revinfo.<BR>
     *
     * @return Valor do atributo revinfo.
     */
    public PMSRevisionEntity getRevinfo() {
        return revinfo;
    }

    /**
     * Atualiza o valor do atributo revinfo.<BR>
     *
     * @param revinfo
     *            Novo valor para o atributo revinfo.
     */
    public void setRevinfo(PMSRevisionEntity revinfo) {
        this.revinfo = revinfo;
    }

    /*
     * (non-Javadoc)
     *
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime
                * result
                + ((codigoAjusteReceita == null) ? 0
                : codigoAjusteReceita.hashCode());
        result = prime * result + ((revinfo == null) ? 0 : revinfo.hashCode());
        return result;
    }

    /*
     * (non-Javadoc)
     *
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        AjusteReceitaAudId other = (AjusteReceitaAudId) obj;
        if (codigoAjusteReceita == null) {
            if (other.codigoAjusteReceita != null)
                return false;
        } else if (!codigoAjusteReceita.equals(other.codigoAjusteReceita))
            return false;
        if (revinfo == null) {
            if (other.revinfo != null)
                return false;
        } else if (!revinfo.equals(other.revinfo))
            return false;
        return true;
    }

    /*
     * (non-Javadoc)
     *
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("AjusteReceitaAudId [codigoAjusteReceita=");
        builder.append(codigoAjusteReceita);
        builder.append(", revinfo=");
        builder.append(revinfo);
        builder.append("]");
        return builder.toString();
    }

}
