/*
 * @(#) AjusteReceita.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Entity gerado a partir da tabela AJUSTE_RECEITA.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 14/07/2011 14:25:43
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "AJUSTE_RECEITA")
@NamedQueries({
		@NamedQuery(name = "AjusteReceita.findAll", query = "SELECT t FROM AjusteReceita t"),

		@NamedQuery(name = "AjusteReceita.findByFilter", query = "SELECT t FROM AjusteReceita t "
				+ " JOIN FETCH t.receitaDealFiscal rdf "
				+ " JOIN FETCH rdf.receitaMoeda rm "
				+ " JOIN FETCH rm.receita r "
				+ " JOIN FETCH r.contratoPratica cp "
				+ " JOIN FETCH rdf.dealFiscal df "
				+ " WHERE ((t.codigoAjusteReceita = ?) OR (? = (0L))) "
				+ " AND (t.codigoLoginAutor = ? OR t.codigoLoginAutor = '')"
				+ " AND (TRUNC(t.dataMesAjuste) = TRUNC(?)) "
				+ " AND ((rdf.codigoReceitaDfiscal = ?) OR (? = (0L))) "
				+ " AND ((t.tipoAjuste.codigoTipoAjuste = ?) OR (? = (0L))) "),

		@NamedQuery(name = "AjusteReceita.findByDateAjuste", query = "SELECT t FROM AjusteReceita t "
				+ " JOIN FETCH t.receitaDealFiscal rdf "
				+ " JOIN FETCH rdf.receitaMoeda rm "
				+ " JOIN FETCH rm.receita r "
				+ " JOIN FETCH r.contratoPratica cp "
				+ " JOIN FETCH rdf.dealFiscal df "
				+ " WHERE (TRUNC(t.dataMesAjuste) = TRUNC(?)) "),

        @NamedQuery(name = "AjusteReceita.findByDateAjusteAndContratoPratica", query = "SELECT t FROM AjusteReceita t "
                + " JOIN FETCH t.receitaDealFiscal rdf "
                + " JOIN FETCH rdf.receitaMoeda rm "
                + " JOIN FETCH rm.receita r "
                + " JOIN FETCH r.contratoPratica cp "
                + " JOIN FETCH rdf.dealFiscal df "
                + " WHERE (TRUNC(t.dataMesAjuste) = TRUNC(?)) "
                + " AND cp.codigoContratoPratica = ? "),

		@NamedQuery(name = "AjusteReceita.findByDateReceita", query = "SELECT t FROM AjusteReceita t "
				+ " JOIN FETCH t.receitaDealFiscal rdf "
				+ " JOIN FETCH rdf.receitaMoeda rm "
				+ " JOIN FETCH rm.receita r "
				+ " JOIN FETCH r.contratoPratica cp "
				+ " JOIN FETCH rdf.dealFiscal df "
				+ " WHERE (TRUNC(r.dataMes) = TRUNC(?)) "),

		@NamedQuery(name = "AjusteReceita.findByDateReceitaAndContratoPratica", query = "SELECT t FROM AjusteReceita t "
				+ " JOIN FETCH t.receitaDealFiscal rdf "
				+ " JOIN FETCH rdf.receitaMoeda rm "
				+ " JOIN FETCH rm.receita r "
				+ " JOIN FETCH r.contratoPratica cp "
				+ " JOIN FETCH rdf.dealFiscal df "
				+ " WHERE (TRUNC(r.dataMes) = TRUNC(?)) "
				+ " AND cp.codigoContratoPratica = ? "),

		@NamedQuery(name = "AjusteReceita.findByDateReceitaAndDateAjuste", query = "SELECT t FROM AjusteReceita t "
				+ " JOIN FETCH t.receitaDealFiscal rdf "
				+ " JOIN FETCH rdf.receitaMoeda rm "
				+ " JOIN FETCH rm.receita r "
				+ " JOIN FETCH r.contratoPratica cp "
				+ " JOIN FETCH rdf.dealFiscal df "
				+ " WHERE (TRUNC(r.dataMes) = TRUNC(?)) "
				+ " AND (TRUNC(t.dataMesAjuste) = TRUNC(?))"),

		@NamedQuery(name = "AjusteReceita.findByDateReceitaAndDateAjusteAndContratoPratica", query = "SELECT t FROM AjusteReceita t "
				+ " JOIN FETCH t.receitaDealFiscal rdf "
				+ " JOIN FETCH rdf.receitaMoeda rm "
				+ " JOIN FETCH rm.receita r "
				+ " JOIN FETCH r.contratoPratica cp "
				+ " JOIN FETCH rdf.dealFiscal df "
				+ " WHERE (TRUNC(r.dataMes) = TRUNC(?)) "
				+ " AND (TRUNC(t.dataMesAjuste) = TRUNC(?))"
				+ " AND cp.codigoContratoPratica = ? "),

        @NamedQuery(name = "AjusteReceita.findByRangeDate", query = "SELECT t FROM AjusteReceita t "
                + " JOIN FETCH t.receitaDealFiscal rdf "
                + " JOIN FETCH rdf.receitaMoeda rm "
                + " JOIN FETCH rm.receita r "
                + " JOIN FETCH r.contratoPratica cp "
                + " JOIN FETCH rdf.dealFiscal df "
                + " WHERE (TRUNC(t.dataMesAjuste) >= TRUNC(?)) "
                + " AND (TRUNC(t.dataMesAjuste) <= TRUNC(?))"),

		@NamedQuery(name = "AjusteReceita.findByReceitaDealFiscal", query = "SELECT t FROM AjusteReceita t "
				+ "JOIN FETCH t.receitaDealFiscal rdf "
				+ "WHERE rdf.codigoReceitaDfiscal = ?"),

		@NamedQuery(name = "AjusteReceita.findByReceita", query = "SELECT t FROM AjusteReceita t "
				+ "JOIN t.receitaDealFiscal rdf "
				+ "JOIN rdf.receitaMoeda rm "
				+ "WHERE rm.receita.codigoReceita = ? "),

		@NamedQuery(name = "AjusteReceita.findByReceitaMoeda", query = "SELECT t FROM AjusteReceita t "
				+ "JOIN t.receitaDealFiscal rdf "
				+ "JOIN rdf.receitaMoeda rm "
				+ "WHERE rm.codigoReceitaMoeda = ? "
				+ "AND (t.ajusteReceitaPai IS NOT NULL OR t.tipoAjuste.codigoTipoAjuste != 3) "
				+ "ORDER BY t.dataMesAjuste"),
		
		@NamedQuery(name = "AjusteReceita.findByAjusteReceitaPai", query = "SELECT t FROM AjusteReceita t "
				+ "WHERE t.ajusteReceitaPai.codigoAjusteReceita = ?"),

		@NamedQuery(name = "AjusteReceita.getTotalPublishedByDealFiscalAndDate", query = "SELECT t FROM AjusteReceita t "
				+ "LEFT JOIN FETCH t.receitaDealFiscal rdf "
				+ "LEFT JOIN FETCH rdf.receitaMoeda rm "
				+ "LEFT JOIN FETCH rm.receita r "
				+ "WHERE rdf.dealFiscal.codigoDealFiscal = :codigoDealFiscal "
				+ "AND TRUNC(r.dataMes) <= :dataFim "
				+ "AND UPPER(r.indicadorVersao) IN ('PB', 'IN', 'PD')") })
public class AjusteReceita implements java.io.Serializable {

	// ========================================================================
	// BEGIN - Coloque aqui o codigo manual
	// ========================================================================

	/** Constante para NamedQuery "AjusteReceita.findByFilter". */
	public static final String FIND_BY_FILTER = "AjusteReceita.findByFilter";

	/** Constante para NamedQuery "AjusteReceita.findByDateAjuste". */
	public static final String FIND_BY_DATE_AJUSTE = "AjusteReceita.findByDateAjuste";

	/**
	 * Constante para NamedQuery
	 * "AjusteReceita.findByDateAjusteAndContratoPratica".
	 */
	public static final String FIND_BY_DATE_AJUSTE_AND_CONTRATO_PRATICA = "AjusteReceita.findByDateAjusteAndContratoPratica";

	/** Constante para NamedQuery "AjusteReceita.findByDateReceita". */
	public static final String FIND_BY_DATE_RECEITA = "AjusteReceita.findByDateReceita";

	/**
	 * Constante para NamedQuery
	 * "AjusteReceita.findByDateReceitaAndContratoPratica".
	 */
	public static final String FIND_BY_DATE_RECEITA_AND_CONTRATO_PRATICA = "AjusteReceita.findByDateReceitaAndContratoPratica";

	/**
	 * Constante para NamedQuery "AjusteReceita.findByDateReceitaAndDateAjuste".
	 */
	public static final String FIND_BY_DATE_RECEITA_AND_DATE_AJUSTE = "AjusteReceita.findByDateReceitaAndDateAjuste";

	/**
	 * Constante para NamedQuery
	 * "AjusteReceita.findByDateReceitaAndDateAjusteAndContratoPratica".
	 */
	public static final String FIND_BY_DATE_RECEITA_AND_DATE_AJUSTE_AND_CONTRATO_PRATICA = "AjusteReceita.findByDateReceitaAndDateAjusteAndContratoPratica";

	/** Constante para NamedQuery "AjusteReceita.findByRangeDate". */
	public static final String FIND_BY_RANGE_DATE = "AjusteReceita.findByRangeDate";

	/** Constrante para NamedQuery AjusteReceita.findByReceitaDealFiscal. */
	public static final String FIND_BY_RECEITA_DEAL_FISCAL = "AjusteReceita.findByReceitaDealFiscal";

	/** Constrante para NamedQuery AjusteReceita.findByReceita. */
	public static final String FIND_BY_RECEITA = "AjusteReceita.findByReceita";

	/**
	 * Constrante para NamedQuery
	 * AjusteReceita.getTotalPublishedByDealFiscalAndDate.
	 */
	public static final String GET_TOTAL_PUBLISHED_BY_DEAL_FISCAL_AND_DATE = "AjusteReceita.getTotalPublishedByDealFiscalAndDate";

	/** Constrante para NamedQuery AjusteReceita.findByReceitaMoeda. */
	public static final String FIND_BY_RECEITA_MOEDA = "AjusteReceita.findByReceitaMoeda";

	/** Constrante para NamedQuery AjusteReceita.findByAjusteReceitaPai. */
	public static final String FIND_BY_AJUSTE_RECEITA_PAI = "AjusteReceita.findByAjusteReceitaPai";

	// ========================================================================
	// END
	// ========================================================================

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "AjusteReceita.findAll".
	 */
	public static final String FIND_ALL = "AjusteReceita.findAll";

	/**
	 * Atributo gerado a partir da coluna AJRE_CD_AJUSTE_RECEITA.
	 */
	@Id
	@GeneratedValue(generator = "AjusteReceitaSeq")
	@SequenceGenerator(name = "AjusteReceitaSeq", sequenceName = "SQ_AJRE_CD_AJUSTE_RECEITA", allocationSize = 1)
	@Column(name = "AJRE_CD_AJUSTE_RECEITA", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoAjusteReceita;

	/**
	 * Atributo gerado a partir da coluna TIAJ_CD_TIPO_AJUSTE.
	 */
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIAJ_CD_TIPO_AJUSTE")
	private TipoAjuste tipoAjuste;

	/**
	 * Atributo gerado a partir da coluna REDF_CD_RECEITA_DFISCAL.
	 */
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REDF_CD_RECEITA_DFISCAL", nullable = false)
	private ReceitaDealFiscal receitaDealFiscal;

	/**
	 * Atributo gerado a partir da coluna AJRE_CD_LOGIN_AUTOR.
	 */
	@Audited
	@Column(name = "AJRE_CD_LOGIN_AUTOR", nullable = false, length = 20)
	private String codigoLoginAutor;

	/**
	 * Atributo gerado a partir da coluna AJRE_TX_OBSERVACAO.
	 */
	@Audited
	@Column(name = "AJRE_TX_OBSERVACAO", length = 1000)
	private String textoObservacao;

	/**
	 * Atributo gerado a partir da coluna AJRE_DT_MES_AJUSTE.
	 */
	@Audited
	@Temporal(TemporalType.DATE)
	@Column(name = "AJRE_DT_MES_AJUSTE", length = 7)
	private Date dataMesAjuste;

	/**
	 * Atributo gerado a partir da coluna AJRE_DT_CRIACAO.
	 */
	@Audited
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AJRE_DT_CRIACAO", length = 7)
	private Date dataCriacao;

	/**
	 * Atributo gerado a partir da coluna AJRE_DT_ATUALIZACAO.
	 */
	@Audited
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AJRE_DT_ATUALIZACAO", length = 7)
	private Date dataAtualizacao;

	/**
	 * Atributo gerado a partir da coluna AJRE_VL_AJUSTE.
	 */
	@Audited
	@Column(name = "AJRE_VL_AJUSTE", precision = 22, scale = 0)
	private BigDecimal valorAjuste;

	/** Atributo balanco. */
	@Transient
	private BigDecimal balanco;

	/** Total de Ajuste feito em um c-lob. */
	@Transient
	private BigDecimal totalAjusteContrato;

	/** Total de Balance feito em um c-lob. */
	@Transient
	private BigDecimal totalBalancoContrato;

	/**
	 * Atributo gerado a partir da coluna AJRE_CD_AJUSTE_RECEITA_PAI.
	 */
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "AJRE_CD_AJUSTE_RECEITA_PAI")
	private AjusteReceita ajusteReceitaPai;

	/**
	 * Construtor default.
	 */
	public AjusteReceita() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoAjusteReceita
	 *            Valor do atributo codigoAjusteReceita;
	 * @param tipoAjuste
	 *            Valor do atributo tipoAjuste;
	 * @param receitaDealFiscal
	 *            Valor do atributo receitaDealFiscal;
	 * @param codigoLoginAutor
	 *            Valor do atributo codigoLoginAutor;
	 */
	public AjusteReceita(final Long codigoAjusteReceita,
			final TipoAjuste tipoAjuste,
			final ReceitaDealFiscal receitaDealFiscal,
			final String codigoLoginAutor) {
		this.codigoAjusteReceita = codigoAjusteReceita;
		this.tipoAjuste = tipoAjuste;
		this.receitaDealFiscal = receitaDealFiscal;
		this.codigoLoginAutor = codigoLoginAutor;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoAjusteReceita
	 *            Valor do atributo codigoAjusteReceita;
	 * @param tipoAjuste
	 *            Valor do atributo tipoAjuste;
	 * @param receitaDealFiscal
	 *            Valor do atributo receitaDealFiscal;
	 * @param codigoLoginAutor
	 *            Valor do atributo codigoLoginAutor;
	 * @param textoObservacao
	 *            Valor do atributo textoObservacao;
	 * @param dataMesAjuste
	 *            Valor do atributo dataMesAjuste;
	 * @param dataCriacao
	 *            Valor do atributo dataCriacao;
	 * @param valorAjuste
	 *            Valor do atributo valorAjuste;
	 */
	public AjusteReceita(final Long codigoAjusteReceita,
			final TipoAjuste tipoAjuste,
			final ReceitaDealFiscal receitaDealFiscal,
			final String codigoLoginAutor, final String textoObservacao,
			final Date dataMesAjuste, final Date dataCriacao,
			final BigDecimal valorAjuste) {
		this.codigoAjusteReceita = codigoAjusteReceita;
		this.tipoAjuste = tipoAjuste;
		this.receitaDealFiscal = receitaDealFiscal;
		this.codigoLoginAutor = codigoLoginAutor;
		this.textoObservacao = textoObservacao;
		this.dataMesAjuste = dataMesAjuste;
		this.dataCriacao = dataCriacao;
		this.valorAjuste = valorAjuste;
	}

	/**
	 * @return the totalBalancoContrato
	 */
	public BigDecimal getTotalBalancoContrato() {
		return totalBalancoContrato;
	}

	/**
	 * @param totalBalancoContrato
	 *            the totalBalancoContrato to set
	 */
	public void setTotalBalancoContrato(final BigDecimal totalBalancoContrato) {
		this.totalBalancoContrato = totalBalancoContrato;
	}

	/**
	 * @return the totalAjusteContrato
	 */
	public BigDecimal getTotalAjusteContrato() {
		return totalAjusteContrato;
	}

	/**
	 * @param totalAjusteContrato
	 *            the totalAjusteContrato to set
	 */
	public void setTotalAjusteContrato(final BigDecimal totalAjusteContrato) {
		this.totalAjusteContrato = totalAjusteContrato;
	}

	/**
	 * Obtem o valor do atributo codigoAjusteReceita.<BR>
	 * Atributo gerado a partir da coluna AJRE_CD_AJUSTE_RECEITA.
	 * 
	 * @return Valor do atributo codigoAjusteReceita.
	 */
	public Long getCodigoAjusteReceita() {
		return this.codigoAjusteReceita;
	}

	/**
	 * Atualiza o valor do atributo codigoAjusteReceita.<BR>
	 * Atributo gerado a partir da coluna AJRE_CD_AJUSTE_RECEITA.
	 * 
	 * @param codigoAjusteReceita
	 *            Novo valor para o atributo codigoAjusteReceita.
	 */
	public void setCodigoAjusteReceita(final Long codigoAjusteReceita) {
		this.codigoAjusteReceita = codigoAjusteReceita;
	}

	/**
	 * Obtem o valor do atributo tipoAjuste.<BR>
	 * Atributo gerado a partir da coluna TIAJ_CD_TIPO_AJUSTE.
	 * 
	 * @return Valor do atributo tipoAjuste.
	 */
	public TipoAjuste getTipoAjuste() {
		return this.tipoAjuste;
	}

	/**
	 * Atualiza o valor do atributo tipoAjuste.<BR>
	 * Atributo gerado a partir da coluna TIAJ_CD_TIPO_AJUSTE.
	 * 
	 * @param tipoAjuste
	 *            Novo valor para o atributo tipoAjuste.
	 */
	public void setTipoAjuste(final TipoAjuste tipoAjuste) {
		this.tipoAjuste = tipoAjuste;
	}

	/**
	 * Obtem o valor do atributo receitaDealFiscal.<BR>
	 * Atributo gerado a partir da coluna REDF_CD_RECEITA_DFISCAL.
	 * 
	 * @return Valor do atributo receitaDealFiscal.
	 */
	public ReceitaDealFiscal getReceitaDealFiscal() {
		return this.receitaDealFiscal;
	}

	/**
	 * Atualiza o valor do atributo receitaDealFiscal.<BR>
	 * Atributo gerado a partir da coluna REDF_CD_RECEITA_DFISCAL.
	 * 
	 * @param receitaDealFiscal
	 *            Novo valor para o atributo receitaDealFiscal.
	 */
	public void setReceitaDealFiscal(final ReceitaDealFiscal receitaDealFiscal) {
		this.receitaDealFiscal = receitaDealFiscal;
	}

	/**
	 * Obtem o valor do atributo codigoLoginAutor.<BR>
	 * Atributo gerado a partir da coluna AJRE_CD_LOGIN_AUTOR.
	 * 
	 * @return Valor do atributo codigoLoginAutor.
	 */
	public String getCodigoLoginAutor() {
		return this.codigoLoginAutor;
	}

	/**
	 * Atualiza o valor do atributo codigoLoginAutor.<BR>
	 * Atributo gerado a partir da coluna AJRE_CD_LOGIN_AUTOR.
	 * 
	 * @param codigoLoginAutor
	 *            Novo valor para o atributo codigoLoginAutor.
	 */
	public void setCodigoLoginAutor(final String codigoLoginAutor) {
		this.codigoLoginAutor = codigoLoginAutor;
	}

	/**
	 * Obtem o valor do atributo textoObservacao.<BR>
	 * Atributo gerado a partir da coluna AJRE_TX_OBSERVACAO.
	 * 
	 * @return Valor do atributo textoObservacao.
	 */
	public String getTextoObservacao() {
		return this.textoObservacao;
	}

	/**
	 * Atualiza o valor do atributo textoObservacao.<BR>
	 * Atributo gerado a partir da coluna AJRE_TX_OBSERVACAO.
	 * 
	 * @param textoObservacao
	 *            Novo valor para o atributo textoObservacao.
	 */
	public void setTextoObservacao(final String textoObservacao) {
		this.textoObservacao = textoObservacao;
	}

	/**
	 * Obtem o valor do atributo dataMesAjuste.<BR>
	 * Atributo gerado a partir da coluna AJRE_DT_MES_AJUSTE.
	 * 
	 * @return Valor do atributo dataMesAjuste.
	 */
	public Date getDataMesAjuste() {
		return this.dataMesAjuste;
	}

	/**
	 * Atualiza o valor do atributo dataMesAjuste.<BR>
	 * Atributo gerado a partir da coluna AJRE_DT_MES_AJUSTE.
	 * 
	 * @param dataMesAjuste
	 *            Novo valor para o atributo dataMesAjuste.
	 */
	public void setDataMesAjuste(final Date dataMesAjuste) {
		this.dataMesAjuste = dataMesAjuste;
	}

	/**
	 * Obtem o valor do atributo dataCriacao.<BR>
	 * Atributo gerado a partir da coluna AJRE_DT_CRIACAO.
	 * 
	 * @return Valor do atributo dataCriacao.
	 */
	public Date getDataCriacao() {
		return this.dataCriacao;
	}

	/**
	 * Atualiza o valor do atributo dataCriacao.<BR>
	 * Atributo gerado a partir da coluna AJRE_DT_CRIACAO.
	 * 
	 * @param dataCriacao
	 *            Novo valor para o atributo dataCriacao.
	 */
	public void setDataCriacao(final Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	/**
	 * Obtem o valor do atributo valorAjuste.<BR>
	 * Atributo gerado a partir da coluna AJRE_VL_AJUSTE.
	 * 
	 * @return Valor do atributo valorAjuste.
	 */
	public BigDecimal getValorAjuste() {
		return this.valorAjuste;
	}

	/**
	 * @return the dataAtualizacao
	 */
	public Date getDataAtualizacao() {
		return dataAtualizacao;
	}

	/**
	 * @param dataAtualizacao
	 *            the dataAtualizacao to set
	 */
	public void setDataAtualizacao(final Date dataAtualizacao) {
		this.dataAtualizacao = dataAtualizacao;
	}

	/**
	 * Atualiza o valor do atributo valorAjuste.<BR>
	 * Atributo gerado a partir da coluna AJRE_VL_AJUSTE.
	 * 
	 * @param valorAjuste
	 *            Novo valor para o atributo valorAjuste.
	 */
	public void setValorAjuste(final BigDecimal valorAjuste) {
		this.valorAjuste = valorAjuste;
	}

	/**
	 * @see Object#toString()
	 * @return string
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoAjusteReceita").append("='")
				.append(getCodigoAjusteReceita()).append("' ");

		buffer.append("receitaDealFiscal").append("='")
				.append(getReceitaDealFiscal()).append("' ");
		buffer.append("codigoLoginAutor").append("='")
				.append(getCodigoLoginAutor()).append("' ");
		buffer.append("textoObservacao").append("='")
				.append(getTextoObservacao()).append("' ");
		buffer.append("dataMesAjuste").append("='").append(getDataMesAjuste())
				.append("' ");
		buffer.append("dataCriacao").append("='").append(getDataCriacao())
				.append("' ");
		buffer.append("valorAjuste").append("='").append(getValorAjuste())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	/**
	 * Retorna o Balanço (valor da receita - valor do ajuste).
	 * 
	 * @return balanco
	 */
	public BigDecimal getBalanco() {
		return this.balanco;
	}

	/**
	 * @param balanco
	 *            the balanco to set
	 */
	public void setBalanco(final BigDecimal balanco) {
		this.balanco = balanco;
	}

	/**
	 * @return the ajusteReceitaPai
	 */
	public AjusteReceita getAjusteReceitaPai() {
		return ajusteReceitaPai;
	}

	/**
	 * @param ajusteReceitaPai
	 *            the ajusteReceitaPai to set
	 */
	public void setAjusteReceitaPai(AjusteReceita ajusteReceitaPai) {
		this.ajusteReceitaPai = ajusteReceitaPai;
	}

}
