/*
 * @(#) AlocacaoPeriodoOh.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela ALOCACAO_PERIODO_OH.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 08/01/2010 11:39:27
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "ALOCACAO_PERIODO_OH")
@NamedQueries({
    @NamedQuery(name = "AlocacaoPeriodoOh.findAll", query = "SELECT t FROM AlocacaoPeriodoOh t"),
    
    @NamedQuery(name = "AlocacaoPeriodoOh.findByPessoaAndMonthDate", 
            query = "SELECT apoh FROM AlocacaoPeriodoOh apoh"
                +   " WHERE apoh.alocacaoOverhead.pessoa.codigoPessoa = ? "
                +   " AND TRUNC(apoh.dataAlocPeriodoOh) = TRUNC(?)"
                +   " ORDER BY apoh.alocacaoOverhead.dataInicio, apoh.alocacaoOverhead.dataFim"),
                
    @NamedQuery(name = "AlocacaoPeriodoOh.findByPessoaAndBetweenDateMonth", 
            query = "SELECT apoh FROM AlocacaoPeriodoOh apoh"
                +   " WHERE apoh.alocacaoOverhead.pessoa.codigoPessoa = ? "
                +   " AND TRUNC(?) >= TRUNC(apoh.dataAlocPeriodoOh) "
                +   " AND TRUNC(?) <= TRUNC(apoh.dataAlocPeriodoOh)"),
                
    @NamedQuery(name = "AlocacaoPeriodoOh.findByAlocacaoOverhead", 
            query = "SELECT apoh FROM AlocacaoPeriodoOh apoh "
                +   " WHERE apoh.alocacaoOverhead.codigoAlocacaoOverhead = ? "
                +   " ORDER BY apoh.dataAlocPeriodoOh ASC "),

    @NamedQuery(name = "AlocacaoPeriodoOh.findByPessoaInAndDate",
            query = "SELECT apoh FROM AlocacaoPeriodoOh apoh"
                +   " WHERE apoh.alocacaoOverhead.pessoa.codigoPessoa in :peopleCodes "
                +   " AND TRUNC(apoh.dataAlocPeriodoOh) = TRUNC(:month)"
                +   " ORDER BY apoh.alocacaoOverhead.dataInicio, apoh.alocacaoOverhead.dataFim")
})
public class AlocacaoPeriodoOh implements java.io.Serializable {
    
    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    
    /** Constante para NamedQuery "AlocacaoPeriodoOh.findByPessoaAndMonthDate". */
    public static final String FIND_BY_PESSOA_AND_MONTH_DATE = 
        "AlocacaoPeriodoOh.findByPessoaAndMonthDate";
    
    /** Constante para NamedQuery "AlocacaoPeriodoOh.findByPessoaAndBetweenDateMonth". */
    public static final String FIND_BY_PESSOA_AND_BETWEEN_MONTH_DATE = 
        "AlocacaoPeriodoOh.findByPessoaAndBetweenDateMonth";
    
    /** Constante para NamedQuery "AlocacaoPeriodoOh.findByAlocacaoOverhead". */
    public static final String FIND_BY_ALOCACAO_OVERHEAD = 
        "AlocacaoPeriodoOh.findByAlocacaoOverhead";

    /** Constante para NamedQuery "AlocacaoPeriodoOh.findByPessoaAndMonthDate". */
    public static final String FIND_BY_PESSOA_IN_AND_MONTH =
            "AlocacaoPeriodoOh.findByPessoaInAndDate";
    
    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** Constante para NamedQuery "AlocacaoPeriodoOh.findAll". */
    public static final String FIND_ALL = "AlocacaoPeriodoOh.findAll";
    
    /**
     * Atributo gerado a partir da coluna ALPO_CD_ALOC_PERIODO_OH.
     */
    @Id
    @GeneratedValue(generator = "AlocacaoPeriodoOhSeq")
    @SequenceGenerator(name = "AlocacaoPeriodoOhSeq", 
            sequenceName = "SQ_ALPO_CD_ALOC_PERIODO_OH", allocationSize = 1)
    @Column(name = "ALPO_CD_ALOC_PERIODO_OH", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoAlocPeriodoOh;

    /**
     * Atributo gerado a partir da coluna ALOV_CD_ALOCACAO_OVERHEAD.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ALOV_CD_ALOCACAO_OVERHEAD", nullable = false)
    private AlocacaoOverhead alocacaoOverhead;

    /**
     * Atributo gerado a partir da coluna ALPO_DT_ALOC_PERIODO_OH.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "ALPO_DT_ALOC_PERIODO_OH", length = 7)
    private Date dataAlocPeriodoOh;

    /**
     * Atributo gerado a partir da coluna ALPO_PR_ALOC_PERIODO_OH.
     */

    @Column(name = "ALPO_PR_ALOC_PERIODO_OH", precision = 5)
    private BigDecimal percentualAlocPeriodoOh;

    /**
     * Construtor default.
     */
    public AlocacaoPeriodoOh() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoAlocPeriodoOh Valor do atributo codigoAlocPeriodoOh;
     * @param alocacaoOverhead Valor do atributo alocacaoOverhead;
     */
    public AlocacaoPeriodoOh(final Long codigoAlocPeriodoOh,
            final AlocacaoOverhead alocacaoOverhead) {
        this.codigoAlocPeriodoOh = codigoAlocPeriodoOh;
        this.alocacaoOverhead = alocacaoOverhead;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoAlocPeriodoOh Valor do atributo codigoAlocPeriodoOh;
     * @param alocacaoOverhead Valor do atributo alocacaoOverhead;
     * @param dataAlocPeriodoOh Valor do atributo dataAlocPeriodoOh;
     * @param percentualAlocPeriodoOh Valor do atributo percentualAlocPeriodoOh;
     */
    public AlocacaoPeriodoOh(final Long codigoAlocPeriodoOh,
            final AlocacaoOverhead alocacaoOverhead, final Date dataAlocPeriodoOh,
            final BigDecimal percentualAlocPeriodoOh) {
        this.codigoAlocPeriodoOh = codigoAlocPeriodoOh;
        this.alocacaoOverhead = alocacaoOverhead;
        this.dataAlocPeriodoOh = dataAlocPeriodoOh;
        this.percentualAlocPeriodoOh = percentualAlocPeriodoOh;
    }

    /**
     * Obtem o valor do atributo codigoAlocPeriodoOh.<BR>
     * Atributo gerado a partir da coluna ALPO_CD_ALOC_PERIODO_OH.
     * @return Valor do atributo codigoAlocPeriodoOh.
     */
    public Long getCodigoAlocPeriodoOh() {
        return this.codigoAlocPeriodoOh;
    }

    /**
     * Atualiza o valor do atributo codigoAlocPeriodoOh.<BR>
     * Atributo gerado a partir da coluna ALPO_CD_ALOC_PERIODO_OH.
     * @param codigoAlocPeriodoOh Novo valor para o atributo codigoAlocPeriodoOh.
     */
    public void setCodigoAlocPeriodoOh(final Long codigoAlocPeriodoOh) {
        this.codigoAlocPeriodoOh = codigoAlocPeriodoOh;
    }

    /**
     * Obtem o valor do atributo alocacaoOverhead.<BR>
     * Atributo gerado a partir da coluna ALOV_CD_ALOCACAO_OVERHEAD.
     * @return Valor do atributo alocacaoOverhead.
     */
    public AlocacaoOverhead getAlocacaoOverhead() {
        return this.alocacaoOverhead;
    }

    /**
     * Atualiza o valor do atributo alocacaoOverhead.<BR>
     * Atributo gerado a partir da coluna ALOV_CD_ALOCACAO_OVERHEAD.
     * @param alocacaoOverhead Novo valor para o atributo alocacaoOverhead.
     */
    public void setAlocacaoOverhead(final AlocacaoOverhead alocacaoOverhead) {
        this.alocacaoOverhead = alocacaoOverhead;
    }

    /**
     * Obtem o valor do atributo dataAlocPeriodoOh.<BR>
     * Atributo gerado a partir da coluna ALPO_DT_ALOC_PERIODO_OH.
     * @return Valor do atributo dataAlocPeriodoOh.
     */
    public Date getDataAlocPeriodoOh() {
        return this.dataAlocPeriodoOh;
    }

    /**
     * Atualiza o valor do atributo dataAlocPeriodoOh.<BR>
     * Atributo gerado a partir da coluna ALPO_DT_ALOC_PERIODO_OH.
     * @param dataAlocPeriodoOh Novo valor para o atributo dataAlocPeriodoOh.
     */
    public void setDataAlocPeriodoOh(final Date dataAlocPeriodoOh) {
        this.dataAlocPeriodoOh = dataAlocPeriodoOh;
    }

    /**
     * Obtem o valor do atributo percentualAlocPeriodoOh.<BR>
     * Atributo gerado a partir da coluna ALPO_PR_ALOC_PERIODO_OH.
     * @return Valor do atributo percentualAlocPeriodoOh.
     */
    public BigDecimal getPercentualAlocPeriodoOh() {
        return this.percentualAlocPeriodoOh;
    }

    /**
     * Atualiza o valor do atributo percentualAlocPeriodoOh.<BR>
     * Atributo gerado a partir da coluna ALPO_PR_ALOC_PERIODO_OH.
     * @param percentualAlocPeriodoOh Novo valor para o atributo percentualAlocPeriodoOh.
     */
    public void setPercentualAlocPeriodoOh(
            final BigDecimal percentualAlocPeriodoOh) {
        this.percentualAlocPeriodoOh = percentualAlocPeriodoOh;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoAlocPeriodoOh").append("='").append(
                getCodigoAlocPeriodoOh()).append("' ");
        buffer.append("alocacaoOverhead").append("='").append(
                getAlocacaoOverhead()).append("' ");
        buffer.append("dataAlocPeriodoOh").append("='").append(
                getDataAlocPeriodoOh()).append("' ");
        buffer.append("percentualAlocPeriodoOh").append("='").append(
                getPercentualAlocPeriodoOh()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
