/*
 * @(#) AlocacaoFoto.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela ALOCACAO_FOTO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 17/02/2011 17:51:17
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "ALOCACAO_FOTO")
@NamedQueries({
    @NamedQuery(name = "AlocacaoFoto.findAll", query = "SELECT t FROM AlocacaoFoto t")
})
public class AlocacaoFoto implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /** Lista de AlocacaoPeriodoFoto relacionado com a AlocacaoFoto corrente. */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "alocacaoFoto", cascade = CascadeType.ALL)
    private List<AlocacaoPeriodoFoto> alocacaoPeriodoFotos = new ArrayList<AlocacaoPeriodoFoto>(
            0);

    /**
     * Obtem o valor do atributo alocacaoPeriodoFotos.<BR>
     * 
     * @return Valor do atributo alocacaoPeriodoFotos.
     */
    public List<AlocacaoPeriodoFoto> getAlocacaoPeriodoFotos() {
        return this.alocacaoPeriodoFotos;
    }

    /**
     * Atualiza o valor do atributo alocacaoPeriodoFotos.<BR>
     * 
     * @param alocacaoPeriodoFotos
     *            Novo valor para o atributo alocacaoPeriodoFotos.
     */
    public void setAlocacaoPeriodoFotos(
            final List<AlocacaoPeriodoFoto> alocacaoPeriodoFotos) {
        this.alocacaoPeriodoFotos = alocacaoPeriodoFotos;
    }

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "AlocacaoFoto.findAll".
     */
    public static final String FIND_ALL = "AlocacaoFoto.findAll";

    /**
     * Atributo gerado a partir da coluna ALFO_CD_ALOC_FOTO.
     */
    @Id
    @GeneratedValue(generator = "AlocacaoFotoSeq")
    @SequenceGenerator(name = "AlocacaoFotoSeq", sequenceName = "SQ_ALFO_CD_ALOC_FOTO", allocationSize = 1)
    @Column(name = "ALFO_CD_ALOC_FOTO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoAlocFoto;

    /**
     * Atributo gerado a partir da coluna MAAF_CD_MAPA_ALOC_FOTO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MAAF_CD_MAPA_ALOC_FOTO", nullable = false)
    private MapaAlocacaoFoto mapaAlocacaoFoto;

    /**
     * Atributo gerado a partir da coluna ALFO_IN_STATUS_FOTO.
     */

    @Column(name = "ALFO_IN_STATUS_FOTO", length = 240)
    private String indicadorStatusFoto;

    /**
     * Atributo gerado a partir da coluna ALFO_CD_ALOCACAO.
     */

    @Column(name = "ALFO_CD_ALOCACAO", precision = 18, scale = 0)
    private Long codigoAlocacao;
    
    /**
     * Atributo gerado a partir da coluna ALFO_CD_MAPA_ALOCACAO.
     */

    @Column(name = "ALFO_CD_MAPA_ALOCACAO", precision = 18, scale = 0)
    private Long codigoMapaAlocacao;

    /**
     * Atributo gerado a partir da coluna ALFO_CD_PERFIL_VENDIDO.
     */

    @Column(name = "ALFO_CD_PERFIL_VENDIDO", precision = 18, scale = 0)
    private Long codigoPerfilVendido;
    
    /**
     * Atributo gerado a partir da coluna ALFO_CD_RECURSO.
     */

    @Column(name = "ALFO_CD_RECURSO", precision = 18, scale = 0)
    private Long codigoRecurso;
    
    /**
     * Atributo gerado a partir da coluna ALFO_CD_CIDADE_BASE.
     */

    @Column(name = "ALFO_CD_CIDADE_BASE", precision = 18, scale = 0)
    private Long codigoCidadeBase;

    /**
     * Atributo gerado a partir da coluna ALFO_VL_UR.
     */

    @Column(name = "ALFO_VL_UR", precision = 18, scale = 15)
    private BigDecimal valorUr;
    
    /**
     * Atributo gerado a partir da coluna ALFO_IN_ESTAGIO.
     */

    @Column(name = "ALFO_IN_ESTAGIO", length = 3)
    private String indicadorEstagio;

    /**
     * Atributo gerado a partir da coluna ALFO_DT_INICIO.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "ALFO_DT_INICIO", length = 7)
    private Date dataInicio;

    /**
     * Atributo gerado a partir da coluna ALFO_DT_FIM.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "ALFO_DT_FIM", length = 7)
    private Date dataFim;

    /**
     * Construtor default.
     */
    public AlocacaoFoto() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoAlocFoto
     *            Valor do atributo codigoAlocFoto;
     * @param mapaAlocacaoFoto
     *            Valor do atributo mapaAlocacaoFoto;
     */
    public AlocacaoFoto(final Long codigoAlocFoto,
            final MapaAlocacaoFoto mapaAlocacaoFoto) {
        this.codigoAlocFoto = codigoAlocFoto;
        this.mapaAlocacaoFoto = mapaAlocacaoFoto;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoAlocFoto
     *            Valor do atributo codigoAlocFoto;
     * @param mapaAlocacaoFoto
     *            Valor do atributo mapaAlocacaoFoto;
     * @param indicadorStatusFoto
     *            Valor do atributo indicadorStatusFoto;
     * @param codigoAlocacao
     *            Valor do atributo codigoAlocacao;
     * @param codigoPerfilVendido
     *            Valor do atributo codigoPerfilVendido;
     * @param valorUr
     *            Valor do atributo valorUr;
     * @param codigoRecurso
     *            Valor do atributo codigoRecurso;
     * @param codigoCidadeBase
     *            Valor do atributo codigoCidadeBase;
     * @param dataInicio
     *            Valor do atributo dataInicio;
     * @param dataFim
     *            Valor do atributo dataFim;
     * @param indicadorEstagio
     *            Valor do atributo mapaAlocacaoFoto;
     * @param codigoMapaAlocacao
     *            Valor do atributo codigoMapaAlocacao;
     * @param alocacaoPeriodoFotos
     *            Valor do atributo alocacaoPeriodoFotos;
     */
    public AlocacaoFoto(final Long codigoAlocFoto,
            final MapaAlocacaoFoto mapaAlocacaoFoto,
            final String indicadorStatusFoto, final Long codigoAlocacao,
            final Long codigoPerfilVendido, final BigDecimal valorUr,
            final Long codigoRecurso, final Long codigoCidadeBase,
            final Date dataInicio, final Date dataFim,
            final String indicadorEstagio, final Long codigoMapaAlocacao,
            final List<AlocacaoPeriodoFoto> alocacaoPeriodoFotos) {
        this.codigoAlocFoto = codigoAlocFoto;
        this.mapaAlocacaoFoto = mapaAlocacaoFoto;
        this.indicadorStatusFoto = indicadorStatusFoto;
        this.codigoAlocacao = codigoAlocacao;
        this.codigoPerfilVendido = codigoPerfilVendido;
        this.valorUr = valorUr;
        this.codigoRecurso = codigoRecurso;
        this.codigoCidadeBase = codigoCidadeBase;
        this.dataInicio = dataInicio;
        this.dataFim = dataFim;
        this.indicadorEstagio = indicadorEstagio;
        this.codigoMapaAlocacao = codigoMapaAlocacao;
        this.alocacaoPeriodoFotos = alocacaoPeriodoFotos;
    }

    /**
     * Obtem o valor do atributo codigoAlocFoto.<BR>
     * Atributo gerado a partir da coluna ALFO_CD_ALOC_FOTO.
     * 
     * @return Valor do atributo codigoAlocFoto.
     */
    public Long getCodigoAlocFoto() {
        return this.codigoAlocFoto;
    }

    /**
     * Atualiza o valor do atributo codigoAlocFoto.<BR>
     * Atributo gerado a partir da coluna ALFO_CD_ALOC_FOTO.
     * 
     * @param codigoAlocFoto
     *            Novo valor para o atributo codigoAlocFoto.
     */
    public void setCodigoAlocFoto(final Long codigoAlocFoto) {
        this.codigoAlocFoto = codigoAlocFoto;
    }

    /**
     * Obtem o valor do atributo mapaAlocacaoFoto.<BR>
     * Atributo gerado a partir da coluna MAAF_CD_MAPA_ALOC_FOTO.
     * 
     * @return Valor do atributo mapaAlocacaoFoto.
     */
    public MapaAlocacaoFoto getMapaAlocacaoFoto() {
        return this.mapaAlocacaoFoto;
    }

    /**
     * Atualiza o valor do atributo mapaAlocacaoFoto.<BR>
     * Atributo gerado a partir da coluna MAAF_CD_MAPA_ALOC_FOTO.
     * 
     * @param mapaAlocacaoFoto
     *            Novo valor para o atributo mapaAlocacaoFoto.
     */
    public void setMapaAlocacaoFoto(final MapaAlocacaoFoto mapaAlocacaoFoto) {
        this.mapaAlocacaoFoto = mapaAlocacaoFoto;
    }

    /**
     * Obtem o valor do atributo indicadorStatusFoto.<BR>
     * Atributo gerado a partir da coluna ALFO_IN_STATUS_FOTO.
     * 
     * @return Valor do atributo indicadorStatusFoto.
     */
    public String getIndicadorStatusFoto() {
        return this.indicadorStatusFoto;
    }

    /**
     * Atualiza o valor do atributo indicadorStatusFoto.<BR>
     * Atributo gerado a partir da coluna ALFO_IN_STATUS_FOTO.
     * 
     * @param indicadorStatusFoto
     *            Novo valor para o atributo indicadorStatusFoto.
     */
    public void setIndicadorStatusFoto(final String indicadorStatusFoto) {
        this.indicadorStatusFoto = indicadorStatusFoto;
    }

    /**
     * Obtem o valor do atributo codigoAlocacao.<BR>
     * Atributo gerado a partir da coluna ALFO_CD_ALOCACAO.
     * 
     * @return Valor do atributo codigoAlocacao.
     */
    public Long getCodigoAlocacao() {
        return this.codigoAlocacao;
    }

    /**
     * Atualiza o valor do atributo codigoAlocacao.<BR>
     * Atributo gerado a partir da coluna ALFO_CD_ALOCACAO.
     * 
     * @param codigoAlocacao
     *            Novo valor para o atributo codigoAlocacao.
     */
    public void setCodigoAlocacao(final Long codigoAlocacao) {
        this.codigoAlocacao = codigoAlocacao;
    }

    /**
     * Obtem o valor do atributo codigoPerfilVendido.<BR>
     * Atributo gerado a partir da coluna ALFO_CD_PERFIL_VENDIDO.
     * 
     * @return Valor do atributo codigoPerfilVendido.
     */
    public Long getCodigoPerfilVendido() {
        return this.codigoPerfilVendido;
    }

    /**
     * Atualiza o valor do atributo codigoPerfilVendido.<BR>
     * Atributo gerado a partir da coluna ALFO_CD_PERFIL_VENDIDO.
     * 
     * @param codigoPerfilVendido
     *            Novo valor para o atributo codigoPerfilVendido.
     */
    public void setCodigoPerfilVendido(final Long codigoPerfilVendido) {
        this.codigoPerfilVendido = codigoPerfilVendido;
    }

    /**
     * Obtem o valor do atributo valorUr.<BR>
     * Atributo gerado a partir da coluna ALFO_VL_UR.
     * 
     * @return Valor do atributo valorUr.
     */
    public BigDecimal getValorUr() {
        return this.valorUr;
    }

    /**
     * Atualiza o valor do atributo valorUr.<BR>
     * Atributo gerado a partir da coluna ALFO_VL_UR.
     * 
     * @param valorUr
     *            Novo valor para o atributo valorUr.
     */
    public void setValorUr(final BigDecimal valorUr) {
        this.valorUr = valorUr;
    }

    /**
     * Obtem o valor do atributo codigoRecurso.<BR>
     * Atributo gerado a partir da coluna ALFO_CD_RECURSO.
     * 
     * @return Valor do atributo codigoRecurso.
     */
    public Long getCodigoRecurso() {
        return this.codigoRecurso;
    }

    /**
     * Atualiza o valor do atributo codigoRecurso.<BR>
     * Atributo gerado a partir da coluna ALFO_CD_RECURSO.
     * 
     * @param codigoRecurso
     *            Novo valor para o atributo codigoRecurso.
     */
    public void setCodigoRecurso(final Long codigoRecurso) {
        this.codigoRecurso = codigoRecurso;
    }

    /**
     * Obtem o valor do atributo codigoCidadeBase.<BR>
     * Atributo gerado a partir da coluna ALFO_CD_CIDADE_BASE.
     * 
     * @return Valor do atributo codigoCidadeBase.
     */
    public Long getCodigoCidadeBase() {
        return this.codigoCidadeBase;
    }

    /**
     * Atualiza o valor do atributo codigoCidadeBase.<BR>
     * Atributo gerado a partir da coluna ALFO_CD_CIDADE_BASE.
     * 
     * @param codigoCidadeBase
     *            Novo valor para o atributo codigoCidadeBase.
     */
    public void setCodigoCidadeBase(final Long codigoCidadeBase) {
        this.codigoCidadeBase = codigoCidadeBase;
    }

    /**
     * Obtem o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna ALFO_DT_INICIO.
     * 
     * @return Valor do atributo dataInicio.
     */
    public Date getDataInicio() {
        return this.dataInicio;
    }

    /**
     * Atualiza o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna ALFO_DT_INICIO.
     * 
     * @param dataInicio
     *            Novo valor para o atributo dataInicio.
     */
    public void setDataInicio(final Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    /**
     * Obtem o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna ALFO_DT_FIM.
     * 
     * @return Valor do atributo dataFim.
     */
    public Date getDataFim() {
        return this.dataFim;
    }

    /**
     * Atualiza o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna ALFO_DT_FIM.
     * 
     * @param dataFim
     *            Novo valor para o atributo dataFim.
     */
    public void setDataFim(final Date dataFim) {
        this.dataFim = dataFim;
    }

    /**
     * Obtem o valor do atributo indicadorEstagio.<BR>
     * Atributo gerado a partir da coluna ALFO_IN_ESTAGIO.
     * 
     * @return Valor do atributo indicadorEstagio.
     */
    public String getIndicadorEstagio() {
        return this.indicadorEstagio;
    }

    /**
     * Atualiza o valor do atributo indicadorEstagio.<BR>
     * Atributo gerado a partir da coluna ALFO_IN_ESTAGIO.
     * 
     * @param indicadorEstagio
     *            Novo valor para o atributo indicadorEstagio.
     */
    public void setIndicadorEstagio(final String indicadorEstagio) {
        this.indicadorEstagio = indicadorEstagio;
    }

    /**
     * Obtem o valor do atributo codigoMapaAlocacao.<BR>
     * Atributo gerado a partir da coluna ALFO_CD_MAPA_ALOCACAO.
     * 
     * @return Valor do atributo codigoMapaAlocacao.
     */
    public Long getCodigoMapaAlocacao() {
        return this.codigoMapaAlocacao;
    }

    /**
     * Atualiza o valor do atributo codigoMapaAlocacao.<BR>
     * Atributo gerado a partir da coluna ALFO_CD_MAPA_ALOCACAO.
     * 
     * @param codigoMapaAlocacao
     *            Novo valor para o atributo codigoMapaAlocacao.
     */
    public void setCodigoMapaAlocacao(final Long codigoMapaAlocacao) {
        this.codigoMapaAlocacao = codigoMapaAlocacao;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoAlocFoto").append("='")
                .append(getCodigoAlocFoto()).append("' ");
        buffer.append("mapaAlocacaoFoto").append("='").append(
                getMapaAlocacaoFoto()).append("' ");
        buffer.append("indicadorStatusFoto").append("='").append(
                getIndicadorStatusFoto()).append("' ");
        buffer.append("codigoAlocacao").append("='")
                .append(getCodigoAlocacao()).append("' ");
        buffer.append("codigoPerfilVendido").append("='").append(
                getCodigoPerfilVendido()).append("' ");
        buffer.append("valorUr").append("='").append(getValorUr()).append("' ");
        buffer.append("codigoRecurso").append("='").append(getCodigoRecurso())
                .append("' ");
        buffer.append("codigoCidadeBase").append("='").append(
                getCodigoCidadeBase()).append("' ");
        buffer.append("dataInicio").append("='").append(getDataInicio())
                .append("' ");
        buffer.append("dataFim").append("='").append(getDataFim()).append("' ");
        buffer.append("indicadorEstagio").append("='").append(
                getIndicadorEstagio()).append("' ");
        buffer.append("codigoMapaAlocacao").append("='").append(
                getCodigoMapaAlocacao()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}