/*
 * @(#) Alocacao.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.*;

/**
 * Entity gerado a partir da tabela ALOCACAO. Relacao de Alocacao dos Recursos
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 12/08/2009 17:14:06
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "ALOCACAO")
@NamedQueries({
        @NamedQuery(name = "Alocacao.findAll", query = "SELECT t FROM Alocacao t"),

        @NamedQuery(name = "Alocacao.findByMapaAlocacao", query = "SELECT a FROM Alocacao a"
                + " WHERE a.mapaAlocacao.codigoMapaAlocacao = ?"
                + " ORDER BY a.recurso.indicadorTipoRecurso, a.recurso.codigoMnemonico "),

        @NamedQuery(name = "Alocacao.findByMapaAlocacaoAndPeriod", query = "SELECT a FROM Alocacao a"
                + " WHERE a.mapaAlocacao.codigoMapaAlocacao = ? "
                + "  AND EXISTS (SELECT alocacao.codigoAlocacao from Alocacao alocacao "
                + "               JOIN alocacao.alocacaoPeriodos ap "
                + "               WHERE alocacao.codigoAlocacao = a.codigoAlocacao "
                + "               AND TRUNC(ap.dataAlocacaoPeriodo) between TRUNC(?) AND TRUNC(?) "
                + "               AND ap.percentualAlocacaoPeriodo <> 0.0 )"
                + " ORDER BY a.recurso.indicadorTipoRecurso, a.recurso.codigoMnemonico "),

        @NamedQuery(name = "Alocacao.findByMapaAlocacaoAndRecursoAndPerfil", query = "SELECT a FROM Alocacao a"
                + " JOIN FETCH a.alocacaoPeriodos alocacaoPeriodo "
                + " WHERE a.mapaAlocacao.codigoMapaAlocacao = ? "
                + "  AND a.perfilVendido.codigoPerfilVendido = ? "
                + "  AND EXISTS (SELECT alocacao.codigoAlocacao from Alocacao alocacao "
                + "               JOIN alocacao.alocacaoPeriodos ap "
                + "               JOIN alocacao.recurso r "
                + "               WHERE alocacao.codigoAlocacao = a.codigoAlocacao "
                + "               AND alocacao.recurso.codigoRecurso = r.codigoRecurso "
                + "               AND r.codigoMnemonico = ? )"),
        @NamedQuery(name = "Alocacao.findVigentesByContratoPratica", query = "SELECT a FROM Alocacao a " +
                " JOIN FETCH a.alocacaoPeriodos ap " +
                " JOIN FETCH a.mapaAlocacao ma " +
                " JOIN FETCH ma.contratoPratica cp " +
                " WHERE cp.codigoContratoPratica = :contratoPraticaCode " +
                " AND TRUNC(ap.dataAlocacaoPeriodo, 'mm') > trunc(:closingDate, 'mm') " +
                " AND ap.percentualAlocacaoPeriodo > 0 " +
                " AND a.valorUr > 0")
})
public class Alocacao implements java.io.Serializable, Cloneable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    /** Valor do serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** Constante para NamedQuery "Alocacao.findAll". */
    public static final String FIND_ALL = "Alocacao.findAll";

    /** Constante para NamedQuery "Alocacao.findByMapaAlocacao". */
    public static final String FIND_BY_MAPA_ALOCACAO =
            "Alocacao.findByMapaAlocacao";

    /** Constante para NamedQuery "Alocacao.findByMapaAlocacaoAndPeriod". */
    public static final String FIND_BY_MAPA_ALOCACAO_AND_PERIOD =
            "Alocacao.findByMapaAlocacaoAndPeriod";

    /**
     * Constante para NamedQuery
     * "Alocacao.findByMapaAlocacaoAndRecursoAndPerfil".
     */
    public static final String FIND_BY_MAPA_ALOCACAO_AND_RECURSO_AND_PERFIL =
            "Alocacao.findByMapaAlocacaoAndRecursoAndPerfil";

    public static final String FIND_VIGENTES_BY_CONTRATO_PRATICA =
            "Alocacao.findVigentesByContratoPratica";

    /**
     * Atributo gerado a partir da coluna ALOC_DT_INICIO.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "ALOC_DT_INICIO", length = 7)
    private Date dataInicio;

    /**
     * Atributo gerado a partir da coluna ALOC_DT_FIM.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "ALOC_DT_FIM", length = 7)
    private Date dataFim;

    /**
     * Obtem o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna ALOC_DT_INICIO.
     * 
     * @return Valor do atributo dataInicio.
     */
    public Date getDataInicio() {
        return this.dataInicio;
    }

    /**
     * Atualiza o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna ALOC_DT_INICIO.
     * 
     * @param dataInicio
     *            Novo valor para o atributo dataInicio.
     */
    public void setDataInicio(final Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    /**
     * Obtem o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna ALOC_DT_FIM.
     * 
     * @return Valor do atributo dataFim.
     */
    public Date getDataFim() {
        return this.dataFim;
    }

    /**
     * Atualiza o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna ALOC_DT_FIM.
     * 
     * @param dataFim
     *            Novo valor para o atributo dataFim.
     */
    public void setDataFim(final Date dataFim) {
        this.dataFim = dataFim;
    }

    /** Lista de AlocacaoPeriodo relacionado com a Alocacao corrente. */
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "alocacao")
    private Set<AlocacaoPeriodo> alocacaoPeriodos =
            new HashSet<AlocacaoPeriodo>(0);

    /**
     * Obtem o valor do atributo alocacaoPeriodos.<BR>
     * 
     * @return Valor do atributo alocacaoPeriodos.
     */
    public Set<AlocacaoPeriodo> getAlocacaoPeriodos() {
        return this.alocacaoPeriodos;
    }

    /**
     * Atualiza o valor do atributo alocacaoPeriodos.<BR>
     * 
     * @param alocacaoPeriodos
     *            Novo valor para o atributo alocacaoPeriodos.
     */
    public void setAlocacaoPeriodos(final Set<AlocacaoPeriodo> alocacaoPeriodos) {
        this.alocacaoPeriodos = alocacaoPeriodos;
    }

    /**
     * Retorna o tamanho da lista de AlocacaoPeriodo.
     * 
     * @return size da lista de AlocacaoPeriodo
     */
    public Integer getAlocacaoPeriodosSize() {
        return this.alocacaoPeriodos.size();
    }

    /** Lista de Etiquetas relacionado com a Alocacao corrente. */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "alocacao", cascade = CascadeType.ALL)
    private List<EtiquetaAlocacao> etiquetaAlocacaos =
            new ArrayList<EtiquetaAlocacao>(0);

    /**
     * Obtem o valor do atributo etiquetaAlocacaos.<BR>
     * 
     * @return Valor do atributo etiquetaAlocacaos.
     */
    public List<EtiquetaAlocacao> getEtiquetaAlocacaos() {
        return this.etiquetaAlocacaos;
    }

    /**
     * Atualiza o valor do atributo etiquetaAlocacaos.<BR>
     * 
     * @param etiquetaAlocacaos
     *            Novo valor para o atributo etiquetaAlocacaos.
     */
    public void setEtiquetaAlocacaos(
            final List<EtiquetaAlocacao> etiquetaAlocacaos) {
        this.etiquetaAlocacaos = etiquetaAlocacaos;
    }

    /**
     * Realiza uma copia do objeto, porem com uma referencia diferente.
     * 
     * @return a cópia do Objeto
     */
    public Alocacao getClone() {
        try {
            return (Alocacao) super.clone();
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
            return null;
        }
    }

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Atributo gerado a partir da coluna ALOC_CD_ALOCACAO. Codigo da Alocacao
     */
    @Id
    @GeneratedValue(generator = "AlocacaoSeq")
    @SequenceGenerator(name = "AlocacaoSeq", sequenceName = "SQ_ALOC_CD_ALOCACAO", allocationSize = 1)
    @Column(name = "ALOC_CD_ALOCACAO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoAlocacao;

    /**
     * Atributo gerado a partir da coluna MAAL_CD_MAPA_ALOCACAO. Codigo do Mapa
     * de Alocacao
     */
    @Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "MAAL_CD_MAPA_ALOCACAO")
    private MapaAlocacao mapaAlocacao;

    /**
     * Atributo gerado a partir da coluna RECU_CD_RECURSO. Codigo do Recurso
     */
    @Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "RECU_CD_RECURSO")
    private Recurso recurso;

    /**
     * Atributo gerado a partir da coluna PEVE_CD_PERFIL_VENDIDO.
     */
    @Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PEVE_CD_PERFIL_VENDIDO", nullable = false)
    private PerfilVendido perfilVendido;

    /**
     * Atributo gerado a partir da coluna CIBA_CD_CIDADE_BASE.
     */
    @Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "CIBA_CD_CIDADE_BASE", nullable = false)
    private CidadeBase cidadeBase;

    /**
     * Atributo gerado a partir da coluna ALOC_IN_ESTAGIO.
     */
    @Audited
    @Column(name = "ALOC_IN_ESTAGIO", length = 3)
    private String indicadorEstagio;

    /**
     * Atributo gerado a partir da coluna ALOC_VL_UR.
     */
    @Audited
    @Column(name = "ALOC_VL_UR", precision = 5, scale = 2)
    private BigDecimal valorUr;

    /**
     * Construtor default.
     */
    public Alocacao() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoAlocacao
     *            Valor do atributo codigoAlocacao;
     * @param perfilVendido
     *            Valor do atributo perfilVendido;
     * @param cidadeBase
     *            Valor do atributo cidadeBase;
     */
    public Alocacao(final Long codigoAlocacao,
            final PerfilVendido perfilVendido, final CidadeBase cidadeBase) {
        this.codigoAlocacao = codigoAlocacao;
        this.perfilVendido = perfilVendido;
        this.cidadeBase = cidadeBase;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoAlocacao
     *            Valor do atributo codigoAlocacao;
     * @param mapaAlocacao
     *            Valor do atributo mapaAlocacao;
     * @param recurso
     *            Valor do atributo recurso;
     * @param perfilVendido
     *            Valor do atributo perfilVendido;
     * @param cidadeBase
     *            Valor do atributo cidadeBase;
     * @param alocacaoPeriodos
     *            Valor do atributo alocacaoPeriodos;
     * @param indicadorEstagio
     *            Valor do atributo indicadorEstagio;
     * @param valorUr
     *            Valor do atributo valorUr;
     * @param etiquetaAlocacaos
     *            Valor do atributo etiquetaAlocacaos;
     */
    public Alocacao(final Long codigoAlocacao, final MapaAlocacao mapaAlocacao,
            final Recurso recurso, final PerfilVendido perfilVendido,
            final CidadeBase cidadeBase, final String indicadorEstagio,
            final Set<AlocacaoPeriodo> alocacaoPeriodos,
            final BigDecimal valorUr,
            final List<EtiquetaAlocacao> etiquetaAlocacaos) {
        this.codigoAlocacao = codigoAlocacao;
        this.mapaAlocacao = mapaAlocacao;
        this.recurso = recurso;
        this.perfilVendido = perfilVendido;
        this.cidadeBase = cidadeBase;
        this.indicadorEstagio = indicadorEstagio;
        this.alocacaoPeriodos = alocacaoPeriodos;
        this.valorUr = valorUr;
        this.etiquetaAlocacaos = etiquetaAlocacaos;
    }

    /**
     * Obtem o valor do atributo codigoAlocacao.<BR>
     * Atributo gerado a partir da coluna ALOC_CD_ALOCACAO. Codigo da Alocacao
     * 
     * @return Valor do atributo codigoAlocacao.
     */
    public Long getCodigoAlocacao() {
        return this.codigoAlocacao;
    }

    /**
     * Atualiza o valor do atributo codigoAlocacao.<BR>
     * Atributo gerado a partir da coluna ALOC_CD_ALOCACAO. Codigo da Alocacao
     * 
     * @param codigoAlocacao
     *            Novo valor para o atributo codigoAlocacao.
     */
    public void setCodigoAlocacao(final Long codigoAlocacao) {
        this.codigoAlocacao = codigoAlocacao;
    }

    /**
     * Obtem o valor do atributo mapaAlocacao.<BR>
     * Atributo gerado a partir da coluna MAAL_CD_MAPA_ALOCACAO. Codigo do Mapa
     * de Alocacao
     * 
     * @return Valor do atributo mapaAlocacao.
     */
    public MapaAlocacao getMapaAlocacao() {
        return this.mapaAlocacao;
    }

    /**
     * Atualiza o valor do atributo mapaAlocacao.<BR>
     * Atributo gerado a partir da coluna MAAL_CD_MAPA_ALOCACAO. Codigo do Mapa
     * de Alocacao
     * 
     * @param mapaAlocacao
     *            Novo valor para o atributo mapaAlocacao.
     */
    public void setMapaAlocacao(final MapaAlocacao mapaAlocacao) {
        this.mapaAlocacao = mapaAlocacao;
    }

    /**
     * Obtem o valor do atributo recurso.<BR>
     * Atributo gerado a partir da coluna RECU_CD_RECURSO. Codigo do Recurso
     * 
     * @return Valor do atributo recurso.
     */
    public Recurso getRecurso() {
        return this.recurso;
    }

    /**
     * Atualiza o valor do atributo recurso.<BR>
     * Atributo gerado a partir da coluna RECU_CD_RECURSO. Codigo do Recurso
     * 
     * @param recurso
     *            Novo valor para o atributo recurso.
     */
    public void setRecurso(final Recurso recurso) {
        this.recurso = recurso;
    }

    /**
     * Obtem o valor do atributo perfilVendido.<BR>
     * Atributo gerado a partir da coluna PEVE_CD_PERFIL_VENDIDO.
     * 
     * @return Valor do atributo perfilVendido.
     */
    public PerfilVendido getPerfilVendido() {
        return this.perfilVendido;
    }

    /**
     * Atualiza o valor do atributo perfilVendido.<BR>
     * Atributo gerado a partir da coluna PEVE_CD_PERFIL_VENDIDO.
     * 
     * @param perfilVendido
     *            Novo valor para o atributo perfilVendido.
     */
    public void setPerfilVendido(final PerfilVendido perfilVendido) {
        this.perfilVendido = perfilVendido;
    }

    /**
     * Obtem o valor do atributo cidadeBase.<BR>
     * Atributo gerado a partir da coluna CIBA_CD_CIDADE_BASE.
     * 
     * @return Valor do atributo cidadeBase.
     */
    public CidadeBase getCidadeBase() {
        return this.cidadeBase;
    }

    /**
     * Atualiza o valor do atributo cidadeBase.<BR>
     * Atributo gerado a partir da coluna CIBA_CD_CIDADE_BASE.
     * 
     * @param cidadeBase
     *            Novo valor para o atributo cidadeBase.
     */
    public void setCidadeBase(final CidadeBase cidadeBase) {
        this.cidadeBase = cidadeBase;
    }

    /**
     * Obtem o valor do atributo indicadorEstagio.<BR>
     * Atributo gerado a partir da coluna ALOC_IN_ESTAGIO.
     * 
     * @return Valor do atributo indicadorEstagio.
     */
    public String getIndicadorEstagio() {
        return this.indicadorEstagio;
    }

    /**
     * Atualiza o valor do atributo indicadorEstagio.<BR>
     * Atributo gerado a partir da coluna ALOC_IN_ESTAGIO.
     * 
     * @param indicadorEstagio
     *            Novo valor para o atributo indicadorEstagio.
     */
    public void setIndicadorEstagio(final String indicadorEstagio) {
        this.indicadorEstagio = indicadorEstagio;
    }

    /**
     * Obtem o valor do atributo valorUr.<BR>
     * Atributo gerado a partir da coluna ALOC_VL_UR.
     * 
     * @return Valor do atributo valorUr.
     */
    public BigDecimal getValorUr() {
        return this.valorUr;
    }

    /**
     * Atualiza o valor do atributo valorUr.<BR>
     * Atributo gerado a partir da coluna ALOC_VL_UR.
     * 
     * @param valorUr
     *            Novo valor para o atributo valorUr.
     */
    public void setValorUr(final BigDecimal valorUr) {
        this.valorUr = valorUr;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoAlocacao").append("='")
                .append(getCodigoAlocacao()).append("' ");
        buffer.append("mapaAlocacao").append("='").append(getMapaAlocacao())
                .append("' ");
        buffer.append("recurso").append("='").append(getRecurso()).append("' ");

        buffer.append("cidadeBase").append("='").append(getCidadeBase())
                .append("' ");
        buffer.append("indicadorEstagio").append("='").append(
                getIndicadorEstagio()).append("' ");
        buffer.append("valorUr").append("='").append(getValorUr()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
