/*
 * @(#) ApropriacaoHoraExtra.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.jsefa.csv.annotation.CsvDataType;
import org.jsefa.csv.annotation.CsvField;

import com.ciandt.pms.csv.util.CsvBigDecimalConverter;
import com.ciandt.pms.csv.util.CsvDateConverter;

/**
 * Entity gerado a partir da tabela APROPRIACAO_HORA_EXTRA.
 * 
 * @author Generated by Hibernate Tools 3.6.0
 * @since 22/10/2013 11:34:48
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "APROPRIACAO_HORA_EXTRA", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PESS_CD_PESSOA", "APHE_DT_MES" }))
@NamedQueries({
		@NamedQuery(name = "ApropriacaoHoraExtra.findAll", query = "SELECT t FROM ApropriacaoHoraExtra t"),

		@NamedQuery(name = "ApropriacaoHoraExtra.existsApropriacaoHoraExtra", query = "SELECT aphe FROM ApropriacaoHoraExtra aphe "
				+ "WHERE aphe.pessoa.codigoLogin = :codigoLogin "
				+ "  AND TRUNC(aphe.dataMes,'MM') = TRUNC(:dataMes,'MM') "),

		@NamedQuery(name = "ApropriacaoHoraExtra.findByData", query = "SELECT aphe FROM ApropriacaoHoraExtra aphe "
				+ "WHERE to_char(aphe.dataMes, 'MM/yyyy') = :dataFechamento "
				+ "ORDER BY aphe.pessoa.nomePessoa ASC "),

		@NamedQuery(name = "ApropriacaoHoraExtra.findByDataAndCodigoPessoa", query = "SELECT aphe FROM ApropriacaoHoraExtra aphe "
				+ "WHERE to_char(aphe.dataMes, 'MM/yyyy') = :dataFechamento "
				+ "AND (aphe.pessoa.codigoPessoa = :codigoPessoa OR :codigoPessoa = 0l)"
				+ "ORDER BY aphe.pessoa.nomePessoa ASC ") })
@CsvDataType
public class ApropriacaoHoraExtra implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "ApropriacaoHoraExtra.findAll".
	 */
	public static final String FIND_ALL = "ApropriacaoHoraExtra.findAll";

	/**
	 * Constante para NamedQuery
	 * "ApropriacaoHoraExtra.existsApropriacaoPlantao".
	 */
	public static final String EXISTS_APROPRIACAO_HORA_EXTRA = "ApropriacaoHoraExtra.existsApropriacaoHoraExtra";

	/**
	 * Constante para NamedQuery "ApropriacaoHoraExtra.findByData".
	 */
	public static final String FIND_BY_DATA = "ApropriacaoHoraExtra.findByData";

	/**
	 * Constante para NamedQuery
	 * "ApropriacaoHoraExtra.findByDataAndCodigoPessoa".
	 */
	public static final String FIND_BY_DATA_E_PESSOA = "ApropriacaoHoraExtra.findByDataAndCodigoPessoa";

	/**
	 * Atributo gerado a partir da coluna APHE_CD_APROPRIACAO_HORA_EXTRA.
	 */
	@Id
	@GeneratedValue(generator = "ApropriacaoHoraExtraSeq")
	@SequenceGenerator(name = "ApropriacaoHoraExtraSeq", sequenceName = "SQ_APHE_CD_APROP_HORA_EXTRA", allocationSize = 1)
	@Column(name = "APHE_CD_APROPRIACAO_HORA_EXTRA", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoApropriacaoHoraExtra;

	/**
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PESS_CD_PESSOA", nullable = false)
	private Pessoa pessoa;

	/**
	 * Atributo gerado a partir da coluna UPAR_CD_UPLOAD_ARQUIVO.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPAR_CD_UPLOAD_ARQUIVO")
	private UploadArquivo uploadArquivo;

	/**
	 * Atributo transiente que contem o login da pessoa.
	 */
	@Transient
	@CsvField(pos = 0, required = true)
	private String login;

	/**
	 * Atributo transient
	 */
	@Transient
	@CsvField(pos = 3, required = true)
	private String siglaMoeda;
	
	/**
	 * Atributo gerado a partir da coluna APHE_DT_MES.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "APHE_DT_MES", length = 7, nullable = false)
	@CsvField(pos = 1, converterType = CsvDateConverter.class)
	private Date dataMes;

	/**
	 * Atributo gerado a partir da coluna APHE_VL_HORA_EXTRA.
	 */

	@Column(name = "APHE_VL_HORA_EXTRA", nullable = false, precision = 18, scale = 4)
	@CsvField(pos = 2, converterType = CsvBigDecimalConverter.class)
	private BigDecimal valorHoraExtra;
	

	/**
	 * Atributo gerado a partir da coluna MOED_CD_MOEDA.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOED_CD_MOEDA", nullable = false)
	private Moeda moeda;

	/**
	 * Atributo gerado a partir da coluna APHE_CD_AUTOR_ATUALIZACAO.
	 */
	@Column(name = "APHE_CD_AUTOR_ATUALIZACAO", length = 20)
	private String codigoAutorAtualizacao;

	/**
	 * Atributo gerado a partir da coluna APHE_DT_ATUALIZACAO.
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "APHE_DT_ATUALIZACAO", length = 7)
	private Date dataAtualizacao;

	/**
	 * Construtor default.
	 */
	public ApropriacaoHoraExtra() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoApropriacaoHoraExtra
	 *            Valor do atributo codigoApropriacaoHoraExtra;
	 * @param pessoa
	 *            Valor do atributo pessoa;
	 * @param moeda
	 *            Valor do atributo moeda;
	 * @param dataMes
	 *            Valor do atributo dataMes;
	 * @param valorHoraExtra
	 *            Valor do atributo valorHoraExtra;
	 */
	public ApropriacaoHoraExtra(Long codigoApropriacaoHoraExtra, Pessoa pessoa,
			Moeda moeda, Date dataMes, BigDecimal valorHoraExtra) {
		this.codigoApropriacaoHoraExtra = codigoApropriacaoHoraExtra;
		this.pessoa = pessoa;
		this.moeda = moeda;
		this.dataMes = dataMes;
		this.valorHoraExtra = valorHoraExtra;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoApropriacaoHoraExtra
	 *            Valor do atributo codigoApropriacaoHoraExtra;
	 * @param pessoa
	 *            Valor do atributo pessoa;
	 * @param moeda
	 *            Valor do atributo moeda;
	 * @param dataMes
	 *            Valor do atributo dataMes;
	 * @param valorHoraExtra
	 *            Valor do atributo valorHoraExtra;
	 */
	public ApropriacaoHoraExtra(Long codigoApropriacaoHoraExtra, Pessoa pessoa,
			Moeda moeda, UploadArquivo uploadArquivo, Date dataMes,
			BigDecimal valorHoraExtra, String codigoAutorAtualizacao,
			Date dataAtualizacao) {
		this.codigoApropriacaoHoraExtra = codigoApropriacaoHoraExtra;
		this.pessoa = pessoa;
		this.moeda = moeda;
		this.uploadArquivo = uploadArquivo;
		this.dataMes = dataMes;
		this.valorHoraExtra = valorHoraExtra;
		this.codigoAutorAtualizacao = codigoAutorAtualizacao;
		this.dataAtualizacao = dataAtualizacao;
	}

	/**
	 * Obtem o valor do atributo codigoApropriacaoHoraExtra.<BR>
	 * Atributo gerado a partir da coluna APHE_CD_APROPRIACAO_HORA_EXTRA.
	 * 
	 * @return Valor do atributo codigoApropriacaoHoraExtra.
	 */
	public Long getCodigoApropriacaoHoraExtra() {
		return this.codigoApropriacaoHoraExtra;
	}

	/**
	 * Atualiza o valor do atributo codigoApropriacaoHoraExtra.<BR>
	 * Atributo gerado a partir da coluna APHE_CD_APROPRIACAO_HORA_EXTRA.
	 * 
	 * @param codigoApropriacaoHoraExtra
	 *            Novo valor para o atributo codigoApropriacaoHoraExtra.
	 */
	public void setCodigoApropriacaoHoraExtra(Long codigoApropriacaoHoraExtra) {
		this.codigoApropriacaoHoraExtra = codigoApropriacaoHoraExtra;
	}

	/**
	 * Obtem o valor do atributo pessoa.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 * 
	 * @return Valor do atributo pessoa.
	 */
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	/**
	 * Atualiza o valor do atributo pessoa.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 * 
	 * @param pessoa
	 *            Novo valor para o atributo pessoa.
	 */
	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	/**
	 * Obtem o valor do atributo uploadArquivo.<BR>
	 * Atributo gerado a partir da coluna UPAR_CD_UPLOAD_ARQUIVO.
	 * 
	 * @return Valor do atributo uploadArquivo.
	 */
	public UploadArquivo getUploadArquivo() {
		return this.uploadArquivo;
	}

	/**
	 * Atualiza o valor do atributo uploadArquivo.<BR>
	 * Atributo gerado a partir da coluna UPAR_CD_UPLOAD_ARQUIVO.
	 * 
	 * @param uploadArquivo
	 *            Novo valor para o atributo uploadArquivo.
	 */
	public void setUploadArquivo(UploadArquivo uploadArquivo) {
		this.uploadArquivo = uploadArquivo;
	}

	/**
	 * Obtem o valor do atributo dataMes.<BR>
	 * Atributo gerado a partir da coluna APHE_DT_MES.
	 * 
	 * @return Valor do atributo dataMes.
	 */
	public Date getDataMes() {
		return this.dataMes;
	}

	/**
	 * Atualiza o valor do atributo dataMes.<BR>
	 * Atributo gerado a partir da coluna APHE_DT_MES.
	 * 
	 * @param dataMes
	 *            Novo valor para o atributo dataMes.
	 */
	public void setDataMes(Date dataMes) {
		this.dataMes = dataMes;
	}

	/**
	 * Obtem o valor do atributo valorHoraExtra.<BR>
	 * Atributo gerado a partir da coluna APHE_VL_HORA_EXTRA.
	 * 
	 * @return Valor do atributo valorHoraExtra.
	 */
	public BigDecimal getValorHoraExtra() {
		return this.valorHoraExtra;
	}

	/**
	 * Atualiza o valor do atributo valorHoraExtra.<BR>
	 * Atributo gerado a partir da coluna APHE_VL_HORA_EXTRA.
	 * 
	 * @param valorHoraExtra
	 *            Novo valor para o atributo valorHoraExtra.
	 */
	public void setValorHoraExtra(BigDecimal valorHoraExtra) {
		this.valorHoraExtra = valorHoraExtra;
	}

	/**
	 * Obtem o valor do atributo moeda.<BR>
	 * Atributo gerado a partir da coluna MOED_CD_MOEDA.
	 * 
	 * @return Valor do atributo moeda.
	 */
	public Moeda getMoeda() {
		return this.moeda;
	}

	/**
	 * Atualiza o valor do atributo moeda.<BR>
	 * Atributo gerado a partir da coluna MOED_CD_MOEDA.
	 * 
	 * @param moeda
	 *            Novo valor para o atributo moeda.
	 */
	public void setMoeda(Moeda moeda) {
		this.moeda = moeda;
	}

	/**
	 * Obtem o valor do atributo codigoAutorAtualizacao.<BR>
	 * Atributo gerado a partir da coluna APHE_CD_AUTOR_ATUALIZACAO.
	 * 
	 * @return Valor do atributo codigoAutorAtualizacao.
	 */
	public String getCodigoAutorAtualizacao() {
		return this.codigoAutorAtualizacao;
	}

	/**
	 * Atualiza o valor do atributo codigoAutorAtualizacao.<BR>
	 * Atributo gerado a partir da coluna APHE_CD_AUTOR_ATUALIZACAO.
	 * 
	 * @param codigoAutorAtualizacao
	 *            Novo valor para o atributo codigoAutorAtualizacao.
	 */
	public void setCodigoAutorAtualizacao(String codigoAutorAtualizacao) {
		this.codigoAutorAtualizacao = codigoAutorAtualizacao;
	}

	/**
	 * Obtem o valor do atributo dataAtualizacao.<BR>
	 * Atributo gerado a partir da coluna APHE_DT_ATUALIZACAO.
	 * 
	 * @return Valor do atributo dataAtualizacao.
	 */
	public Date getDataAtualizacao() {
		return this.dataAtualizacao;
	}

	/**
	 * Atualiza o valor do atributo dataAtualizacao.<BR>
	 * Atributo gerado a partir da coluna APHE_DT_ATUALIZACAO.
	 * 
	 * @param dataAtualizacao
	 *            Novo valor para o atributo dataAtualizacao.
	 */
	public void setDataAtualizacao(Date dataAtualizacao) {
		this.dataAtualizacao = dataAtualizacao;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoApropriacaoHoraExtra").append("='")
				.append(getCodigoApropriacaoHoraExtra()).append("' ");
		buffer.append("pessoa").append("='").append(getPessoa()).append("' ");
		buffer.append("moeda").append("='").append(getMoeda()).append("' ");
		buffer.append("uploadArquivo").append("='").append(getUploadArquivo())
				.append("' ");
		buffer.append("dataMes").append("='").append(getDataMes()).append("' ");
		buffer.append("valorHoraExtra").append("='")
				.append(getValorHoraExtra()).append("' ");
		buffer.append("codigoAutorAtualizacao").append("='")
				.append(getCodigoAutorAtualizacao()).append("' ");
		buffer.append("dataAtualizacao").append("='")
				.append(getDataAtualizacao()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	/**
	 * @param login
	 *            the login to set
	 */
	public void setLogin(final String login) {
		this.login = login;
	}

	/**
	 * @return the login
	 */
	public String getLogin() {
		if (login == null && pessoa != null) {
			return pessoa.getCodigoLogin();
		}

		return login;
	}

	/**
	 * @return the siglaMoeda
	 */
	public String getSiglaMoeda() {
		return siglaMoeda;
	}

	/**
	 * @param siglaMoeda the siglaMoeda to set
	 */
	public void setSiglaMoeda(String siglaMoeda) {
		this.siglaMoeda = siglaMoeda;
	}
}