/*
 * @(#) ApropriacaoPlantao.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.jsefa.csv.annotation.CsvDataType;
import org.jsefa.csv.annotation.CsvField;

import com.ciandt.pms.csv.util.CsvBigDecimalConverter;
import com.ciandt.pms.csv.util.CsvDateConverter;

/**
 * Entity gerado a partir da tabela APROPRIACAO_PLANTAO.
 * 
 * @author Generated by Hibernate Tools 3.6.0
 * @since 22/10/2013 11:34:48
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "APROPRIACAO_PLANTAO", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PESS_CD_PESSOA", "APPL_DT_MES" }))
@NamedQueries({
		@NamedQuery(name = "ApropriacaoPlantao.findAll", query = "SELECT t FROM ApropriacaoPlantao t"),

		@NamedQuery(name = "ApropriacaoPlantao.existsApropriacaoPlantao", query = "SELECT appl FROM ApropriacaoPlantao appl "
				+ "WHERE appl.pessoa.codigoLogin = :codigoLogin "
				+ "  AND TRUNC(appl.dataMes,'MM') = TRUNC(:dataMes,'MM') "),

		@NamedQuery(name = "ApropriacaoPlantao.findByData", query = "SELECT appl FROM ApropriacaoPlantao appl "
				+ "WHERE to_char(appl.dataMes, 'MM/yyyy') = :dataFechamento "
				+ "ORDER BY appl.pessoa.nomePessoa ASC "),

		@NamedQuery(name = "ApropriacaoPlantao.findByDataAndCodigoPessoa", query = "SELECT appl FROM ApropriacaoPlantao appl "
				+ "WHERE to_char(appl.dataMes, 'MM/yyyy') = :dataFechamento "
				+ "AND (appl.pessoa.codigoPessoa = :codigoPessoa OR :codigoPessoa = 0L)"
				+ "ORDER BY appl.pessoa.nomePessoa ASC ")

})
@CsvDataType
public class ApropriacaoPlantao implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "ApropriacaoPlantao.findAll".
	 */
	public static final String FIND_ALL = "ApropriacaoPlantao.findAll";

	/**
	 * Constante para NamedQuery "ApropriacaoPlantao.existsApropriacaoPlantao".
	 */
	public static final String EXISTS_APROPRIACAO_PLANTAO = "ApropriacaoPlantao.existsApropriacaoPlantao";

	/**
	 * Constante para NamedQuery "ApropriacaoPlantao.findByData".
	 */
	public static final String FIND_BY_DATA = "ApropriacaoPlantao.findByData";

	/**
	 * Constante para NamedQuery "ApropriacaoPlantao.findByDataAndCodigoPessoa".
	 */
	public static final String FIND_BY_DATA_E_PESSOA = "ApropriacaoPlantao.findByDataAndCodigoPessoa";

	/**
	 * Atributo gerado a partir da coluna APPL_CD_APROPRIACAO_PLANTAO.
	 */
	@Id
	@GeneratedValue(generator = "ApropriacaoPlantaoSeq")
	@SequenceGenerator(name = "ApropriacaoPlantaoSeq", sequenceName = "SQ_APPL_CD_APROP_PLANTAO", allocationSize = 1)
	@Column(name = "APPL_CD_APROPRIACAO_PLANTAO", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoApropriacaoPlantao;

	/**
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PESS_CD_PESSOA", nullable = false)
	private Pessoa pessoa;

	/**
	 * Atributo gerado a partir da coluna UPAR_CD_UPLOAD_ARQUIVO.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPAR_CD_UPLOAD_ARQUIVO")
	private UploadArquivo uploadArquivo;

	/**
	 * Atributo transiente que contem o login da pessoa.
	 */
	@Transient
	@CsvField(pos = 0, required = true)
	private String login;

	/**
	 * Atributo transient
	 */
	@Transient
	@CsvField(pos = 3, required = true)
	private String siglaMoeda;

	/**
	 * Atributo gerado a partir da coluna APPL_DT_MES.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "APPL_DT_MES", nullable = false, length = 7)
	@CsvField(pos = 1, converterType = CsvDateConverter.class, required = true)
	private Date dataMes;

	/**
	 * Atributo gerado a partir da coluna APPL_VL_PLANTAO.
	 */
	@Column(name = "APPL_VL_PLANTAO", nullable = false, precision = 18, scale = 4)
	@CsvField(pos = 2, converterType = CsvBigDecimalConverter.class, required = true)
	private BigDecimal valorPlantao;

	/**
	 * Atributo gerado a partir da coluna MOED_CD_MOEDA.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOED_CD_MOEDA", nullable = false)
	private Moeda moeda;

	/**
	 * Atributo gerado a partir da coluna APPL_CD_AUTOR_ATUALIZACAO.
	 */
	@Column(name = "APPL_CD_AUTOR_ATUALIZACAO", length = 20)
	private String codigoAutorAtualizacao;

	/**
	 * Atributo gerado a partir da coluna APPL_DT_ATUALIZACAO.
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "APPL_DT_ATUALIZACAO", length = 7)
	private Date dataAtualizacao;

	/**
	 * Construtor default.
	 */
	public ApropriacaoPlantao() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoApropriacaoPlantao
	 *            Valor do atributo codigoApropriacaoPlantao;
	 * @param pessoa
	 *            Valor do atributo pessoa;
	 * @param moeda
	 *            Valor do atributo moeda;
	 * @param dataMes
	 *            Valor do atributo dataMes;
	 * @param valorPlantao
	 *            Valor do atributo valorPlantao;
	 */
	public ApropriacaoPlantao(Long codigoApropriacaoPlantao, Pessoa pessoa,
			Moeda moeda, Date dataMes, BigDecimal valorPlantao) {
		this.codigoApropriacaoPlantao = codigoApropriacaoPlantao;
		this.pessoa = pessoa;
		this.moeda = moeda;
		this.dataMes = dataMes;
		this.valorPlantao = valorPlantao;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoApropriacaoPlantao
	 *            Valor do atributo codigoApropriacaoPlantao;
	 * @param pessoa
	 *            Valor do atributo pessoa;
	 * @param moeda
	 *            Valor do atributo moeda;
	 * @param dataMes
	 *            Valor do atributo dataMes;
	 * @param valorPlantao
	 *            Valor do atributo valorPlantao;
	 */
	public ApropriacaoPlantao(Long codigoApropriacaoPlantao, Pessoa pessoa,
			Moeda moeda, UploadArquivo uploadArquivo, Date dataMes,
			BigDecimal valorPlantao, String codigoAutorAtualizacao,
			Date dataAtualizacao) {
		this.codigoApropriacaoPlantao = codigoApropriacaoPlantao;
		this.pessoa = pessoa;
		this.moeda = moeda;
		this.uploadArquivo = uploadArquivo;
		this.dataMes = dataMes;
		this.valorPlantao = valorPlantao;
		this.codigoAutorAtualizacao = codigoAutorAtualizacao;
		this.dataAtualizacao = dataAtualizacao;
	}

	/**
	 * Obtem o valor do atributo codigoApropriacaoPlantao.<BR>
	 * Atributo gerado a partir da coluna APPL_CD_APROPRIACAO_PLANTAO.
	 * 
	 * @return Valor do atributo codigoApropriacaoPlantao.
	 */
	public Long getCodigoApropriacaoPlantao() {
		return this.codigoApropriacaoPlantao;
	}

	/**
	 * Atualiza o valor do atributo codigoApropriacaoPlantao.<BR>
	 * Atributo gerado a partir da coluna APPL_CD_APROPRIACAO_PLANTAO.
	 * 
	 * @param codigoApropriacaoPlantao
	 *            Novo valor para o atributo codigoApropriacaoPlantao.
	 */
	public void setCodigoApropriacaoPlantao(Long codigoApropriacaoPlantao) {
		this.codigoApropriacaoPlantao = codigoApropriacaoPlantao;
	}

	/**
	 * Obtem o valor do atributo pessoa.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 * 
	 * @return Valor do atributo pessoa.
	 */
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	/**
	 * Atualiza o valor do atributo pessoa.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 * 
	 * @param pessoa
	 *            Novo valor para o atributo pessoa.
	 */
	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	/**
	 * Obtem o valor do atributo uploadArquivo.<BR>
	 * Atributo gerado a partir da coluna UPAR_CD_UPLOAD_ARQUIVO.
	 * 
	 * @return Valor do atributo uploadArquivo.
	 */
	public UploadArquivo getUploadArquivo() {
		return this.uploadArquivo;
	}

	/**
	 * Atualiza o valor do atributo uploadArquivo.<BR>
	 * Atributo gerado a partir da coluna UPAR_CD_UPLOAD_ARQUIVO.
	 * 
	 * @param uploadArquivo
	 *            Novo valor para o atributo uploadArquivo.
	 */
	public void setUploadArquivo(UploadArquivo uploadArquivo) {
		this.uploadArquivo = uploadArquivo;
	}

	/**
	 * Obtem o valor do atributo dataMes.<BR>
	 * Atributo gerado a partir da coluna APPL_DT_MES.
	 * 
	 * @return Valor do atributo dataMes.
	 */
	public Date getDataMes() {
		return this.dataMes;
	}

	/**
	 * Atualiza o valor do atributo dataMes.<BR>
	 * Atributo gerado a partir da coluna APPL_DT_MES.
	 * 
	 * @param dataMes
	 *            Novo valor para o atributo dataMes.
	 */
	public void setDataMes(Date dataMes) {
		this.dataMes = dataMes;
	}

	/**
	 * Obtem o valor do atributo valorPlantao.<BR>
	 * Atributo gerado a partir da coluna APPL_VL_PLANTAO.
	 * 
	 * @return Valor do atributo valorPlantao.
	 */
	public BigDecimal getValorPlantao() {
		return this.valorPlantao;
	}

	/**
	 * Atualiza o valor do atributo valorPlantao.<BR>
	 * Atributo gerado a partir da coluna APPL_VL_PLANTAO.
	 * 
	 * @param valorPlantao
	 *            Novo valor para o atributo valorPlantao.
	 */
	public void setValorPlantao(BigDecimal valorPlantao) {
		this.valorPlantao = valorPlantao;
	}

	/**
	 * Obtem o valor do atributo moeda.<BR>
	 * Atributo gerado a partir da coluna MOED_CD_MOEDA.
	 * 
	 * @return Valor do atributo moeda.
	 */
	public Moeda getMoeda() {
		return this.moeda;
	}

	/**
	 * Atualiza o valor do atributo moeda.<BR>
	 * Atributo gerado a partir da coluna MOED_CD_MOEDA.
	 * 
	 * @param moeda
	 *            Novo valor para o atributo moeda.
	 */
	public void setMoeda(Moeda moeda) {
		this.moeda = moeda;
	}

	/**
	 * Obtem o valor do atributo codigoAutorAtualizacao.<BR>
	 * Atributo gerado a partir da coluna APPL_CD_AUTOR_ATUALIZACAO.
	 * 
	 * @return Valor do atributo codigoAutorAtualizacao.
	 */
	public String getCodigoAutorAtualizacao() {
		return this.codigoAutorAtualizacao;
	}

	/**
	 * Atualiza o valor do atributo codigoAutorAtualizacao.<BR>
	 * Atributo gerado a partir da coluna APPL_CD_AUTOR_ATUALIZACAO.
	 * 
	 * @param codigoAutorAtualizacao
	 *            Novo valor para o atributo codigoAutorAtualizacao.
	 */
	public void setCodigoAutorAtualizacao(String codigoAutorAtualizacao) {
		this.codigoAutorAtualizacao = codigoAutorAtualizacao;
	}

	/**
	 * Obtem o valor do atributo dataAtualizacao.<BR>
	 * Atributo gerado a partir da coluna APPL_DT_ATUALIZACAO.
	 * 
	 * @return Valor do atributo dataAtualizacao.
	 */
	public Date getDataAtualizacao() {
		return this.dataAtualizacao;
	}

	/**
	 * Atualiza o valor do atributo dataAtualizacao.<BR>
	 * Atributo gerado a partir da coluna APPL_DT_ATUALIZACAO.
	 * 
	 * @param dataAtualizacao
	 *            Novo valor para o atributo dataAtualizacao.
	 */
	public void setDataAtualizacao(Date dataAtualizacao) {
		this.dataAtualizacao = dataAtualizacao;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoApropriacaoPlantao").append("='")
				.append(getCodigoApropriacaoPlantao()).append("' ");
		buffer.append("pessoa").append("='").append(getPessoa()).append("' ");
		buffer.append("moeda").append("='").append(getMoeda()).append("' ");
		buffer.append("uploadArquivo").append("='").append(getUploadArquivo())
				.append("' ");
		buffer.append("dataMes").append("='").append(getDataMes()).append("' ");
		buffer.append("valorPlantao").append("='").append(getValorPlantao())
				.append("' ");
		buffer.append("codigoAutorAtualizacao").append("='")
				.append(getCodigoAutorAtualizacao()).append("' ");
		buffer.append("dataAtualizacao").append("='")
				.append(getDataAtualizacao()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	/**
	 * @param login
	 *            the login to set
	 */
	public void setLogin(final String login) {
		this.login = login;
	}

	/**
	 * @return the login
	 */
	public String getLogin() {
		if (login == null && pessoa != null) {
			return pessoa.getCodigoLogin();
		}

		return login;
	}

	/**
	 * @return the siglaMoeda
	 */
	public String getSiglaMoeda() {
		return siglaMoeda;
	}

	/**
	 * @param siglaMoeda
	 *            the siglaMoeda to set
	 */
	public void setSiglaMoeda(String siglaMoeda) {
		this.siglaMoeda = siglaMoeda;
	}
}
