/*
 * @(#) CentroLucro.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela CENTRO_LUCRO. Relacao de Centros de Lucro
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 04/08/2009 09:09:36
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CENTRO_LUCRO")
@NamedQueries({
		@NamedQuery(name = "CentroLucro.findAll", query = "SELECT t FROM CentroLucro t "
				+ "ORDER BY t.nomeCentroLucro ASC "),

		@NamedQuery(name = "CentroLucro.findByFilter", query = "SELECT cl FROM CentroLucro cl "
				+ "WHERE (UPPER(cl.nomeCentroLucro) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
				+ "AND (cl.naturezaCentroLucro.codigoNatureza = ? OR (? = 0L)) "
				+ "ORDER BY cl.nomeCentroLucro ASC "),

		@NamedQuery(name = "CentroLucro.findByFilterFetch", query = "SELECT cl FROM CentroLucro cl "
				+ "LEFT JOIN FETCH cl.naturezaCentroLucro "
				+ "WHERE (UPPER(cl.nomeCentroLucro) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
				+ "AND (cl.naturezaCentroLucro.codigoNatureza = ? OR (? = 0L)) "
				+ "ORDER BY cl.nomeCentroLucro ASC "),

		@NamedQuery(name = "CentroLucro.findByNatureza", query = "SELECT cl FROM CentroLucro cl "
				+ "WHERE cl.naturezaCentroLucro.codigoNatureza = ? "
				+ "ORDER BY cl.nomeCentroLucro ASC "),
		
		@NamedQuery(name = "CentroLucro.findActiveByNatureza", query = "SELECT cl FROM CentroLucro cl "
				+ "WHERE cl.indicadorAtivo = 'A' AND cl.naturezaCentroLucro.codigoNatureza = ? "
				+ "ORDER BY cl.nomeCentroLucro ASC "),

		@NamedQuery(name = "CentroLucro.findNameActiveByNatureza", query = "SELECT cl.nomeCentroLucro FROM CentroLucro cl "
				+ "WHERE cl.indicadorAtivo = 'A' AND cl.naturezaCentroLucro.codigoNatureza = ? "
				+ "ORDER BY cl.nomeCentroLucro ASC "),

		@NamedQuery(name = "CentroLucro.findByDealFiscalAndNatureza", query = "SELECT distinct cl FROM CentroLucro cl "
				+ "JOIN FETCH cl.contratoPraticaCentroLucros cpcl "
				+ "JOIN FETCH cpcl.contratoPratica cp "
				+ "JOIN FETCH cp.cpraticaDfiscals cpdf "
				+ "WHERE cpcl.contratoPratica.codigoContratoPratica = cp.codigoContratoPratica "
				+ "AND cp.codigoContratoPratica = cpdf.contratoPratica.codigoContratoPratica "
				+ "AND cpdf.dealFiscal.codigoDealFiscal = ? "
				+ "AND cl.naturezaCentroLucro.codigoNatureza = ? "
				+ "AND cpcl.dataInicioVigencia <= ? "
				+ "AND nvl(cpcl.dataFimVigencia, add_months(?, 2)) >= ? "),

		@NamedQuery(name = "CentroLucro.findCentroLucroBusinessManagerByName", query = "SELECT cl FROM CentroLucro cl "
				+ "WHERE cl.naturezaCentroLucro.codigoNatureza = ? "
				+ "AND cl.nomeCentroLucro = ? "),


})
public class CentroLucro implements java.io.Serializable {

	// ========================================================================
	// BEGIN - Coloque aqui o codigo manual
	// ========================================================================

	/** Constante para NamedQuery "CentroLucro.findByFilter". */
	public static final String FIND_BY_FILTER = "CentroLucro.findByFilter";

	/** Constante para NamedQuery "CentroLucro.findByFilterFetch". */
	public static final String FIND_BY_FILTER_FETCH = "CentroLucro.findByFilterFetch";

	/** Constante para NamedQuery "CentroLucro.findByNatureza". */
	public static final String FIND_BY_NATUREZA = "CentroLucro.findByNatureza";
	
	/** Constante para NamedQuery "CentroLucro.findActiveByNatureza". */
	public static final String FIND_ACTIVE_BY_NATUREZA = "CentroLucro.findActiveByNatureza";

	/** Constante para NamedQuery "CentroLucro.findByDealFiscalAndNatureza". */
	public static final String FIND_BY_DEAL_FISCAL_AND_NATUREZA = "CentroLucro.findByDealFiscalAndNatureza";

	/** Constante para NamedQuery "CentroLucro.findNameActiveByNatureza". */
	public static final String FIND_NAME_ACTIVE_BY_NATUREZA = "CentroLucro.findNameActiveByNatureza";

	/** Constante para NamedQuery "CentroLucro.findCentroLucroBusinessManagerByName". */
	public static final String FIND_BUSINESS_MANAGER_BY_NAME = "CentroLucro.findCentroLucroBusinessManagerByName";



	// ========================================================================
	// END
	// ========================================================================

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "CentroLucro.findAll".
	 */
	public static final String FIND_ALL = "CentroLucro.findAll";

	/**
	 * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO. Codigo do Centro
	 * de Lucro
	 */
	@Id
	@GeneratedValue(generator = "CentroLucroSeq")
	@SequenceGenerator(name = "CentroLucroSeq", sequenceName = "SQ_CELU_CD_CENTRO_LUCRO", allocationSize = 1)
	@Column(name = "CELU_CD_CENTRO_LUCRO", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoCentroLucro;

	/**
	 * Atributo gerado a partir da coluna NACL_CD_NATUREZA. Codigo da Natureza
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NACL_CD_NATUREZA")
	private NaturezaCentroLucro naturezaCentroLucro;

	/**
	 * Atributo gerado a partir da coluna CELU_NM_CENTRO_LUCRO. Descricao do
	 * Centro de Lucro
	 */
	@Column(name = "CELU_NM_CENTRO_LUCRO", length = 100)
	private String nomeCentroLucro;
	
	/**
	 * Atributo gerado a partir da coluna CELU_IN_ATIVO.
	 */
	@Column(name = "CELU_IN_ATIVO", length = 1)
	private String indicadorAtivo;

	/**
	 * Relacionamento muitos pra muitos.
	 */
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "centroLucros")
	private Set<ContratoPratica> contratoPraticas = new HashSet<ContratoPratica>(
			0);

	/**
	 * Relacionamento um pra muitos.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centroLucro")
	private Set<ContratoPraticaCentroLucro> contratoPraticaCentroLucros = new HashSet<ContratoPraticaCentroLucro>(
			0);

	/**
	 * Atributo gerado a partir da tabela GRUPO_CUSTO_CENTRO_LUCRO.
	 * Relacionamento um para muitos.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centroLucro")
	private Set<GrupoCustoCentroLucro> grupoCustoCentroLucros = new HashSet<GrupoCustoCentroLucro>(
			0);

	/**
	 * Construtor default.
	 */
	public CentroLucro() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoCentroLucro
	 *            Valor do atributo codigoCentroLucro;
	 */
	public CentroLucro(final Long codigoCentroLucro) {
		this.codigoCentroLucro = codigoCentroLucro;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoCentroLucro
	 *            Valor do atributo codigoCentroLucro;
	 * @param naturezaCentroLucro
	 *            Valor do atributo naturezaCentroLucro;
	 * @param nomeCentroLucro
	 *            Valor do atributo nomeCentroLucro;
	 * @param grupoCustoCentroLucros
	 *            Valor do atributo grupoCustoCentroLucros;
	 */
	public CentroLucro(final Long codigoCentroLucro,
			final NaturezaCentroLucro naturezaCentroLucro,
			final String nomeCentroLucro,
			final Set<GrupoCustoCentroLucro> grupoCustoCentroLucros) {
		this.codigoCentroLucro = codigoCentroLucro;
		this.naturezaCentroLucro = naturezaCentroLucro;
		this.nomeCentroLucro = nomeCentroLucro;
		this.grupoCustoCentroLucros = grupoCustoCentroLucros;
	}

	/**
	 * Obtem o valor do atributo codigoCentroLucro.<BR>
	 * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO. Codigo do Centro
	 * de Lucro
	 * 
	 * @return Valor do atributo codigoCentroLucro.
	 */
	public Long getCodigoCentroLucro() {
		return this.codigoCentroLucro;
	}

	/**
	 * Atualiza o valor do atributo codigoCentroLucro.<BR>
	 * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO. Codigo do Centro
	 * de Lucro
	 * 
	 * @param codigoCentroLucro
	 *            Novo valor para o atributo codigoCentroLucro.
	 */
	public void setCodigoCentroLucro(final Long codigoCentroLucro) {
		this.codigoCentroLucro = codigoCentroLucro;
	}

	/**
	 * Obtem o valor do atributo naturezaCentroLucro.<BR>
	 * Atributo gerado a partir da coluna NACL_CD_NATUREZA. Codigo da Natureza
	 * 
	 * @return Valor do atributo naturezaCentroLucro.
	 */
	public NaturezaCentroLucro getNaturezaCentroLucro() {
		return this.naturezaCentroLucro;
	}

	/**
	 * Atualiza o valor do atributo naturezaCentroLucro.<BR>
	 * Atributo gerado a partir da coluna NACL_CD_NATUREZA. Codigo da Natureza
	 * 
	 * @param naturezaCentroLucro
	 *            Novo valor para o atributo naturezaCentroLucro.
	 */
	public void setNaturezaCentroLucro(
			final NaturezaCentroLucro naturezaCentroLucro) {
		this.naturezaCentroLucro = naturezaCentroLucro;
	}

	/**
	 * Obtem o valor do atributo nomeCentroLucro.<BR>
	 * Atributo gerado a partir da coluna CELU_NM_CENTRO_LUCRO. Descricao do
	 * Centro de Lucro
	 * 
	 * @return Valor do atributo nomeCentroLucro.
	 */
	public String getNomeCentroLucro() {
		return this.nomeCentroLucro;
	}

	/**
	 * Atualiza o valor do atributo nomeCentroLucro.<BR>
	 * Atributo gerado a partir da coluna CELU_NM_CENTRO_LUCRO. Descricao do
	 * Centro de Lucro
	 * 
	 * @param nomeCentroLucro
	 *            Novo valor para o atributo nomeCentroLucro.
	 */
	public void setNomeCentroLucro(final String nomeCentroLucro) {
		this.nomeCentroLucro = nomeCentroLucro;
	}

	/**
	 * @return the contratoPraticaCentroLucros
	 */
	public Set<ContratoPraticaCentroLucro> getContratoPraticaCentroLucros() {
		return contratoPraticaCentroLucros;
	}

	/**
	 * @param contratoPraticaCentroLucros
	 *            the contratoPraticaCentroLucros to set
	 */
	public void setContratoPraticaCentroLucros(
			Set<ContratoPraticaCentroLucro> contratoPraticaCentroLucros) {
		this.contratoPraticaCentroLucros = contratoPraticaCentroLucros;
	}

	/**
	 * Obtem o valor do atributo grupoCustoCentroLucros.<BR>
	 * 
	 * @return Valor do atributo grupoCustoCentroLucros.
	 */
	public Set<GrupoCustoCentroLucro> getGrupoCustoCentroLucros() {
		return this.grupoCustoCentroLucros;
	}

	/**
	 * Atualiza o valor do atributo grupoCustoCentroLucros.<BR>
	 * 
	 * @param grupoCustoCentroLucros
	 *            Novo valor para o atributo grupoCustoCentroLucros.
	 */
	public void setGrupoCustoCentroLucros(
			final Set<GrupoCustoCentroLucro> grupoCustoCentroLucros) {
		this.grupoCustoCentroLucros = grupoCustoCentroLucros;
	}

	/**
	 * @return the contratoPraticas
	 */
	public Set<ContratoPratica> getContratoPraticas() {
		return contratoPraticas;
	}

	/**
	 * @param contratoPraticas
	 *            the contratoPraticas to set
	 */
	public void setContratoPraticas(Set<ContratoPratica> contratoPraticas) {
		this.contratoPraticas = contratoPraticas;
	}

	/**
	 * @return the indicadorAtivo
	 */
	public String getIndicadorAtivo() {
		return indicadorAtivo;
	}

	/**
	 * @param indicadorAtivo the indicadorAtivo to set
	 */
	public void setIndicadorAtivo(String indicadorAtivo) {
		this.indicadorAtivo = indicadorAtivo;
	}

	/**
	 * @see Object#toString()
	 * @return representação String do Objeto
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoCentroLucro").append("='")
				.append(getCodigoCentroLucro()).append("' ");
		buffer.append("naturezaCentroLucro").append("='")
				.append(getNaturezaCentroLucro()).append("' ");
		buffer.append("nomeCentroLucro").append("='")
				.append(getNomeCentroLucro()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}