/*
 * @(#) Comissao.java
 * Copyright (c) 2010 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Entity gerado a partir da tabela COMISSAO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 05/10/2010 11:13:07
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "COMISSAO")
@NamedQueries({
		@NamedQuery(name = "Comissao.findAll", query = "SELECT t FROM Comissao t"),

		@NamedQuery(name = "Comissao.findByFilterDP", query = "SELECT c FROM Comissao c "
				+ " JOIN FETCH c.pessoaAe pessAe "
				+ " JOIN FETCH c.pessoaAprovador pessAp "
				+ " WHERE ( c.dataComissao between (?1) AND (?2) ) "
				+ "   AND ( (pessAe.codigoPessoa = ?3) OR (?3 is 0L)) "
				+ "   AND ( (pessAp.codigoPessoa = ?4) OR (?4 is 0L))"
				+ "   AND ( c.indicadorEstadoAtual like '%' || ?5 || '%') "
				+ "   AND ( c.indicadorEstadoAtual IN ('AP','FW','CM') ) "
				+ " ORDER BY c.dataComissao") })
public class Comissao implements java.io.Serializable {

	/** Valor do serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Constante para NamedQuery "Comissao.findAll". */
	public static final String FIND_ALL = "Comissao.findAll";

	/** Constante para NamedQuery "Comissao.findByFilter". */
	public static final String FIND_BY_FILTER_DP = "Comissao.findByFilterDP";

	/**
	 * Atributo gerado a partir da coluna COMI_CD_COMISSAO.
	 */
	@Id
	@GeneratedValue(generator = "ComissaoSeq")
	@SequenceGenerator(name = "ComissaoSeq", sequenceName = "SQ_COMI_CD_COMISSAO", allocationSize = 1)
	@Column(name = "COMI_CD_COMISSAO", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoComissao;

	/**
	 * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "COPR_CD_CONTRATO_PRATICA")
	private ContratoPratica contratoPratica;

	/**
	 * Atributo gerado a partir da coluna PESS_CD_AE_COMISSIONADO.
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PESS_CD_AE_COMISSIONADO", nullable = false)
	private Pessoa pessoaAe;

	/**
	 * Atributo gerado a partir da coluna PESS_CD_APROVADOR.
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PESS_CD_APROVADOR")
	private Pessoa pessoaAprovador;

	/**
	 * Atributo gerado a partir da coluna ESCO_IN_ESTADO_ATUAL.
	 */
	@Column(name = "ESCO_IN_ESTADO_ATUAL", length = 3)
	private String indicadorEstadoAtual;

	/**
	 * Atributo gerado a partir da coluna COMI_DT_COMISSAO.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "COMI_DT_COMISSAO", nullable = false, length = 7)
	private Date dataComissao;

	/**
	 * Atributo gerado a partir da coluna COMI_IN_TIPO.
	 */
	@Column(name = "COMI_IN_TIPO", length = 2)
	private String indicadorTipo;

	/**
	 * Atributo gerado a partir da coluna MOED_CD_MOEDA.
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MOED_CD_MOEDA")
	private Moeda moeda;

	/** Atributo gerado a partir da coluna COAC_PR_COMISSAO. */
	@Column(name = "COMI_PR_COMISSAO", precision = 22, scale = 0)
	private BigDecimal percentualComissao;

	/** Atributo gerado a partir da coluna COAC_VL_COMISSAO. */
	@Column(name = "COMI_VL_COMISSAO", precision = 22, scale = 0)
	private BigDecimal valorComissao;

	/**
	 * Atributo gerado a partir da tabela HISTORICO_COMISSAO.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comissao", cascade = CascadeType.ALL)
	@OrderBy("dataHistorico")
	private List<HistoricoComissao> historicoComissaos = new ArrayList<HistoricoComissao>(
			0);

	/**
	 * Atributo gerado a partir da tabela HISTORICO_COMISSAO.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comissao")
	private List<ComissaoAcelerador> comissaoAceleradores = new ArrayList<ComissaoAcelerador>(
			0);

	/**
	 * Atributo gerado a partir da tabela HISTORICO_COMISSAO.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comissao")
	private List<ComissaoFatura> comissaoFaturas = new ArrayList<ComissaoFatura>(
			0);

	/**
	 * Construtor default.
	 */
	public Comissao() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoComissao
	 *            Valor do atributo codigoComissao;
	 * @param contratoPratica
	 *            Valor do atributo contratoPratica;
	 * @param pessoaByPessCdAeComissionado
	 *            Valor do atributo pessoaByPessCdAeComissionado;
	 * @param dataComissao
	 *            Valor do atributo dataComissao;
	 */
	public Comissao(final Long codigoComissao,
			final ContratoPratica contratoPratica,
			final Pessoa pessoaByPessCdAeComissionado, final Date dataComissao) {
		this.codigoComissao = codigoComissao;
		this.contratoPratica = contratoPratica;
		this.pessoaAe = pessoaByPessCdAeComissionado;
		this.dataComissao = dataComissao;
	}

	/**
	 * Obtem o valor do atributo codigoComissao.<BR>
	 * Atributo gerado a partir da coluna COMI_CD_COMISSAO.
	 * 
	 * @return Valor do atributo codigoComissao.
	 */
	public Long getCodigoComissao() {
		return this.codigoComissao;
	}

	/**
	 * Atualiza o valor do atributo codigoComissao.<BR>
	 * Atributo gerado a partir da coluna COMI_CD_COMISSAO.
	 * 
	 * @param codigoComissao
	 *            Novo valor para o atributo codigoComissao.
	 */
	public void setCodigoComissao(final Long codigoComissao) {
		this.codigoComissao = codigoComissao;
	}

	/**
	 * Obtem o valor do atributo contratoPratica.<BR>
	 * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
	 * 
	 * @return Valor do atributo contratoPratica.
	 */
	public ContratoPratica getContratoPratica() {
		return this.contratoPratica;
	}

	/**
	 * Atualiza o valor do atributo contratoPratica.<BR>
	 * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
	 * 
	 * @param contratoPratica
	 *            Novo valor para o atributo contratoPratica.
	 */
	public void setContratoPratica(final ContratoPratica contratoPratica) {
		this.contratoPratica = contratoPratica;
	}

	/**
	 * Obtem o valor do atributo pessoaByPessCdAeComissionado.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_AE_COMISSIONADO.
	 * 
	 * @return Valor do atributo pessoaByPessCdAeComissionado.
	 */
	public Pessoa getPessoaAe() {
		return this.pessoaAe;
	}

	/**
	 * Atualiza o valor do atributo pessoaByPessCdAeComissionado.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_AE_COMISSIONADO.
	 * 
	 * @param pessoaByPessCdAeComissionado
	 *            Novo valor para o atributo pessoaByPessCdAeComissionado.
	 */
	public void setPessoaAe(final Pessoa pessoaByPessCdAeComissionado) {
		this.pessoaAe = pessoaByPessCdAeComissionado;
	}

	/**
	 * Obtem o valor do atributo pessoaByPessCdAprovador.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_APROVADOR.
	 * 
	 * @return Valor do atributo pessoaByPessCdAprovador.
	 */
	public Pessoa getPessoaAprovador() {
		return this.pessoaAprovador;
	}

	/**
	 * Atualiza o valor do atributo pessoaByPessCdAprovador.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_APROVADOR.
	 * 
	 * @param pessoaByPessCdAprovador
	 *            Novo valor para o atributo pessoaByPessCdAprovador.
	 */
	public void setPessoaAprovador(final Pessoa pessoaByPessCdAprovador) {
		this.pessoaAprovador = pessoaByPessCdAprovador;
	}

	/**
	 * Obtem o valor do atributo dataComissao.<BR>
	 * Atributo gerado a partir da coluna COMI_DT_COMISSAO.
	 * 
	 * @return Valor do atributo dataComissao.
	 */
	public Date getDataComissao() {
		return this.dataComissao;
	}

	/**
	 * Atualiza o valor do atributo dataComissao.<BR>
	 * Atributo gerado a partir da coluna COMI_DT_COMISSAO.
	 * 
	 * @param dataComissao
	 *            Novo valor para o atributo dataComissao.
	 */
	public void setDataComissao(final Date dataComissao) {
		this.dataComissao = dataComissao;
	}

	/**
	 * Obtem o valor do atributo indicadorTipo.<BR>
	 * Atributo gerado a partir da coluna COMI_IN_TIPO.
	 * 
	 * @return Valor do atributo indicadorTipo.
	 */
	public String getIndicadorTipo() {
		return this.indicadorTipo;
	}

	/**
	 * Atualiza o valor do atributo indicadorTipo.<BR>
	 * Atributo gerado a partir da coluna COMI_IN_TIPO.
	 * 
	 * @param indicadorTipo
	 *            Novo valor para o atributo indicadorTipo.
	 */
	public void setIndicadorTipo(final String indicadorTipo) {
		this.indicadorTipo = indicadorTipo;
	}

	/**
	 * @see Object#toString()
	 * 
	 * @return retorna a entidade no formato de string
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoComissao").append("='")
				.append(getCodigoComissao()).append("' ");
		buffer.append("contratoPratica").append("='")
				.append(getContratoPratica()).append("' ");
		buffer.append("pessoaByPessCdAeComissionado").append("='")
				.append(getPessoaAe()).append("' ");
		buffer.append("pessoaByPessCdAprovador").append("='")
				.append(getPessoaAprovador()).append("' ");
		buffer.append("dataComissao").append("='").append(getDataComissao())
				.append("' ");
		buffer.append("indicadorTipo").append("='").append(getIndicadorTipo())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	/**
	 * @param indicadorEstadoAtual
	 *            the indicadorEstadoAtual to set
	 */
	public void setIndicadorEstadoAtual(final String indicadorEstadoAtual) {
		this.indicadorEstadoAtual = indicadorEstadoAtual;
	}

	/**
	 * @return the indicadorEstadoAtual
	 */
	public String getIndicadorEstadoAtual() {
		return indicadorEstadoAtual;
	}

	/**
	 * @param historicoComissaos
	 *            the historicoComissaos to set
	 */
	public void setHistoricoComissaos(
			final List<HistoricoComissao> historicoComissaos) {
		this.historicoComissaos = historicoComissaos;
	}

	/**
	 * @return the historicoComissaos
	 */
	public List<HistoricoComissao> getHistoricoComissaos() {
		return historicoComissaos;
	}

	/**
	 * @param moeda
	 *            the moeda to set
	 */
	public void setMoeda(final Moeda moeda) {
		this.moeda = moeda;
	}

	/**
	 * @return the moeda
	 */
	public Moeda getMoeda() {
		return moeda;
	}

	/**
	 * Obtem o valor do atributo percentualComissao.<BR>
	 * Atributo gerado a partir da coluna COAC_PR_COMISSAO.
	 * 
	 * @return Valor do atributo percentualComissao.
	 */
	public BigDecimal getPercentualComissao() {
		return this.percentualComissao;
	}

	/**
	 * Atualiza o valor do atributo percentualComissao.<BR>
	 * Atributo gerado a partir da coluna COAC_PR_COMISSAO.
	 * 
	 * @param percentualComissao
	 *            Novo valor para o atributo percentualComissao.
	 */
	public void setPercentualComissao(final BigDecimal percentualComissao) {
		this.percentualComissao = percentualComissao;
	}

	/**
	 * Obtem o valor do atributo valorComissao.<BR>
	 * Atributo gerado a partir da coluna COAC_VL_COMISSAO.
	 * 
	 * @return Valor do atributo valorComissao.
	 */
	public BigDecimal getValorComissao() {
		return this.valorComissao;
	}

	/**
	 * Atualiza o valor do atributo valorComissao.<BR>
	 * Atributo gerado a partir da coluna COAC_VL_COMISSAO.
	 * 
	 * @param valorComissao
	 *            Novo valor para o atributo valorComissao.
	 */
	public void setValorComissao(final BigDecimal valorComissao) {
		this.valorComissao = valorComissao;
	}

	/**
	 * @param comissaoAceleradores
	 *            the comissaoAceleradores to set
	 */
	public void setComissaoAceleradores(
			final List<ComissaoAcelerador> comissaoAceleradores) {
		this.comissaoAceleradores = comissaoAceleradores;
	}

	/**
	 * @return the comissaoAceleradores
	 */
	public List<ComissaoAcelerador> getComissaoAceleradores() {
		return comissaoAceleradores;
	}

	/**
	 * @param comissaoFaturas
	 *            the comissaoFaturas to set
	 */
	public void setComissaoFaturas(final List<ComissaoFatura> comissaoFaturas) {
		this.comissaoFaturas = comissaoFaturas;
	}

	/**
	 * @return the comissaoFaturas
	 */
	public List<ComissaoFatura> getComissaoFaturas() {
		return comissaoFaturas;
	}

}
