/*
 * @(#) ComposicaoTce.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela COMPOSICAO_TCE.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 07/06/2011 14:22:49
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "COMPOSICAO_TCE")
@NamedQueries({ 
    @NamedQuery(name = "ComposicaoTce.findAll", query = "SELECT t FROM ComposicaoTce t"),
    
    @NamedQuery(name = "ComposicaoTce.findByPessoaAndDate", query = "SELECT cote FROM ComposicaoTce cote "
        + " JOIN FETCH cote.pessoa "
        + " WHERE (cote.pessoa.codigoPessoa = ?) "
        + "   AND (TRUNC(cote.dataMes) = TRUNC(?)) "),
        
    @NamedQuery(name = "ComposicaoTce.findByPessoaAndMaxDate", query = "SELECT cote FROM ComposicaoTce cote "
        + " JOIN FETCH cote.pessoa "
        + " WHERE (cote.pessoa.codigoPessoa = ?1) "
        + "   AND ( TRUNC(cote.dataMes) = "
        + "         (select TRUNC(MAX(t.dataMes)) FROM ComposicaoTce t "
        + "          WHERE t.pessoa.codigoPessoa = ?1 "
        + "            AND TRUNC(t.dataMes) < TRUNC(?2)) ) "),
    
    @NamedQuery(name = "ComposicaoTce.findByFilter", query = "SELECT cote FROM ComposicaoTce cote "
        + " JOIN FETCH cote.pessoa "
        + " LEFT OUTER JOIN FETCH cote.tipoContrato "
        + " JOIN FETCH cote.moeda "
        + " WHERE (UPPER(cote.pessoa.codigoLogin) like '%'||TRIM(UPPER(?1))||'%' "
        + "   OR UPPER(cote.pessoa.nomePessoa) like '%'||TRIM(UPPER(?1))||'%' ) "
        + "   AND (TRUNC(cote.dataMes) = TRUNC(?2)) "
        + "   AND (cote.indicadorTipo like '%'||TRIM(?3)||'%') "
        + " ORDER BY cote.pessoa.nomePessoa ASC "),
        
    @NamedQuery(name = "ComposicaoTce.findByFilterMissBlank", query = "SELECT cote FROM ComposicaoTce cote "
        + " JOIN FETCH cote.pessoa "
        + " LEFT OUTER JOIN FETCH cote.tipoContrato "
        + " JOIN FETCH cote.moeda "
        + " WHERE (UPPER(cote.pessoa.codigoLogin) like '%'||TRIM(UPPER(?1))||'%' "
        + "   OR UPPER(cote.pessoa.nomePessoa) like '%'||TRIM(UPPER(?1))||'%' ) "
        + "   AND (TRUNC(cote.dataMes) = TRUNC(?2)) "
        + "   AND (cote.indicadorTipo like '%'||TRIM(?3)||'%') "
        + "   AND ((cote.valorSalario = 0 OR cote.valorSalario IS NULL) "
        + "        OR (cote.valorBeneficios = 0 OR cote.valorBeneficios IS NULL) " 
        + "        OR (cote.numeroHorasJornada = 0 OR cote.numeroHorasJornada IS NULL) "
        + "        OR (cote.tipoContrato.codigoTipoContrato = 0 OR cote.tipoContrato.codigoTipoContrato IS NULL)) "
        + " ORDER BY cote.pessoa.nomePessoa ASC "),
        
    @NamedQuery(name = "ComposicaoTce.removeByDate", query = "DELETE FROM ComposicaoTce cote "
        + " WHERE (TRUNC(cote.dataMes) = TRUNC(:param1)) "
        + "   AND (cote.indicadorTipo like '%'||TRIM(:param2)||'%') ")
})
public class ComposicaoTce implements java.io.Serializable {
    
    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    
    /** Constante para NamedQuery "ComposicaoTce.findByPessoaAndDate". */
    public static final String FIND_BY_PESSOA_AND_DATE = "ComposicaoTce.findByPessoaAndDate";
    
    /** Constante para NamedQuery "ComposicaoTce.findByPessoaAndMaxDate". */
    public static final String FIND_BY_PESSOA_AND_MAX_DATE = "ComposicaoTce.findByPessoaAndMaxDate";
    
    /** Constante para NamedQuery "ComposicaoTce.findByFilter". */
    public static final String FIND_BY_FILTER = "ComposicaoTce.findByFilter";
    
    /** Constante para NamedQuery "ComposicaoTce.findByFilterMissBlank". */
    public static final String FIND_BY_FILTER_MISS_BLANK = "ComposicaoTce.findByFilterMissBlank";
    
    /** Constante para NamedQuery "ComposicaoTce.removeByDate". */
    public static final String REMOVE_BY_DATE = "ComposicaoTce.removeByDate";

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "ComposicaoTce.findAll".
     */
    public static final String FIND_ALL = "ComposicaoTce.findAll";

    /**
     * Atributo gerado a partir da coluna COTE_CD_COMPOSICAO_TCE.
     */
    @Id
    @GeneratedValue(generator = "ComposicaoTceSeq")
    @SequenceGenerator(name = "ComposicaoTceSeq", sequenceName = "SQ_COTE_CD_COMPOSICAO_TCE", allocationSize = 1)
    @Column(name = "COTE_CD_COMPOSICAO_TCE", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoComposicaoTce;

    /**
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PESS_CD_PESSOA", nullable = false)
    private Pessoa pessoa;
    
    /**
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TICO_CD_TIPO_CONTRATO", nullable = true)
    private TipoContrato tipoContrato;

    /**
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MOED_CD_MOEDA", nullable = false)
    private Moeda moeda;

    /**
     * Atributo gerado a partir da coluna COTE_DT_MES.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "COTE_DT_MES", length = 7)
    private Date dataMes;

    /**
     * Atributo gerado a partir da coluna COTE_VL_SALARIO.
     */

    @Column(name = "COTE_VL_SALARIO", precision = 22, scale = 0)
    private BigDecimal valorSalario;

    /**
     * Atributo gerado a partir da coluna COTE_VL_BENEFICIOS.
     */

    @Column(name = "COTE_VL_BENEFICIOS", precision = 22, scale = 0)
    private BigDecimal valorBeneficios;

    /**
     * Atributo gerado a partir da coluna COTE_VL_HORAS_JORNADA.
     */

    @Column(name = "COTE_NR_HORAS_JORNADA", precision = 22, scale = 0)
    private BigDecimal numeroHorasJornada;

    /**
     * Atributo gerado a partir da coluna COTE_IN_TIPO.
     */

    @Column(name = "COTE_IN_TIPO", length = 2)
    private String indicadorTipo;

    /**
     * Construtor default.
     */
    public ComposicaoTce() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoComposicaoTce Valor do atributo codigoComposicaoTce;
     * @param pessoa Valor do atributo pessoa;
     * @param moeda Valor do atributo moeda;
     */
    public ComposicaoTce(final Long codigoComposicaoTce, final Pessoa pessoa, 
            final Moeda moeda) {
        this.codigoComposicaoTce = codigoComposicaoTce;
        this.pessoa = pessoa;
        this.moeda = moeda;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoComposicaoTce Valor do atributo codigoComposicaoTce;
     * @param pessoa Valor do atributo pessoa;
     * @param tipoContrato Valor do atributo tipoContrato;
     * @param moeda Valor do atributo moeda;
     * @param dataMes Valor do atributo dataMes;
     * @param valorSalario Valor do atributo valorSalario;
     * @param valorBeneficios Valor do atributo valorBeneficios;
     * @param numeroHorasJornada Valor do atributo numeroHorasJornada;
     * @param indicadorTipo Valor do atributo indicadorTipo;
     */
    public ComposicaoTce(final Long codigoComposicaoTce, final Pessoa pessoa, 
            final TipoContrato tipoContrato, final Moeda moeda,
            final Date dataMes, final BigDecimal valorSalario,
            final BigDecimal valorBeneficios, final BigDecimal numeroHorasJornada,
            final String indicadorTipo) {
        this.codigoComposicaoTce = codigoComposicaoTce;
        this.pessoa = pessoa;
        this.tipoContrato = tipoContrato;
        this.moeda = moeda;
        this.dataMes = dataMes;
        this.valorSalario = valorSalario;
        this.valorBeneficios = valorBeneficios;
        this.numeroHorasJornada = numeroHorasJornada;
        this.indicadorTipo = indicadorTipo;
    }

    /**
     * Obtem o valor do atributo codigoComposicaoTce.<BR>
     * Atributo gerado a partir da coluna COTE_CD_COMPOSICAO_TCE.
     * @return Valor do atributo codigoComposicaoTce.
     */
    public Long getCodigoComposicaoTce() {
        return this.codigoComposicaoTce;
    }

    /**
     * Atualiza o valor do atributo codigoComposicaoTce.<BR>
     * Atributo gerado a partir da coluna COTE_CD_COMPOSICAO_TCE.
     * @param codigoComposicaoTce Novo valor para o atributo codigoComposicaoTce.
     */
    public void setCodigoComposicaoTce(final Long codigoComposicaoTce) {
        this.codigoComposicaoTce = codigoComposicaoTce;
    }

    /**
     * Obtem o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     * @return Valor do atributo pessoa.
     */
    public Pessoa getPessoa() {
        return this.pessoa;
    }

    /**
     * Atualiza o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     * @param pessoa Novo valor para o atributo pessoa.
     */
    public void setPessoa(final Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    
    /**
     * Obtem o valor do atributo tipoContrato.<BR>
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     * @return Valor do atributo tipoContrato.
     */
    public TipoContrato getTipoContrato() {
        return this.tipoContrato;
    }

    /**
     * Atualiza o valor do atributo tipoContrato.<BR>
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     * @param tipoContrato Novo valor para o atributo tipoContrato.
     */
    public void setTipoContrato(final TipoContrato tipoContrato) {
        this.tipoContrato = tipoContrato;
    }

    /**
     * Obtem o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * @return Valor do atributo moeda.
     */
    public Moeda getMoeda() {
        return this.moeda;
    }

    /**
     * Atualiza o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * @param moeda Novo valor para o atributo moeda.
     */
    public void setMoeda(final Moeda moeda) {
        this.moeda = moeda;
    }

    /**
     * Obtem o valor do atributo dataMes.<BR>
     * Atributo gerado a partir da coluna COTE_DT_MES.
     * @return Valor do atributo dataMes.
     */
    public Date getDataMes() {
        return this.dataMes;
    }

    /**
     * Atualiza o valor do atributo dataMes.<BR>
     * Atributo gerado a partir da coluna COTE_DT_MES.
     * @param dataMes Novo valor para o atributo dataMes.
     */
    public void setDataMes(final Date dataMes) {
        this.dataMes = dataMes;
    }

    /**
     * Obtem o valor do atributo valorSalario.<BR>
     * Atributo gerado a partir da coluna COTE_VL_SALARIO.
     * @return Valor do atributo valorSalario.
     */
    public BigDecimal getValorSalario() {
        return this.valorSalario;
    }

    /**
     * Atualiza o valor do atributo valorSalario.<BR>
     * Atributo gerado a partir da coluna COTE_VL_SALARIO.
     * @param valorSalario Novo valor para o atributo valorSalario.
     */
    public void setValorSalario(final BigDecimal valorSalario) {
        this.valorSalario = valorSalario;
    }

    /**
     * Obtem o valor do atributo valorBeneficios.<BR>
     * Atributo gerado a partir da coluna COTE_VL_BENEFICIOS.
     * @return Valor do atributo valorBeneficios.
     */
    public BigDecimal getValorBeneficios() {
        return this.valorBeneficios;
    }

    /**
     * Atualiza o valor do atributo valorBeneficios.<BR>
     * Atributo gerado a partir da coluna COTE_VL_BENEFICIOS.
     * @param valorBeneficios Novo valor para o atributo valorBeneficios.
     */
    public void setValorBeneficios(final BigDecimal valorBeneficios) {
        this.valorBeneficios = valorBeneficios;
    }

    /**
     * Obtem o valor do atributo numeroHorasJornada.<BR>
     * Atributo gerado a partir da coluna COTE_NR_HORAS_JORNADA.
     * @return Valor do atributo numeroHorasJornada.
     */
    public BigDecimal getNumeroHorasJornada() {
        return this.numeroHorasJornada;
    }

    /**
     * Atualiza o valor do atributo numeroHorasJornada.<BR>
     * Atributo gerado a partir da coluna COTE_NR_HORAS_JORNADA.
     * @param numeroHorasJornada Novo valor para o atributo numeroHorasJornada.
     */
    public void setNumeroHorasJornada(final BigDecimal numeroHorasJornada) {
        this.numeroHorasJornada = numeroHorasJornada;
    }

    /**
     * Obtem o valor do atributo indicadorTipo.<BR>
     * Atributo gerado a partir da coluna COTE_IN_TIPO.
     * @return Valor do atributo indicadorTipo.
     */
    public String getIndicadorTipo() {
        return this.indicadorTipo;
    }

    /**
     * Atualiza o valor do atributo indicadorTipo.<BR>
     * Atributo gerado a partir da coluna COTE_IN_TIPO.
     * @param indicadorTipo Novo valor para o atributo indicadorTipo.
     */
    public void setIndicadorTipo(final String indicadorTipo) {
        this.indicadorTipo = indicadorTipo;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoComposicaoTce").append("='").append(
                getCodigoComposicaoTce()).append("' ");
        buffer.append("pessoa").append("='").append(getPessoa()).append("' ");
        buffer.append("tipoContrato").append("='").append(getTipoContrato()).append("' ");
        buffer.append("moeda").append("='").append(getMoeda()).append("' ");
        buffer.append("dataMes").append("='").append(getDataMes()).append("' ");
        buffer.append("valorSalario").append("='").append(getValorSalario())
                .append("' ");
        buffer.append("valorBeneficios").append("='").append(
                getValorBeneficios()).append("' ");
        buffer.append("numeroHorasJornada").append("='").append(
                getNumeroHorasJornada()).append("' ");
        buffer.append("indicadorTipo").append("='").append(getIndicadorTipo())
                .append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}