/*
 * @(#) ContratoPraticaOrcDesp.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela CONTRATO_PRATICA_ORC_DESP.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 24/07/2012 15:26:39
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CONTRATO_PRATICA_ORC_DESP")
@NamedQueries({@NamedQuery(name = "ContratoPraticaOrcDesp.findAll", query = "SELECT t FROM ContratoPraticaOrcDesp t"),
               @NamedQuery(name = "ContratoPraticaOrcDesp.findByOrcamentoDespesa", 
               query = "SELECT t FROM ContratoPraticaOrcDesp t "
                   +    "WHERE t.orcamentoDespesa.codigoOrcaDespesa = ? ")
})
public class ContratoPraticaOrcDesp implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "ContratoPraticaOrcDesp.findAll".
     */
    public static final String FIND_ALL = "ContratoPraticaOrcDesp.findAll";
    
    /**
     * Constante para NamedQuery "ContratoPraticaOrcDesp.findByOrcamentoDespesa".
     */
    public static final String FIND_BY_ORCAMENTO_DESPESA = "ContratoPraticaOrcDesp.findByOrcamentoDespesa";

    /**
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     */
    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "codigoOrcDespesa", column = @Column(name = "ORDE_CD_ORCA_DESPESA", nullable = false, precision = 18, scale = 0)),
            @AttributeOverride(name = "codigoContratoPratica", column = @Column(name = "COPR_CD_CONTRATO_PRATICA", nullable = false, precision = 18, scale = 0))})
    private ContratoPraticaOrcDespId id;

    /**
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COPR_CD_CONTRATO_PRATICA", nullable = false, insertable = false, updatable = false)
    private ContratoPratica contratoPratica;

    /**
     * Atributo gerado a partir da coluna ORDE_CD_ORCA_DESPESA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ORDE_CD_ORCA_DESPESA", nullable = false, insertable = false, updatable = false)
    private OrcamentoDespesa orcamentoDespesa;

    /**
     * Construtor default.
     */
    public ContratoPraticaOrcDesp() {
    }

    /**
     * Construtor.
     * 
     * @param id
     *            id.
     */
    public ContratoPraticaOrcDesp(final ContratoPraticaOrcDespId id) {
        this.id = id;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param id
     *            Valor do atributo id;
     * @param contratoPratica
     *            Valor do atributo contratoPratica;
     * @param orcamentoDespesa
     *            Valor do atributo orcamentoDespesa;
     */
    public ContratoPraticaOrcDesp(final ContratoPraticaOrcDespId id,
            final ContratoPratica contratoPratica,
            final OrcamentoDespesa orcamentoDespesa) {
        this.id = id;
        this.contratoPratica = contratoPratica;
        this.orcamentoDespesa = orcamentoDespesa;
    }

    /**
     * Obtem o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     * 
     * @return Valor do atributo id.
     */
    public ContratoPraticaOrcDespId getId() {
        return this.id;
    }

    /**
     * Atualiza o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     * 
     * @param id
     *            Novo valor para o atributo id.
     */
    public void setId(final ContratoPraticaOrcDespId id) {
        this.id = id;
    }

    /**
     * Obtem o valor do atributo contratoPratica.<BR>
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     * 
     * @return Valor do atributo contratoPratica.
     */
    public ContratoPratica getContratoPratica() {
        return this.contratoPratica;
    }

    /**
     * Atualiza o valor do atributo contratoPratica.<BR>
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     * 
     * @param contratoPratica
     *            Novo valor para o atributo contratoPratica.
     */
    public void setContratoPratica(final ContratoPratica contratoPratica) {
        this.contratoPratica = contratoPratica;
    }

    /**
     * Obtem o valor do atributo orcamentoDespesa.<BR>
     * Atributo gerado a partir da coluna ORDE_CD_ORCA_DESPESA.
     * 
     * @return Valor do atributo orcamentoDespesa.
     */
    public OrcamentoDespesa getOrcamentoDespesa() {
        return this.orcamentoDespesa;
    }

    /**
     * Atualiza o valor do atributo orcamentoDespesa.<BR>
     * Atributo gerado a partir da coluna ORDE_CD_ORCA_DESPESA.
     * 
     * @param orcamentoDespesa
     *            Novo valor para o atributo orcamentoDespesa.
     */
    public void setOrcamentoDespesa(final OrcamentoDespesa orcamentoDespesa) {
        this.orcamentoDespesa = orcamentoDespesa;
    }

    /**
     * @see Object#toString()
     * @return buffer.
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("contratoPratica").append("='").append(
                getContratoPratica()).append("' ");
        buffer.append("orcamentoDespesa").append("='").append(
                getOrcamentoDespesa()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}