/*
 * @(#) ContratoPraticaCentroLucro.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela CONTRATO_PRATICA_CENTRO_LUCRO.
 * Relacao do Contrato Pratica com Centro de Lucro_Natureza
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 15/09/2009 16:00:53
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CONTRATO_PRATICA_CENTRO_LUCRO")
@NamedQueries({ 
    @NamedQuery(name = "ContratoPraticaCentroLucro.findAll", 
            query = "SELECT t FROM ContratoPraticaCentroLucro t"),
            
    @NamedQuery(name = "ContratoPraticaCentroLucro.findByContratoPratica", 
            query = "SELECT t FROM ContratoPraticaCentroLucro t"
            + " WHERE t.contratoPratica.codigoContratoPratica = ?"
            + " ORDER BY t.centroLucro.naturezaCentroLucro.nomeNatureza ASC, " 
            + " t.dataInicioVigencia ASC"),
            
    @NamedQuery(name = "ContratoPraticaCentroLucro.findByContratoPraticaAndNaturezaOptional", 
            query = "SELECT t FROM ContratoPraticaCentroLucro t"
            + " WHERE t.contratoPratica.codigoContratoPratica = ?"
            + " AND t.centroLucro.naturezaCentroLucro.indicadorTipo != 'O'"
            + " ORDER BY t.centroLucro.naturezaCentroLucro.nomeNatureza ASC, " 
            + " t.dataInicioVigencia ASC"),

    @NamedQuery(name = "ContratoPraticaCentroLucro.findByContratoPraticaAndNatureza", 
            query = "SELECT t FROM ContratoPraticaCentroLucro t"
            + " WHERE t.contratoPratica.codigoContratoPratica = ? "
            + " AND t.centroLucro.naturezaCentroLucro.codigoNatureza = ?"
            + " ORDER BY t.dataInicioVigencia ASC"),
    
    @NamedQuery(name = "ContratoPraticaCentroLucro.findMaxStartDateByContratoPraticaAndNatureza", 
            query = "SELECT t FROM ContratoPraticaCentroLucro t"
            + " WHERE t.contratoPratica.codigoContratoPratica = ? " 
            + " AND t.centroLucro.naturezaCentroLucro.codigoNatureza = ? "
            + " AND t.dataInicioVigencia = "
            + "(SELECT MAX(x.dataInicioVigencia) FROM ContratoPraticaCentroLucro x"
            + " WHERE x.contratoPratica.codigoContratoPratica = ? "
            + " AND x.centroLucro.naturezaCentroLucro.codigoNatureza = ?)"),
     
    @NamedQuery(name = "ContratoPraticaCentroLucro.findByContPratAndNatAndDate", 
            query = "SELECT t FROM ContratoPraticaCentroLucro t"
            + " WHERE t.contratoPratica.codigoContratoPratica = ? "
            + " AND t.centroLucro.naturezaCentroLucro.codigoNatureza = ? "
            + " AND ((TRUNC(?) between t.dataInicioVigencia and t.dataFimVigencia) or "
            + "       (t.dataFimVigencia is null and t.dataInicioVigencia <= TRUNC(?))) "
            + " ORDER BY t.dataInicioVigencia ASC")
            
})
public class ContratoPraticaCentroLucro implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    
    /** Constante para NamedQuery "ContratoPraticaCentroLucro.findByContratoPratica". */
    public static final String FIND_BY_CONTRATO_PRATICA = 
        "ContratoPraticaCentroLucro.findByContratoPratica";
    
    /** Constante para NamedQuery "ContratoPraticaCentroLucro.findMaxStartDateByContratoPraticaAndNatureza". */
    public static final String FIND_MAX_START_DATE_BY_CONTRATO_PRATICA_AND_NATUREZA = 
        "ContratoPraticaCentroLucro.findMaxStartDateByContratoPraticaAndNatureza";
    
    /** Constante para NamedQuery "ContratoPraticaCentroLucro.findByContratoPraticaAndNatureza". */
    public static final String FIND_BY_CONTRATO_PRATICA_AND_NATUREZA = 
        "ContratoPraticaCentroLucro.findByContratoPraticaAndNatureza";
    
    /** Constante para NamedQuery "ContratoPraticaCentroLucro.findByContratoPraticaAndNaturezaOptional". */
    public static final String FIND_BY_CONTRATO_PRATICA_AND_NATUREZA_OPTIONAL = 
        "ContratoPraticaCentroLucro.findByContratoPraticaAndNaturezaOptional";
    
    /** Constante para NamedQuery "ContratoPraticaCentroLucro.findByContPratAndNatAndDate". */
    public static final String FIND_BY_CONT_PRAT_AND_NAT_AND_DATE = 
        "ContratoPraticaCentroLucro.findByContPratAndNatAndDate";
    
    // ========================================================================
    // END
    // ========================================================================
    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "ContratoPraticaCentroLucro.findAll".
     */
    public static final String FIND_ALL = "ContratoPraticaCentroLucro.findAll";

    /**
     * Atributo gerado a partir da coluna CPCL_CD_CONTRATO_PRATICA_CL.
     */
    @Id
    @GeneratedValue(generator = "ContratoPraticaCentroLucroSeq")
    @SequenceGenerator(name = "ContratoPraticaCentroLucroSeq", 
            sequenceName = "SQ_CPCL_CD_CONTRATO_PRATICA_CL", allocationSize = 1)
    @Column(name = "CPCL_CD_CONTRATO_PRATICA_CL", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoContratoPraticaCl;

    /**
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     * Codigo do Contrato Pratica
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COPR_CD_CONTRATO_PRATICA", nullable = false)
    private ContratoPratica contratoPratica;

    /**
     * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO.
     * Codigo do Centro de Lucro
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CELU_CD_CENTRO_LUCRO", nullable = false)
    private CentroLucro centroLucro;

    /**
     * Atributo gerado a partir da coluna CPCL_DT_INICIO_VIGENCIA.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "CPCL_DT_INICIO_VIGENCIA", length = 7)
    private Date dataInicioVigencia;

    /**
     * Atributo gerado a partir da coluna CPCL_DT_FIM_VIGENCIA.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "CPCL_DT_FIM_VIGENCIA", length = 7)
    private Date dataFimVigencia;

    /**
     * Construtor default.
     */
    public ContratoPraticaCentroLucro() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoContratoPraticaCl Valor do atributo codigoContratoPraticaCl;
     * @param contratoPratica Valor do atributo contratoPratica;
     * @param centroLucro Valor do atributo centroLucro;
     */
    public ContratoPraticaCentroLucro(final Long codigoContratoPraticaCl,
            final ContratoPratica contratoPratica, final CentroLucro centroLucro) {
        this.codigoContratoPraticaCl = codigoContratoPraticaCl;
        this.contratoPratica = contratoPratica;
        this.centroLucro = centroLucro;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoContratoPraticaCl Valor do atributo codigoContratoPraticaCl;
     * @param contratoPratica Valor do atributo contratoPratica;
     * @param centroLucro Valor do atributo centroLucro;
     * @param dataInicioVigencia Valor do atributo dataInicioVigencia;
     * @param dataFimVigencia Valor do atributo dataFimVigencia;
     */
    public ContratoPraticaCentroLucro(final Long codigoContratoPraticaCl,
            final ContratoPratica contratoPratica, final CentroLucro centroLucro,
            final Date dataInicioVigencia, final Date dataFimVigencia) {
        this.codigoContratoPraticaCl = codigoContratoPraticaCl;
        this.contratoPratica = contratoPratica;
        this.centroLucro = centroLucro;
        this.dataInicioVigencia = dataInicioVigencia;
        this.dataFimVigencia = dataFimVigencia;
    }

    /**
     * Obtem o valor do atributo codigoContratoPraticaCl.<BR>
     * Atributo gerado a partir da coluna CPCL_CD_CONTRATO_PRATICA_CL.
     * @return Valor do atributo codigoContratoPraticaCl.
     */
    public Long getCodigoContratoPraticaCl() {
        return this.codigoContratoPraticaCl;
    }

    /**
     * Atualiza o valor do atributo codigoContratoPraticaCl.<BR>
     * Atributo gerado a partir da coluna CPCL_CD_CONTRATO_PRATICA_CL.
     * @param codigoContratoPraticaCl Novo valor para o atributo codigoContratoPraticaCl.
     */
    public void setCodigoContratoPraticaCl(final Long codigoContratoPraticaCl) {
        this.codigoContratoPraticaCl = codigoContratoPraticaCl;
    }

    /**
     * Obtem o valor do atributo contratoPratica.<BR>
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     * Codigo do Contrato Pratica
     * @return Valor do atributo contratoPratica.
     */
    public ContratoPratica getContratoPratica() {
        return this.contratoPratica;
    }

    /**
     * Atualiza o valor do atributo contratoPratica.<BR>
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     * Codigo do Contrato Pratica
     * @param contratoPratica Novo valor para o atributo contratoPratica.
     */
    public void setContratoPratica(final ContratoPratica contratoPratica) {
        this.contratoPratica = contratoPratica;
    }

    /**
     * Obtem o valor do atributo centroLucro.<BR>
     * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO.
     * Codigo do Centro de Lucro
     * @return Valor do atributo centroLucro.
     */
    public CentroLucro getCentroLucro() {
        return this.centroLucro;
    }

    /**
     * Atualiza o valor do atributo centroLucro.<BR>
     * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO.
     * Codigo do Centro de Lucro
     * @param centroLucro Novo valor para o atributo centroLucro.
     */
    public void setCentroLucro(final CentroLucro centroLucro) {
        this.centroLucro = centroLucro;
    }

    /**
     * Obtem o valor do atributo dataInicioVigencia.<BR>
     * Atributo gerado a partir da coluna CPCL_DT_INICIO_VIGENCIA.
     * @return Valor do atributo dataInicioVigencia.
     */
    public Date getDataInicioVigencia() {
        return this.dataInicioVigencia;
    }

    /**
     * Atualiza o valor do atributo dataInicioVigencia.<BR>
     * Atributo gerado a partir da coluna CPCL_DT_INICIO_VIGENCIA.
     * @param dataInicioVigencia Novo valor para o atributo dataInicioVigencia.
     */
    public void setDataInicioVigencia(final Date dataInicioVigencia) {
        this.dataInicioVigencia = dataInicioVigencia;
    }

    /**
     * Obtem o valor do atributo dataFimVigencia.<BR>
     * Atributo gerado a partir da coluna CPCL_DT_FIM_VIGENCIA.
     * @return Valor do atributo dataFimVigencia.
     */
    public Date getDataFimVigencia() {
        return this.dataFimVigencia;
    }

    /**
     * Atualiza o valor do atributo dataFimVigencia.<BR>
     * Atributo gerado a partir da coluna CPCL_DT_FIM_VIGENCIA.
     * @param dataFimVigencia Novo valor para o atributo dataFimVigencia.
     */
    public void setDataFimVigencia(final Date dataFimVigencia) {
        this.dataFimVigencia = dataFimVigencia;
    }

    /**
     * @see Object#toString()
     * 
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoContratoPraticaCl").append("='").append(
                getCodigoContratoPraticaCl()).append("' ");
        buffer.append("contratoPratica").append("='").append(
                getContratoPratica()).append("' ");
        buffer.append("centroLucro").append("='").append(getCentroLucro())
                .append("' ");
        buffer.append("dataInicioVigencia").append("='").append(
                getDataInicioVigencia()).append("' ");
        buffer.append("dataFimVigencia").append("='").append(
                getDataFimVigencia()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
