/*
 * @(#) ControleReajuste.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Calendar;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;

/**
 * Entity gerado a partir da tabela CONTROLE_REAJUSTE.
 * 
 * @author Generated by Hibernate Tools 3.6.0
 * @since 06/12/2013 16:56:59
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CONTROLE_REAJUSTE")
@NamedQueries({
	@NamedQuery(name = "ControleReajuste.findAll", query = "SELECT t FROM ControleReajuste t"),

	@NamedQuery(name = "ControleReajuste.findToSendEmail", query = "SELECT t FROM ControleReajuste t "
			+ "WHERE t.dataPrevista <= :dataInicioLembrete "
			+ "AND (t.dataEnvioEmail IS NULL OR t.dataEnvioEmail <= :dataUltimoEnvioEmail) "
			+ "AND t.controleReajusteStatus.codigoControleReajStatus in (1, 2, 3) "
			+ "AND t.fichaReajuste.fichaReajusteStatus.codigoFichaReajusteStatus = 1"),

	@NamedQuery(name = "ControleReajuste.findByDateIntervalAndFichaReajuste", query = "SELECT t FROM ControleReajuste t"
			+ " WHERE t.dataPrevista BETWEEN :startDate AND :endDate"
			+ " AND t.fichaReajuste = :fichaReajuste"),

	@NamedQuery(name = "ControleReajuste.findGreaterThanDateAndFichaReajuste", query = "SELECT t FROM ControleReajuste t"
			+ " WHERE t.dataPrevista > :date"
			+ " AND t.fichaReajuste = :fichaReajuste"),

	@NamedQuery(name = "ControleReajuste.findByFichaReajuste", query = "SELECT t FROM ControleReajuste t "
			+ "WHERE t.fichaReajuste.codigoFichaReajuste = ?"),

	@NamedQuery(name = "ControleReajuste.findLastbyFichaReajuste", query = "SELECT c FROM ControleReajuste c"
			+ " WHERE c.fichaReajuste = :fichaReajuste"
			+ " AND c.dataPrevista = ("
				+ "		SELECT MAX(t.dataPrevista) FROM"
				+ " 	ControleReajuste t"
				+ " 	WHERE t.fichaReajuste = :fichaReajuste)"),

	@NamedQuery(name = "ControleReajuste.findByDateInterval", query = "SELECT c FROM ControleReajuste c"
			+ " WHERE c.dataPrevista BETWEEN :startDate AND :endDate"),

		@NamedQuery(name = "ControleReajuste.findByDateIntervalAndMsaAndCliente", query = "SELECT DISTINCT cr FROM ControleReajuste cr"
			+ " JOIN FETCH cr.fichaReajuste f"
			+ " JOIN FETCH f.documentoLegals d"
			+ " JOIN FETCH d.msa m"
			+ " JOIN FETCH m.cliente c"
			+ " WHERE (m.codigoMsa = :msa OR :msa = null)"
			+ " AND (cr.controleReajusteStatus.codigoControleReajStatus = :controleReajusteStatusId OR :controleReajusteStatusId = null)"
			+ " AND (c.codigoCliente = :cliente OR :cliente = null)"
				+ " AND cr.dataPrevista BETWEEN :startDate AND :endDate") })
public class ControleReajuste implements java.io.Serializable, Cloneable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "ControleReajuste.findAll".
	 */
	public static final String FIND_ALL = "ControleReajuste.findAll";

	/**
	 * Constante para NamedQuery "ControleReajuste.findToSendEmail".
	 */
	public static final String FIND_TO_SEND_EMAIL = "ControleReajuste.findToSendEmail";

	/**
	 * Constante para NamedQuery
	 * "ControleReajuste.findByDateIntervalAndFichaReajuste".
	 */
	public static final String FIND_BY_DATE_INTERVAL_AND_FICHA_REAJUSTE = "ControleReajuste.findByDateIntervalAndFichaReajuste";

	/**
	 * Constante para NamedQuery
	 * "ControleReajuste.findGreaterThanDateAndFichaReajuste".
	 */
	public static final String FIND_GREATER_THAN_DATE_AND_FICHA_REAJUSTE = "ControleReajuste.findGreaterThanDateAndFichaReajuste";

	/**
	 * Constante para NamedQuery "ControleReajuste.findLastbyFichaReajuste".
	 */
	public static final String FIND_LAST_BY_FICHA_REAJUSTE = "ControleReajuste.findLastbyFichaReajuste";

	/**
	 * Constante para NamedQuery "ControleReajuste.findByFichaReajuste".
	 */
	public static final String FIND_BY_FICHA_REAJUSTE = "ControleReajuste.findByFichaReajuste";
	
	/**
	 * Constante para NamedQuery "ControleReajuste.findByDateInterval".
	 */
	public static final String FIND_BY_DATE_INTERVAL = "ControleReajuste.findByDateInterval";
	
	/**
	 * Constante para NamedQuery
	 * "ControleReajuste.findByDateIntervalAndMsaAndCliente".
	 */
	public static final String FIND_BY_DATE_INTERVAL_AND_MSA_AND_CLIENTE = "ControleReajuste.findByDateIntervalAndMsaAndCliente";

	/**
	 * Atributo gerado a partir da coluna CORE_CD_CONTROLE_REAJUSTE.
	 */
	@Id
	@GeneratedValue(generator = "ControleReajusteSeq")
	@SequenceGenerator(name = "ControleReajusteSeq", sequenceName = "SQ_CORE_CD_CONTROLE_REAJUSTE", allocationSize = 1)
	@Column(name = "CORE_CD_CONTROLE_REAJUSTE", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoControleReajuste;

	/**
	 * Atributo gerado a partir da coluna CORS_CD_CONTROLE_REAJ_STATUS.
	 */
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CORS_CD_CONTROLE_REAJ_STATUS", nullable = false)
	private ControleReajusteStatus controleReajusteStatus;

	/**
	 * Atributo gerado a partir da coluna FIRE_CD_FICHA_REAJUSTE.
	 */
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FIRE_CD_FICHA_REAJUSTE", nullable = false)
	private FichaReajuste fichaReajuste;

	/**
	 * Atributo gerado a partir da coluna CORE_DT_PREVISTA.
	 */
	@Audited
	@Temporal(TemporalType.DATE)
	@Column(name = "CORE_DT_PREVISTA", length = 7)
	private Date dataPrevista;

	/**
	 * Atributo gerado a partir da coluna CORE_DT_REAJUSTE.
	 */
	@Audited
	@Temporal(TemporalType.DATE)
	@Column(name = "CORE_DT_REAJUSTE", length = 7)
	private Date dataReajuste;

	/**
	 * Atributo gerado a partir da coluna CORE_PR_PREVISTA.
	 */
	@Audited
	@Column(name = "CORE_PR_PREVISTA", precision = 5, scale = 2)
	private BigDecimal percentualPrevista;

	/**
	 * Atributo gerado a partir da coluna CORE_PR_REALIZADA.
	 */
	@Audited
	@Column(name = "CORE_PR_REALIZADA", precision = 5, scale = 2)
	private BigDecimal percentualRealizada;

	/**
	 * Atributo gerado a partir da coluna CORE_TX_OBSERVACAO.
	 */
	@Audited
	@Column(name = "CORE_TX_OBSERVACAO", length = 1000)
	private String textoObservacao;

	/**
	 * Atributo gerado a partir da coluna CORE_DT_ENVIO_EMAIL.
	 */
	@Audited
	@Temporal(TemporalType.DATE)
	@Column(name = "CORE_DT_ENVIO_EMAIL", length = 7)
	private Date dataEnvioEmail;

	/**
	 * Construtor default.
	 */
	public ControleReajuste() {
	}

	/**
	 * 
	 * @param fichaReajuste
	 */
	public ControleReajuste(ControleReajusteStatus controleReajusteStatus,
			FichaReajuste fichaReajuste) {
		this.setFichaReajuste(fichaReajuste);

		this.setControleReajusteStatus(controleReajusteStatus);

		Calendar dataPrevista = Calendar.getInstance();
		dataPrevista.setTime(fichaReajuste.getDataBase());
		dataPrevista
				.add(Calendar.MONTH, fichaReajuste.getNumeroPeriodicidade());
		this.setDataPrevista(dataPrevista.getTime());
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoControleReajuste
	 *            Valor do atributo codigoControleReajuste;
	 * @param controleReajusteStatus
	 *            Valor do atributo controleReajusteStatus;
	 * @param fichaReajuste
	 *            Valor do atributo fichaReajuste;
	 */
	public ControleReajuste(Long codigoControleReajuste,
			ControleReajusteStatus controleReajusteStatus,
			FichaReajuste fichaReajuste) {
		this.codigoControleReajuste = codigoControleReajuste;
		this.controleReajusteStatus = controleReajusteStatus;
		this.fichaReajuste = fichaReajuste;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoControleReajuste
	 *            Valor do atributo codigoControleReajuste;
	 * @param controleReajusteStatus
	 *            Valor do atributo controleReajusteStatus;
	 * @param fichaReajuste
	 *            Valor do atributo fichaReajuste;
	 */
	public ControleReajuste(Long codigoControleReajuste,
			ControleReajusteStatus controleReajusteStatus,
			FichaReajuste fichaReajuste, Date dataPrevista, Date dataReajuste,
			BigDecimal percentualPrevista, BigDecimal percentualRealizada,
			String textoObservacao, Date dataEnvioEmail) {
		this.codigoControleReajuste = codigoControleReajuste;
		this.controleReajusteStatus = controleReajusteStatus;
		this.fichaReajuste = fichaReajuste;
		this.dataPrevista = dataPrevista;
		this.dataReajuste = dataReajuste;
		this.percentualPrevista = percentualPrevista;
		this.percentualRealizada = percentualRealizada;
		this.textoObservacao = textoObservacao;
		this.dataEnvioEmail = dataEnvioEmail;
	}

	/**
	 * Obtem o valor do atributo codigoControleReajuste.<BR>
	 * Atributo gerado a partir da coluna CORE_CD_CONTROLE_REAJUSTE.
	 * 
	 * @return Valor do atributo codigoControleReajuste.
	 */
	public Long getCodigoControleReajuste() {
		return this.codigoControleReajuste;
	}

	/**
	 * Atualiza o valor do atributo codigoControleReajuste.<BR>
	 * Atributo gerado a partir da coluna CORE_CD_CONTROLE_REAJUSTE.
	 * 
	 * @param codigoControleReajuste
	 *            Novo valor para o atributo codigoControleReajuste.
	 */
	public void setCodigoControleReajuste(Long codigoControleReajuste) {
		this.codigoControleReajuste = codigoControleReajuste;
	}

	/**
	 * Obtem o valor do atributo controleReajusteStatus.<BR>
	 * Atributo gerado a partir da coluna CORS_CD_CONTROLE_REAJ_STATUS.
	 * 
	 * @return Valor do atributo controleReajusteStatus.
	 */
	public ControleReajusteStatus getControleReajusteStatus() {
		return this.controleReajusteStatus;
	}

	/**
	 * Atualiza o valor do atributo controleReajusteStatus.<BR>
	 * Atributo gerado a partir da coluna CORS_CD_CONTROLE_REAJ_STATUS.
	 * 
	 * @param controleReajusteStatus
	 *            Novo valor para o atributo controleReajusteStatus.
	 */
	public void setControleReajusteStatus(
			ControleReajusteStatus controleReajusteStatus) {
		this.controleReajusteStatus = controleReajusteStatus;
	}

	/**
	 * Obtem o valor do atributo fichaReajuste.<BR>
	 * Atributo gerado a partir da coluna FIRE_CD_FICHA_REAJUSTE.
	 * 
	 * @return Valor do atributo fichaReajuste.
	 */
	public FichaReajuste getFichaReajuste() {
		return this.fichaReajuste;
	}

	/**
	 * Atualiza o valor do atributo fichaReajuste.<BR>
	 * Atributo gerado a partir da coluna FIRE_CD_FICHA_REAJUSTE.
	 * 
	 * @param fichaReajuste
	 *            Novo valor para o atributo fichaReajuste.
	 */
	public void setFichaReajuste(FichaReajuste fichaReajuste) {
		this.fichaReajuste = fichaReajuste;
	}

	/**
	 * Obtem o valor do atributo dataPrevista.<BR>
	 * Atributo gerado a partir da coluna CORE_DT_PREVISTA.
	 * 
	 * @return Valor do atributo dataPrevista.
	 */
	public Date getDataPrevista() {
		return this.dataPrevista;
	}

	/**
	 * Atualiza o valor do atributo dataPrevista.<BR>
	 * Atributo gerado a partir da coluna CORE_DT_PREVISTA.
	 * 
	 * @param dataPrevista
	 *            Novo valor para o atributo dataPrevista.
	 */
	public void setDataPrevista(Date dataPrevista) {
		this.dataPrevista = dataPrevista;
	}

	/**
	 * Obtem o valor do atributo dataReajuste.<BR>
	 * Atributo gerado a partir da coluna CORE_DT_REAJUSTE.
	 * 
	 * @return Valor do atributo dataReajuste.
	 */
	public Date getDataReajuste() {
		return this.dataReajuste;
	}

	/**
	 * Atualiza o valor do atributo dataReajuste.<BR>
	 * Atributo gerado a partir da coluna CORE_DT_REAJUSTE.
	 * 
	 * @param dataReajuste
	 *            Novo valor para o atributo dataReajuste.
	 */
	public void setDataReajuste(Date dataReajuste) {
		this.dataReajuste = dataReajuste;
	}

	/**
	 * Obtem o valor do atributo percentualPrevista.<BR>
	 * Atributo gerado a partir da coluna CORE_PR_PREVISTA.
	 * 
	 * @return Valor do atributo percentualPrevista.
	 */
	public BigDecimal getPercentualPrevista() {
		return this.percentualPrevista;
	}

	/**
	 * Atualiza o valor do atributo percentualPrevista.<BR>
	 * Atributo gerado a partir da coluna CORE_PR_PREVISTA.
	 * 
	 * @param percentualPrevista
	 *            Novo valor para o atributo percentualPrevista.
	 */
	public void setPercentualPrevista(BigDecimal percentualPrevista) {
		if (percentualPrevista != null) {
			percentualPrevista = percentualPrevista.setScale(4, BigDecimal.ROUND_HALF_UP);
		}
		this.percentualPrevista = percentualPrevista;
	}

	/**
	 * Obtem o valor do atributo percentualRealizada.<BR>
	 * Atributo gerado a partir da coluna CORE_PR_REALIZADA.
	 * 
	 * @return Valor do atributo percentualRealizada.
	 */
	public BigDecimal getPercentualRealizada() {
		return this.percentualRealizada;
	}

	/**
	 * Atualiza o valor do atributo percentualRealizada.<BR>
	 * Atributo gerado a partir da coluna CORE_PR_REALIZADA.
	 * 
	 * @param percentualRealizada
	 *            Novo valor para o atributo percentualRealizada.
	 */
	public void setPercentualRealizada(BigDecimal percentualRealizada) {
		if (percentualRealizada != null) {
			percentualRealizada = percentualRealizada.setScale(4, BigDecimal.ROUND_HALF_UP);
		}
		this.percentualRealizada = percentualRealizada;
	}

	/**
	 * Obtem o valor do atributo textoObservacao.<BR>
	 * Atributo gerado a partir da coluna CORE_TX_OBSERVACAO.
	 * 
	 * @return Valor do atributo textoObservacao.
	 */
	public String getTextoObservacao() {
		return this.textoObservacao;
	}

	/**
	 * Atualiza o valor do atributo textoObservacao.<BR>
	 * Atributo gerado a partir da coluna CORE_TX_OBSERVACAO.
	 * 
	 * @param textoObservacao
	 *            Novo valor para o atributo textoObservacao.
	 */
	public void setTextoObservacao(String textoObservacao) {
		this.textoObservacao = textoObservacao;
	}

	/**
	 * Obtem o valor do atributo dataEnvioEmail.<BR>
	 * Atributo gerado a partir da coluna CORE_DT_ENVIO_EMAIL.
	 * 
	 * @return Valor do atributo dataEnvioEmail.
	 */
	public Date getDataEnvioEmail() {
		return dataEnvioEmail;
	}

	/**
	 * Atualiza o valor do atributo dataEnvioEmail.<BR>
	 * Atributo gerado a partir da coluna CORE_DT_ENVIO_EMAIL.
	 * 
	 * @param dataEnvioEmail
	 *            Novo valor para o atributo dataEnvioEmail.
	 */
	public void setDataEnvioEmail(Date dataEnvioEmail) {
		this.dataEnvioEmail = dataEnvioEmail;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoControleReajuste").append("='")
				.append(getCodigoControleReajuste()).append("' ");
		buffer.append("controleReajusteStatus").append("='")
				.append(getControleReajusteStatus()).append("' ");
		buffer.append("fichaReajuste").append("='").append(getFichaReajuste())
				.append("' ");
		buffer.append("dataPrevista").append("='").append(getDataPrevista())
				.append("' ");
		buffer.append("dataReajuste").append("='").append(getDataReajuste())
				.append("' ");
		buffer.append("percentualPrevista").append("='")
				.append(getPercentualPrevista()).append("' ");
		buffer.append("percentualRealizada").append("='")
				.append(getPercentualRealizada()).append("' ");
		buffer.append("textoObservacao").append("='")
				.append(getTextoObservacao()).append("' ");
		buffer.append("dataEnvioEmail").append("='")
				.append(getDataEnvioEmail()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	/**
	 * Retorna a {@code dataPrevista} do próximo {@link ControleReajuste} para
	 * {@code fichaReajuste}.
	 * 
	 * @param fichaReajuste
	 * @param controleReajuste
	 * @return {@link Date}
	 */
	public Date getDataPrevistaOfNextControleReajuste() {
		Calendar nextDataPrevista = Calendar.getInstance();

		nextDataPrevista.setTime(this.getDataPrevista());
		nextDataPrevista.add(Calendar.MONTH, fichaReajuste.getNumeroPeriodicidade());

		return nextDataPrevista.getTime();
}
}