/*
 * @(#) ContratoPratica.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela CONTRATO_PRATICA_GRUPO_CUSTO. Relacao de
 * Contratos X Praticas
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 12/03/2015 17:14:06
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CONTRATO_PRATICA_GRUPO_CUSTO")
@NamedQueries({
		@NamedQuery(name = "ContratoPraticaGrupoCusto.findAll", query = "SELECT t FROM ContratoPraticaGrupoCusto t "),
		@NamedQuery(name = "ContratoPraticaGrupoCusto.findByContratoPraticaId", query = "SELECT t FROM ContratoPraticaGrupoCusto t "
				+ "WHERE t.contratoPratica.codigoContratoPratica = :codigoContratoPratica ORDER BY t.dataInicioVigencia ASC"),
		@NamedQuery(name = "ContratoPraticaGrupoCusto.findMaxDataInicioVigenciaByContratoPraticaId", query = "SELECT t FROM ContratoPraticaGrupoCusto t "
				+ "WHERE t.contratoPratica.codigoContratoPratica = :codigoContratoPratica "
				+ "AND t.dataInicioVigencia = (SELECT MAX(c.dataInicioVigencia) FROM ContratoPraticaGrupoCusto c WHERE c.contratoPratica.codigoContratoPratica = :codigoContratoPratica)"),
		@NamedQuery(name = "ContratoPraticaGrupoCusto.findByContratoPraticaIdAndDataFimVigencia", query = "SELECT t FROM ContratoPraticaGrupoCusto t "
				+ "WHERE t.contratoPratica.codigoContratoPratica = :codigoContratoPratica AND t.dataFimVigencia = :dataFimVigencia")
})
public class ContratoPraticaGrupoCusto implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "ContratoPratica.findAll".
	 */
	public static final String FIND_ALL = "ContratoPraticaGrupoCusto.findAll";

	public static final String FIND_BY_CONTRATO_PRATICA_ID = "ContratoPraticaGrupoCusto.findByContratoPraticaId";

	public static final String FIND_LAST_MAX_DATA_INICIO_VIGENCIA_CONTRATO_PRATICA_ID = "ContratoPraticaGrupoCusto.findMaxDataInicioVigenciaByContratoPraticaId";

	public static final String FIND_BY_CONTRATO_PRATICA_AND_DATA_FIM_VIGENCIA = "ContratoPraticaGrupoCusto.findByContratoPraticaIdAndDataFimVigencia";

	@Id
	@GeneratedValue(generator = "CodigoContratoPraticaGrupoCustoSeq")
	@SequenceGenerator(name = "CodigoContratoPraticaGrupoCustoSeq", sequenceName = "SQ_CPGC_CONTRATO_PRATICA_GC", allocationSize = 1)
	@Column(name = "CPGC_CONTRATO_PRATICA_GC", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoContratoPraticaGrupoCusto;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COPR_CD_CONTRATO_PRATICA", nullable = false)
	private ContratoPratica contratoPratica;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "GRCU_CD_GRUPO_CUSTO", nullable = false)
	private GrupoCusto grupoCusto;

	@Temporal(TemporalType.DATE)
	@Column(name = "CPGC_DT_INICIO_VIGENCIA", length = 7)
	private Date dataInicioVigencia;

	@Temporal(TemporalType.DATE)
	@Column(name = "CPGC_DT_FIM_VIGENCIA", length = 7)
	private Date dataFimVigencia;

	public ContratoPraticaGrupoCusto() {
	}

	public ContratoPraticaGrupoCusto(ContratoPratica contratoPratica,
			GrupoCusto grupoCusto, Date dataInicioVigencia) {
		this.contratoPratica = contratoPratica;
		this.grupoCusto = grupoCusto;
		this.dataInicioVigencia = dataInicioVigencia;
	}

	public Long getCodigoContratoPraticaGrupoCusto() {
		return codigoContratoPraticaGrupoCusto;
	}

	public void setCodigoContratoPraticaGrupoCusto(
			Long codigoContratoPraticaGrupoCusto) {
		this.codigoContratoPraticaGrupoCusto = codigoContratoPraticaGrupoCusto;
	}

	public ContratoPratica getContratoPratica() {
		return contratoPratica;
	}

	public void setContratoPratica(ContratoPratica contratoPratica) {
		this.contratoPratica = contratoPratica;
	}

	public GrupoCusto getGrupoCusto() {
		return grupoCusto;
	}

	public void setGrupoCusto(GrupoCusto grupoCusto) {
		this.grupoCusto = grupoCusto;
	}

	public Date getDataInicioVigencia() {
		return dataInicioVigencia;
	}

	public void setDataInicioVigencia(Date dataInicioVigencia) {
		this.dataInicioVigencia = dataInicioVigencia;
	}

	public Date getDataFimVigencia() {
		return dataFimVigencia;
	}

	public void setDataFimVigencia(Date dataFimVigencia) {
		this.dataFimVigencia = dataFimVigencia;
	}
}