/*
 * @(#) ControleReajusteAud.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela CONTROLE_REAJUSTE_AUD.
 * 
 * @author Generated by Hibernate Tools 3.6.0
 * @since 20/12/2013 10:32:08
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CONTROLE_REAJUSTE_AUD")
@NamedQueries({
		@NamedQuery(name = "ControleReajusteAud.findAll", query = "SELECT t FROM ControleReajusteAud t"),
		@NamedQuery(name = "ControleReajusteAud.findByCodigoControleReajuste", query = "SELECT t FROM ControleReajusteAud t "
				+ "WHERE t.id.codigoControleReajuste = :codigoControleReajuste "
				+ "ORDER BY t.id.revinfo.revtstmp"),
		@NamedQuery(name = "ControleReajusteAud.findByCodigoControleReajusteAndRevtype", query = "SELECT t FROM ControleReajusteAud t "
				+ "WHERE t.id.codigoControleReajuste = :codigoControleReajuste "
				+ "AND t.revType = :revtype") })
public class ControleReajusteAud implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "ControleReajusteAud.findAll".
	 */
	public static final String FIND_ALL = "ControleReajusteAud.findAll";

	/**
	 * Constante para NamedQuery
	 * "ControleReajusteAud.findByCodigoControleReajuste".
	 */
	public static final String FIND_BY_CODIGO_CONTROLE_REAJUSTE = "ControleReajusteAud.findByCodigoControleReajuste";
	
	/**
	 * Constante para NamedQuery
	 * "ControleReajusteAud.findByCodigoControleReajusteAndRevtype".
	 */
	public static final String FIND_BY_CODIGO_CONTROLE_REAJUSTE_AND_REVTYPE = "ControleReajusteAud.findByCodigoControleReajusteAndRevtype";

	/**
	 * Chave.
	 */
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoControleReajuste", column = @Column(name = "CORE_CD_CONTROLE_REAJUSTE", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "revinfo.rev", column = @Column(name = "REV", nullable = false, precision = 18, scale = 0)) })
	private ControleReajusteAudId id;

	/**
	 * Atributo gerado a partir da coluna REVTYPE.
	 */
	@Column(name = "REVTYPE", precision = 3, scale = 0)
	private Long revType;

	/**
	 * Atributo gerado a partir da coluna FIRE_CD_FICHA_REAJUSTE.
	 */
	@Column(name = "FIRE_CD_FICHA_REAJUSTE", length = 7)
	private Long codigoFichaReajuste;

	/**
	 * Atributo gerado a partir da coluna CORE_DT_PREVISTA.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "CORE_DT_PREVISTA", length = 7)
	private Date dataPrevista;

	/**
	 * Atributo gerado a partir da coluna CORE_DT_REAJUSTE.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "CORE_DT_REAJUSTE", length = 7)
	private Date dataReajuste;

	/**
	 * Atributo gerado a partir da coluna CORE_PR_PREVISTA.
	 */
	@Column(name = "CORE_PR_PREVISTA", precision = 18, scale = 0)
	private Long percentualPrevista;

	/**
	 * Atributo gerado a partir da coluna CORE_PR_REALIZADA.
	 */

	@Column(name = "CORE_PR_REALIZADA", precision = 18, scale = 0)
	private Long percentualRealizada;

	/**
	 * Atributo gerado a partir da coluna CORS_CD_CONTROLE_REAJ_STATUS.
	 */

	@Column(name = "CORS_CD_CONTROLE_REAJ_STATUS", precision = 18, scale = 0)
	private Long codigoControleReajStatus;

	/**
	 * Atributo gerado a partir da coluna CORE_TX_OBSERVACAO.
	 */

	@Column(name = "CORE_TX_OBSERVACAO", length = 1000)
	private String textoObservacao;

	/**
	 * Atributo gerado a partir da coluna CORE_DT_ENVIO_EMAIL.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "CORE_DT_ENVIO_EMAIL", length = 7)
	private Date dataEnvioEmail;

	/**
	 * Construtor default.
	 */
	public ControleReajusteAud() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param id
	 *            Valor do atributo id;
	 */
	public ControleReajusteAud(ControleReajusteAudId id) {
		this.id = id;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param id
	 * @param revType
	 * @param codigoFichaReajuste
	 * @param dataPrevista
	 * @param dataReajuste
	 * @param percentualPrevista
	 * @param percentualRealizada
	 * @param codigoControleReajStatus
	 * @param textoObservacao
	 * @param dataEnvioEmail
	 */
	public ControleReajusteAud(ControleReajusteAudId id, Long revType,
			Long codigoFichaReajuste, Date dataPrevista, Date dataReajuste,
			Long percentualPrevista, Long percentualRealizada,
			Long codigoControleReajStatus, String textoObservacao,
			Date dataEnvioEmail) {
		this.id = id;
		this.revType = revType;
		this.codigoFichaReajuste = codigoFichaReajuste;
		this.dataPrevista = dataPrevista;
		this.dataReajuste = dataReajuste;
		this.percentualPrevista = percentualPrevista;
		this.percentualRealizada = percentualRealizada;
		this.codigoControleReajStatus = codigoControleReajStatus;
		this.textoObservacao = textoObservacao;
		this.dataEnvioEmail = dataEnvioEmail;
	}

	/**
	 * Obtem o valor do atributo id.<BR>
	 * Atributo gerado a partir da coluna REV.
	 * 
	 * @return Valor do atributo id.
	 */
	public ControleReajusteAudId getId() {
		return this.id;
	}

	/**
	 * Atualiza o valor do atributo id.<BR>
	 * Atributo gerado a partir da coluna REV.
	 * 
	 * @param id
	 *            Novo valor para o atributo id.
	 */
	public void setId(ControleReajusteAudId id) {
		this.id = id;
	}

	/**
	 * Obtem o valor do atributo .<BR>
	 * Atributo gerado a partir da coluna REVTYPE.
	 * 
	 * @return Valor do atributo .
	 */
	public Long getRevType() {
		return this.revType;
	}

	/**
	 * Atualiza o valor do atributo .<BR>
	 * Atributo gerado a partir da coluna REVTYPE.
	 * 
	 * @param Novo
	 *            valor para o atributo .
	 */
	public void setRevType(Long revType) {
		this.revType = revType;
	}

	/**
	 * Obtem o valor do atributo codigoFichaReajuste.<BR>
	 * Atributo gerado a partir da coluna FIRE_CD_FICHA_REAJUSTE.
	 * 
	 * @return Valor do atributo codigoFichaReajuste.
	 */
	public Long getCodigoFichaReajuste() {
		return this.codigoFichaReajuste;
	}

	/**
	 * Atualiza o valor do atributo codigoFichaReajuste.<BR>
	 * Atributo gerado a partir da coluna FIRE_CD_FICHA_REAJUSTE.
	 * 
	 * @param codigoFichaReajuste
	 *            Novo valor para o atributo codigoFichaReajuste.
	 */
	public void setCodigoFichaReajuste(Long codigoFichaReajuste) {
		this.codigoFichaReajuste = codigoFichaReajuste;
	}

	/**
	 * Obtem o valor do atributo dataPrevista.<BR>
	 * Atributo gerado a partir da coluna CORE_DT_PREVISTA.
	 * 
	 * @return Valor do atributo dataPrevista.
	 */
	public Date getDataPrevista() {
		return this.dataPrevista;
	}

	/**
	 * Atualiza o valor do atributo dataPrevista.<BR>
	 * Atributo gerado a partir da coluna CORE_DT_PREVISTA.
	 * 
	 * @param dataPrevista
	 *            Novo valor para o atributo dataPrevista.
	 */
	public void setDataPrevista(Date dataPrevista) {
		this.dataPrevista = dataPrevista;
	}

	/**
	 * Obtem o valor do atributo dataReajuste.<BR>
	 * Atributo gerado a partir da coluna CORE_DT_REAJUSTE.
	 * 
	 * @return Valor do atributo dataReajuste.
	 */
	public Date getDataReajuste() {
		return this.dataReajuste;
	}

	/**
	 * Atualiza o valor do atributo dataReajuste.<BR>
	 * Atributo gerado a partir da coluna CORE_DT_REAJUSTE.
	 * 
	 * @param dataReajuste
	 *            Novo valor para o atributo dataReajuste.
	 */
	public void setDataReajuste(Date dataReajuste) {
		this.dataReajuste = dataReajuste;
	}

	/**
	 * Obtem o valor do atributo percentualPrevista.<BR>
	 * Atributo gerado a partir da coluna CORE_PR_PREVISTA.
	 * 
	 * @return Valor do atributo percentualPrevista.
	 */
	public Long getPercentualPrevista() {
		return this.percentualPrevista;
	}

	/**
	 * Atualiza o valor do atributo percentualPrevista.<BR>
	 * Atributo gerado a partir da coluna CORE_PR_PREVISTA.
	 * 
	 * @param percentualPrevista
	 *            Novo valor para o atributo percentualPrevista.
	 */
	public void setPercentualPrevista(Long percentualPrevista) {
		this.percentualPrevista = percentualPrevista;
	}

	/**
	 * Obtem o valor do atributo percentualRealizada.<BR>
	 * Atributo gerado a partir da coluna CORE_PR_REALIZADA.
	 * 
	 * @return Valor do atributo percentualRealizada.
	 */
	public Long getPercentualRealizada() {
		return this.percentualRealizada;
	}

	/**
	 * Atualiza o valor do atributo percentualRealizada.<BR>
	 * Atributo gerado a partir da coluna CORE_PR_REALIZADA.
	 * 
	 * @param percentualRealizada
	 *            Novo valor para o atributo percentualRealizada.
	 */
	public void setPercentualRealizada(Long percentualRealizada) {
		this.percentualRealizada = percentualRealizada;
	}

	/**
	 * Obtem o valor do atributo codigoControleReajStatus.<BR>
	 * Atributo gerado a partir da coluna CORS_CD_CONTROLE_REAJ_STATUS.
	 * 
	 * @return Valor do atributo codigoControleReajStatus.
	 */
	public Long getCodigoControleReajStatus() {
		return this.codigoControleReajStatus;
	}

	/**
	 * Atualiza o valor do atributo codigoControleReajStatus.<BR>
	 * Atributo gerado a partir da coluna CORS_CD_CONTROLE_REAJ_STATUS.
	 * 
	 * @param codigoControleReajStatus
	 *            Novo valor para o atributo codigoControleReajStatus.
	 */
	public void setCodigoControleReajStatus(Long codigoControleReajStatus) {
		this.codigoControleReajStatus = codigoControleReajStatus;
	}

	/**
	 * Obtem o valor do atributo textoObservacao.<BR>
	 * Atributo gerado a partir da coluna CORE_TX_OBSERVACAO.
	 * 
	 * @return Valor do atributo textoObservacao.
	 */
	public String getTextoObservacao() {
		return this.textoObservacao;
	}

	/**
	 * Atualiza o valor do atributo textoObservacao.<BR>
	 * Atributo gerado a partir da coluna CORE_TX_OBSERVACAO.
	 * 
	 * @param textoObservacao
	 *            Novo valor para o atributo textoObservacao.
	 */
	public void setTextoObservacao(String textoObservacao) {
		this.textoObservacao = textoObservacao;
	}

	/**
	 * Obtem o valor do atributo dataEnvioEmail.<BR>
	 * Atributo gerado a partir da coluna CORE_DT_ENVIO_EMAIL.
	 * 
	 * @return Valor do atributo dataEnvioEmail.
	 */
	public Date getDataEnvioEmail() {
		return this.dataEnvioEmail;
	}

	/**
	 * Atualiza o valor do atributo dataEnvioEmail.<BR>
	 * Atributo gerado a partir da coluna CORE_DT_ENVIO_EMAIL.
	 * 
	 * @param dataEnvioEmail
	 *            Novo valor para o atributo dataEnvioEmail.
	 */
	public void setDataEnvioEmail(Date dataEnvioEmail) {
		this.dataEnvioEmail = dataEnvioEmail;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("revType").append("='").append(getRevType()).append("' ");
		buffer.append("codigoFichaReajuste").append("='")
				.append(getCodigoFichaReajuste()).append("' ");
		buffer.append("dataPrevista").append("='").append(getDataPrevista())
				.append("' ");
		buffer.append("dataReajuste").append("='").append(getDataReajuste())
				.append("' ");
		buffer.append("percentualPrevista").append("='")
				.append(getPercentualPrevista()).append("' ");
		buffer.append("percentualRealizada").append("='")
				.append(getPercentualRealizada()).append("' ");
		buffer.append("codigoControleReajStatus").append("='")
				.append(getCodigoControleReajStatus()).append("' ");
		buffer.append("textoObservacao").append("='")
				.append(getTextoObservacao()).append("' ");
		buffer.append("dataEnvioEmail").append("='")
				.append(getDataEnvioEmail()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
