/*
 * @(#) ContratoPraticaOrcDespCl.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela CONTRATO_PRATICA_ORC_DESP_CL.
 * 
 * @author Generated by Hibernate Tools 3.6.0
 * @since 11/04/2013 10:24:53
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CONTRATO_PRATICA_ORC_DESP_CL")
@NamedQueries({ 
	@NamedQuery(name = "ContratoPraticaOrcDespCl.findAll", query = "SELECT t FROM ContratoPraticaOrcDespCl t"),
	@NamedQuery(name = "ContratoPraticaOrcDespCl.findByOrcDespCl", query = "SELECT t FROM ContratoPraticaOrcDespCl t "
			+ " WHERE t.orcDespesaCl.codigoOrcaDespCl = ?")
})
public class ContratoPraticaOrcDespCl implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "ContratoPraticaOrcDespCl.findAll".
	 */
	public static final String FIND_ALL = "ContratoPraticaOrcDespCl.findAll";
	
	/**
	 * Constante para NamedQuery "ContratoPraticaOrcDespCl.findByOrcDespCl".
	 */
	public static final String FIND_BY_ORC_DESP_CL = "ContratoPraticaOrcDespCl.findByOrcDespCl";

	/**
	 * Atributo gerado a partir da coluna ORDC_CD_ORCA_DESP_CL.
	 */
	@EmbeddedId
	@GeneratedValue(generator = "ContratoPraticaOrcDespClSeq")
	@SequenceGenerator(name = "ContratoPraticaOrcDespClSeq", sequenceName = "SQ_COPR_CD_CONTRATO_PRATICA", allocationSize = 1)
	@AttributeOverrides({
			@AttributeOverride(name = "codigoContratoPratica", column = @Column(name = "COPR_CD_CONTRATO_PRATICA", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "codigoOrcaDespCl", column = @Column(name = "ORDC_CD_ORCA_DESP_CL", nullable = false, precision = 18, scale = 0)) })
	private ContratoPraticaOrcDespClId id;

	/**
	 * Atributo gerado a partir da coluna ORDC_CD_ORCA_DESP_CL.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDC_CD_ORCA_DESP_CL", nullable = false, insertable = false, updatable = false)
	private OrcDespesaCl orcDespesaCl;

	/**
	 * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COPR_CD_CONTRATO_PRATICA", nullable = false, insertable = false, updatable = false)
	private ContratoPratica contratoPratica;

	/**
	 * Construtor default.
	 */
	public ContratoPraticaOrcDespCl() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param id
	 *            Valor do atributo id;
	 * 
	 */
	public ContratoPraticaOrcDespCl(final ContratoPraticaOrcDespClId id) {
		this.id = id;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param id
	 *            Valor do atributo id;
	 * @param orcDespesaCl
	 *            Valor do atributo orcDespesaCl;
	 * @param contratoPratica
	 *            Valor do atributo contratoPratica;
	 */
	public ContratoPraticaOrcDespCl(final ContratoPraticaOrcDespClId id,
			final OrcDespesaCl orcDespesaCl,
			final ContratoPratica contratoPratica) {
		this.id = id;
		this.orcDespesaCl = orcDespesaCl;
		this.contratoPratica = contratoPratica;
	}

	/**
	 * Obtem o valor do atributo id.<BR>
	 * Atributo gerado a partir da coluna ORDC_CD_ORCA_DESP_CL.
	 * 
	 * @return Valor do atributo id.
	 */
	public ContratoPraticaOrcDespClId getId() {
		return this.id;
	}

	/**
	 * Atualiza o valor do atributo id.<BR>
	 * Atributo gerado a partir da coluna ORDC_CD_ORCA_DESP_CL.
	 * 
	 * @param id
	 *            Novo valor para o atributo id.
	 */
	public void setId(ContratoPraticaOrcDespClId id) {
		this.id = id;
	}

	/**
	 * Obtem o valor do atributo orcDespesaCl.<BR>
	 * Atributo gerado a partir da coluna ORDC_CD_ORCA_DESP_CL.
	 * 
	 * @return Valor do atributo orcDespesaCl.
	 */
	public OrcDespesaCl getOrcDespesaCl() {
		return this.orcDespesaCl;
	}

	/**
	 * Atualiza o valor do atributo orcDespesaCl.<BR>
	 * Atributo gerado a partir da coluna ORDC_CD_ORCA_DESP_CL.
	 * 
	 * @param orcDespesaCl
	 *            Novo valor para o atributo orcDespesaCl.
	 */
	public void setOrcDespesaCl(OrcDespesaCl orcDespesaCl) {
		this.orcDespesaCl = orcDespesaCl;
	}

	/**
	 * Obtem o valor do atributo contratoPratica.<BR>
	 * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
	 * 
	 * @return Valor do atributo contratoPratica.
	 */
	public ContratoPratica getContratoPratica() {
		return this.contratoPratica;
	}

	/**
	 * Atualiza o valor do atributo contratoPratica.<BR>
	 * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
	 * 
	 * @param contratoPratica
	 *            Novo valor para o atributo contratoPratica.
	 */
	public void setContratoPratica(ContratoPratica contratoPratica) {
		this.contratoPratica = contratoPratica;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("orcDespesaCl").append("='").append(getOrcDespesaCl())
				.append("' ");
		buffer.append("contratoPratica").append("='")
				.append(getContratoPratica()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
