/*
 * @(#) ControleReajusteAudId.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * ControleReajusteAudId generated by hbm2java
 * 
 * @author Generated by Hibernate Tools 3.6.0
 * @since 20/12/2013 10:32:08
 * @version 09/01/19 1.1 10:08:00
 */
@Embeddable
public class ControleReajusteAudId implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "ControleReajusteAudId.findAll".
	 */
	public static final String FIND_ALL = "ControleReajusteAudId.findAll";

	@Column(name = "CORE_CD_CONTROLE_REAJUSTE", nullable = false, precision = 18, scale = 0)
	private Long codigoControleReajuste;

	/**
	 * Atributo gerado a partir da coluna REV.
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "REV", nullable = false, insertable = false, updatable = false)
	private PMSRevisionEntity revinfo;

	/**
	 * Construtor default.
	 */
	public ControleReajusteAudId() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoControleReajuste
	 *            Valor do atributo codigoControleReajuste;
	 * @param Valor
	 *            do atributo revinfo;
	 */
	public ControleReajusteAudId(Long codigoControleReajuste,
			PMSRevisionEntity revinfo) {
		this.codigoControleReajuste = codigoControleReajuste;
		this.revinfo = revinfo;
	}

	/**
	 * Obtem o valor do atributo codigoControleReajuste.<BR>
	 * 
	 * @return Valor do atributo codigoControleReajuste.
	 */
	public Long getCodigoControleReajuste() {
		return this.codigoControleReajuste;
	}

	/**
	 * Atualiza o valor do atributo codigoControleReajuste.<BR>
	 * 
	 * @param codigoControleReajuste
	 *            Novo valor para o atributo codigoControleReajuste.
	 */
	public void setCodigoControleReajuste(Long codigoControleReajuste) {
		this.codigoControleReajuste = codigoControleReajuste;
	}

	/**
	 * Obtem o valor do atributo revinfo.<BR>
	 * 
	 * @return Valor do atributo revinfo.
	 */
	public PMSRevisionEntity getRevinfo() {
		return revinfo;
	}

	/**
	 * Atualiza o valor do atributo revinfo.<BR>
	 * 
	 * @param codigoControleReajuste
	 *            Novo valor para o atributo revinfo.
	 */
	public void setRevinfo(PMSRevisionEntity revinfo) {
		this.revinfo = revinfo;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((codigoControleReajuste == null) ? 0
						: codigoControleReajuste.hashCode());
		result = prime * result + ((revinfo == null) ? 0 : revinfo.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ControleReajusteAudId other = (ControleReajusteAudId) obj;
		if (codigoControleReajuste == null) {
			if (other.codigoControleReajuste != null)
				return false;
		} else if (!codigoControleReajuste.equals(other.codigoControleReajuste))
			return false;
		if (revinfo == null) {
			if (other.revinfo != null)
				return false;
		} else if (!revinfo.equals(other.revinfo))
			return false;
		return true;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ControleReajusteAudId [codigoControleReajuste=");
		builder.append(codigoControleReajuste);
		builder.append(", revinfo=");
		builder.append(revinfo);
		builder.append("]");
		return builder.toString();
	}

}
