/*
 * @(#) ControleReajusteStatus.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela CONTROLE_REAJUSTE_STATUS.
 *
 * @author Generated by Hibernate Tools 3.6.0
 * @since 06/12/2013 16:56:59
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CONTROLE_REAJUSTE_STATUS")
@NamedQueries({
	@NamedQuery(name = "ControleReajusteStatus.findAll", query = "SELECT t FROM ControleReajusteStatus t"),
	@NamedQuery(name = "ControleReajusteStatus.findAllActive", query = "SELECT t FROM ControleReajusteStatus t"
			+ " WHERE t.indicadorAtivo = :indicadorAtivo"),
	@NamedQuery(name = "ControleReajusteStatus.findBySiglaControleReajStatus", query = "SELECT t FROM ControleReajusteStatus t"
			+ " WHERE t.siglaControleReajStatus = :siglaControleReajStatus")
})
public class ControleReajusteStatus implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * Constante para NamedQuery "ControleReajusteStatus.findAll".
	 */
	public static final String FIND_ALL = "ControleReajusteStatus.findAll";
	
	/** 
	 * Constante para NamedQuery "ControleReajusteStatus.findAllActive".
	 */
	public static final String FIND_ALL_ACTIVE = "ControleReajusteStatus.findAllActive";
	
	/** 
	 * Constante para NamedQuery "ControleReajusteStatus.findAll".
	 */
	public static final String FIND_BY_SIGLA_CONTROLE_REAJ_STATUS = "ControleReajusteStatus.findBySiglaControleReajStatus";

	/**
	 * Atributo gerado a partir da coluna CORS_CD_CONTROLE_REAJ_STATUS.
	 */
	@Id
	@GeneratedValue(generator = "ControleReajusteStatusSeq")
	@SequenceGenerator(name = "ControleReajusteStatusSeq", sequenceName = "SQ_CORS_CD_CONTROLE_REAJ_STATUS", allocationSize = 1)
	@Column(name = "CORS_CD_CONTROLE_REAJ_STATUS", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoControleReajStatus;

	/**
	 * Atributo gerado a partir da coluna CORS_NM_CONTROLE_REAJ_STATUS.
	 */

	@Column(name = "CORS_NM_CONTROLE_REAJ_STATUS", length = 50)
	private String nomeControleReajStatus;

	/**
	 * Atributo gerado a partir da coluna CORS_SG_CONTROLE_REAJ_STATUS.
	 */

	@Column(name = "CORS_SG_CONTROLE_REAJ_STATUS", length = 2)
	private String siglaControleReajStatus;

	/**
	 * Atributo gerado a partir da coluna CORS_IN_ATIVO.
	 */

	@Column(name = "CORS_IN_ATIVO", length = 1)
	private String indicadorAtivo;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "controleReajusteStatus")
	private Set<ControleReajuste> controleReajustes = new HashSet<ControleReajuste>(
			0);

	/**
	 * Construtor default.
	 */
	public ControleReajusteStatus() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * @param codigoControleReajStatus Valor do atributo codigoControleReajStatus;
	 */
	public ControleReajusteStatus(Long codigoControleReajStatus) {
		this.codigoControleReajStatus = codigoControleReajStatus;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * @param codigoControleReajStatus Valor do atributo codigoControleReajStatus;
	 */
	public ControleReajusteStatus(Long codigoControleReajStatus,
			String nomeControleReajStatus, String siglaControleReajStatus,
			String indicadorAtivo, Set<ControleReajuste> controleReajustes) {
		this.codigoControleReajStatus = codigoControleReajStatus;
		this.nomeControleReajStatus = nomeControleReajStatus;
		this.siglaControleReajStatus = siglaControleReajStatus;
		this.indicadorAtivo = indicadorAtivo;
		this.controleReajustes = controleReajustes;
	}

	/**
	 * Obtem o valor do atributo codigoControleReajStatus.<BR>
	 * Atributo gerado a partir da coluna CORS_CD_CONTROLE_REAJ_STATUS.
	 * @return Valor do atributo codigoControleReajStatus.
	 */
	public Long getCodigoControleReajStatus() {
		return this.codigoControleReajStatus;
	}

	/**
	 * Atualiza o valor do atributo codigoControleReajStatus.<BR>
	 * Atributo gerado a partir da coluna CORS_CD_CONTROLE_REAJ_STATUS.
	 * @param codigoControleReajStatus Novo valor para o atributo codigoControleReajStatus.
	 */
	public void setCodigoControleReajStatus(Long codigoControleReajStatus) {
		this.codigoControleReajStatus = codigoControleReajStatus;
	}

	/**
	 * Obtem o valor do atributo nomeControleReajStatus.<BR>
	 * Atributo gerado a partir da coluna CORS_NM_CONTROLE_REAJ_STATUS.
	 * @return Valor do atributo nomeControleReajStatus.
	 */
	public String getNomeControleReajStatus() {
		return this.nomeControleReajStatus;
	}

	/**
	 * Atualiza o valor do atributo nomeControleReajStatus.<BR>
	 * Atributo gerado a partir da coluna CORS_NM_CONTROLE_REAJ_STATUS.
	 * @param nomeControleReajStatus Novo valor para o atributo nomeControleReajStatus.
	 */
	public void setNomeControleReajStatus(String nomeControleReajStatus) {
		this.nomeControleReajStatus = nomeControleReajStatus;
	}

	/**
	 * Obtem o valor do atributo siglaControleReajStatus.<BR>
	 * Atributo gerado a partir da coluna CORS_SG_CONTROLE_REAJ_STATUS.
	 * @return Valor do atributo siglaControleReajStatus.
	 */
	public String getSiglaControleReajStatus() {
		return this.siglaControleReajStatus;
	}

	/**
	 * Atualiza o valor do atributo siglaControleReajStatus.<BR>
	 * Atributo gerado a partir da coluna CORS_SG_CONTROLE_REAJ_STATUS.
	 * @param siglaControleReajStatus Novo valor para o atributo siglaControleReajStatus.
	 */
	public void setSiglaControleReajStatus(String siglaControleReajStatus) {
		this.siglaControleReajStatus = siglaControleReajStatus;
	}

	/**
	 * Obtem o valor do atributo indicadorAtivo.<BR>
	 * Atributo gerado a partir da coluna CORS_IN_ATIVO.
	 * @return Valor do atributo indicadorAtivo.
	 */
	public String getIndicadorAtivo() {
		return this.indicadorAtivo;
	}

	/**
	 * Atualiza o valor do atributo indicadorAtivo.<BR>
	 * Atributo gerado a partir da coluna CORS_IN_ATIVO.
	 * @param indicadorAtivo Novo valor para o atributo indicadorAtivo.
	 */
	public void setIndicadorAtivo(String indicadorAtivo) {
		this.indicadorAtivo = indicadorAtivo;
	}

	/**
	 * Obtem o valor do atributo controleReajustes.<BR>

	 * @return Valor do atributo controleReajustes.
	 */
	public Set<ControleReajuste> getControleReajustes() {
		return this.controleReajustes;
	}

	/**
	 * Atualiza o valor do atributo controleReajustes.<BR>

	 * @param controleReajustes Novo valor para o atributo controleReajustes.
	 */
	public void setControleReajustes(Set<ControleReajuste> controleReajustes) {
		this.controleReajustes = controleReajustes;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoControleReajStatus").append("='")
				.append(getCodigoControleReajStatus()).append("' ");
		buffer.append("nomeControleReajStatus").append("='")
				.append(getNomeControleReajStatus()).append("' ");
		buffer.append("siglaControleReajStatus").append("='")
				.append(getSiglaControleReajStatus()).append("' ");
		buffer.append("indicadorAtivo").append("='")
				.append(getIndicadorAtivo()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
