/*
 * @(#) CustoPessoaCp.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela CUSTO_PESSOA_CP.
 * Ainda nao esta sendo utilizado
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 30/08/2010 09:46:34
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CUSTO_PESSOA_CP")
@NamedQueries({ 
    @NamedQuery(name = "CustoPessoaCp.findAll", query = "SELECT t FROM CustoPessoaCp t")
})
public class CustoPessoaCp implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "CustoPessoaCp.findAll".
     */
    public static final String FIND_ALL = "CustoPessoaCp.findAll";

    /**
     * Atributo gerado a partir da coluna CUPC_CD_CUSTO_PESSOA_CP.
     */
    @Id
    @GeneratedValue(generator = "CustoPessoaCpSeq")
    @SequenceGenerator(name = "CustoPessoaCpSeq", sequenceName = "SQ_CUPC_CD_CUSTO_PESSOA_CP", allocationSize = 1)
    @Column(name = "CUPC_CD_CUSTO_PESSOA_CP", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoCustoPessoaCp;

    /**
     * Atributo gerado a partir da coluna CUPM_CD_CUSTO_PESSOA_MES.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CUPM_CD_CUSTO_PESSOA_MES", nullable = false)
    private CustoPessoaMes custoPessoaMes;

    /**
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COPR_CD_CONTRATO_PRATICA", nullable = false)
    private ContratoPratica contratoPratica;

    /**
     * Atributo gerado a partir da coluna CUPC_PR_APROPRIADO.
     */

    @Column(name = "CUPC_PR_APROPRIADO", precision = 22, scale = 0)
    private BigDecimal percentualApropriado;

    /**
     * Atributo gerado a partir da coluna CUPC_NR_HORAS.
     */

    @Column(name = "CUPC_NR_HORAS", precision = 22, scale = 0)
    private BigDecimal numeroHoras;

    /**
     * Atributo gerado a partir da coluna CUPC_VL_FATOR.
     */

    @Column(name = "CUPC_VL_FATOR", precision = 22, scale = 0)
    private BigDecimal valorFator;

    /**
     * Atributo gerado a partir da coluna CUPC_VL_APROPRIADO.
     */
    @Column(name = "CUPC_VL_APROPRIADO", precision = 22, scale = 0)
    private BigDecimal valorApropriado;

    /**
     * Construtor default.
     */
    public CustoPessoaCp() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoCustoPessoaCp Valor do atributo codigoCustoPessoaCp;
     * @param custoPessoaMes Valor do atributo custoPessoaMes;
     * @param contratoPratica Valor do atributo contratoPratica;
     */
    public CustoPessoaCp(final Long codigoCustoPessoaCp,
            final CustoPessoaMes custoPessoaMes, final ContratoPratica contratoPratica) {
        this.codigoCustoPessoaCp = codigoCustoPessoaCp;
        this.custoPessoaMes = custoPessoaMes;
        this.contratoPratica = contratoPratica;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoCustoPessoaCp Valor do atributo codigoCustoPessoaCp;
     * @param custoPessoaMes Valor do atributo custoPessoaMes;
     * @param contratoPratica Valor do atributo contratoPratica;
     * @param percentualApropriado Valor do atributo percentualApropriado;
     * @param numeroHoras Valor do atributo numeroHoras;
     * @param valorFator Valor do atributo valorFator;
     * @param valorApropriado Valor do atributo valorApropriado;
     */
    public CustoPessoaCp(final Long codigoCustoPessoaCp,
            final CustoPessoaMes custoPessoaMes, final ContratoPratica contratoPratica,
            final BigDecimal percentualApropriado, final BigDecimal numeroHoras,
            final BigDecimal valorFator, final BigDecimal valorApropriado) {
        this.codigoCustoPessoaCp = codigoCustoPessoaCp;
        this.custoPessoaMes = custoPessoaMes;
        this.contratoPratica = contratoPratica;
        this.percentualApropriado = percentualApropriado;
        this.numeroHoras = numeroHoras;
        this.valorFator = valorFator;
        this.valorApropriado = valorApropriado;
    }

    /**
     * Obtem o valor do atributo codigoCustoPessoaCp.<BR>
     * Atributo gerado a partir da coluna CUPC_CD_CUSTO_PESSOA_CP.
     * @return Valor do atributo codigoCustoPessoaCp.
     */
    public Long getCodigoCustoPessoaCp() {
        return this.codigoCustoPessoaCp;
    }

    /**
     * Atualiza o valor do atributo codigoCustoPessoaCp.<BR>
     * Atributo gerado a partir da coluna CUPC_CD_CUSTO_PESSOA_CP.
     * @param codigoCustoPessoaCp Novo valor para o atributo codigoCustoPessoaCp.
     */
    public void setCodigoCustoPessoaCp(final Long codigoCustoPessoaCp) {
        this.codigoCustoPessoaCp = codigoCustoPessoaCp;
    }

    /**
     * Obtem o valor do atributo custoPessoaMes.<BR>
     * Atributo gerado a partir da coluna CUPM_CD_CUSTO_PESSOA_MES.
     * @return Valor do atributo custoPessoaMes.
     */
    public CustoPessoaMes getCustoPessoaMes() {
        return this.custoPessoaMes;
    }

    /**
     * Atualiza o valor do atributo custoPessoaMes.<BR>
     * Atributo gerado a partir da coluna CUPM_CD_CUSTO_PESSOA_MES.
     * @param custoPessoaMes Novo valor para o atributo custoPessoaMes.
     */
    public void setCustoPessoaMes(final CustoPessoaMes custoPessoaMes) {
        this.custoPessoaMes = custoPessoaMes;
    }

    /**
     * Obtem o valor do atributo contratoPratica.<BR>
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     * @return Valor do atributo contratoPratica.
     */
    public ContratoPratica getContratoPratica() {
        return this.contratoPratica;
    }

    /**
     * Atualiza o valor do atributo contratoPratica.<BR>
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     * @param contratoPratica Novo valor para o atributo contratoPratica.
     */
    public void setContratoPratica(final ContratoPratica contratoPratica) {
        this.contratoPratica = contratoPratica;
    }

    /**
     * Obtem o valor do atributo percentualApropriado.<BR>
     * Atributo gerado a partir da coluna CUPC_PR_APROPRIADO.
     * @return Valor do atributo percentualApropriado.
     */
    public BigDecimal getPercentualApropriado() {
        return this.percentualApropriado;
    }

    /**
     * Atualiza o valor do atributo percentualApropriado.<BR>
     * Atributo gerado a partir da coluna CUPC_PR_APROPRIADO.
     * @param percentualApropriado Novo valor para o atributo percentualApropriado.
     */
    public void setPercentualApropriado(final BigDecimal percentualApropriado) {
        this.percentualApropriado = percentualApropriado;
    }

    /**
     * Obtem o valor do atributo numeroHoras.<BR>
     * Atributo gerado a partir da coluna CUPC_NR_HORAS.
     * @return Valor do atributo numeroHoras.
     */
    public BigDecimal getNumeroHoras() {
        return this.numeroHoras;
    }

    /**
     * Atualiza o valor do atributo numeroHoras.<BR>
     * Atributo gerado a partir da coluna CUPC_NR_HORAS.
     * @param numeroHoras Novo valor para o atributo numeroHoras.
     */
    public void setNumeroHoras(final BigDecimal numeroHoras) {
        this.numeroHoras = numeroHoras;
    }

    /**
     * Obtem o valor do atributo valorFator.<BR>
     * Atributo gerado a partir da coluna CUPC_VL_FATOR.
     * @return Valor do atributo valorFator.
     */
    public BigDecimal getValorFator() {
        return this.valorFator;
    }

    /**
     * Atualiza o valor do atributo valorFator.<BR>
     * Atributo gerado a partir da coluna CUPC_VL_FATOR.
     * @param valorFator Novo valor para o atributo valorFator.
     */
    public void setValorFator(final BigDecimal valorFator) {
        this.valorFator = valorFator;
    }

    /**
     * Obtem o valor do atributo valorApropriado.<BR>
     * Atributo gerado a partir da coluna CUTG_VL_APROPRIADO.
     * @return Valor do atributo valorApropriado.
     */
    public BigDecimal getValorApropriado() {
        return this.valorApropriado;
    }

    /**
     * Atualiza o valor do atributo valorApropriado.<BR>
     * Atributo gerado a partir da coluna CUTG_VL_APROPRIADO.
     * @param valorApropriado Novo valor para o atributo valorApropriado.
     */
    public void setValorApropriado(final BigDecimal valorApropriado) {
        this.valorApropriado = valorApropriado;
    }  

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoCustoPessoaCp").append("='").append(
                getCodigoCustoPessoaCp()).append("' ");
        buffer.append("custoPessoaMes").append("='")
                .append(getCustoPessoaMes()).append("' ");
        buffer.append("contratoPratica").append("='").append(
                getContratoPratica()).append("' ");
        buffer.append("percentualApropriado").append("='").append(
                getPercentualApropriado()).append("' ");
        buffer.append("numeroHoras").append("='").append(getNumeroHoras())
                .append("' ");
        buffer.append("valorFator").append("='").append(getValorFator())
                .append("' ");
        buffer.append("valorApropriado").append("='").append(getValorApropriado())
    			.append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}