/*
 * @(#) CustoTiRecurso.java
 * Copyright (c) 2010 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Entity gerado a partir da tabela CUSTO_TI_RECURSO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 14/07/2010 10:56:14
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CUSTO_TI_RECURSO")
@NamedQueries({
        @NamedQuery(name = "CustoTiRecurso.findAll", query = "SELECT t FROM CustoTiRecurso t"),

        @NamedQuery(name = "CustoTiRecurso.findPrevious", query = "SELECT custo FROM CustoTiRecurso custo"
                + " WHERE custo.tiRecurso.codigoTiRecurso = ? "
                + " AND TRUNC(custo.dataInicio) = "
                + "     (SELECT MAX(TRUNC(custoBefore.dataInicio)) "
                + "         FROM CustoTiRecurso custoBefore "
                + "         WHERE custoBefore.tiRecurso.codigoTiRecurso = ?"
                + "         AND custoBefore.dataInicio < ?)"),

        @NamedQuery(name = "CustoTiRecurso.findNext", query = "SELECT custo FROM CustoTiRecurso custo"
                + " WHERE custo.tiRecurso.codigoTiRecurso = ?"
                + " AND TRUNC(custo.dataInicio) = "
                + "     (SELECT MIN(TRUNC(custoNext.dataInicio)) "
                + "      FROM CustoTiRecurso custoNext "
                + "      WHERE custoNext.tiRecurso.codigoTiRecurso = ?"
                + "      AND custoNext.dataInicio > ?)"),

        @NamedQuery(name = "CustoTiRecurso.findByTiRecurso", query = "SELECT custo FROM CustoTiRecurso custo"
                + " WHERE custo.tiRecurso.codigoTiRecurso = ?")})
public class CustoTiRecurso implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** Constante para NamedQuery "CustoTiRecurso.findAll". */
    public static final String FIND_ALL = "CustoTiRecurso.findAll";

    /** Constante para NamedQuery "CustoTiRecurso.findNext". */
    public static final String FIND_NEXT = "CustoTiRecurso.findNext";

    /** Constante para NamedQuery "CustoTiRecurso.findPrevious". */
    public static final String FIND_PREVIOUS = "CustoTiRecurso.findPrevious";

    /** Constante para NamedQuery "CustoTiRecurso.findByTiRecurso". */
    public static final String FIND_BY_TI_RECURSO =
            "CustoTiRecurso.findByTiRecurso";

    /**
     * Atributo gerado a partir da coluna CUTR_CD_CUSTO_TI_RECURSO.
     */
    @Id
    @GeneratedValue(generator = "CustoTiRecursoSeq")
    @SequenceGenerator(name = "CustoTiRecursoSeq", sequenceName = "SQ_CUTR_CD_CUSTO_TI_RECURSO", allocationSize = 1)
    @Column(name = "CUTR_CD_CUSTO_TI_RECURSO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoCustoTiRecurso;

    /**
     * Atributo gerado a partir da coluna TIRE_CD_TI_RECURSO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TIRE_CD_TI_RECURSO", nullable = false)
    private TiRecurso tiRecurso;

    /**
     * Atributo gerado a partir da coluna CUTR_DT_INICIO.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "CUTR_DT_INICIO", length = 7)
    private Date dataInicio;

    /**
     * Atributo gerado a partir da coluna CUTR_DT_FIM.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "CUTR_DT_FIM", length = 7)
    private Date dataFim;

    /**
     * Atributo gerado a partir da coluna CUTR_VL_CUSTO_TI_RECURSO.
     */

    @Column(name = "CUTR_VL_CUSTO_TI_RECURSO", precision = 22, scale = 0)
    private BigDecimal valorCustoTiRecurso;

    /**
     * Valor do CustoTiRecurso arredondado e no formato de String para o envio
     * de e-mail.
     */
    @Transient
    private String valorCustoTiRecursoString;

    /**
     * Construtor default.
     */
    public CustoTiRecurso() {
    }

    /**
     * Obtem o valor do atributo codigoCustoTiRecurso.<BR>
     * Atributo gerado a partir da coluna CUTR_CD_CUSTO_TI_RECURSO.
     * 
     * @return Valor do atributo codigoCustoTiRecurso.
     */
    public Long getCodigoCustoTiRecurso() {
        return this.codigoCustoTiRecurso;
    }

    /**
     * Atualiza o valor do atributo codigoCustoTiRecurso.<BR>
     * Atributo gerado a partir da coluna CUTR_CD_CUSTO_TI_RECURSO.
     * 
     * @param codigoCustoTiRecurso
     *            Novo valor para o atributo codigoCustoTiRecurso.
     */
    public void setCodigoCustoTiRecurso(final Long codigoCustoTiRecurso) {
        this.codigoCustoTiRecurso = codigoCustoTiRecurso;
    }

    /**
     * Obtem o valor do atributo tiRecurso.<BR>
     * Atributo gerado a partir da coluna TIRE_CD_TI_RECURSO.
     * 
     * @return Valor do atributo tiRecurso.
     */
    public TiRecurso getTiRecurso() {
        return this.tiRecurso;
    }

    /**
     * Atualiza o valor do atributo tiRecurso.<BR>
     * Atributo gerado a partir da coluna TIRE_CD_TI_RECURSO.
     * 
     * @param tiRecurso
     *            Novo valor para o atributo tiRecurso.
     */
    public void setTiRecurso(final TiRecurso tiRecurso) {
        this.tiRecurso = tiRecurso;
    }

    /**
     * Obtem o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna CUTR_DT_INICIO.
     * 
     * @return Valor do atributo dataInicio.
     */
    public Date getDataInicio() {
        return this.dataInicio;
    }

    /**
     * Atualiza o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna CUTR_DT_INICIO.
     * 
     * @param dataInicio
     *            Novo valor para o atributo dataInicio.
     */
    public void setDataInicio(final Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    /**
     * Obtem o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna CUTR_DT_FIM.
     * 
     * @return Valor do atributo dataFim.
     */
    public Date getDataFim() {
        return this.dataFim;
    }

    /**
     * Atualiza o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna CUTR_DT_FIM.
     * 
     * @param dataFim
     *            Novo valor para o atributo dataFim.
     */
    public void setDataFim(final Date dataFim) {
        this.dataFim = dataFim;
    }

    /**
     * Obtem o valor do atributo valorCustoTiRecurso.<BR>
     * Atributo gerado a partir da coluna CUTR_VL_CUSTO_TI_RECURSO.
     * 
     * @return Valor do atributo valorCustoTiRecurso.
     */
    public BigDecimal getValorCustoTiRecurso() {
        return this.valorCustoTiRecurso;
    }

    /**
     * Atualiza o valor do atributo valorCustoTiRecurso.<BR>
     * Atributo gerado a partir da coluna CUTR_VL_CUSTO_TI_RECURSO.
     * 
     * @param valorCustoTiRecurso
     *            Novo valor para o atributo valorCustoTiRecurso.
     */
    public void setValorCustoTiRecurso(final BigDecimal valorCustoTiRecurso) {
        this.valorCustoTiRecurso = valorCustoTiRecurso;
    }

    /**
     * @return the valorCustoTiRecursoString
     */
    public String getValorCustoTiRecursoString() {
        return valorCustoTiRecursoString;
    }

    /**
     * @param valorCustoTiRecursoString
     *            the valorCustoTiRecursoString to set
     */
    public void setValorCustoTiRecursoString(
            final String valorCustoTiRecursoString) {
        this.valorCustoTiRecursoString = valorCustoTiRecursoString;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoCustoTiRecurso").append("='").append(
                getCodigoCustoTiRecurso()).append("' ");
        buffer.append("codigoTiRecurso").append("='").append(getTiRecurso())
                .append("' ");
        buffer.append("dataInicio").append("='").append(getDataInicio())
                .append("' ");
        buffer.append("dataFim").append("='").append(getDataFim()).append("' ");
        buffer.append("valorCustoTiRecurso").append("='").append(
                getValorCustoTiRecurso()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
