/*
 * @(#) CustoRealizado.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela CUSTO_REALIZADO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 24/02/2010 13:56:13
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CUSTO_REALIZADO")
@NamedQueries({
        @NamedQuery(name = "CustoRealizado.findAll", query = "SELECT t FROM CustoRealizado t "),

        @NamedQuery(name = "CustoRealizado.findByPessoaAndContratoPratica", query = "SELECT cure FROM CustoRealizado cure "
                + " WHERE cure.pessoa.codigoPessoa = ? "
                + " AND cure.contratoPratica.codigoContratoPratica = ? "
                + " AND (TRUNC(cure.dataMes) = TRUNC(?)) "),

        @NamedQuery(name = "CustoRealizado.findByPessoaAndDataMes", query = "SELECT cure FROM CustoRealizado cure "
                + " WHERE cure.pessoa.codigoPessoa = ? "
                + " AND (TRUNC(cure.dataMes) = TRUNC(?)) "),

        @NamedQuery(name = "CustoRealizado.getTotalAlocacaoPessoa", query = "SELECT COALESCE(SUM(cure.percentualAlocacaoMes), 0D) "
                + " FROM CustoRealizado cure "
                + " WHERE cure.pessoa.codigoPessoa = ? "
                + " AND cure.contratoPratica.codigoContratoPratica = ? "
                + " AND (TRUNC(cure.dataMes) = TRUNC(?)) "),

        @NamedQuery(name = "CustoRealizado.findMaxStartDateByPessoa", query = "SELECT cure FROM CustoRealizado cure "
                + " WHERE cure.pessoa.codigoPessoa = ? "
                + " AND cure.dataMes = "
                + " (SELECT MAX(cr.dataMes) FROM CustoRealizado cr "
                + " WHERE cr.pessoa.codigoPessoa = ?)"),

        @NamedQuery(name = "CustoRealizado.findContratoPraticaAndDate", query = "SELECT cure FROM CustoRealizado cure "
                + " WHERE cure.contratoPratica.codigoContratoPratica = ? "
                + " AND (TRUNC(cure.dataMes) = TRUNC(?)) ")})
public class CustoRealizado implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /** Constante para NamedQuery "CustoRealizado.findByPessoaAndDataMes". */
    public static final String FIND_BY_PESSOA_AND_DATA_MES =
            "CustoRealizado.findByPessoaAndDataMes";

    /**
     * Constante para NamedQuery
     * "CustoRealizado.findByPessoaAndContratoPratica".
     */
    public static final String FIND_BY_PESSOA_AND_CONTRATO_PRATICA =
            "CustoRealizado.findByPessoaAndContratoPratica";

    /** Constante para NamedQuery "CustoRealizado.getTotalAlocacaoPessoa". */
    public static final String GET_TOTAL_ALOCACAO_PESSOA =
            "CustoRealizado.getTotalAlocacaoPessoa";

    /** Constante para NamedQuery "CustoRealizado.findMaxStartDateByPessoa". */
    public static final String FIND_MAX_START_DATE_BY_PESSOA =
            "CustoRealizado.findMaxStartDateByPessoa";

    /** Constante para NamedQuery "CustoRealizado.findContratoPraticaAndDate". */
    public static final String FIND_BY_CONTRATO_PRATICA_AND_DATE =
            "CustoRealizado.findContratoPraticaAndDate";

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "CustoRealizado.findAll".
     */
    public static final String FIND_ALL = "CustoRealizado.findAll";

    /**
     * Atributo gerado a partir da coluna CURE_CD_CUSTO_REALIZADO.
     */
    @Id
    @GeneratedValue(generator = "CustoRealizadoSeq")
    @SequenceGenerator(name = "CustoRealizadoSeq", sequenceName = "SQ_CURE_CD_CUSTO_REALIZADO", allocationSize = 1)
    @Column(name = "CURE_CD_CUSTO_REALIZADO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoCustoRealizado;

    /**
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PESS_CD_PESSOA", nullable = false)
    private Pessoa pessoa;

    /**
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COPR_CD_CONTRATO_PRATICA")
    private ContratoPratica contratoPratica;

    /**
     * Atributo gerado a partir da coluna CURE_DT_MES.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "CURE_DT_MES", length = 7)
    private Date dataMes;

    /**
     * Atributo gerado a partir da coluna CURE_VL_TCE_MES.
     */

    @Column(name = "CURE_VL_TCE_MES", precision = 22, scale = 0)
    private BigDecimal valorTceMes;

    /**
     * Atributo gerado a partir da coluna CURE_PR_ALOCACAO_MES.
     */

    @Column(name = "CURE_PR_ALOCACAO_MES", precision = 22, scale = 0)
    private BigDecimal percentualAlocacaoMes;

    /**
     * Atributo gerado a partir da coluna CURE_IN_TIPO.
     */

    @Column(name = "CURE_IN_TIPO", length = 2)
    private String indicadorTipo;

    /**
     * Atributo gerado a partir da coluna CURE_VL_TAXA_COTACAO.
     */

    @Column(name = "CURE_VL_TAXA_COTACAO", precision = 22, scale = 0)
    private BigDecimal valorTaxaCotacao;

    /**
     * Atributo gerado a partir da coluna CURE_DT_ATUALIZACAO.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CURE_DT_ATUALIZACAO")
    private Date dataAtualizacao;

    /**
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MOED_CD_MOEDA")
    private Moeda moeda;

    /**
     * Atributo gerado a partir da coluna CURE_PR_ALOCAVEL.
     */
    @Column(name = "CURE_PR_ALOCAVEL", precision = 22, scale = 0)
    private BigDecimal percentualAlocavel;

    /**
     * Atributo gerado a partir da coluna ALPE_CD_ALOCACAO_PERIODO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ALPE_CD_ALOCACAO_PERIODO")
    private AlocacaoPeriodo alocacaoPeriodo;

    /**
     * Construtor default.
     */
    public CustoRealizado() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoCustoRealizado
     *            Valor do atributo codigoCustoRealizado;
     * @param pessoa
     *            Valor do atributo pessoa;
     * @param contratoPratica
     *            Valor do atributo contratoPratica;
     */
    public CustoRealizado(final Long codigoCustoRealizado, final Pessoa pessoa,
            final ContratoPratica contratoPratica) {
        this.codigoCustoRealizado = codigoCustoRealizado;
        this.pessoa = pessoa;
        this.contratoPratica = contratoPratica;
    }

    /**
     * Obtem o valor do atributo codigoCustoRealizado.<BR>
     * Atributo gerado a partir da coluna CURE_CD_CUSTO_REALIZADO.
     * 
     * @return Valor do atributo codigoCustoRealizado.
     */
    public Long getCodigoCustoRealizado() {
        return this.codigoCustoRealizado;
    }

    /**
     * Atualiza o valor do atributo codigoCustoRealizado.<BR>
     * Atributo gerado a partir da coluna CURE_CD_CUSTO_REALIZADO.
     * 
     * @param codigoCustoRealizado
     *            Novo valor para o atributo codigoCustoRealizado.
     */
    public void setCodigoCustoRealizado(final Long codigoCustoRealizado) {
        this.codigoCustoRealizado = codigoCustoRealizado;
    }

    /**
     * Obtem o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     * 
     * @return Valor do atributo pessoa.
     */
    public Pessoa getPessoa() {
        return this.pessoa;
    }

    /**
     * Atualiza o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     * 
     * @param pessoa
     *            Novo valor para o atributo pessoa.
     */
    public void setPessoa(final Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    /**
     * Obtem o valor do atributo contratoPratica.<BR>
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     * 
     * @return Valor do atributo contratoPratica.
     */
    public ContratoPratica getContratoPratica() {
        return this.contratoPratica;
    }

    /**
     * Atualiza o valor do atributo contratoPratica.<BR>
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     * 
     * @param contratoPratica
     *            Novo valor para o atributo contratoPratica.
     */
    public void setContratoPratica(final ContratoPratica contratoPratica) {
        this.contratoPratica = contratoPratica;
    }

    /**
     * Obtem o valor do atributo dataMes.<BR>
     * Atributo gerado a partir da coluna CURE_DT_MES.
     * 
     * @return Valor do atributo dataMes.
     */
    public Date getDataMes() {
        return this.dataMes;
    }

    /**
     * Atualiza o valor do atributo dataMes.<BR>
     * Atributo gerado a partir da coluna CURE_DT_MES.
     * 
     * @param dataMes
     *            Novo valor para o atributo dataMes.
     */
    public void setDataMes(final Date dataMes) {
        this.dataMes = dataMes;
    }

    /**
     * Obtem o valor do atributo valorTceMes.<BR>
     * Atributo gerado a partir da coluna CURE_VL_TCE_MES.
     * 
     * @return Valor do atributo valorTceMes.
     */
    public BigDecimal getValorTceMes() {
        return this.valorTceMes;
    }

    /**
     * Atualiza o valor do atributo valorTceMes.<BR>
     * Atributo gerado a partir da coluna CURE_VL_TCE_MES.
     * 
     * @param valorTceMes
     *            Novo valor para o atributo valorTceMes.
     */
    public void setValorTceMes(final BigDecimal valorTceMes) {
        this.valorTceMes = valorTceMes;
    }

    /**
     * Obtem o valor do atributo percentualAlocacaoMes.<BR>
     * Atributo gerado a partir da coluna CURE_PR_ALOCACAO_MES.
     * 
     * @return Valor do atributo percentualAlocacaoMes.
     */
    public BigDecimal getPercentualAlocacaoMes() {
        return this.percentualAlocacaoMes;
    }

    /**
     * Atualiza o valor do atributo percentualAlocacaoMes.<BR>
     * Atributo gerado a partir da coluna CURE_PR_ALOCACAO_MES.
     * 
     * @param percentualAlocacaoMes
     *            Novo valor para o atributo percentualAlocacaoMes.
     */
    public void setPercentualAlocacaoMes(final BigDecimal percentualAlocacaoMes) {
        this.percentualAlocacaoMes = percentualAlocacaoMes;
    }

    /**
     * Obtem o valor do atributo indicadorTipo.<BR>
     * Atributo gerado a partir da coluna CURE_IN_TIPO.
     * 
     * @return Valor do atributo indicadorTipo.
     */
    public String getIndicadorTipo() {
        return this.indicadorTipo;
    }

    /**
     * Atualiza o valor do atributo indicadorTipo.<BR>
     * Atributo gerado a partir da coluna CURE_IN_TIPO.
     * 
     * @param indicadorTipo
     *            Novo valor para o atributo indicadorTipo.
     */
    public void setIndicadorTipo(final String indicadorTipo) {
        this.indicadorTipo = indicadorTipo;
    }

    /**
     * Obtem o valor do atributo valorTaxaCotacao.<BR>
     * Atributo gerado a partir da coluna CURE_VL_TAXA_COTACAO.
     * 
     * @return Valor do atributo valorTaxaCotacao.
     */
    public BigDecimal getValorTaxaCotacao() {
        return this.valorTaxaCotacao;
    }

    /**
     * Atualiza o valor do atributo valorTaxaCotacao.<BR>
     * Atributo gerado a partir da coluna CURE_VL_TAXA_COTACAO.
     * 
     * @param valorTaxaCotacao
     *            Novo valor para o atributo valorTaxaCotacao.
     */
    public void setValorTaxaCotacao(final BigDecimal valorTaxaCotacao) {
        this.valorTaxaCotacao = valorTaxaCotacao;
    }

    /**
     * Obtem o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * 
     * @return Valor do atributo moeda.
     */
    public Moeda getMoeda() {
        return this.moeda;
    }

    /**
     * Atualiza o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * 
     * @param moeda
     *            Novo valor para o atributo moeda.
     */
    public void setMoeda(final Moeda moeda) {
        this.moeda = moeda;
    }

    /**
     * Obtem o valor do atributo dataAtualizacao.<BR>
     * Atributo gerado a partir da coluna CURE_DT_ATUALIZACAO.
     * 
     * @return Valor do atributo dataAtualizacao.
     */
    public Date getDataAtualizacao() {
        return this.dataAtualizacao;
    }

    /**
     * Atualiza o valor do atributo dataAtualizacao.<BR>
     * Atributo gerado a partir da coluna CURE_DT_ATUALIZACAO.
     * 
     * @param dataAtualizacao
     *            Novo valor para o atributo dataAtualizacao.
     */
    public void setDataAtualizacao(final Date dataAtualizacao) {
        this.dataAtualizacao = dataAtualizacao;
    }

    /**
     * Obtem o valor do atributo percentualAlocavel.<BR>
     * Atributo gerado a partir da coluna CURE_PR_ALOCAVEL.
     * 
     * @return Valor do atributo percentualAlocavel.
     */
    public BigDecimal getPercentualAlocavel() {
        return this.percentualAlocavel;
    }

    /**
     * Atualiza o valor do atributo percentualAlocavel.<BR>
     * Atributo gerado a partir da coluna CURE_PR_ALOCAVEL.
     * 
     * @param percentualAlocavel
     *            Novo valor para o atributo percentualAlocavel.
     */
    public void setPercentualAlocavel(final BigDecimal percentualAlocavel) {
        this.percentualAlocavel = percentualAlocavel;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoCustoRealizado").append("='").append(
                getCodigoCustoRealizado()).append("' ");
        buffer.append("pessoa").append("='").append(getPessoa()).append("' ");
        buffer.append("moeda").append("='").append(getMoeda()).append("' ");
        buffer.append("contratoPratica").append("='").append(
                getContratoPratica()).append("' ");
        buffer.append("dataMes").append("='").append(getDataMes()).append("' ");
        buffer.append("valorTceMes").append("='").append(getValorTceMes())
                .append("' ");
        buffer.append("percentualAlocacaoMes").append("='").append(
                getPercentualAlocacaoMes()).append("' ");
        buffer.append("indicadorTipo").append("='").append(getIndicadorTipo())
                .append("' ");
        buffer.append("valorTaxaCotacao").append("='").append(
                getValorTaxaCotacao()).append("' ");
        buffer.append("dataAtualizacao").append("='").append(
                getDataAtualizacao()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    /**
     * @param alocacaoPeriodo
     *            the alocacaoPeriodo to set
     */
    public void setAlocacaoPeriodo(final AlocacaoPeriodo alocacaoPeriodo) {
        this.alocacaoPeriodo = alocacaoPeriodo;
    }

    /**
     * @return the alocacaoPeriodo
     */
    public AlocacaoPeriodo getAlocacaoPeriodo() {
        return alocacaoPeriodo;
    }

}