/*
 * @(#) CustoInfraBase.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela CUSTO_INFRA_BASE.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 31/05/2010 10:06:59
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CUSTO_INFRA_BASE")
@NamedQueries({
    @NamedQuery(name = "CustoInfraBase.findAll", query = "SELECT t FROM CustoInfraBase t"),
    
    @NamedQuery(name = "CustoInfraBase.findByFilter", query = "SELECT cuib FROM CustoInfraBase cuib "
        + " JOIN FETCH cuib.cidadeBase cidadeBase "
        + " JOIN FETCH cidadeBase.moeda "
        + "WHERE ( (cidadeBase.codigoCidadeBase = ?) OR (? = 0L) ) "
        + "ORDER BY cidadeBase.nomeCidadeBase ASC, cuib.dataMes ASC "),
        
    @NamedQuery(name = "CustoInfraBase.findByDateAndCidadeBase", 
            query = "SELECT cuib FROM CustoInfraBase cuib "
        + " WHERE cuib.cidadeBase.codigoCidadeBase = ? "
        + " AND cuib.dataMes = TRUNC(?) ")
})
public class CustoInfraBase implements java.io.Serializable {
    
    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    
    /**
     * Constante para NamedQuery "CustoInfraBase.findByFilter".
     */
    public static final String FIND_BY_FILTER = "CustoInfraBase.findByFilter";
    
    /**
     * Constante para NamedQuery "CustoInfraBase.findByDateAndCidadeBase".
     */
    public static final String FIND_BY_DATE_AND_CIDADE_BASE = "CustoInfraBase.findByDateAndCidadeBase";
    
    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "CustoInfraBase.findAll".
     */
    public static final String FIND_ALL = "CustoInfraBase.findAll";

    /**
     * Atributo gerado a partir da coluna CUIB_CD_CUSTO_INFRA_BASE.
     */
    @Id
    @GeneratedValue(generator = "CustoInfraBaseSeq")
    @SequenceGenerator(name = "CustoInfraBaseSeq", 
            sequenceName = "SQ_CUIB_CD_CUSTO_INFRA_BASE", allocationSize = 1)
    @Column(name = "CUIB_CD_CUSTO_INFRA_BASE", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoCustoInfraBase;

    /**
     * Atributo gerado a partir da coluna CIBA_CD_CIDADE_BASE.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CIBA_CD_CIDADE_BASE", nullable = false)
    private CidadeBase cidadeBase;

    /**
     * Atributo gerado a partir da coluna CUIB_DT_MES.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "CUIB_DT_MES", length = 7)
    private Date dataMes;

    /**
     * Atributo gerado a partir da coluna CUIB_VL_CUSTO_MES_FTE.
     */

    @Column(name = "CUIB_VL_CUSTO_MES_FTE", precision = 22, scale = 0)
    private BigDecimal valorCustoMesFte;

    /**
     * Construtor default.
     */
    public CustoInfraBase() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoCustoInfraBase Valor do atributo codigoCustoInfraBase;
     * @param cidadeBase Valor do atributo cidadeBase;
     */
    public CustoInfraBase(final Long codigoCustoInfraBase,
            final CidadeBase cidadeBase) {
        this.codigoCustoInfraBase = codigoCustoInfraBase;
        this.cidadeBase = cidadeBase;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoCustoInfraBase Valor do atributo codigoCustoInfraBase;
     * @param cidadeBase Valor do atributo cidadeBase;
     * @param dataMes Valor do atributo dataMes;
     * @param valorCustoMesFte Valor do atributo valorCustoMesFte;
     */
    public CustoInfraBase(final Long codigoCustoInfraBase,
            final CidadeBase cidadeBase, final Date dataMes, final BigDecimal valorCustoMesFte) {
        this.codigoCustoInfraBase = codigoCustoInfraBase;
        this.cidadeBase = cidadeBase;
        this.dataMes = dataMes;
        this.valorCustoMesFte = valorCustoMesFte;
    }

    /**
     * Obtem o valor do atributo codigoCustoInfraBase.<BR>
     * Atributo gerado a partir da coluna CUIB_CD_CUSTO_INFRA_BASE.
     * @return Valor do atributo codigoCustoInfraBase.
     */
    public Long getCodigoCustoInfraBase() {
        return this.codigoCustoInfraBase;
    }

    /**
     * Atualiza o valor do atributo codigoCustoInfraBase.<BR>
     * Atributo gerado a partir da coluna CUIB_CD_CUSTO_INFRA_BASE.
     * @param codigoCustoInfraBase Novo valor para o atributo codigoCustoInfraBase.
     */
    public void setCodigoCustoInfraBase(final Long codigoCustoInfraBase) {
        this.codigoCustoInfraBase = codigoCustoInfraBase;
    }

    /**
     * Obtem o valor do atributo cidadeBase.<BR>
     * Atributo gerado a partir da coluna CIBA_CD_CIDADE_BASE.
     * @return Valor do atributo cidadeBase.
     */
    public CidadeBase getCidadeBase() {
        return this.cidadeBase;
    }

    /**
     * Atualiza o valor do atributo cidadeBase.<BR>
     * Atributo gerado a partir da coluna CIBA_CD_CIDADE_BASE.
     * @param cidadeBase Novo valor para o atributo cidadeBase.
     */
    public void setCidadeBase(final CidadeBase cidadeBase) {
        this.cidadeBase = cidadeBase;
    }

    /**
     * Obtem o valor do atributo dataMes.<BR>
     * Atributo gerado a partir da coluna CUIB_DT_MES.
     * @return Valor do atributo dataMes.
     */
    public Date getDataMes() {
        return this.dataMes;
    }

    /**
     * Atualiza o valor do atributo dataMes.<BR>
     * Atributo gerado a partir da coluna CUIB_DT_MES.
     * @param dataMes Novo valor para o atributo dataMes.
     */
    public void setDataMes(final Date dataMes) {
        this.dataMes = dataMes;
    }

    /**
     * Obtem o valor do atributo valorCustoMesFte.<BR>
     * Atributo gerado a partir da coluna CUIB_VL_CUSTO_MES_FTE.
     * @return Valor do atributo valorCustoMesFte.
     */
    public BigDecimal getValorCustoMesFte() {
        return this.valorCustoMesFte;
    }

    /**
     * Atualiza o valor do atributo valorCustoMesFte.<BR>
     * Atributo gerado a partir da coluna CUIB_VL_CUSTO_MES_FTE.
     * @param valorCustoMesFte Novo valor para o atributo valorCustoMesFte.
     */
    public void setValorCustoMesFte(final BigDecimal valorCustoMesFte) {
        this.valorCustoMesFte = valorCustoMesFte;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoCustoInfraBase").append("='").append(
                getCodigoCustoInfraBase()).append("' ");
        buffer.append("cidadeBase").append("='").append(getCidadeBase())
                .append("' ");
        buffer.append("dataMes").append("='").append(getDataMes()).append("' ");
        buffer.append("valorCustoMesFte").append("='").append(
                getValorCustoMesFte()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}