/*
 * @(#) CustoTceGrupoCusto.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela CUSTO_TCE_GRUPO_CUSTO.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 21/06/2010 13:41:52
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CUSTO_TCE_GRUPO_CUSTO")
@NamedQueries({
    @NamedQuery(name = "CustoTceGrupoCusto.findAll", query = "SELECT t FROM CustoTceGrupoCusto t"),
    
    @NamedQuery(name = "CustoTceGrupoCusto.findByPessoaAndDataMes", 
            query = "SELECT ctgc FROM CustoTceGrupoCusto ctgc "
            + " WHERE ctgc.pessoa.codigoPessoa = ? "
            + " AND (TRUNC(ctgc.dataMes) = TRUNC(?)) "),
            
    @NamedQuery(name = "CustoTceGrupoCusto.findMaxStartDateByPessoa", 
            query = "SELECT ctgc FROM CustoTceGrupoCusto ctgc "
            + " WHERE ctgc.pessoa.codigoPessoa = ? "
            + " AND ctgc.dataMes = "
            + " (SELECT MAX(ct.dataMes) FROM CustoTceGrupoCusto ct "
            + " WHERE ct.pessoa.codigoPessoa = ?)")
})
public class CustoTceGrupoCusto implements java.io.Serializable {
    
    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    
    /** Constante para NamedQuery "CustoTceGrupoCusto.findByPessoaAndDataMes". */
    public static final String FIND_BY_PESSOA_AND_DATA_MES = "CustoTceGrupoCusto.findByPessoaAndDataMes";
    
    /** Constante para NamedQuery "CustoTceGrupoCusto.findMaxStartDateByPessoa". */
    public static final String FIND_MAX_START_DATE_BY_PESSOA = "CustoTceGrupoCusto.findMaxStartDateByPessoa";
    
    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "CustoTceGrupoCusto.findAll".
     */
    public static final String FIND_ALL = "CustoTceGrupoCusto.findAll";

    /**
     * Atributo gerado a partir da coluna CTGC_CD_CUSTO_TCE_GC.
     */
    @Id
    @GeneratedValue(generator = "CustoTceGrupoCustoSeq")
    @SequenceGenerator(name = "CustoTceGrupoCustoSeq", 
            sequenceName = "SQ_CTGC_CD_CUSTO_TCE_GC", allocationSize = 1)
    @Column(name = "CTGC_CD_CUSTO_TCE_GC", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoCustoTceGc;

    /**
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PESS_CD_PESSOA", nullable = false)
    private Pessoa pessoa;

    /**
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MOED_CD_MOEDA", nullable = false)
    private Moeda moeda;

    /**
     * Atributo gerado a partir da coluna GRCU_CD_GRUPO_CUSTO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GRCU_CD_GRUPO_CUSTO", nullable = false)
    private GrupoCusto grupoCusto;

    /**
     * Atributo gerado a partir da coluna CTGC_DT_MES.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "CTGC_DT_MES", length = 7)
    private Date dataMes;

    /**
     * Atributo gerado a partir da coluna CTGC_VL_TCE_MES.
     */

    @Column(name = "CTGC_VL_TCE_MES", precision = 22, scale = 0)
    private BigDecimal valorTceMes;

    /**
     * Atributo gerado a partir da coluna CTGC_PR_ALOCACAO_MES.
     */

    @Column(name = "CTGC_PR_ALOCACAO_MES", precision = 22, scale = 0)
    private BigDecimal percentualAlocacaoMes;

    /**
     * Atributo gerado a partir da coluna CTGC_IN_TIPO.
     */

    @Column(name = "CTGC_IN_TIPO", length = 2)
    private String indicadorTipo;

    /**
     * Atributo gerado a partir da coluna CTGC_VL_TAXA_COTACAO.
     */

    @Column(name = "CTGC_VL_TAXA_COTACAO", precision = 22, scale = 0)
    private BigDecimal valorTaxaCotacao;
    
    /**
     * Atributo gerado a partir da coluna CTGC_DT_ATUALIZACAO.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CTGC_DT_ATUALIZACAO")
    private Date dataAtualizacao;
    
    /**
     * Atributo gerado a partir da coluna CTGC_PR_ALOCAVEL.
     */
    @Column(name = "CTGC_PR_ALOCAVEL", precision = 22, scale = 0)
    private BigDecimal percentualAlocavel;

    /**
     * Construtor default.
     */
    public CustoTceGrupoCusto() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoCustoTceGc Valor do atributo codigoCustoTceGc;
     * @param pessoa Valor do atributo pessoa;
     * @param moeda Valor do atributo moeda;
     * @param grupoCusto Valor do atributo grupoCusto;
     */
    public CustoTceGrupoCusto(final Long codigoCustoTceGc, final Pessoa pessoa,
            final Moeda moeda, final GrupoCusto grupoCusto) {
        this.codigoCustoTceGc = codigoCustoTceGc;
        this.pessoa = pessoa;
        this.moeda = moeda;
        this.grupoCusto = grupoCusto;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoCustoTceGc Valor do atributo codigoCustoTceGc;
     * @param pessoa Valor do atributo pessoa;
     * @param moeda Valor do atributo moeda;
     * @param grupoCusto Valor do atributo grupoCusto;
     * @param dataMes Valor do atributo dataMes;
     * @param valorTceMes Valor do atributo valorTceMes;
     * @param percentualAlocacaoMes Valor do atributo percentualAlocacaoMes;
     * @param indicadorTipo Valor do atributo indicadorTipo;
     * @param valorTaxaCotacao Valor do atributo valorTaxaCotacao;
     * @param dataAtualizacao Valor do atributo dataAtualizacao;
     * @param percentualAlocavel Valor do atributo percentualAlocavel;
     */
    public CustoTceGrupoCusto(final Long codigoCustoTceGc, final Pessoa pessoa,
            final Moeda moeda, final GrupoCusto grupoCusto, final Date dataMes,
            final BigDecimal valorTceMes, final BigDecimal percentualAlocacaoMes,
            final String indicadorTipo, final BigDecimal valorTaxaCotacao,
            final Date dataAtualizacao, final BigDecimal percentualAlocavel) {
        this.codigoCustoTceGc = codigoCustoTceGc;
        this.pessoa = pessoa;
        this.moeda = moeda;
        this.grupoCusto = grupoCusto;
        this.dataMes = dataMes;
        this.valorTceMes = valorTceMes;
        this.percentualAlocacaoMes = percentualAlocacaoMes;
        this.indicadorTipo = indicadorTipo;
        this.valorTaxaCotacao = valorTaxaCotacao;
        this.dataAtualizacao = dataAtualizacao;
        this.percentualAlocavel = percentualAlocavel;
    }

    /**
     * Obtem o valor do atributo codigoCustoTceGc.<BR>
     * Atributo gerado a partir da coluna CTGC_CD_CUSTO_TCE_GC.
     * @return Valor do atributo codigoCustoTceGc.
     */
    public Long getCodigoCustoTceGc() {
        return this.codigoCustoTceGc;
    }

    /**
     * Atualiza o valor do atributo codigoCustoTceGc.<BR>
     * Atributo gerado a partir da coluna CTGC_CD_CUSTO_TCE_GC.
     * @param codigoCustoTceGc Novo valor para o atributo codigoCustoTceGc.
     */
    public void setCodigoCustoTceGc(final Long codigoCustoTceGc) {
        this.codigoCustoTceGc = codigoCustoTceGc;
    }

    /**
     * Obtem o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     * @return Valor do atributo pessoa.
     */
    public Pessoa getPessoa() {
        return this.pessoa;
    }

    /**
     * Atualiza o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     * @param pessoa Novo valor para o atributo pessoa.
     */
    public void setPessoa(final Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    /**
     * Obtem o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * @return Valor do atributo moeda.
     */
    public Moeda getMoeda() {
        return this.moeda;
    }

    /**
     * Atualiza o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * @param moeda Novo valor para o atributo moeda.
     */
    public void setMoeda(final Moeda moeda) {
        this.moeda = moeda;
    }

    /**
     * Obtem o valor do atributo grupoCusto.<BR>
     * Atributo gerado a partir da coluna GRCU_CD_GRUPO_CUSTO.
     * @return Valor do atributo grupoCusto.
     */
    public GrupoCusto getGrupoCusto() {
        return this.grupoCusto;
    }

    /**
     * Atualiza o valor do atributo grupoCusto.<BR>
     * Atributo gerado a partir da coluna GRCU_CD_GRUPO_CUSTO.
     * @param grupoCusto Novo valor para o atributo grupoCusto.
     */
    public void setGrupoCusto(final GrupoCusto grupoCusto) {
        this.grupoCusto = grupoCusto;
    }

    /**
     * Obtem o valor do atributo dataMes.<BR>
     * Atributo gerado a partir da coluna CTGC_DT_MES.
     * @return Valor do atributo dataMes.
     */
    public Date getDataMes() {
        return this.dataMes;
    }

    /**
     * Atualiza o valor do atributo dataMes.<BR>
     * Atributo gerado a partir da coluna CTGC_DT_MES.
     * @param dataMes Novo valor para o atributo dataMes.
     */
    public void setDataMes(final Date dataMes) {
        this.dataMes = dataMes;
    }

    /**
     * Obtem o valor do atributo valorTceMes.<BR>
     * Atributo gerado a partir da coluna CTGC_VL_TCE_MES.
     * @return Valor do atributo valorTceMes.
     */
    public BigDecimal getValorTceMes() {
        return this.valorTceMes;
    }

    /**
     * Atualiza o valor do atributo valorTceMes.<BR>
     * Atributo gerado a partir da coluna CTGC_VL_TCE_MES.
     * @param valorTceMes Novo valor para o atributo valorTceMes.
     */
    public void setValorTceMes(final BigDecimal valorTceMes) {
        this.valorTceMes = valorTceMes;
    }

    /**
     * Obtem o valor do atributo percentualAlocacaoMes.<BR>
     * Atributo gerado a partir da coluna CTGC_PR_ALOCACAO_MES.
     * @return Valor do atributo percentualAlocacaoMes.
     */
    public BigDecimal getPercentualAlocacaoMes() {
        return this.percentualAlocacaoMes;
    }

    /**
     * Atualiza o valor do atributo percentualAlocacaoMes.<BR>
     * Atributo gerado a partir da coluna CTGC_PR_ALOCACAO_MES.
     * @param percentualAlocacaoMes Novo valor para o atributo percentualAlocacaoMes.
     */
    public void setPercentualAlocacaoMes(final BigDecimal percentualAlocacaoMes) {
        this.percentualAlocacaoMes = percentualAlocacaoMes;
    }

    /**
     * Obtem o valor do atributo indicadorTipo.<BR>
     * Atributo gerado a partir da coluna CTGC_IN_TIPO.
     * @return Valor do atributo indicadorTipo.
     */
    public String getIndicadorTipo() {
        return this.indicadorTipo;
    }

    /**
     * Atualiza o valor do atributo indicadorTipo.<BR>
     * Atributo gerado a partir da coluna CTGC_IN_TIPO.
     * @param indicadorTipo Novo valor para o atributo indicadorTipo.
     */
    public void setIndicadorTipo(final String indicadorTipo) {
        this.indicadorTipo = indicadorTipo;
    }

    /**
     * Obtem o valor do atributo valorTaxaCotacao.<BR>
     * Atributo gerado a partir da coluna CTGC_VL_TAXA_COTACAO.
     * @return Valor do atributo valorTaxaCotacao.
     */
    public BigDecimal getValorTaxaCotacao() {
        return this.valorTaxaCotacao;
    }

    /**
     * Atualiza o valor do atributo valorTaxaCotacao.<BR>
     * Atributo gerado a partir da coluna CTGC_VL_TAXA_COTACAO.
     * @param valorTaxaCotacao Novo valor para o atributo valorTaxaCotacao.
     */
    public void setValorTaxaCotacao(final BigDecimal valorTaxaCotacao) {
        this.valorTaxaCotacao = valorTaxaCotacao;
    }
    
    /**
     * Obtem o valor do atributo dataAtualizacao.<BR>
     * Atributo gerado a partir da coluna CTGC_DT_ATUALIZACAO.
     * @return Valor do atributo dataAtualizacao.
     */
    public Date getDataAtualizacao() {
        return this.dataAtualizacao;
    }

    /**
     * Atualiza o valor do atributo dataAtualizacao.<BR>
     * Atributo gerado a partir da coluna CTGC_DT_ATUALIZACAO.
     * @param dataAtualizacao Novo valor para o atributo dataAtualizacao.
     */
    public void setDataAtualizacao(final Date dataAtualizacao) {
        this.dataAtualizacao = dataAtualizacao;
    }
    
    /**
     * Obtem o valor do atributo percentualAlocavel.<BR>
     * Atributo gerado a partir da coluna CTGC_PR_ALOCAVEL.
     * @return Valor do atributo percentualAlocavel.
     */
    public BigDecimal getPercentualAlocavel() {
        return this.percentualAlocavel;
    }

    /**
     * Atualiza o valor do atributo percentualAlocavel.<BR>
     * Atributo gerado a partir da coluna CTGC_PR_ALOCAVEL.
     * @param percentualAlocavel Novo valor para o atributo percentualAlocavel.
     */
    public void setPercentualAlocavel(final BigDecimal percentualAlocavel) {
        this.percentualAlocavel = percentualAlocavel;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoCustoTceGc").append("='").append(
                getCodigoCustoTceGc()).append("' ");
        buffer.append("pessoa").append("='").append(getPessoa()).append("' ");
        buffer.append("moeda").append("='").append(getMoeda()).append("' ");
        buffer.append("grupoCusto").append("='").append(getGrupoCusto())
                .append("' ");
        buffer.append("dataMes").append("='").append(getDataMes()).append("' ");
        buffer.append("valorTceMes").append("='").append(getValorTceMes())
                .append("' ");
        buffer.append("percentualAlocacaoMes").append("='").append(
                getPercentualAlocacaoMes()).append("' ");
        buffer.append("indicadorTipo").append("='").append(getIndicadorTipo())
                .append("' ");
        buffer.append("valorTaxaCotacao").append("='").append(
                getValorTaxaCotacao()).append("' ");
        buffer.append("dataAtualizacao").append("='").append(
                getDataAtualizacao()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}