/*
 * @(#) CustoPessoaMes.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela CUSTO_PESSOA_MES.
 * Ainda nao esta sendo utilizado
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 30/08/2010 09:46:34
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CUSTO_PESSOA_MES")
@NamedQueries({ 
    @NamedQuery(name = "CustoPessoaMes.findAll", query = "SELECT t FROM CustoPessoaMes t"),
    
    @NamedQuery(name = "CustoPessoaMes.findByPessoaAndDataMes", 
            query = "SELECT cupm FROM CustoPessoaMes cupm "
            + " WHERE cupm.pessoa.codigoPessoa = ? "
            + " AND (TRUNC(cupm.dataMes) = TRUNC(?)) "),
    
    @NamedQuery(name = "CustoPessoaMes.findByDataMes", 
            query = "SELECT cupm FROM CustoPessoaMes cupm "
            + " WHERE (TRUNC(cupm.dataMes) = TRUNC(?)) ")
})
public class CustoPessoaMes implements java.io.Serializable {
    
    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    
    /** Constante para NamedQuery "CustoPessoaMes.findByPessoaAndDataMes". */
    public static final String FIND_BY_PESSOA_AND_DATA_MES = "CustoPessoaMes.findByPessoaAndDataMes";
    
    /** Constante para NamedQuery "CustoPessoaMes.findByDataMes". */
    public static final String FIND_BY_DATA_MES = "CustoPessoaMes.findByDataMes";
    
    /** Relacionamento com CustoPessoaCp. */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "custoPessoaMes", 
            cascade = CascadeType.ALL)
    private List<CustoPessoaCp> custoPessoaCps = new ArrayList<CustoPessoaCp>(0);

    /** Relacionamento com CustoPessoaGc. */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "custoPessoaMes", 
            cascade = CascadeType.ALL)
    private List<CustoPessoaGc> custoPessoaGcs = new ArrayList<CustoPessoaGc>(0);
    
    /**
     * Obtem o valor do atributo custoPessoaCps.<BR>

     * @return Valor do atributo custoPessoaCps.
     */
    public List<CustoPessoaCp> getCustoPessoaCps() {
        return this.custoPessoaCps;
    }

    /**
     * Atualiza o valor do atributo custoPessoaCps.<BR>

     * @param custoPessoaCps Novo valor para o atributo custoPessoaCps.
     */
    public void setCustoPessoaCps(final List<CustoPessoaCp> custoPessoaCps) {
        this.custoPessoaCps = custoPessoaCps;
    }

    /**
     * Obtem o valor do atributo custoPessoaGcs.<BR>

     * @return Valor do atributo custoPessoaGcs.
     */
    public List<CustoPessoaGc> getCustoPessoaGcs() {
        return this.custoPessoaGcs;
    }

    /**
     * Atualiza o valor do atributo custoPessoaGcs.<BR>

     * @param custoPessoaGcs Novo valor para o atributo custoPessoaGcs.
     */
    public void setCustoPessoaGcs(final List<CustoPessoaGc> custoPessoaGcs) {
        this.custoPessoaGcs = custoPessoaGcs;
    }
    
    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "CustoPessoaMes.findAll".
     */
    public static final String FIND_ALL = "CustoPessoaMes.findAll";

    /**
     * Atributo gerado a partir da coluna CUPM_CD_CUSTO_PESSOA_MES.
     */
    @Id
    @GeneratedValue(generator = "CustoPessoaMesSeq")
    @SequenceGenerator(name = "CustoPessoaMesSeq", 
            sequenceName = "SQ_CUPM_CD_CUSTO_PESSOA_MES", allocationSize = 1)
    @Column(name = "CUPM_CD_CUSTO_PESSOA_MES", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoCustoPessoaMes;

    /**
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PESS_CD_PESSOA", nullable = false)
    private Pessoa pessoa;

    /**
     * Atributo gerado a partir da coluna CUPM_DT_MES.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "CUPM_DT_MES", nullable = false, length = 7)
    private Date dataMes;

    /**
     * Atributo gerado a partir da coluna CUPM_VL_SALARIO.
     */

    @Column(name = "CUPM_VL_SALARIO", precision = 22, scale = 0)
    private BigDecimal valorSalario;

    /**
     * Atributo gerado a partir da coluna CUPM_VL_JORNADA.
     */

    @Column(name = "CUPM_VL_JORNADA", precision = 22, scale = 0)
    private BigDecimal valorJornada;

    /**
     * Atributo gerado a partir da coluna CUPM_IN_ORIGEM.
     */

    @Column(name = "CUPM_IN_ORIGEM", length = 2)
    private String indicadorOrigem;

    /**
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MOED_CD_MOEDA", nullable = false)
    private Moeda moeda;

    /**
     * Construtor default.
     */
    public CustoPessoaMes() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoCustoPessoaMes Valor do atributo codigoCustoPessoaMes;
     * @param pessoa Valor do atributo pessoa;
     * @param dataMes Valor do atributo dataMes;
     * @param moeda Valor do atributo moeda;
     */
    public CustoPessoaMes(final Long codigoCustoPessoaMes, final Pessoa pessoa,
            final Date dataMes, final Moeda moeda) {
        this.codigoCustoPessoaMes = codigoCustoPessoaMes;
        this.pessoa = pessoa;
        this.dataMes = dataMes;
        this.moeda = moeda;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoCustoPessoaMes Valor do atributo codigoCustoPessoaMes;
     * @param pessoa Valor do atributo pessoa;
     * @param dataMes Valor do atributo dataMes;
     * @param valorSalario Valor do atributo valorSalario;
     * @param valorJornada Valor do atributo valorJornada;
     * @param indicadorOrigem Valor do atributo indicadorOrigem;
     * @param moeda Valor do atributo moeda;
     * @param custoPessoaCps Valor do atributo custoPessoaCps;
     * @param custoPessoaGcs Valor do atributo custoPessoaGcs;
     */
    public CustoPessoaMes(final Long codigoCustoPessoaMes, final Pessoa pessoa,
            final Date dataMes, final BigDecimal valorSalario, final BigDecimal valorJornada,
            final String indicadorOrigem, final Moeda moeda,
            final List<CustoPessoaCp> custoPessoaCps, final List<CustoPessoaGc> custoPessoaGcs) {
        this.codigoCustoPessoaMes = codigoCustoPessoaMes;
        this.pessoa = pessoa;
        this.dataMes = dataMes;
        this.valorSalario = valorSalario;
        this.valorJornada = valorJornada;
        this.indicadorOrigem = indicadorOrigem;
        this.moeda = moeda;
        this.custoPessoaCps = custoPessoaCps;
        this.custoPessoaGcs = custoPessoaGcs;
    }

    /**
     * Obtem o valor do atributo codigoCustoPessoaMes.<BR>
     * Atributo gerado a partir da coluna CUPM_CD_CUSTO_PESSOA_MES.
     * @return Valor do atributo codigoCustoPessoaMes.
     */
    public Long getCodigoCustoPessoaMes() {
        return this.codigoCustoPessoaMes;
    }

    /**
     * Atualiza o valor do atributo codigoCustoPessoaMes.<BR>
     * Atributo gerado a partir da coluna CUPM_CD_CUSTO_PESSOA_MES.
     * @param codigoCustoPessoaMes Novo valor para o atributo codigoCustoPessoaMes.
     */
    public void setCodigoCustoPessoaMes(final Long codigoCustoPessoaMes) {
        this.codigoCustoPessoaMes = codigoCustoPessoaMes;
    }

    /**
     * Obtem o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     * @return Valor do atributo pessoa.
     */
    public Pessoa getPessoa() {
        return this.pessoa;
    }

    /**
     * Atualiza o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     * @param pessoa Novo valor para o atributo pessoa.
     */
    public void setPessoa(final Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    /**
     * Obtem o valor do atributo dataMes.<BR>
     * Atributo gerado a partir da coluna CUPM_DT_MES.
     * @return Valor do atributo dataMes.
     */
    public Date getDataMes() {
        return this.dataMes;
    }

    /**
     * Atualiza o valor do atributo dataMes.<BR>
     * Atributo gerado a partir da coluna CUPM_DT_MES.
     * @param dataMes Novo valor para o atributo dataMes.
     */
    public void setDataMes(final Date dataMes) {
        this.dataMes = dataMes;
    }

    /**
     * Obtem o valor do atributo valorSalario.<BR>
     * Atributo gerado a partir da coluna CUPM_VL_SALARIO.
     * @return Valor do atributo valorSalario.
     */
    public BigDecimal getValorSalario() {
        return this.valorSalario;
    }

    /**
     * Atualiza o valor do atributo valorSalario.<BR>
     * Atributo gerado a partir da coluna CUPM_VL_SALARIO.
     * @param valorSalario Novo valor para o atributo valorSalario.
     */
    public void setValorSalario(final BigDecimal valorSalario) {
        this.valorSalario = valorSalario;
    }

    /**
     * Obtem o valor do atributo valorJornada.<BR>
     * Atributo gerado a partir da coluna CUPM_VL_JORNADA.
     * @return Valor do atributo valorJornada.
     */
    public BigDecimal getValorJornada() {
        return this.valorJornada;
    }

    /**
     * Atualiza o valor do atributo valorJornada.<BR>
     * Atributo gerado a partir da coluna CUPM_VL_JORNADA.
     * @param valorJornada Novo valor para o atributo valorJornada.
     */
    public void setValorJornada(final BigDecimal valorJornada) {
        this.valorJornada = valorJornada;
    }

    /**
     * Obtem o valor do atributo indicadorOrigem.<BR>
     * Atributo gerado a partir da coluna CUPM_IN_ORIGEM.
     * @return Valor do atributo indicadorOrigem.
     */
    public String getIndicadorOrigem() {
        return this.indicadorOrigem;
    }

    /**
     * Atualiza o valor do atributo indicadorOrigem.<BR>
     * Atributo gerado a partir da coluna CUPM_IN_ORIGEM.
     * @param indicadorOrigem Novo valor para o atributo indicadorOrigem.
     */
    public void setIndicadorOrigem(final String indicadorOrigem) {
        this.indicadorOrigem = indicadorOrigem;
    }

    /**
     * Obtem o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * @return Valor do atributo moeda.
     */
    public Moeda getMoeda() {
        return this.moeda;
    }

    /**
     * Atualiza o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * @param moeda Novo valor para o atributo moeda.
     */
    public void setMoeda(final Moeda moeda) {
        this.moeda = moeda;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoCustoPessoaMes").append("='").append(
                getCodigoCustoPessoaMes()).append("' ");
        buffer.append("pessoa").append("='").append(getPessoa())
                .append("' ");
        buffer.append("dataMes").append("='").append(getDataMes()).append("' ");
        buffer.append("valorSalario").append("='").append(getValorSalario())
                .append("' ");
        buffer.append("valorJornada").append("='").append(getValorJornada())
                .append("' ");
        buffer.append("indicadorOrigem").append("='").append(
                getIndicadorOrigem()).append("' ");
        buffer.append("moeda").append("='").append(getMoeda())
                .append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}