/*
 * @(#) CustoBasePapelAlocacao.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela CUSTO_BASE_PAPEL_ALOCACAO.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 12/07/2011 16:36:52
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "CUSTO_BASE_PAPEL_ALOCACAO")
@NamedQueries({
        @NamedQuery(name = "CustoBasePapelAlocacao.findAll", query = "SELECT t FROM CustoBasePapelAlocacao t"),
        @NamedQuery(name = "CustoBasePapelAlocacao.findByBasePapelAlocacao",
                query = "SELECT cbpa FROM CustoBasePapelAlocacao cbpa "
                        + "WHERE cbpa.basePapelAlocacao.codigoBasePapelAlocacao = ? "
                        + "ORDER BY cbpa.dataInicio ASC "),

        @NamedQuery(name = "CustoBasePapelAlocacao.findMaxStartDateByBasePapelAlocacao",
                query = "SELECT cbpa FROM CustoBasePapelAlocacao cbpa "
                        + "WHERE cbpa.basePapelAlocacao.codigoBasePapelAlocacao = ? "
                        + "AND cbpa.dataInicio = "
                        + "(SELECT MAX(t.dataInicio) FROM CustoBasePapelAlocacao t "
                        + "WHERE t.basePapelAlocacao.codigoBasePapelAlocacao = ?) "),

        @NamedQuery(name = "CustoBasePapelAlocacao.findByBasePapelAndDate",
                query = "SELECT cbpa FROM CustoBasePapelAlocacao cbpa "
                        + "WHERE cbpa.basePapelAlocacao.codigoBasePapelAlocacao = ? "
                        + " AND TRUNC(?) >= TRUNC(cbpa.dataInicio) "
                        + " AND (TRUNC(?) <= TRUNC(cbpa.dataFim) OR cbpa.dataFim is null)"),

        @NamedQuery(name = "CustoBasePapelAlocacao.findByStartDate",
                query = " SELECT t FROM CustoBasePapelAlocacao t "
                        + " WHERE t.dataInicio = ? " + " AND t.basePapelAlocacao.codigoBasePapelAlocacao = ?"),

        @NamedQuery(name = "CustoBasePapelAlocacao.findPrevious", query = "SELECT t FROM CustoBasePapelAlocacao t"
                + " WHERE t.basePapelAlocacao.codigoBasePapelAlocacao = ? "
                + " AND TRUNC(t.dataInicio) = "
                + "     (SELECT MAX(TRUNC(cbpaBefore.dataInicio)) "
                + "         FROM CustoBasePapelAlocacao cbpaBefore "
                + "         WHERE cbpaBefore.basePapelAlocacao.codigoBasePapelAlocacao = ?"
                + "         AND cbpaBefore.dataInicio < ?)"),

        @NamedQuery(name = "CustoBasePapelAlocacao.findNext", query = "SELECT t FROM CustoBasePapelAlocacao t"
                + " WHERE t.basePapelAlocacao.codigoBasePapelAlocacao = ? "
                + " AND TRUNC(t.dataInicio) = "
                + "     (SELECT MIN(TRUNC(cbpaNext.dataInicio)) "
                + "         FROM CustoBasePapelAlocacao cbpaNext "
                + "         WHERE cbpaNext.basePapelAlocacao.codigoBasePapelAlocacao = ?"
                + "         AND cbpaNext.dataInicio > ?)"),

        @NamedQuery(name = "CustoBasePapelAlocacao.findByBasePapelAndCurrentDate",
                query = "SELECT cbpa FROM CustoBasePapelAlocacao cbpa "
                        + "WHERE cbpa.basePapelAlocacao.codigoBasePapelAlocacao = ? "
                        + "and TRUNC(sysdate,'MM') BETWEEN cbpa.dataInicio and NVL(cbpa.dataFim, sysdate + 30)"),

        @NamedQuery(name = "CustoBasePapelAlocacao.findByStartDateGreaterThan",
                query = "select cbpa from CustoBasePapelAlocacao cbpa \n"
                        + "    where cbpa.basePapelAlocacao.codigoBasePapelAlocacao = ? \n"
                        + "      and cbpa.dataInicio > ?")

})
public class CustoBasePapelAlocacao implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /**
     * Constante para NamedQuery
     * "CustoBasePapelAlocacao.findByBasePapelAlocacao".
     */
    public static final String FIND_BY_BASE_PAPEL_ALOCACAO = "CustoBasePapelAlocacao.findByBasePapelAlocacao";

    /**
     * Constante para NamedQuery
     * "CustoBasePapelAlocacao.findByBasePapelAlocacao".
     */
    public static final String FIND_BY_START_DATE = "CustoBasePapelAlocacao.findByStartDate";

    /**
     * Constante para NamedQuery
     * "CustoBasePapelAlocacao.findMaxStartDateByBasePapelAlocacao".
     */
    public static final String FIND_MAX_START_DATE_BY_BASE_PAPEL_ALOCACAO =
            "CustoBasePapelAlocacao.findMaxStartDateByBasePapelAlocacao";

    /**
     * Constante para NamedQuery
     * "CustoBasePapelAlocacao.findByBasePapelAndDate".
     */
    public static final String FIND_BY_BASE_PAPEL_AND_DATE = "CustoBasePapelAlocacao.findByBasePapelAndDate";

    /** Constante para NamedQuery "CustoBasePapelAlocacao.findPrevious". */
    public static final String FIND_PREVIOUS = "CustoBasePapelAlocacao.findPrevious";

    /** Constante para NamedQuery "CustoBasePapelAlocacao.findNext". */
    public static final String FIND_NEXT = "CustoBasePapelAlocacao.findNext";

    /**
     * Constante para NamedQuery
     * "CustoBasePapelAlocacao.findByBasePapelAndCurrentDate".
     */
    public static final String FIND_BY_BASE_PAPEL_AND_CURRENT_DATE = "CustoBasePapelAlocacao.findByBasePapelAndCurrentDate";

    public static final String FIND_BY_START_DATE_GREATER_THAN = "CustoBasePapelAlocacao.findByStartDateGreaterThan";

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "CustoBasePapelAlocacao.findAll".
     */
    public static final String FIND_ALL = "CustoBasePapelAlocacao.findAll";

    /**
     * Atributo gerado a partir da coluna CBPA_CD_BASE_PAPEL_ALOCACAO.
     */
    @Id
    @GeneratedValue(generator = "CustoBasePapelAlocacaoSeq")
    @SequenceGenerator(name = "CustoBasePapelAlocacaoSeq", sequenceName = "SQ_CBPA_CD_CUSTO_BASE_PAPEL_AL", allocationSize = 1)
    @Column(name = "CBPA_CD_CUSTO_BASE_PAPEL_ALOC", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoCustoBasePapelAloc;

    /**
     * Atributo gerado a partir da coluna BAPA_CD_BASE_PAPEL_ALOCACAO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BAPA_CD_BASE_PAPEL_ALOCACAO", nullable = false)
    private BasePapelAlocacao basePapelAlocacao;

    /**
     * Atributo gerado a partir da coluna CBPA_DT_INICIO.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "CBPA_DT_INICIO", length = 7)
    private Date dataInicio;

    /**
     * Atributo gerado a partir da coluna CBPA_DT_FIM.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "CBPA_DT_FIM", length = 7)
    private Date dataFim;

    /**
     * Atributo gerado a partir da coluna CBPA_VL_BASE_PAPEL_ALOCACAO.
     */

    @Column(name = "CBPA_VL_BASE_PAPEL_ALOCACAO", precision = 22, scale = 0)
    private BigDecimal valorBasePapelAlocacao;

    @Column(name = "CBPA_VL_SALARIO", precision = 22, scale = 0)
    private BigDecimal valorSalario;

    @Column(name = "CBPA_VL_BENEFICIOS", precision = 22, scale = 0)
    private BigDecimal valorBeneficios;

    @Column(name = "CBPA_VL_IMPOSTOS", precision = 22, scale = 0)
    private BigDecimal valorImpostos;

    @Column(name = "CBPA_VL_PROVISIONAMENTO", precision = 22, scale = 0)
    private BigDecimal valorProvisionamento;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CBPA_DT_LAST_UPDATE")
    private Date lastUpdated;

    @Column(name = "CBPA_CD_LOGIN_UPDATE", length = 20)
    private String updateAuthor;

    /**
     * Construtor default.
     */
    public CustoBasePapelAlocacao() {
    }

    /**
     * Construtor com preenchimento da entidade.
     *
     * @param codigoCustoBasePapelAloc
     *            Valor do atributo codigoBasePapelAlocacao;
     * @param basePapelAlocacao
     *            Valor do atributo basePapelAlocacao;
     */
    public CustoBasePapelAlocacao(final Long codigoCustoBasePapelAloc,
                                  final BasePapelAlocacao basePapelAlocacao) {
        this.codigoCustoBasePapelAloc = codigoCustoBasePapelAloc;
        this.basePapelAlocacao = basePapelAlocacao;
    }

    /**
     * Construtor com preenchimento da entidade.
     *
     * @param codigoCustoBasePapelAloc
     *            Valor do atributo codigoBasePapelAlocacao;
     * @param basePapelAlocacao
     *            Valor do atributo basePapelAlocacao;
     * @param dataInicio
     *            Valor do atributo dataInicio;
     * @param dataFim
     *            Valor do atributo dataFim;
     * @param valorBasePapelAlocacao
     *            Valor do atributo valorBasePapelAlocacao;
     */
    public CustoBasePapelAlocacao(final Long codigoCustoBasePapelAloc,
                                  final BasePapelAlocacao basePapelAlocacao, final Date dataInicio,
                                  final Date dataFim, final BigDecimal valorBasePapelAlocacao,
                                  final BigDecimal valorSalario, final BigDecimal valorBeneficios,
                                  final BigDecimal valorImpostos, final BigDecimal valorProvisionamento) {
        this.codigoCustoBasePapelAloc = codigoCustoBasePapelAloc;
        this.basePapelAlocacao = basePapelAlocacao;
        this.dataInicio = dataInicio;
        this.dataFim = dataFim;
        this.valorBasePapelAlocacao = valorBasePapelAlocacao;
        this.valorSalario = valorSalario;
        this.valorBeneficios = valorBeneficios;
        this.valorImpostos = valorImpostos;
        this.valorProvisionamento = valorProvisionamento;
    }

    /**
     * Obtem o valor do atributo codigoBasePapelAlocacao.<BR>
     * Atributo gerado a partir da coluna CBPA_CD_BASE_PAPEL_ALOCACAO.
     *
     * @return Valor do atributo codigoBasePapelAlocacao.
     */
    public Long getCodigoCustoBasePapelAloc() {
        return this.codigoCustoBasePapelAloc;
    }

    /**
     * Atualiza o valor do atributo codigoBasePapelAlocacao.<BR>
     * Atributo gerado a partir da coluna CBPA_CD_BASE_PAPEL_ALOCACAO.
     *
     * @param codigoCustoBasePapelAloc
     *            Novo valor para o atributo codigoBasePapelAlocacao.
     */
    public void setCodigoCustoBasePapelAloc(final Long codigoCustoBasePapelAloc) {
        this.codigoCustoBasePapelAloc = codigoCustoBasePapelAloc;
    }

    /**
     * Obtem o valor do atributo basePapelAlocacao.<BR>
     * Atributo gerado a partir da coluna BAPA_CD_BASE_PAPEL_ALOCACAO.
     *
     * @return Valor do atributo basePapelAlocacao.
     */
    public BasePapelAlocacao getBasePapelAlocacao() {
        return this.basePapelAlocacao;
    }

    /**
     * Atualiza o valor do atributo basePapelAlocacao.<BR>
     * Atributo gerado a partir da coluna BAPA_CD_BASE_PAPEL_ALOCACAO.
     *
     * @param basePapelAlocacao
     *            Novo valor para o atributo basePapelAlocacao.
     */
    public void setBasePapelAlocacao(final BasePapelAlocacao basePapelAlocacao) {
        this.basePapelAlocacao = basePapelAlocacao;
    }

    /**
     * Obtem o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna CBPA_DT_INICIO.
     *
     * @return Valor do atributo dataInicio.
     */
    public Date getDataInicio() {
        return this.dataInicio;
    }

    /**
     * Atualiza o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna CBPA_DT_INICIO.
     *
     * @param dataInicio
     *            Novo valor para o atributo dataInicio.
     */
    public void setDataInicio(final Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    /**
     * Obtem o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna CBPA_DT_FIM.
     *
     * @return Valor do atributo dataFim.
     */
    public Date getDataFim() {
        return this.dataFim;
    }

    /**
     * Atualiza o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna CBPA_DT_FIM.
     *
     * @param dataFim
     *            Novo valor para o atributo dataFim.
     */
    public void setDataFim(final Date dataFim) {
        this.dataFim = dataFim;
    }

    /**
     * Obtem o valor do atributo valorBasePapelAlocacao.<BR>
     * Atributo gerado a partir da coluna CBPA_VL_BASE_PAPEL_ALOCACAO.
     *
     * @return Valor do atributo valorBasePapelAlocacao.
     */
    public BigDecimal getValorBasePapelAlocacao() {
        return this.valorBasePapelAlocacao;
    }

    /**
     * Atualiza o valor do atributo valorBasePapelAlocacao.<BR>
     * Atributo gerado a partir da coluna CBPA_VL_BASE_PAPEL_ALOCACAO.
     *
     * @param valorBasePapelAlocacao
     *            Novo valor para o atributo valorBasePapelAlocacao.
     */
    public void setValorBasePapelAlocacao(
            final BigDecimal valorBasePapelAlocacao) {
        this.valorBasePapelAlocacao = valorBasePapelAlocacao;
    }

    /**
     * Obtem o valor do atributo valorSalario.<BR>
     * Atributo gerado a partir da coluna CBPA_VL_SALARIO.
     *
     * @return Valor do atributo valorSalario.
     */
    public BigDecimal getValorSalario() {
        return this.valorSalario;
    }

    /**
     * Atualiza o valor do atributo valorSalario.<BR>
     * Atributo gerado a partir da coluna CBPA_VL_SALARIO.
     *
     * @param valorSalario
     *            Novo valor para o atributo valorSalario.
     */
    public void setValorSalario(
            final BigDecimal valorSalario) {
        this.valorSalario = valorSalario;
    }

    /**
     * Obtem o valor do atributo valorBeneficios.<BR>
     * Atributo gerado a partir da coluna CBPA_VL_BENEFICIOS.
     *
     * @return Valor do atributo valorBeneficios.
     */
    public BigDecimal getValorBeneficios() {
        return this.valorBeneficios;
    }

    /**
     * Atualiza o valor do atributo valorBeneficios.<BR>
     * Atributo gerado a partir da coluna CBPA_VL_BENEFICIOS.
     *
     * @param valorBeneficios
     *            Novo valor para o atributo valorBeneficios.
     */
    public void setValorBeneficios(
            final BigDecimal valorBeneficios) {
        this.valorBeneficios = valorBeneficios;
    }

    /**
     * Obtem o valor do atributo valorImpostos.<BR>
     * Atributo gerado a partir da coluna CBPA_VL_IMPOSTOS.
     *
     * @return Valor do atributo valorImpostos.
     */
    public BigDecimal getValorImpostos() {
        return this.valorImpostos;
    }

    /**
     * Atualiza o valor do atributo valorImpostos.<BR>
     * Atributo gerado a partir da coluna CBPA_VL_IMPOSTOS.
     *
     * @param valorImpostos
     *            Novo valor para o atributo valorImpostos.
     */
    public void setValorImpostos(
            final BigDecimal valorImpostos) {
        this.valorImpostos = valorImpostos;
    }

    /**
     * Obtem o valor do atributo valorProvisionamento.<BR>
     * Atributo gerado a partir da coluna CBPA_VL_PROVISIONAMENTO.
     *
     * @return Valor do atributo valorProvisionamento.
     */
    public BigDecimal getValorProvisionamento() {
        return this.valorProvisionamento;
    }

    /**
     * Atualiza o valor do atributo valorProvisionamento.<BR>
     * Atributo gerado a partir da coluna CBPA_VL_PROVISIONAMENTO.
     *
     * @param valorProvisionamento
     *            Novo valor para o atributo valorProvisionamento.
     */
    public void setValorProvisionamento(
            final BigDecimal valorProvisionamento) {
        this.valorProvisionamento = valorProvisionamento;
    }

    public Date getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public String getUpdateAuthor() {
        return updateAuthor;
    }

    public void setUpdateAuthor(String updateAuthor) {
        this.updateAuthor = updateAuthor;
    }

    /**
     * @see Object#toString()
     * @return string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoCustoBasePapelAloc").append("='").append(
                getCodigoCustoBasePapelAloc()).append("' ");
        buffer.append("basePapelAlocacao").append("='").append(
                getBasePapelAlocacao()).append("' ");
        buffer.append("dataInicio").append("='").append(getDataInicio())
                .append("' ");
        buffer.append("dataFim").append("='").append(getDataFim()).append("' ");
        buffer.append("valorBasePapelAlocacao").append("='").append(
                getValorBasePapelAlocacao()).append("' ");
        buffer.append("valorSalario").append("='").append(
                getValorBasePapelAlocacao()).append("' ");
        buffer.append("valorBeneficios").append("='").append(
                getValorBasePapelAlocacao()).append("' ");
        buffer.append("valorImpostos").append("='").append(
                getValorBasePapelAlocacao()).append("' ");
        buffer.append("valorProvisionamento").append("='").append(
                getValorBasePapelAlocacao()).append("' ");
        buffer.append("lastUpdated").append("='").append(
                getLastUpdated()).append("' ");
        buffer.append("updateAuthor").append("='").append(
                getUpdateAuthor()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public CustoBasePapelAlocacao clone() {
        CustoBasePapelAlocacao clone = new CustoBasePapelAlocacao();
        clone.setCodigoCustoBasePapelAloc(this.codigoCustoBasePapelAloc);
        clone.setBasePapelAlocacao(this.basePapelAlocacao);
        clone.setDataInicio(this.dataInicio);
        clone.setDataFim(this.dataFim);
        clone.setValorBasePapelAlocacao(this.valorBasePapelAlocacao);
        clone.setValorSalario(this.valorSalario);
        clone.setValorBeneficios(this.valorBeneficios);
        clone.setValorProvisionamento(this.valorProvisionamento);
        clone.setValorImpostos(this.valorImpostos);

        return clone;
    }

}
