/*
 * @(#) DocumentoLegalTipo.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.ciandt.pms.Constants;

/**
 * Entity gerado a partir da tabela DOCUMENTO_LEGAL_TIPO.
 *
 * @author Generated by Hibernate Tools 3.4.0.CR1
 * @since 14/11/2013 14:55:05
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "DOCUMENTO_LEGAL_TIPO")
@NamedQueries({
	@NamedQuery(name = "DocumentoLegalTipo.findAll", query = "SELECT t FROM DocumentoLegalTipo t"),
	@NamedQuery(name = "DocumentoLegalTipo.findAllActive", query = "SELECT dt FROM DocumentoLegalTipo dt "
			+ "WHERE dt.indicadorAtivo = '" + Constants.ACTIVE + "'")
})
public class DocumentoLegalTipo implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * Constante para NamedQuery "DocumentoLegalTipo.findAll".
	 */
	public static final String FIND_ALL = "DocumentoLegalTipo.findAll";
	
	/** 
	 * Constante para NamedQuery "DocumentoLegalTipo.findAllActive".
	 */
	public static final String FIND_ALL_ACTIVE = "DocumentoLegalTipo.findAllActive";

	/**
	 * Atributo gerado a partir da coluna DOLT_CD_TIPO_DOCUMENTO_LEGAL.
	 */
	@Id
	@GeneratedValue(generator = "DocumentoLegalTipoSeq")
	@SequenceGenerator(name = "DocumentoLegalTipoSeq", sequenceName = "SQ_DOLT_CD_TP_DOCUMENTO_LEGAL", allocationSize = 1)
	@Column(name = "DOLT_CD_TIPO_DOCUMENTO_LEGAL", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoTipoDocumentoLegal;

	/**
	 * Atributo gerado a partir da coluna DOLT_NM_TIPO_DOCUMENTO_LEGAL.
	 */

	@Column(name = "DOLT_NM_TIPO_DOCUMENTO_LEGAL", length = 100)
	private String nomeTipoDocumentoLegal;

	/**
	 * Atributo gerado a partir da coluna DOLT_SG_TIPO_DOCUMENTO_LEGAL.
	 */

	@Column(name = "DOLT_SG_TIPO_DOCUMENTO_LEGAL", length = 2)
	private String siglaTipoDocumentoLegal;

	/**
	 * Atributo gerado a partir da coluna DOLT_IN_ATIVO.
	 */

	@Column(name = "DOLT_IN_ATIVO", length = 1)
	private String indicadorAtivo;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentoLegalTipo")
	private Set<DocumentoLegal> documentoLegals = new HashSet<DocumentoLegal>(0);

	/**
	 * Construtor default.
	 */
	public DocumentoLegalTipo() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * @param codigoTipoDocumentoLegal Valor do atributo codigoTipoDocumentoLegal;
	 */
	public DocumentoLegalTipo(Long codigoTipoDocumentoLegal) {
		this.codigoTipoDocumentoLegal = codigoTipoDocumentoLegal;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * @param codigoTipoDocumentoLegal Valor do atributo codigoTipoDocumentoLegal;
	 */
	public DocumentoLegalTipo(Long codigoTipoDocumentoLegal,
			String nomeTipoDocumentoLegal, String siglaTipoDocumentoLegal,
			String indicadorAtivo, Set<DocumentoLegal> documentoLegals) {
		this.codigoTipoDocumentoLegal = codigoTipoDocumentoLegal;
		this.nomeTipoDocumentoLegal = nomeTipoDocumentoLegal;
		this.siglaTipoDocumentoLegal = siglaTipoDocumentoLegal;
		this.indicadorAtivo = indicadorAtivo;
		this.documentoLegals = documentoLegals;
	}

	/**
	 * Obtem o valor do atributo codigoTipoDocumentoLegal.<BR>
	 * Atributo gerado a partir da coluna DOLT_CD_TIPO_DOCUMENTO_LEGAL.
	 * @return Valor do atributo codigoTipoDocumentoLegal.
	 */
	public Long getCodigoTipoDocumentoLegal() {
		return this.codigoTipoDocumentoLegal;
	}

	/**
	 * Atualiza o valor do atributo codigoTipoDocumentoLegal.<BR>
	 * Atributo gerado a partir da coluna DOLT_CD_TIPO_DOCUMENTO_LEGAL.
	 * @param codigoTipoDocumentoLegal Novo valor para o atributo codigoTipoDocumentoLegal.
	 */
	public void setCodigoTipoDocumentoLegal(Long codigoTipoDocumentoLegal) {
		this.codigoTipoDocumentoLegal = codigoTipoDocumentoLegal;
	}

	/**
	 * Obtem o valor do atributo nomeTipoDocumentoLegal.<BR>
	 * Atributo gerado a partir da coluna DOLT_NM_TIPO_DOCUMENTO_LEGAL.
	 * @return Valor do atributo nomeTipoDocumentoLegal.
	 */
	public String getNomeTipoDocumentoLegal() {
		return this.nomeTipoDocumentoLegal;
	}

	/**
	 * Atualiza o valor do atributo nomeTipoDocumentoLegal.<BR>
	 * Atributo gerado a partir da coluna DOLT_NM_TIPO_DOCUMENTO_LEGAL.
	 * @param nomeTipoDocumentoLegal Novo valor para o atributo nomeTipoDocumentoLegal.
	 */
	public void setNomeTipoDocumentoLegal(String nomeTipoDocumentoLegal) {
		this.nomeTipoDocumentoLegal = nomeTipoDocumentoLegal;
	}

	/**
	 * Obtem o valor do atributo siglaTipoDocumentoLegal.<BR>
	 * Atributo gerado a partir da coluna DOLT_SG_TIPO_DOCUMENTO_LEGAL.
	 * @return Valor do atributo siglaTipoDocumentoLegal.
	 */
	public String getSiglaTipoDocumentoLegal() {
		return this.siglaTipoDocumentoLegal;
	}

	/**
	 * Atualiza o valor do atributo siglaTipoDocumentoLegal.<BR>
	 * Atributo gerado a partir da coluna DOLT_SG_TIPO_DOCUMENTO_LEGAL.
	 * @param siglaTipoDocumentoLegal Novo valor para o atributo siglaTipoDocumentoLegal.
	 */
	public void setSiglaTipoDocumentoLegal(String siglaTipoDocumentoLegal) {
		this.siglaTipoDocumentoLegal = siglaTipoDocumentoLegal;
	}

	/**
	 * Obtem o valor do atributo indicadorAtivo.<BR>
	 * Atributo gerado a partir da coluna DOLT_IN_ATIVO.
	 * @return Valor do atributo indicadorAtivo.
	 */
	public String getIndicadorAtivo() {
		return this.indicadorAtivo;
	}

	/**
	 * Atualiza o valor do atributo indicadorAtivo.<BR>
	 * Atributo gerado a partir da coluna DOLT_IN_ATIVO.
	 * @param indicadorAtivo Novo valor para o atributo indicadorAtivo.
	 */
	public void setIndicadorAtivo(String indicadorAtivo) {
		this.indicadorAtivo = indicadorAtivo;
	}

	/**
	 * Obtem o valor do atributo documentoLegals.<BR>

	 * @return Valor do atributo documentoLegals.
	 */
	public Set<DocumentoLegal> getDocumentoLegals() {
		return this.documentoLegals;
	}

	/**
	 * Atualiza o valor do atributo documentoLegals.<BR>

	 * @param documentoLegals Novo valor para o atributo documentoLegals.
	 */
	public void setDocumentoLegals(Set<DocumentoLegal> documentoLegals) {
		this.documentoLegals = documentoLegals;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoTipoDocumentoLegal").append("='")
				.append(getCodigoTipoDocumentoLegal()).append("' ");
		buffer.append("nomeTipoDocumentoLegal").append("='")
				.append(getNomeTipoDocumentoLegal()).append("' ");
		buffer.append("siglaTipoDocumentoLegal").append("='")
				.append(getSiglaTipoDocumentoLegal()).append("' ");
		buffer.append("indicadorAtivo").append("='")
				.append(getIndicadorAtivo()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
