/*
 * @(#) DocumentoLegalAnexoArquivo.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela DOCUMENTO_LEGAL_ANEXO_ARQUIVO.
 *
 * @author Generated by Hibernate Tools 3.4.0.CR1
 * @since 14/11/2013 14:55:05
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "DOCUMENTO_LEGAL_ANEXO_ARQUIVO")
@NamedQueries({
	@NamedQuery(name = "DocumentoLegalAnexoArquivo.findAll", query = "SELECT t FROM DocumentoLegalAnexoArquivo t"),
	@NamedQuery(name = "DocumentoLegalAnexoArquivo.findByDocumentolegal", query = "SELECT da FROM DocumentoLegalAnexoArquivo da "
			+ "WHERE da.documentoLegal = :documentoLegal"),
	@NamedQuery(name = "DocumentoLegalAnexoArquivo.findByFileName", query="SELECT t FROM DocumentoLegalAnexoArquivo t "
			+ "WHERE t.nomeDocLegalAnexoArq = ?")
})
public class DocumentoLegalAnexoArquivo implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * Constante para NamedQuery "DocumentoLegalAnexoArquivo.findAll".
	 */
	public static final String FIND_ALL = "DocumentoLegalAnexoArquivo.findAll";
	
	/** 
	 * Constante para NamedQuery "DocumentoLegalAnexoArquivo.findByDocumentolegal".
	 */
	public static final String FIND_BY_DOCUMENTO_LEGAL = "DocumentoLegalAnexoArquivo.findByDocumentolegal";
	
	/** 
	 * Constante para NamedQuery "DocumentoLegalAnexoArquivo.findByFileName".
	 */
	public static final String FIND_BY_FILE_NAME = "DocumentoLegalAnexoArquivo.findByFileName";

	/**
	 * Atributo gerado a partir da coluna DLAA_CD_DOC_LEGAL_ANEXO_ARQ.
	 */
	@Id
	@GeneratedValue(generator = "DocumentoLegalAnexoArquivoSeq")
	@SequenceGenerator(name = "DocumentoLegalAnexoArquivoSeq", sequenceName = "SQ_DLAA_CD_DOC_LEGAL_ANEXO_ARQ", allocationSize = 1)
	@Column(name = "DLAA_CD_DOC_LEGAL_ANEXO_ARQ", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoDocLegalAnexoArq;

	/**
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PESS_CD_PESSOA", nullable = false)
	private Pessoa pessoa;

	/**
	 * Atributo gerado a partir da coluna DOLE_CD_DOCUMENTO_LEGAL.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOLE_CD_DOCUMENTO_LEGAL", nullable = false)
	private DocumentoLegal documentoLegal;

	/**
	 * Atributo gerado a partir da coluna DLAA_NM_DOC_LEGAL_ANEXO_ARQ.
	 */

	@Column(name = "DLAA_NM_DOC_LEGAL_ANEXO_ARQ", length = 150)
	private String nomeDocLegalAnexoArq;

	/**
	 * Atributo gerado a partir da coluna DLAA_DT_DOC_LEGAL_ANEXO_ARQ.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "DLAA_DT_DOC_LEGAL_ANEXO_ARQ", length = 7)
	private Date dataDocLegalAnexoArq;

	/**
	 * Atributo gerado a partir da coluna DLAA_TX_COMENTARIO.
	 */

	@Column(name = "DLAA_TX_COMENTARIO", length = 300)
	private String textoComentario;

	/**
	 * Construtor default.
	 */
	public DocumentoLegalAnexoArquivo() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * @param codigoDocLegalAnexoArq Valor do atributo codigoDocLegalAnexoArq;
	 * @param pessoa Valor do atributo pessoa;
	 * @param documentoLegal Valor do atributo documentoLegal;
	 */
	public DocumentoLegalAnexoArquivo(Long codigoDocLegalAnexoArq,
			Pessoa pessoa, DocumentoLegal documentoLegal) {
		this.codigoDocLegalAnexoArq = codigoDocLegalAnexoArq;
		this.pessoa = pessoa;
		this.documentoLegal = documentoLegal;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * @param codigoDocLegalAnexoArq Valor do atributo codigoDocLegalAnexoArq;
	 * @param pessoa Valor do atributo pessoa;
	 * @param documentoLegal Valor do atributo documentoLegal;
	 */
	public DocumentoLegalAnexoArquivo(Long codigoDocLegalAnexoArq,
			Pessoa pessoa, DocumentoLegal documentoLegal,
			String nomeDocLegalAnexoArq, Date dataDocLegalAnexoArq,
			String textoComentario) {
		this.codigoDocLegalAnexoArq = codigoDocLegalAnexoArq;
		this.pessoa = pessoa;
		this.documentoLegal = documentoLegal;
		this.nomeDocLegalAnexoArq = nomeDocLegalAnexoArq;
		this.dataDocLegalAnexoArq = dataDocLegalAnexoArq;
		this.textoComentario = textoComentario;
	}

	/**
	 * Obtem o valor do atributo codigoDocLegalAnexoArq.<BR>
	 * Atributo gerado a partir da coluna DLAA_CD_DOC_LEGAL_ANEXO_ARQ.
	 * @return Valor do atributo codigoDocLegalAnexoArq.
	 */
	public Long getCodigoDocLegalAnexoArq() {
		return this.codigoDocLegalAnexoArq;
	}

	/**
	 * Atualiza o valor do atributo codigoDocLegalAnexoArq.<BR>
	 * Atributo gerado a partir da coluna DLAA_CD_DOC_LEGAL_ANEXO_ARQ.
	 * @param codigoDocLegalAnexoArq Novo valor para o atributo codigoDocLegalAnexoArq.
	 */
	public void setCodigoDocLegalAnexoArq(Long codigoDocLegalAnexoArq) {
		this.codigoDocLegalAnexoArq = codigoDocLegalAnexoArq;
	}

	/**
	 * Obtem o valor do atributo pessoa.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 * @return Valor do atributo pessoa.
	 */
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	/**
	 * Atualiza o valor do atributo pessoa.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 * @param pessoa Novo valor para o atributo pessoa.
	 */
	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	/**
	 * Obtem o valor do atributo documentoLegal.<BR>
	 * Atributo gerado a partir da coluna DOLE_CD_DOCUMENTO_LEGAL.
	 * @return Valor do atributo documentoLegal.
	 */
	public DocumentoLegal getDocumentoLegal() {
		return this.documentoLegal;
	}

	/**
	 * Atualiza o valor do atributo documentoLegal.<BR>
	 * Atributo gerado a partir da coluna DOLE_CD_DOCUMENTO_LEGAL.
	 * @param documentoLegal Novo valor para o atributo documentoLegal.
	 */
	public void setDocumentoLegal(DocumentoLegal documentoLegal) {
		this.documentoLegal = documentoLegal;
	}

	/**
	 * Obtem o valor do atributo nomeDocLegalAnexoArq.<BR>
	 * Atributo gerado a partir da coluna DLAA_NM_DOC_LEGAL_ANEXO_ARQ.
	 * @return Valor do atributo nomeDocLegalAnexoArq.
	 */
	public String getNomeDocLegalAnexoArq() {
		return this.nomeDocLegalAnexoArq;
	}

	/**
	 * Atualiza o valor do atributo nomeDocLegalAnexoArq.<BR>
	 * Atributo gerado a partir da coluna DLAA_NM_DOC_LEGAL_ANEXO_ARQ.
	 * @param nomeDocLegalAnexoArq Novo valor para o atributo nomeDocLegalAnexoArq.
	 */
	public void setNomeDocLegalAnexoArq(String nomeDocLegalAnexoArq) {
		this.nomeDocLegalAnexoArq = nomeDocLegalAnexoArq;
	}

	/**
	 * Obtem o valor do atributo dataDocLegalAnexoArq.<BR>
	 * Atributo gerado a partir da coluna DLAA_DT_DOC_LEGAL_ANEXO_ARQ.
	 * @return Valor do atributo dataDocLegalAnexoArq.
	 */
	public Date getDataDocLegalAnexoArq() {
		return this.dataDocLegalAnexoArq;
	}

	/**
	 * Atualiza o valor do atributo dataDocLegalAnexoArq.<BR>
	 * Atributo gerado a partir da coluna DLAA_DT_DOC_LEGAL_ANEXO_ARQ.
	 * @param dataDocLegalAnexoArq Novo valor para o atributo dataDocLegalAnexoArq.
	 */
	public void setDataDocLegalAnexoArq(Date dataDocLegalAnexoArq) {
		this.dataDocLegalAnexoArq = dataDocLegalAnexoArq;
	}

	/**
	 * Obtem o valor do atributo textoComentario.<BR>
	 * Atributo gerado a partir da coluna DLAA_TX_COMENTARIO.
	 * @return Valor do atributo textoComentario.
	 */
	public String getTextoComentario() {
		return this.textoComentario;
	}

	/**
	 * Atualiza o valor do atributo textoComentario.<BR>
	 * Atributo gerado a partir da coluna DLAA_TX_COMENTARIO.
	 * @param textoComentario Novo valor para o atributo textoComentario.
	 */
	public void setTextoComentario(String textoComentario) {
		this.textoComentario = textoComentario;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoDocLegalAnexoArq").append("='")
				.append(getCodigoDocLegalAnexoArq()).append("' ");
		buffer.append("pessoa").append("='").append(getPessoa()).append("' ");
		buffer.append("documentoLegal").append("='")
				.append(getDocumentoLegal()).append("' ");
		buffer.append("nomeDocLegalAnexoArq").append("='")
				.append(getNomeDocLegalAnexoArq()).append("' ");
		buffer.append("dataDocLegalAnexoArq").append("='")
				.append(getDataDocLegalAnexoArq()).append("' ");
		buffer.append("textoComentario").append("='")
				.append(getTextoComentario()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
