/*
 * @(#) DocumentoLegalResponsavel.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela DOCUMENTO_LEGAL_RESPONSAVEL.
 * 
 * @author Generated by Hibernate Tools 3.6.0
 * @since 06/12/2013 16:56:59
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "DOCUMENTO_LEGAL_RESPONSAVEL")
@NamedQueries({
	@NamedQuery(name = "DocumentoLegalResponsavel.findAll", query = "SELECT t FROM DocumentoLegalResponsavel t"),
})
public class DocumentoLegalResponsavel implements java.io.Serializable, Cloneable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "DocumentoLegalResponsavel.findAll".
	 */
	public static final String FIND_ALL = "DocumentoLegalResponsavel.findAll";

	/**
	 * Constante para NamedQuery "DocumentoLegalResponsavel.findToSendEmail".
	 */
	public static final String FIND_TO_SEND_EMAIL = "DocumentoLegalResponsavel.findToSendEmail";

	/**
	 * Atributo gerado a partir da coluna DOLR_CD_DOCUMENTO_LEGAL_RESPON.
	 */
	@Id
	@GeneratedValue(generator = "DocumentoLegalResponsavelSeq")
	@SequenceGenerator(name = "DocumentoLegalResponsavelSeq", sequenceName = "SQ_DOLR_CD_DOCUMENTO_LEGAL_RES", allocationSize = 1)
	@Column(name = "DOLR_CD_DOCUMENTO_LEGAL_RESPON", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoDocumentoLegalResponsavel;

	/**
	 * Atributo gerado a partir da coluna DOLE_CD_DOCUMENTO_LEGAL.
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DOLE_CD_DOCUMENTO_LEGAL", nullable = false)
	private DocumentoLegal documentoLegal;

    /**
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PESS_CD_PESSOA", nullable = false)
    private Pessoa pessoa;

	/**
	 * Construtor default.
	 */
	public DocumentoLegalResponsavel() {
	}

	/**
	 * @return the codigoDocumentoLegalResponsavel
	 */
	public Long getCodigoDocumentoLegalResponsavel() {
		return codigoDocumentoLegalResponsavel;
	}

	/**
	 * @param codigoDocumentoLegalResponsavel the codigoDocumentoLegalResponsavel to set
	 */
	public void setCodigoDocumentoLegalResponsavel(
			Long codigoDocumentoLegalResponsavel) {
		this.codigoDocumentoLegalResponsavel = codigoDocumentoLegalResponsavel;
	}

	/**
	 * @return the documentoLegal
	 */
	public DocumentoLegal getDocumentoLegal() {
		return documentoLegal;
	}

	/**
	 * @param documentoLegal the documentoLegal to set
	 */
	public void setDocumentoLegal(DocumentoLegal documentoLegal) {
		this.documentoLegal = documentoLegal;
	}

	/**
	 * @return the pessoa
	 */
	public Pessoa getPessoa() {
		return pessoa;
	}

	/**
	 * @param pessoa the pessoa to set
	 */
	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

}