/*
 * @(#) DreLogFechamento.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela DRE_LOG_FECHAMENTO.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 07/06/2010 16:30:22
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "DRE_LOG_FECHAMENTO")
@NamedQueries({ 
    @NamedQuery(name = "DreLogFechamento.findAll", query = "SELECT t FROM DreLogFechamento t"),
    
    @NamedQuery(name = "DreLogFechamento.findByDataMes", query = "SELECT drlf FROM DreLogFechamento drlf "
        + "WHERE (drlf.dataMes = ?) ")
})
public class DreLogFechamento implements java.io.Serializable {
    
    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    
    /**
     * Constante para NamedQuery "DreLogFechamento.findByDataMes".
     */
    public static final String FIND_BY_DATA_MES = "DreLogFechamento.findByDataMes";
    
    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "DreLogFechamento.findAll".
     */
    public static final String FIND_ALL = "DreLogFechamento.findAll";

    /**
     * Atributo gerado a partir da coluna DRLF_CD_LOG_FECHAMENTO.
     */
    @Id
    @GeneratedValue(generator = "DreLogFechamentoSeq")
    @SequenceGenerator(name = "DreLogFechamentoSeq", 
            sequenceName = "SQ_DRLF_CD_LOG_FECHAMENTO", allocationSize = 1)
    @Column(name = "DRLF_CD_LOG_FECHAMENTO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoLogFechamento;

    /**
     * Atributo gerado a partir da coluna DRLF_DT_MES.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "DRLF_DT_MES", length = 7)
    private Date dataMes;

    /**
     * Atributo gerado a partir da coluna DRLF_DT_EXECUCAO.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DRLF_DT_EXECUCAO", length = 7)
    private Date dataExecucao;

    /**
     * Atributo gerado a partir da coluna DRLF_TX_LOG.
     */
    @Lob
    @Column(name = "DRLF_TX_LOG")
    @Basic(fetch = FetchType.LAZY)
    private String textoLog;

    /**
     * Atributo gerado a partir da coluna DRLF_CD_AUTOR.
     */

    @Column(name = "DRLF_CD_AUTOR", length = 50)
    private String codigoAutor;

    /**
     * Atributo gerado a partir da coluna DRLF_IN_SUCESSO.
     */

    @Column(name = "DRLF_IN_SUCESSO", length = 1)
    private String indicadorSucesso;

    /**
     * Construtor default.
     */
    public DreLogFechamento() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoLogFechamento Valor do atributo codigoLogFechamento;
     */
    public DreLogFechamento(final Long codigoLogFechamento) {
        this.codigoLogFechamento = codigoLogFechamento;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoLogFechamento Valor do atributo codigoLogFechamento;
     * @param dataMes Valor do atributo dataMes;
     * @param dataExecucao Valor do atributo dataExecucao;
     * @param textoLog Valor do atributo textoLog;
     * @param codigoAutor Valor do atributo codigoAutor;
     * @param indicadorSucesso Valor do atributo indicadorSucesso;
     */
    public DreLogFechamento(final Long codigoLogFechamento, final Date dataMes,
            final Date dataExecucao, final String textoLog, final String codigoAutor,
            final String indicadorSucesso) {
        this.codigoLogFechamento = codigoLogFechamento;
        this.dataMes = dataMes;
        this.dataExecucao = dataExecucao;
        this.textoLog = textoLog;
        this.codigoAutor = codigoAutor;
        this.indicadorSucesso = indicadorSucesso;
    }

    /**
     * Obtem o valor do atributo codigoLogFechamento.<BR>
     * Atributo gerado a partir da coluna DRLF_CD_LOG_FECHAMENTO.
     * @return Valor do atributo codigoLogFechamento.
     */
    public Long getCodigoLogFechamento() {
        return this.codigoLogFechamento;
    }

    /**
     * Atualiza o valor do atributo codigoLogFechamento.<BR>
     * Atributo gerado a partir da coluna DRLF_CD_LOG_FECHAMENTO.
     * @param codigoLogFechamento Novo valor para o atributo codigoLogFechamento.
     */
    public void setCodigoLogFechamento(final Long codigoLogFechamento) {
        this.codigoLogFechamento = codigoLogFechamento;
    }

    /**
     * Obtem o valor do atributo dataMes.<BR>
     * Atributo gerado a partir da coluna DRLF_DT_MES.
     * @return Valor do atributo dataMes.
     */
    public Date getDataMes() {
        return this.dataMes;
    }

    /**
     * Atualiza o valor do atributo dataMes.<BR>
     * Atributo gerado a partir da coluna DRLF_DT_MES.
     * @param dataMes Novo valor para o atributo dataMes.
     */
    public void setDataMes(final Date dataMes) {
        this.dataMes = dataMes;
    }

    /**
     * Obtem o valor do atributo dataExecucao.<BR>
     * Atributo gerado a partir da coluna DRLF_DT_EXECUCAO.
     * @return Valor do atributo dataExecucao.
     */
    public Date getDataExecucao() {
        return this.dataExecucao;
    }

    /**
     * Atualiza o valor do atributo dataExecucao.<BR>
     * Atributo gerado a partir da coluna DRLF_DT_EXECUCAO.
     * @param dataExecucao Novo valor para o atributo dataExecucao.
     */
    public void setDataExecucao(final Date dataExecucao) {
        this.dataExecucao = dataExecucao;
    }

    /**
     * Obtem o valor do atributo textoLog.<BR>
     * Atributo gerado a partir da coluna DRLF_TX_LOG.
     * @return Valor do atributo textoLog.
     */
    public String getTextoLog() {
        return this.textoLog;
    }

    /**
     * Atualiza o valor do atributo textoLog.<BR>
     * Atributo gerado a partir da coluna DRLF_TX_LOG.
     * @param textoLog Novo valor para o atributo textoLog.
     */
    public void setTextoLog(final String textoLog) {
        this.textoLog = textoLog;
    }

    /**
     * Obtem o valor do atributo codigoAutor.<BR>
     * Atributo gerado a partir da coluna DRLF_CD_AUTOR.
     * @return Valor do atributo codigoAutor.
     */
    public String getCodigoAutor() {
        return this.codigoAutor;
    }

    /**
     * Atualiza o valor do atributo codigoAutor.<BR>
     * Atributo gerado a partir da coluna DRLF_CD_AUTOR.
     * @param codigoAutor Novo valor para o atributo codigoAutor.
     */
    public void setCodigoAutor(final String codigoAutor) {
        this.codigoAutor = codigoAutor;
    }

    /**
     * Obtem o valor do atributo indicadorSucesso.<BR>
     * Atributo gerado a partir da coluna DRLF_IN_SUCESSO.
     * @return Valor do atributo indicadorSucesso.
     */
    public String getIndicadorSucesso() {
        return this.indicadorSucesso;
    }

    /**
     * Atualiza o valor do atributo indicadorSucesso.<BR>
     * Atributo gerado a partir da coluna DRLF_IN_SUCESSO.
     * @param indicadorSucesso Novo valor para o atributo indicadorSucesso.
     */
    public void setIndicadorSucesso(final String indicadorSucesso) {
        this.indicadorSucesso = indicadorSucesso;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoLogFechamento").append("='").append(
                getCodigoLogFechamento()).append("' ");
        buffer.append("dataMes").append("='").append(getDataMes()).append("' ");
        buffer.append("dataExecucao").append("='").append(getDataExecucao())
                .append("' ");
        buffer.append("textoLog").append("='").append(getTextoLog()).append(
                "' ");
        buffer.append("codigoAutor").append("='").append(getCodigoAutor())
                .append("' ");
        buffer.append("indicadorSucesso").append("='").append(
                getIndicadorSucesso()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}