/*
 * @(#) DreMes.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Entity gerado a partir da tabela DRE_MES.
 * 
 * @author Generated by Hibernate Tools 3.6.0
 * @since 10/10/2013 16:22:55
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "DRE_MES", uniqueConstraints = @UniqueConstraint(columnNames = "DREM_DT_MES"))
@NamedQueries({
		@NamedQuery(name = "DreMes.findAll", query = "SELECT t FROM DreMes t"),
		@NamedQuery(name = "DreMes.findByDataMes", query = "SELECT t FROM DreMes t "
				+ "WHERE TRUNC(t.dataMes) = TRUNC(:dataMes) ") })
public class DreMes implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "DreMes.findAll".
	 */
	public static final String FIND_ALL = "DreMes.findAll";

	/**
	 * Constante para NamedQuery "DreMes.findByDataMes".
	 */
	public static final String FIND_BY_DATA_MES = "DreMes.findByDataMes";

	/**
	 * Atributo gerado a partir da coluna DREM_CD_DRE_MES.
	 */
	@Id
	@GeneratedValue(generator = "DreMesSeq")
	@SequenceGenerator(name = "DreMesSeq", sequenceName = "SQ_DREM_CD_DRE_MES", allocationSize = 1)
	@Column(name = "DREM_CD_DRE_MES", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoDreMes;

	/**
	 * Atributo gerado a partir da coluna DREM_DT_MES.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "DREM_DT_MES", unique = true, nullable = false, length = 7)
	private Date dataMes;

	/**
	 * Atributo gerado a partir da coluna DREM_IN_STATUS.
	 */

	@Column(name = "DREM_IN_STATUS", nullable = false, length = 1)
	private String indicadorStatus;

	/**
	 * Atributo gerado a partir da coluna DREM_DT_INICIO.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "DREM_DT_INICIO", nullable = false, length = 7)
	private Date dataInicio;

	/**
	 * Atributo gerado a partir da coluna DREM_DT_FIM.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "DREM_DT_FIM", length = 7)
	private Date dataFim;

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "dreMes")
	private Set<DreProcesso> dreProcessos = new HashSet<DreProcesso>(0);

	/**
	 * Construtor default.
	 */
	public DreMes() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoDreMes
	 *            Valor do atributo codigoDreMes;
	 * @param dataMes
	 *            Valor do atributo dataMes;
	 * @param indicadorStatus
	 *            Valor do atributo indicadorStatus;
	 * @param dataInicio
	 *            Valor do atributo dataInicio;
	 */
	public DreMes(Long codigoDreMes, Date dataMes, String indicadorStatus,
			Date dataInicio) {
		this.codigoDreMes = codigoDreMes;
		this.dataMes = dataMes;
		this.indicadorStatus = indicadorStatus;
		this.dataInicio = dataInicio;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param dataMes
	 *            Valor do atributo dataMes;
	 * @param indicadorStatus
	 *            Valor do atributo indicadorStatus;
	 * @param dataInicio
	 *            Valor do atributo dataInicio;
	 */
	public DreMes(Date dataMes, String indicadorStatus, Date dataInicio) {
		this.dataMes = dataMes;
		this.indicadorStatus = indicadorStatus;
		this.dataInicio = dataInicio;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoDreMes
	 *            Valor do atributo codigoDreMes;
	 * @param dataMes
	 *            Valor do atributo dataMes;
	 * @param indicadorStatus
	 *            Valor do atributo indicadorStatus;
	 * @param dataInicio
	 *            Valor do atributo dataInicio;
	 */
	public DreMes(Long codigoDreMes, Date dataMes, String indicadorStatus,
			Date dataInicio, Date dataFim, Set<DreProcesso> dreProcessos) {
		this.codigoDreMes = codigoDreMes;
		this.dataMes = dataMes;
		this.indicadorStatus = indicadorStatus;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
		this.dreProcessos = dreProcessos;
	}

	/**
	 * Obtem o valor do atributo codigoDreMes.<BR>
	 * Atributo gerado a partir da coluna DREM_CD_DRE_MES.
	 * 
	 * @return Valor do atributo codigoDreMes.
	 */
	public Long getCodigoDreMes() {
		return this.codigoDreMes;
	}

	/**
	 * Atualiza o valor do atributo codigoDreMes.<BR>
	 * Atributo gerado a partir da coluna DREM_CD_DRE_MES.
	 * 
	 * @param codigoDreMes
	 *            Novo valor para o atributo codigoDreMes.
	 */
	public void setCodigoDreMes(Long codigoDreMes) {
		this.codigoDreMes = codigoDreMes;
	}

	/**
	 * Obtem o valor do atributo dataMes.<BR>
	 * Atributo gerado a partir da coluna DREM_DT_MES.
	 * 
	 * @return Valor do atributo dataMes.
	 */
	public Date getDataMes() {
		return this.dataMes;
	}

	/**
	 * Atualiza o valor do atributo dataMes.<BR>
	 * Atributo gerado a partir da coluna DREM_DT_MES.
	 * 
	 * @param dataMes
	 *            Novo valor para o atributo dataMes.
	 */
	public void setDataMes(Date dataMes) {
		this.dataMes = dataMes;
	}

	/**
	 * Obtem o valor do atributo indicadorStatus.<BR>
	 * Atributo gerado a partir da coluna DREM_IN_STATUS.
	 * 
	 * @return Valor do atributo indicadorStatus: <li>"C" - Complete</li> <li>
	 *         "I" - Imcomplete</li>
	 * 
	 */
	public String getIndicadorStatus() {
		return this.indicadorStatus;
	}

	/**
	 * Atualiza o valor do atributo indicadorStatus.<BR>
	 * Atributo gerado a partir da coluna DREM_IN_STATUS.
	 * 
	 * @param indicadorStatus
	 *            Novo valor para o atributo indicadorStatus: <li>"C" - Complete
	 *            </li> <li>
	 *            "I" - Imcomplete</li>
	 */
	public void setIndicadorStatus(String indicadorStatus) {
		this.indicadorStatus = indicadorStatus;
	}

	/**
	 * Obtem o valor do atributo dataInicio.<BR>
	 * Atributo gerado a partir da coluna DREM_DT_INICIO.
	 * 
	 * @return Valor do atributo dataInicio.
	 */
	public Date getDataInicio() {
		return this.dataInicio;
	}

	/**
	 * Atualiza o valor do atributo dataInicio.<BR>
	 * Atributo gerado a partir da coluna DREM_DT_INICIO.
	 * 
	 * @param dataInicio
	 *            Novo valor para o atributo dataInicio.
	 */
	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	/**
	 * Obtem o valor do atributo dataFim.<BR>
	 * Atributo gerado a partir da coluna DREM_DT_FIM.
	 * 
	 * @return Valor do atributo dataFim.
	 */
	public Date getDataFim() {
		return this.dataFim;
	}

	/**
	 * Atualiza o valor do atributo dataFim.<BR>
	 * Atributo gerado a partir da coluna DREM_DT_FIM.
	 * 
	 * @param dataFim
	 *            Novo valor para o atributo dataFim.
	 */
	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	/**
	 * Obtem o valor do atributo dreProcessos.<BR>
	 * 
	 * @return Valor do atributo dreProcessos.
	 */
	public Set<DreProcesso> getDreProcessos() {
		return this.dreProcessos;
	}

	/**
	 * Atualiza o valor do atributo dreProcessos.<BR>
	 * 
	 * @param dreProcessos
	 *            Novo valor para o atributo dreProcessos.
	 */
	public void setDreProcessos(Set<DreProcesso> dreProcessos) {
		this.dreProcessos = dreProcessos;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoDreMes").append("='").append(getCodigoDreMes())
				.append("' ");
		buffer.append("dataMes").append("='").append(getDataMes()).append("' ");
		buffer.append("indicadorStatus").append("='")
				.append(getIndicadorStatus()).append("' ");
		buffer.append("dataInicio").append("='").append(getDataInicio())
				.append("' ");
		buffer.append("dataFim").append("='").append(getDataFim()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
