/*
 * @(#) Empresa.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import org.hibernate.annotations.Type;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Entity gerado a partir da tabela EMPRESA.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 30/10/2009 10:42:58
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "EMPRESA")
@SqlResultSetMappings(@SqlResultSetMapping(name = "scalarEmpresa"))
@NamedNativeQueries({
        @NamedNativeQuery(name = "Empresa.findWithAssociatedPosition", query = "SELECT DISTINCT emp.empr_cd_empresa, emp.empr_nm_empresa, " +
                "emp.empr_cd_erp_codigo FROM pms20.empresa emp \n" +
                "INNER JOIN pms20.base_papel_alocacao bpa ON bpa.empr_cd_erp_codigo = emp.empr_cd_erp_codigo \n" +
                "LEFT JOIN pms20.custo_base_papel_alocacao cbpa ON bpa.bapa_cd_base_papel_alocacao = cbpa.bapa_cd_base_papel_alocacao \n" +
                "INNER JOIN pms20.papel_alocacao pa ON pa.paal_cd_papel_alocacao = bpa.paal_cd_papel_alocacao \n" +
                "AND emp.empr_in_ativo = 'A' ORDER BY emp.empr_cd_empresa ASC",resultSetMapping = "scalarEmpresa")})
@NamedQueries({
        @NamedQuery(name = "Empresa.findAll", query = "SELECT t FROM Empresa t "
                + "WHERE (t.indicadorAtivo = 'A') "
                + "ORDER BY t.nomeEmpresa ASC "),

        @NamedQuery(name = "Empresa.findAllSubsidiary", query = "SELECT empr FROM Empresa empr "
                + "WHERE (empr.empresa.codigoEmpresa is not null) "
                + "ORDER BY empr.nomeEmpresa ASC "),

        @NamedQuery(name = "Empresa.findAllActiveForCombobox", query = "SELECT new Empresa(t.codigoEmpresa, t.nomeEmpresa) FROM Empresa t "
                + "WHERE (t.empresa is null) "
                + "AND (t.indicadorAtivo = 'A') "
                + "ORDER BY t.nomeEmpresa ASC "),

        @NamedQuery(name = "Empresa.findAllParentCompany", query = "SELECT empr FROM Empresa empr "
                + "WHERE (empr.empresa.codigoEmpresa is null) "
                + "  AND (empr.indicadorAtivo = 'A') "
                + "ORDER BY empr.nomeEmpresa ASC "),

        @NamedQuery(name = "Empresa.findByFilter", query = "SELECT empr FROM Empresa empr "
                + " LEFT JOIN FETCH empr.empresa emprPai "
                + " WHERE (UPPER(empr.nomeEmpresa) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + " AND (UPPER(empr.indicadorAtivo) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + " AND (emprPai.codigoEmpresa = ? OR (? = 0L)) "
                + " AND (UPPER(empr.numeroCnpj) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + " AND (UPPER(empr.textoPais) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + " AND (UPPER(empr.textoEstado) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + " AND (UPPER(empr.textoCidade) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + " AND (UPPER(empr.codigoMnemonico) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + " ORDER BY empr.nomeEmpresa ASC "),

        @NamedQuery(name = "Empresa.findByAcronym", query = "SELECT empr FROM Empresa empr "
                + "WHERE (UPPER(empr.codigoMnemonico) = TRIM(UPPER(?))) "),
        @NamedQuery(name = "Empresa.findByERP", query = "SELECT empr FROM Empresa empr "
                + "WHERE (empr.codigoErpFilial = ?) "),
        @NamedQuery(name = "Empresa.findByName", query = "SELECT empr FROM Empresa empr WHERE (UPPER(empr.nomeEmpresa) = TRIM(UPPER(?))) "),
        @NamedQuery(name = "Empresa.findByIndicadorExibicaoMsaContrato", query = "SELECT empr from Empresa empr where empr.indicadorExibicaoMsaContrato = ? order by empr.textoCidade ASC"),
        @NamedQuery(name = "Empresa.findByIdIn", query = "SELECT t FROM Empresa t WHERE t.codigoEmpresa IN :empresaCodes"),
        @NamedQuery(name = "Empresa.findByCodigoTaxpayerCompany", query = "SELECT e FROM Empresa e"
                + " where e.codigoTaxpayerCompany = :codigoTaxpayerCompany"
                + " and (e.indicadorAtivo = 'A')")
})
public class Empresa implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /** Constante para NamedQuery "Empresa.findAllSubsidiary". */
    public static final String FIND_ALL_SUBSIDIARY = "Empresa.findAllSubsidiary";

    /** Constante para NamedQuery "Empresa.findAllParentCompany". */
    public static final String FIND_ALL_PARENT_COMPANY = "Empresa.findAllParentCompany";

    /** Constante para NamedQuery "Empresa.findByFilterEmpresaFilho". */
    public static final String FIND_BY_FILTER = "Empresa.findByFilter";

    /** Constante para NamedQuery "Empresa.findByAcronym". */
    public static final String FIND_BY_ACRONYM = "Empresa.findByAcronym";

    public static final String FIND_BY_ERP = "Empresa.findByERP";

    public static final String FIND_BY_NAME= "Empresa.findByName";

    public static final String FIND_ALL_ACTIVE_FOR_COMBOBOX = "Empresa.findAllActiveForCombobox";

    public static final String FIND_COMPANIES_WITH_ASSOCIATED_POSITION = "Empresa.findWithAssociatedPosition";

    public static final String FIND_BY_INDICADOR_MSA_CONTRATO = "Empresa.findByIndicadorExibicaoMsaContrato";

    public static final String FIND_BY_ID_IN = "Empresa.findByIdIn";

    public static final String FIND_BY_CODIGO_TAXPAYER_COMPANY = "Empresa.findByCodigoTaxpayerCompany";

    // ========================================================================
    // END
    // ========================================================================

    /** Valor do serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** Constante para NamedQuery "Empresa.findAll". */
    public static final String FIND_ALL = "Empresa.findAll";

    /** Atributo gerado a partir da coluna EMPR_CD_EMPRESA. */
    @Id
    @GeneratedValue(generator = "EmpresaSeq")
    @SequenceGenerator(name = "EmpresaSeq", sequenceName = "SQ_EMPR_CD_EMPRESA", allocationSize = 1)
    @Column(name = "EMPR_CD_EMPRESA", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoEmpresa;

    /** Atributo gerado a partir da coluna EMPR_CD_EMPRESA_MATRIZ. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EMPR_CD_EMPRESA_MATRIZ")
    private Empresa empresa;

    /** Atributo gerado a partir da coluna EMPR_NM_EMPRESA. */
    @Column(name = "EMPR_NM_EMPRESA", length = 100)
    private String nomeEmpresa;

    /** Atributo gerado a partir da coluna EMPR_CD_ERP_PROJ_PAD_CODIGO. */
    @Column(name = "EMPR_CD_ERP_PROJ_PAD_CODIGO", nullable=true)
    private Long codigoErpProjetoPadrao;

    @Column(name = "EMPR_CD_ERP_CODIGO", length = 18)
    private Long codigoEmpresaERP;

    /** Atributo gerado a partir da coluna EMPR_NR_CNPJ. */
    @Column(name = "EMPR_NR_CNPJ", length = 50)
    private String numeroCnpj;

    /** Atributo gerado a partir da coluna EMPR_IN_ATIVO. */
    @Column(name = "EMPR_IN_ATIVO", length = 1)
    private String indicadorAtivo;

    /** Lista de empresas. */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
    private Set<Empresa> empresas = new HashSet<Empresa>(0);

    /** Lista de uploadDespesas. */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
    private List<UploadDespesa> uploadDespesas = new ArrayList<UploadDespesa>(0);

    /** Atributo gerado a partir da coluna EMPR_CD_MNEMONICO. */
    @Column(name = "EMPR_CD_MNEMONICO", length = 10)
    private String codigoMnemonico;

    /** Atributo gerado a partir da coluna EMPR_TX_CIDADE. */
    @Column(name = "EMPR_TX_CIDADE", length = 100)
    private String textoCidade;

    /** Atributo gerado a partir da coluna EMPR_TX_ESTADO. */
    @Column(name = "EMPR_TX_ESTADO", length = 100)
    private String textoEstado;

    /** Atributo gerado a partir da coluna EMPR_TX_PAIS. */
    @Column(name = "EMPR_TX_PAIS", length = 100)
    private String textoPais;

    /** Atributo gerado a partir da coluna EMPR_CD_ERP_CUS_IDE. */
    @Column(name = "EMPR_CD_ERP_CUS_IDE", length = 5)
    private String codigoErpCusIde;

    /** Atributo gerado a partir da coluna EMPR_CD_ERP_CCUSTO. */
    @Column(name = "EMPR_CD_MEGA_CALC_AGN_CODIGO", precision = 22, scale = 0)
    private BigDecimal codigoErpCcusto;

    /** Atributo gerado a partir da coluna EMPR_CD_ERP_PROJ_IDE. */
    @Column(name = "EMPR_CD_MEGA_APL_CODIGO", length = 5)
    private String codigoErpProjIde;

    /** Atributo gerado a partir da coluna EMPR_CD_ERP_PROJETO. */
    @Column(name = "EMPR_CD_ERP_PROJETO", precision = 22, scale = 0)
    private BigDecimal codigoErpProjeto;

    /** Atributo gerado a partir da coluna EMPR_CD_ERP_FILIAL. */
    @Column(name = "EMPR_CD_ERP_FILIAL", precision = 22, scale = 0)
    private BigDecimal codigoErpFilial;

    /** Atributo gerado a partir da coluna EMPR_CD_ERP_TPD_PAD. */
    @Column(name = "EMPR_CD_ERP_TPD_PAD", precision = 22, scale = 0)
    private BigDecimal codigoErpTpdPad;

    /** Atributo gerado a partir da coluna EMPR_CD_ERP_TPD_CODIGO. */
    @Column(name = "EMPR_CD_ERP_TPD_CODIGO", precision = 22, scale = 0)
    private BigDecimal codigoErpTpdCodigo;

    /** Atributo gerado a partir da coluna EMPR_CD_ERP_ACAO_CODIGO. */
    @Column(name = "EMPR_CD_ERP_ACAO_CODIGO", precision = 22, scale = 0)
    private BigDecimal codigoErpAcaoCodigo;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MOED_CD_MOEDA")
    private Moeda moeda;

    /** Atributo gerado a partir da coluna EMPR_VL_TAXA_CSLRF. */
    @Column(name = "EMPR_VL_TAXA_CSLRF", precision = 22, scale = 0)
    private BigDecimal valorTaxaCslrf;

    @Column(name = "EMPR_IN_MSA_CONTRATO")
    @Type(type = "yes_no")
    private Boolean indicadorExibicaoMsaContrato;

    @Column(name = "EMPR_IN_PLANO_CONTABIL_MOEDA", length = 1)
    @Type(type="yes_no")
    private Boolean indicadorPlanoContabilPorMoeda;

    @Column(name = "EMPR_ORCL_TAX_PAYER_COMP", length = 30)
    private String codigoTaxpayerCompany;

	/** Construtor default. */
    public Empresa() {
    }

    /**
     * Construtor com preenchimento da entidade.
     *
     * @param codigoEmpresa
     *            Valor do atributo codigoEmpresa;
     */
    public Empresa(final Long codigoEmpresa) {
        this.codigoEmpresa = codigoEmpresa;
    }

    public Empresa(Long codigoEmpresa, String nomeEmpresa) {
        this.codigoEmpresa = codigoEmpresa;
        this.nomeEmpresa = nomeEmpresa;
    }

    /**
     * Obtem o valor do atributo {@link Empresa#codigoErpProjetoPadrao}.<BR>
     *
     * @return the codigoErpProjetoPadrao
     */
    public Long getCodigoErpProjetoPadrao() {
        return codigoErpProjetoPadrao;
    }

    /**
     * Atualiza o valor do atributo codigoErpProjetoPadrao.<BR>
     *
     * @param codigoErpProjetoPadrao Novo valor para o atributo {@link Empresa#codigoErpProjetoPadrao}.
     */
    public void setCodigoErpProjetoPadrao(Long codigoErpProjetoPadrao) {
        this.codigoErpProjetoPadrao = codigoErpProjetoPadrao;
    }

    /**
     * Obtem o valor do atributo codigoEmpresa.<BR>
     * Atributo gerado a partir da coluna EMPR_CD_EMPRESA.
     * 
     * @return Valor do atributo codigoEmpresa.
     */
    public Long getCodigoEmpresa() {
        return this.codigoEmpresa;
    }

    /**
     * Atualiza o valor do atributo codigoEmpresa.<BR>
     * Atributo gerado a partir da coluna EMPR_CD_EMPRESA.
     * 
     * @param codigoEmpresa
     *            Novo valor para o atributo codigoEmpresa.
     */
    public void setCodigoEmpresa(final Long codigoEmpresa) {
        this.codigoEmpresa = codigoEmpresa;
    }

    /**
     * Obtem o valor do atributo empresa.<BR>
     * Atributo gerado a partir da coluna EMPR_CD_EMPRESA_MATRIZ.
     * 
     * @return Valor do atributo empresa.
     */
    public Empresa getEmpresa() {
        return this.empresa;
    }

    /**
     * Atualiza o valor do atributo empresa.<BR>
     * Atributo gerado a partir da coluna EMPR_CD_EMPRESA_MATRIZ.
     * 
     * @param empresa
     *            Novo valor para o atributo empresa.
     */
    public void setEmpresa(final Empresa empresa) {
        this.empresa = empresa;
    }

    /**
     * Obtem o valor do atributo nomeEmpresa.<BR>
     * Atributo gerado a partir da coluna EMPR_NM_EMPRESA.
     * 
     * @return Valor do atributo nomeEmpresa.
     */
    public String getNomeEmpresa() {
        return this.nomeEmpresa;
    }

    /**
     * Atualiza o valor do atributo nomeEmpresa.<BR>
     * Atributo gerado a partir da coluna EMPR_NM_EMPRESA.
     * 
     * @param nomeEmpresa
     *            Novo valor para o atributo nomeEmpresa.
     */
    public void setNomeEmpresa(final String nomeEmpresa) {
        this.nomeEmpresa = nomeEmpresa;
    }

    /**
     * Obtem o valor do atributo numeroCnpj.<BR>
     * Atributo gerado a partir da coluna EMPR_NR_CNPJ.
     * 
     * @return Valor do atributo numeroCnpj.
     */
    public String getNumeroCnpj() {
        return this.numeroCnpj;
    }

    /**
     * Atualiza o valor do atributo numeroCnpj.<BR>
     * Atributo gerado a partir da coluna EMPR_NR_CNPJ.
     * 
     * @param numeroCnpj
     *            Novo valor para o atributo numeroCnpj.
     */
    public void setNumeroCnpj(final String numeroCnpj) {
        this.numeroCnpj = numeroCnpj;
    }

    /**
     * Obtem o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna EMPR_IN_ATIVO.
     * 
     * @return Valor do atributo indicadorAtivo.
     */
    public String getIndicadorAtivo() {
        return this.indicadorAtivo;
    }

    /**
     * Atualiza o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna EMPR_IN_ATIVO.
     * 
     * @param indicadorAtivo
     *            Novo valor para o atributo indicadorAtivo.
     */
    public void setIndicadorAtivo(final String indicadorAtivo) {
        this.indicadorAtivo = indicadorAtivo;
    }

    /**
     * Obtem o valor do atributo empresas.<BR>
     * 
     * @return Valor do atributo empresas.
     */
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }

    /**
     * Atualiza o valor do atributo empresas.<BR>
     * 
     * @param empresas
     *            Novo valor para o atributo empresas.
     */
    public void setEmpresas(final Set<Empresa> empresas) {
        this.empresas = empresas;
    }

    /**
     * Obtem o valor do atributo codigoMnemonico.<BR>
     * Atributo gerado a partir da coluna EMPR_CD_MNEMONICO.
     * 
     * @return Valor do atributo codigoMnemonico.
     */
    public String getCodigoMnemonico() {
        return this.codigoMnemonico;
    }

    /**
     * Atualiza o valor do atributo codigoMnemonico.<BR>
     * Atributo gerado a partir da coluna EMPR_CD_MNEMONICO.
     * 
     * @param codigoMnemonico
     *            Novo valor para o atributo codigoMnemonico.
     */
    public void setCodigoMnemonico(final String codigoMnemonico) {
        this.codigoMnemonico = codigoMnemonico;
    }

    /**
     * @return the textoCidade
     */
    public String getTextoCidade() {
        return textoCidade;
    }

    /**
     * @param textoCidade
     *            the textoCidade to set
     */
    public void setTextoCidade(final String textoCidade) {
        this.textoCidade = textoCidade;
    }

    /**
     * @return the textoEstado
     */
    public String getTextoEstado() {
        return textoEstado;
    }

    /**
     * @param textoEstado
     *            the textoEstado to set
     */
    public void setTextoEstado(final String textoEstado) {
        this.textoEstado = textoEstado;
    }

    /**
     * @return the textoPais
     */
    public String getTextoPais() {
        return textoPais;
    }

    /**
     * @param textoPais
     *            the textoPais to set
     */
    public void setTextoPais(final String textoPais) {
        this.textoPais = textoPais;
    }

    /**
     * @return the codigoErpCusIde
     */
    public String getCodigoErpCusIde() {
        return codigoErpCusIde;
    }

    /**
     * @param codigoErpCusIde
     *            the codigoErpCusIde to set
     */
    public void setCodigoErpCusIde(final String codigoErpCusIde) {
        this.codigoErpCusIde = codigoErpCusIde;
    }

    /**
     * @return the codigoErpCcusto
     */
    public BigDecimal getCodigoErpCcusto() {
        return codigoErpCcusto;
    }

    /**
     * @param codigoErpCcusto
     *            the codigoErpCcusto to set
     */
    public void setCodigoErpCcusto(final BigDecimal codigoErpCcusto) {
        this.codigoErpCcusto = codigoErpCcusto;
    }

    /**
     * @return the codigoErpProjIde
     */
    public String getCodigoErpProjIde() {
        return codigoErpProjIde;
    }

    /**
     * @param codigoErpProjIde
     *            the codigoErpProjIde to set
     */
    public void setCodigoErpProjIde(final String codigoErpProjIde) {
        this.codigoErpProjIde = codigoErpProjIde;
    }

    /**
     * @return the codigoErpProjeto
     */
    public BigDecimal getCodigoErpProjeto() {
        return codigoErpProjeto;
    }

    /**
     * @param codigoErpProjeto
     *            the codigoErpProjeto to set
     */
    public void setCodigoErpProjeto(final BigDecimal codigoErpProjeto) {
        this.codigoErpProjeto = codigoErpProjeto;
    }

    /**
     * @return the codigoErpFilial
     */
    public BigDecimal getCodigoErpFilial() {
        return codigoErpFilial;
    }

    /**
     * @param codigoErpFilial
     *            the codigoErpFilial to set
     */
    public void setCodigoErpFilial(final BigDecimal codigoErpFilial) {
        this.codigoErpFilial = codigoErpFilial;
    }

    /**
     * @return the codigoErpTpdPad
     */
    public BigDecimal getCodigoErpTpdPad() {
        return codigoErpTpdPad;
    }

    /**
     * @param codigoErpTpdPad
     *            the codigoErpTpdPad to set
     */
    public void setCodigoErpTpdPad(final BigDecimal codigoErpTpdPad) {
        this.codigoErpTpdPad = codigoErpTpdPad;
    }

    /**
     * @return the codigoErpTpdCodigo
     */
    public BigDecimal getCodigoErpTpdCodigo() {
        return codigoErpTpdCodigo;
    }

    /**
     * @param codigoErpTpdCodigo
     *            the codigoErpTpdCodigo to set
     */
    public void setCodigoErpTpdCodigo(final BigDecimal codigoErpTpdCodigo) {
        this.codigoErpTpdCodigo = codigoErpTpdCodigo;
    }

    /**
     * @return the codigoErpAcaoCodigo
     */
    public BigDecimal getCodigoErpAcaoCodigo() {
        return codigoErpAcaoCodigo;
    }

    /**
     * @param codigoErpAcaoCodigo
     *            the codigoErpAcaoCodigo to set
     */
    public void setCodigoErpAcaoCodigo(final BigDecimal codigoErpAcaoCodigo) {
        this.codigoErpAcaoCodigo = codigoErpAcaoCodigo;
    }

    /**
     * @return the uploadDespesas
     */
    public List<UploadDespesa> getUploadDespesas() {
        return uploadDespesas;
    }

    /**
     * @param uploadDespesas
     *            the uploadDespesas to set
     */
    public void setUploadDespesas(final List<UploadDespesa> uploadDespesas) {
        this.uploadDespesas = uploadDespesas;
    }

    /**
     * @param valorTaxaCslrf
     *            the valorTaxaCslrf to set
     */
    public void setValorTaxaCslrf(final BigDecimal valorTaxaCslrf) {
        this.valorTaxaCslrf = valorTaxaCslrf;
    }

    /**
     * @return the valorTaxaCslrf
     */
    public BigDecimal getValorTaxaCslrf() {
        return valorTaxaCslrf;
    }

    public Moeda getMoeda() {
        return moeda;
    }

    public void setMoeda(Moeda moeda) {
        this.moeda = moeda;
    }

    public void setCodigoEmpresaERP (final Long codigoEmpresaERP)
    {
        this.codigoEmpresaERP = codigoEmpresaERP;
    }

    public Long getCodigoEmpresaERP () {return codigoEmpresaERP;}

    public Boolean getIndicadorExibicaoMsaContrato() {
        return indicadorExibicaoMsaContrato;
    }

    public void setIndicadorExibicaoMsaContrato(Boolean indicadorExibicaoMsaContrato) {
        this.indicadorExibicaoMsaContrato = indicadorExibicaoMsaContrato;
    }

    public Boolean getIndicadorPlanoContabilPorMoeda() {
        return indicadorPlanoContabilPorMoeda;
    }

    public void setIndicadorPlanoContabilPorMoeda(Boolean indicadorPlanoContabilPorMoeda) {
        this.indicadorPlanoContabilPorMoeda = indicadorPlanoContabilPorMoeda;
    }

    public String getCodigoTaxpayerCompany() {
        return this.codigoTaxpayerCompany;
    }

    public void setCodigoTaxpayerCompany(final String codigoTaxpayerCompany) {
        this.codigoTaxpayerCompany = codigoTaxpayerCompany;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoEmpresa").append("='").append(getCodigoEmpresa())
                .append("' ");
        buffer.append("empresa").append("='").append(getEmpresa()).append("' ");
        buffer.append("nomeEmpresa").append("='").append(getNomeEmpresa())
                .append("' ");
        buffer.append("numeroCnpj").append("='").append(getNumeroCnpj())
                .append("' ");
        buffer.append("indicadorAtivo").append("='")
                .append(getIndicadorAtivo()).append("' ");
        buffer.append("codigoMnemonico").append("='").append(
                getCodigoMnemonico()).append("' ");
        buffer.append("textoCidade").append("='").append(getTextoCidade())
                .append("' ");
        buffer.append("textoEstado").append("='").append(getTextoEstado())
                .append("' ");
        buffer.append("textoPais").append("='").append(getTextoPais()).append(
                "' ");
        buffer.append("codigoErpCusIde").append("='").append(
                getCodigoErpCusIde()).append("' ");
        buffer.append("codigoErpCcusto").append("='").append(
                getCodigoErpCcusto()).append("' ");
        buffer.append("codigoErpProjIde").append("='").append(
                getCodigoErpProjIde()).append("' ");
        buffer.append("codigoErpProjeto").append("='").append(
                getCodigoErpProjeto()).append("' ");
        buffer.append("codigoErpFilial").append("='").append(
                getCodigoErpFilial()).append("' ");
        buffer.append("codigoErpTpdPad").append("='").append(
                getCodigoErpTpdPad()).append("' ");
        buffer.append("codigoErpTpdCodigo").append("='").append(
                getCodigoErpTpdCodigo()).append("' ");
        buffer.append("codigoErpAcaoCodigo").append("='").append(
                getCodigoErpAcaoCodigo()).append("' ");
        buffer.append("moeda").append("='").append(
                getMoeda()).append("' ");
        buffer.append("indicadorPlanoContabilPorMoeda").append("='").append(
                getIndicadorPlanoContabilPorMoeda()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }
    
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		Empresa empr = (Empresa) obj;
		if (this.codigoEmpresa != null
				&& this.codigoEmpresa.equals(empr.getCodigoEmpresa())) {
			return true;
		} else {
			return false;
		}
	}
}
