/*
 * @(#) EstratificacaoUr.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela ESTRATIFICACAO_UR.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 14/04/2011 15:56:16
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "ESTRATIFICACAO_UR")
@NamedQueries({
        @NamedQuery(name = "EstratificacaoUr.findAll", query = "SELECT t FROM EstratificacaoUr t"),
        @NamedQuery(name = "EstratificacaoUr.findByReceita", query = "SELECT estratificacaoUr FROM EstratificacaoUr estratificacaoUr "
                + "LEFT OUTER JOIN estratificacaoUr.receita receita "
                + "WHERE estratificacaoUr.receita.codigoReceita = ?"),
        @NamedQuery(name = "EstratificacaoUr.findByMapaAlocacaoData", query = "SELECT estratificacaoUr FROM EstratificacaoUr estratificacaoUr "
                + "LEFT OUTER JOIN estratificacaoUr.mapaAlocacao mapaAlocacao "
                + "WHERE estratificacaoUr.mapaAlocacao.codigoMapaAlocacao = ? "
                + "AND estratificacaoUr.dataMes = ? ")})
public class EstratificacaoUr implements java.io.Serializable, Cloneable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /**
     * Constante para NamedQuery "EstratificacaoUr.findByReceita".
     */
    public static final String FIND_BY_RECEITA =
            "EstratificacaoUr.findByReceita";

    /**
     * Constante para NamedQuery "EstratificacaoUr.findByMapaAlocacao".
     */
    public static final String FIND_BY_MAPA_ALOCACAO_DATA =
            "EstratificacaoUr.findByMapaAlocacaoData";

    /**
     * Lista de ItemEstratificacaoUr relacionado com a EstratificacaoUr
     * corrente.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estratificacaoUr", cascade = CascadeType.ALL)
    private List<ItemEstratificacaoUr> itemEstratificacaoUrs =
            new ArrayList<ItemEstratificacaoUr>(0);

    /**
     * Obtem o valor do atributo itemEstratificacaoUrs.<BR>
     * 
     * @return Valor do atributo itemEstratificacaoUrs.
     */
    public List<ItemEstratificacaoUr> getItemEstratificacaoUrs() {
        return this.itemEstratificacaoUrs;
    }

    /**
     * Atualiza o valor do atributo itemEstratificacaoUrs.<BR>
     * 
     * @param itemEstratificacaoUrs
     *            Novo valor para o atributo itemEstratificacaoUrs.
     */
    public void setItemEstratificacaoUrs(
            final List<ItemEstratificacaoUr> itemEstratificacaoUrs) {
        this.itemEstratificacaoUrs = itemEstratificacaoUrs;
    }

    /**
     * Realiza uma copia do objeto, porem com uma referencia diferente.
     * 
     * @return a cópia do FatorUrMes
     */
    public EstratificacaoUr getClone() {
        try {
            return (EstratificacaoUr) super.clone();
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
            return null;
        }
    }

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "EstratificacaoUr.findAll".
     */
    public static final String FIND_ALL = "EstratificacaoUr.findAll";

    /**
     * Atributo gerado a partir da coluna ESUR_CD_ESTRATIFICACAO_UR.
     */
    @Id
    @GeneratedValue(generator = "EstratificacaoUrSeq")
    @SequenceGenerator(name = "EstratificacaoUrSeq", sequenceName = "SQ_ESUR_CD_ESTRATIFICACAO_UR", allocationSize = 1)
    @Column(name = "ESUR_CD_ESTRATIFICACAO_UR", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoEstratificacaoUr;

    /**
     * Atributo gerado a partir da coluna MAAL_CD_MAPA_ALOCACAO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MAAL_CD_MAPA_ALOCACAO", nullable = false)
    private MapaAlocacao mapaAlocacao;

    /**
     * Atributo gerado a partir da coluna RECE_CD_RECEITA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RECE_CD_RECEITA")
    private Receita receita;

    /**
     * Atributo gerado a partir da coluna ESUR_DT_MES.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "ESUR_DT_MES", length = 7, nullable = false)
    private Date dataMes;

    /**
     * Atributo gerado a partir da coluna ESUR_NR_TOTAL_DESVIO.
     */

    @Column(name = "ESUR_NR_TOTAL_DESVIO", precision = 22, scale = 0)
    private BigDecimal numeroTotalDesvio;

    /**
     * Atributo gerado a partir da coluna ESUR_CD_LOGIN_CRIADOR.
     */

    @Column(name = "ESUR_CD_LOGIN_CRIADOR", length = 50)
    private String codigoLoginCriador;

    /**
     * Atributo gerado a partir da coluna ESUR_DT_ATUALIZACAO.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ESUR_DT_ATUALIZACAO", length = 7)
    private Date dataAtualizacao;

    /**
     * Atributo gerado a partir da coluna ESUR_DT_CRIACAO.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ESUR_DT_CRIACAO", length = 7)
    private Date dataCriacao;

    /**
     * Construtor default.
     */
    public EstratificacaoUr() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoEstratificacaoUr
     *            Valor do atributo codigoEstratificacaoUr;
     * @param mapaAlocacao
     *            Valor do atributo mapaAlocacao;
     */
    public EstratificacaoUr(final Long codigoEstratificacaoUr,
            final MapaAlocacao mapaAlocacao) {
        this.codigoEstratificacaoUr = codigoEstratificacaoUr;
        this.mapaAlocacao = mapaAlocacao;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoEstratificacaoUr
     *            Valor do atributo codigoEstratificacaoUr;
     * @param mapaAlocacao
     *            Valor do atributo mapaAlocacao;
     * @param receita
     *            Valor do atributo receita;
     * @param dataMes
     *            Valor do atributo dataMes;
     * @param numeroTotalDesvio
     *            Valor do atributo numeroTotalDesvio;
     * @param codigoLoginCriador
     *            Valor do atributo codigoLoginCriador;
     * @param dataAtualizacao
     *            Valor do atributo dataAtualizacao;
     * @param itemEstratificacaoUrs
     *            Valor do atributo itemEstratificacaoUrs;
     */
    public EstratificacaoUr(final Long codigoEstratificacaoUr,
            final MapaAlocacao mapaAlocacao, final Receita receita,
            final Date dataMes, final BigDecimal numeroTotalDesvio,
            final String codigoLoginCriador, final Date dataAtualizacao,
            final List<ItemEstratificacaoUr> itemEstratificacaoUrs) {
        this.codigoEstratificacaoUr = codigoEstratificacaoUr;
        this.mapaAlocacao = mapaAlocacao;
        this.receita = receita;
        this.dataMes = dataMes;
        this.numeroTotalDesvio = numeroTotalDesvio;
        this.codigoLoginCriador = codigoLoginCriador;
        this.dataAtualizacao = dataAtualizacao;
        this.itemEstratificacaoUrs = itemEstratificacaoUrs;
    }

    /**
     * Obtem o valor do atributo codigoEstratificacaoUr.<BR>
     * Atributo gerado a partir da coluna ESUR_CD_ESTRATIFICACAO_UR.
     * 
     * @return Valor do atributo codigoEstratificacaoUr.
     */
    public Long getCodigoEstratificacaoUr() {
        return this.codigoEstratificacaoUr;
    }

    /**
     * Atualiza o valor do atributo codigoEstratificacaoUr.<BR>
     * Atributo gerado a partir da coluna ESUR_CD_ESTRATIFICACAO_UR.
     * 
     * @param codigoEstratificacaoUr
     *            Novo valor para o atributo codigoEstratificacaoUr.
     */
    public void setCodigoEstratificacaoUr(final Long codigoEstratificacaoUr) {
        this.codigoEstratificacaoUr = codigoEstratificacaoUr;
    }

    /**
     * Obtem o valor do atributo mapaAlocacao.<BR>
     * Atributo gerado a partir da coluna MAAL_CD_MAPA_ALOCACAO.
     * 
     * @return Valor do atributo mapaAlocacao.
     */
    public MapaAlocacao getMapaAlocacao() {
        return this.mapaAlocacao;
    }

    /**
     * Atualiza o valor do atributo mapaAlocacao.<BR>
     * Atributo gerado a partir da coluna MAAL_CD_MAPA_ALOCACAO.
     * 
     * @param mapaAlocacao
     *            Novo valor para o atributo mapaAlocacao.
     */
    public void setMapaAlocacao(final MapaAlocacao mapaAlocacao) {
        this.mapaAlocacao = mapaAlocacao;
    }

    /**
     * Obtem o valor do atributo receita.<BR>
     * Atributo gerado a partir da coluna RECE_CD_RECEITA.
     * 
     * @return Valor do atributo receita.
     */
    public Receita getReceita() {
        return this.receita;
    }

    /**
     * Atualiza o valor do atributo receita.<BR>
     * Atributo gerado a partir da coluna RECE_CD_RECEITA.
     * 
     * @param receita
     *            Novo valor para o atributo receita.
     */
    public void setReceita(final Receita receita) {
        this.receita = receita;
    }

    /**
     * Obtem o valor do atributo dataMes.<BR>
     * Atributo gerado a partir da coluna ESUR_DT_MES.
     * 
     * @return Valor do atributo dataMes.
     */
    public Date getDataMes() {
        return this.dataMes;
    }

    /**
     * Atualiza o valor do atributo dataMes.<BR>
     * Atributo gerado a partir da coluna ESUR_DT_MES.
     * 
     * @param dataMes
     *            Novo valor para o atributo dataMes.
     */
    public void setDataMes(final Date dataMes) {
        this.dataMes = dataMes;
    }

    /**
     * Obtem o valor do atributo numeroTotalDesvio.<BR>
     * Atributo gerado a partir da coluna ESUR_NR_TOTAL_DESVIO.
     * 
     * @return Valor do atributo numeroTotalDesvio.
     */
    public BigDecimal getNumeroTotalDesvio() {
        return this.numeroTotalDesvio;
    }

    /**
     * Atualiza o valor do atributo numeroTotalDesvio.<BR>
     * Atributo gerado a partir da coluna ESUR_NR_TOTAL_DESVIO.
     * 
     * @param numeroTotalDesvio
     *            Novo valor para o atributo numeroTotalDesvio.
     */
    public void setNumeroTotalDesvio(final BigDecimal numeroTotalDesvio) {
        this.numeroTotalDesvio = numeroTotalDesvio;
    }

    /**
     * Obtem o valor do atributo codigoLoginCriador.<BR>
     * Atributo gerado a partir da coluna ESUR_CD_LOGIN_CRIADOR.
     * 
     * @return Valor do atributo codigoLoginCriador.
     */
    public String getCodigoLoginCriador() {
        return this.codigoLoginCriador;
    }

    /**
     * Atualiza o valor do atributo codigoLoginCriador.<BR>
     * Atributo gerado a partir da coluna ESUR_CD_LOGIN_CRIADOR.
     * 
     * @param codigoLoginCriador
     *            Novo valor para o atributo codigoLoginCriador.
     */
    public void setCodigoLoginCriador(final String codigoLoginCriador) {
        this.codigoLoginCriador = codigoLoginCriador;
    }

    /**
     * Obtem o valor do atributo dataAtualizacao.<BR>
     * Atributo gerado a partir da coluna ESUR_DT_ATUALIZACAO.
     * 
     * @return Valor do atributo dataAtualizacao.
     */
    public Date getDataAtualizacao() {
        return this.dataAtualizacao;
    }

    /**
     * Atualiza o valor do atributo dataAtualizacao.<BR>
     * Atributo gerado a partir da coluna ESUR_DT_ATUALIZACAO.
     * 
     * @param dataAtualizacao
     *            Novo valor para o atributo dataAtualizacao.
     */
    public void setDataAtualizacao(final Date dataAtualizacao) {
        this.dataAtualizacao = dataAtualizacao;
    }

    /**
     * @return the dataCriacao
     */
    public Date getDataCriacao() {
        return dataCriacao;
    }

    /**
     * @param dataCriacao
     *            the dataCriacao to set
     */
    public void setDataCriacao(final Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoEstratificacaoUr").append("='").append(
                getCodigoEstratificacaoUr()).append("' ");
        buffer.append("mapaAlocacao").append("='").append(getMapaAlocacao())
                .append("' ");
        buffer.append("receita").append("='").append(getReceita()).append("' ");
        buffer.append("dataMes").append("='").append(getDataMes()).append("' ");
        buffer.append("numeroTotalDesvio").append("='").append(
                getNumeroTotalDesvio()).append("' ");
        buffer.append("codigoLoginCriador").append("='").append(
                getCodigoLoginCriador()).append("' ");
        buffer.append("dataAtualizacao").append("='").append(
                getDataAtualizacao()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}