/*
 * @(#) ExplicacaoDesvio.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela EXPLICACAO_DESVIO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 14/04/2011 15:56:16
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "EXPLICACAO_DESVIO")
@NamedQueries({
        @NamedQuery(name = "ExplicacaoDesvio.findAll", query = "SELECT t FROM ExplicacaoDesvio t"),
        @NamedQuery(name = "ExplicacaoDesvio.findAtivos", query = "SELECT t FROM ExplicacaoDesvio t "
                + " WHERE (UPPER(t.indicadorAtivo) = 'S')"),
        @NamedQuery(name = "ExplicacaoDesvio.findSelecionado", query = "SELECT t FROM ExplicacaoDesvio t "
                + " WHERE (UPPER(t.indicadorSelecionado) = 'S')") })
public class ExplicacaoDesvio implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "ExplicacaoDesvio.findAll".
     */
    public static final String FIND_ALL = "ExplicacaoDesvio.findAll";

    /**
     * Constante para NamedQuery "ExplicacaoDesvio.findAtivos".
     */
    public static final String FIND_ATIVOS = "ExplicacaoDesvio.findAtivos";

    /**
     * Constante para NamedQuery "ExplicacaoDesvio.findSelecionado".
     */
    public static final String FIND_SELECIONADO = "ExplicacaoDesvio.findSelecionado";

    /**
     * Atributo gerado a partir da coluna EXDE_CD_MOTIVO_DESVIO.
     */
    @Id
    @GeneratedValue(generator = "ExplicacaoDesvioSeq")
    @SequenceGenerator(name = "ExplicacaoDesvioSeq", sequenceName = "SQ_EXDE_CD_MOTIVO_DESVIO", allocationSize = 1)
    @Column(name = "EXDE_CD_MOTIVO_DESVIO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoMotivoDesvio;

    /**
     * Atributo gerado a partir da coluna EXDE_NM_MOTIVO_DESVIO.
     */

    @Column(name = "EXDE_NM_MOTIVO_DESVIO", length = 100)
    private String nomeMotivoDesvio;

    /**
     * Atributo gerado a partir da coluna EXDE_IN_ATIVO.
     */

    @Column(name = "EXDE_IN_ATIVO", length = 1)
    private String indicadorAtivo;

    /**
     * Atributo gerado a partir da coluna EXDE_IN_SELECIONADO.
     */

    @Column(name = "EXDE_IN_SELECIONADO", length = 1)
    private String indicadorSelecionado;

    /**
     * Lista de ItemEstratificacaoUr relacionado com a ExplicacaoDesvio
     * corrente.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "explicacaoDesvio")
    private Set<ItemEstratificacaoUr> itemEstratificacaoUrs = new HashSet<ItemEstratificacaoUr>(
            0);

    /**
     * Construtor default.
     */
    public ExplicacaoDesvio() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoMotivoDesvio
     *            Valor do atributo codigoMotivoDesvio;
     */
    public ExplicacaoDesvio(final Long codigoMotivoDesvio) {
        this.codigoMotivoDesvio = codigoMotivoDesvio;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoMotivoDesvio
     *            Valor do atributo codigoMotivoDesvio;
     * @param nomeMotivoDesvio
     *            Valor do atributo nomeMotivoDesvio;
     * @param indicadorAtivo
     *            Valor do atributo indicadorAtivo;
     * @param itemEstratificacaoUrs
     *            Valor do atributo itemEstratificacaoUrs;
     */
    public ExplicacaoDesvio(final Long codigoMotivoDesvio,
            final String nomeMotivoDesvio, final String indicadorAtivo,
            final Set<ItemEstratificacaoUr> itemEstratificacaoUrs) {
        this.codigoMotivoDesvio = codigoMotivoDesvio;
        this.nomeMotivoDesvio = nomeMotivoDesvio;
        this.indicadorAtivo = indicadorAtivo;
        this.itemEstratificacaoUrs = itemEstratificacaoUrs;
    }

    /**
     * Obtem o valor do atributo codigoMotivoDesvio.<BR>
     * Atributo gerado a partir da coluna EXDE_CD_MOTIVO_DESVIO.
     * 
     * @return Valor do atributo codigoMotivoDesvio.
     */
    public Long getCodigoMotivoDesvio() {
        return this.codigoMotivoDesvio;
    }

    /**
     * Atualiza o valor do atributo codigoMotivoDesvio.<BR>
     * Atributo gerado a partir da coluna EXDE_CD_MOTIVO_DESVIO.
     * 
     * @param codigoMotivoDesvio
     *            Novo valor para o atributo codigoMotivoDesvio.
     */
    public void setCodigoMotivoDesvio(final Long codigoMotivoDesvio) {
        this.codigoMotivoDesvio = codigoMotivoDesvio;
    }

    /**
     * Obtem o valor do atributo nomeMotivoDesvio.<BR>
     * Atributo gerado a partir da coluna EXDE_NM_MOTIVO_DESVIO.
     * 
     * @return Valor do atributo nomeMotivoDesvio.
     */
    public String getNomeMotivoDesvio() {
        return this.nomeMotivoDesvio;
    }

    /**
     * Atualiza o valor do atributo nomeMotivoDesvio.<BR>
     * Atributo gerado a partir da coluna EXDE_NM_MOTIVO_DESVIO.
     * 
     * @param nomeMotivoDesvio
     *            Novo valor para o atributo nomeMotivoDesvio.
     */
    public void setNomeMotivoDesvio(final String nomeMotivoDesvio) {
        this.nomeMotivoDesvio = nomeMotivoDesvio;
    }

    /**
     * Obtem o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna EXDE_IN_ATIVO.
     * 
     * @return Valor do atributo indicadorAtivo.
     */
    public String getIndicadorAtivo() {
        return this.indicadorAtivo;
    }

    /**
     * Atualiza o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna EXDE_IN_ATIVO.
     * 
     * @param indicadorAtivo
     *            Novo valor para o atributo indicadorAtivo.
     */
    public void setIndicadorAtivo(final String indicadorAtivo) {
        this.indicadorAtivo = indicadorAtivo;
    }

    /**
     * Obtem o valor do atributo indicadorSelecionado.<BR>
     * Atributo gerado a partir da coluna EXDE_IN_SELECIONADO.
     * 
     * @return Valor do atributo indicadorSelecionado.
     */
    public String getIndicadorSelecionado() {
        return this.indicadorSelecionado;
    }

    /**
     * Atualiza o valor do atributo indicadorSelecionado.<BR>
     * Atributo gerado a partir da coluna EXDE_IN_SELECIONADO.
     * 
     * @param indicadorSelecionado
     *            Novo valor para o atributo indicadorSelecionado.
     */
    public void setIndicadorSelecionado(final String indicadorSelecionado) {
        this.indicadorSelecionado = indicadorSelecionado;
    }

    /**
     * Obtem o valor do atributo itemEstratificacaoUrs.<BR>
     * 
     * @return Valor do atributo itemEstratificacaoUrs.
     */
    public Set<ItemEstratificacaoUr> getItemEstratificacaoUrs() {
        return this.itemEstratificacaoUrs;
    }

    /**
     * Atualiza o valor do atributo itemEstratificacaoUrs.<BR>
     * 
     * @param itemEstratificacaoUrs
     *            Novo valor para o atributo itemEstratificacaoUrs.
     */
    public void setItemEstratificacaoUrs(
            final Set<ItemEstratificacaoUr> itemEstratificacaoUrs) {
        this.itemEstratificacaoUrs = itemEstratificacaoUrs;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoMotivoDesvio").append("='").append(
                getCodigoMotivoDesvio()).append("' ");
        buffer.append("nomeMotivoDesvio").append("='").append(
                getNomeMotivoDesvio()).append("' ");
        buffer.append("indicadorAtivo").append("='")
                .append(getIndicadorAtivo()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}