/*
 * @(#) FatorReajuste.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela FATOR_REAJUSTE.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 25/02/2010 11:01:28
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "FATOR_REAJUSTE")
@NamedQueries({
    @NamedQuery(name = "FatorReajuste.findAll", query = "SELECT t FROM FatorReajuste t"),
    
    @NamedQuery(name = "FatorReajuste.findByTipoContrato", 
            query = "SELECT fr FROM FatorReajuste fr"
                + " WHERE fr.tipoContrato.codigoTipoContrato = ? "
                + " AND TRUNC(fr.dataInicio, 'YYYY') >= TRUNC(sysdate,'YYYY') " 
                + " ORDER BY fr.dataInicio asc"),
                
    @NamedQuery(name = "FatorReajuste.findByStartDate", 
            query = " SELECT fr FROM FatorReajuste fr " 
                + " WHERE fr.dataInicio = ? AND fr.tipoContrato.codigoTipoContrato = ?"),
    
    @NamedQuery(name = "FatorReajuste.findByPeriod", 
            query = " SELECT fr FROM FatorReajuste fr " 
                + " WHERE  fr.tipoContrato.codigoTipoContrato = ? " 
                + " AND TRUNC(fr.dataInicio) between TRUNC(?) and TRUNC(?) "
                + " ORDER BY fr.dataInicio"),            
                
    @NamedQuery(name = "FatorReajuste.findPrevious", 
            query = "SELECT fr FROM FatorReajuste fr"
                + " WHERE fr.tipoContrato.codigoTipoContrato = ? "
                + " AND TRUNC(fr.dataInicio) = "
                + "     (SELECT MAX(TRUNC(frBefore.dataInicio)) " 
                + "         FROM FatorReajuste frBefore " 
                + "         WHERE frBefore.tipoContrato.codigoTipoContrato = ?" 
                + "         AND frBefore.dataInicio < ?)"),
                
    @NamedQuery(name = "FatorReajuste.findNext", 
            query = "SELECT fr FROM FatorReajuste fr"
                + " WHERE fr.tipoContrato.codigoTipoContrato = ?" 
                + " AND TRUNC(fr.dataInicio) = "
                + "     (SELECT MIN(TRUNC(frNext.dataInicio)) " 
                + "      FROM FatorReajuste frNext "
                + "      WHERE frNext.tipoContrato.codigoTipoContrato = ?"
                + "      AND frNext.dataInicio > ?)")
})
public class FatorReajuste implements java.io.Serializable {

    /** Valor do serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** Constante para NamedQuery "FatorReajuste.findAll". */
    public static final String FIND_ALL = "FatorReajuste.findAll";

    /** Constante para NamedQuery "FatorReajuste.findByTipoContrato". */
    public static final String FIND_BY_TIPO_CONTRATO = "FatorReajuste.findByTipoContrato";
    
    /** Constante para NamedQuery "FatorReajuste.findNext". */
    public static final String FIND_NEXT = "FatorReajuste.findNext";
    
    /** Constante para NamedQuery "FatorReajuste.findPrevious". */
    public static final String FIND_PREVIOUS = "FatorReajuste.findPrevious";
    
    /** Constante para NamedQuery "FatorReajuste.findByStartDate". */
    public static final String FIND_BY_START_DATE = "FatorReajuste.findByStartDate";
    
    /** Constante para NamedQuery "FatorReajuste.findByPeriod". */
    public static final String FIND_BY_PERIOD = "FatorReajuste.findByPeriod";
    
    /**
     * Atributo gerado a partir da coluna FATR_CD_FATOR_REAJUSTE.
     */
    @Id
    @GeneratedValue(generator = "FatorReajusteSeq")
    @SequenceGenerator(name = "FatorReajusteSeq", sequenceName = "SQ_FATR_CD_FATOR_REAJUSTE", allocationSize = 1)
    @Column(name = "FATR_CD_FATOR_REAJUSTE", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoFatorReajuste;

    /**
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TICO_CD_TIPO_CONTRATO", nullable = false)
    private TipoContrato tipoContrato;

    /**
     * Atributo gerado a partir da coluna FATR_DT_INICIO.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "FATR_DT_INICIO", length = 7)
    private Date dataInicio;

    /**
     * Atributo gerado a partir da coluna FATR_DT_FIM.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "FATR_DT_FIM", length = 7)
    private Date dataFim;

    /**
     * Atributo gerado a partir da coluna FATR_PR_FATOR.
     */

    @Column(name = "FATR_PR_FATOR", precision = 22, scale = 0)
    private BigDecimal percentualFator;

    /**
     * Construtor default.
     */
    public FatorReajuste() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoFatorReajuste Valor do atributo codigoFatorReajuste;
     * @param tipoContrato Valor do atributo tipoContrato;
     */
    public FatorReajuste(final Long codigoFatorReajuste,
            final TipoContrato tipoContrato) {
        this.codigoFatorReajuste = codigoFatorReajuste;
        this.tipoContrato = tipoContrato;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoFatorReajuste Valor do atributo codigoFatorReajuste;
     * @param tipoContrato Valor do atributo tipoContrato;
     * @param percentualFator Valor do atributo percentualFator;
     */
    public FatorReajuste(final Long codigoFatorReajuste, 
            final TipoContrato tipoContrato, final BigDecimal percentualFator) {
        this.codigoFatorReajuste = codigoFatorReajuste;
        this.tipoContrato = tipoContrato;
        this.percentualFator = percentualFator;
    }

    /**
     * Obtem o valor do atributo codigoFatorReajuste.<BR>
     * Atributo gerado a partir da coluna FATR_CD_FATOR_REAJUSTE.
     * @return Valor do atributo codigoFatorReajuste.
     */
    public Long getCodigoFatorReajuste() {
        return this.codigoFatorReajuste;
    }

    /**
     * Atualiza o valor do atributo codigoFatorReajuste.<BR>
     * Atributo gerado a partir da coluna FATR_CD_FATOR_REAJUSTE.
     * @param codigoFatorReajuste Novo valor para o atributo codigoFatorReajuste.
     */
    public void setCodigoFatorReajuste(final Long codigoFatorReajuste) {
        this.codigoFatorReajuste = codigoFatorReajuste;
    }

    /**
     * Obtem o valor do atributo tipoContrato.<BR>
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     * @return Valor do atributo tipoContrato.
     */
    public TipoContrato getTipoContrato() {
        return this.tipoContrato;
    }

    /**
     * Atualiza o valor do atributo tipoContrato.<BR>
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     * @param tipoContrato Novo valor para o atributo tipoContrato.
     */
    public void setTipoContrato(final TipoContrato tipoContrato) {
        this.tipoContrato = tipoContrato;
    }

    /**
     * Obtem o valor do atributo percentualFator.<BR>
     * Atributo gerado a partir da coluna FATR_PR_FATOR.
     * @return Valor do atributo percentualFator.
     */
    public BigDecimal getPercentualFator() {
        return this.percentualFator;
    }

    /**
     * Atualiza o valor do atributo percentualFator.<BR>
     * Atributo gerado a partir da coluna FATR_PR_FATOR.
     * @param percentualFator Novo valor para o atributo percentualFator.
     */
    public void setPercentualFator(final BigDecimal percentualFator) {
        this.percentualFator = percentualFator;
    }
    
    /**
     * Obtem o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna FATR_DT_INICIO.
     * @return Valor do atributo dataInicio.
     */
    public Date getDataInicio() {
        return this.dataInicio;
    }

    /**
     * Atualiza o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna FATR_DT_INICIO.
     * @param dataInicio Novo valor para o atributo dataInicio.
     */
    public void setDataInicio(final Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    /**
     * Obtem o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna FATR_DT_FIM.
     * @return Valor do atributo dataFim.
     */
    public Date getDataFim() {
        return this.dataFim;
    }

    /**
     * Atualiza o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna FATR_DT_FIM.
     * @param dataFim Novo valor para o atributo dataFim.
     */
    public void setDataFim(final Date dataFim) {
        this.dataFim = dataFim;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoFatorReajuste").append("='").append(
                getCodigoFatorReajuste()).append("' ");
        buffer.append("tipoContrato").append("='").append(getTipoContrato())
                .append("' ");
        buffer.append("percentualFator").append("='").append(
                getPercentualFator()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
