/*
 * @(#) FaturaReceita.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela FATURA_RECEITA.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 19/01/2010 09:15:55
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "FATURA_RECEITA")
@NamedQueries({ 
    @NamedQuery(name = "FaturaReceita.findAll", query = "SELECT t FROM FaturaReceita t"),
    
    @NamedQuery(name = "FaturaReceita.findByReceitaDealFiscal", 
            query = "SELECT fr FROM FaturaReceita fr"
                + " WHERE fr.receitaDealFiscal.codigoReceitaDfiscal = ? "),
    
    @NamedQuery(name = "FaturaReceita.getTotalByFatura", 
            query = "SELECT SUM(fr.valorReceitaAssociada) FROM FaturaReceita fr"
                + " WHERE fr.fatura.codigoFatura = ? "),
                
    @NamedQuery(name = "FaturaReceita.getSaldoByFatura", 
            query = "SELECT COALESCE(SUM(fr.valorReceitaAssociada), 0D) - SUM(item.valorItem) "
                + " FROM FaturaReceita fr "
                + " JOIN fr.fatura.itemFaturas item "
                + " WHERE fr.fatura.codigoFatura = ? "),            
                
    @NamedQuery(name = "FaturaReceita.getTotalFaturaByReceitaDeal", 
            query = "SELECT SUM(fr.valorReceitaAssociada) FROM FaturaReceita fr"
                + " WHERE fr.receitaDealFiscal.codigoReceitaDfiscal = ? "),
                
	@NamedQuery(name = "FaturaReceita.getTotalFaturaByDealFiscal", query = "SELECT fr FROM FaturaReceita fr "
			+ "JOIN FETCH fr.fatura f "
			+ "JOIN FETCH f.itemFaturas if "
			+ "JOIN FETCH if.fonteReceita r "
			+ "JOIN FETCH fr.receitaDealFiscal rdf "
			+ "JOIN FETCH rdf.dealFiscal df "
			+ "WHERE df.codigoDealFiscal = :codigoDealFiscal "
			+ "AND TRUNC(rdf.receitaMoeda.receita.dataMes) <= :dataFim "
			+ "AND f.indicadorStatus = 'SB' "
			+ "AND r.indicadorTipo = 'SV'")
    
})
public class FaturaReceita implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** Constante para NamedQuery "FaturaReceita.findAll". */
    public static final String FIND_ALL = "FaturaReceita.findAll";

    /** Constante para NamedQuery "FaturaReceita.getTotalFaturaByReceitaDeal". */
    public static final String GET_TOTAL_FATURA_BY_RECEITA_DEAL = 
        "FaturaReceita.getTotalFaturaByReceitaDeal";
    
    /** Constante para NamedQuery "FaturaReceita.getTotalByFatura". */
    public static final String GET_TOTAL_BY_FATURA = 
        "FaturaReceita.getTotalByFatura";
    
    /** Constante para NamedQuery "FaturaReceita.findByReceitaDealFiscal". */
    public static final String FIND_BY_RECEITA_DEAL_FISCAL = 
        "FaturaReceita.findByReceitaDealFiscal";
    
    /** Constante para NamedQuery "FaturaReceita.getSaldoByFatura". */
    public static final String GET_SALDO_BY_FATURA = 
        "FaturaReceita.findByReceitaDealFiscal";
    
    /** Constante para NamedQuery "FaturaReceita.getTotalFaturaByDealFiscal". */
    public static final String GET_TOTAL_FATURA_BY_DEAL_FISCAL = 
        "FaturaReceita.getTotalFaturaByDealFiscal";
    
    /**
     * Atributo gerado a partir da coluna FARE_CD_FATURA_RECEITA.
     */
    @Id
    @GeneratedValue(generator = "FaturaReceitaSeq")
    @SequenceGenerator(name = "FaturaReceitaSeq", sequenceName = "SQ_FARE_CD_FATURA_RECEITA", allocationSize = 1)
    @Column(name = "FARE_CD_FATURA_RECEITA", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoFaturaReceita;

    /**
     * Atributo gerado a partir da coluna FATU_CD_FATURA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FATU_CD_FATURA", nullable = false)
    private Fatura fatura;

    /**
     * Atributo gerado a partir da coluna REDF_CD_RECEITA_DFISCAL.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REDF_CD_RECEITA_DFISCAL", nullable = false)
    private ReceitaDealFiscal receitaDealFiscal;

    /**
     * Atributo gerado a partir da coluna FARE_VL_RECEITA_ASSOCIADA.
     */

    @Column(name = "FARE_VL_RECEITA_ASSOCIADA", precision = 22, scale = 0)
    private BigDecimal valorReceitaAssociada;

    /**
     * Construtor default.
     */
    public FaturaReceita() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoFaturaReceita Valor do atributo codigoFaturaReceita;
     * @param fatura Valor do atributo fatura;
     * @param receitaDealFiscal Valor do atributo receitaDealFiscal;
     */
    public FaturaReceita(final Long codigoFaturaReceita, final Fatura fatura,
            final ReceitaDealFiscal receitaDealFiscal) {
        this.codigoFaturaReceita = codigoFaturaReceita;
        this.fatura = fatura;
        this.receitaDealFiscal = receitaDealFiscal;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoFaturaReceita Valor do atributo codigoFaturaReceita;
     * @param fatura Valor do atributo fatura;
     * @param receitaDealFiscal Valor do atributo receitaDealFiscal;
     * @param valorReceitaAssociada Valor do atributo valorReceitaAssociada;
     */
    public FaturaReceita(final Long codigoFaturaReceita, final Fatura fatura,
            final ReceitaDealFiscal receitaDealFiscal,
            final BigDecimal valorReceitaAssociada) {
        this.codigoFaturaReceita = codigoFaturaReceita;
        this.fatura = fatura;
        this.receitaDealFiscal = receitaDealFiscal;
        this.valorReceitaAssociada = valorReceitaAssociada;
    }

    /**
     * Obtem o valor do atributo codigoFaturaReceita.<BR>
     * Atributo gerado a partir da coluna FARE_CD_FATURA_RECEITA.
     * @return Valor do atributo codigoFaturaReceita.
     */
    public Long getCodigoFaturaReceita() {
        return this.codigoFaturaReceita;
    }

    /**
     * Atualiza o valor do atributo codigoFaturaReceita.<BR>
     * Atributo gerado a partir da coluna FARE_CD_FATURA_RECEITA.
     * @param codigoFaturaReceita Novo valor para o atributo codigoFaturaReceita.
     */
    public void setCodigoFaturaReceita(final Long codigoFaturaReceita) {
        this.codigoFaturaReceita = codigoFaturaReceita;
    }

    /**
     * Obtem o valor do atributo fatura.<BR>
     * Atributo gerado a partir da coluna FATU_CD_FATURA.
     * @return Valor do atributo fatura.
     */
    public Fatura getFatura() {
        return this.fatura;
    }

    /**
     * Atualiza o valor do atributo fatura.<BR>
     * Atributo gerado a partir da coluna FATU_CD_FATURA.
     * @param fatura Novo valor para o atributo fatura.
     */
    public void setFatura(final Fatura fatura) {
        this.fatura = fatura;
    }

    /**
     * Obtem o valor do atributo receitaDealFiscal.<BR>
     * Atributo gerado a partir da coluna REDF_CD_RECEITA_DFISCAL.
     * @return Valor do atributo receitaDealFiscal.
     */
    public ReceitaDealFiscal getReceitaDealFiscal() {
        return this.receitaDealFiscal;
    }

    /**
     * Atualiza o valor do atributo receitaDealFiscal.<BR>
     * Atributo gerado a partir da coluna REDF_CD_RECEITA_DFISCAL.
     * @param receitaDealFiscal Novo valor para o atributo receitaDealFiscal.
     */
    public void setReceitaDealFiscal(final ReceitaDealFiscal receitaDealFiscal) {
        this.receitaDealFiscal = receitaDealFiscal;
    }

    /**
     * Obtem o valor do atributo valorReceitaAssociada.<BR>
     * Atributo gerado a partir da coluna FARE_VL_RECEITA_ASSOCIADA.
     * @return Valor do atributo valorReceitaAssociada.
     */
    public BigDecimal getValorReceitaAssociada() {
        return this.valorReceitaAssociada;
    }

    /**
     * Atualiza o valor do atributo valorReceitaAssociada.<BR>
     * Atributo gerado a partir da coluna FARE_VL_RECEITA_ASSOCIADA.
     * @param valorReceitaAssociada Novo valor para o atributo valorReceitaAssociada.
     */
    public void setValorReceitaAssociada(final BigDecimal valorReceitaAssociada) {
        this.valorReceitaAssociada = valorReceitaAssociada;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoFaturaReceita").append("='").append(
                getCodigoFaturaReceita()).append("' ");
        buffer.append("fatura").append("='").append(getFatura()).append("' ");
        buffer.append("receitaDealFiscal").append("='").append(
                getReceitaDealFiscal()).append("' ");
        buffer.append("valorReceitaAssociada").append("='").append(
                getValorReceitaAssociada()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}