/*
 * @(#) Fatura.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Entity gerado a partir da tabela FATURA_APAGADA.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 30/10/2014 10:42:58
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "FATURA_APAGADA")
@NamedQueries({
		@NamedQuery(name = FaturaApagada.FIND_ALL, query = "SELECT f FROM FaturaApagada f "),
		@NamedQuery(name = FaturaApagada.FIND_BY_ID, query = "SELECT f FROM FaturaApagada f WHERE f.codigoFaturaApagada = :faturaApagadaId"),
		@NamedQuery(name = FaturaApagada.FIND_BY_FILTER, query = "SELECT fatu FROM FaturaApagada fatu "
				+ "JOIN FETCH fatu.dealFiscal defi "
				+ "JOIN FETCH defi.msa msa "
				+ "WHERE TRUNC(fatu.dataPrevisao) >= TRUNC(:dataPrevisaoBeg) "
				+ "AND TRUNC(fatu.dataPrevisao) <= TRUNC(:dataPrevisaoEnd) "
				+ "AND ( (msa.cliente.codigoCliente = :codigoCliente) OR (:codigoCliente = 0L) ) "
				+ "AND ( (defi.codigoDealFiscal = :codigoDealFiscal) OR (:codigoDealFiscal = 0L) ) "
				+ "AND ( (fatu.moeda.codigoMoeda = :codigoMoeda) OR (:codigoMoeda = 0L) ) "
				+ "AND ( (fatu.numeroDoc = :numeroDoc) OR (:numeroDoc is null) ) "
				+ "AND ( UPPER(fatu.indicadorStatus) like '%'||TRIM(UPPER(:indicadorStatus))||'%' OR (:indicadorStatus is null) ) "
				+ "AND ( (msa.codigoMsa = :codigoMsa) OR (:codigoMsa = 0L) ) "
				+ "AND ( UPPER(fatu.codigoLoginAe) like '%'||TRIM(UPPER(:codigoLoginAe))||'%' or (:codigoLoginAe is null))"
				+ "ORDER BY defi.cliente.nomeCliente ASC, "
				+ "defi.nomeDealFiscal ASC, fatu.dataPrevisao ASC ")
})
public class FaturaApagada implements java.io.Serializable, Cloneable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "Fatura.findAll".
	 */
	public static final String FIND_ALL = "FaturaApagada.findAll";
	
	/**
	 * Constante para NamedQuery "Fatura.findAll".
	 */
	public static final String FIND_BY_ID = "FaturaApagada.findById";
	
	/**
	 * Constante para NamedQuery "Fatura.findByFilter".
	 */
	public static final String FIND_BY_FILTER = "FaturaApagada.findByFilter";


	/**
	 * Atributo gerado a partir da coluna FATU_CD_FATURA.
	 */
	@Id
	@Column(name = "FAAP_CD_FATURA_APAGADA", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoFaturaApagada;

	/**
	 * Atributo gerado a partir da coluna FATU_DT_PREVISAO.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "FAAP_DT_PREVISAO", length = 7)
	private Date dataPrevisao;

	/**
	 * Atributo gerado a partir da coluna FATU_NR_DOC.
	 */
	@Column(name = "FAAP_NR_DOC", length = 50)
	private String numeroDoc;

	/**
	 * Atributo gerado a partir da coluna FATU_TX_OBSERVACAO.
	 */
	@Column(name = "FAAP_TX_OBSERVACAO", length = 1000)
	private String textoObservacao;

	/**
	 * Atributo gerado a partir da coluna FATU_IN_STATUS.
	 */
	@Column(name = "FAAP_IN_STATUS", length = 2)
	private String indicadorStatus;
	
	/**
	 * Atributo gerado a partir da coluna MOED_CD_MOEDA.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOED_CD_MOEDA", nullable = false)
	private Moeda moeda;

	/**
	 * Atributo gerado a partir da coluna DEFI_CD_DEAL_FISCAL.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEFI_CD_DEAL_FISCAL")
	private DealFiscal dealFiscal;

	/**
	 * Atributo gerado a partir da coluna FATU_CD_LOGIN_AE.
	 */
	@Column(name = "FAAP_CD_LOGIN_AE", length = 50)
	private String codigoLoginAe;

	/**
	 * Atributo gerado a partir da coluna FATU_CD_ERP_PEDIDO.
	 */
	@Column(name = "FAAP_CD_ERP_PEDIDO", precision = 18, scale = 0)
	private Long codigoErpPedido;

	/**
	 * Atributo gerado a partir da coluna FATU_TX_ERROR.
	 */
	@Column(name = "FAAP_TX_ERROR", length = 250)
	private String textoError;

	/**
	 * Atributo gerado a partir da coluna FATU_DT_CANCELAMENTO.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "FAAP_DT_CANCELAMENTO", length = 7)
	private Date dataCancelamento;

	/**
	 * Atributo gerado a partir da coluna FATU_TX_RAZAO_CANCELAMENTO.
	 */

	@Column(name = "FAAP_TX_RAZAO_CANCELAMENTO", length = 500)
	private String textoRazaoCancelamento;
	
	/** Atributo gerado a partir da coluna FATU_CD_COTACAO_MOEDA. */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMO_CD_COTACAO_MOEDA")
	private CotacaoMoeda cotacaoMoeda;

	/**
	 * Atributo gerado a partir da coluna FATU_DT_VENCIMENTO.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "FAAP_DT_VENCIMENTO", length = 7)
	private Date dataVencimento;

	/**
	 * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO_SSO.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CELU_CD_CENTRO_LUCRO_SSO")
	private CentroLucro centroLucroSso;

	/**
	 * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO_UMKT.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CELU_CD_CENTRO_LUCRO_UMKT")
	private CentroLucro centroLucroUmkt;

	/**
	 * Lista de itens da fatura.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faturaApagada", cascade = CascadeType.ALL)
	private List<ItemFaturaApagado> itemFaturaApagados = new ArrayList<ItemFaturaApagado>(0);

	/**
	 * Lista de HistoricoFatura.
	 */
	@Transient
	private List<HistoricoFatura> historicoFaturas = new ArrayList<HistoricoFatura>(
			0);

	/**
	 * Construtor default.
	 */
	public FaturaApagada() {
	}

	public FaturaApagada(Fatura fatura) {

		this.codigoFaturaApagada = fatura.getCodigoFatura();
		this.dataPrevisao = fatura.getDataPrevisao();
		this.numeroDoc = fatura.getNumeroDoc();
		this.textoObservacao = fatura.getTextoObservacao();
		this.indicadorStatus = fatura.getIndicadorStatus();
		this.moeda = fatura.getMoeda();
		this.dealFiscal = fatura.getDealFiscal();
		this.codigoLoginAe = fatura.getCodigoLoginAe();
		this.codigoErpPedido = fatura.getCodigoErpPedido();
		this.textoError = fatura.getTextoError();
		this.dataCancelamento = fatura.getDataCancelamento();
		this.textoRazaoCancelamento = fatura.getTextoRazaoCancelamento();
		this.cotacaoMoeda = fatura.getCotacaoMoeda();
		this.dataVencimento = fatura.getDataVencimento();
		this.centroLucroSso = fatura.getCentroLucroSso();
		this.centroLucroUmkt = fatura.getCentroLucroUmkt();
	}

	/**
	 * @return the codigoFatura
	 */
	public Long getCodigoFatura() {
		return codigoFaturaApagada;
	}

	/**
	 * @param codigoFatura
	 *            the codigoFatura to set
	 */
	public void setCodigoFatura(final Long codigoFatura) {
		this.codigoFaturaApagada = codigoFatura;
	}

	/**
	 * @return the moeda
	 */
	public Moeda getMoeda() {
		return moeda;
	}

	/**
	 * @param moeda
	 *            the moeda to set
	 */
	public void setMoeda(final Moeda moeda) {
		this.moeda = moeda;
	}

	/**
	 * @return the dealFiscal
	 */
	public DealFiscal getDealFiscal() {
		return dealFiscal;
	}

	/**
	 * @param dealFiscal
	 *            the dealFiscal to set
	 */
	public void setDealFiscal(final DealFiscal dealFiscal) {
		this.dealFiscal = dealFiscal;
	}

	/**
	 * @return the dataPrevisao
	 */
	public Date getDataPrevisao() {
		return dataPrevisao;
	}

	/**
	 * @param dataPrevisao
	 *            the dataPrevisao to set
	 */
	public void setDataPrevisao(final Date dataPrevisao) {
		this.dataPrevisao = dataPrevisao;
	}

	/**
	 * @return the numeroDoc
	 */
	public String getNumeroDoc() {
		return numeroDoc;
	}

	/**
	 * @param numeroDoc
	 *            the numeroDoc to set
	 */
	public void setNumeroDoc(final String numeroDoc) {
		this.numeroDoc = numeroDoc;
	}

	/**
	 * @return the textoObservacao
	 */
	public String getTextoObservacao() {
		return textoObservacao;
	}

	/**
	 * @param textoObservacao
	 *            the textoObservacao to set
	 */
	public void setTextoObservacao(final String textoObservacao) {
		this.textoObservacao = textoObservacao;
	}

	/**
	 * @return the indicadorStatus
	 */
	public String getIndicadorStatus() {
		return indicadorStatus;
	}

	/**
	 * @param indicadorStatus
	 *            the indicadorStatus to set
	 */
	public void setIndicadorStatus(final String indicadorStatus) {
		this.indicadorStatus = indicadorStatus;
	}

	/**
	 * @return the codigoLoginAe
	 */
	public String getCodigoLoginAe() {
		return codigoLoginAe;
	}

	/**
	 * @param codigoLoginAe
	 *            the codigoLoginAe to set
	 */
	public void setCodigoLoginAe(final String codigoLoginAe) {
		this.codigoLoginAe = codigoLoginAe;
	}

	/**
	 * @return the codigoErpPedido
	 */
	public Long getCodigoErpPedido() {
		return codigoErpPedido;
	}

	/**
	 * @param codigoErpPedido
	 *            the codigoErpPedido to set
	 */
	public void setCodigoErpPedido(final Long codigoErpPedido) {
		this.codigoErpPedido = codigoErpPedido;
	}

	/**
	 * @return the textoError
	 */
	public String getTextoError() {
		return textoError;
	}

	/**
	 * @param textoError
	 *            the textoError to set
	 */
	public void setTextoError(final String textoError) {
		this.textoError = textoError;
	}

	/**
	 * @return the dataCancelamento
	 */
	public Date getDataCancelamento() {
		return dataCancelamento;
	}

	/**
	 * @param dataCancelamento
	 *            the dataCancelamento to set
	 */
	public void setDataCancelamento(final Date dataCancelamento) {
		this.dataCancelamento = dataCancelamento;
	}

	/**
	 * @return the textoRazaoCancelamento
	 */
	public String getTextoRazaoCancelamento() {
		return textoRazaoCancelamento;
	}

	/**
	 * @param textoRazaoCancelamento
	 *            the textoRazaoCancelamento to set
	 */
	public void setTextoRazaoCancelamento(final String textoRazaoCancelamento) {
		this.textoRazaoCancelamento = textoRazaoCancelamento;
	}

	/**
	 * @return the dataVencimento
	 */
	public Date getDataVencimento() {
		return dataVencimento;
	}

	/**
	 * @param dataVencimento
	 *            the dataVencimento to set
	 */
	public void setDataVencimento(final Date dataVencimento) {
		this.dataVencimento = dataVencimento;
	}

	/**
	 * @return the cotacaoMoeda
	 */
	public CotacaoMoeda getCotacaoMoeda() {
		return cotacaoMoeda;
	}

	/**
	 * @param cotacaoMoeda
	 *            the cotacaoMoeda to set
	 */
	public void setCotacaoMoeda(final CotacaoMoeda cotacaoMoeda) {
		this.cotacaoMoeda = cotacaoMoeda;
	}

	/**
	 * Obtem o valor do atributo centroLucroByCeluCdCentroLucroUmkt.<BR>
	 * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO_UMKT.
	 * 
	 * @return Valor do atributo centroLucroByCeluCdCentroLucroUmkt.
	 */
	public CentroLucro getCentroLucroUmkt() {
		return this.centroLucroUmkt;
	}

	/**
	 * Atualiza o valor do atributo centroLucroByCeluCdCentroLucroUmkt.<BR>
	 * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO_UMKT.
	 */
	public void setCentroLucroUmkt(CentroLucro centroLucroUmkt) {
		this.centroLucroUmkt = centroLucroUmkt;
	}

	/**
	 * Obtem o valor do atributo centroLucroByCeluCdCentroLucroSso.<BR>
	 * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO_SSO.
	 * 
	 * @return Valor do atributo centroLucroByCeluCdCentroLucroSso.
	 */
	public CentroLucro getCentroLucroSso() {
		return this.centroLucroSso;
	}

	/**
	 * Atualiza o valor do atributo centroLucroByCeluCdCentroLucroSso.<BR>
	 * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO_SSO.
	 */
	public void setCentroLucroSso(CentroLucro centroLucroSso) {
		this.centroLucroSso = centroLucroSso;
	}

	/**
	 * @return the itemFaturaApagados
	 */
	public List<ItemFaturaApagado> getItemFaturaApagados() {
		return itemFaturaApagados;
	}

	/**
	 * @param itemFaturaApagados the itemFaturaApagados to set
	 */
	public void setItemFaturaApagados(List<ItemFaturaApagado> itemFaturaApagados) {
		this.itemFaturaApagados = itemFaturaApagados;
	}

	/**
	 * @see Object#toString()
	 * @return representação String do Objeto
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoFatura").append("='").append(getCodigoFatura())
				.append("' ");
		buffer.append("moeda").append("='").append(getMoeda()).append("' ");
		buffer.append("dealFiscal").append("='").append(getDealFiscal())
				.append("' ");
		buffer.append("dataPrevisao").append("='").append(getDataPrevisao())
				.append("' ");
		buffer.append("numeroDoc").append("='").append(getNumeroDoc())
				.append("' ");
		buffer.append("textoObservacao").append("='")
				.append(getTextoObservacao()).append("' ");
		buffer.append("indicadorStatus").append("='")
				.append(getIndicadorStatus()).append("' ");
		buffer.append("codigoLoginAe").append("='").append(getCodigoLoginAe())
				.append("' ");
		buffer.append("codigoErpPedido").append("='")
				.append(getCodigoErpPedido()).append("' ");
		buffer.append("textoError").append("='").append(getTextoError())
				.append("' ");
		buffer.append("dataCancelamento").append("='")
				.append(getDataCancelamento()).append("' ");
		buffer.append("textoRazaoCancelamento").append("='")
				.append(getTextoRazaoCancelamento()).append("' ");
		buffer.append("cotacaoMoeda").append("='").append(getCotacaoMoeda())
				.append("' ");
		buffer.append("dataVencimento").append("='")
				.append(getDataVencimento()).append("' ");
		buffer.append("centroLucroByCeluCdCentroLucroSso").append("='")
				.append(getCentroLucroSso()).append("' ");
		buffer.append("moeda").append("='").append(getMoeda()).append("' ");
		buffer.append("centroLucroByCeluCdCentroLucroUmkt").append("='")
				.append(getCentroLucroUmkt()).append("' ")
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}