/*
 * @(#) FichaReajuste.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;

/**
 * Entity gerado a partir da tabela FICHA_REAJUSTE.
 *
 * @author Generated by Hibernate Tools 3.6.0
 * @since 06/12/2013 16:56:59
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "FICHA_REAJUSTE")
@NamedQueries({
	@NamedQuery(name = "FichaReajuste.findAll", query = "SELECT t FROM FichaReajuste t"),
	
	@NamedQuery(name = "FichaReajuste.findByStatus", query = "SELECT t FROM FichaReajuste t"
			+ " WHERE t.fichaReajusteStatus = :fichaReajusteStatus"),

	@NamedQuery(name = "FichaReajuste.findByNomeFichaReajuste", query = "SELECT t FROM FichaReajuste t"
			+ " WHERE t.nomeFichaReajuste = :nomeFichaReajuste"),

	@NamedQuery(name = "FichaReajuste.findByDocumentoLegal", query = "SELECT f FROM FichaReajuste f"
			+ " WHERE f.codigoFichaReajuste IN (:idsFichaReajuste)")
})
public class FichaReajuste implements java.io.Serializable, Cloneable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * Constante para NamedQuery "FichaReajuste.findAll".
	 */
	public static final String FIND_ALL = "FichaReajuste.findAll";
	
	/** 
	 * Constante para NamedQuery "FichaReajuste.findByStatus".
	 */
	public static final String FIND_BY_STATUS = "FichaReajuste.findByStatus";
	
	/** 
	 * Constante para NamedQuery "FichaReajuste.findAll".
	 */
	public static final String FIND_BY_NOME_FICHA_REAJUSTE = "FichaReajuste.findByNomeFichaReajuste";
	
	/** 
	 * Constante para NamedQuery "FichaReajuste.findByDocumentoLegal".
	 */
	public static final String FIND_BY_DOCUMENTOS_LEGAIS = "FichaReajuste.findByDocumentoLegal";

	/**
	 * Atributo gerado a partir da coluna FIRE_CD_FICHA_REAJUSTE.
	 */
	@Id
	@GeneratedValue(generator = "FichaReajusteSeq")
	@SequenceGenerator(name = "FichaReajusteSeq", sequenceName = "SQ_FIRE_CD_FICHA_REAJUSTE", allocationSize = 1)
	@Column(name = "FIRE_CD_FICHA_REAJUSTE", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoFichaReajuste;

	/**
	 * Atributo gerado a partir da coluna FIRI_CD_FICHA_REAJUSTE_INDICE.
	 */
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FIRI_CD_FICHA_REAJUSTE_INDICE", nullable = false)
	private FichaReajusteIndice fichaReajusteIndice;

	/**
	 * Atributo gerado a partir da coluna FIRS_CD_FICHA_REAJUSTE_STATUS.
	 */
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FIRS_CD_FICHA_REAJUSTE_STATUS", nullable = false)
	private FichaReajusteStatus fichaReajusteStatus;

	/**
	 * Atributo gerado a partir da coluna FIRE_NM_FICHA_REAJUSTE.
	 */
	@Audited
	@Column(name = "FIRE_NM_FICHA_REAJUSTE", nullable = false, length = 200)
	private String nomeFichaReajuste;

	/**
	 * Atributo gerado a partir da coluna FIRE_DT_BASE.
	 */
	@Audited
	@Temporal(TemporalType.DATE)
	@Column(name = "FIRE_DT_BASE", length = 7)
	private Date dataBase;

	/**
	 * Atributo gerado a partir da coluna FIRE_NR_PERIODICIDADE.
	 */
	@Audited
	@Column(name = "FIRE_NR_PERIODICIDADE", precision = 18, scale = 0)
	private Integer numeroPeriodicidade;

	/**
	 * Atributo gerado a partir da coluna FIRE_TX_CLAUSULA.
	 */
	@Audited
	@Column(name = "FIRE_TX_CLAUSULA", length = 1000)
	private String textoClausula;

	/**
	 * Atributo gerado a partir da coluna FIRE_TX_OBSERVACAO.
	 */
	@Audited
	@Column(name = "FIRE_TX_OBSERVACAO", length = 1000)
	private String textoObservacao;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaReajuste", cascade=CascadeType.REMOVE)
	private Set<ControleReajuste> controleReajustes = new HashSet<ControleReajuste>(
			0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaReajuste")
	private Set<DocumentoLegal> documentoLegals = new HashSet<DocumentoLegal>(0);

	/**
	 * Construtor default.
	 */
	public FichaReajuste() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * @param codigoFichaReajuste Valor do atributo codigoFichaReajuste;
	 * @param fichaReajusteIndice Valor do atributo fichaReajusteIndice;
	 * @param fichaReajusteStatus Valor do atributo fichaReajusteStatus;
	 * @param nomeFichaReajuste Valor do atributo nomeFichaReajuste;
	 */
	public FichaReajuste(Long codigoFichaReajuste,
			FichaReajusteIndice fichaReajusteIndice,
			FichaReajusteStatus fichaReajusteStatus, String nomeFichaReajuste) {
		this.codigoFichaReajuste = codigoFichaReajuste;
		this.fichaReajusteIndice = fichaReajusteIndice;
		this.fichaReajusteStatus = fichaReajusteStatus;
		this.nomeFichaReajuste = nomeFichaReajuste;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * @param codigoFichaReajuste Valor do atributo codigoFichaReajuste;
	 * @param fichaReajusteIndice Valor do atributo fichaReajusteIndice;
	 * @param fichaReajusteStatus Valor do atributo fichaReajusteStatus;
	 * @param nomeFichaReajuste Valor do atributo nomeFichaReajuste;
	 */
	public FichaReajuste(Long codigoFichaReajuste,
			FichaReajusteIndice fichaReajusteIndice,
			FichaReajusteStatus fichaReajusteStatus, String nomeFichaReajuste,
			Date dataBase, Integer numeroPeriodicidade, String textoClausula,
			String textoObservacao, Set<ControleReajuste> controleReajustes,
			Set<DocumentoLegal> documentoLegals) {
		this.codigoFichaReajuste = codigoFichaReajuste;
		this.fichaReajusteIndice = fichaReajusteIndice;
		this.fichaReajusteStatus = fichaReajusteStatus;
		this.nomeFichaReajuste = nomeFichaReajuste;
		this.dataBase = dataBase;
		this.numeroPeriodicidade = numeroPeriodicidade;
		this.textoClausula = textoClausula;
		this.textoObservacao = textoObservacao;
		this.controleReajustes = controleReajustes;
		this.documentoLegals = documentoLegals;
	}

	/**
	 * Obtem o valor do atributo codigoFichaReajuste.<BR>
	 * Atributo gerado a partir da coluna FIRE_CD_FICHA_REAJUSTE.
	 * @return Valor do atributo codigoFichaReajuste.
	 */
	public Long getCodigoFichaReajuste() {
		return this.codigoFichaReajuste;
	}

	/**
	 * Atualiza o valor do atributo codigoFichaReajuste.<BR>
	 * Atributo gerado a partir da coluna FIRE_CD_FICHA_REAJUSTE.
	 * @param codigoFichaReajuste Novo valor para o atributo codigoFichaReajuste.
	 */
	public void setCodigoFichaReajuste(Long codigoFichaReajuste) {
		this.codigoFichaReajuste = codigoFichaReajuste;
	}

	/**
	 * Obtem o valor do atributo fichaReajusteIndice.<BR>
	 * Atributo gerado a partir da coluna FIRI_CD_FICHA_REAJUSTE_INDICE.
	 * @return Valor do atributo fichaReajusteIndice.
	 */
	public FichaReajusteIndice getFichaReajusteIndice() {
		return this.fichaReajusteIndice;
	}

	/**
	 * Atualiza o valor do atributo fichaReajusteIndice.<BR>
	 * Atributo gerado a partir da coluna FIRI_CD_FICHA_REAJUSTE_INDICE.
	 * @param fichaReajusteIndice Novo valor para o atributo fichaReajusteIndice.
	 */
	public void setFichaReajusteIndice(FichaReajusteIndice fichaReajusteIndice) {
		this.fichaReajusteIndice = fichaReajusteIndice;
	}

	/**
	 * Obtem o valor do atributo fichaReajusteStatus.<BR>
	 * Atributo gerado a partir da coluna FIRS_CD_FICHA_REAJUSTE_STATUS.
	 * @return Valor do atributo fichaReajusteStatus.
	 */
	public FichaReajusteStatus getFichaReajusteStatus() {
		return this.fichaReajusteStatus;
	}

	/**
	 * Atualiza o valor do atributo fichaReajusteStatus.<BR>
	 * Atributo gerado a partir da coluna FIRS_CD_FICHA_REAJUSTE_STATUS.
	 * @param fichaReajusteStatus Novo valor para o atributo fichaReajusteStatus.
	 */
	public void setFichaReajusteStatus(FichaReajusteStatus fichaReajusteStatus) {
		this.fichaReajusteStatus = fichaReajusteStatus;
	}

	/**
	 * Obtem o valor do atributo nomeFichaReajuste.<BR>
	 * Atributo gerado a partir da coluna FIRE_NM_FICHA_REAJUSTE.
	 * @return Valor do atributo nomeFichaReajuste.
	 */
	public String getNomeFichaReajuste() {
		return this.nomeFichaReajuste;
	}

	/**
	 * Atualiza o valor do atributo nomeFichaReajuste.<BR>
	 * Atributo gerado a partir da coluna FIRE_NM_FICHA_REAJUSTE.
	 * @param nomeFichaReajuste Novo valor para o atributo nomeFichaReajuste.
	 */
	public void setNomeFichaReajuste(String nomeFichaReajuste) {
		this.nomeFichaReajuste = nomeFichaReajuste;
	}

	/**
	 * Obtem o valor do atributo dataBase.<BR>
	 * Atributo gerado a partir da coluna FIRE_DT_BASE.
	 * @return Valor do atributo dataBase.
	 */
	public Date getDataBase() {
		return this.dataBase;
	}

	/**
	 * Atualiza o valor do atributo dataBase.<BR>
	 * Atributo gerado a partir da coluna FIRE_DT_BASE.
	 * @param dataBase Novo valor para o atributo dataBase.
	 */
	public void setDataBase(Date dataBase) {
		this.dataBase = dataBase;
	}

	/**
	 * Obtem o valor do atributo numeroPeriodicidade.<BR>
	 * Atributo gerado a partir da coluna FIRE_NR_PERIODICIDADE.
	 * @return Valor do atributo numeroPeriodicidade.
	 */
	public Integer getNumeroPeriodicidade() {
		return this.numeroPeriodicidade;
	}

	/**
	 * Atualiza o valor do atributo numeroPeriodicidade.<BR>
	 * Atributo gerado a partir da coluna FIRE_NR_PERIODICIDADE.
	 * @param numeroPeriodicidade Novo valor para o atributo numeroPeriodicidade.
	 */
	public void setNumeroPeriodicidade(Integer numeroPeriodicidade) {
		this.numeroPeriodicidade = numeroPeriodicidade;
	}

	/**
	 * Obtem o valor do atributo textoClausula.<BR>
	 * Atributo gerado a partir da coluna FIRE_TX_CLAUSULA.
	 * @return Valor do atributo textoClausula.
	 */
	public String getTextoClausula() {
		return this.textoClausula;
	}

	/**
	 * Atualiza o valor do atributo textoClausula.<BR>
	 * Atributo gerado a partir da coluna FIRE_TX_CLAUSULA.
	 * @param textoClausula Novo valor para o atributo textoClausula.
	 */
	public void setTextoClausula(String textoClausula) {
		this.textoClausula = textoClausula;
	}

	/**
	 * Obtem o valor do atributo textoObservacao.<BR>
	 * Atributo gerado a partir da coluna FIRE_TX_OBSERVACAO.
	 * @return Valor do atributo textoObservacao.
	 */
	public String getTextoObservacao() {
		return this.textoObservacao;
	}

	/**
	 * Atualiza o valor do atributo textoObservacao.<BR>
	 * Atributo gerado a partir da coluna FIRE_TX_OBSERVACAO.
	 * @param textoObservacao Novo valor para o atributo textoObservacao.
	 */
	public void setTextoObservacao(String textoObservacao) {
		this.textoObservacao = textoObservacao;
	}

	/**
	 * Obtem o valor do atributo controleReajustes.<BR>

	 * @return Valor do atributo controleReajustes.
	 */
	public Set<ControleReajuste> getControleReajustes() {
		return this.controleReajustes;
	}

	/**
	 * Atualiza o valor do atributo controleReajustes.<BR>

	 * @param controleReajustes Novo valor para o atributo controleReajustes.
	 */
	public void setControleReajustes(Set<ControleReajuste> controleReajustes) {
		this.controleReajustes = controleReajustes;
	}

	/**
	 * Obtem o valor do atributo documentoLegals.<BR>

	 * @return Valor do atributo documentoLegals.
	 */
	public Set<DocumentoLegal> getDocumentoLegals() {
		return this.documentoLegals;
	}

	/**
	 * Atualiza o valor do atributo documentoLegals.<BR>

	 * @param documentoLegals Novo valor para o atributo documentoLegals.
	 */
	public void setDocumentoLegals(Set<DocumentoLegal> documentoLegals) {
		this.documentoLegals = documentoLegals;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoFichaReajuste").append("='")
				.append(getCodigoFichaReajuste()).append("' ");
		buffer.append("fichaReajusteIndice").append("='")
				.append(getFichaReajusteIndice()).append("' ");
		buffer.append("fichaReajusteStatus").append("='")
				.append(getFichaReajusteStatus()).append("' ");
		buffer.append("nomeFichaReajuste").append("='")
				.append(getNomeFichaReajuste()).append("' ");
		buffer.append("dataBase").append("='").append(getDataBase())
				.append("' ");
		buffer.append("numeroPeriodicidade").append("='")
				.append(getNumeroPeriodicidade()).append("' ");
		buffer.append("textoClausula").append("='").append(getTextoClausula())
				.append("' ");
		buffer.append("textoObservacao").append("='")
				.append(getTextoObservacao()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}
	
	public Msa getMsaForDataTable() {
		Msa msa = null;
		for (DocumentoLegal dl : this.getDocumentoLegals()) {
			msa = dl.getMsa();
			break;
		}

		return msa;
	}

	/**
	 * Retona a que de hoje mais a periodicidade da {@link FichaReajuste}
	 *
	 * @return {@link Date}
	 */
	public Date getFrequencyIntervalFromNow() {
		Calendar interval = Calendar.getInstance();
		interval.add(Calendar.MONTH, this.getNumeroPeriodicidade());
		interval.set(Calendar.MINUTE, 0);
		interval.set(Calendar.SECOND, 0);

		return interval.getTime();
	}
}