/*
 * @(#) FichaReajusteIndice.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela FICHA_REAJUSTE_INDICE.
 *
 * @author Generated by Hibernate Tools 3.6.0
 * @since 06/12/2013 16:56:59
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "FICHA_REAJUSTE_INDICE")
@NamedQueries({
	@NamedQuery(name = "FichaReajusteIndice.findAll", query = "SELECT t FROM FichaReajusteIndice t"),
	@NamedQuery(name = "FichaReajusteIndice.findByNomeFichaReajusteIndice", query = "SELECT i FROM FichaReajusteIndice i"
			+ " WHERE i.nomeFichaReajusteIndice = :nomeFichaReajusteIndice")
})
public class FichaReajusteIndice implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * Constante para NamedQuery "FichaReajusteIndice.findAll".
	 */
	public static final String FIND_ALL = "FichaReajusteIndice.findAll";
	
	/** 
	 * Constante para NamedQuery "FichaReajusteIndice.findByNomeFichaReajusteIndice".
	 */
	public static final String FIND_BY_NOME_FICHA_REAJUSTE_INDICE = "FichaReajusteIndice.findByNomeFichaReajusteIndice";

	/**
	 * Atributo gerado a partir da coluna FIRI_CD_FICHA_REAJUSTE_INDICE.
	 */
	@Id
	@GeneratedValue(generator = "FichaReajusteIndiceSeq")
	@SequenceGenerator(name = "FichaReajusteIndiceSeq", sequenceName = "SQ_FIRI_CD_FICHA_REAJUSTE_INDICE", allocationSize = 1)
	@Column(name = "FIRI_CD_FICHA_REAJUSTE_INDICE", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoFichaReajusteIndice;

	/**
	 * Atributo gerado a partir da coluna FIRI_NM_FICHA_REAJUSTE_INDICE.
	 */

	@Column(name = "FIRI_NM_FICHA_REAJUSTE_INDICE", length = 50)
	private String nomeFichaReajusteIndice;

	/**
	 * Atributo gerado a partir da coluna FIRI_IN_ATIVO.
	 */

	@Column(name = "FIRI_IN_ATIVO", length = 1)
	private String indicadorAtivo;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaReajusteIndice")
	private Set<FichaReajuste> fichaReajustes = new HashSet<FichaReajuste>(0);

	/**
	 * Construtor default.
	 */
	public FichaReajusteIndice() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * @param codigoFichaReajusteIndice Valor do atributo codigoFichaReajusteIndice;
	 */
	public FichaReajusteIndice(Long codigoFichaReajusteIndice) {
		this.codigoFichaReajusteIndice = codigoFichaReajusteIndice;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * @param codigoFichaReajusteIndice Valor do atributo codigoFichaReajusteIndice;
	 */
	public FichaReajusteIndice(Long codigoFichaReajusteIndice,
			String nomeFichaReajusteIndice, String indicadorAtivo,
			Set<FichaReajuste> fichaReajustes) {
		this.codigoFichaReajusteIndice = codigoFichaReajusteIndice;
		this.nomeFichaReajusteIndice = nomeFichaReajusteIndice;
		this.indicadorAtivo = indicadorAtivo;
		this.fichaReajustes = fichaReajustes;
	}

	/**
	 * Obtem o valor do atributo codigoFichaReajusteIndice.<BR>
	 * Atributo gerado a partir da coluna FIRI_CD_FICHA_REAJUSTE_INDICE.
	 * @return Valor do atributo codigoFichaReajusteIndice.
	 */
	public Long getCodigoFichaReajusteIndice() {
		return this.codigoFichaReajusteIndice;
	}

	/**
	 * Atualiza o valor do atributo codigoFichaReajusteIndice.<BR>
	 * Atributo gerado a partir da coluna FIRI_CD_FICHA_REAJUSTE_INDICE.
	 * @param codigoFichaReajusteIndice Novo valor para o atributo codigoFichaReajusteIndice.
	 */
	public void setCodigoFichaReajusteIndice(Long codigoFichaReajusteIndice) {
		this.codigoFichaReajusteIndice = codigoFichaReajusteIndice;
	}

	/**
	 * Obtem o valor do atributo nomeFichaReajusteIndice.<BR>
	 * Atributo gerado a partir da coluna FIRI_NM_FICHA_REAJUSTE_INDICE.
	 * @return Valor do atributo nomeFichaReajusteIndice.
	 */
	public String getNomeFichaReajusteIndice() {
		return this.nomeFichaReajusteIndice;
	}

	/**
	 * Atualiza o valor do atributo nomeFichaReajusteIndice.<BR>
	 * Atributo gerado a partir da coluna FIRI_NM_FICHA_REAJUSTE_INDICE.
	 * @param nomeFichaReajusteIndice Novo valor para o atributo nomeFichaReajusteIndice.
	 */
	public void setNomeFichaReajusteIndice(String nomeFichaReajusteIndice) {
		this.nomeFichaReajusteIndice = nomeFichaReajusteIndice;
	}

	/**
	 * Obtem o valor do atributo indicadorAtivo.<BR>
	 * Atributo gerado a partir da coluna FIRI_IN_ATIVO.
	 * @return Valor do atributo indicadorAtivo.
	 */
	public String getIndicadorAtivo() {
		return this.indicadorAtivo;
	}

	/**
	 * Atualiza o valor do atributo indicadorAtivo.<BR>
	 * Atributo gerado a partir da coluna FIRI_IN_ATIVO.
	 * @param indicadorAtivo Novo valor para o atributo indicadorAtivo.
	 */
	public void setIndicadorAtivo(String indicadorAtivo) {
		this.indicadorAtivo = indicadorAtivo;
	}

	/**
	 * Obtem o valor do atributo fichaReajustes.<BR>

	 * @return Valor do atributo fichaReajustes.
	 */
	public Set<FichaReajuste> getFichaReajustes() {
		return this.fichaReajustes;
	}

	/**
	 * Atualiza o valor do atributo fichaReajustes.<BR>

	 * @param fichaReajustes Novo valor para o atributo fichaReajustes.
	 */
	public void setFichaReajustes(Set<FichaReajuste> fichaReajustes) {
		this.fichaReajustes = fichaReajustes;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoFichaReajusteIndice").append("='")
				.append(getCodigoFichaReajusteIndice()).append("' ");
		buffer.append("nomeFichaReajusteIndice").append("='")
				.append(getNomeFichaReajusteIndice()).append("' ");
		buffer.append("indicadorAtivo").append("='")
				.append(getIndicadorAtivo()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
