/*
 * @(#) FollowCliente.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela FOLLOW_CLIENTE.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 30/07/2012 09:47:20
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "FOLLOW_CLIENTE")
@NamedQueries({
        @NamedQuery(name = "FollowCliente.findAll", query = "SELECT t FROM FollowCliente t"),
        @NamedQuery(name = "FollowCliente.findByCodigoLogin", query = "SELECT t FROM FollowCliente t "
                +   "WHERE t.codigoLogin = ? "),
        @NamedQuery(name = "FollowCliente.findByClienteAndCodigoLogin", query = "SELECT t FROM FollowCliente t "
                +   "WHERE t.cliente.codigoCliente = ? "
                +   "AND t.codigoLogin = ? "),
        @NamedQuery(name = "FollowCliente.findByCliente", query = "SELECT t FROM FollowCliente t "
                +   "WHERE t.cliente.codigoCliente = ? ")
})
public class FollowCliente implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "FollowCliente.findAll".
     */
    public static final String FIND_ALL = "FollowCliente.findAll";

    /**
     * Constante para NamedQuery "FollowCliente.findByCodigoLogin".
     */
    public static final String FIND_BY_CODIGO_LOGIN =
            "FollowCliente.findByCodigoLogin";

    /**
     * Constante para NamedQuery "FollowCliente.findByClienteAndCodigoLogin".
     */
    public static final String FIND_BY_CLIENTE_AND_CODIGO_LOGIN =
            "FollowCliente.findByClienteAndCodigoLogin";
    
    /**
     * Constante para NamedQuery "FollowCliente.findByCliente".
     */
    public static final String FIND_BY_CLIENTE =
            "FollowCliente.findByCliente";

    /**
     * Atributo gerado a partir da coluna FOCL_CD_FOLLOW_CLIENTE.
     */
    @Id
    @GeneratedValue(generator = "FollowClienteSeq")
    @SequenceGenerator(name = "FollowClienteSeq", sequenceName = "SQ_FOCL_CD_FOLLOW_CLIENTE", allocationSize = 1)
    @Column(name = "FOCL_CD_FOLLOW_CLIENTE", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoFollowCliente;

    /**
     * Atributo gerado a partir da coluna CLIE_CD_CLIENTE.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIE_CD_CLIENTE", nullable = false)
    private Cliente cliente;

    /**
     * Atributo gerado a partir da coluna PESS_CD_LOGIN.
     */

    @Column(name = "PESS_CD_LOGIN", length = 100)
    private String codigoLogin;

    /**
     * Construtor default.
     */
    public FollowCliente() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoFollowCliente
     *            Valor do atributo codigoFollowCliente;
     * @param cliente
     *            Valor do atributo cliente;
     */
    public FollowCliente(final Long codigoFollowCliente, final Cliente cliente) {
        this.codigoFollowCliente = codigoFollowCliente;
        this.cliente = cliente;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoFollowCliente
     *            Valor do atributo codigoFollowCliente;
     * @param cliente
     *            Valor do atributo cliente;
     * @param codigoLogin
     *            Valor do atributo codigoLogin;
     */
    public FollowCliente(final Long codigoFollowCliente, final Cliente cliente,
            final String codigoLogin) {
        this.codigoFollowCliente = codigoFollowCliente;
        this.cliente = cliente;
        this.codigoLogin = codigoLogin;
    }

    /**
     * Obtem o valor do atributo codigoFollowCliente.<BR>
     * Atributo gerado a partir da coluna FOCL_CD_FOLLOW_CLIENTE.
     * 
     * @return Valor do atributo codigoFollowCliente.
     */
    public Long getCodigoFollowCliente() {
        return this.codigoFollowCliente;
    }

    /**
     * Atualiza o valor do atributo codigoFollowCliente.<BR>
     * Atributo gerado a partir da coluna FOCL_CD_FOLLOW_CLIENTE.
     * 
     * @param codigoFollowCliente
     *            Novo valor para o atributo codigoFollowCliente.
     */
    public void setCodigoFollowCliente(final Long codigoFollowCliente) {
        this.codigoFollowCliente = codigoFollowCliente;
    }

    /**
     * Obtem o valor do atributo cliente.<BR>
     * Atributo gerado a partir da coluna CLIE_CD_CLIENTE.
     * 
     * @return Valor do atributo cliente.
     */
    public Cliente getCliente() {
        return this.cliente;
    }

    /**
     * Atualiza o valor do atributo cliente.<BR>
     * Atributo gerado a partir da coluna CLIE_CD_CLIENTE.
     * 
     * @param cliente
     *            Novo valor para o atributo cliente.
     */
    public void setCliente(final Cliente cliente) {
        this.cliente = cliente;
    }

    /**
     * Obtem o valor do atributo codigoLogin.<BR>
     * Atributo gerado a partir da coluna PESS_CD_LOGIN.
     * 
     * @return Valor do atributo codigoLogin.
     */
    public String getCodigoLogin() {
        return this.codigoLogin;
    }

    /**
     * Atualiza o valor do atributo codigoLogin.<BR>
     * Atributo gerado a partir da coluna PESS_CD_LOGIN.
     * 
     * @param codigoLogin
     *            Novo valor para o atributo codigoLogin.
     */
    public void setCodigoLogin(final String codigoLogin) {
        this.codigoLogin = codigoLogin;
    }

    /**
     * @see Object#toString()
     * @return buffer
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoFollowCliente").append("='").append(
                getCodigoFollowCliente()).append("' ");
        buffer.append("cliente").append("='").append(getCliente()).append("' ");
        buffer.append("codigoLogin").append("='").append(getCodigoLogin())
                .append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
