/*
 * @(#) GrupoCustoPeriodo.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;
import org.hibernate.envers.RelationTargetAuditMode;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela GRUPO_CUSTO_PERIODO.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 12/05/2010 11:53:39
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Audited
@AuditTable(value = "GRUPO_CUSTO_PERIODO_AUD")
@Table(name = "GRUPO_CUSTO_PERIODO")
@NamedQueries({ 
    @NamedQuery(name = "GrupoCustoPeriodo.findAll", query = "SELECT t FROM GrupoCustoPeriodo t"),
    
    @NamedQuery(name = "GrupoCustoPeriodo.findMaxStartDateByGrupoCusto", 
            query = "SELECT gcp FROM GrupoCustoPeriodo gcp "
        + " WHERE gcp.grupoCusto.codigoGrupoCusto = ? "
        + " AND gcp.dataInicio = "
        + "(SELECT MAX(t.dataInicio) FROM GrupoCustoPeriodo t"
        + " WHERE t.grupoCusto.codigoGrupoCusto = ?)")
})
public class GrupoCustoPeriodo implements java.io.Serializable {
    
    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    
    /** 
     * Constante para NamedQuery "GrupoCustoPeriodo.findMaxStartDateByGrupoCusto".
     */
    public static final String FIND_MAX_START_DATE_BY_GRUPO_CUSTO = 
        "GrupoCustoPeriodo.findMaxStartDateByGrupoCusto";

    /**
     * Atributo gerado a partir da tabela GRUPO_CUSTO_CENTRO_LUCRO.
     */
    @NotAudited
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoCustoPeriodo", cascade = CascadeType.ALL)
    private List<GrupoCustoCentroLucro> grupoCustoCentroLucros = new ArrayList<GrupoCustoCentroLucro>(
            0);
    
    /**
     * Obtem o valor do atributo grupoCustoCentroLucros.<BR>

     * @return Valor do atributo grupoCustoCentroLucros.
     */
    public List<GrupoCustoCentroLucro> getGrupoCustoCentroLucros() {
        return this.grupoCustoCentroLucros;
    }

    /**
     * Atualiza o valor do atributo grupoCustoCentroLucros.<BR>

     * @param grupoCustoCentroLucros Novo valor para o atributo grupoCustoCentroLucros.
     */
    public void setGrupoCustoCentroLucros(
            final List<GrupoCustoCentroLucro> grupoCustoCentroLucros) {
        this.grupoCustoCentroLucros = grupoCustoCentroLucros;
    }
    
    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "GrupoCustoPeriodo.findAll".
     */
    public static final String FIND_ALL = "GrupoCustoPeriodo.findAll";

    /**
     * Atributo gerado a partir da coluna GRCP_CD_GC_PERIODO.
     */
    @Audited
    @Id
    @GeneratedValue(generator = "GrupoCustoPeriodoSeq")
    @SequenceGenerator(name = "GrupoCustoPeriodoSeq", sequenceName = "SQ_GRCP_CD_GC_PERIODO", allocationSize = 1)
    @Column(name = "GRCP_CD_GC_PERIODO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoGcPeriodo;

    /**
     * Atributo gerado a partir da coluna GRCU_CD_GRUPO_CUSTO.
     */
    @Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GRCU_CD_GRUPO_CUSTO", nullable = false)
    private GrupoCusto grupoCusto;

    /**
     * Atributo gerado a partir da coluna GRCP_DT_INICIO.
     */
    @Audited
    @Temporal(TemporalType.DATE)
    @Column(name = "GRCP_DT_INICIO", length = 7)
    private Date dataInicio;

    /**
     * Atributo gerado a partir da coluna GRCP_DT_FIM.
     */
    @Audited
    @Temporal(TemporalType.DATE)
    @Column(name = "GRCP_DT_FIM", length = 7)
    private Date dataFim;

    /**
     * Construtor default.
     */
    public GrupoCustoPeriodo() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoGcPeriodo Valor do atributo codigoGcPeriodo;
     * @param grupoCusto Valor do atributo grupoCusto;
     */
    public GrupoCustoPeriodo(final Long codigoGcPeriodo, final GrupoCusto grupoCusto) {
        this.codigoGcPeriodo = codigoGcPeriodo;
        this.grupoCusto = grupoCusto;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoGcPeriodo Valor do atributo codigoGcPeriodo;
     * @param grupoCusto Valor do atributo grupoCusto;
     * @param dataInicio Valor do atributo dataInicio;
     * @param dataFim Valor do atributo dataFim;
     * @param grupoCustoCentroLucros Valor do atributo grupoCustoCentroLucros;
     */
    public GrupoCustoPeriodo(final Long codigoGcPeriodo, final GrupoCusto grupoCusto,
            final Date dataInicio, final Date dataFim,
            final List<GrupoCustoCentroLucro> grupoCustoCentroLucros) {
        this.codigoGcPeriodo = codigoGcPeriodo;
        this.grupoCusto = grupoCusto;
        this.dataInicio = dataInicio;
        this.dataFim = dataFim;
        this.grupoCustoCentroLucros = grupoCustoCentroLucros;
    }

    /**
     * Obtem o valor do atributo codigoGcPeriodo.<BR>
     * Atributo gerado a partir da coluna GRCP_CD_GC_PERIODO.
     * @return Valor do atributo codigoGcPeriodo.
     */
    public Long getCodigoGcPeriodo() {
        return this.codigoGcPeriodo;
    }

    /**
     * Atualiza o valor do atributo codigoGcPeriodo.<BR>
     * Atributo gerado a partir da coluna GRCP_CD_GC_PERIODO.
     * @param codigoGcPeriodo Novo valor para o atributo codigoGcPeriodo.
     */
    public void setCodigoGcPeriodo(final Long codigoGcPeriodo) {
        this.codigoGcPeriodo = codigoGcPeriodo;
    }

    /**
     * Obtem o valor do atributo grupoCusto.<BR>
     * Atributo gerado a partir da coluna GRCU_CD_GRUPO_CUSTO.
     * @return Valor do atributo grupoCusto.
     */
    public GrupoCusto getGrupoCusto() {
        return this.grupoCusto;
    }

    /**
     * Atualiza o valor do atributo grupoCusto.<BR>
     * Atributo gerado a partir da coluna GRCU_CD_GRUPO_CUSTO.
     * @param grupoCusto Novo valor para o atributo grupoCusto.
     */
    public void setGrupoCusto(final GrupoCusto grupoCusto) {
        this.grupoCusto = grupoCusto;
    }

    /**
     * Obtem o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna GRCP_DT_INICIO.
     * @return Valor do atributo dataInicio.
     */
    public Date getDataInicio() {
        return this.dataInicio;
    }

    /**
     * Atualiza o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna GRCP_DT_INICIO.
     * @param dataInicio Novo valor para o atributo dataInicio.
     */
    public void setDataInicio(final Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    /**
     * Obtem o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna GRCP_DT_FIM.
     * @return Valor do atributo dataFim.
     */
    public Date getDataFim() {
        return this.dataFim;
    }

    /**
     * Atualiza o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna GRCP_DT_FIM.
     * @param dataFim Novo valor para o atributo dataFim.
     */
    public void setDataFim(final Date dataFim) {
        this.dataFim = dataFim;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoGcPeriodo").append("='").append(
                getCodigoGcPeriodo()).append("' ");
        buffer.append("grupoCusto").append("='").append(getGrupoCusto())
                .append("' ");
        buffer.append("dataInicio").append("='").append(getDataInicio())
                .append("' ");
        buffer.append("dataFim").append("='").append(getDataFim()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
