/*
 * @(#) GrupoCusto.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import com.ciandt.pms.persistence.dao.jpa.GrupoCustoAreaOrcamentaria;
import org.hibernate.annotations.Cascade;
import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;
import org.hibernate.envers.RelationTargetAuditMode;

import javax.persistence.*;
import java.util.*;

/**
 * Entity gerado a partir da tabela GRUPO_CUSTO esta entidade representa
 * "Cost Center".
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 11/03/2010 15:46:37
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "GRUPO_CUSTO")
@Audited
@AuditTable(value = "GRUPO_CUSTO_AUD")
@SqlResultSetMappings(@SqlResultSetMapping(name = "scalarGrupoCusto", entities = @EntityResult(entityClass = GrupoCusto.class)))
@NamedQueries({
		@NamedQuery(name = GrupoCusto.FIND_ACTIVE_PROD_COM, query = "SELECT t FROM GrupoCusto t "
				+ "LEFT JOIN FETCH t.empresa "
				+ "JOIN t.area a "
				+ "WHERE t.indicadorDeletado = 'N' "
				+ "AND a.indicadorAtivo = 'A' "
				+ "AND a.codigoArea IN (1,4) "
				+ "ORDER BY t.nomeGrupoCusto "),
		@NamedQuery(name = "GrupoCusto.findAll", query = "SELECT t FROM GrupoCusto t "
				+ "LEFT JOIN FETCH t.empresa "
				+ "WHERE t.indicadorDeletado = 'N' "
				+ "ORDER BY t.nomeGrupoCusto "),

        @NamedQuery(name = GrupoCusto.FIND_ALL_ACTIVE, query = "SELECT gc FROM GrupoCusto gc "
				+ "LEFT JOIN FETCH gc.empresa "
				+ "WHERE gc.indicadorAtivo = 'A' "
				+ "AND gc.indicadorDeletado = 'N' "
				+ "ORDER BY upper(gc.nomeGrupoCusto)"),

		@NamedQuery(name = GrupoCusto.FIND_ALL_ACTIVE_RETURN_CODIGO_AND_NOME_GRUPO_CUSTO, query = "SELECT new GrupoCusto(gc.codigoGrupoCusto, gc.nomeGrupoCusto) FROM GrupoCusto gc "
				+ "WHERE gc.indicadorAtivo = 'A' "
				+ "AND gc.indicadorDeletado = 'N' "
				+ "ORDER BY upper(gc.nomeGrupoCusto)"),
				
		@NamedQuery(name = GrupoCusto.FIND_ALL_ACTIVE_BY_ESTR_ORG, query = "SELECT gc FROM GrupoCusto gc "
				+ "LEFT JOIN FETCH gc.empresa "
				+ "WHERE gc.indicadorAtivo = 'A' "
				+ "AND gc.indicadorDeletado = 'N' "
				+ "AND gc.area.siglaEstrOrganiz = :siglaArea "
				+ "ORDER BY gc.nomeGrupoCusto"),

        @NamedQuery(name = "GrupoCusto.findByAcronym", query = "SELECT gc FROM GrupoCusto gc "
				+ "LEFT JOIN FETCH gc.empresa "
				+ "WHERE gc.siglaGrupoCusto = ? "
				+ "AND gc.indicadorDeletado = 'N' "
				+ "ORDER BY gc.nomeGrupoCusto "),

		@NamedQuery(name = GrupoCusto.FIND_GRUPOCUSTO_BY_ID_WITH_PERIODOS, query = "SELECT gc FROM GrupoCusto gc "
				+ "LEFT JOIN FETCH gc.grupoCustoPeriodos gcp "
				+ "LEFT JOIN FETCH gc.empresa "
				+ "WHERE gc.codigoGrupoCusto = ? "
				+ "AND gc.indicadorDeletado = 'N' "),

        @NamedQuery(name = "GrupoCusto.findByFilter", query = "SELECT gc FROM GrupoCusto gc "
				+ "LEFT JOIN FETCH gc.empresa "
				+ "LEFT JOIN FETCH gc.grupoCustoStatus gcs "
                + "WHERE (UPPER(gc.nomeGrupoCusto) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + "AND (UPPER(gc.siglaGrupoCusto) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
				+ "AND (UPPER(gcs.siglaStatusGrupoCusto) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
				+ "AND gc.indicadorDeletado = 'N' "
                + "ORDER BY gc.nomeGrupoCusto ASC "),

		@NamedQuery(name = "GrupoCusto.findByAproverRescinded", query =
				  "SELECT gc FROM GrupoCusto gc, Pessoa ps "
				+ "WHERE (gc.aprovador.codigoPessoa = ps.codigoPessoa OR gc.gerenteAprovador.codigoPessoa = ps.codigoPessoa) "
				+ "AND ps.dataRescisao is not null "
				+ "AND gc.indicadorAtivo = 'A' "
				+ "AND gc.grupoCustoStatus = 1 "
				+ "AND gc.indicadorDeletado = 'N' "
				+ "ORDER BY gc.nomeGrupoCusto ASC "),
		@NamedQuery(name = "GrupoCusto.findAllGrupoCustoByCostCenterHierarchy", query = "SELECT gc FROM GrupoCusto gc "
				+ "WHERE gc.costCenterHierarchy.code = :costCenterHierarchyCode "
				+ "ORDER BY gc.nomeGrupoCusto ASC ")})
public class GrupoCusto implements java.io.Serializable {

    /** Constante para NamedQuery "GrupoCusto.findAllActive". */
    public static final String FIND_ALL_ACTIVE = "GrupoCusto.findAllActive";

	/** Constante para NamedQuery "GrupoCusto.findActiveProdCom". */
	public static final String FIND_ACTIVE_PROD_COM = "GrupoCusto.findActiveProdCom";
    
    /** Constante para NamedQuery "GrupoCusto.findAllActiveReturnCodigoAndNomeGrupoCusto". */
    public static final String FIND_ALL_ACTIVE_RETURN_CODIGO_AND_NOME_GRUPO_CUSTO = "GrupoCusto.findAllActiveReturnCodigoAndNomeGrupoCusto";

	/** Constante para NamedQuery "GrupoCusto.findByFilter". */
    public static final String FIND_BY_FILTER = "GrupoCusto.findByFilter";

	/** Constante para NamedQuery "GrupoCusto.findByAproverRescinded". */
	public static final String FIND_BY_APPROVER_RESCINDED = "GrupoCusto.findByAproverRescinded";


	/** Constante para NamedQuery "GrupoCusto.findByAcronym". */
    public static final String FIND_BY_ACRONYM = "GrupoCusto.findByAcronym";

    /**
	 * Constante para NamedQuery "GrupoCusto.findGrupoCustoByIdWithPeriodos".
	 */
	public static final String FIND_GRUPOCUSTO_BY_ID_WITH_PERIODOS = "GrupoCusto.findGrupoCustoByIdWithPeriodos";

	public static final String FIND_ALL_ACTIVE_BY_ESTR_ORG = "GrupoCusto.findGrupoCustoAllActiveAndEstrOrgan";

	public static final String FIND_ALL_BY_COST_CENTER_HIERARCHY = "GrupoCusto.findAllGrupoCustoByCostCenterHierarchy";

    /**
     * Atributo gerado a partir da tabela GRUPO_CUSTO_PERIODO.
     */
		@NotAudited
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoCusto", cascade = CascadeType.ALL)
    private List<GrupoCustoPeriodo> grupoCustoPeriodos =
            new ArrayList<GrupoCustoPeriodo>(0);

    /** Atributo gerado a partir da coluna AREA_CD_AREA. */
		@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "AREA_CD_AREA", nullable = true)
    private Area area;

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** Constante para NamedQuery "GrupoCusto.findAll". */
    public static final String FIND_ALL = "GrupoCusto.findAll";

    /**
     * Atributo gerado a partir da coluna GRCU_CD_GRUPO_CUSTO.
     */
    @Id
    @GeneratedValue(generator = "GrupoCustoSeq")
    @SequenceGenerator(name = "GrupoCustoSeq", sequenceName = "SQ_GRCU_CD_GRUPO_CUSTO", allocationSize = 1)
    @Column(name = "GRCU_CD_GRUPO_CUSTO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoGrupoCusto;

    /**
     * Atributo gerado a partir da coluna GRCU_NM_GRUPO_CUSTO.
     */

    @Column(name = "GRCU_NM_GRUPO_CUSTO", length = 100)
    private String nomeGrupoCusto;

    /**
     * Atributo gerado a partir da coluna GRCU_SG_GRUPO_CUSTO.
     */

    @Column(name = "GRCU_SG_GRUPO_CUSTO", length = 10)
    private String siglaGrupoCusto;

    /**
     * Atributo gerado a partir da coluna GRCU_IN_ATIVO.
     */
    @Column(name = "GRCU_IN_ATIVO", nullable = false, length = 1)
    private String indicadorAtivo;

    /**
     * Atributo gerado a partir da coluna GRCU_DT_ATIVO.
     */
	@Temporal(TemporalType.DATE)
	@Column(name = "GRCU_DT_INATIVACAO", length = 7, nullable = true)
	private Date dataInativacao;

	/**
	 * Atributo gerado a partir da coluna GRCU_DT_ATIVO.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "GRCU_DT_IMPLANTACAO", length = 7, nullable = true)
	private Date dataImplantacao;

    /**
     * Atributo gerado a partir da tabela PESSOA_GRUPO_CUSTO.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoCusto")
		@NotAudited
    private Set<PessoaGrupoCusto> pessoaGrupoCustos =
            new HashSet<PessoaGrupoCusto>(0);
    /**
     * Atributo gerado a partir da tabela REGISTRO_ATIVIDADE.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoCusto")
		@NotAudited
    private List<RegistroAtividade> registroAtividades =
            new ArrayList<RegistroAtividade>(0);

    /**
     * Atributo gerado a partir da tabela UPLOAD_DESPESA.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoCusto")
		@NotAudited
    private List<UploadDespesa> uploadDespesas =
            new ArrayList<UploadDespesa>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoCusto")
	@NotAudited
	private List<Convergencia> convergencias = new ArrayList<Convergencia>();

	/**
	 * Lista de GrupoCustoAreaOrcamentaria.
	 */
	@OrderBy("dataInicio, ASC")
	@NotAudited
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoCusto")
	@Cascade(org.hibernate.annotations.CascadeType.ALL)
	private List<GrupoCustoAreaOrcamentaria> grupoCustoAreaOrcamentarias = 
		new ArrayList<GrupoCustoAreaOrcamentaria>(0);

	/**
	 * Atributo gerado a partir da coluna PESS_CD_APROVADOR.
	 */
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PESS_CD_APROVADOR")
	private Pessoa aprovador;

    /**
	 * Atributo gerado a partir da coluna PESS_CD_GERENTE.
	 */
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PESS_CD_GERENTE")
	private Pessoa gerenteAprovador;

	/**
	 * Atributo gerado a partir da coluna EMPR_CD_EMPRESA.
	 */
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPR_CD_EMPRESA")
	private Empresa empresa;

	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne
	@JoinColumn(name = "COCH_CD_COST_CENTER_HIERARCHY")
	private CostCenterHierarchy costCenterHierarchy;

	@Column(name = "GRCU_IN_DELETE_LOGICO")
	private String indicadorDeletado;

    @Column(name = "ERP_CD_CCUSTO", nullable = true)
    private Long erpCodigoCentroCusto;

	@Column(name = "ERP_CD_CCUSTO_PAI", nullable = true)
	private Long erpCodigoCentroCustoPai;

	@Column(name = "ERP_CD_IDE_PAI", nullable = true)
	private Long erpCodigoIdePai;

	@Column(name = "ERP_CD_IDE_PROJ_OVERHEAD_PAI", nullable = true)
	private Long erpCodigoIdePaiProjetoOverhead;

    @Column(name = "ERP_CD_PAD_CCUSTO", nullable = true)
    private Long erpCentroCustoPadrao;

	@Column(name = "ERP_CD_PROJ_OVERHEAD", nullable = true)
	private Long erpCodigoProjetoOverhead;

	@Column(name = "ERP_CD_PROJ_OVERHEAD_PAI", nullable = true)
	private Long erpCodigoProjetoOverheadPai;

	@Column(name = "ERP_TIPO_CONTA", nullable = true)
	private String erpTipoConta;

	@Transient
    private Boolean activeView;

	@Transient
	private Boolean activeEdit;

	@Transient
	private Boolean activeFollow;

	@Transient
	private Boolean activeUnfollow;

	@Transient
	private Boolean activeTravelBudget;

	@Transient
	private Boolean activeDelete;

	@Transient
	private Boolean changeStatusCostCenter;

	@Transient
	private Boolean hasBudgetArea;

	@Transient
	private Boolean isInactivationProcess;

	@Transient
	private String errorMessageBudgetAreaConstraintContentFirstText = "";

	@Transient
	private String errorMessageBudgetAreaConstraintContentSecondText = "";

	@Transient
	private String errorMessageBudgetAreaConstraintContentThirdText = "";

	@Transient
	private boolean isErrorMessageBudgetAreaConstraint = false;

	@Transient
	private boolean enabledFieldInactivationDate = false;

	@Transient
	private boolean enabledParentOverheadProject = false;

	@Transient
	private boolean disabledFieldInactivationDate = false;

	@Column(name = "GRCU_TX_DESCRICAO")
	private String descricaoGrupoCusto;

	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRCS_CD_GRUPO_CUSTO_STATUS", nullable = false)
	private GrupoCustoStatus grupoCustoStatus;
	
	@NotAudited
	@Column(name = "GRCU_IN_REQUEST_INTEG")
	private String requestIntegration;

	@NotAudited
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoCusto")
	private Set<ContratoPraticaGrupoCusto> contratoPraticaGrupoCustos = new HashSet<ContratoPraticaGrupoCusto>(
			0);



	/**
     * Construtor default.
     */
    public GrupoCusto() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoGrupoCusto
     *            Valor do atributo codigoGrupoCusto;
     * @param nomeGrupoCusto
     *            Valor do atributo nomeGrupoCusto;
     */
    public GrupoCusto(final Long codigoGrupoCusto, final String nomeGrupoCusto) {
        this.codigoGrupoCusto = codigoGrupoCusto;
        this.nomeGrupoCusto = nomeGrupoCusto;
    }

	public GrupoCusto(final Long codigoGrupoCusto, final String nomeGrupoCusto, Empresa empresa) {
		this.codigoGrupoCusto = codigoGrupoCusto;
		this.nomeGrupoCusto = nomeGrupoCusto;
		this.empresa = empresa;
	}

    /**
     * Construtor com preenchimento da entidade.
     *  @param codigoGrupoCusto
     *            Valor do atributo codigoGrupoCusto;
     * @param nomeGrupoCusto
     *            Valor do atributo nomeGrupoCusto;
	 * @param siglaGrupoCusto
 *            Valor do atributo siglaGrupoCusto;
	 * @param indicadorAtivo
*            Valor do atributo indicadorAtivo;
	 * @param pessoaGrupoCustos
*            Valor do atributo pessoaGrupoCustos;
	 * @param grupoCustoPeriodos
	 * @param descricaoGrupoCusto
	 */
    public GrupoCusto(final Long codigoGrupoCusto, final String nomeGrupoCusto,
					  final String siglaGrupoCusto, final String indicadorAtivo,
					  final Set<PessoaGrupoCusto> pessoaGrupoCustos,
					  final List<GrupoCustoPeriodo> grupoCustoPeriodos, String descricaoGrupoCusto,
					  GrupoCustoStatus grupoCustoStatus, String requestIntegration) {
        this.codigoGrupoCusto = codigoGrupoCusto;
        this.nomeGrupoCusto = nomeGrupoCusto;
        this.siglaGrupoCusto = siglaGrupoCusto;
        this.indicadorAtivo = indicadorAtivo;
        this.pessoaGrupoCustos = pessoaGrupoCustos;
        this.grupoCustoPeriodos = grupoCustoPeriodos;
		this.descricaoGrupoCusto = descricaoGrupoCusto;
		this.grupoCustoStatus = grupoCustoStatus;
		this.requestIntegration = requestIntegration;
	}

    /**
     * Obtem o valor do atributo grupoCustoPeriodos.<BR>
     * 
     * @return Valor do atributo grupoCustoPeriodos.
     */
    public List<GrupoCustoPeriodo> getGrupoCustoPeriodos() {
        return this.grupoCustoPeriodos;
    }

    /**
     * Atualiza o valor do atributo grupoCustoPeriodos.<BR>
     * 
     * @param grupoCustoPeriodos
     *            Novo valor para o atributo grupoCustoPeriodos.
     */
    public void setGrupoCustoPeriodos(
            final List<GrupoCustoPeriodo> grupoCustoPeriodos) {
        this.grupoCustoPeriodos = grupoCustoPeriodos;
    }

    /**
     * Obtem o valor do atributo codigoGrupoCusto.<BR>
     * Atributo gerado a partir da coluna GRCU_CD_GRUPO_CUSTO.
     * 
     * @return Valor do atributo codigoGrupoCusto.
     */
    public Long getCodigoGrupoCusto() {
        return this.codigoGrupoCusto;
    }

    /**
     * Atualiza o valor do atributo codigoGrupoCusto.<BR>
     * Atributo gerado a partir da coluna GRCU_CD_GRUPO_CUSTO.
     * 
     * @param codigoGrupoCusto
     *            Novo valor para o atributo codigoGrupoCusto.
     */
    public void setCodigoGrupoCusto(final Long codigoGrupoCusto) {
        this.codigoGrupoCusto = codigoGrupoCusto;
    }

    /**
     * Obtem o valor do atributo nomeGrupoCusto.<BR>
     * Atributo gerado a partir da coluna GRCU_NM_GRUPO_CUSTO.
     * 
     * @return Valor do atributo nomeGrupoCusto.
     */
    public String getNomeGrupoCusto() {
        return this.nomeGrupoCusto;
    }

    /**
     * Atualiza o valor do atributo nomeGrupoCusto.<BR>
     * Atributo gerado a partir da coluna GRCU_NM_GRUPO_CUSTO.
     * 
     * @param nomeGrupoCusto
     *            Novo valor para o atributo nomeGrupoCusto.
     */
    public void setNomeGrupoCusto(final String nomeGrupoCusto) {
        this.nomeGrupoCusto = nomeGrupoCusto;
    }

    /**
     * Obtem o valor do atributo siglaGrupoCusto.<BR>
     * Atributo gerado a partir da coluna GRCU_SG_GRUPO_CUSTO.
     * 
     * @return Valor do atributo siglaGrupoCusto.
     */
    public String getSiglaGrupoCusto() {
        return this.siglaGrupoCusto;
    }

    /**
     * Atualiza o valor do atributo siglaGrupoCusto.<BR>
     * Atributo gerado a partir da coluna GRCU_SG_GRUPO_CUSTO.
     * 
     * @param siglaGrupoCusto
     *            Novo valor para o atributo siglaGrupoCusto.
     */
    public void setSiglaGrupoCusto(final String siglaGrupoCusto) {
        this.siglaGrupoCusto = siglaGrupoCusto;
    }

    /**
     * Obtem o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna GRCU_IN_ATIVO.
     * 
     * @return Valor do atributo indicadorAtivo.
     */
    public String getIndicadorAtivo() {
        return this.indicadorAtivo;
    }

    /**
     * Atualiza o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna GRCU_IN_ATIVO.
     * 
     * @param indicadorAtivo
     *            Novo valor para o atributo indicadorAtivo.
     */
    public void setIndicadorAtivo(final String indicadorAtivo) {
        this.indicadorAtivo = indicadorAtivo;
    }

    /**
     * Obtem o valor do atributo pessoaGrupoCustos.<BR>
     * 
     * @return Valor do atributo pessoaGrupoCustos.
     */
    public Set<PessoaGrupoCusto> getPessoaGrupoCustos() {
        return this.pessoaGrupoCustos;
    }

    /**
     * Atualiza o valor do atributo pessoaGrupoCustos.<BR>
     * 
     * @param pessoaGrupoCustos
     *            Novo valor para o atributo pessoaGrupoCustos.
     */
    public void setPessoaGrupoCustos(
            final Set<PessoaGrupoCusto> pessoaGrupoCustos) {
        this.pessoaGrupoCustos = pessoaGrupoCustos;
    }

    /**
     * Obtem o valor do atributo area.<BR>
     * Atributo gerado a partir da coluna AREA_CD_AREA.
     * 
     * @return Valor do atributo area.
     */
    public Area getArea() {
        return this.area;
    }

    /**
     * Atualiza o valor do atributo area.<BR>
     * Atributo gerado a partir da coluna AREA_CD_AREA.
     * 
     * @param area
     *            Novo valor para o atributo area.
     */
    public void setArea(final Area area) {
        this.area = area;
    }

    /**
     * @return the uploadDespesas
     */
    public List<UploadDespesa> getUploadDespesas() {
        return uploadDespesas;
    }

    /**
     * @param uploadDespesas
     *            the uploadDespesas to set
     */
    public void setUploadDespesas(final List<UploadDespesa> uploadDespesas) {
        this.uploadDespesas = uploadDespesas;
    }

    /**
     * @return the registroAtividades
     */
    public List<RegistroAtividade> getRegistroAtividades() {
        return registroAtividades;
    }

    /**
     * @param registroAtividades
     *            the registroAtividades to set
     */
    public void setRegistroAtividades(List<RegistroAtividade> registroAtividades) {
        this.registroAtividades = registroAtividades;
    }

    /**
	 * @return the convegencias
	 */
	public List<Convergencia> getConvergencias() {
		return convergencias;
	}

	/**
	 * @param convergencias
	 *            the convergencias to set
	 */
	public void setConvergencias(List<Convergencia> convergencias) {
		this.convergencias = convergencias;
	}

	/**
	 * @return the aprovador
	 */
	public Pessoa getAprovador() {
		return aprovador;
	}

	/**
	 * @param aprovador
	 *            the aprovador to set
	 */
	public void setAprovador(Pessoa aprovador) {
		this.aprovador = aprovador;
	}

	/**
	 * @return the gerenteAprovador
	 */
	public Pessoa getGerenteAprovador() {
		return gerenteAprovador;
	}

	/**
	 * @param gerenteAprovador
	 *            the gerenteAprovador to set
	 */
	public void setGerenteAprovador(Pessoa gerenteAprovador) {
		this.gerenteAprovador = gerenteAprovador;
	}

	/**
	 * Obtem o valor do atributo {@link GrupoCusto#empresa}.<BR>
	 * 
	 * @return the empresa
	 */
	public Empresa getEmpresa() {
		return empresa;
	}

	/**
	 * Atualiza o valor do atributo empresa.<BR>
	 * 
	 * @param empresa
	 *            Novo valor para o atributo {@link GrupoCusto#empresa}.
	 */
	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public CostCenterHierarchy getCostCenterHierarchy() {
		return this.costCenterHierarchy;
	}

	public void setCostCenterHierarchy(CostCenterHierarchy costCenterHierarchy) {
		this.costCenterHierarchy = costCenterHierarchy;
	}

	/**
	 * Obtem o valor do atributo {@link GrupoCusto#indicadorDeletado}.<BR>
	 * 
	 * @return the indicadorDeletado
	 */
	public String getIndicadorDeletado() {
		return indicadorDeletado;
	}

	/**
	 * Atualiza o valor do atributo indicadorDeletado.<BR>
	 * 
	 * @param indicadorDeletado
	 *            {@link GrupoCusto}.
	 */
	public void setIndicadorDeletado(String indicadorDeletado) {
		this.indicadorDeletado = indicadorDeletado;
	}

	/**
	 * Obtem o valor do atributo {@link GrupoCusto#dataInativacao}.<BR>
	 *
	 * @return the dataInativacao
	 */
	public Date getDataInativacao() {
		return dataInativacao;
	}

	/**
	 * Atualiza o valor do atributo dataInativacao.<BR>
	 *
	 * @param dataInativacao Novo valor para o atributo {@link GrupoCusto#dataInativacao}.
	 */
	public void setDataInativacao(Date dataInativacao) {
		this.dataInativacao = dataInativacao;
	}

	/**
	 * Obtem o valor do atributo {@link GrupoCusto#dataImplantacao}.<BR>
	 *
	 * @return the dataImplantacao
	 */
	public Date getDataImplantacao() {
		return dataImplantacao;
	}

	/**
	 * Atualiza o valor do atributo dataImplantacao.<BR>
	 *
	 * @param dataImplantacao Novo valor para o atributo {@link GrupoCusto#dataImplantacao}.
	 */
	public void setDataImplantacao(Date dataImplantacao) {
		this.dataImplantacao = dataImplantacao;
	}

	/**
	 * Obtem o valor do atributo {@link GrupoCusto#erpCodigoCentroCusto}.<BR>
	 *
	 * @return the erpCodigoCentroCusto
	 */
	public Long getErpCodigoCentroCusto() {
		return erpCodigoCentroCusto;
	}

	/**
	 * Atualiza o valor do atributo erpCodigoCentroCusto.<BR>
	 *
	 * @param erpCodigoCentroCusto Novo valor para o atributo {@link GrupoCusto#erpCodigoCentroCusto}.
	 */
	public void setErpCodigoCentroCusto(Long erpCodigoCentroCusto) {
		this.erpCodigoCentroCusto = erpCodigoCentroCusto;
	}


	/**
	 * Obtem o valor do atributo {@link GrupoCusto#erpCodigoCentroCustoPai}.<BR>
	 *
	 * @return the erpCodigoCentroCustoPai
	 */
	public Long getErpCodigoCentroCustoPai() {
		return erpCodigoCentroCustoPai;
	}

	/**
	 * Atualiza o valor do atributo erpCodigoCentroCustoPai.<BR>
	 *
	 * @param erpCodigoCentroCustoPai Novo valor para o atributo {@link GrupoCusto#erpCodigoCentroCustoPai}.
	 */
	public void setErpCodigoCentroCustoPai(Long erpCodigoCentroCustoPai) {
		this.erpCodigoCentroCustoPai = erpCodigoCentroCustoPai;
	}

	public Long getErpCodigoIdePai() {
		return erpCodigoIdePai;
	}

	public void setErpCodigoIdePai(Long erpCodigoIdePai) {
		this.erpCodigoIdePai = erpCodigoIdePai;
	}

	public Long getErpCodigoIdePaiProjetoOverhead() {
		return erpCodigoIdePaiProjetoOverhead;
	}

	public void setErpCodigoIdePaiProjetoOverhead(Long erpCodigoIdePaiProjetoOverhead) {
		this.erpCodigoIdePaiProjetoOverhead = erpCodigoIdePaiProjetoOverhead;
	}

	/**
	 * Obtem o valor do atributo {@link GrupoCusto#erpCentroCustoPadrao}.<BR>
	 *
	 * @return the erpCentroCustoPadrao
	 */
	public Long getErpCentroCustoPadrao() {
		return erpCentroCustoPadrao;
	}

	/**
	 * Atualiza o valor do atributo erpCentroCustoPadrao.<BR>
	 *
	 * @param erpCentroCustoPadrao Novo valor para o atributo {@link GrupoCusto#erpCentroCustoPadrao}.
	 */
	public void setErpCentroCustoPadrao(Long erpCentroCustoPadrao) {
		this.erpCentroCustoPadrao = erpCentroCustoPadrao;
	}

	/**
	 * @return the contratoPraticaGrupoCustos
	 */
	public Set<ContratoPraticaGrupoCusto> getContratoPraticaGrupoCustos() {
		return contratoPraticaGrupoCustos;
	}

	/**
	 * @param contratoPraticaGrupoCustos the contratoPraticaGrupoCustos to set
	 */
	public void setContratoPraticaGrupoCustos(
			Set<ContratoPraticaGrupoCusto> contratoPraticaGrupoCustos) {
		this.contratoPraticaGrupoCustos = contratoPraticaGrupoCustos;
	}

	public Boolean getActiveView() {
		return activeView;
	}

	public void setActiveView(Boolean activeView) {
		this.activeView = activeView;
	}

	public Boolean getActiveEdit() {
		return activeEdit;
	}

	public void setActiveEdit(Boolean activeEdit) {
		this.activeEdit = activeEdit;
	}

	public Boolean getActiveFollow() {
		return activeFollow;
	}

	public void setActiveFollow(Boolean activeFollow) {
		this.activeFollow = activeFollow;
	}

	public Boolean getActiveUnfollow() {
		return activeUnfollow;
	}

	public void setActiveUnfollow(Boolean activeUnfollow) {
		this.activeUnfollow = activeUnfollow;
	}

	public Boolean getActiveTravelBudget() {
		return activeTravelBudget;
	}

	public void setActiveTravelBudget(Boolean activeTravelBudget) {
		this.activeTravelBudget = activeTravelBudget;
	}

	public Boolean getActiveDelete() {
		return activeDelete;
	}

	public void setActiveDelete(Boolean activeDelete) {
		this.activeDelete = activeDelete;
	}


	public Boolean getChangeStatusCostCenter() {
		return changeStatusCostCenter;
	}

	public void setChangeStatusCostCenter(Boolean changeStatusCostCenter) {
		this.changeStatusCostCenter = changeStatusCostCenter;
	}

	public Boolean getHasBudgetArea() {
		return hasBudgetArea;
	}

	public void setHasBudgetArea(Boolean hasBudgetArea) {
		this.hasBudgetArea = hasBudgetArea;
	}

	public Boolean getIsInactivationProcess() {
		return isInactivationProcess;
	}

	public void setIsInactivationProcess(Boolean isInactivationProcess) {
		this.isInactivationProcess = isInactivationProcess;
	}

	public Long getErpCodigoProjetoOverhead() {
		return erpCodigoProjetoOverhead;
	}

	public void setErpCodigoProjetoOverhead(Long erpCodigoProjetoOverhead) {
		this.erpCodigoProjetoOverhead = erpCodigoProjetoOverhead;
	}

	public Long getErpCodigoProjetoOverheadPai() {
		return erpCodigoProjetoOverheadPai;
	}

	public void setErpCodigoProjetoOverheadPai(Long erpCodigoProjetoOverheadPai) {
		this.erpCodigoProjetoOverheadPai = erpCodigoProjetoOverheadPai;
	}

	public String getErpTipoConta() {
		return erpTipoConta;
	}

	public void setErpTipoConta(String erpTipoConta) {
		this.erpTipoConta = erpTipoConta;
	}


	/**
	 * @return the grupoCustoAreaOrcamentarias
	 */
	public List<GrupoCustoAreaOrcamentaria> getGrupoCustoAreaOrcamentarias() {
		return grupoCustoAreaOrcamentarias;
	}

	/**
	 * @param grupoCustoAreaOrcamentarias the grupoCustoAreaOrcamentarias to set
	 */
	public void setGrupoCustoAreaOrcamentarias(
			List<GrupoCustoAreaOrcamentaria> grupoCustoAreaOrcamentarias) {
		this.grupoCustoAreaOrcamentarias = grupoCustoAreaOrcamentarias;
	}

	public String getDescricaoGrupoCusto() {
		return descricaoGrupoCusto;
	}

	public void setDescricaoGrupoCusto(String descricaoGrupoCusto) {
		this.descricaoGrupoCusto = descricaoGrupoCusto;
	}

	public GrupoCustoStatus getGrupoCustoStatus() {
		return grupoCustoStatus;
	}

	public void setGrupoCustoStatus(GrupoCustoStatus grupoCustoStatus) {
		this.grupoCustoStatus = grupoCustoStatus;
	}

	public String getRequestIntegration() {
		return requestIntegration;
	}

	public void setRequestIntegration(String integrationError) {
		this.requestIntegration = integrationError;
	}

	public boolean getErrorMessageBudgetAreaConstraint() {
		return isErrorMessageBudgetAreaConstraint;
	}

	public void setErrorMessageBudgetAreaConstraint(boolean isErrorMessageBudgetAreaConstraint){
		this.isErrorMessageBudgetAreaConstraint = isErrorMessageBudgetAreaConstraint;
	}

	public String getErrorMessageBudgetAreaConstraintContentFirstText() {
		return errorMessageBudgetAreaConstraintContentFirstText;
	}

	public void setErrorMessageBudgetAreaConstraintContentFirstText(String errorMessageBudgetAreaConstraintContentFirstText) {
		this.errorMessageBudgetAreaConstraintContentFirstText = errorMessageBudgetAreaConstraintContentFirstText;
	}

	public String getErrorMessageBudgetAreaConstraintContentSecondText() {
		return errorMessageBudgetAreaConstraintContentSecondText;
	}

	public void setErrorMessageBudgetAreaConstraintContentSecondText(String errorMessageBudgetAreaConstraintContentSecondText) {
		this.errorMessageBudgetAreaConstraintContentSecondText = errorMessageBudgetAreaConstraintContentSecondText;
	}

	public String getErrorMessageBudgetAreaConstraintContentThirdText() {
		return errorMessageBudgetAreaConstraintContentThirdText;
	}

	public void setErrorMessageBudgetAreaConstraintContentThirdText(String errorMessageBudgetAreaConstraintContentThirdText) {
		this.errorMessageBudgetAreaConstraintContentThirdText = errorMessageBudgetAreaConstraintContentThirdText;
	}

	public boolean isEnabledFieldInactivationDate() {
		return enabledFieldInactivationDate;
	}

	public void setEnabledFieldInactivationDate(boolean enabledFieldInactivationDate) {
		this.enabledFieldInactivationDate = enabledFieldInactivationDate;
	}

	public boolean isEnabledParentOverheadProject() {
		return enabledParentOverheadProject;
	}

	public void setEnabledParentOverheadProject(boolean enabledParentOverheadProject) {
		this.enabledParentOverheadProject = enabledParentOverheadProject;
	}

	public boolean isDisabledFieldInactivationDate() {
		return disabledFieldInactivationDate;
	}

	public void setDisabledFieldInactivationDate(boolean disabledFieldInactivationDate) {
		this.disabledFieldInactivationDate = disabledFieldInactivationDate;
	}

	/**
     * @see Object#toString()
     * 
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoGrupoCusto").append("='").append(
                getCodigoGrupoCusto()).append("' ");
        buffer.append("nomeGrupoCusto").append("='")
                .append(getNomeGrupoCusto()).append("' ");
        buffer.append("siglaGrupoCusto").append("='").append(
                getSiglaGrupoCusto()).append("' ");
        buffer.append("indicadorAtivo").append("='")
                .append(getIndicadorAtivo()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
