/*
 * @(#) GrupoCustoCentroLucro.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Objects;

/**
 * Entity gerado a partir da tabela GRUPO_CUSTO_CENTRO_LUCRO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 12/05/2010 11:53:39
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "GRUPO_CUSTO_CENTRO_LUCRO")
@NamedQueries({ @NamedQuery(name = "GrupoCustoCentroLucro.findAll", 
        query = "SELECT t FROM GrupoCustoCentroLucro t") })
public class GrupoCustoCentroLucro implements java.io.Serializable {
    
    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    
    /**
     * Nome do CentroLucro.
     */
    @Transient
    private String nomeCentroLucro;
    
    /** Lista com os nomes do centro de lucro da NaturezaCentroLucro corrente. */
    @Transient
    private List<String> nomeCentroLucroList = new ArrayList<String>();
    
    /**
     * @return the nomeCentroLucro
     */
    public String getNomeCentroLucro() {
        return nomeCentroLucro;
    }

    /**
     * @param nomeCentroLucro the nomeCentroLucro to set
     */
    public void setNomeCentroLucro(final String nomeCentroLucro) {
        this.nomeCentroLucro = nomeCentroLucro;
    }
    
    /**
     * @return the nomeCentroLucroList
     */
    public List<String> getNomeCentroLucroList() {
        return nomeCentroLucroList;
    }

    /**
     * @param nomeCentroLucroList the nomeCentroLucroList to set
     */
    public void setNomeCentroLucroList(final List<String> nomeCentroLucroList) {
        this.nomeCentroLucroList = nomeCentroLucroList;
    }
    
    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "GrupoCustoCentroLucro.findAll".
     */
    public static final String FIND_ALL = "GrupoCustoCentroLucro.findAll";

    /**
     * Atributo gerado a partir da coluna GCCL_CD_GRUPO_CUSTO_CL.
     */
    @Id
    @GeneratedValue(generator = "GrupoCustoCentroLucroSeq")
    @SequenceGenerator(name = "GrupoCustoCentroLucroSeq", 
            sequenceName = "SQ_GCCL_CD_GRUPO_CUSTO_CL", allocationSize = 1)
    @Column(name = "GCCL_CD_GRUPO_CUSTO_CL", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoGrupoCustoCl;

    /**
     * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CELU_CD_CENTRO_LUCRO")
    private CentroLucro centroLucro;

    /**
     * Atributo gerado a partir da coluna NACL_CD_NATUREZA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NACL_CD_NATUREZA", nullable = false)
    private NaturezaCentroLucro naturezaCentroLucro;

    /**
     * Atributo gerado a partir da coluna GRCP_CD_GC_PERIODO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GRCP_CD_GC_PERIODO", nullable = false)
    private GrupoCustoPeriodo grupoCustoPeriodo;

    /**
     * Construtor default.
     */
    public GrupoCustoCentroLucro() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoGrupoCustoCl
     *            Valor do atributo codigoGrupoCustoCl;
     * @param naturezaCentroLucro
     *            Valor do atributo naturezaCentroLucro;
     * @param grupoCustoPeriodo
     *            Valor do atributo grupoCustoPeriodo;
     */
    public GrupoCustoCentroLucro(final Long codigoGrupoCustoCl,
            final NaturezaCentroLucro naturezaCentroLucro,
            final GrupoCustoPeriodo grupoCustoPeriodo) {
        this.codigoGrupoCustoCl = codigoGrupoCustoCl;
        this.naturezaCentroLucro = naturezaCentroLucro;
        this.grupoCustoPeriodo = grupoCustoPeriodo;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoGrupoCustoCl
     *            Valor do atributo codigoGrupoCustoCl;
     * @param naturezaCentroLucro
     *            Valor do atributo naturezaCentroLucro;
     * @param centroLucro
     *            Valor do atributo centroLucro;
     * @param grupoCustoPeriodo
     *            Valor do atributo grupoCustoPeriodo;
     */
    public GrupoCustoCentroLucro(final Long codigoGrupoCustoCl,
            final NaturezaCentroLucro naturezaCentroLucro,
            final CentroLucro centroLucro,
            final GrupoCustoPeriodo grupoCustoPeriodo) {
        this.codigoGrupoCustoCl = codigoGrupoCustoCl;
        this.naturezaCentroLucro = naturezaCentroLucro;
        this.centroLucro = centroLucro;
        this.grupoCustoPeriodo = grupoCustoPeriodo;
    }

    /**
     * Obtem o valor do atributo codigoGrupoCustoCl.<BR>
     * Atributo gerado a partir da coluna GCCL_CD_GRUPO_CUSTO_CL.
     * 
     * @return Valor do atributo codigoGrupoCustoCl.
     */
    public Long getCodigoGrupoCustoCl() {
        return this.codigoGrupoCustoCl;
    }

    /**
     * Atualiza o valor do atributo codigoGrupoCustoCl.<BR>
     * Atributo gerado a partir da coluna GCCL_CD_GRUPO_CUSTO_CL.
     * 
     * @param codigoGrupoCustoCl
     *            Novo valor para o atributo codigoGrupoCustoCl.
     */
    public void setCodigoGrupoCustoCl(final Long codigoGrupoCustoCl) {
        this.codigoGrupoCustoCl = codigoGrupoCustoCl;
    }

    /**
     * Obtem o valor do atributo centroLucro.<BR>
     * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO.
     * 
     * @return Valor do atributo centroLucro.
     */
    public CentroLucro getCentroLucro() {
        return this.centroLucro;
    }

    /**
     * Atualiza o valor do atributo centroLucro.<BR>
     * Atributo gerado a partir da coluna CELU_CD_CENTRO_LUCRO.
     * 
     * @param centroLucro
     *            Novo valor para o atributo centroLucro.
     */
    public void setCentroLucro(final CentroLucro centroLucro) {
        this.centroLucro = centroLucro;
    }

    /**
     * Obtem o valor do atributo naturezaCentroLucro.<BR>
     * Atributo gerado a partir da coluna NACL_CD_NATUREZA.
     * 
     * @return Valor do atributo naturezaCentroLucro.
     */
    public NaturezaCentroLucro getNaturezaCentroLucro() {
        return this.naturezaCentroLucro;
    }

    /**
     * Atualiza o valor do atributo naturezaCentroLucro.<BR>
     * Atributo gerado a partir da coluna NACL_CD_NATUREZA.
     * 
     * @param naturezaCentroLucro
     *            Novo valor para o atributo naturezaCentroLucro.
     */
    public void setNaturezaCentroLucro(
            final NaturezaCentroLucro naturezaCentroLucro) {
        this.naturezaCentroLucro = naturezaCentroLucro;
    }

    /**
     * Obtem o valor do atributo grupoCustoPeriodo.<BR>
     * Atributo gerado a partir da coluna GRCP_CD_GC_PERIODO.
     * 
     * @return Valor do atributo grupoCustoPeriodo.
     */
    public GrupoCustoPeriodo getGrupoCustoPeriodo() {
        return this.grupoCustoPeriodo;
    }

    /**
     * Atualiza o valor do atributo grupoCustoPeriodo.<BR>
     * Atributo gerado a partir da coluna GRCP_CD_GC_PERIODO.
     * 
     * @param grupoCustoPeriodo
     *            Novo valor para o atributo grupoCustoPeriodo.
     */
    public void setGrupoCustoPeriodo(final GrupoCustoPeriodo grupoCustoPeriodo) {
        this.grupoCustoPeriodo = grupoCustoPeriodo;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoGrupoCustoCl").append("='").append(
                getCodigoGrupoCustoCl()).append("' ");
        buffer.append("centroLucro").append("='").append(getCentroLucro())
                .append("' ");
        buffer.append("naturezaCentroLucro").append("='").append(
                getNaturezaCentroLucro()).append("' ");
        buffer.append("grupoCustoPeriodo").append("='").append(
                getGrupoCustoPeriodo()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;

        GrupoCustoCentroLucro that = (GrupoCustoCentroLucro) obj;

        return Objects.equals(codigoGrupoCustoCl, that.codigoGrupoCustoCl) &&
                Objects.equals(centroLucro, that.centroLucro) &&
                Objects.equals(naturezaCentroLucro, that.naturezaCentroLucro) &&
                Objects.equals(grupoCustoPeriodo, that.grupoCustoPeriodo);
    }

    @Override
    public int hashCode() {
        return Objects.hash(codigoGrupoCustoCl, centroLucro, naturezaCentroLucro, grupoCustoPeriodo);
    }

}