/*
 * @(#) HistoricoFatura.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela HISTORICO_FATURA.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 10/05/2011 13:45:44
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "HISTORICO_FATURA")
@NamedQueries({
    @NamedQuery(name = "HistoricoFatura.findAll", query = "SELECT t FROM HistoricoFatura t"),
    @NamedQuery(name = HistoricoFatura.FIND_BY_CODIGO_FATURA, query = "SELECT t FROM HistoricoFatura t"
    		+ " WHERE t.fatura.codigoFatura = :codigoFatura")
})
public class HistoricoFatura implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "HistoricoFatura.findAll".
     */
    public static final String FIND_ALL = "HistoricoFatura.findAll";

    public static final String FIND_BY_CODIGO_FATURA = "HistoricoFatura.findByCodigoFatura";

    /**
     * Atributo gerado a partir da coluna HIFA_CD_HISTORICO_FATURA.
     */
    @Id
    @GeneratedValue(generator = "HistoricoFaturaSeq")
    @SequenceGenerator(name = "HistoricoFaturaSeq", 
            sequenceName = "SQ_HIFA_CD_HISTORICO_FATURA", allocationSize = 1)
    @Column(name = "HIFA_CD_HISTORICO_FATURA", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoHistoricoFatura;

    /**
     * Atributo gerado a partir da coluna FATU_CD_FATURA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FATU_CD_FATURA", nullable = false)
    private Fatura fatura;

    /**
     * Atributo gerado a partir da coluna HIFA_CD_AUTOR.
     */

    @Column(name = "HIFA_CD_AUTOR", length = 50)
    private String codigoAutor;

    /**
     * Atributo gerado a partir da coluna HIFA_DT_ALTERACAO.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "HIFA_DT_ALTERACAO", length = 7)
    private Date dataAlteracao;

    /**
     * Atributo gerado a partir da coluna HIFA_IN_STATUS_ANTERIOR.
     */
    @Column(name = "HIFA_IN_STATUS_ANTERIOR", length = 2)
    private String indicadorStatusAnterior;

    /**
     * Atributo gerado a partir da coluna HIFA_IN_STATUS_ATUAL.
     */
    @Column(name = "HIFA_IN_STATUS_ATUAL", length = 2)
    private String indicadorStatusAtual;

	/**
	 * Atributo gerado a partir da coluna HIFA_VL_FATURA.
	 */
	@Column(name = "HIFA_VL_FATURA", precision = 22, scale = 0)
	private BigDecimal valorFatura;

    /**
     * Atributo gerado a partir da coluna HIFA_DT_PREVISAO.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "HIFA_DT_PREVISAO", length = 7)
    private Date dataPrevisao;

	/**
	 * Atributo gerado a partir da coluna MOED_CD_MOEDA.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOED_CD_MOEDA", nullable = false)
	private Moeda moeda;

    /**
     * Construtor default.
     */
    public HistoricoFatura() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoHistoricoFatura Valor do atributo codigoHistoricoFatura;
     * @param fatura Valor do atributo fatura;
     */
    public HistoricoFatura(final Long codigoHistoricoFatura, final Fatura fatura) {
        this.codigoHistoricoFatura = codigoHistoricoFatura;
        this.fatura = fatura;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoHistoricoFatura
     *            Valor do atributo codigoHistoricoFatura;
     * @param fatura
     *            Valor do atributo fatura;
     * @param codigoAutor
     *            Valor do atributo codigoAutor;
     * @param dataAlteracao
     *            Valor do atributo dataAlteracao;
     * @param indicadorStatusAnterior
     *            Valor do atributo indicadorStatusAnterior;
     * @param indicadorStatusAtual
     *            Valor do atributo indicadorStatusAtual;
     */
    public HistoricoFatura(final Long codigoHistoricoFatura,
            final Fatura fatura, final String codigoAutor,
            final Date dataAlteracao, final String indicadorStatusAnterior,
            final String indicadorStatusAtual) {
        this.codigoHistoricoFatura = codigoHistoricoFatura;
        this.fatura = fatura;
        this.codigoAutor = codigoAutor;
        this.dataAlteracao = dataAlteracao;
        this.indicadorStatusAnterior = indicadorStatusAnterior;
        this.indicadorStatusAtual = indicadorStatusAtual;
    }

    /**
     * Obtem o valor do atributo codigoHistoricoFatura.<BR>
     * Atributo gerado a partir da coluna HIFA_CD_HISTORICO_FATURA.
     * @return Valor do atributo codigoHistoricoFatura.
     */
    public Long getCodigoHistoricoFatura() {
        return this.codigoHistoricoFatura;
    }

    /**
     * Atualiza o valor do atributo codigoHistoricoFatura.<BR>
     * Atributo gerado a partir da coluna HIFA_CD_HISTORICO_FATURA.
     * @param codigoHistoricoFatura Novo valor para o atributo codigoHistoricoFatura.
     */
    public void setCodigoHistoricoFatura(final Long codigoHistoricoFatura) {
        this.codigoHistoricoFatura = codigoHistoricoFatura;
    }

    /**
     * Obtem o valor do atributo fatura.<BR>
     * Atributo gerado a partir da coluna FATU_CD_FATURA.
     * @return Valor do atributo fatura.
     */
    public Fatura getFatura() {
        return this.fatura;
    }

    /**
     * Atualiza o valor do atributo fatura.<BR>
     * Atributo gerado a partir da coluna FATU_CD_FATURA.
     * @param fatura Novo valor para o atributo fatura.
     */
    public void setFatura(final Fatura fatura) {
        this.fatura = fatura;
    }

    /**
     * Obtem o valor do atributo codigoAutor.<BR>
     * Atributo gerado a partir da coluna HIFA_CD_AUTOR.
     * @return Valor do atributo codigoAutor.
     */
    public String getCodigoAutor() {
        return this.codigoAutor;
    }

    /**
     * Atualiza o valor do atributo codigoAutor.<BR>
     * Atributo gerado a partir da coluna HIFA_CD_AUTOR.
     * @param codigoAutor Novo valor para o atributo codigoAutor.
     */
    public void setCodigoAutor(final String codigoAutor) {
        this.codigoAutor = codigoAutor;
    }

    /**
     * Obtem o valor do atributo dataAlteracao.<BR>
     * Atributo gerado a partir da coluna HIFA_DT_ALTERACAO.
     * @return Valor do atributo dataAlteracao.
     */
    public Date getDataAlteracao() {
        return this.dataAlteracao;
    }

    /**
     * Atualiza o valor do atributo dataAlteracao.<BR>
     * Atributo gerado a partir da coluna HIFA_DT_ALTERACAO.
     * @param dataAlteracao Novo valor para o atributo dataAlteracao.
     */
    public void setDataAlteracao(final Date dataAlteracao) {
        this.dataAlteracao = dataAlteracao;
    }

    /**
     * Obtem o valor do atributo indicadorStatusAnterior.<BR>
     * Atributo gerado a partir da coluna HIFA_IN_STATUS_ANTERIOR.
     * @return Valor do atributo indicadorStatusAnterior.
     */
    public String getIndicadorStatusAnterior() {
        return this.indicadorStatusAnterior;
    }

    /**
     * Atualiza o valor do atributo indicadorStatusAnterior.<BR>
     * Atributo gerado a partir da coluna HIFA_IN_STATUS_ANTERIOR.
     * @param indicadorStatusAnterior Novo valor para o atributo indicadorStatusAnterior.
     */
    public void setIndicadorStatusAnterior(final String indicadorStatusAnterior) {
        this.indicadorStatusAnterior = indicadorStatusAnterior;
    }

    /**
     * Obtem o valor do atributo indicadorStatusAtual.<BR>
     * Atributo gerado a partir da coluna HIFA_IN_STATUS_ATUAL.
     * @return Valor do atributo indicadorStatusAtual.
     */
    public String getIndicadorStatusAtual() {
        return this.indicadorStatusAtual;
    }

    /**
     * Atualiza o valor do atributo indicadorStatusAtual.<BR>
     * Atributo gerado a partir da coluna HIFA_IN_STATUS_ATUAL.
     * @param indicadorStatusAtual Novo valor para o atributo indicadorStatusAtual.
     */
    public void setIndicadorStatusAtual(final String indicadorStatusAtual) {
        this.indicadorStatusAtual = indicadorStatusAtual;
    }

    /**
	 * @return the valorFatura
	 */
	public BigDecimal getValorFatura() {
		return valorFatura;
	}

	/**
	 * @param valorFatura the valorFatura to set
	 */
	public void setValorFatura(BigDecimal valorFatura) {
		this.valorFatura = valorFatura;
	}

	/**
	 * @return the dataPrevisao
	 */
	public Date getDataPrevisao() {
		return dataPrevisao;
	}

	/**
	 * @param dataPrevisao the dataPrevisao to set
	 */
	public void setDataPrevisao(Date dataPrevisao) {
		this.dataPrevisao = dataPrevisao;
	}

	/**
	 * @return the moeda
	 */
	public Moeda getMoeda() {
		return moeda;
	}

	/**
	 * @param moeda the moeda to set
	 */
	public void setMoeda(Moeda moeda) {
		this.moeda = moeda;
	}

	/**
     * @see Object#toString()
     * @return retorna o objeto em formato de String.
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoHistoricoFatura").append("='").append(
                getCodigoHistoricoFatura()).append("' ");
        buffer.append("fatura").append("='").append(getFatura()).append("' ");
        buffer.append("codigoAutor").append("='").append(getCodigoAutor())
                .append("' ");
        buffer.append("dataAlteracao").append("='").append(getDataAlteracao())
                .append("' ");
        buffer.append("indicadorStatusAnterior").append("='").append(
                getIndicadorStatusAnterior()).append("' ");
        buffer.append("indicadorStatusAtual").append("='").append(
                getIndicadorStatusAtual()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}