/*
 * @(#) IntegFaturaParametro.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela INTEG_FATURA_PARAMETRO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 22/03/2010 11:51:35
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "INTEG_FATURA_PARAMETRO")
@NamedQueries({
        @NamedQuery(name = "IntegFaturaParametro.findAll", 
                query = "SELECT t FROM IntegFaturaParametro t "
                + "ORDER BY t.empresa.nomeEmpresa ASC, "
                + "t.tipoServico.nomeTipoServico ASC, t.fonteReceita.nomeFonteReceita ASC "),

        @NamedQuery(name = "IntegFaturaParametro.findByFilter", 
                query = "SELECT infp FROM IntegFaturaParametro infp "
                + " JOIN FETCH infp.empresa e "
                + " JOIN FETCH infp.tipoServico t "
                + " JOIN FETCH infp.fonteReceita f "
                + "WHERE ( (infp.empresa.codigoEmpresa = ?) OR (? = 0L) ) "
                + "AND ( (infp.tipoServico.codigoTipoServico = ?) OR (? = 0L) ) "
                + "AND ( (infp.fonteReceita.codigoFonteReceita = ?) OR (? = 0L) ) "
                + "ORDER BY infp.empresa.nomeEmpresa ASC, "
                + "infp.tipoServico.nomeTipoServico ASC, infp.fonteReceita.nomeFonteReceita ASC "),
                
        @NamedQuery(name = "IntegFaturaParametro.findByTpServicoFtReceitaAndEmpresa", 
                query = "SELECT t FROM IntegFaturaParametro t "
                    + " WHERE t.tipoServico.codigoTipoServico = ? " 
                    + " AND t.fonteReceita.codigoFonteReceita = ? " 
                    + " AND t.empresa.codigoEmpresa = ? ")           
})
public class IntegFaturaParametro implements java.io.Serializable, Cloneable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /** Constante para NamedQuery "IntegFaturaParametro.findByFilter". */
    public static final String FIND_BY_FILTER = "IntegFaturaParametro.findByFilter";
    
    
    /** Constante para NamedQuery "IntegFaturaParametro.findByTpServicoFtReceitaAndEmpresa". */
    public static final String FIND_BY_TP_SERVICO_FT_RECEITA_AND_EMPRESA = 
        "IntegFaturaParametro.findByTpServicoFtReceitaAndEmpresa";
    
    /**
     * Realiza uma copia do objeto, porem com uma referencia diferente.
     * 
     * @return a cópia da IntegFaturaParametro
     */
    public IntegFaturaParametro getClone() {
        try {
            return (IntegFaturaParametro) super.clone();
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
            return null;
        }
    }

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "IntegFaturaParametro.findAll".
     */
    public static final String FIND_ALL = "IntegFaturaParametro.findAll";

    /**
     * Atributo gerado a partir da coluna INFP_CD_INTEG_FATURA_PARAM.
     */
    @Id
    @GeneratedValue(generator = "IntegFaturaParametroSeq")
    @SequenceGenerator(name = "IntegFaturaParametroSeq", 
            sequenceName = "SQ_INFP_CD_INTEG_FATURA_PARAM", allocationSize = 1)
    @Column(name = "INFP_CD_INTEG_FATURA_PARAM", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoIntegFaturaParam;

    /**
     * Atributo gerado a partir da coluna TISE_CD_TIPO_SERVICO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TISE_CD_TIPO_SERVICO", nullable = false)
    private TipoServico tipoServico;

    /**
     * Atributo gerado a partir da coluna FORE_CD_FONTE_RECEITA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FORE_CD_FONTE_RECEITA", nullable = false)
    private FonteReceita fonteReceita;

    /**
     * Atributo gerado a partir da coluna EMPR_CD_EMPRESA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EMPR_CD_EMPRESA", nullable = false)
    private Empresa empresa;

    /**
     * Atributo gerado a partir da coluna INFP_CD_ERP_ITEM.
     */

    @Column(name = "INFP_CD_ERP_ITEM", precision = 22, scale = 0)
    private BigDecimal codigoErpItem;

    /**
     * Atributo gerado a partir da coluna INFP_CD_ERP_SERVICO.
     */

    @Column(name = "INFP_CD_ERP_SERVICO", precision = 22, scale = 0)
    private BigDecimal codigoErpServico;

    /**
     * Construtor default.
     */
    public IntegFaturaParametro() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoIntegFaturaParam
     *            Valor do atributo codigoIntegFaturaParam;
     * @param tipoServico
     *            Valor do atributo tipoServico;
     * @param fonteReceita
     *            Valor do atributo fonteReceita;
     * @param empresa
     *            Valor do atributo empresa;
     */
    public IntegFaturaParametro(final Long codigoIntegFaturaParam,
            final TipoServico tipoServico, final FonteReceita fonteReceita,
            final Empresa empresa) {
        this.codigoIntegFaturaParam = codigoIntegFaturaParam;
        this.tipoServico = tipoServico;
        this.fonteReceita = fonteReceita;
        this.empresa = empresa;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoIntegFaturaParam
     *            Valor do atributo codigoIntegFaturaParam;
     * @param tipoServico
     *            Valor do atributo tipoServico;
     * @param fonteReceita
     *            Valor do atributo fonteReceita;
     * @param empresa
     *            Valor do atributo empresa;
     * @param codigoErpItem
     *            Valor do atributo codigoErpItem;
     * @param codigoErpServico
     *            Valor do atributo codigoErpServico;
     */
    public IntegFaturaParametro(final Long codigoIntegFaturaParam,
            final TipoServico tipoServico, final FonteReceita fonteReceita,
            final Empresa empresa, final BigDecimal codigoErpItem,
            final BigDecimal codigoErpServico) {
        this.codigoIntegFaturaParam = codigoIntegFaturaParam;
        this.tipoServico = tipoServico;
        this.fonteReceita = fonteReceita;
        this.empresa = empresa;
        this.codigoErpItem = codigoErpItem;
        this.codigoErpServico = codigoErpServico;
    }

    /**
     * Obtem o valor do atributo codigoIntegFaturaParam.<BR>
     * Atributo gerado a partir da coluna INFP_CD_INTEG_FATURA_PARAM.
     * 
     * @return Valor do atributo codigoIntegFaturaParam.
     */
    public Long getCodigoIntegFaturaParam() {
        return this.codigoIntegFaturaParam;
    }

    /**
     * Atualiza o valor do atributo codigoIntegFaturaParam.<BR>
     * Atributo gerado a partir da coluna INFP_CD_INTEG_FATURA_PARAM.
     * 
     * @param codigoIntegFaturaParam
     *            Novo valor para o atributo codigoIntegFaturaParam.
     */
    public void setCodigoIntegFaturaParam(final Long codigoIntegFaturaParam) {
        this.codigoIntegFaturaParam = codigoIntegFaturaParam;
    }

    /**
     * Obtem o valor do atributo tipoServico.<BR>
     * Atributo gerado a partir da coluna TISE_CD_TIPO_SERVICO.
     * 
     * @return Valor do atributo tipoServico.
     */
    public TipoServico getTipoServico() {
        return this.tipoServico;
    }

    /**
     * Atualiza o valor do atributo tipoServico.<BR>
     * Atributo gerado a partir da coluna TISE_CD_TIPO_SERVICO.
     * 
     * @param tipoServico
     *            Novo valor para o atributo tipoServico.
     */
    public void setTipoServico(final TipoServico tipoServico) {
        this.tipoServico = tipoServico;
    }

    /**
     * Obtem o valor do atributo fonteReceita.<BR>
     * Atributo gerado a partir da coluna FORE_CD_FONTE_RECEITA.
     * 
     * @return Valor do atributo fonteReceita.
     */
    public FonteReceita getFonteReceita() {
        return this.fonteReceita;
    }

    /**
     * Atualiza o valor do atributo fonteReceita.<BR>
     * Atributo gerado a partir da coluna FORE_CD_FONTE_RECEITA.
     * 
     * @param fonteReceita
     *            Novo valor para o atributo fonteReceita.
     */
    public void setFonteReceita(final FonteReceita fonteReceita) {
        this.fonteReceita = fonteReceita;
    }

    /**
     * Obtem o valor do atributo empresa.<BR>
     * Atributo gerado a partir da coluna EMPR_CD_EMPRESA.
     * 
     * @return Valor do atributo empresa.
     */
    public Empresa getEmpresa() {
        return this.empresa;
    }

    /**
     * Atualiza o valor do atributo empresa.<BR>
     * Atributo gerado a partir da coluna EMPR_CD_EMPRESA.
     * 
     * @param empresa
     *            Novo valor para o atributo empresa.
     */
    public void setEmpresa(final Empresa empresa) {
        this.empresa = empresa;
    }

    /**
     * Obtem o valor do atributo codigoErpItem.<BR>
     * Atributo gerado a partir da coluna INFP_CD_ERP_ITEM.
     * 
     * @return Valor do atributo codigoErpItem.
     */
    public BigDecimal getCodigoErpItem() {
        return this.codigoErpItem;
    }

    /**
     * Atualiza o valor do atributo codigoErpItem.<BR>
     * Atributo gerado a partir da coluna INFP_CD_ERP_ITEM.
     * 
     * @param codigoErpItem
     *            Novo valor para o atributo codigoErpItem.
     */
    public void setCodigoErpItem(final BigDecimal codigoErpItem) {
        this.codigoErpItem = codigoErpItem;
    }

    /**
     * Obtem o valor do atributo codigoErpServico.<BR>
     * Atributo gerado a partir da coluna INFP_CD_ERP_SERVICO.
     * 
     * @return Valor do atributo codigoErpServico.
     */
    public BigDecimal getCodigoErpServico() {
        return this.codigoErpServico;
    }

    /**
     * Atualiza o valor do atributo codigoErpServico.<BR>
     * Atributo gerado a partir da coluna INFP_CD_ERP_SERVICO.
     * 
     * @param codigoErpServico
     *            Novo valor para o atributo codigoErpServico.
     */
    public void setCodigoErpServico(final BigDecimal codigoErpServico) {
        this.codigoErpServico = codigoErpServico;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna o objeto em formato de String.
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoIntegFaturaParam").append("='").append(
                getCodigoIntegFaturaParam()).append("' ");
        buffer.append("tipoServico").append("='").append(getTipoServico())
                .append("' ");
        buffer.append("fonteReceita").append("='").append(getFonteReceita())
                .append("' ");
        buffer.append("empresa").append("='").append(getEmpresa()).append("' ");
        buffer.append("codigoErpItem").append("='").append(getCodigoErpItem())
                .append("' ");
        buffer.append("codigoErpServico").append("='").append(
                getCodigoErpServico()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}