/*
 * @(#) ItemTabelaPreco.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;

import java.math.BigDecimal;

import javax.persistence.*;

/**
 * Entity gerado a partir da tabela ITEM_TABELA_PRECO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 12/08/2009 17:14:06
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "ITEM_TABELA_PRECO")
@SqlResultSetMappings(@SqlResultSetMapping(name = "scalarItemTabelaPreco"))
@Audited
@AuditTable(value = "ITEM_TABELA_PRECO_AUD")
@NamedNativeQueries({
		@NamedNativeQuery(name = "ItemTabelaPreco.findAllocationByPerfilVendidoAndTabelaPreco", query = "select count(1) from pms20.item_tabela_preco itp \n" +
				"inner join pms20.alocacao a on a.peve_cd_perfil_vendido = itp.peve_cd_perfil_vendido\n" +
				"inner join pms20.alocacao_periodo ap on a.aloc_cd_alocacao = ap.aloc_cd_alocacao " +
				"inner join pms20.tabela_preco tp on tp.tapr_cd_tabela_preco = itp.tapr_cd_tabela_preco \n" +
				"where itp.tapr_cd_tabela_preco = :codigoTabelaPreco \n" +
				"and itp.peve_cd_perfil_vendido = :codigoPerfilVendido \n" +
				"and ap.alpe_dt_alocacao_periodo between tp.tapr_dt_inicio_vigencia and nvl(tp.tapr_dt_fim_vigencia, trunc(sysdate + 3600,'MM')) \n" +
				"and ap.alpe_pr_alocacao_periodo > 0 \n",resultSetMapping = "scalarItemTabelaPreco")
})
@NamedQueries({

		@NamedQuery(name = "ItemTabelaPreco.findAll", query = "SELECT t FROM ItemTabelaPreco t"
				+ " ORDER BY t.codigoItemTbPreco ASC "),

		@NamedQuery(name = "ItemTabelaPreco.findByTabelaPreco", query = "SELECT itp FROM ItemTabelaPreco itp"
				+ " WHERE itp.tabelaPreco.codigoTabelaPreco = ? "
				+ " ORDER BY itp.codigoItemTbPreco ASC "),

		@NamedQuery(name = "ItemTabelaPreco.findByPerfilVendido", query = "SELECT itp FROM ItemTabelaPreco itp"
				+ " WHERE itp.perfilVendido.codigoPerfilVendido = ? "
				+ " ORDER BY itp.perfilVendido.nomePerfilVendido ASC "),

		@NamedQuery(name = "ItemTabelaPreco.findByMsaAndPerfil", query = "SELECT itp FROM ItemTabelaPreco itp "
				+ "LEFT JOIN FETCH itp.tabelaPreco tp "
				+ "LEFT JOIN FETCH tp.msa msa "
				+ " WHERE msa.codigoMsa = ? "
				+ " AND tp.priceTableStatus.code = 4 "
				+ " AND itp.perfilVendido.codigoPerfilVendido = ? "
				+ " AND TRUNC(tp.dataInicioVigencia) <= TRUNC(?) "
				+ " AND (TRUNC(tp.dataFimVigencia) >= TRUNC(?)"
				+ "     OR tp.dataFimVigencia is null)"),

		@NamedQuery(name = "ItemTabelaPreco.findByTabelaPrecoAndPerfil", query = "SELECT itp FROM ItemTabelaPreco itp"
				+ " WHERE itp.tabelaPreco.codigoTabelaPreco = ? "
				+ " AND itp.perfilVendido.codigoPerfilVendido = ? "
				+ " ORDER BY itp.codigoItemTbPreco ASC "),

		@NamedQuery(name = "ItemTabelaPreco.findByPerfilAndMoeda", query = "SELECT itp FROM ItemTabelaPreco itp "
				+ "LEFT JOIN FETCH itp.tabelaPreco tp "
				+ " WHERE itp.perfilVendido.codigoPerfilVendido = :codigoPerfilVendido "
				+ " AND tp.moeda.codigoMoeda = :codigoMoeda "
				+ " AND TRUNC(tp.dataInicioVigencia) <= TRUNC(sysdate) "
				+ " AND (TRUNC(tp.dataFimVigencia) >= TRUNC(sysdate)"
				+ "     OR tp.dataFimVigencia is null)")
})
public class ItemTabelaPreco implements java.io.Serializable {

	// ========================================================================
	// BEGIN - Coloque aqui o codigo manual
	// ========================================================================

	/** Constante para NamedQuery "ItemTabelaPreco.findByTabelaPreco". */
	public static final String FIND_BY_TABELA_PRECO = "ItemTabelaPreco.findByTabelaPreco";

	/** Constante para NamedQuery "ItemTabelaPreco.findByTabelaPrecoAndPerfil". */
	public static final String FIND_BY_TABELA_PRECO_AND_PERFIL = "ItemTabelaPreco.findByTabelaPrecoAndPerfil";

	/**
	 * Constante para NamedQuery
	 * "ItemTabelaPreco.findByContratoPraticaAndPerfil".
	 */
	public static final String FIND_BY_MSA_AND_PERFIL = "ItemTabelaPreco.findByMsaAndPerfil";

	/** Constante para NamedQuery "ItemTabelaPreco.findByPerfilVendido". */
	public static final String FIND_BY_PERFIL_VENDIDO = "ItemTabelaPreco.findByPerfilVendido";

	public static final String FIND_ALLOCATION_BY_PERFIL_VENDIDO_AND_TABELA_PRECO = "ItemTabelaPreco.findAllocationByPerfilVendidoAndTabelaPreco";

	/** Constante para NamedQuery "ItemTabelaPreco.findByPerfilAndMoeda". */
	public static final String FIND_BY_PERFIL_AND_MOEDA = "ItemTabelaPreco.findByPerfilAndMoeda";	

	// ========================================================================
	// END
	// ========================================================================

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "ItemTabelaPreco.findAll".
	 */
	public static final String FIND_ALL = "ItemTabelaPreco.findAll";

	/**
	 * Atributo gerado a partir da coluna ITTP_CD_ITEM_TB_PRECO.
	 */
	@Id
	@GeneratedValue(generator = "ItemTabelaPrecoSeq")
	@SequenceGenerator(name = "ItemTabelaPrecoSeq", sequenceName = "SQ_ITTP_CD_ITEM_TB_PRECO", allocationSize = 1)
	@Column(name = "ITTP_CD_ITEM_TB_PRECO", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoItemTbPreco;

	/**
	 * Atributo gerado a partir da coluna PEVE_CD_PERFIL_VENDIDO.
	 */
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PEVE_CD_PERFIL_VENDIDO", nullable = false)
	private PerfilVendido perfilVendido;

	/**
	 * Atributo gerado a partir da coluna TAPR_CD_TABELA_PRECO.
	 */
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TAPR_CD_TABELA_PRECO", nullable = false)
	private TabelaPreco tabelaPreco;

	/**
	 * Atributo gerado a partir da coluna ITTP_VL_ITEM_TB_PRECO.
	 */
	@Audited
	@Column(name = "ITTP_VL_ITEM_TB_PRECO", precision = 22, scale = 0)
	private BigDecimal valorItemTbPreco;

	/**
	 * Atributo gerado a partir da coluna ITTP_PR_DESPESA.
	 */
	@Audited
	@Column(name = "ITTP_PR_DESPESA", precision = 15, scale = 13)
	private BigDecimal percentualDespesa;



	/**
	 * Atributo gerado a partir da coluna ITTP_IN_APPROVED.
	 */

	@Column(name = "ITTP_IN_APPROVED", length = 1)
	private String indicadorApproved;


	/**
	 * Atributo Transiente para valor da despesa.
	 */
	@Transient
	private BigDecimal valorDespesa;

	/**
	 * Construtor default.
	 */
	public ItemTabelaPreco() {
	}

	/**
	 * Obtem o valor do atributo codigoItemTbPreco.<BR>
	 * Atributo gerado a partir da coluna ITTP_CD_ITEM_TB_PRECO.
	 * 
	 * @return Valor do atributo codigoItemTbPreco.
	 */
	public Long getCodigoItemTbPreco() {
		return this.codigoItemTbPreco;
	}

	/**
	 * Atualiza o valor do atributo codigoItemTbPreco.<BR>
	 * Atributo gerado a partir da coluna ITTP_CD_ITEM_TB_PRECO.
	 * 
	 * @param codigoItemTbPreco
	 *            Novo valor para o atributo codigoItemTbPreco.
	 */
	public void setCodigoItemTbPreco(final Long codigoItemTbPreco) {
		this.codigoItemTbPreco = codigoItemTbPreco;
	}

	/**
	 * Obtem o valor do atributo perfilVendido.<BR>
	 * Atributo gerado a partir da coluna PEVE_CD_PERFIL_VENDIDO.
	 * 
	 * @return Valor do atributo perfilVendido.
	 */
	public PerfilVendido getPerfilVendido() {
		return this.perfilVendido;
	}

	/**
	 * Atualiza o valor do atributo perfilVendido.<BR>
	 * Atributo gerado a partir da coluna PEVE_CD_PERFIL_VENDIDO.
	 * 
	 * @param perfilVendido
	 *            Novo valor para o atributo perfilVendido.
	 */
	public void setPerfilVendido(final PerfilVendido perfilVendido) {
		this.perfilVendido = perfilVendido;
	}

	/**
	 * Obtem o valor do atributo tabelaPreco.<BR>
	 * Atributo gerado a partir da coluna TAPR_CD_TABELA_PRECO.
	 * 
	 * @return Valor do atributo tabelaPreco.
	 */
	public TabelaPreco getTabelaPreco() {
		return this.tabelaPreco;
	}

	/**
	 * Atualiza o valor do atributo tabelaPreco.<BR>
	 * Atributo gerado a partir da coluna TAPR_CD_TABELA_PRECO.
	 * 
	 * @param tabelaPreco
	 *            Novo valor para o atributo tabelaPreco.
	 */
	public void setTabelaPreco(final TabelaPreco tabelaPreco) {
		this.tabelaPreco = tabelaPreco;
	}

	/**
	 * Obtem o valor do atributo valorItemTbPreco.<BR>
	 * Atributo gerado a partir da coluna ITTP_VL_ITEM_TB_PRECO.
	 * 
	 * @return Valor do atributo valorItemTbPreco.
	 */
	public BigDecimal getValorItemTbPreco() {
		return this.valorItemTbPreco;
	}

	/**
	 * Atualiza o valor do atributo valorItemTbPreco.<BR>
	 * Atributo gerado a partir da coluna ITTP_VL_ITEM_TB_PRECO.
	 * 
	 * @param valorItemTbPreco
	 *            Novo valor para o atributo valorItemTbPreco.
	 */
	public void setValorItemTbPreco(final BigDecimal valorItemTbPreco) {
		this.valorItemTbPreco = valorItemTbPreco;
	}

	/**
	 * Obtem o valor do atributo percentualDespesa.<BR>
	 * Atributo gerado a partir da coluna ITTP_PR_DESPESA.
	 * 
	 * @return the percentualDespesa
	 */
	public BigDecimal getPercentualDespesa() {
		return percentualDespesa == null ? BigDecimal.ZERO : percentualDespesa;
	}

	/**
	 * Atualiza o valor do atributo percentualDespesa.<BR>
	 * Atributo gerado a partir da coluna ITTP_PR_DESPESA.
	 * 
	 * @param percentualDespesa
	 *            the percentualDespesa to set
	 */
	public void setPercentualDespesa(final BigDecimal percentualDespesa) {
		this.percentualDespesa = percentualDespesa;
	}

	/**
	 * Obtem o valor do atributo valorDespesa.<BR>
	 * 
	 * @return the valorDespesa
	 */
	public BigDecimal getValorDespesa() {
		return valorDespesa;
	}

	/**
	 * Obtem o valor do atributo indicadorApproved.<BR>
	 *
	 * @return the indicadorApproved
	 */
	public String getIndicadorApproved() {
		return indicadorApproved;
	}

	/**
	 * Atualiza o valor do atributo indicadorApproved.<BR>
	 * Atributo gerado a partir da coluna ITTP_IN_APPROVED.
	 *
	 * @param indicadorApproved
	 *            the indicadorApproved to set
	 */
	public void setIndicadorApproved(String indicadorApproved) {
		this.indicadorApproved = indicadorApproved;
	}

	/**
	 * Atualiza o valor do atributo valorDespesa.<BR>
	 * 
	 * @param valorDespesa
	 *            the valorDespesa to set
	 */
	public void setValorDespesa(final BigDecimal valorDespesa) {
		this.valorDespesa = valorDespesa;
	}

	/**
	 * @see Object#toString()
	 * @return representação String do Objeto
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoItemTbPreco").append("='")
				.append(getCodigoItemTbPreco()).append("' ");
		buffer.append("perfilVendido").append("='").append(getPerfilVendido())
				.append("' ");
		buffer.append("tabelaPreco").append("='").append(getTabelaPreco())
				.append("' ");
		buffer.append("valorItemTbPreco").append("='")
				.append(getValorItemTbPreco()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}