/*
 * @(#) MapaAlocacao.java
 * Copyright (c) 2009 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.ciandt.pms.audit.listener.AuditoriaJpaListener;


/**
 * Entity gerado a partir da tabela MAPA_ALOCACAO. Relacao dos Mapas de Alocacao
 * X Contrato_Pratica X Recurso
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 04/08/2009 09:09:36
 * @version 09/01/19 1.1 10:08:00
 * 
 */
@Entity
@Table(name = "MAPA_ALOCACAO")
@EntityListeners(AuditoriaJpaListener.class)
@NamedQueries({
        @NamedQuery(name = "MapaAlocacao.findAll", query = "SELECT t FROM MapaAlocacao t"),

        @NamedQuery(name = "MapaAlocacao.findAllPublished", query = "SELECT mapa FROM MapaAlocacao mapa"
                + " WHERE mapa.indicadorVersao = 'PB' ORDER BY mapa.textoTitulo"),

        @NamedQuery(name = "MapaAlocacao.findByFilter", query = "SELECT mapa FROM MapaAlocacao mapa "
                + "WHERE (UPPER(mapa.textoTitulo) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + "AND ( (mapa.indicadorVersao = ?) OR (? is null) ) "
                + "AND ( (mapa.contratoPratica.codigoContratoPratica = ?) OR (? = 0L) ) "
                + "ORDER BY mapa.textoTitulo ASC "),

        @NamedQuery(name = "MapaAlocacao.findByLoginTrava", query = "SELECT mapa FROM MapaAlocacao mapa "
                + " WHERE mapa.loginTrava = ? "),

        @NamedQuery(name = "MapaAlocacao.findAllLock", query = "SELECT mapa FROM MapaAlocacao mapa "
                + " WHERE mapa.loginTrava is not null "),

        @NamedQuery(name = "MapaAlocacao.findByContratoPratica", query = "SELECT mapa FROM MapaAlocacao mapa "
                + " WHERE mapa.contratoPratica.codigoContratoPratica = ?"
                + " AND mapa.indicadorVersao = 'PB' "),

        @NamedQuery(name = "MapaAlocacao.findByFilterFetch", query = "SELECT distinct mapa FROM MapaAlocacao mapa "
                + " LEFT JOIN FETCH mapa.contratoPratica cp "
                + " LEFT JOIN cp.contratoPraticaCentroLucros contratoPraticaCL "
                + "WHERE (UPPER(mapa.textoTitulo) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + "AND ( (mapa.indicadorVersao = ?) OR (? is null) ) "
                + "AND ( (mapa.contratoPratica.codigoContratoPratica = ?) OR (? = 0L) ) "
                + "AND ( (mapa.contratoPratica.msa.codigoMsa = ?) OR (? = 0L) ) "
                + "AND ( (mapa.contratoPratica.msa.cliente.codigoCliente = ?) OR (? = 0L) ) "
                + "AND ( (contratoPraticaCL.centroLucro.codigoCentroLucro = ?) OR (? = 0L) ) "
                + "AND ( (contratoPraticaCL.centroLucro.naturezaCentroLucro.codigoNatureza = ?) OR (? = 0L) ) "
                + " AND (contratoPraticaCL.dataFimVigencia IS NULL) "
                + "ORDER BY mapa.textoTitulo ASC "),

        @NamedQuery(name = "MapaAlocacao.findByFilterFetchFollowingOnly", query = "SELECT distinct mapa FROM MapaAlocacao mapa "
                + " JOIN mapa.mapaAlocacaoPessoas mapaAlocPess "
                + " LEFT JOIN FETCH mapa.contratoPratica cp "
                + " LEFT JOIN cp.contratoPraticaCentroLucros contratoPraticaCL "
                + "WHERE (UPPER(mapa.textoTitulo) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + "AND ( (mapa.indicadorVersao = ?) OR (? is null) ) "
                + "AND ( (mapa.contratoPratica.codigoContratoPratica = ?) OR (? = 0L) ) "
                + "AND ( (mapa.contratoPratica.msa.codigoMsa = ?) OR (? = 0L) ) "
                + "AND ( (mapa.contratoPratica.msa.cliente.codigoCliente = ?) OR (? = 0L) ) "
                + "AND ( (contratoPraticaCL.centroLucro.codigoCentroLucro = ?) OR (? = 0L) ) "
                + "AND ( (contratoPraticaCL.centroLucro.naturezaCentroLucro.codigoNatureza = ?) OR (? = 0L) ) "
                + " AND (mapaAlocPess.pessoa.codigoPessoa = ?) "
                + " AND (contratoPraticaCL.dataFimVigencia IS NULL) "
                + "ORDER BY mapa.textoTitulo ASC "),

        @NamedQuery(name = "MapaAlocacao.findByFilterReview", query = "SELECT distinct mapa FROM MapaAlocacao mapa "
                + " LEFT JOIN FETCH mapa.contratoPratica cp"
                + " LEFT JOIN mapa.alocacaos alocacao "
                + " LEFT JOIN alocacao.alocacaoPeriodos ap "
                + " LEFT JOIN mapa.estratificacaoUrs estratificacaoUrs "
                + " LEFT JOIN cp.contratoPraticaCentroLucros contratoPraticaCL "
                + "WHERE ((mapa.contratoPratica.codigoContratoPratica = ?) OR (? = 0L) ) "
                + " AND ( (mapa.contratoPratica.msa.cliente.codigoCliente = ?) OR (? = 0L) ) "
                + " AND (ap.dataAlocacaoPeriodo = ?) "
                + " AND (mapa.indicadorVersao = ?) "
                + " AND ( (contratoPraticaCL.centroLucro.codigoCentroLucro = ?) OR (? = 0L) ) "
                + " AND ( (contratoPraticaCL.centroLucro.naturezaCentroLucro.codigoNatureza = ?) OR (? = 0L) ) "
                + " AND ( TRUNC(?) BETWEEN TRUNC(contratoPraticaCL.dataInicioVigencia) AND "
                + "                          (CASE WHEN contratoPraticaCL.dataFimVigencia IS NOT NULL "
                + "                             THEN TRUNC(contratoPraticaCL.dataFimVigencia) "
                + "                             ELSE TRUNC(to_date('31/12/9999','dd/mm/yyyy')) "
                + "                           END) ) "
                + "ORDER BY mapa.textoTitulo ASC "),

        @NamedQuery(name = "MapaAlocacao.findByDate", query = "SELECT distinct mapa FROM MapaAlocacao mapa "
                + " LEFT JOIN FETCH mapa.contratoPratica "
                + " LEFT JOIN mapa.alocacaos alocacao "
                + " LEFT JOIN alocacao.alocacaoPeriodos ap "
                + " LEFT JOIN mapa.estratificacaoUrs estratificacaoUrs "
                + " LEFT OUTER JOIN mapa.contratoPratica.centroLucros centroLucro "
                + "WHERE (ap.dataAlocacaoPeriodo = ?) "
                + "AND (mapa.indicadorVersao = ?) "
                + "ORDER BY mapa.textoTitulo ASC "),

        @NamedQuery(name = "MapaAlocacao.findByFilterWithoutRevenue", query = "SELECT distinct mapa FROM MapaAlocacao mapa "
                + " JOIN mapa.contratoPratica cp"
                + " LEFT JOIN cp.contratoPraticaCentroLucros contratoPraticaCL"
                + " JOIN mapa.alocacaos alocacao "
                + " JOIN alocacao.alocacaoPeriodos ap "
                + " WHERE ( mapa.indicadorVersao = 'PB' )"
                + "     AND ( (mapa.contratoPratica.msa.cliente.codigoCliente = ?) OR (? = 0L) ) "
                + "     AND ( (contratoPraticaCL.centroLucro.codigoCentroLucro = ?) OR (? = 0L) ) "
                + "     AND ( (contratoPraticaCL.centroLucro.naturezaCentroLucro.codigoNatureza = ?) OR (? = 0L) ) "
                + "     AND ( (mapa.contratoPratica.pratica.codigoPratica = ?) OR (? = 0L) ) "
                + "     AND ( TRUNC(ap.dataAlocacaoPeriodo) = TRUNC(?) )"
                + "     AND ( ap.percentualAlocacaoPeriodo <> 0.0 )"
                + "     AND ( not exists (SELECT r FROM Receita r WHERE "
                + "                 r.contratoPratica.codigoContratoPratica = cp.codigoContratoPratica "
                + "                 AND TRUNC(r.dataMes) = TRUNC(?) "
                + "					AND r.indicadorVersao != 'FC') )"
                + "     AND ( TRUNC(?) BETWEEN TRUNC(contratoPraticaCL.dataInicioVigencia) AND "
                + "                               (CASE WHEN contratoPraticaCL.dataFimVigencia IS NOT NULL "
                + "                                 THEN TRUNC(contratoPraticaCL.dataFimVigencia) "
                + "                                 ELSE TRUNC(to_date('31/12/9999','dd/mm/yyyy')) "
                + "                               END) ) "),

        @NamedQuery(name = "MapaAlocacao.findAllPBByRangeMonths", query = "SELECT distinct mapa FROM MapaAlocacao mapa "
                + " JOIN FETCH mapa.alocacaos alocacao "
                + " JOIN FETCH alocacao.alocacaoPeriodos ap "
                + " WHERE ( mapa.indicadorVersao = 'PB' ) "
                + "   AND ( TRUNC(ap.dataAlocacaoPeriodo) >= TRUNC(?) ) "
                + " ORDER BY mapa.textoTitulo ASC")

})
public class MapaAlocacao implements java.io.Serializable, Cloneable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /** Constante para NamedQuery "MapaAlocacao.findByFilter". */
    public static final String FIND_BY_FILTER = "MapaAlocacao.findByFilter";

    /** Constante para NamedQuery "MapaAlocacao.findByFilterReview". */
    public static final String FIND_BY_FILTER_REVIEW =
            "MapaAlocacao.findByFilterReview";

    /** Constante para NamedQuery "MapaAlocacao.findByDate". */
    public static final String FIND_BY_DATE = "MapaAlocacao.findByDate";

    /** Constante para NamedQuery "MapaAlocacao.findByFilter". */
    public static final String FIND_BY_FILTER_FETCH =
            "MapaAlocacao.findByFilterFetch";

    /** Constante para NamedQuery "MapaAlocacao.findByFilterFollowingOnly". */
    public static final String FIND_BY_FILTER_FETCH_FOLLOWING_ONLY =
            "MapaAlocacao.findByFilterFetchFollowingOnly";

    /** Constante para NamedQuery "MapaAlocacao.findByLoginTrava". */
    public static final String FIND_BY_LOGIN_TRAVA =
            "MapaAlocacao.findByLoginTrava";

    /** Constante para NamedQuery "MapaAlocacao.findAllLock". */
    public static final String FIND_ALL_LOCK = "MapaAlocacao.findAllLock";

    /** Constante para NamedQuery "MapaAlocacao.findAllPublished". */
    public static final String FIND_ALL_PUBLISHED =
            "MapaAlocacao.findAllPublished";

    /** Constante para NamedQuery "MapaAlocacao.findByContratoPratica". */
    public static final String FIND_BY_CONTRATO_PRATICA =
            "MapaAlocacao.findByContratoPratica";

    /** Constante para NamedQuery "MapaAlocacao.findByFilterWithoutRevenue". */
    public static final String FIND_BY_FILTER_WITHOUT_REVENUE =
            "MapaAlocacao.findByFilterWithoutRevenue";

    /** Constante para NamedQuery "MapaAlocacao.findAllPBByRangeMonths". */
    public static final String FIND_ALL_PB_BY_RANGE_MONTHS =
            "MapaAlocacao.findAllPBByRangeMonths";

    /** Indicador (transiente) se é stratified ou não. */
    @Transient
    private boolean stratified = Boolean.valueOf(false);

    /** Indicador (transiente) se possui undefined. */
    @Transient
    private Boolean hasUndefined = Boolean.valueOf(false);

    /**
     * @return the stratified
     */
    public boolean isStratified() {
        return stratified;
    }

    /**
     * @param stratified
     *            the stratified to set
     */
    public void setStratified(final boolean stratified) {
        this.stratified = stratified;
    }

    /**
     * @return the hasUndefined
     */
    public Boolean getHasUndefined() {
        return hasUndefined;
    }

    /**
     * @param hasUndefined
     *            the hasUndefined to set
     */
    public void setHasUndefined(final Boolean hasUndefined) {
        this.hasUndefined = hasUndefined;
    }

    /** 
     * Lista de Alocacao relacionado com o MapaAlocacao corrente.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mapaAlocacao")
    private List<Alocacao> alocacaos = new ArrayList<Alocacao>(0);

    /**
     * Atributo gerado a partir da tabela MAPA_ALOCACAO_PESSOA.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mapaAlocacao", cascade = CascadeType.ALL)
    private List<MapaAlocacaoPessoa> mapaAlocacaoPessoas =
            new ArrayList<MapaAlocacaoPessoa>(0);
    
    /**
     * Relacionamento um para muitos.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mapaAlocacao", cascade = {CascadeType.ALL})
    @OrderBy("dataMes")
    private List<FatorUrMes> fatorUrMeses = new ArrayList<FatorUrMes>(0);
    
    /**
     * Relacionamento um para muitos.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mapaAlocacao", cascade = {CascadeType.ALL})
    private List<EstratificacaoUr> estratificacaoUrs =
            new ArrayList<EstratificacaoUr>(0);

    /**
     * Realiza uma copia do objeto, porem com uma referencia diferente.
     * 
     * @return a cópia do MapaAlocacao
     */
    public MapaAlocacao getClone() {
        try {
            return (MapaAlocacao) super.clone();
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
            return null;
        }
    }

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "MapaAlocacao.findAll".
     */
    public static final String FIND_ALL = "MapaAlocacao.findAll";

    /**
     * Atributo gerado a partir da coluna MAAL_CD_MAPA_ALOCACAO. Codigo do Mapa
     * de Alocacao
     */
    @Id
    @GeneratedValue(generator = "MapaAlocacaoSeq")
    @SequenceGenerator(name = "MapaAlocacaoSeq", sequenceName = "SQ_MAAL_CD_MAPA_ALOCACAO", allocationSize = 1)
    @Column(name = "MAAL_CD_MAPA_ALOCACAO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoMapaAlocacao;

    /**
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA. Codigo do
     * Contrato_Pratica
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "COPR_CD_CONTRATO_PRATICA")
    private ContratoPratica contratoPratica;

    /**
     * Atributo gerado a partir da coluna MAAL_TX_TITULO.
     */
    @Column(name = "MAAL_TX_TITULO", length = 100)
    private String textoTitulo;

    /**
     * Atributo gerado a partir da coluna MAAL_IN_VERSAO.
     */
    @Column(name = "MAAL_IN_VERSAO", length = 2)
    private String indicadorVersao;

    /**
     * Atributo gerado a partir da coluna MAAL_LOGIN_TRAVA.
     */
    @Column(name = "MAAL_LOGIN_TRAVA", length = 15)
    private String loginTrava;

    /**
     * Atributo gerado a partir da coluna MAAL_DT_TRAVA.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "MAAL_DT_TRAVA", length = 7)
    private Date dataTrava;

    /**
     * Atributo gerado a partir da coluna MAAL_DT_INICIO.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "MAAL_DT_INICIO", length = 7)
    private Date dataInicio;

    /**
     * Atributo gerado a partir da coluna MAAL_DT_FIM.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "MAAL_DT_FIM", length = 7)
    private Date dataFim;

    /**
     * Atributo gerado a partir da coluna MAAL_DT_INICIO_JANELA.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "MAAL_DT_INICIO_JANELA", length = 7)
    private Date dataInicioJanela;    

    /**
     * Construtor default.
     */
    public MapaAlocacao() {
    }
    
    /**
     * @return the alocacaos
     */
    public List<Alocacao> getAlocacaos() {
        return alocacaos;
    }

    /**
     * @param alocacaos the alocacaos to set
     */
    public void setAlocacaos(List<Alocacao> alocacaos) {
        this.alocacaos = alocacaos;
    }

    /**
     * @return the mapaAlocacaoPessoas
     */
    public List<MapaAlocacaoPessoa> getMapaAlocacaoPessoas() {
        return mapaAlocacaoPessoas;
    }

    /**
     * @param mapaAlocacaoPessoas the mapaAlocacaoPessoas to set
     */
    public void setMapaAlocacaoPessoas(List<MapaAlocacaoPessoa> mapaAlocacaoPessoas) {
        this.mapaAlocacaoPessoas = mapaAlocacaoPessoas;
    }

    /**
     * @return the fatorUrMeses
     */
    public List<FatorUrMes> getFatorUrMeses() {
        return fatorUrMeses;
    }

    /**
     * @param fatorUrMeses the fatorUrMeses to set
     */
    public void setFatorUrMeses(List<FatorUrMes> fatorUrMeses) {
        this.fatorUrMeses = fatorUrMeses;
    }

    /**
     * @return the estratificacaoUrs
     */
    public List<EstratificacaoUr> getEstratificacaoUrs() {
        return estratificacaoUrs;
    }

    /**
     * @param estratificacaoUrs the estratificacaoUrs to set
     */
    public void setEstratificacaoUrs(List<EstratificacaoUr> estratificacaoUrs) {
        this.estratificacaoUrs = estratificacaoUrs;
    }

    /**
     * @return the codigoMapaAlocacao
     */
    public Long getCodigoMapaAlocacao() {
        return codigoMapaAlocacao;
    }

    /**
     * @param codigoMapaAlocacao the codigoMapaAlocacao to set
     */
    public void setCodigoMapaAlocacao(Long codigoMapaAlocacao) {
        this.codigoMapaAlocacao = codigoMapaAlocacao;
    }

    /**
     * @return the contratoPratica
     */
    public ContratoPratica getContratoPratica() {
        return contratoPratica;
    }

    /**
     * @param contratoPratica the contratoPratica to set
     */
    public void setContratoPratica(ContratoPratica contratoPratica) {
        this.contratoPratica = contratoPratica;
    }

    /**
     * @return the textoTitulo
     */
    public String getTextoTitulo() {
        return textoTitulo;
    }

    /**
     * @param textoTitulo the textoTitulo to set
     */
    public void setTextoTitulo(String textoTitulo) {
        this.textoTitulo = textoTitulo;
    }

    /**
     * @return the indicadorVersao
     */
    public String getIndicadorVersao() {
        return indicadorVersao;
    }

    /**
     * @param indicadorVersao the indicadorVersao to set
     */
    public void setIndicadorVersao(String indicadorVersao) {
        this.indicadorVersao = indicadorVersao;
    }

    /**
     * @return the loginTrava
     */
    public String getLoginTrava() {
        return loginTrava;
    }

    /**
     * @param loginTrava the loginTrava to set
     */
    public void setLoginTrava(String loginTrava) {
        this.loginTrava = loginTrava;
    }

    /**
     * @return the dataTrava
     */
    public Date getDataTrava() {
        return dataTrava;
    }

    /**
     * @param dataTrava the dataTrava to set
     */
    public void setDataTrava(Date dataTrava) {
        this.dataTrava = dataTrava;
    }

    /**
     * @return the dataInicio
     */
    public Date getDataInicio() {
        return dataInicio;
    }

    /**
     * @param dataInicio the dataInicio to set
     */
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    /**
     * @return the dataFim
     */
    public Date getDataFim() {
        return dataFim;
    }

    /**
     * @param dataFim the dataFim to set
     */
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }

    /**
     * @return the dataInicioJanela
     */
    public Date getDataInicioJanela() {
        return dataInicioJanela;
    }

    /**
     * @param dataInicioJanela the dataInicioJanela to set
     */
    public void setDataInicioJanela(Date dataInicioJanela) {
        this.dataInicioJanela = dataInicioJanela;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@")
                .append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoMapaAlocacao").append("='")
                .append(getCodigoMapaAlocacao()).append("' ");
        buffer.append("contratoPratica").append("='")
                .append(getContratoPratica()).append("' ");
        buffer.append("textoTitulo").append("='").append(getTextoTitulo())
                .append("' ");
        buffer.append("indicadorVersao").append("='")
                .append(getIndicadorVersao()).append("' ");
        buffer.append("loginTrava").append("='").append(getLoginTrava())
                .append("' ");
        buffer.append("dataTrava").append("='").append(getDataTrava())
                .append("' ");
        buffer.append("dataInicio").append("='").append(getDataInicio())
                .append("' ");
        buffer.append("dataFim").append("='").append(getDataFim()).append("' ");
        buffer.append("dataInicioJanela").append("='")
                .append(getDataInicioJanela()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}