/*
 * @(#) MapaAlocacaoFoto.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedNativeQueries;
import javax.persistence.NamedNativeQuery;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.QueryHint;
import javax.persistence.SequenceGenerator;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela MAPA_ALOCACAO_FOTO.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 17/02/2011 17:51:17
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "MAPA_ALOCACAO_FOTO")
@SqlResultSetMappings(
        @SqlResultSetMapping (name = "scalarMapaAlocacaoFoto")
)

@NamedNativeQueries(
    @NamedNativeQuery(
            name = "MapaAlocacaoFoto.updateStatusFotos",
            query = "{ ? = call pms20.ufc_pms_atualiza_tabelas_foto }",
            hints = { @QueryHint(name = "org.hibernate.callable", value = "true") },
            resultClass = Integer.class,
            resultSetMapping = "scalarMapaAlocacaoFoto"
    )
)

@NamedQueries({
    @NamedQuery(name = "MapaAlocacaoFoto.findAll", query = "SELECT t FROM MapaAlocacaoFoto t")
})
public class MapaAlocacaoFoto implements java.io.Serializable {
    
    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    
    /** Constante para NamedQuery "MapaAlocacaoFoto.updateStatusFotos". */
    public static final String UPDATE_STATUS_FOTOS = "MapaAlocacaoFoto.updateStatusFotos";
    
    /** Lista de Alocacao relacionado com o MapaAlocacaoFoto corrente. */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mapaAlocacaoFoto", cascade = CascadeType.ALL)
    private List<AlocacaoFoto> alocacaoFotos = new ArrayList<AlocacaoFoto>(0);
    
    /**
     * Obtem o valor do atributo alocacaoFotos.<BR>

     * @return Valor do atributo alocacaoFotos.
     */
    public List<AlocacaoFoto> getAlocacaoFotos() {
        return this.alocacaoFotos;
    }

    /**
     * Atualiza o valor do atributo alocacaoFotos.<BR>

     * @param alocacaoFotos Novo valor para o atributo alocacaoFotos.
     */
    public void setAlocacaoFotos(final List<AlocacaoFoto> alocacaoFotos) {
        this.alocacaoFotos = alocacaoFotos;
    }
    
    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "MapaAlocacaoFoto.findAll".
     */
    public static final String FIND_ALL = "MapaAlocacaoFoto.findAll";

    /**
     * Atributo gerado a partir da coluna MAAF_CD_MAPA_ALOC_FOTO.
     */
    @Id
    @GeneratedValue(generator = "MapaAlocacaoFotoSeq")
    @SequenceGenerator(name = "MapaAlocacaoFotoSeq", 
            sequenceName = "SQ_MAAF_CD_MAPA_ALOC_FOTO", allocationSize = 1)
    @Column(name = "MAAF_CD_MAPA_ALOC_FOTO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoMapaAlocFoto;

    /**
     * Atributo gerado a partir da coluna MAAF_IN_STATUS_FOTO.
     */

    @Column(name = "MAAF_IN_STATUS_FOTO", length = 2)
    private String indicadorStatusFoto;

    /**
     * Atributo gerado a partir da coluna MAAF_CD_MAPA_ALOCACAO.
     */

    @Column(name = "MAAF_CD_MAPA_ALOCACAO", precision = 18, scale = 0)
    private Long codigoMapaAlocacao;

    /**
     * Atributo gerado a partir da coluna MAAF_CD_CONTRATO_PRATICA.
     */

    @Column(name = "MAAF_CD_CONTRATO_PRATICA", precision = 18, scale = 0)
    private Long codigoContratoPratica;

    /**
     * Atributo gerado a partir da coluna MAAF_TX_TITULO.
     */

    @Column(name = "MAAF_TX_TITULO", length = 100)
    private String textoTitulo;

    /**
     * Atributo gerado a partir da coluna MAAF_IN_VERSAO.
     */

    @Column(name = "MAAF_IN_VERSAO", length = 2)
    private String indicadorVersao;

    /**
     * Atributo gerado a partir da coluna MAAF_LOGIN_TRAVA.
     */

    @Column(name = "MAAF_LOGIN_TRAVA", length = 15)
    private String loginTrava;

    /**
     * Atributo gerado a partir da coluna MAAF_DT_TRAVA.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "MAAF_DT_TRAVA", length = 7)
    private Date dataTrava;

    /**
     * Atributo gerado a partir da coluna MAAF_DT_INICIO.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "MAAF_DT_INICIO", length = 7)
    private Date dataInicio;

    /**
     * Atributo gerado a partir da coluna MAAF_DT_FIM.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "MAAF_DT_FIM", length = 7)
    private Date dataFim;

    /**
     * Atributo gerado a partir da coluna MAAF_DT_INICIO_JANELA.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "MAAF_DT_INICIO_JANELA", length = 7)
    private Date dataInicioJanela;

    /**
     * Construtor default.
     */
    public MapaAlocacaoFoto() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoMapaAlocFoto Valor do atributo codigoMapaAlocFoto;
     */
    public MapaAlocacaoFoto(final Long codigoMapaAlocFoto) {
        this.codigoMapaAlocFoto = codigoMapaAlocFoto;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoMapaAlocFoto Valor do atributo codigoMapaAlocFoto;
     * @param indicadorStatusFoto Valor do atributo indicadorStatusFoto;
     * @param codigoMapaAlocacao Valor do atributo codigoMapaAlocacao;
     * @param codigoContratoPratica Valor do atributo codigoContratoPratica;
     * @param textoTitulo Valor do atributo textoTitulo;
     * @param indicadorVersao Valor do atributo indicadorVersao;
     * @param loginTrava Valor do atributo loginTrava;
     * @param dataTrava Valor do atributo dataTrava;
     * @param dataInicio Valor do atributo dataInicio;
     * @param dataFim Valor do atributo dataFim;
     * @param dataInicioJanela Valor do atributo dataInicioJanela;
     * @param alocacaoFotos Valor do atributo alocacaoFotos;
     */
    public MapaAlocacaoFoto(final Long codigoMapaAlocFoto,
            final String indicadorStatusFoto, final Long codigoMapaAlocacao,
            final Long codigoContratoPratica, final String textoTitulo,
            final String indicadorVersao, final String loginTrava, final Date dataTrava,
            final Date dataInicio, final Date dataFim, final Date dataInicioJanela,
            final List<AlocacaoFoto> alocacaoFotos) {
        this.codigoMapaAlocFoto = codigoMapaAlocFoto;
        this.indicadorStatusFoto = indicadorStatusFoto;
        this.codigoMapaAlocacao = codigoMapaAlocacao;
        this.codigoContratoPratica = codigoContratoPratica;
        this.textoTitulo = textoTitulo;
        this.indicadorVersao = indicadorVersao;
        this.loginTrava = loginTrava;
        this.dataTrava = dataTrava;
        this.dataInicio = dataInicio;
        this.dataFim = dataFim;
        this.dataInicioJanela = dataInicioJanela;
        this.alocacaoFotos = alocacaoFotos;
    }

    /**
     * Obtem o valor do atributo codigoMapaAlocFoto.<BR>
     * Atributo gerado a partir da coluna MAAF_CD_MAPA_ALOC_FOTO.
     * @return Valor do atributo codigoMapaAlocFoto.
     */
    public Long getCodigoMapaAlocFoto() {
        return this.codigoMapaAlocFoto;
    }

    /**
     * Atualiza o valor do atributo codigoMapaAlocFoto.<BR>
     * Atributo gerado a partir da coluna MAAF_CD_MAPA_ALOC_FOTO.
     * @param codigoMapaAlocFoto Novo valor para o atributo codigoMapaAlocFoto.
     */
    public void setCodigoMapaAlocFoto(final Long codigoMapaAlocFoto) {
        this.codigoMapaAlocFoto = codigoMapaAlocFoto;
    }

    /**
     * Obtem o valor do atributo indicadorStatusFoto.<BR>
     * Atributo gerado a partir da coluna MAAF_IN_STATUS_FOTO.
     * @return Valor do atributo indicadorStatusFoto.
     */
    public String getIndicadorStatusFoto() {
        return this.indicadorStatusFoto;
    }

    /**
     * Atualiza o valor do atributo indicadorStatusFoto.<BR>
     * Atributo gerado a partir da coluna MAAF_IN_STATUS_FOTO.
     * @param indicadorStatusFoto Novo valor para o atributo indicadorStatusFoto.
     */
    public void setIndicadorStatusFoto(final String indicadorStatusFoto) {
        this.indicadorStatusFoto = indicadorStatusFoto;
    }

    /**
     * Obtem o valor do atributo codigoMapaAlocacao.<BR>
     * Atributo gerado a partir da coluna MAAF_CD_MAPA_ALOCACAO.
     * @return Valor do atributo codigoMapaAlocacao.
     */
    public Long getCodigoMapaAlocacao() {
        return this.codigoMapaAlocacao;
    }

    /**
     * Atualiza o valor do atributo codigoMapaAlocacao.<BR>
     * Atributo gerado a partir da coluna MAAF_CD_MAPA_ALOCACAO.
     * @param codigoMapaAlocacao Novo valor para o atributo codigoMapaAlocacao.
     */
    public void setCodigoMapaAlocacao(final Long codigoMapaAlocacao) {
        this.codigoMapaAlocacao = codigoMapaAlocacao;
    }

    /**
     * Obtem o valor do atributo codigoContratoPratica.<BR>
     * Atributo gerado a partir da coluna MAAF_CD_CONTRATO_PRATICA.
     * @return Valor do atributo codigoContratoPratica.
     */
    public Long getCodigoContratoPratica() {
        return this.codigoContratoPratica;
    }

    /**
     * Atualiza o valor do atributo codigoContratoPratica.<BR>
     * Atributo gerado a partir da coluna MAAF_CD_CONTRATO_PRATICA.
     * @param codigoContratoPratica Novo valor para o atributo codigoContratoPratica.
     */
    public void setCodigoContratoPratica(final Long codigoContratoPratica) {
        this.codigoContratoPratica = codigoContratoPratica;
    }

    /**
     * Obtem o valor do atributo textoTitulo.<BR>
     * Atributo gerado a partir da coluna MAAF_TX_TITULO.
     * @return Valor do atributo textoTitulo.
     */
    public String getTextoTitulo() {
        return this.textoTitulo;
    }

    /**
     * Atualiza o valor do atributo textoTitulo.<BR>
     * Atributo gerado a partir da coluna MAAF_TX_TITULO.
     * @param textoTitulo Novo valor para o atributo textoTitulo.
     */
    public void setTextoTitulo(final String textoTitulo) {
        this.textoTitulo = textoTitulo;
    }

    /**
     * Obtem o valor do atributo indicadorVersao.<BR>
     * Atributo gerado a partir da coluna MAAF_IN_VERSAO.
     * @return Valor do atributo indicadorVersao.
     */
    public String getIndicadorVersao() {
        return this.indicadorVersao;
    }

    /**
     * Atualiza o valor do atributo indicadorVersao.<BR>
     * Atributo gerado a partir da coluna MAAF_IN_VERSAO.
     * @param indicadorVersao Novo valor para o atributo indicadorVersao.
     */
    public void setIndicadorVersao(final String indicadorVersao) {
        this.indicadorVersao = indicadorVersao;
    }

    /**
     * Obtem o valor do atributo loginTrava.<BR>
     * Atributo gerado a partir da coluna MAAF_LOGIN_TRAVA.
     * @return Valor do atributo loginTrava.
     */
    public String getLoginTrava() {
        return this.loginTrava;
    }

    /**
     * Atualiza o valor do atributo loginTrava.<BR>
     * Atributo gerado a partir da coluna MAAF_LOGIN_TRAVA.
     * @param loginTrava Novo valor para o atributo loginTrava.
     */
    public void setLoginTrava(final String loginTrava) {
        this.loginTrava = loginTrava;
    }

    /**
     * Obtem o valor do atributo dataTrava.<BR>
     * Atributo gerado a partir da coluna MAAF_DT_TRAVA.
     * @return Valor do atributo dataTrava.
     */
    public Date getDataTrava() {
        return this.dataTrava;
    }

    /**
     * Atualiza o valor do atributo dataTrava.<BR>
     * Atributo gerado a partir da coluna MAAF_DT_TRAVA.
     * @param dataTrava Novo valor para o atributo dataTrava.
     */
    public void setDataTrava(final Date dataTrava) {
        this.dataTrava = dataTrava;
    }

    /**
     * Obtem o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna MAAF_DT_INICIO.
     * @return Valor do atributo dataInicio.
     */
    public Date getDataInicio() {
        return this.dataInicio;
    }

    /**
     * Atualiza o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna MAAF_DT_INICIO.
     * @param dataInicio Novo valor para o atributo dataInicio.
     */
    public void setDataInicio(final Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    /**
     * Obtem o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna MAAF_DT_FIM.
     * @return Valor do atributo dataFim.
     */
    public Date getDataFim() {
        return this.dataFim;
    }

    /**
     * Atualiza o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna MAAF_DT_FIM.
     * @param dataFim Novo valor para o atributo dataFim.
     */
    public void setDataFim(final Date dataFim) {
        this.dataFim = dataFim;
    }

    /**
     * Obtem o valor do atributo dataInicioJanela.<BR>
     * Atributo gerado a partir da coluna MAAF_DT_INICIO_JANELA.
     * @return Valor do atributo dataInicioJanela.
     */
    public Date getDataInicioJanela() {
        return this.dataInicioJanela;
    }

    /**
     * Atualiza o valor do atributo dataInicioJanela.<BR>
     * Atributo gerado a partir da coluna MAAF_DT_INICIO_JANELA.
     * @param dataInicioJanela Novo valor para o atributo dataInicioJanela.
     */
    public void setDataInicioJanela(final Date dataInicioJanela) {
        this.dataInicioJanela = dataInicioJanela;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoMapaAlocFoto").append("='").append(
                getCodigoMapaAlocFoto()).append("' ");
        buffer.append("indicadorStatusFoto").append("='").append(
                getIndicadorStatusFoto()).append("' ");
        buffer.append("codigoMapaAlocacao").append("='").append(
                getCodigoMapaAlocacao()).append("' ");
        buffer.append("codigoContratoPratica").append("='").append(
                getCodigoContratoPratica()).append("' ");
        buffer.append("textoTitulo").append("='").append(getTextoTitulo())
                .append("' ");
        buffer.append("indicadorVersao").append("='").append(
                getIndicadorVersao()).append("' ");
        buffer.append("loginTrava").append("='").append(getLoginTrava())
                .append("' ");
        buffer.append("dataTrava").append("='").append(getDataTrava()).append(
                "' ");
        buffer.append("dataInicio").append("='").append(getDataInicio())
                .append("' ");
        buffer.append("dataFim").append("='").append(getDataFim()).append("' ");
        buffer.append("dataInicioJanela").append("='").append(
                getDataInicioJanela()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}