/*
 * @(#) MapaAlocacaoPessoa.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela MAPA_ALOCACAO_PESSOA.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 17/02/2011 14:17:22
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "MAPA_ALOCACAO_PESSOA")
@NamedQueries({
        @NamedQuery(name = "MapaAlocacaoPessoa.findAll", query = "SELECT t FROM MapaAlocacaoPessoa t"),

        @NamedQuery(name = "MapaAlocacaoPessoa.findByMapaAlocAndPessoa", 
                query = "SELECT maap FROM MapaAlocacaoPessoa maap "
                + " WHERE maap.mapaAlocacao.codigoMapaAlocacao = ?"
                + " AND maap.pessoa.codigoPessoa = ?"),

        @NamedQuery(name = "MapaAlocacaoPessoa.findByMapaAloc", query = "SELECT maap FROM MapaAlocacaoPessoa maap "
                + " WHERE maap.mapaAlocacao.codigoMapaAlocacao = ?"),

        @NamedQuery(name = "MapaAlocacaoPessoa.findByCodigoMD5", 
                query = "SELECT maap FROM MapaAlocacaoPessoa maap "
                + " WHERE maap.codigoMD5 = ?") 
                })
public class MapaAlocacaoPessoa implements java.io.Serializable, Cloneable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /** Constante para NamedQuery "MapaAlocacaoPessoa.findByMapaAlocAndPessoa". */
    public static final String FIND_BY_MAPA_ALOC_AND_PESSOA = "MapaAlocacaoPessoa.findByMapaAlocAndPessoa";

    /** Constante para NamedQuery "MapaAlocacaoPessoa.findByMapaAloc". */
    public static final String FIND_BY_MAPA_ALOC = "MapaAlocacaoPessoa.findByMapaAloc";

    /** Constante para NamedQuery "MapaAlocacaoPessoa.findByCodigoMD5". */
    public static final String FIND_BY_CODIGO_MD5 = "MapaAlocacaoPessoa.findByCodigoMD5";

    /**
     * Realiza uma copia do objeto, porem com uma referencia diferente.
     * 
     * @return a cópia do FatorUrMes
     */
    public MapaAlocacaoPessoa getClone() {
        try {
            return (MapaAlocacaoPessoa) super.clone();
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
            return null;
        }
    }

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "MapaAlocacaoPessoa.findAll".
     */
    public static final String FIND_ALL = "MapaAlocacaoPessoa.findAll";

    /**
     * Atributo gerado a partir da coluna MAAP_CD_MAPA_ALOC_PESSOA.
     */
    @Id
    @GeneratedValue(generator = "MapaAlocacaoPessoaSeq")
    @SequenceGenerator(name = "MapaAlocacaoPessoaSeq", 
            sequenceName = "SQ_MAAP_CD_MAPA_ALOC_PESSOA", allocationSize = 1)
    @Column(name = "MAAP_CD_MAPA_ALOC_PESSOA", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoMapaAlocPessoa;

    /**
     * Atributo gerado a partir da coluna MAAL_CD_MAPA_ALOCACAO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MAAL_CD_MAPA_ALOCACAO", nullable = false)
    private MapaAlocacao mapaAlocacao;

    /**
     * Atributo gerado a partir da coluna PESS_CD_PESSOA_FLWER.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PESS_CD_PESSOA_FLWER", nullable = false)
    private Pessoa pessoa;

    /**
     * Atributo gerado a partir da coluna MAAP_CD_MD5.
     */
    @Column(name = "MAAP_CD_MD5", length = 100)
    private String codigoMD5;

    /**
     * Construtor default.
     */
    public MapaAlocacaoPessoa() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoMapaAlocPessoa
     *            Valor do atributo codigoMapaAlocPessoa;
     * @param mapaAlocacao
     *            Valor do atributo mapaAlocacao;
     * @param pessoa
     *            Valor do atributo pessoa;
     * @param codigoMD5
     *            Valor do atributo codigoMD5;
     */
    public MapaAlocacaoPessoa(final Long codigoMapaAlocPessoa,
            final MapaAlocacao mapaAlocacao, final Pessoa pessoa,
            final String codigoMD5) {
        this.codigoMapaAlocPessoa = codigoMapaAlocPessoa;
        this.mapaAlocacao = mapaAlocacao;
        this.pessoa = pessoa;
        this.codigoMD5 = codigoMD5;
    }

    /**
     * Obtem o valor do atributo codigoMapaAlocPessoa.<BR>
     * Atributo gerado a partir da coluna MAAP_CD_MAPA_ALOC_PESSOA.
     * 
     * @return Valor do atributo codigoMapaAlocPessoa.
     */
    public Long getCodigoMapaAlocPessoa() {
        return this.codigoMapaAlocPessoa;
    }

    /**
     * Atualiza o valor do atributo codigoMapaAlocPessoa.<BR>
     * Atributo gerado a partir da coluna MAAP_CD_MAPA_ALOC_PESSOA.
     * 
     * @param codigoMapaAlocPessoa
     *            Novo valor para o atributo codigoMapaAlocPessoa.
     */
    public void setCodigoMapaAlocPessoa(final Long codigoMapaAlocPessoa) {
        this.codigoMapaAlocPessoa = codigoMapaAlocPessoa;
    }

    /**
     * Obtem o valor do atributo mapaAlocacao.<BR>
     * Atributo gerado a partir da coluna MAAL_CD_MAPA_ALOCACAO.
     * 
     * @return Valor do atributo mapaAlocacao.
     */
    public MapaAlocacao getMapaAlocacao() {
        return this.mapaAlocacao;
    }

    /**
     * Atualiza o valor do atributo mapaAlocacao.<BR>
     * Atributo gerado a partir da coluna MAAL_CD_MAPA_ALOCACAO.
     * 
     * @param mapaAlocacao
     *            Novo valor para o atributo mapaAlocacao.
     */
    public void setMapaAlocacao(final MapaAlocacao mapaAlocacao) {
        this.mapaAlocacao = mapaAlocacao;
    }

    /**
     * Obtem o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA_FLWER.
     * 
     * @return Valor do atributo pessoa.
     */
    public Pessoa getPessoa() {
        return this.pessoa;
    }

    /**
     * Atualiza o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA_FLWER.
     * 
     * @param pessoa
     *            Novo valor para o atributo pessoa.
     */
    public void setPessoa(final Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    /**
     * Obtem o valor do atributo codigoMD5.<BR>
     * Atributo gerado a partir da coluna PEPE_CD_MD5.
     * 
     * @return Valor do atributo codigoMD5.
     */
    public String getCodigoMD5() {
        return this.codigoMD5;
    }

    /**
     * Atualiza o valor do atributo codigoMD5.<BR>
     * Atributo gerado a partir da coluna PEPE_CD_MD5.
     * 
     * @param codigoMD5
     *            Novo valor para o atributo codigoMD5.
     */
    public void setCodigoMD5(final String codigoMD5) {
        this.codigoMD5 = codigoMD5;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoMapaAlocPessoa").append("='").append(
                getCodigoMapaAlocPessoa()).append("' ");
        buffer.append("mapaAlocacao").append("='").append(getMapaAlocacao())
                .append("' ");
        buffer.append("pessoa").append("='").append(getPessoa()).append("' ");
        buffer.append("codigoMD5").append("='").append(getCodigoMD5()).append(
                "' ");
        buffer.append("]");

        return buffer.toString();
    }

}