/*
 * @(#) Modulo.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.*;
import java.util.Date;

/**
 * Entity gerado a partir da tabela MODULO.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 26/11/2009 15:19:48
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "MODULO")
@NamedQueries({
    @NamedQuery(name = "Modulo.findAll", query = "SELECT t FROM Modulo t")
})
public class Modulo implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "Modulo.findAll".
     */
    public static final String FIND_ALL = "Modulo.findAll";

    /**
     * Atributo gerado a partir da coluna MODU_CD_MODULO.
     */
    @Id
    @GeneratedValue(generator = "ModuloSeq")
    @SequenceGenerator(name = "ModuloSeq", sequenceName = "SQ_MODU_CD_MODULO", allocationSize = 1)
    @Column(name = "MODU_CD_MODULO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoModulo;

    /**
     * Atributo gerado a partir da coluna MODU_NM_MODULO.
     */

    @Column(name = "MODU_NM_MODULO", nullable = false, length = 50)
    private String nomeModulo;

    /**
     * Atributo gerado a partir da coluna MODU_DT_FECHAMENTO.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "MODU_DT_FECHAMENTO", length = 7)
    private Date dataFechamento;

    /**
     * Atributo gerado a partir da coluna MODU_DT_ATUALIZACAO.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "MODU_DT_ATUALIZACAO", length = 7)
    private Date dataAtualizacao;

    /**
     * Atributo gerado a partir da coluna MODU_CD_AUTOR.
     */

    @Column(name = "MODU_CD_AUTOR", length = 50)
    private String codigoAutor;

    @Column(name = "MODU_SG_MODULO")
    private String sigla;

    /**
     * Construtor default.
     */
    public Modulo() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoModulo Valor do atributo codigoModulo;
     * @param nomeModulo Valor do atributo nomeModulo;
     */
    public Modulo(final Long codigoModulo, final String nomeModulo) {
        this.codigoModulo = codigoModulo;
        this.nomeModulo = nomeModulo;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoModulo Valor do atributo codigoModulo;
     * @param nomeModulo Valor do atributo nomeModulo;
     * @param dataFechamento Valor do atributo dataFechamento;
     * @param dataAtualizacao Valor do atributo dataAtualizacao;
     * @param codigoAutor Valor do atributo codigoAutor;
     */
    public Modulo(final Long codigoModulo, final String nomeModulo, final Date dataFechamento,
            final Date dataAtualizacao, final String codigoAutor) {
        this.codigoModulo = codigoModulo;
        this.nomeModulo = nomeModulo;
        this.dataFechamento = dataFechamento;
        this.dataAtualizacao = dataAtualizacao;
        this.codigoAutor = codigoAutor;
    }

    /**
     * Obtem o valor do atributo codigoModulo.<BR>
     * Atributo gerado a partir da coluna MODU_CD_MODULO.
     * @return Valor do atributo codigoModulo.
     */
    public Long getCodigoModulo() {
        return this.codigoModulo;
    }

    /**
     * Atualiza o valor do atributo codigoModulo.<BR>
     * Atributo gerado a partir da coluna MODU_CD_MODULO.
     * @param codigoModulo Novo valor para o atributo codigoModulo.
     */
    public void setCodigoModulo(final Long codigoModulo) {
        this.codigoModulo = codigoModulo;
    }

    /**
     * Obtem o valor do atributo nomeModulo.<BR>
     * Atributo gerado a partir da coluna MODU_NM_MODULO.
     * @return Valor do atributo nomeModulo.
     */
    public String getNomeModulo() {
        return this.nomeModulo;
    }

    /**
     * Atualiza o valor do atributo nomeModulo.<BR>
     * Atributo gerado a partir da coluna MODU_NM_MODULO.
     * @param nomeModulo Novo valor para o atributo nomeModulo.
     */
    public void setNomeModulo(final String nomeModulo) {
        this.nomeModulo = nomeModulo;
    }

    /**
     * Obtem o valor do atributo dataFechamento.<BR>
     * Atributo gerado a partir da coluna MODU_DT_FECHAMENTO.
     * @return Valor do atributo dataFechamento.
     */
    public Date getDataFechamento() {
        return this.dataFechamento;
    }

    /**
     * Atualiza o valor do atributo dataFechamento.<BR>
     * Atributo gerado a partir da coluna MODU_DT_FECHAMENTO.
     * @param dataFechamento Novo valor para o atributo dataFechamento.
     */
    public void setDataFechamento(final Date dataFechamento) {
        this.dataFechamento = dataFechamento;
    }

    /**
     * Obtem o valor do atributo dataAtualizacao.<BR>
     * Atributo gerado a partir da coluna MODU_DT_ATUALIZACAO.
     * @return Valor do atributo dataAtualizacao.
     */
    public Date getDataAtualizacao() {
        return this.dataAtualizacao;
    }

    /**
     * Atualiza o valor do atributo dataAtualizacao.<BR>
     * Atributo gerado a partir da coluna MODU_DT_ATUALIZACAO.
     * @param dataAtualizacao Novo valor para o atributo dataAtualizacao.
     */
    public void setDataAtualizacao(final Date dataAtualizacao) {
        this.dataAtualizacao = dataAtualizacao;
    }

    /**
     * Obtem o valor do atributo codigoAutor.<BR>
     * Atributo gerado a partir da coluna MODU_CD_AUTOR.
     * @return Valor do atributo codigoAutor.
     */
    public String getCodigoAutor() {
        return this.codigoAutor;
    }

    /**
     * Atualiza o valor do atributo codigoAutor.<BR>
     * Atributo gerado a partir da coluna MODU_CD_AUTOR.
     * @param codigoAutor Novo valor para o atributo codigoAutor.
     */
    public void setCodigoAutor(final String codigoAutor) {
        this.codigoAutor = codigoAutor;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna o objeto em formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoModulo").append("='").append(getCodigoModulo())
                .append("' ");
        buffer.append("nomeModulo").append("='").append(getNomeModulo())
                .append("' ");
        buffer.append("dataFechamento").append("='")
                .append(getDataFechamento()).append("' ");
        buffer.append("dataAtualizacao").append("='").append(
                getDataAtualizacao()).append("' ");
        buffer.append("codigoAutor").append("='").append(getCodigoAutor())
                .append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public String getSigla() {
        return sigla;
    }

    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
}
