/*
 * @(#) MotivoResultado.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela MOTIVO_RESULTADO.
 * 
 * @author Generated by Hibernate Tools 3.6.0
 * @since 29/10/2012 13:23:28
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "MOTIVO_RESULTADO")
@NamedQueries({
		@NamedQuery(name = "MotivoResultado.findAll", query = "SELECT t FROM MotivoResultado t"),
		@NamedQuery(name = "MotivoResultado.findAllAtivos", query = "SELECT t FROM MotivoResultado t"
				+ " WHERE t.indicadorAtivo = 'A' "
				+ " ORDER BY t.codigoMotivoResultado") })
public class MotivoResultado implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "MotivoResultado.findAll".
	 */
	public static final String FIND_ALL = "MotivoResultado.findAll";

	/** Constante para NamedQuery "MotivoResultado.findAll". */
	public static final String FIND_ALL_ATIVOS = "MotivoResultado.findAllAtivos";

	/**
	 * Atributo gerado a partir da coluna MORE_CD_MOTIVO_RESULTADO.
	 */
	@Id
	@GeneratedValue(generator = "MotivoResultadoSeq")
	@SequenceGenerator(name = "MotivoResultadoSeq", sequenceName = "SQ_MORE_CD_MOTIVO_RESULTADO", allocationSize = 1)
	@Column(name = "MORE_CD_MOTIVO_RESULTADO", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoMotivoResultado;

	/**
	 * Atributo gerado a partir da coluna MORE_NM_MOTIVO_RESULTADO.
	 */

	@Column(name = "MORE_NM_MOTIVO_RESULTADO", length = 100)
	private String nomeMotivoResultado;

	/**
	 * Atributo gerado a partir da coluna MORE_IN_ATIVO.
	 */

	@Column(name = "MORE_IN_ATIVO", length = 1)
	private String indicadorAtivo;

	/**
	 * Os {@link ReceitaResultado} associados a este {@link MotivoResultado}.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motivoResultado")
	private List<ReceitaResultado> receitaResultados = new ArrayList<ReceitaResultado>(
			0);

	/**
	 * Construtor default.
	 */
	public MotivoResultado() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoMotivoResultado
	 *            Valor do atributo codigoMotivoResultado;
	 */
	public MotivoResultado(final Long codigoMotivoResultado) {
		this.codigoMotivoResultado = codigoMotivoResultado;
	}

	/**
	 * Obtem o valor do atributo codigoMotivoResultado.<BR>
	 * Atributo gerado a partir da coluna MORE_CD_MOTIVO_RESULTADO.
	 * 
	 * @return Valor do atributo codigoMotivoResultado.
	 */
	public Long getCodigoMotivoResultado() {
		return this.codigoMotivoResultado;
	}

	/**
	 * Atualiza o valor do atributo codigoMotivoResultado.<BR>
	 * Atributo gerado a partir da coluna MORE_CD_MOTIVO_RESULTADO.
	 * 
	 * @param codigoMotivoResultado
	 *            Novo valor para o atributo codigoMotivoResultado.
	 */
	public void setCodigoMotivoResultado(final Long codigoMotivoResultado) {
		this.codigoMotivoResultado = codigoMotivoResultado;
	}

	/**
	 * Obtem o valor do atributo nomeMotivoResultado.<BR>
	 * Atributo gerado a partir da coluna MORE_NM_MOTIVO_RESULTADO.
	 * 
	 * @return Valor do atributo nomeMotivoResultado.
	 */
	public String getNomeMotivoResultado() {
		return this.nomeMotivoResultado;
	}

	/**
	 * Atualiza o valor do atributo nomeMotivoResultado.<BR>
	 * Atributo gerado a partir da coluna MORE_NM_MOTIVO_RESULTADO.
	 * 
	 * @param nomeMotivoResultado
	 *            Novo valor para o atributo nomeMotivoResultado.
	 */
	public void setNomeMotivoResultado(final String nomeMotivoResultado) {
		this.nomeMotivoResultado = nomeMotivoResultado;
	}

	/**
	 * Obtem o valor do atributo indicadorAtivo.<BR>
	 * Atributo gerado a partir da coluna MORE_IN_ATIVO.
	 * 
	 * @return Valor do atributo indicadorAtivo.
	 */
	public String getIndicadorAtivo() {
		return this.indicadorAtivo;
	}

	/**
	 * Atualiza o valor do atributo indicadorAtivo.<BR>
	 * Atributo gerado a partir da coluna MORE_IN_ATIVO.
	 * 
	 * @param indicadorAtivo
	 *            Novo valor para o atributo indicadorAtivo.
	 */
	public void setIndicadorAtivo(final String indicadorAtivo) {
		this.indicadorAtivo = indicadorAtivo;
	}

	/**
	 * Obtem o valor do atributo receitaResultados.<BR>
	 * 
	 * @return Valor do atributo receitaResultados.
	 */
	public List<ReceitaResultado> getReceitaResultados() {
		return this.receitaResultados;
	}

	/**
	 * Atualiza o valor do atributo receitaResultados.<BR>
	 * 
	 * @param receitaResultados
	 *            Novo valor para o atributo receitaResultados.
	 */
	public void setReceitaResultados(
			final List<ReceitaResultado> receitaResultados) {
		this.receitaResultados = receitaResultados;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoMotivoResultado").append("='")
				.append(getCodigoMotivoResultado()).append("' ");
		buffer.append("nomeMotivoResultado").append("='")
				.append(getNomeMotivoResultado()).append("' ");
		buffer.append("indicadorAtivo").append("='")
				.append(getIndicadorAtivo()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
