/*
 * @(#) Msa.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity gerado a partir da tabela MSA. Relacao de Contratos
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 28/09/2012 10:30:06
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "MSA")
@NamedQueries({
		@NamedQuery(name = "Msa.findAll", query = "SELECT t FROM Msa t "
				+ "ORDER BY t.nomeMsa ASC"),

		@NamedQuery(name = "Msa.findAllReturnCodigoAndNomeMsa", query = "SELECT new Msa(t.codigoMsa, t.nomeMsa) FROM Msa t "),

		@NamedQuery(name = "Msa.findByFilter", query = "SELECT t FROM Msa t "
				+ "LEFT JOIN FETCH t.cliente "
				+ "WHERE (UPPER(t.nomeMsa) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
				+ "AND ((t.cliente.codigoCliente = ?) OR (? = 0L)) "
				+ "AND ((t.bmDn = ?) OR (? = 0L)) "
				+ "AND ((t.industryType = ?) OR (? = 0L)) "
				+ "AND (UPPER(t.indicadorStatus) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
				+ "ORDER BY t.nomeMsa ASC"),

		@NamedQuery(name = "Msa.findByCliente", query = "SELECT t FROM Msa t "
				+ "WHERE t.cliente.codigoCliente = ? "
				+ "ORDER BY t.nomeMsa ASC "),

		@NamedQuery(name = "Msa.findAllComplete", query = "SELECT t FROM Msa t "
				+ "WHERE t.indicadorCompleto = 'Y' "
				+ "ORDER BY t.nomeMsa ASC "),

		@NamedQuery(name = "Msa.findQuickByName", query = "SELECT t FROM Msa t "
				+ "WHERE (UPPER(t.nomeMsa) like '%'||TRIM(UPPER(?))||'%') "
				+ "ORDER BY t.nomeMsa"),

		@NamedQuery(name = "Msa.findByName", query = "SELECT t FROM Msa t "
				+ "WHERE UPPER(t.nomeMsa) = TRIM(UPPER(?)) "),

		@NamedQuery(name = "Msa.findAllByName", query = "SELECT t FROM Msa t "
				+ "WHERE UPPER(t.nomeMsa) = UPPER(?) "),

		@NamedQuery(name = "Msa.findByCentroLucro", query = "SELECT m FROM Msa m"
				+ "	JOIN m.contratoPraticas cp"
				+ " JOIN cp.centroLucros cl"
				+ " WHERE cl.codigoCentroLucro = :codigoCentroLucro"),

		@NamedQuery(name = "Msa.findByBmDn", query = "SELECT m FROM Msa m "
				+ " WHERE m.bmDn = :bmdn"),

		@NamedQuery(name = "Msa.findByIndustryType", query = "SELECT m FROM Msa m "
				+ " WHERE m.industryType = :industryType")
})
public class Msa implements java.io.Serializable {

	// ========================================================================
	// BEGIN - Coloque aqui o codigo manual
	// ========================================================================

	/**
	 * Constante para NamedQuery "Msa.findByFilter".
	 */
	public static final String FIND_BY_FILTER = "Msa.findByFilter";

	/**
	 * Constante para NamedQuery "Msa.findByCliente".
	 */
	public static final String FIND_BY_CLIENTE = "Msa.findByCliente";

	/**
	 * Constante para NamedQuery "Msa.findQuickByName".
	 */
	public static final String FIND_QUICK_BY_NAME = "Msa.findQuickByName";

	/**
	 * Constante para NamedQuery "Msa.findAllComplete".
	 */
	public static final String FIND_ALL_COMPLETE = "Msa.findAllComplete";

	/**
	 * Constante para NamedQuery "Msa.findByName".
	 */
	public static final String FIND_BY_NAME = "Msa.findByName";

	/**
	 * Constante para NamedQuery "Msa.findAllByName".
	 */
	public static final String FIND_ALL_BY_NAME = "Msa.findAllByName";
	
	/**
	 * Constante para NamedQuery "Msa.findAllReturnCodigoAndNomeMsa".
	 */
	public static final String FIND_ALL_RETURN_CODIGO_AND_NOME_MSA = "Msa.findAllReturnCodigoAndNomeMsa";

	/**
	 * Constante para NamedQuery "Msa.findByBmDn".
	 */
	public static final String FIND_BY_BMDN = "Msa.findByBmDn";

	/**
	 * Constante para NamedQuery "Msa.findByIndustryType".
	 */
	public static final String FIND_BY_INDUSTRY_TYPE = "Msa.findByIndustryType";

	/**
	 * Constante para NamedQuery "Msa.findByCentroLucro".
	 */
	public static final String FIND_BY_CENTRO_LUCRO = "Msa.findByCentroLucro";


	/** Lista de PerfilVendido. */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msa")
	private List<PerfilVendido> perfilVendidos = new ArrayList<PerfilVendido>(0);

	/** Lista de MsaSaldoMoeda. */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msa", cascade = CascadeType.ALL)
	private List<MsaSaldoMoeda> msaSaldoMoedas = new ArrayList<MsaSaldoMoeda>(0);

	/** Lista de TabelaPreco. */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msa")
	private List<TabelaPreco> tabelaPrecos = new ArrayList<TabelaPreco>(0);

	/** Lista de DealFiscal. */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msa", cascade = CascadeType.ALL)
	private List<DealFiscal> dealFiscals = new ArrayList<DealFiscal>(0);

	/** Lista de ContratoPratica. */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msa")
	private List<ContratoPratica> contratoPraticas = new ArrayList<ContratoPratica>(
			0);

	/** Lista de Fiscal Balance Acumulado. */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msa")
	private List<VwFiscalBalanceAcumulado> VwFiscalBalanceAcumulados = new ArrayList<VwFiscalBalanceAcumulado>(0);

	// ========================================================================
	// END
	// ========================================================================

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "Msa.findAll".
	 */
	public static final String FIND_ALL = "Msa.findAll";

	/**
	 * Atributo gerado a partir da coluna MSAA_CD_MSA. Codigo do Contrato
	 */
	@Id
	@GeneratedValue(generator = "MsaSeq")
	@SequenceGenerator(name = "MsaSeq", sequenceName = "SQ_MSAA_CD_MSA", allocationSize = 1)
	@Column(name = "MSAA_CD_MSA", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoMsa;

	/**
	 * Atributo gerado a partir da coluna CLIE_CD_CLIENTE. Codigo do Cliente
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIE_CD_CLIENTE")
	private Cliente cliente;

	/**
	 * Atributo gerado a partir da coluna MSAA_NM_MSA. Descricao do Contrato
	 */

	@Column(name = "MSAA_NM_MSA", length = 240)
	private String nomeMsa;

	/**
	 * Atributo gerado a partir da coluna MSAA_IN_STATUS.
	 */

	@Column(name = "MSAA_IN_STATUS", nullable = false, length = 2)
	private String indicadorStatus;

	/**
	 * Atributo gerado a partir da coluna MSAA_IN_TIPO_FATURA.
	 */
	@Column(name = "MSAA_IN_TIPO_FATURA", length = 2)
	private String indicadorTipoFatura;

	/**
	 * Atributo gerado a partir da coluna MSAA_IN_COMPLETO.
	 */

	@Column(name = "MSAA_IN_COMPLETO", nullable = false, length = 1)
	private String indicadorCompleto;

	@Column(name = "MSAA_IN_REEMBOLSAVEL", length = 1)
	private String indicadorReembolsavel;

	/**
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA_DN.
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PESS_CD_PESSOA_APPROVER")
	private Pessoa pessoa;

	/**
	 * Atributo gerado a partir da coluna COPR_PR_MARGEM.
	 */
	@Column(name = "MSAA_PR_MARGEM", precision = 22, scale = 0)
	private BigDecimal percentualMargem;

	/**
	 * Atributo gerado a partir da coluna COPR_PR_COMISSAO.
	 */
	@Column(name = "MSAA_PR_COMISSAO", precision = 22, scale = 0)
	private BigDecimal percentualComissao;

	/**
	 * Atributo gerado a partir da coluna COPR_IN_CALC_DU.
	 */
	@Column(name = "MSAA_IN_CALC_DU", length = 1)
	private String indicadorCalculoDiasUteis;

	/**
	 * Atributo gerado a partir da coluna COPR_IN_CALC_ROUNDUP.
	 */
	@Column(name = "MSAA_IN_CALC_ROUNDUP", length = 1)
	private String indicadorArredondamentoDiarias;

	/**
	 * Atributo gerado a partir da coluna MSAA_TX_FIXED_PAYMENT_DAY.
	 */
	@Column(name = "MSAA_TX_FIXED_PAYMENT_DAY", length = 200)
	private String fixedPaymentDays;

	/**
	 * Atributo gerado a partir da coluna MSAA_TX_BILLING_WINDOW.
	 */
	@Column(name = "MSAA_TX_BILLING_WINDOW", length = 200)
	private String billingWindow;

	/**
	 * Atributo gerado a partir da coluna COPR_IN_CALC_ROUNDUP.
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MSCM_CD_MSA_CHARGE_METHOD")
	private MsaChargeMethod chargeMethod;

	/**
	 * Atributo gerado a partir da coluna MSAA_CD_BM_DN.
	 */
	@Column(name = "MSAA_CD_BM_DN")
	private Long bmDn;

	/**
	 * Atributo gerado a partir da coluna MSAA_CD_INDUSTRY_TYPE.
	 */
	@Column(name = "MSAA_CD_INDUSTRY_TYPE", precision = 18, scale = 0)
	private Long industryType;

	/**
	 * Atributo transitório / calculado Forecast Sales Tax.
	 */
	@Transient
	private BigDecimal forecastSalesTax = BigDecimal.valueOf(0);

	/**
	 * Construtor default.
	 */
	public Msa() {
	}

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoMsa
     *            Valor do atributo codigoMsa;
     * @param nomeMsa
     *            Valor do atributo nomeMsa;
     */
    public Msa(final Long codigoMsa, final String nomeMsa) {
        this.codigoMsa = codigoMsa;
        this.nomeMsa = nomeMsa;
    }

	public Msa(final Long codigoMsa, final String nomeMsa, Cliente cliente) {
		this.codigoMsa = codigoMsa;
		this.nomeMsa = nomeMsa;
		this.cliente = cliente;
	}

	/**
	 * Obtem o valor do atributo codigoMsa.<BR>
	 * Atributo gerado a partir da coluna MSAA_CD_MSA. Codigo do Contrato
	 * 
	 * @return Valor do atributo codigoMsa.
	 */
	public Long getCodigoMsa() {
		return this.codigoMsa;
	}

	/**
	 * Atualiza o valor do atributo codigoMsa.<BR>
	 * Atributo gerado a partir da coluna MSAA_CD_MSA. Codigo do Contrato
	 * 
	 * @param codigoMsa
	 *            Novo valor para o atributo codigoMsa.
	 */
	public void setCodigoMsa(final Long codigoMsa) {
		this.codigoMsa = codigoMsa;
	}

	/**
	 * Obtem o valor do atributo cliente.<BR>
	 * Atributo gerado a partir da coluna CLIE_CD_CLIENTE. Codigo do Cliente
	 * 
	 * @return Valor do atributo cliente.
	 */
	public Cliente getCliente() {
		return this.cliente;
	}

	/**
	 * Atualiza o valor do atributo cliente.<BR>
	 * Atributo gerado a partir da coluna CLIE_CD_CLIENTE. Codigo do Cliente
	 * 
	 * @param cliente
	 *            Novo valor para o atributo cliente.
	 */
	public void setCliente(final Cliente cliente) {
		this.cliente = cliente;
	}

	/**
	 * Obtem o valor do atributo nomeMsa.<BR>
	 * Atributo gerado a partir da coluna MSAA_NM_MSA. Descricao do Contrato
	 * 
	 * @return Valor do atributo nomeMsa.
	 */
	public String getNomeMsa() {
		return this.nomeMsa;
	}

	/**
	 * Atualiza o valor do atributo nomeMsa.<BR>
	 * Atributo gerado a partir da coluna MSAA_NM_MSA. Descricao do Contrato
	 * 
	 * @param nomeMsa
	 *            Novo valor para o atributo nomeMsa.
	 */
	public void setNomeMsa(final String nomeMsa) {
		this.nomeMsa = nomeMsa;
	}

	/**
	 * Obtem o valor do atributo indicadorStatus.<BR>
	 * Atributo gerado a partir da coluna CONT_IN_STATUS.
	 * 
	 * @return Valor do atributo indicadorStatus.
	 */
	public String getIndicadorStatus() {
		return this.indicadorStatus;
	}

	/**
	 * Atualiza o valor do atributo indicadorStatus.<BR>
	 * Atributo gerado a partir da coluna CONT_IN_STATUS.
	 * 
	 * @param indicadorStatus
	 *            Novo valor para o atributo indicadorStatus.
	 */
	public void setIndicadorStatus(final String indicadorStatus) {
		this.indicadorStatus = indicadorStatus;
	}

	/**
	 * Obtem o valor do atributo perfilVendidos.<BR>
	 * 
	 * @return Valor do atributo perfilVendidos.
	 */
	public List<PerfilVendido> getPerfilVendidos() {
		return this.perfilVendidos;
	}

	/**
	 * Atualiza o valor do atributo perfilVendidos.<BR>
	 * 
	 * @param perfilVendidos
	 *            Novo valor para o atributo perfilVendidos.
	 */
	public void setPerfilVendidos(final List<PerfilVendido> perfilVendidos) {
		this.perfilVendidos = perfilVendidos;
	}

	/**
	 * Obtem o valor do atributo msaSaldoMoedas.<BR>
	 * 
	 * @return Valor do atributo msaSaldoMoedas.
	 */
	public List<MsaSaldoMoeda> getMsaSaldoMoedas() {
		return this.msaSaldoMoedas;
	}

	/**
	 * Atualiza o valor do atributo msaSaldoMoedas.<BR>
	 * 
	 * @param msaSaldoMoedas
	 *            Novo valor para o atributo msaSaldoMoedas.
	 */
	public void setMsaSaldoMoedas(final List<MsaSaldoMoeda> msaSaldoMoedas) {
		this.msaSaldoMoedas = msaSaldoMoedas;
	}

	/**
	 * Obtem o valor do atributo tabelaPrecos.<BR>
	 * 
	 * @return Valor do atributo tabelaPrecos.
	 */
	public List<TabelaPreco> getTabelaPrecos() {
		return this.tabelaPrecos;
	}

	/**
	 * Atualiza o valor do atributo tabelaPrecos.<BR>
	 * 
	 * @param tabelaPrecos
	 *            Novo valor para o atributo tabelaPrecos.
	 */
	public void setTabelaPrecos(final List<TabelaPreco> tabelaPrecos) {
		this.tabelaPrecos = tabelaPrecos;
	}

	/**
	 * Obtem o valor do atributo dealFiscals.<BR>
	 * 
	 * @return Valor do atributo dealFiscals.
	 */
	public List<DealFiscal> getDealFiscals() {
		return this.dealFiscals;
	}

	/**
	 * Atualiza o valor do atributo dealFiscals.<BR>
	 * 
	 * @param dealFiscals
	 *            Novo valor para o atributo dealFiscals.
	 */
	public void setDealFiscals(final List<DealFiscal> dealFiscals) {
		this.dealFiscals = dealFiscals;
	}

	/**
	 * @return the pessoa
	 */
	public Pessoa getPessoa() {
		return pessoa;
	}

	/**
	 * @param pessoa
	 *            the pessoa to set
	 */
	public void setPessoa(final Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	/**
	 * @return the percentualMargem
	 */
	public BigDecimal getPercentualMargem() {
		return percentualMargem;
	}

	/**
	 * @param percentualMargem
	 *            the percentualMargem to set
	 */
	public void setPercentualMargem(final BigDecimal percentualMargem) {
		this.percentualMargem = percentualMargem;
	}

	/**
	 * @return the percentualComissao
	 */
	public BigDecimal getPercentualComissao() {
		return percentualComissao;
	}

	/**
	 * @param percentualComissao
	 *            the percentualComissao to set
	 */
	public void setPercentualComissao(final BigDecimal percentualComissao) {
		this.percentualComissao = percentualComissao;
	}

	/**
	 * Obtem o valor do atributo contratoPraticas.<BR>
	 * 
	 * @return Valor do atributo contratoPraticas.
	 */
	public List<ContratoPratica> getContratoPraticas() {
		return this.contratoPraticas;
	}

	/**
	 * Atualiza o valor do atributo contratoPraticas.<BR>
	 * 
	 * @param contratoPraticas
	 *            Novo valor para o atributo contratoPraticas.
	 */
	public void setContratoPraticas(final List<ContratoPratica> contratoPraticas) {
		this.contratoPraticas = contratoPraticas;
	}

	/**
	 * @return the forecastSalesTax
	 */
	public BigDecimal getForecastSalesTax() {
		return forecastSalesTax;
	}

	/**
	 * @param forecastSalesTax
	 *            the forecastSalesTax to set
	 */
	public void setForecastSalesTax(final BigDecimal forecastSalesTax) {
		this.forecastSalesTax = forecastSalesTax;
	}

	public String getIndicadorReembolsavel () {return indicadorReembolsavel;}

	public void setIndicadorReembolsavel (final String indicadorReembolsavel) {this.indicadorReembolsavel = indicadorReembolsavel;}

	/**
	 * @return the indicadorReembolsavel
	 */
	public String getIndicadorCalculoDiasUteis() {
		return indicadorCalculoDiasUteis;
	}

	/**
	 * @param indicadorCalculoDiasUteis
	 *            the indicadorReembolsavel to set
	 */
	public void setIndicadorCalculoDiasUteis(final String indicadorCalculoDiasUteis) {
		this.indicadorCalculoDiasUteis = indicadorCalculoDiasUteis;
	}

	/**
	 * @return the indicadorReembolsavel
	 */
	public String getIndicadorArredondamentoDiarias() {
		return indicadorArredondamentoDiarias;
	}

	/**
	 * @param indicadorArredondamentoDiarias
	 *            the indicadorReembolsavel to set
	 */
	public void setIndicadorArredondamentoDiarias(final String indicadorArredondamentoDiarias) {
		this.indicadorArredondamentoDiarias = indicadorArredondamentoDiarias;
	}
	/**
	 * @see Object#toString()
	 * @return toString
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoMsa").append("='").append(getCodigoMsa())
				.append("' ");
		buffer.append("cliente").append("='").append(getCliente()).append("' ");
		buffer.append("nomeMsa").append("='").append(getNomeMsa()).append("' ");
		buffer.append("indicadorStatus").append("='")
				.append(getIndicadorStatus()).append("' ");
		buffer.append("pessoa").append("='").append(getPessoa()).append("' ");
		buffer.append("bmDn").append("='")
				.append(getBmDn()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	/**
	 * @return the indicadorCompleto
	 */
	public String getIndicadorCompleto() {
		return indicadorCompleto;
	}

	/**
	 * @param indicadorCompleto
	 *            the indicadorCompleto to set
	 */
	public void setIndicadorCompleto(final String indicadorCompleto) {
		this.indicadorCompleto = indicadorCompleto;
	}

	/**
	 * @return the indicadorTipoFatura
	 */
	public String getIndicadorTipoFatura() {
		return indicadorTipoFatura;
	}

	/**
	 * @param indicadorTipoFatura 
	 * 			the indicadorTipoFatura to set
	 */
	public void setIndicadorTipoFatura(String indicadorTipoFatura) {
		this.indicadorTipoFatura = indicadorTipoFatura;
	}

	public String getFixedPaymentDays() {
		return fixedPaymentDays;
	}

	public void setFixedPaymentDays(String fixedPaymentDays) {
		this.fixedPaymentDays = fixedPaymentDays;
	}

	public String getBillingWindow() {
		return billingWindow;
	}

	public void setBillingWindow(String billingWindow) {
		this.billingWindow = billingWindow;
	}

	public MsaChargeMethod getChargeMethod() {
		return chargeMethod;
	}

	public void setChargeMethod(MsaChargeMethod chargeMethod) {
		this.chargeMethod = chargeMethod;
	}

	public Long getBmDn() {
		return bmDn;
	}

	public void setBmDn(Long bmDn) {
		this.bmDn = bmDn;
	}

	public Long getIndustryType() {
		return industryType;
	}
	public void setIndustryType(Long industryType) {
		this.industryType = industryType;
	}
}