/*
 * @(#) MsaSaldoMoeda.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;

/**
 * Entity gerado a partir da tabela MSA_SALDO_MOEDA.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 28/09/2012 10:30:06
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "MSA_SALDO_MOEDA")
@NamedQueries({
    @NamedQuery(name = "MsaSaldoMoeda.findAll", query = "SELECT t FROM MsaSaldoMoeda t"),
    
    @NamedQuery(name = "MsaSaldoMoeda.findByMsa", query = "SELECT t FROM MsaSaldoMoeda t "
            + "WHERE t.msa.codigoMsa = ?"),
            
    @NamedQuery(name = "MsaSaldoMoeda.findByMsaAndActive", query = "SELECT t FROM MsaSaldoMoeda t "
    		+ "WHERE t.msa.codigoMsa = ? "
    		+ "AND t.indicadorAtivo = 'A'")
})
public class MsaSaldoMoeda implements java.io.Serializable {
    
    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    
    /** 
     * Constante para NamedQuery "MsaSaldoMoeda.findByMsa".
     */
    public static final String FIND_BY_MSA = "MsaSaldoMoeda.findByMsa";
    
    /** 
     * Constante para NamedQuery "MsaSaldoMoeda.findByMsaAndActive".
     */
    public static final String FIND_BY_MSA_AND_ACTIVE = "MsaSaldoMoeda.findByMsaAndActive";
    
    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;
    
    /** 
     * Constante para NamedQuery "MsaSaldoMoeda.findAll".
     */
    public static final String FIND_ALL = "MsaSaldoMoeda.findAll";

    /**
     * Atributo gerado a partir da coluna MSSM_CD_MSA_SALDO.
     */
    @Id
    @GeneratedValue(generator = "MsaSaldoMoedaSeq")
    @SequenceGenerator(name = "MsaSaldoMoedaSeq", sequenceName = "SQ_MSSM_CD_MSA_SALDO", allocationSize = 1)
    @Column(name = "MSSM_CD_MSA_SALDO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoMsaSaldo;

    /**
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     */
    @Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MOED_CD_MOEDA", nullable = false)
    private Moeda moeda;

    /**
     * Atributo gerado a partir da coluna MSAA_CD_MSA.
     */
    @Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MSAA_CD_MSA", nullable = false)
    private Msa msa;

    /**
     * Atributo gerado a partir da coluna MSSM_VL_ORCAMENTO.
     */
    @Audited
    @Column(name = "MSSM_VL_ORCAMENTO", precision = 22, scale = 0)
    private BigDecimal valorOrcamento;
    
	/**
	 * Atributo gerado a partir da coluna MSSM_IN_ATIVO.
	 */
    @Audited
	@Column(name = "MSSM_IN_ATIVO", nullable = false, length = 1)
	private String indicadorAtivo;

    /**
     * Construtor default.
     */
    public MsaSaldoMoeda() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoMsaSaldo Valor do atributo codigoMsaSaldo;
     * @param moeda Valor do atributo moeda;
     * @param msa Valor do atributo msa;
     */
    public MsaSaldoMoeda(final Long codigoMsaSaldo, final Moeda moeda,
            final Msa msa) {
        this.codigoMsaSaldo = codigoMsaSaldo;
        this.moeda = moeda;
        this.msa = msa;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoMsaSaldo Valor do atributo codigoMsaSaldo;
     * @param moeda Valor do atributo moeda;
     * @param msa Valor do atributo msa;
     * @param valorOrcamento Valor do atributo valorOrcamento;
     */
    public MsaSaldoMoeda(final Long codigoMsaSaldo, final Moeda moeda,
            final Msa msa, final BigDecimal valorOrcamento) {
        this.codigoMsaSaldo = codigoMsaSaldo;
        this.moeda = moeda;
        this.msa = msa;
        this.valorOrcamento = valorOrcamento;
    }

    /**
     * Obtem o valor do atributo codigoMsaSaldo.<BR>
     * Atributo gerado a partir da coluna MSSM_CD_MSA_SALDO.
     * @return Valor do atributo codigoMsaSaldo.
     */
    public Long getCodigoMsaSaldo() {
        return this.codigoMsaSaldo;
    }

    /**
     * Atualiza o valor do atributo codigoMsaSaldo.<BR>
     * Atributo gerado a partir da coluna MSSM_CD_MSA_SALDO.
     * @param codigoMsaSaldo Novo valor para o atributo codigoMsaSaldo.
     */
    public void setCodigoMsaSaldo(final Long codigoMsaSaldo) {
        this.codigoMsaSaldo = codigoMsaSaldo;
    }

    /**
     * Obtem o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * @return Valor do atributo moeda.
     */
    public Moeda getMoeda() {
        return this.moeda;
    }

    /**
     * Atualiza o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * @param moeda Novo valor para o atributo moeda.
     */
    public void setMoeda(final Moeda moeda) {
        this.moeda = moeda;
    }

    /**
     * Obtem o valor do atributo msa.<BR>
     * Atributo gerado a partir da coluna MSAA_CD_MSA.
     * @return Valor do atributo msa.
     */
    public Msa getMsa() {
        return this.msa;
    }

    /**
     * Atualiza o valor do atributo msa.<BR>
     * Atributo gerado a partir da coluna MSAA_CD_MSA.
     * @param msa Novo valor para o atributo msa.
     */
    public void setMsa(final Msa msa) {
        this.msa = msa;
    }

    /**
     * Obtem o valor do atributo valorOrcamento.<BR>
     * Atributo gerado a partir da coluna MSSM_VL_ORCAMENTO.
     * @return Valor do atributo valorOrcamento.
     */
    public BigDecimal getValorOrcamento() {
        return this.valorOrcamento;
    }

    /**
     * Atualiza o valor do atributo valorOrcamento.<BR>
     * Atributo gerado a partir da coluna MSSM_VL_ORCAMENTO.
     * @param valorOrcamento Novo valor para o atributo valorOrcamento.
     */
    public void setValorOrcamento(final BigDecimal valorOrcamento) {
        this.valorOrcamento = valorOrcamento;
    }
    
    

    /**
	 * @return the indicadorAtivo
	 */
	public String getIndicadorAtivo() {
		return indicadorAtivo;
	}

	/**
	 * @param indicadorAtivo the indicadorAtivo to set
	 */
	public void setIndicadorAtivo(String indicadorAtivo) {
		this.indicadorAtivo = indicadorAtivo;
	}

	/**
     * @see Object#toString()
     * @return toString
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoMsaSaldo").append("='")
                .append(getCodigoMsaSaldo()).append("' ");
        buffer.append("moeda").append("='").append(getMoeda()).append("' ");
        buffer.append("msa").append("='").append(getMsa()).append("' ");
        buffer.append("valorOrcamento").append("='").append(getValorOrcamento())
                .append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
