/*
 * @(#) OrcDespDelegacao.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela ORC_DESP_DELEGACAO.
 * 
 * @author Generated by Hibernate Tools 3.4.0.CR1
 * @since 10/09/2013 09:41:36
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "ORC_DESP_DELEGACAO")
@NamedQueries({
		@NamedQuery(name = "OrcDespDelegacao.findAll", query = "SELECT t FROM OrcDespDelegacao t"),
		@NamedQuery(name = "OrcDespDelegacao.findByOrcDespesa", query = "SELECT t FROM OrcDespDelegacao t "
				+ "WHERE t.id.codigoOrcDespesa = ? ORDER BY t.id.codigoLogin"),
		@NamedQuery(name = "OrcDespDelegacao.findByOrcDespesaAndLogin", query = "SELECT t FROM OrcDespDelegacao t "
				+ "WHERE t.id.codigoOrcDespesa = ? AND t.id.codigoLogin = ?"),
		@NamedQuery(name = "OrcDespDelegacao.findByLogin", query = "SELECT t FROM OrcDespDelegacao t "
				+ "JOIN t.orcDespesa od WHERE t.id.codigoLogin = ? ORDER BY od.dataFim DESC") })
public class OrcDespDelegacao implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "OrcDespDelegacao.findAll".
	 */
	public static final String FIND_ALL = "OrcDespDelegacao.findAll";

	/**
	 * Constante para NamedQuery "OrcDespDelegacao.findByOrcDespesa".
	 */
	public static final String FIND_BY_ORC_DEPSESA = "OrcDespDelegacao.findByOrcDespesa";

	/**
	 * Constante para NamedQuery "OrcDespDelegacao.findByOrcDespesaAndLogin".
	 */
	public static final String FIND_BY_ORC_DEPSESA_AND_LOGIN = "OrcDespDelegacao.findByOrcDespesaAndLogin";
	
	/**
	 * Constante para NamedQuery "OrcDespDelegacao.findByLogin".
	 */
	public static final String FIND_BY_LOGIN = "OrcDespDelegacao.findByLogin";

	/**
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN.
	 */
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoOrcDespesa", column = @Column(name = "ORDD_CD_ORC_DESPESA", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "codigoLogin", column = @Column(name = "PESS_CD_LOGIN", nullable = false, length = 100)) })
	private OrcDespDelegacaoId id;

	/**
	 * Atributo gerado a partir da coluna ORDD_CD_ORC_DESPESA.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDD_CD_ORC_DESPESA", nullable = false, insertable = false, updatable = false)
	private OrcamentoDespesa orcDespesa;

	@Column(name = "PESS_CD_LOGIN", nullable = false, length = 100, insertable = false, updatable = false)
	private String codigoLogin;

	/**
	 * Construtor default.
	 */
	public OrcDespDelegacao() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param id
	 *            Valor do atributo id;
	 * @param orcDespesa
	 *            Valor do atributo orcDespesa;
	 */
	public OrcDespDelegacao(OrcDespDelegacaoId id, OrcamentoDespesa orcDespesa) {
		this.id = id;
		this.orcDespesa = orcDespesa;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param id
	 *            id.
	 */
	public OrcDespDelegacao(final OrcDespDelegacaoId id) {
		this.id = id;
	}

	/**
	 * Obtem o valor do atributo id.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN.
	 * 
	 * @return Valor do atributo id.
	 */
	public OrcDespDelegacaoId getId() {
		return this.id;
	}

	/**
	 * Atualiza o valor do atributo id.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN.
	 * 
	 * @param id
	 *            Novo valor para o atributo id.
	 */
	public void setId(OrcDespDelegacaoId id) {
		this.id = id;
	}

	/**
	 * Obtem o valor do atributo orcDespesa.<BR>
	 * Atributo gerado a partir da coluna ORDD_CD_ORC_DESPESA.
	 * 
	 * @return Valor do atributo orcDespesa.
	 */
	public OrcamentoDespesa getOrcDespesa() {
		return this.orcDespesa;
	}

	/**
	 * Atualiza o valor do atributo orcDespesa.<BR>
	 * Atributo gerado a partir da coluna ORDD_CD_ORC_DESPESA.
	 * 
	 * @param orcDespesa
	 *            Novo valor para o atributo orcDespesa.
	 */
	public void setOrcDespesa(OrcamentoDespesa orcDespesa) {
		this.orcDespesa = orcDespesa;
	}

	/**
	 * @return the codigoLogin
	 */
	public String getCodigoLogin() {
		return codigoLogin;
	}

	/**
	 * @param codigoLogin
	 *            the codigoLogin to set
	 */
	public void setCodigoLogin(String codigoLogin) {
		this.codigoLogin = codigoLogin;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("orcDespesa").append("='").append(getOrcDespesa())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
