/*
 * @(#) OrcDespWhiteList.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela ORC_DESP_WHITE_LIST.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 24/07/2012 15:26:39
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "ORC_DESP_WHITE_LIST")
@NamedQueries({
		@NamedQuery(name = "OrcDespWhiteList.findAll", query = "SELECT t FROM OrcDespWhiteList t"),
		@NamedQuery(name = "OrcDespWhiteList.findByOrcamentoDespesa", query = "SELECT t FROM OrcDespWhiteList t "
				+ "WHERE t.orcamentoDespesa.codigoOrcaDespesa = ? "
				+ "ORDER BY t.codigoLogin"),
		@NamedQuery(name = "OrcDespWhiteList.findByOrcDespAndName", query = "SELECT t FROM OrcDespWhiteList t "
				+ "WHERE t.orcamentoDespesa.codigoOrcaDespesa = ? "
				+ "AND t.codigoLogin = ? ") })
public class OrcDespWhiteList implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "OrcDespWhiteList.findAll".
	 */
	public static final String FIND_ALL = "OrcDespWhiteList.findAll";

	/**
	 * Constante para NamedQuery "OrcDespWhiteList.findByOrcamentoDespesa".
	 */
	public static final String FIND_BY_ORCAMENTO_DESPESA = "OrcDespWhiteList.findByOrcamentoDespesa";

	/**
	 * Constante para NamedQuery "OrcDespWhiteList.findByOrcDespAndName".
	 */
	public static final String FIND_BY_ORC_DESP_AND_NAME = "OrcDespWhiteList.findByOrcDespAndName";

	/**
	 * Atributo gerado a partir da coluna ODWL_CD_ORC_DESP_WL.
	 */
	@Id
	@GeneratedValue(generator = "OrcDespWhiteListSeq")
	@SequenceGenerator(name = "OrcDespWhiteListSeq", sequenceName = "SQ_ODWL_CD_ORCA_DESP_WL", allocationSize = 1)
	@Column(name = "ODWL_CD_ORCA_DESP_WL", unique = true, nullable = false, precision = 22, scale = 0)
	private Long codigoOrcDespWl;

	/**
	 * Atributo gerado a partir da coluna ORDE_CD_ORCA_DESPESA.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDE_CD_ORCA_DESPESA", nullable = false)
	private OrcamentoDespesa orcamentoDespesa;

	/**
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN.
	 */
	@Column(name = "PESS_CD_LOGIN", length = 100)
	private String codigoLogin;

	/**
	 * Construtor default.
	 */
	public OrcDespWhiteList() {
	}

	/**
	 * Obtem o valor do atributo codigoOrcDespWl.<BR>
	 * Atributo gerado a partir da coluna ODWL_CD_ORC_DESP_WL.
	 * 
	 * @return Valor do atributo codigoOrcDespWl.
	 */
	public Long getCodigoOrcDespWl() {
		return this.codigoOrcDespWl;
	}

	/**
	 * Atualiza o valor do atributo codigoOrcDespWl.<BR>
	 * Atributo gerado a partir da coluna ODWL_CD_ORC_DESP_WL.
	 * 
	 * @param codigoOrcDespWl
	 *            Novo valor para o atributo codigoOrcDespWl.
	 */
	public void setCodigoOrcDespWl(final Long codigoOrcDespWl) {
		this.codigoOrcDespWl = codigoOrcDespWl;
	}

	/**
	 * Obtem o valor do atributo orcamentoDespesa.<BR>
	 * Atributo gerado a partir da coluna ORDE_CD_ORCA_DESPESA.
	 * 
	 * @return Valor do atributo orcamentoDespesa.
	 */
	public OrcamentoDespesa getOrcamentoDespesa() {
		return this.orcamentoDespesa;
	}

	/**
	 * Atualiza o valor do atributo orcamentoDespesa.<BR>
	 * Atributo gerado a partir da coluna ORDE_CD_ORCA_DESPESA.
	 * 
	 * @param orcamentoDespesa
	 *            Novo valor para o atributo orcamentoDespesa.
	 */
	public void setOrcamentoDespesa(final OrcamentoDespesa orcamentoDespesa) {
		this.orcamentoDespesa = orcamentoDespesa;
	}

	/**
	 * Obtem o valor do atributo codigoLogin.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN.
	 * 
	 * @return Valor do atributo codigoLogin.
	 */
	public String getCodigoLogin() {
		return this.codigoLogin;
	}

	/**
	 * Atualiza o valor do atributo codigoLogin.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN.
	 * 
	 * @param codigoLogin
	 *            Novo valor para o atributo codigoLogin.
	 */
	public void setCodigoLogin(final String codigoLogin) {
		this.codigoLogin = codigoLogin;
	}

	/**
	 * @see Object#toString()
	 * @return buffer.
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoOrcDespWl").append("='")
				.append(getCodigoOrcDespWl()).append("' ");
		buffer.append("orcamentoDespesa").append("='")
				.append(getOrcamentoDespesa()).append("' ");
		buffer.append("codigoLogin").append("='").append(getCodigoLogin())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
