/*
 * @(#) PapelAlocacao.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela PAPEL_ALOCACAO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 12/08/2009 17:14:06
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "PAPEL_ALOCACAO")
@NamedQueries({
        @NamedQuery(name = "PapelAlocacao.findAll", query = "SELECT t FROM PapelAlocacao t "
                + "ORDER BY t.nomePapelAlocacao ASC "),

        @NamedQuery(name = "PapelAlocacao.findAllActive", query = "SELECT t FROM PapelAlocacao t "
                + "WHERE (t.indicadorAtivo = 'A') "
                + "ORDER BY t.nomePapelAlocacao ASC "),

        @NamedQuery(name = "PapelAlocacao.findByRecurso", query = "SELECT pa FROM PapelAlocacao pa "
                + "WHERE pa.recurso.codigoRecurso = ?)"),

        @NamedQuery(name = "PapelAlocacao.findByFilter", query = "SELECT paal FROM PapelAlocacao paal "
                + "WHERE (UPPER(paal.nomePapelAlocacao) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + "AND (UPPER(paal.indicadorAtivo) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + "AND (paal.recurso.codigoRecurso = ? OR (? = 0L)) "
                + "ORDER BY paal.nomePapelAlocacao ASC "),

        @NamedQuery(name = "PapelAlocacao.findByFilterFetch", query = "SELECT paal FROM PapelAlocacao paal "
                + "LEFT JOIN FETCH paal.recurso "
                + "WHERE (UPPER(paal.nomePapelAlocacao) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + "AND (UPPER(paal.indicadorAtivo) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
                + "AND (paal.recurso.codigoRecurso = ? OR (? = 0L)) "
                + "ORDER BY paal.nomePapelAlocacao ASC "),

        @NamedQuery(name = "PapelAlocacao.findAllNotTceAssociated", query = "SELECT paal FROM PapelAlocacao paal "
                + "WHERE paal.codigoPapelAlocacao not in ( "
                + "SELECT tcpa.papelAlocacao.codigoPapelAlocacao "
                + "FROM TcePapelAlocacao tcpa "
                + "WHERE ((TRUNC(?) between tcpa.dataInicio and tcpa.dataFim) or "
                + "       (tcpa.dataFim is null and tcpa.dataInicio <= TRUNC(?))) ) "
                + "ORDER BY paal.nomePapelAlocacao ASC ") })
public class PapelAlocacao implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /** Constante para NamedQuery "PapelAlocacao.findByFilter". */
    public static final String FIND_BY_FILTER = "PapelAlocacao.findByFilter";

    /** Constante para NamedQuery "PapelAlocacao.findByFilterFetch". */
    public static final String FIND_BY_FILTER_FETCH = "PapelAlocacao.findByFilterFetch";

    /** Constante para NamedQuery "PapelAlocacao.findByRecurso". */
    public static final String FIND_BY_RECURSO = "PapelAlocacao.findByRecurso";

    /** Constante para NamedQuery "PapelAlocacao.findAllNotTceAssociated". */
    public static final String FIND_ALL_NOT_TCE_ASSOCIATED = "PapelAlocacao.findAllNotTceAssociated";

    /** Lista de TcePapelAlocacao relacionados. */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "papelAlocacao", cascade = CascadeType.ALL)
    private List<TcePapelAlocacao> tcePapelAlocacaos = new ArrayList<TcePapelAlocacao>(
            0);

    /**
     * Relacionamento um pra muitos.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "papelAlocacao")
    private List<BasePapelAlocacao> basePapelAlocacaos = new ArrayList<BasePapelAlocacao>(
            0);

    /**
     * Obtem o valor do atributo tcePapelAlocacaos.<BR>
     * 
     * @return Valor do atributo tcePapelAlocacaos.
     */
    public List<TcePapelAlocacao> getTcePapelAlocacaos() {
        return this.tcePapelAlocacaos;
    }

    /**
     * Atualiza o valor do atributo tcePapelAlocacaos.<BR>
     * 
     * @param tcePapelAlocacaos
     *            Novo valor para o atributo tcePapelAlocacaos.
     */
    public void setTcePapelAlocacaos(
            final List<TcePapelAlocacao> tcePapelAlocacaos) {
        this.tcePapelAlocacaos = tcePapelAlocacaos;
    }

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "PapelAlocacao.findAll".
     */
    public static final String FIND_ALL = "PapelAlocacao.findAll";

    /**
     * Constante para NamedQuery "PapelAlocacao.findAllActive".
     */
    public static final String FIND_ALL_ACTIVE = "PapelAlocacao.findAllActive";

    /**
     * Atributo gerado a partir da coluna PAAL_CD_PAPEL_ALOCACAO.
     */
    @Id
    @GeneratedValue(generator = "PapelAlocacaoSeq")
    @SequenceGenerator(name = "PapelAlocacaoSeq", sequenceName = "SQ_PAAL_CD_PAPEL_ALOCACAO", allocationSize = 1)
    @Column(name = "PAAL_CD_PAPEL_ALOCACAO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoPapelAlocacao;

    /**
     * Atributo gerado a partir da coluna RECU_CD_RECURSO.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "RECU_CD_RECURSO", nullable = false)
    private Recurso recurso;

    /**
     * Atributo gerado a partir da coluna PAAL_NM_PAPEL_ALOCACAO.
     */

    @Column(name = "PAAL_NM_PAPEL_ALOCACAO", length = 240)
    private String nomePapelAlocacao;

    /**
     * Atributo gerado a partir da coluna PAAL_IN_ATIVO.
     */

    @Column(name = "PAAL_IN_ATIVO", length = 1)
    private String indicadorAtivo;

    /**
     * Construtor default.
     */
    public PapelAlocacao() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoPapelAlocacao
     *            Valor do atributo codigoPapelAlocacao;
     * @param recurso
     *            Valor do atributo recurso;
     */
    public PapelAlocacao(final Long codigoPapelAlocacao, final Recurso recurso) {
        this.codigoPapelAlocacao = codigoPapelAlocacao;
        this.recurso = recurso;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoPapelAlocacao
     *            Valor do atributo codigoPapelAlocacao;
     * @param recurso
     *            Valor do atributo recurso;
     * @param nomePapelAlocacao
     *            Valor do atributo nomePapelAlocacao;
     * @param tcePapelAlocacaos
     *            Valor do atributo tcePapelAlocacaos;
     * @param indicadorAtivo
     *            Valor do atributo indicadorAtivo;
     */
    public PapelAlocacao(final Long codigoPapelAlocacao, final Recurso recurso,
            final String nomePapelAlocacao,
            final List<TcePapelAlocacao> tcePapelAlocacaos,
            final String indicadorAtivo) {
        this.codigoPapelAlocacao = codigoPapelAlocacao;
        this.recurso = recurso;
        this.nomePapelAlocacao = nomePapelAlocacao;
        this.tcePapelAlocacaos = tcePapelAlocacaos;
        this.indicadorAtivo = indicadorAtivo;
    }

    /**
     * Obtem o valor do atributo codigoPapelAlocacao.<BR>
     * Atributo gerado a partir da coluna PAAL_CD_PAPEL_ALOCACAO.
     * 
     * @return Valor do atributo codigoPapelAlocacao.
     */
    public Long getCodigoPapelAlocacao() {
        return this.codigoPapelAlocacao;
    }

    /**
     * Atualiza o valor do atributo codigoPapelAlocacao.<BR>
     * Atributo gerado a partir da coluna PAAL_CD_PAPEL_ALOCACAO.
     * 
     * @param codigoPapelAlocacao
     *            Novo valor para o atributo codigoPapelAlocacao.
     */
    public void setCodigoPapelAlocacao(final Long codigoPapelAlocacao) {
        this.codigoPapelAlocacao = codigoPapelAlocacao;
    }

    /**
     * Obtem o valor do atributo recurso.<BR>
     * Atributo gerado a partir da coluna RECU_CD_RECURSO.
     * 
     * @return Valor do atributo recurso.
     */
    public Recurso getRecurso() {
        return this.recurso;
    }

    /**
     * Atualiza o valor do atributo recurso.<BR>
     * Atributo gerado a partir da coluna RECU_CD_RECURSO.
     * 
     * @param recurso
     *            Novo valor para o atributo recurso.
     */
    public void setRecurso(final Recurso recurso) {
        this.recurso = recurso;
    }

    /**
     * Obtem o valor do atributo nomePapelAlocacao.<BR>
     * Atributo gerado a partir da coluna PAAL_NM_PAPEL_ALOCACAO.
     * 
     * @return Valor do atributo nomePapelAlocacao.
     */
    public String getNomePapelAlocacao() {
        return this.nomePapelAlocacao;
    }

    /**
     * Atualiza o valor do atributo nomePapelAlocacao.<BR>
     * Atributo gerado a partir da coluna PAAL_NM_PAPEL_ALOCACAO.
     * 
     * @param nomePapelAlocacao
     *            Novo valor para o atributo nomePapelAlocacao.
     */
    public void setNomePapelAlocacao(final String nomePapelAlocacao) {
        this.nomePapelAlocacao = nomePapelAlocacao;
    }

    /**
     * Obtem o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna PAAL_IN_ATIVO.
     * 
     * @return Valor do atributo indicadorAtivo.
     */
    public String getIndicadorAtivo() {
        return this.indicadorAtivo;
    }

    /**
     * Atualiza o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna PAAL_IN_ATIVO.
     * 
     * @param indicadorAtivo
     *            Novo valor para o atributo indicadorAtivo.
     */
    public void setIndicadorAtivo(final String indicadorAtivo) {
        this.indicadorAtivo = indicadorAtivo;
    }

    /**
     * @return the basePapelAlocacaos
     */
    public List<BasePapelAlocacao> getBasePapelAlocacaos() {
        return basePapelAlocacaos;
    }

    /**
     * @param basePapelAlocacaos
     *            the basePapelAlocacaos to set
     */
    public void setBasePapelAlocacaos(
            final List<BasePapelAlocacao> basePapelAlocacaos) {
        this.basePapelAlocacaos = basePapelAlocacaos;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoPapelAlocacao").append("='").append(
                getCodigoPapelAlocacao()).append("' ");
        buffer.append("recurso").append("='").append(getRecurso()).append("' ");
        buffer.append("nomePapelAlocacao").append("='").append(
                getNomePapelAlocacao()).append("' ");
        buffer.append("indicadorAtivo").append("='")
                .append(getIndicadorAtivo()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}