/*
 * @(#) PerfilPadrao.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Entity gerado a partir da tabela PERFIL_PADRAO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 06/07/2012 16:34:23
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "PERFIL_PADRAO", uniqueConstraints = @UniqueConstraint(columnNames = {
        "CIBA_CD_CIDADE_BASE", "PEMG_CD_PMG", "CAPM_CD_CARGO_PMS"}))
@NamedQueries({
        @NamedQuery(name = "PerfilPadrao.findAll", query = "SELECT t FROM PerfilPadrao t"),
        @NamedQuery(name = "PerfilPadrao.findByCargoPmgAndCidadeBase", query = "SELECT t FROM PerfilPadrao t "
                + "WHERE t.cargoPms.codigoCargoPms = ? AND "
                + "t.pmg.codigoPmg = ? AND "
                + "t.cidadeBase.codigoCidadeBase = ?"),
         @NamedQuery(name = "PerfilPadrao.findByCargoPms", query = "SELECT t FROM PerfilPadrao t WHERE t.cargoPms.codigoCargoPms = ?")       
})
public class PerfilPadrao implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "PerfilPadrao.findAll".
     */
    public static final String FIND_ALL = "PerfilPadrao.findAll";
    
    /**
    * Constante para NamedQuery "PerfilPadrao.findAll".
    */
   public static final String FIND_BY_CARGO_PMG_AND_CIDADEBASE = "PerfilPadrao.findByCargoPmgAndCidadeBase";
   
   /**
    * Constante para namedquery.
    */
   public static final String FIND_BY_CARGO_PMS = "PerfilPadrao.findByCargoPms";

    /**
     * Atributo gerado a partir da coluna PEPA_CD_PERFIL_PADRAO.
     */
    @Id
    @GeneratedValue(generator = "PerfilPadraoSeq")
    @SequenceGenerator(name = "PerfilPadraoSeq", sequenceName = "SQ_PEPA_CD_PERFIL_PADRAO", allocationSize = 1)
    @Column(name = "PEPA_CD_PERFIL_PADRAO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoPerfilPadrao;

    /**
     * Atributo gerado a partir da coluna PEMG_CD_PMG.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PEMG_CD_PMG", nullable = false)
    private Pmg pmg;

    /**
     * Atributo gerado a partir da coluna CAPM_CD_CARGO_PMS.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CAPM_CD_CARGO_PMS")
    private CargoPms cargoPms;

    /**
     * Atributo gerado a partir da coluna CIBA_CD_CIDADE_BASE.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CIBA_CD_CIDADE_BASE", nullable = false)
    private CidadeBase cidadeBase;

    /**
     * Atributo gerado a partir da coluna PEPA_IN_ATIVO.
     */

    @Column(name = "PEPA_IN_ATIVO", length = 1)
    private String indicadorAtivo;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "perfilPadrao")
    private Set<ItemTabPerPadrao> itemTabPerPadraos =
            new HashSet<ItemTabPerPadrao>(0);

    /**
     * Construtor default.
     */
    public PerfilPadrao() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoPerfilPadrao
     *            Valor do atributo codigoPerfilPadrao;
     * @param pmg
     *            Valor do atributo pmg;
     * @param cidadeBase
     *            Valor do atributo cidadeBase;
     */
    public PerfilPadrao(Long codigoPerfilPadrao, Pmg pmg, CidadeBase cidadeBase) {
        this.codigoPerfilPadrao = codigoPerfilPadrao;
        this.pmg = pmg;
        this.cidadeBase = cidadeBase;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoPerfilPadrao
     *            Valor do atributo codigoPerfilPadrao;
     * @param pmg
     *            Valor do atributo pmg;
     * @param cargoPms
     *            Valor do atributo cargoPms;
     * @param cidadeBase
     *            Valor do atributo cidadeBase;
     * @param indicadorAtivo
     *            Valor do atributo indicadorAtivo;
     * @param itemTabPerPadraos
     *            Valor do atributo itemTabPerPadraos;
     */
    public PerfilPadrao(Long codigoPerfilPadrao, Pmg pmg, CargoPms cargoPms,
            CidadeBase cidadeBase, String indicadorAtivo,
            Set<ItemTabPerPadrao> itemTabPerPadraos) {
        this.codigoPerfilPadrao = codigoPerfilPadrao;
        this.pmg = pmg;
        this.cargoPms = cargoPms;
        this.cidadeBase = cidadeBase;
        this.indicadorAtivo = indicadorAtivo;
        this.itemTabPerPadraos = itemTabPerPadraos;
    }

    /**
     * Obtem o valor do atributo codigoPerfilPadrao.<BR>
     * Atributo gerado a partir da coluna PEPA_CD_PERFIL_PADRAO.
     * 
     * @return Valor do atributo codigoPerfilPadrao.
     */
    public Long getCodigoPerfilPadrao() {
        return this.codigoPerfilPadrao;
    }

    /**
     * Atualiza o valor do atributo codigoPerfilPadrao.<BR>
     * Atributo gerado a partir da coluna PEPA_CD_PERFIL_PADRAO.
     * 
     * @param codigoPerfilPadrao
     *            Novo valor para o atributo codigoPerfilPadrao.
     */
    public void setCodigoPerfilPadrao(final Long codigoPerfilPadrao) {
        this.codigoPerfilPadrao = codigoPerfilPadrao;
    }

    /**
     * Obtem o valor do atributo pmg.<BR>
     * Atributo gerado a partir da coluna PEMG_CD_PMG.
     * 
     * @return Valor do atributo pmg.
     */
    public Pmg getPmg() {
        return this.pmg;
    }

    /**
     * Atualiza o valor do atributo pmg.<BR>
     * Atributo gerado a partir da coluna PEMG_CD_PMG.
     * 
     * @param pmg
     *            Novo valor para o atributo pmg.
     */
    public void setPmg(final Pmg pmg) {
        this.pmg = pmg;
    }

    /**
     * Obtem o valor do atributo cargoPms.<BR>
     * Atributo gerado a partir da coluna CAPM_CD_CARGO_PMS.
     * 
     * @return Valor do atributo cargoPms.
     */
    public CargoPms getCargoPms() {
        return this.cargoPms;
    }

    /**
     * Atualiza o valor do atributo cargoPms.<BR>
     * Atributo gerado a partir da coluna CAPM_CD_CARGO_PMS.
     * 
     * @param cargoPms
     *            Novo valor para o atributo cargoPms.
     */
    public void setCargoPms(final CargoPms cargoPms) {
        this.cargoPms = cargoPms;
    }

    /**
     * Obtem o valor do atributo cidadeBase.<BR>
     * Atributo gerado a partir da coluna CIBA_CD_CIDADE_BASE.
     * 
     * @return Valor do atributo cidadeBase.
     */
    public CidadeBase getCidadeBase() {
        return this.cidadeBase;
    }

    /**
     * Atualiza o valor do atributo cidadeBase.<BR>
     * Atributo gerado a partir da coluna CIBA_CD_CIDADE_BASE.
     * 
     * @param cidadeBase
     *            Novo valor para o atributo cidadeBase.
     */
    public void setCidadeBase(final CidadeBase cidadeBase) {
        this.cidadeBase = cidadeBase;
    }

    /**
     * Obtem o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna PEPA_IN_ATIVO.
     * 
     * @return Valor do atributo indicadorAtivo.
     */
    public String getIndicadorAtivo() {
        return this.indicadorAtivo;
    }

    /**
     * Atualiza o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna PEPA_IN_ATIVO.
     * 
     * @param indicadorAtivo
     *            Novo valor para o atributo indicadorAtivo.
     */
    public void setIndicadorAtivo(final String indicadorAtivo) {
        this.indicadorAtivo = indicadorAtivo;
    }

    /**
     * Obtem o valor do atributo itemTabPerPadraos.<BR>
     * 
     * @return Valor do atributo itemTabPerPadraos.
     */
    public Set<ItemTabPerPadrao> getItemTabPerPadraos() {
        return this.itemTabPerPadraos;
    }

    /**
     * Atualiza o valor do atributo itemTabPerPadraos.<BR>
     * 
     * @param itemTabPerPadraos
     *            Novo valor para o atributo itemTabPerPadraos.
     */
    public void setItemTabPerPadraos(
            final Set<ItemTabPerPadrao> itemTabPerPadraos) {
        this.itemTabPerPadraos = itemTabPerPadraos;
    }

    /**
     * @see Object#toString()
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoPerfilPadrao").append("='").append(
                getCodigoPerfilPadrao()).append("' ");
        buffer.append("pmg").append("='").append(getPmg()).append("' ");
        buffer.append("cargoPms").append("='").append(getCargoPms()).append(
                "' ");
        buffer.append("cidadeBase").append("='").append(getCidadeBase())
                .append("' ");
        buffer.append("indicadorAtivo").append("='")
                .append(getIndicadorAtivo()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
