/*
 * @(#) PessoaPessoa.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela PESSOA_PESSOA.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 17/02/2011 14:17:22
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "PESSOA_PESSOA")
@NamedQueries({
        @NamedQuery(name = "PessoaPessoa.findAll", query = "SELECT t FROM PessoaPessoa t"),

        @NamedQuery(name = "PessoaPessoa.findByPessoaAndPessoaFlwer", query = "SELECT pepe FROM PessoaPessoa pepe "
                + " WHERE pepe.pessoa.codigoPessoa = ?"
                + " AND pepe.pessoaFlwer.codigoPessoa = ?"),

        @NamedQuery(name = "PessoaPessoa.findByPessoa", query = "SELECT pepe FROM PessoaPessoa pepe "
                + " WHERE pepe.pessoa.codigoPessoa = ?"),

        @NamedQuery(name = "PessoaPessoa.findByPessoaFlwer", query = "SELECT pepe FROM PessoaPessoa pepe "
                + " WHERE pepe.pessoaFlwer.codigoPessoa = ?"),

        @NamedQuery(name = "PessoaPessoa.findByCodigoMD5", query = "SELECT pepe FROM PessoaPessoa pepe "
                + " WHERE pepe.codigoMD5 = ?") 
})
public class PessoaPessoa implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /** Constante para NamedQuery "PessoaPessoa.findByPessoaAndPessoaFlwer". */
    public static final String FIND_BY_PESSOA_AND_PESSOA_FLWER = "PessoaPessoa.findByPessoaAndPessoaFlwer";

    /** Constante para NamedQuery "PessoaPessoa.findByPessoa". */
    public static final String FIND_BY_PESSOA = "PessoaPessoa.findByPessoa";

    /** Constante para NamedQuery "PessoaPessoa.findByPessoaFlwer". */
    public static final String FIND_BY_PESSOA_FLWER = "PessoaPessoa.findByPessoaFlwer";

    /** Constante para NamedQuery "PessoaPessoa.findByCodigoMD5". */
    public static final String FIND_BY_CODIGO_MD5 = "PessoaPessoa.findByCodigoMD5";

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "PessoaPessoa.findAll".
     */
    public static final String FIND_ALL = "PessoaPessoa.findAll";

    /**
     * Atributo gerado a partir da coluna PEPE_CD_PESSOA_PESSOA.
     */
    @Id
    @GeneratedValue(generator = "PessoaPessoaSeq")
    @SequenceGenerator(name = "PessoaPessoaSeq", sequenceName = "SQ_PEPE_CD_PESSOA_PESSOA", allocationSize = 1)
    @Column(name = "PEPE_CD_PESSOA_PESSOA", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoPessoaPessoa;

    /**
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PESS_CD_PESSOA", nullable = false)
    private Pessoa pessoa;

    /**
     * Atributo gerado a partir da coluna PESS_CD_PESSOA_FLWER.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PESS_CD_PESSOA_FLWER", nullable = false)
    private Pessoa pessoaFlwer;

    /**
     * Atributo gerado a partir da coluna PEPE_CD_MD5.
     */
    @Column(name = "PEPE_CD_MD5", length = 100)
    private String codigoMD5;

    /**
     * Construtor default.
     */
    public PessoaPessoa() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoPessoaPessoa
     *            Valor do atributo codigoPessoaPessoa;
     * @param pessoa
     *            Valor do atributo pessoa;
     * @param pessoaFlwer
     *            Valor do atributo pessoaFlwer;
     * @param codigoMD5
     *            Valor do atributo codigoMD5;
     */
    public PessoaPessoa(final Long codigoPessoaPessoa, final Pessoa pessoa,
            final Pessoa pessoaFlwer, final String codigoMD5) {
        this.codigoPessoaPessoa = codigoPessoaPessoa;
        this.pessoa = pessoa;
        this.pessoaFlwer = pessoaFlwer;
        this.codigoMD5 = codigoMD5;
    }

    /**
     * Obtem o valor do atributo codigoPessoaPessoa.<BR>
     * Atributo gerado a partir da coluna PEPE_CD_PESSOA_PESSOA.
     * 
     * @return Valor do atributo codigoPessoaPessoa.
     */
    public Long getCodigoPessoaPessoa() {
        return this.codigoPessoaPessoa;
    }

    /**
     * Atualiza o valor do atributo codigoPessoaPessoa.<BR>
     * Atributo gerado a partir da coluna PEPE_CD_PESSOA_PESSOA.
     * 
     * @param codigoPessoaPessoa
     *            Novo valor para o atributo codigoPessoaPessoa.
     */
    public void setCodigoPessoaPessoa(final Long codigoPessoaPessoa) {
        this.codigoPessoaPessoa = codigoPessoaPessoa;
    }

    /**
     * Obtem o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     * 
     * @return Valor do atributo pessoa.
     */
    public Pessoa getPessoa() {
        return this.pessoa;
    }

    /**
     * Atualiza o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     * 
     * @param pessoa
     *            Novo valor para o atributo pessoa.
     */
    public void setPessoa(final Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    /**
     * Obtem o valor do atributo pessoaFlwer.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA_FLWER.
     * 
     * @return Valor do atributo pessoaFlwer.
     */
    public Pessoa getPessoaFlwer() {
        return this.pessoaFlwer;
    }

    /**
     * Atualiza o valor do atributo pessoaFlwer.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA_FLWER.
     * 
     * @param pessoaFlwer
     *            Novo valor para o atributo pessoaFlwer.
     */
    public void setPessoaFlwer(final Pessoa pessoaFlwer) {
        this.pessoaFlwer = pessoaFlwer;
    }

    /**
     * Obtem o valor do atributo codigoMD5.<BR>
     * Atributo gerado a partir da coluna PEPE_CD_MD5.
     * 
     * @return Valor do atributo codigoMD5.
     */
    public String getCodigoMD5() {
        return this.codigoMD5;
    }

    /**
     * Atualiza o valor do atributo codigoMD5.<BR>
     * Atributo gerado a partir da coluna PEPE_CD_MD5.
     * 
     * @param codigoMD5
     *            Novo valor para o atributo codigoMD5.
     */
    public void setCodigoMD5(final String codigoMD5) {
        this.codigoMD5 = codigoMD5;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoPessoaPessoa").append("='").append(
                getCodigoPessoaPessoa()).append("' ");
        buffer.append("pessoa").append("='").append(getPessoa()).append("' ");
        buffer.append("pessoaFlwer").append("='").append(getPessoaFlwer())
                .append("' ");
        buffer.append("codigoMD5").append("='").append(getCodigoMD5())
                .append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}