/*
 * @(#) PessoaSalario.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela PESSOA_SALARIO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 30/07/2010 11:47:09
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "PESSOA_SALARIO")
@NamedQueries({
        @NamedQuery(name = "PessoaSalario.findAll", query = "SELECT t FROM PessoaSalario t"),

        @NamedQuery(name = "PessoaSalario.findByStartDate", query = " SELECT t FROM PessoaSalario t "
                + " WHERE t.dataInicio = ? " 
                + " AND t.pessoa.codigoPessoa = ?"),

        @NamedQuery(name = "PessoaSalario.findPrevious", query = "SELECT t FROM PessoaSalario t"
                + " WHERE t.pessoa.codigoPessoa = ? "
                + " AND TRUNC(t.dataInicio) = "
                + "     (SELECT MAX(TRUNC(psBefore.dataInicio)) "
                + "         FROM PessoaSalario psBefore "
                + "         WHERE psBefore.pessoa.codigoPessoa = ?"
                + "         AND psBefore.dataInicio < ?)"),

        @NamedQuery(name = "PessoaSalario.findNext", query = "SELECT t FROM PessoaSalario t"
                + " WHERE t.pessoa.codigoPessoa = ? "
                + " AND TRUNC(t.dataInicio) = "
                + "     (SELECT MIN(TRUNC(psNext.dataInicio)) "
                + "         FROM PessoaSalario psNext "
                + "         WHERE psNext.pessoa.codigoPessoa = ?"
                + "         AND psNext.dataInicio > ?)"),

        @NamedQuery(name = "PessoaSalario.findByPessoaAndDate", query = "SELECT t FROM PessoaSalario t"
                + " WHERE t.pessoa.codigoPessoa = ? "
                + " AND ((TRUNC(?) between t.dataInicio and t.dataFim) or "
                + "       (t.dataFim is null and t.dataInicio <= TRUNC(?))) ")

})
@Deprecated
public class PessoaSalario implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /** Constante para NamedQuery "PessoaSalario.findByStartDate". */
    public static final String FIND_BY_START_DATE = "PessoaSalario.findByStartDate";

    /** Constante para NamedQuery "PessoaSalario.findPrevious". */
    public static final String FIND_PREVIOUS = "PessoaSalario.findPrevious";

    /** Constante para NamedQuery "PessoaSalario.findNext". */
    public static final String FIND_NEXT = "PessoaSalario.findNext";

    /** Constante para NamedQuery "PessoaSalario.findByPessoaAndDate". */
    public static final String FIND_BY_PESSOA_AND_DATE = "PessoaSalario.findByPessoaAndDate";

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "PessoaSalario.findAll".
     */
    public static final String FIND_ALL = "PessoaSalario.findAll";

    /**
     * Atributo gerado a partir da coluna PESA_CD_PESSOA_SALARIO.
     */
    @Id
    @GeneratedValue(generator = "PessoaSalarioSeq")
    @SequenceGenerator(name = "PessoaSalarioSeq", sequenceName = "SQ_PESA_CD_PESSOA_SALARIO", allocationSize = 1)
    @Column(name = "PESA_CD_PESSOA_SALARIO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoPessoaSalario;

    /**
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PESS_CD_PESSOA", nullable = false)
    private Pessoa pessoa;

    /**
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MOED_CD_MOEDA", nullable = false)
    private Moeda moeda;

    /**
     * Atributo gerado a partir da coluna PESA_VL_SALARIO.
     */

    @Column(name = "PESA_VL_SALARIO", precision = 22, scale = 0)
    private BigDecimal valorSalario;

    /**
     * Atributo gerado a partir da coluna PESA_VL_HORA.
     */

    @Column(name = "PESA_VL_HORA", precision = 22, scale = 0)
    private BigDecimal valorHora;

    /**
     * Atributo gerado a partir da coluna PESA_DT_INICIO.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "PESA_DT_INICIO", length = 7)
    private Date dataInicio;

    /**
     * Atributo gerado a partir da coluna PESA_DT_FIM.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "PESA_DT_FIM", length = 7)
    private Date dataFim;

    /**
     * Atributo gerado a partir da coluna PESA_DT_CRIACAO.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "PESA_DT_CRIACAO")
    private Date dataCriacao;

    /**
     * Construtor default.
     */
    public PessoaSalario() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoPessoaSalario
     *            Valor do atributo codigoPessoaSalario;
     * @param pessoa
     *            Valor do atributo pessoa;
     * @param moeda
     *            Valor do atributo moeda;
     */
    public PessoaSalario(final Long codigoPessoaSalario, final Pessoa pessoa,
            final Moeda moeda) {
        this.codigoPessoaSalario = codigoPessoaSalario;
        this.pessoa = pessoa;
        this.moeda = moeda;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoPessoaSalario
     *            Valor do atributo codigoPessoaSalario;
     * @param pessoa
     *            Valor do atributo pessoa;
     * @param moeda
     *            Valor do atributo moeda;
     * @param valorSalario
     *            Valor do atributo valorSalario;
     * @param valorHora
     *            Valor do atributo valorHora;
     * @param dataInicio
     *            Valor do atributo dataInicio;
     * @param dataFim
     *            Valor do atributo dataFim;
     * @param dataCriacao
     *            Valor do atributo dataCriacao;
     */
    public PessoaSalario(final Long codigoPessoaSalario, final Pessoa pessoa,
            final Moeda moeda, final BigDecimal valorSalario,
            final BigDecimal valorHora, final Date dataInicio,
            final Date dataFim, final Date dataCriacao) {
        this.codigoPessoaSalario = codigoPessoaSalario;
        this.pessoa = pessoa;
        this.moeda = moeda;
        this.valorSalario = valorSalario;
        this.valorHora = valorHora;
        this.dataInicio = dataInicio;
        this.dataFim = dataFim;
        this.dataCriacao = dataCriacao;
    }

    /**
     * Obtem o valor do atributo codigoPessoaSalario.<BR>
     * Atributo gerado a partir da coluna PESA_CD_PESSOA_SALARIO.
     * 
     * @return Valor do atributo codigoPessoaSalario.
     */
    public Long getCodigoPessoaSalario() {
        return this.codigoPessoaSalario;
    }

    /**
     * Atualiza o valor do atributo codigoPessoaSalario.<BR>
     * Atributo gerado a partir da coluna PESA_CD_PESSOA_SALARIO.
     * 
     * @param codigoPessoaSalario
     *            Novo valor para o atributo codigoPessoaSalario.
     */
    public void setCodigoPessoaSalario(final Long codigoPessoaSalario) {
        this.codigoPessoaSalario = codigoPessoaSalario;
    }

    /**
     * Obtem o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     * 
     * @return Valor do atributo pessoa.
     */
    public Pessoa getPessoa() {
        return this.pessoa;
    }

    /**
     * Atualiza o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     * 
     * @param pessoa
     *            Novo valor para o atributo pessoa.
     */
    public void setPessoa(final Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    /**
     * Obtem o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * 
     * @return Valor do atributo moeda.
     */
    public Moeda getMoeda() {
        return this.moeda;
    }

    /**
     * Atualiza o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * 
     * @param moeda
     *            Novo valor para o atributo moeda.
     */
    public void setMoeda(final Moeda moeda) {
        this.moeda = moeda;
    }

    /**
     * Obtem o valor do atributo valorSalario.<BR>
     * Atributo gerado a partir da coluna PESA_VL_SALARIO.
     * 
     * @return Valor do atributo valorSalario.
     */
    public BigDecimal getValorSalario() {
        return this.valorSalario;
    }

    /**
     * Atualiza o valor do atributo valorSalario.<BR>
     * Atributo gerado a partir da coluna PESA_VL_SALARIO.
     * 
     * @param valorSalario
     *            Novo valor para o atributo valorSalario.
     */
    public void setValorSalario(final BigDecimal valorSalario) {
        this.valorSalario = valorSalario;
    }

    /**
     * Obtem o valor do atributo valorHora.<BR>
     * Atributo gerado a partir da coluna PESA_VL_HORA.
     * 
     * @return Valor do atributo valorHora.
     */
    public BigDecimal getValorHora() {
        return this.valorHora;
    }

    /**
     * Atualiza o valor do atributo valorHora.<BR>
     * Atributo gerado a partir da coluna PESA_VL_HORA.
     * 
     * @param valorHora
     *            Novo valor para o atributo valorHora.
     */
    public void setValorHora(final BigDecimal valorHora) {
        this.valorHora = valorHora;
    }

    /**
     * Obtem o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna PESA_DT_INICIO.
     * 
     * @return Valor do atributo dataInicio.
     */
    public Date getDataInicio() {
        return this.dataInicio;
    }

    /**
     * Atualiza o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna PESA_DT_INICIO.
     * 
     * @param dataInicio
     *            Novo valor para o atributo dataInicio.
     */
    public void setDataInicio(final Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    /**
     * Obtem o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna PESA_DT_FIM.
     * 
     * @return Valor do atributo dataFim.
     */
    public Date getDataFim() {
        return this.dataFim;
    }

    /**
     * Atualiza o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna PESA_DT_FIM.
     * 
     * @param dataFim
     *            Novo valor para o atributo dataFim.
     */
    public void setDataFim(final Date dataFim) {
        this.dataFim = dataFim;
    }

    /**
     * Obtem o valor do atributo dataCriacao.<BR>
     * Atributo gerado a partir da coluna PESA_DT_CRIACAO.
     * 
     * @return Valor do atributo dataCriacao.
     */
    public Date getDataCriacao() {
        return this.dataCriacao;
    }

    /**
     * Atualiza o valor do atributo dataCriacao.<BR>
     * Atributo gerado a partir da coluna PESA_DT_CRIACAO.
     * 
     * @param dataCriacao
     *            Novo valor para o atributo dataCriacao.
     */
    public void setDataCriacao(final Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    /**
     * @see Object#toString()
     * 
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoPessoaSalario").append("='").append(
                getCodigoPessoaSalario()).append("' ");
        buffer.append("pessoa").append("='").append(getPessoa()).append("' ");
        buffer.append("moeda").append("='").append(getMoeda()).append("' ");
        buffer.append("valorSalario").append("='").append(getValorSalario())
                .append("' ");
        buffer.append("valorHora").append("='").append(getValorHora()).append(
                "' ");
        buffer.append("dataInicio").append("='").append(getDataInicio())
                .append("' ");
        buffer.append("dataFim").append("='").append(getDataFim()).append("' ");
        buffer.append("dataCriacao").append("='").append(getDataFim()).append(
                "' ");
        buffer.append("]");

        return buffer.toString();
    }

}