/*
 * @(#) PessoaTipoContrato.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela PESSOA_TIPO_CONTRATO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 23/07/2010 15:55:11
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "PESSOA_TIPO_CONTRATO")
@NamedQueries({
        @NamedQuery(name = "PessoaTipoContrato.findAll", query = "SELECT t FROM PessoaTipoContrato t"),

        @NamedQuery(name = "PessoaTipoContrato.findByStartDate", query = " SELECT t FROM PessoaTipoContrato t "
                + " WHERE t.dataInicio = ? " + " AND t.pessoa.codigoPessoa = ?"),

        @NamedQuery(name = "PessoaTipoContrato.findPrevious", query = "SELECT t FROM PessoaTipoContrato t"
                + " WHERE t.pessoa.codigoPessoa = ? "
                + " AND TRUNC(t.dataInicio) = "
                + "     (SELECT MAX(TRUNC(ptcBefore.dataInicio)) "
                + "         FROM PessoaTipoContrato ptcBefore "
                + "         WHERE ptcBefore.pessoa.codigoPessoa = ?"
                + "         AND ptcBefore.dataInicio < ?)"),

        @NamedQuery(name = "PessoaTipoContrato.findNext", query = "SELECT t FROM PessoaTipoContrato t"
                + " WHERE t.pessoa.codigoPessoa = ? "
                + " AND TRUNC(t.dataInicio) = "
                + "     (SELECT MIN(TRUNC(ptcNext.dataInicio)) "
                + "         FROM PessoaTipoContrato ptcNext "
                + "         WHERE ptcNext.pessoa.codigoPessoa = ?"
                + "         AND ptcNext.dataInicio > ?)"),

        @NamedQuery(name = "PessoaTipoContrato.findByPessoaAndDate", query = "SELECT t FROM PessoaTipoContrato t"
                + " WHERE t.pessoa.codigoPessoa = ? "
                + " AND ((TRUNC(?) between t.dataInicio and t.dataFim) or "
                + "       (t.dataFim is null and t.dataInicio <= TRUNC(?))) "),

        @NamedQuery(name = "PessoaTipoContrato.findByPessoaInAndDate", query = "SELECT t FROM PessoaTipoContrato t"
                + " WHERE t.pessoa.codigoPessoa in :peopleCodes "
                + " AND ((TRUNC(:month) between t.dataInicio and t.dataFim) or "
                + "       (t.dataFim is null and t.dataInicio <= TRUNC(:month))) ")

})
public class PessoaTipoContrato implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /** Constante para NamedQuery "PessoaTipoContrato.findByStartDate". */
    public static final String FIND_BY_START_DATE = "PessoaTipoContrato.findByStartDate";

    /** Constante para NamedQuery "PessoaTipoContrato.findPrevious". */
    public static final String FIND_PREVIOUS = "PessoaTipoContrato.findPrevious";

    /** Constante para NamedQuery "PessoaTipoContrato.findNext". */
    public static final String FIND_NEXT = "PessoaTipoContrato.findNext";

    /** Constante para NamedQuery "PessoaTipoContrato.findByPessoaAndDate". */
    public static final String FIND_BY_PESSOA_AND_DATE = "PessoaTipoContrato.findByPessoaAndDate";

    /** Constante para NamedQuery "PessoaTipoContrato.findByPessoaAndDate". */
    public static final String FIND_BY_PESSOA_IN_AND_DATE = "PessoaTipoContrato.findByPessoaInAndDate";

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "PessoaTipoContrato.findAll".
     */
    public static final String FIND_ALL = "PessoaTipoContrato.findAll";

    /**
     * Atributo gerado a partir da coluna PETC_CD_PESSOA_TP_CONTRATO.
     */
    @Id
    @GeneratedValue(generator = "PessoaTipoContratoSeq")
    @SequenceGenerator(name = "PessoaTipoContratoSeq", 
            sequenceName = "SQ_PETC_CD_PESSOA_TP_CONTRATO", allocationSize = 1)
    @Column(name = "PETC_CD_PESSOA_TP_CONTRATO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoPessoaTpContrato;

    /**
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PESS_CD_PESSOA", nullable = false)
    private Pessoa pessoa;

    /**
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TICO_CD_TIPO_CONTRATO", nullable = false)
    private TipoContrato tipoContrato;

    /**
     * Atributo gerado a partir da coluna EMPR_CD_EMPRESA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EMPR_CD_EMPRESA")
    private Empresa empresa;

    /**
     * Atributo gerado a partir da coluna PETC_PR_ALOCAVEL.
     */

    @Column(name = "PETC_PR_ALOCAVEL", precision = 10)
    private BigDecimal percentualAlocavel;

    /**
     * Atributo gerado a partir da coluna PETC_DT_INICIO.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "PETC_DT_INICIO", length = 7)
    private Date dataInicio;

    /**
     * Atributo gerado a partir da coluna PETC_DT_FIM.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "PETC_DT_FIM", length = 7)
    private Date dataFim;

    /**
     * Atributo gerado a partir da coluna PETC_DT_CRIACAO.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "PETC_DT_CRIACAO")
    private Date dataCriacao;

    /**
     * Atributo gerado a partir da coluna PETC_VL_JORNADA.
     */

    @Column(name = "PETC_VL_JORNADA", precision = 22, scale = 0)
    private BigDecimal valorJornada;

    /**
     * Construtor default.
     */
    public PessoaTipoContrato() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoPessoaTpContrato
     *            Valor do atributo codigoPessoaTpContrato;
     * @param pessoa
     *            Valor do atributo pessoa;
     * @param tipoContrato
     *            Valor do atributo tipoContrato;
     * @param empresa
     *            Valor do atributo empresa;
     */
    public PessoaTipoContrato(final Long codigoPessoaTpContrato,
            final Pessoa pessoa, final TipoContrato tipoContrato,
            final Empresa empresa) {
        this.codigoPessoaTpContrato = codigoPessoaTpContrato;
        this.pessoa = pessoa;
        this.tipoContrato = tipoContrato;
        this.empresa = empresa;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoPessoaTpContrato
     *            Valor do atributo codigoPessoaTpContrato;
     * @param pessoa
     *            Valor do atributo pessoa;
     * @param tipoContrato
     *            Valor do atributo tipoContrato;
     * @param empresa
     *            Valor do atributo empresa;
     * @param percentualAlocavel
     *            Valor do atributo percentualAlocavel;
     * @param dataInicio
     *            Valor do atributo dataInicio;
     * @param dataFim
     *            Valor do atributo dataFim;
     * @param dataCriacao
     *            Valor do atributo dataCriacao;
     * @param valorJornada
     *            Valor do atributo valorJornada;
     */
    public PessoaTipoContrato(final Long codigoPessoaTpContrato,
            final Pessoa pessoa, final TipoContrato tipoContrato,
            final Empresa empresa, final BigDecimal percentualAlocavel,
            final Date dataInicio, final Date dataFim, final Date dataCriacao,
            final BigDecimal valorJornada) {
        this.codigoPessoaTpContrato = codigoPessoaTpContrato;
        this.pessoa = pessoa;
        this.tipoContrato = tipoContrato;
        this.percentualAlocavel = percentualAlocavel;
        this.dataInicio = dataInicio;
        this.dataFim = dataFim;
        this.dataCriacao = dataCriacao;
        this.valorJornada = valorJornada;
    }

    /**
     * Obtem o valor do atributo codigoPessoaTpContrato.<BR>
     * Atributo gerado a partir da coluna PETC_CD_PESSOA_TP_CONTRATO.
     * 
     * @return Valor do atributo codigoPessoaTpContrato.
     */
    public Long getCodigoPessoaTpContrato() {
        return this.codigoPessoaTpContrato;
    }

    /**
     * Atualiza o valor do atributo codigoPessoaTpContrato.<BR>
     * Atributo gerado a partir da coluna PETC_CD_PESSOA_TP_CONTRATO.
     * 
     * @param codigoPessoaTpContrato
     *            Novo valor para o atributo codigoPessoaTpContrato.
     */
    public void setCodigoPessoaTpContrato(final Long codigoPessoaTpContrato) {
        this.codigoPessoaTpContrato = codigoPessoaTpContrato;
    }

    /**
     * Obtem o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     * 
     * @return Valor do atributo pessoa.
     */
    public Pessoa getPessoa() {
        return this.pessoa;
    }

    /**
     * Atualiza o valor do atributo pessoa.<BR>
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     * 
     * @param pessoa
     *            Novo valor para o atributo pessoa.
     */
    public void setPessoa(final Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    /**
     * Obtem o valor do atributo tipoContrato.<BR>
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     * 
     * @return Valor do atributo tipoContrato.
     */
    public TipoContrato getTipoContrato() {
        return this.tipoContrato;
    }

    /**
     * Atualiza o valor do atributo tipoContrato.<BR>
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     * 
     * @param tipoContrato
     *            Novo valor para o atributo tipoContrato.
     */
    public void setTipoContrato(final TipoContrato tipoContrato) {
        this.tipoContrato = tipoContrato;
    }

    /**
     * Obtem o valor do atributo empresa.<BR>
     * Atributo gerado a partir da coluna EMPR_CD_EMPRESA.
     * 
     * @return Valor do atributo empresa.
     */
    public Empresa getEmpresa() {
        return this.empresa;
    }

    /**
     * Atualiza o valor do atributo empresa.<BR>
     * Atributo gerado a partir da coluna EMPR_CD_EMPRESA.
     * 
     * @param empresa
     *            Novo valor para o atributo empresa.
     */
    public void setEmpresa(final Empresa empresa) {
        this.empresa = empresa;
    }

    /**
     * Obtem o valor do atributo percentualAlocavel.<BR>
     * Atributo gerado a partir da coluna PETC_PR_ALOCAVEL.
     * 
     * @return Valor do atributo percentualAlocavel.
     */
    public BigDecimal getPercentualAlocavel() {
        return this.percentualAlocavel;
    }

    /**
     * Atualiza o valor do atributo percentualAlocavel.<BR>
     * Atributo gerado a partir da coluna PETC_PR_ALOCAVEL.
     * 
     * @param percentualAlocavel
     *            Novo valor para o atributo percentualAlocavel.
     */
    public void setPercentualAlocavel(final BigDecimal percentualAlocavel) {
        this.percentualAlocavel = percentualAlocavel;
    }

    /**
     * Obtem o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna PETC_DT_INICIO.
     * 
     * @return Valor do atributo dataInicio.
     */
    public Date getDataInicio() {
        return this.dataInicio;
    }

    /**
     * Atualiza o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna PETC_DT_INICIO.
     * 
     * @param dataInicio
     *            Novo valor para o atributo dataInicio.
     */
    public void setDataInicio(final Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    /**
     * Obtem o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna PETC_DT_FIM.
     * 
     * @return Valor do atributo dataFim.
     */
    public Date getDataFim() {
        return this.dataFim;
    }

    /**
     * Atualiza o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna PETC_DT_FIM.
     * 
     * @param dataFim
     *            Novo valor para o atributo dataFim.
     */
    public void setDataFim(final Date dataFim) {
        this.dataFim = dataFim;
    }

    /**
     * Obtem o valor do atributo dataCriacao.<BR>
     * Atributo gerado a partir da coluna PETC_DT_CRIACAO.
     * 
     * @return Valor do atributo dataCriacao.
     */
    public Date getDataCriacao() {
        return this.dataCriacao;
    }

    /**
     * Atualiza o valor do atributo dataCriacao.<BR>
     * Atributo gerado a partir da coluna PETC_DT_CRIACAO.
     * 
     * @param dataCriacao
     *            Novo valor para o atributo dataCriacao.
     */
    public void setDataCriacao(final Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    /**
     * Obtem o valor do atributo valorJornada.<BR>
     * Atributo gerado a partir da coluna PETC_VL_JORNADA.
     * 
     * @return Valor do atributo valorJornada.
     */
    public BigDecimal getValorJornada() {
        return this.valorJornada;
    }

    /**
     * Atualiza o valor do atributo valorJornada.<BR>
     * Atributo gerado a partir da coluna PETC_VL_JORNADA.
     * 
     * @param valorJornada
     *            Novo valor para o atributo valorJornada.
     */
    public void setValorJornada(final BigDecimal valorJornada) {
        this.valorJornada = valorJornada;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoPessoaTpContrato").append("='").append(
                getCodigoPessoaTpContrato()).append("' ");
        buffer.append("pessoa").append("='").append(getPessoa()).append("' ");
        buffer.append("tipoContrato").append("='").append(getTipoContrato())
                .append("' ");
        buffer.append("empresa").append("='").append(getEmpresa()).append("' ");
        buffer.append("percentualAlocavel").append("='").append(
                getPercentualAlocavel()).append("' ");
        buffer.append("dataInicio").append("='").append(getDataInicio())
                .append("' ");
        buffer.append("dataFim").append("='").append(getDataFim()).append("' ");
        buffer.append("dataCriacao").append("='").append(getDataCriacao())
                .append("' ");
        buffer.append("valorJornada").append("='").append(getValorJornada())
                .append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}