/*
 * @(#) Pessoa.java
 * Copyright (c) 2009 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import com.ciandt.pms.Constants;
import org.apache.commons.lang.WordUtils;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.*;

/**
 * Entity gerado a partir da tabela PESSOA.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 23/09/2009 09:05:51
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "PESSOA")
@NamedQueries({
		@NamedQuery(name = "Pessoa.findAll", query = "SELECT t FROM Pessoa t "
				+ " WHERE t.recurso.indicadorAtivo = 'A' "
				+ " ORDER BY t.codigoLogin"),

		@NamedQuery(name = "Pessoa.findAllReturnCodigoPessoaAndCodigoLogin", query = "SELECT new Pessoa(t.codigoPessoa, t.codigoLogin) FROM Pessoa t "
				+ " WHERE t.recurso.indicadorAtivo = 'A' "
				+ " ORDER BY t.codigoLogin"),

		@NamedQuery(name = "Pessoa.findAllActiveByDate", query = "SELECT p FROM Pessoa p "
				+ " WHERE TO_DATE(TO_CHAR(?1,'MM/yyyy'),'MM/yyyy') "
				+ "           >= TO_DATE(TO_CHAR(p.dataAdmissao,'MM/yyyy'),'MM/yyyy') "
				+ "   AND ( "
				+ " ( TO_DATE(TO_CHAR(?1,'MM/yyyy'),'MM/yyyy') "
				+ "         <= TO_DATE(TO_CHAR(p.dataRescisao,'MM/yyyy'),'MM/yyyy') ) "
				+ " OR (p.dataRescisao is null) )" + " ORDER BY p.codigoLogin"),

		@NamedQuery(name = "Pessoa.findByLoginMgrAndDate", query = "SELECT p FROM Pessoa p "
				+ " WHERE (UPPER(p.codigoLoginMgr) = TRIM(UPPER(?)) OR (? is null)) "
				+ " AND TO_DATE(TO_CHAR(?,'MM/yyyy'),'MM/yyyy') "
				+ "         >= TO_DATE(TO_CHAR(p.dataAdmissao,'MM/yyyy'),'MM/yyyy') "
				+ " AND ( "
				+ " ( TO_DATE(TO_CHAR(?,'MM/yyyy'),'MM/yyyy') "
				+ "         <= TO_DATE(TO_CHAR(p.dataRescisao,'MM/yyyy'),'MM/yyyy') ) "
				+ " OR (p.dataRescisao is null) )"
				+ " ORDER BY p.dataMesValidado ASC, p.codigoLogin ASC "),

		@NamedQuery(name = "Pessoa.findNotValidatedByDate", query = "SELECT p FROM Pessoa p "
				+ " WHERE TO_DATE(TO_CHAR(?,'MM/yyyy'),'MM/yyyy') "
				+ "         >= TO_DATE(TO_CHAR(p.dataAdmissao,'MM/yyyy'),'MM/yyyy') "
				+ " AND ( ( TO_DATE(TO_CHAR(?,'MM/yyyy'),'MM/yyyy') "
				+ "         <= TO_DATE(TO_CHAR(p.dataRescisao,'MM/yyyy'),'MM/yyyy') ) "
				+ "        OR (p.dataRescisao is null) )"
				+ " AND ( TO_DATE(TO_CHAR(p.dataMesValidado,'MM/yyyy'),'MM/yyyy') "
				+ "         < TO_DATE(TO_CHAR(?,'MM/yyyy'),'MM/yyyy') "
				+ "     OR p.dataMesValidado is null)"
				+ " ORDER BY p.dataMesValidado ASC, p.codigoLogin ASC "),

		@NamedQuery(name = "Pessoa.countNotValidatedByDate", query = "SELECT count(p) FROM Pessoa p "
				+ " WHERE TO_DATE(TO_CHAR(:dataMes,'MM/yyyy'),'MM/yyyy') "
				+ "         >= TO_DATE(TO_CHAR(p.dataAdmissao,'MM/yyyy'),'MM/yyyy') "
				+ " AND ( ( TO_DATE(TO_CHAR(:dataMes,'MM/yyyy'),'MM/yyyy') "
				+ "         <= TO_DATE(TO_CHAR(p.dataRescisao,'MM/yyyy'),'MM/yyyy') ) "
				+ "        OR (p.dataRescisao is null) )"
				+ " AND ( TO_DATE(TO_CHAR(p.dataMesValidado,'MM/yyyy'),'MM/yyyy') "
				+ "         < TO_DATE(TO_CHAR(:dataMes,'MM/yyyy'),'MM/yyyy') "
				+ "     OR p.dataMesValidado is null)"),

		@NamedQuery(name = "Pessoa.findByLogin", query = "SELECT p FROM Pessoa p "
				+ " WHERE p.codigoLogin = ? "),

		@NamedQuery(name = "Pessoa.findByLikeLogin", query = "SELECT p FROM Pessoa p "
				+ " WHERE UPPER(p.codigoLogin) like '%'||TRIM(UPPER(?1))||'%' "
				+ " AND (p.recurso.indicadorAtivo = ?2 OR ?2 is null)"
				+ " ORDER BY p.codigoLogin "),

		@NamedQuery(name = "Pessoa.findAccountExecutiveByLikeLogin", query = "SELECT p FROM Pessoa p "
				+ " WHERE UPPER(p.codigoLogin) like '%'||TRIM(UPPER(?1))||'%' "
				+ " AND p.recurso.indicadorAtivo = 'A'"
				+ " ORDER BY p.codigoLogin "),

		@NamedQuery(name = "Pessoa.findByFilter", query = "SELECT p FROM Pessoa p "
				+ " WHERE ( UPPER(p.codigoLogin) like '%'||TRIM(UPPER(?))||'%' "
				+ " OR UPPER(p.nomePessoa) like '%'||TRIM(UPPER(?))||'%' )"
				+ " AND (UPPER(p.codigoLoginMgr) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
				// + " AND p.recurso.indicadorAtivo = 'A'"
				+ " ORDER BY p.nomePessoa"),

		@NamedQuery(name = "Pessoa.findByFilterActiveOnly", query = "SELECT p FROM Pessoa p "
				+ " WHERE ( UPPER(p.codigoLogin) like '%'||TRIM(UPPER(?))||'%' "
				+ " OR UPPER(p.nomePessoa) like '%'||TRIM(UPPER(?))||'%' )"
				+ " AND (UPPER(p.codigoLoginMgr) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
				+ " AND (p.dataRescisao is null OR p.recurso.indicadorAtivo = 'A')"
				+ " ORDER BY p.nomePessoa"),

		@NamedQuery(name = "Pessoa.findByFilterFollowingOnly", query = "SELECT p FROM Pessoa p "
				+ " JOIN p.pessoaPessoas pessPess "
				+ " WHERE ( UPPER(p.codigoLogin) like '%'||TRIM(UPPER(?))||'%' "
				+ " OR UPPER(p.nomePessoa) like '%'||TRIM(UPPER(?))||'%' )"
				+ " AND (UPPER(p.codigoLoginMgr) like '%'||TRIM(UPPER(?))||'%' OR (? is null)) "
				+ " AND (pessPess.pessoaFlwer.codigoPessoa = ?) "
				+ " ORDER BY p.nomePessoa"),

		@NamedQuery(name = "Pessoa.findAllManager", query = "SELECT manager FROM Pessoa manager "
				+ "WHERE manager.codigoLogin in (select manager.codigoLoginMgr from manager) "
				+ " AND manager.recurso.indicadorAtivo = 'A' "
				+ "ORDER BY manager.codigoLogin"),
				
		@NamedQuery(name = "Pessoa.findAllManagerReturnCodigoPessoaAndCodigoLogin", query = "SELECT new Pessoa(manager.codigoPessoa, manager.codigoLogin) "
				+ "FROM Pessoa manager "
				+ "WHERE manager.codigoLogin in (select manager.codigoLoginMgr from manager) "
				+ " AND manager.recurso.indicadorAtivo = 'A' "
				+ "ORDER BY manager.codigoLogin"),

		@NamedQuery(name = "Pessoa.findAllBusinessManager", query = "SELECT manager FROM Pessoa manager "
				+ " JOIN manager.perfilSistemas perfilSistema "
				+ "WHERE perfilSistema.siglaPerfilSistema = '"
				+ Constants.AUTHORITY_TYPE_BM
				+ "'"
				+ " AND manager.recurso.indicadorAtivo = 'A' "
				+ "ORDER BY manager.codigoLogin"),

		@NamedQuery(name = "Pessoa.findAllAccountExecutive", query = "SELECT ae FROM Pessoa ae "
				+ " JOIN ae.perfilSistemas perfilSistema "
				+ "WHERE perfilSistema.siglaPerfilSistema = '"
				+ Constants.AUTHORITY_TYPE_AE
				+ "'"
				+ " AND ae.recurso.indicadorAtivo = 'A' "
				+ "ORDER BY ae.codigoLogin"),

		@NamedQuery(name = "Pessoa.findByRecurso", query = "SELECT p FROM Pessoa p"
				+ " WHERE p.recurso.codigoRecurso = ?"),

		@NamedQuery(name = "Pessoa.findByRecursoTipo", query = "SELECT p FROM Pessoa p"
				+ " WHERE p.recurso.codigoRecurso = ? "
				+ "AND p.recurso.indicadorTipoRecurso = ? "),

		@NamedQuery(name = "Pessoa.findFlwerByMapaAlocacaoPessoa", query = "SELECT m.pessoa "
				+ "FROM MapaAlocacaoPessoa m "
				+ " WHERE m.codigoMapaAlocPessoa = ?"),

		@NamedQuery(name = "Pessoa.findFlwerByPessoaPessoa", query = "SELECT p.pessoaFlwer FROM PessoaPessoa p "
				+ " WHERE p.codigoPessoaPessoa = ?"),

		@NamedQuery(name = "Pessoa.findByCodigoMD5", query = "SELECT p FROM Pessoa p "
				+ " WHERE p.codigoMD5 = ?"),

		@NamedQuery(name = "Pessoa.findByChargebackAndPeriod", query = "SELECT p.codigoPessoa, p.recurso.codigoRecurso, "
				+ " p.cidadeBase.codigoCidadeBase, p.codigoLogin,  p.nomePessoa, p.textoEmail, p.dataAdmissao, "
				+ " p.codigoLoginMgr, p.dataMesValidado, "
				+ " p.percentualAlocavel, p.tipoContrato.codigoTipoContrato, p.percentualUrAlvo, p.dataRescisao, "
				+ " p.indicadorFollowOn, p.codigoMD5"
				+ " FROM Pessoa p "
				+ " JOIN p.chargebackPessoas chargeback "
				+ " WHERE chargeback.tiRecurso.codigoTiRecurso = ? "
				+ "   AND TRUNC(chargeback.dataMes) between TRUNC(?) AND TRUNC(?) "
				+ " GROUP BY p.codigoPessoa, p.recurso.codigoRecurso, "
				+ " p.cidadeBase.codigoCidadeBase, p.codigoLogin,  p.nomePessoa, p.textoEmail, p.dataAdmissao, "
				+ " p.codigoLoginMgr, p.dataMesValidado, "
				+ " p.percentualAlocavel, p.tipoContrato.codigoTipoContrato, p.percentualUrAlvo, p.dataRescisao, "
				+ " p.indicadorFollowOn, p.codigoMD5 "
				+ " ORDER BY p.nomePessoa ASC "),

		@NamedQuery(name = "Pessoa.findByMapaAlocacaoAndMesValidado", query = "SELECT p FROM Pessoa p "
				+ " JOIN p.recurso.alocacaos a "
				+ " WHERE a.mapaAlocacao.codigoMapaAlocacao = ? "
				+ "     AND TRUNC(p.dataMesValidado) = TRUNC(?) "),

		@NamedQuery(name = "Pessoa.quickSearchExSrManager", query = "SELECT DISTINCT p FROM Pessoa p "
				+ " JOIN p.perfilSistemas ps "
				+ " WHERE (UPPER(p.codigoLogin) like '%'||TRIM(UPPER(?))||'%') "
				//+ " AND ps.codigoPerfilSistema IN (13, 6, 4) "
				+ " AND p.recurso.indicadorAtivo = 'A' "
				+ " ORDER BY p.codigoLogin"),
				
				@NamedQuery(name = "Pessoa.quickSearchPMSUser", query = "SELECT DISTINCT p FROM Pessoa p"
						+ " JOIN p.perfilSistemas ps"
						+ " WHERE (UPPER(p.codigoLogin) like '%'||TRIM(UPPER(?))||'%')"
						+ " AND p.recurso.indicadorAtivo = 'A' "
						+ " ORDER BY p.codigoLogin"),

		@NamedQuery(name = "Pessoa.findbyLoginAndExSrManager", query = "SELECT DISTINCT p FROM Pessoa p "
				+ " JOIN p.perfilSistemas ps "
				+ " WHERE p.codigoLogin = ? "
				//+ " AND ps.codigoPerfilSistema IN (13, 6, 4) "
				+ " AND p.recurso.indicadorAtivo = 'A' "),
		
		@NamedQuery(name = "Pessoa.findWithOpenVoucherBeforeDate", query = "SELECT DISTINCT p FROM Pessoa p"
				+ " JOIN FETCH p.vouchers pv"
				+ " WHERE pv.dataCreation < :dataCreation"
				+ " AND pv.indicadorStatus = '" + Constants.STATUS_VOUCHER_OPEN + "'"),

		@NamedQuery(name = "Pessoa.findFollowingOrcDespWithOpenVoucherBeforeDate", query = "SELECT p FROM Pessoa p"
				+ " JOIN p.followOrcamentosDesp pfo"
				+ " JOIN pfo.orcamentoDespesa pfod"
				+ " JOIN pfod.vouchers pv"
				+ " WHERE pv.dataCreation < :dataCreation"
				+ " AND pv.indicadorStatus = '" + Constants.STATUS_VOUCHER_OPEN + "'"),

		@NamedQuery(name = "Pessoa.findByLoginIn", query = "SELECT p FROM Pessoa p WHERE p.codigoLogin IN (:logins)")

})
@NamedNativeQueries({
		@NamedNativeQuery(name = Pessoa.FIND_BY_POSITION_MAP_IN, resultClass = Pessoa.class,
				query = " SELECT pess.* " +
						" FROM PMS20.PESSOA pess " +
						" JOIN PMS20.RECURSO recu ON pess.RECU_CD_RECURSO = recu.RECU_CD_RECURSO " +
						" JOIN HRS.EMPLOYEE empl ON pess.PESS_CD_LOGIN = empl.EMPL_CD_LOGIN " + // Faz a juncao pelo LOGIN, pois o CD pode ser diferente entre PMS20 e HRS.
						" JOIN HRS.HISTORY_POSITION hipo ON ( " +
						"     empl.EMPL_CD_EMPLOYEE = hipo.EMPL_CD_EMPLOYEE " +
						"     AND TRUNC(SYSDATE) BETWEEN hipo.HIPO_DT_BEGIN AND NVL(hipo.HIPO_DT_END, SYSDATE + 30) ) " +
						" JOIN HRS.POSITION posi ON hipo.POSI_CD_POSITION = posi.POSI_CD_POSITION " +
						" JOIN HRS.POSITION_MAP poma ON posi.POMA_CD_POSITION_MAP = poma.POMA_CD_POSITION_MAP " +
						" WHERE recu.RECU_IN_ATIVO = 'A' " +
						" AND (poma.POMA_NR_LEVEL >= 50 AND poma.POMA_NR_LEVEL <= 100) " +
						" ORDER BY pess.PESS_CD_LOGIN"),
})
public class Pessoa implements java.io.Serializable, Cloneable {

	// ========================================================================
	// BEGIN - Coloque aqui o codigo manual
	// ========================================================================

	/** Constante para NamedQuery "Pessoa.findAllActiveByDate". */
	public static final String FIND_ALL_ACTIVE_BY_DATE = "Pessoa.findAllActiveByDate";

	/** Constante para NamedQuery "Pessoa.findByRecurso". */
	public static final String FIND_BY_RECURSO = "Pessoa.findByRecurso";

	/** Constante para NamedQuery "Pessoa.findByRecursoTipo". */
	public static final String FIND_BY_RECURSO_TIPO = "Pessoa.findByRecursoTipo";

	/** Constante para NamedQuery "Pessoa.findByLoginMgrAndDate". */
	public static final String FIND_BY_LOGIN_MGR_AND_DATE = "Pessoa.findByLoginMgrAndDate";

	/** Constante para NamedQuery "Pessoa.findNotValidatedByDate". */
	public static final String FIND_NOT_VALIDATED_BY_DATE = "Pessoa.findNotValidatedByDate";

	/** Constante para NamedQuery "Pessoa.countNotValidatedByDate". */
	public static final String COUNT_NOT_VALIDATED_BY_DATE = "Pessoa.countNotValidatedByDate";

	/** Constante para NamedQuery "Pessoa.findAllManager". */
	public static final String FIND_ALL_MGR = "Pessoa.findAllManager";
	
	/** Constante para NamedQuery "Pessoa.findAllManagerReturnCodigoPessoaAndCodigoLogin". */
	public static final String FIND_ALL_MGR_RETURN_CODIGO_PESSOA_AND_CODIGO_LOGIN = "Pessoa.findAllManagerReturnCodigoPessoaAndCodigoLogin";

	public static final String FIND_BY_POSITION_MAP_IN = "Pessoa.findByPositionMapIn";

	/** Constante para NamedQuery "Pessoa.findByLikeLogin". */
	public static final String FIND_BY_LIKE_LOGIN = "Pessoa.findByLikeLogin";

	/** Constante para NamedQuery "Pessoa.findByLogin". */
	public static final String FIND_BY_LOGIN = "Pessoa.findByLogin";

	/** Constante para NamedQuery "Pessoa.findByFilter". */
	public static final String FIND_BY_FILTER = "Pessoa.findByFilter";

	/** Constante para NamedQuery "Pessoa.findByFilterActiveOnly". */
	public static final String FIND_BY_FILTER_ACTIVE_ONLY = "Pessoa.findByFilterActiveOnly";

	/** Constante para NamedQuery "Pessoa.findByFilterFollowingOnly". */
	public static final String FIND_BY_FILTER_FOLLOWING_ONLY = "Pessoa.findByFilterFollowingOnly";

	/** Constante para NamedQuery "Pessoa.findAllBusinessManager". */
	public static final String FIND_ALL_BUSINESS_MANAGER = "Pessoa.findAllBusinessManager";

	/** Constante para NamedQuery "Pessoa.findAllAccountExecutive". */
	public static final String FIND_ALL_ACCOUNT_EXECUTIVE = "Pessoa.findAllAccountExecutive";

	/** Constante para NamedQuery "Pessoa.findAccountExecutiveByLikeLogin". */
	public static final String FIND_ACCOUNT_EXECUTIVE_BY_LIKE_LOGIN = "Pessoa.findAccountExecutiveByLikeLogin";

	/** Constante para NamedQuery "Pessoa.findFlwerByMapaAlocacaoPessoa". */
	public static final String FIND_FLWER_BY_MAPA_ALOCACAO_PESSOA = "Pessoa.findFlwerByMapaAlocacaoPessoa";

	/** Constante para NamedQuery "Pessoa.findFlwerByPessoaPessoa". */
	public static final String FIND_FLWER_BY_PESSOA_PESSOA = "Pessoa.findFlwerByPessoaPessoa";

	/** Constante para NamedQuery "Pessoa.findByCodigoMD5". */
	public static final String FIND_BY_CODIGO_MD5 = "Pessoa.findByCodigoMD5";

	/** Constante para NamedQuery "Pessoa.findByChargebackAndPeriod". */
	public static final String FIND_BY_TIRECURSO_AND_PERIOD = "Pessoa.findByChargebackAndPeriod";

	/** Constante para NamedQuery "Pessoa.findByMapaAlocacaoAndDataMesValidado". */
	public static final String FIND_BY_MAPA_ALOCACAO_AND_MES_VALIDADO = "Pessoa.findByMapaAlocacaoAndMesValidado";

	/** Constante para NamedQuery "Pessoa.findAllExSrManager". */
	public static final String QUICK_SEARCH_EXECUTIVE_SENIOR_MANAGER = "Pessoa.quickSearchExSrManager";
	
	/** Constante para NamedQuery "Pessoa.findAllExSrManager". */
	public static final String QUICK_SEARCH_PMS_USER = "Pessoa.quickSearchPMSUser";
	
	/** Constante para NamedQuery "Pessoa.findWithOpenVoucherBeforeDate". */
	public static final String FIND_WITH_OPEN_VOUCHER_BEFORE_DATE = "Pessoa.findWithOpenVoucherBeforeDate";
	
	/** Constante para NamedQuery "Pessoa.findFollowingOrcDespWithOpenVoucherBeforeDate". */
	public static final String FIND_FOLLOWING_ORC_DESP_WITH_OPEN_VOUCHER_BEFORE_DATE = "Pessoa.findFollowingOrcDespWithOpenVoucherBeforeDate";
	
	/** Constante para NamedQuery "Pessoa.findbyLoginAndExSrManager". */
	public static final String FIND_BY_LOGIN_EXECUTIVE_SENIOR_MANAGER = "Pessoa.findbyLoginAndExSrManager";
	
	/** Constante para NamedQuery "Pessoa.findAllReturnCodigoPessoaAndCodigoLogin". */
	public static final String FIND_ALL_RETURN_CODIGO_PESSOA_AND_CODIGO_LOGIN = "Pessoa.findAllReturnCodigoPessoaAndCodigoLogin";

	/** Constante para NamedQuery "Pessoa.findByLoginIn". */
	public static final String FIND_BY_LOGIN_IN = "Pessoa.findByLoginIn";


	/**
	 * Atributo gerado a partir da tabela PESSOA_PERFIL_SISTEMA.
	 */
	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinTable(name = "PESSOA_PERFIL_SISTEMA", joinColumns = { @JoinColumn(name = "PESS_CD_PESSOA", nullable = false, updatable = true, insertable = true) }, inverseJoinColumns = { @JoinColumn(name = "PESI_CD_PERFIL_SISTEMA", nullable = false, updatable = true, insertable = true) })
	private Set<PerfilSistema> perfilSistemas = new HashSet<PerfilSistema>(0);

	/**
	 * Atributo gerado a partir da tabela PESSOA_AREA_ORCAMENTARIA.
	 */
	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinTable(name = "PESSOA_AREA_ORCAMENTARIA", joinColumns = { @JoinColumn(name = "PESS_CD_PESSOA", nullable = false, updatable = true, insertable = true) }, inverseJoinColumns = { @JoinColumn(name = "AROR_CD_AREA_ORCAMENTARIA", nullable = false, updatable = true, insertable = true) })
	private Set<AreaOrcamentaria> areasOrcamentarias = new HashSet<AreaOrcamentaria>(0);


	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinTable(name = "PESSOA_EMPRESA_BUDGET", joinColumns = { @JoinColumn(name = "PESS_CD_PESSOA", nullable = false, updatable = true, insertable = true) }, inverseJoinColumns = { @JoinColumn(name = "EMPR_CD_EMPRESA", nullable = false, updatable = true, insertable = true) })
	private Set<Empresa> empresasOrcamentarias = new HashSet<Empresa>(0);


	/**
	 * Atributo gerado a partir da tabela VOUCHER.
	 */
	@OneToMany
	@JoinColumn(name = "PESS_CD_PESSOA", referencedColumnName = "PESS_CD_PESSOA")
	private List<Voucher> vouchers = new ArrayList<Voucher>();

	/**
	 * Relacionamento um pra muitos.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	private List<AlocacaoOverhead> alocacoesOverhead = new ArrayList<AlocacaoOverhead>(0);

	/** Relacionamento com a entidade ComposicaoTce. */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	private Set<ComposicaoTce> composicaoTces = new HashSet<ComposicaoTce>(0);

	/** Relacionamento com entidade FollowOrcamentoDesp */
	@OneToMany
	@JoinColumn(name = "PESS_CD_LOGIN", referencedColumnName = "PESS_CD_LOGIN")
	private List<FollowOrcamentoDesp> followOrcamentosDesp = new ArrayList<FollowOrcamentoDesp>();

	/**
	 * @param alocacoesOverhead
	 *            the alocacoesOverhead to set
	 */
	public void setAlocacoesOverhead(
			final List<AlocacaoOverhead> alocacoesOverhead) {
		this.alocacoesOverhead = alocacoesOverhead;
	}

	/**
	 * @return the alocacoesOverhead
	 */
	public List<AlocacaoOverhead> getAlocacoesOverhead() {
		return alocacoesOverhead;
	}

	/**
	 * Atributo gerado a partir da tabela PESSOA_GRUPO_CUSTO.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	@OrderBy("dataInicio")
	private List<PessoaGrupoCusto> pessoaGrupoCustos = new ArrayList<PessoaGrupoCusto>(
			0);

	/**
	 * @param pessoaGrupoCustos
	 *            the pessoaGrupoCustos to set
	 */
	public void setPessoaGrupoCustos(
			final List<PessoaGrupoCusto> pessoaGrupoCustos) {
		this.pessoaGrupoCustos = pessoaGrupoCustos;
	}

	/**
	 * @return the pessoaGrupoCustos
	 */
	public List<PessoaGrupoCusto> getPessoaGrupoCustos() {
		return pessoaGrupoCustos;
	}

	/**
	 * Lista de PessoaBillability.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	private List<PessoaBillability> pessoaBillabilities = new ArrayList<PessoaBillability>(
			0);


	/**
	 * @return the pessoaBillabilities7jh
	 */
	public List<PessoaBillability> getPessoaBillabilities() {
		return pessoaBillabilities;
	}

	/**
	 * @param pessoaBillabilities the vouchers to set
	 */
	public void setPessoaBillabilities(List<PessoaBillability> pessoaBillabilities) {
		this.pessoaBillabilities = pessoaBillabilities;
	}

	/**
	 * Atributo gerado a partir da tabela PESSOA_TIPO_CONTRATO.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	@OrderBy("dataInicio")
	private List<PessoaTipoContrato> pessoaTipoContratos = new ArrayList<PessoaTipoContrato>(
			0);

	/**
	 * Obtem o valor do atributo pessoaTipoContratos.<BR>
	 * 
	 * @return Valor do atributo pessoaTipoContratos.
	 */
	public List<PessoaTipoContrato> getPessoaTipoContratos() {
		return this.pessoaTipoContratos;
	}

	public PessoaTipoContrato getPessoaTipoContratoAtual() {
		if (this.pessoaTipoContratos != null && !this.pessoaTipoContratos.isEmpty()) {
			for (PessoaTipoContrato ptc : this.pessoaTipoContratos) {
				if (ptc.getDataFim() == null) {
					return ptc;
				}
			}
		}

		return null;
	}

	/**
	 * Atualiza o valor do atributo pessoaTipoContratos.<BR>
	 * 
	 * @param pessoaTipoContratos
	 *            Novo valor para o atributo pessoaTipoContratos.
	 */
	public void setPessoaTipoContratos(
			final List<PessoaTipoContrato> pessoaTipoContratos) {
		this.pessoaTipoContratos = pessoaTipoContratos;
	}

	/**
	 * Atributo gerado a partir da tabela PESSOA_CIDADE_BASE.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	@OrderBy("dataInicio")
	private Set<PessoaCidadeBase> pessoaCidadeBases = new HashSet<PessoaCidadeBase>(
			0);

	/** Atributo gerado a partir da tabela CHARGEBACK_PESSOA. */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	private List<ChargebackPessoa> chargebackPessoas = new ArrayList<ChargebackPessoa>(
			0);

	/**
	 * Atributo gerado a partir da tabela PESSOA_DELEGACAO.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	private List<PessoaDelegacao> pessoaDelegacaos = new ArrayList<PessoaDelegacao>(
			0);

	/**
	 * Atributo gerado a partir da tabela PESSOA_DELEGACAO.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoaDelegada")
	private List<PessoaDelegacao> pessoaDelegacaosDelegadas = new ArrayList<PessoaDelegacao>(
			0);

	/**
	 * Atributo gerado a partir da tabela MAPA_ALOCACAO_PESSOA.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	private List<MapaAlocacaoPessoa> mapaAlocacaoPessoas = new ArrayList<MapaAlocacaoPessoa>(
			0);

	/**
	 * Obtem o valor do atributo mapaAlocacaoPessoas.<BR>
	 * 
	 * @return Valor do atributo mapaAlocacaoPessoas.
	 */
	public List<MapaAlocacaoPessoa> getMapaAlocacaoPessoas() {
		return this.mapaAlocacaoPessoas;
	}

	/**
	 * Atualiza o valor do atributo mapaAlocacaoPessoas.<BR>
	 * 
	 * @param mapaAlocacaoPessoas
	 *            Novo valor para o atributo mapaAlocacaoPessoas.
	 */
	public void setMapaAlocacaoPessoas(
			final List<MapaAlocacaoPessoa> mapaAlocacaoPessoas) {
		this.mapaAlocacaoPessoas = mapaAlocacaoPessoas;
	}

	/**
	 * Atributo gerado a partir da tabela PESSOA_PESSOA.
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa", cascade = CascadeType.ALL)
	private List<PessoaPessoa> pessoaPessoas = new ArrayList<PessoaPessoa>(0);

	/**
	 * Atualiza o valor do atributo pessoaPessoas.<BR>
	 * 
	 * @param pessoaPessoas
	 *            Novo valor para o atributo pessoaPessoas.
	 */
	public void setPessoaPessoas(final List<PessoaPessoa> pessoaPessoas) {
		this.pessoaPessoas = pessoaPessoas;
	}

	/**
	 * @param chargebackPessoas
	 *            the chargebackPessoas to set
	 */
	public void setChargebackPessoas(
			final List<ChargebackPessoa> chargebackPessoas) {
		this.chargebackPessoas = chargebackPessoas;
	}

	/**
	 * @return the chargebackPessoas
	 */
	public List<ChargebackPessoa> getChargebackPessoas() {
		return chargebackPessoas;
	}

	/**
	 * Realiza uma copia do objeto, porem com uma referencia diferente.
	 * 
	 * @return a cópia do Objeto
	 */
	public Pessoa getClone() {
		try {
			return (Pessoa) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
			return null;
		}
	}

	// ========================================================================
	// END
	// ========================================================================

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "Pessoa.findAll".
	 */
	public static final String FIND_ALL = "Pessoa.findAll";

	/**
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 */
	@Id
	@GeneratedValue(generator = "PessoaSeq")
	@SequenceGenerator(name = "PessoaSeq", sequenceName = "SQ_PESS_CD_PESSOA", allocationSize = 1)
	@Column(name = "PESS_CD_PESSOA", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoPessoa;

	/**
	 * Atributo gerado a partir da coluna PESS_DT_RESCISAO.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "PESS_DT_RESCISAO", length = 7)
	private Date dataRescisao;

	/**
	 * Atributo gerado a partir da coluna RECU_CD_RECURSO.
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RECU_CD_RECURSO", nullable = false)
	private Recurso recurso;

	/**
	 * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TICO_CD_TIPO_CONTRATO")
	private TipoContrato tipoContrato;

	/**
	 * Atributo gerado a partir da coluna CIBA_CD_CIDADE_BASE.
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CIBA_CD_CIDADE_BASE", nullable = true)
	private CidadeBase cidadeBase;

	/**
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN.
	 */

	@Column(name = "PESS_CD_LOGIN", length = 20, nullable = false, insertable = false, updatable = false)
	private String codigoLogin;

	/**
	 * Atributo gerado a partir da coluna PESS_NM_PESSOA.
	 */

	@Column(name = "PESS_NM_PESSOA", length = 200)
	private String nomePessoa;

	/**
	 * Atributo gerado a partir da coluna PESS_TX_EMAIL.
	 */

	@Column(name = "PESS_TX_EMAIL", length = 200)
	private String textoEmail;

	/**
	 * Atributo gerado a partir da coluna PESS_DT_ADMISSAO.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "PESS_DT_ADMISSAO", length = 7)
	private Date dataAdmissao;

	/**
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN_MGR.
	 */
	@Column(name = "PESS_CD_LOGIN_MGR", length = 50)
	private String codigoLoginMgr;

	/**
	 * Atributo gerado a partir da coluna PESS_DT_MES_VALIDADO.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "PESS_DT_MES_VALIDADO", length = 7)
	private Date dataMesValidado;

	/**
	 * Atributo gerado a partir da coluna PESS_PR_ALOCAVEL.
	 */
	@Column(name = "PESS_PR_ALOCAVEL", precision = 3)
	private BigDecimal percentualAlocavel;

	/**
	 * Atributo gerado a partir da coluna PESS_PR_UR_ALVO.
	 */
	@Column(name = "PESS_PR_UR_ALVO", precision = 22, scale = 0)
	private BigDecimal percentualUrAlvo;

	/**
	 * Atributo gerado a partir da coluna PESS_IN_FOLLOW_ON.
	 */
	@Column(name = "PESS_IN_FOLLOW_ON", length = 1)
	private String indicadorFollowOn;

	/**
	 * Indicador de delegacao de recursos.
	 */
	@Transient
	private String indicadorDelegateOn;

	/**
	 * Atributo gerado a partir da coluna PESS_CD_MD5.
	 */
	@Column(name = "PESS_CD_MD5", length = 100)
	private String codigoMD5;

	/**
	 * Indica se a validação esta sendo chamada pela tela de Closing DRE By
	 * Login
	 * 
	 * <li>true - Indica que a validação esta sendo chamada pela tela de Closing
	 * DRE By Login</li> <li>false - Indica que a validação esta sendo chamada
	 * por outra tela</li>
	 */
	@Transient
	private boolean validacaoCloseDreByLogin;

	/**
	 * Construtor default.
	 */
	public Pessoa() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoPessoa
	 *            Valor do atributo codigoPessoa;
	 * @param codigoLogin
	 *            Valor do atributo codigoLogin;
	 */
	public Pessoa(final Long codigoPessoa, final String codigoLogin) {
		this.codigoPessoa = codigoPessoa;
		this.codigoLogin = codigoLogin;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param codigoPessoa
	 *            Valor do atributo codigoPessoa;
	 * @param recurso
	 *            Valor do atributo recurso;
	 * @param cidadeBase
	 *            Valor do atributo cidadeBase;
	 */
	public Pessoa(final Long codigoPessoa, final Recurso recurso,
			final CidadeBase cidadeBase) {
		this.codigoPessoa = codigoPessoa;
		this.recurso = recurso;
		this.cidadeBase = cidadeBase;
	}

	/**
	 * Obtem o valor do atributo codigoPessoa.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 * 
	 * @return Valor do atributo codigoPessoa.
	 */
	public Long getCodigoPessoa() {
		return this.codigoPessoa;
	}

	/**
	 * Atualiza o valor do atributo codigoPessoa.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 * 
	 * @param codigoPessoa
	 *            Novo valor para o atributo codigoPessoa.
	 */
	public void setCodigoPessoa(final Long codigoPessoa) {
		this.codigoPessoa = codigoPessoa;
	}

	/**
	 * Obtem o valor do atributo recurso.<BR>
	 * Atributo gerado a partir da coluna RECU_CD_RECURSO.
	 * 
	 * @return Valor do atributo recurso.
	 */
	public Recurso getRecurso() {
		return this.recurso;
	}

	/**
	 * Atualiza o valor do atributo recurso.<BR>
	 * Atributo gerado a partir da coluna RECU_CD_RECURSO.
	 * 
	 * @param recurso
	 *            Novo valor para o atributo recurso.
	 */
	public void setRecurso(final Recurso recurso) {
		this.recurso = recurso;
	}

	/**
	 * Obtem o valor do atributo cidadeBase.<BR>
	 * Atributo gerado a partir da coluna CIBA_CD_CIDADE_BASE.
	 * 
	 * @return Valor do atributo cidadeBase.
	 */
	public CidadeBase getCidadeBase() {
		return this.cidadeBase;
	}

	/**
	 * Atualiza o valor do atributo cidadeBase.<BR>
	 * Atributo gerado a partir da coluna CIBA_CD_CIDADE_BASE.
	 * 
	 * @param cidadeBase
	 *            Novo valor para o atributo cidadeBase.
	 */
	public void setCidadeBase(final CidadeBase cidadeBase) {
		this.cidadeBase = cidadeBase;
	}

	/**
	 * Obtem o valor do atributo codigoLogin.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN.
	 * 
	 * @return Valor do atributo codigoLogin.
	 */
	public String getCodigoLogin() {
		return this.codigoLogin;
	}

	/**
	 * Atualiza o valor do atributo codigoLogin.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN.
	 * 
	 * @param codigoLogin
	 *            Novo valor para o atributo codigoLogin.
	 */
	public void setCodigoLogin(final String codigoLogin) {
		this.codigoLogin = codigoLogin;
	}

	/**
	 * Obtem o valor do atributo nomePessoa.<BR>
	 * Atributo gerado a partir da coluna PESS_NM_PESSOA.
	 * 
	 * @return Valor do atributo nomePessoa.
	 */
	public String getNomePessoa() {
		return this.nomePessoa;
	}

	/**
	 * Retorna o primeiro nome da pessoa
	 * @return String
	 */
	public String getPrimeiroNomePessoa() {
		if (this.nomePessoa != null) {
			
			return WordUtils.capitalize(this.nomePessoa).split(" ")[0];
		}

		return null;
	}

	/**
	 * Atualiza o valor do atributo nomePessoa.<BR>
	 * Atributo gerado a partir da coluna PESS_NM_PESSOA.
	 * 
	 * @param nomePessoa
	 *            Novo valor para o atributo nomePessoa.
	 */
	public void setNomePessoa(final String nomePessoa) {
		this.nomePessoa = nomePessoa;
	}

	/**
	 * Obtem o valor do atributo textoEmail.<BR>
	 * Atributo gerado a partir da coluna PESS_TX_EMAIL.
	 * 
	 * @return Valor do atributo textoEmail.
	 */
	public String getTextoEmail() {
		return this.textoEmail;
	}

	/**
	 * Atualiza o valor do atributo textoEmail.<BR>
	 * Atributo gerado a partir da coluna PESS_TX_EMAIL.
	 * 
	 * @param textoEmail
	 *            Novo valor para o atributo textoEmail.
	 */
	public void setTextoEmail(final String textoEmail) {
		this.textoEmail = textoEmail;
	}

	/**
	 * Obtem o valor do atributo dataAdmissao.<BR>
	 * Atributo gerado a partir da coluna PESS_DT_ADMISSAO.
	 * 
	 * @return Valor do atributo dataAdmissao.
	 */
	public Date getDataAdmissao() {
		return this.dataAdmissao;
	}

	/**
	 * Atualiza o valor do atributo dataAdmissao.<BR>
	 * Atributo gerado a partir da coluna PESS_DT_ADMISSAO.
	 * 
	 * @param dataAdmissao
	 *            Novo valor para o atributo dataAdmissao.
	 */
	public void setDataAdmissao(final Date dataAdmissao) {
		this.dataAdmissao = dataAdmissao;
	}

	/**
	 * Obtem o valor do atributo codigoLoginMgr.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN_MGR.
	 * 
	 * @return Valor do atributo codigoLoginMgr.
	 */
	public String getCodigoLoginMgr() {
		return this.codigoLoginMgr;
	}

	/**
	 * Atualiza o valor do atributo codigoLoginMgr.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN_MGR.
	 * 
	 * @param codigoLoginMgr
	 *            Novo valor para o atributo codigoLoginMgr.
	 */
	public void setCodigoLoginMgr(final String codigoLoginMgr) {
		this.codigoLoginMgr = codigoLoginMgr;
	}

	/**
	 * Obtem o valor do atributo dataMesValidado.<BR>
	 * Atributo gerado a partir da coluna PESS_DT_MES_VALIDADO.
	 * 
	 * @return Valor do atributo dataMesValidado.
	 */
	public Date getDataMesValidado() {
		return this.dataMesValidado;
	}

	/**
	 * Atualiza o valor do atributo dataMesValidado.<BR>
	 * Atributo gerado a partir da coluna PESS_DT_MES_VALIDADO.
	 * 
	 * @param dataMesValidado
	 *            Novo valor para o atributo dataMesValidado.
	 */
	public void setDataMesValidado(final Date dataMesValidado) {
		this.dataMesValidado = dataMesValidado;
	}

	/**
	 * Obtem o valor do atributo percentualAlocavel.<BR>
	 * Atributo gerado a partir da coluna PESS_PR_ALOCAVEL.
	 * 
	 * @return Valor do atributo percentualAlocavel.
	 */
	public BigDecimal getPercentualAlocavel() {
		return this.percentualAlocavel;
	}

	/**
	 * Atualiza o valor do atributo percentualAlocavel.<BR>
	 * Atributo gerado a partir da coluna PESS_PR_ALOCAVEL.
	 * 
	 * @param percentualAlocavel
	 *            Novo valor para o atributo percentualAlocavel.
	 */
	public void setPercentualAlocavel(final BigDecimal percentualAlocavel) {
		this.percentualAlocavel = percentualAlocavel;
	}

	/**
	 * Obtem o valor do atributo tipoContrato.<BR>
	 * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
	 * 
	 * @return Valor do atributo tipoContrato.
	 */
	public TipoContrato getTipoContrato() {
		return this.tipoContrato;
	}

	/**
	 * Atualiza o valor do atributo tipoContrato.<BR>
	 * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
	 * 
	 * @param tipoContrato
	 *            Novo valor para o atributo tipoContrato.
	 */
	public void setTipoContrato(final TipoContrato tipoContrato) {
		this.tipoContrato = tipoContrato;
	}

	/**
	 * @see Object#toString()
	 * @return representação String do Objeto
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoPessoa").append("='").append(getCodigoPessoa())
				.append("' ");
		buffer.append("codigoLogin").append("='").append(getCodigoLogin())
				.append("' ");
		buffer.append("nomePessoa").append("='").append(getNomePessoa())
				.append("' ");
		buffer.append("textoEmail").append("='").append(getTextoEmail())
				.append("' ");
		buffer.append("dataAdmissao").append("='").append(getDataAdmissao())
				.append("' ");
		buffer.append("codigoLoginMgr").append("='")
				.append(getCodigoLoginMgr()).append("' ");
		buffer.append("dataMesValidado").append("='")
				.append(getDataMesValidado()).append("' ");
		buffer.append("percentualAlocavel").append("='")
				.append(getPercentualAlocavel()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	/**
	 * Obtem o valor do atributo percentualUrAlvo.<BR>
	 * Atributo gerado a partir da coluna PESS_PR_UR_ALVO.
	 * 
	 * @return Valor do atributo percentualUrAlvo.
	 */
	public BigDecimal getPercentualUrAlvo() {
		return this.percentualUrAlvo;
	}

	/**
	 * Atualiza o valor do atributo percentualUrAlvo.<BR>
	 * Atributo gerado a partir da coluna PESS_PR_UR_ALVO.
	 * 
	 * @param percentualUrAlvo
	 *            Novo valor para o atributo percentualUrAlvo.
	 */
	public void setPercentualUrAlvo(final BigDecimal percentualUrAlvo) {
		this.percentualUrAlvo = percentualUrAlvo;
	}

	/**
	 * Obtem o valor do atributo dataRescisao.<BR>
	 * Atributo gerado a partir da coluna PESS_DT_RESCISAO.
	 * 
	 * @return Valor do atributo dataRescisao.
	 */
	public Date getDataRescisao() {
		return this.dataRescisao;
	}

	/**
	 * Atualiza o valor do atributo dataRescisao.<BR>
	 * Atributo gerado a partir da coluna PESS_DT_RESCISAO.
	 * 
	 * @param dataRescisao
	 *            Novo valor para o atributo dataRescisao.
	 */
	public void setDataRescisao(final Date dataRescisao) {
		this.dataRescisao = dataRescisao;
	}

	/**
	 * @param perfilSistemas
	 *            the perfilSistemas to set
	 */
	public void setPerfilSistemas(final Set<PerfilSistema> perfilSistemas) {
		this.perfilSistemas = perfilSistemas;
	}

	/**
	 * @return the perfilSistemas
	 */
	public Set<PerfilSistema> getPerfilSistemas() {
		return perfilSistemas;
	}

	public Set<Empresa> getEmpresasOrcamentarias() {
		return empresasOrcamentarias;
	}

	public void setEmpresasOrcamentarias(Set<Empresa> empresasOrcamentarias) {
		this.empresasOrcamentarias = empresasOrcamentarias;
	}

	/**
	 * @param areasOrcamentarias
	 *            the areasOrcamentarias to set
	 */
	public void setAreasOrcamentarias(final Set<AreaOrcamentaria> areasOrcamentarias) {
		this.areasOrcamentarias = areasOrcamentarias;
	}

	/**
	 * @return the areasOrcamentarias
	 */
	public Set<AreaOrcamentaria> getAreasOrcamentarias() {
		return areasOrcamentarias;
	}

	/**
	 * @return the pessoaPessoas
	 */
	public List<PessoaPessoa> getPessoaPessoas() {
		return pessoaPessoas;
	}

	/**
	 * @return the pessoaCidadeBases
	 */
	public Set<PessoaCidadeBase> getPessoaCidadeBases() {
		return pessoaCidadeBases;
	}

	/**
	 * @param pessoaCidadeBases
	 *            the pessoaCidadeBases to set
	 */
	public void setPessoaCidadeBases(
			final Set<PessoaCidadeBase> pessoaCidadeBases) {
		this.pessoaCidadeBases = pessoaCidadeBases;
	}

	/**
	 * Obtem o valor do atributo composicaoTces.<BR>
	 * 
	 * @return Valor do atributo composicaoTces.
	 */
	public Set<ComposicaoTce> getComposicaoTces() {
		return this.composicaoTces;
	}

	/**
	 * Atualiza o valor do atributo composicaoTces.<BR>
	 * 
	 * @param composicaoTces
	 *            Novo valor para o atributo composicaoTces.
	 */
	public void setComposicaoTces(final Set<ComposicaoTce> composicaoTces) {
		this.composicaoTces = composicaoTces;
	}

	/**
	 * @return the indicadorFollowOn
	 */
	public String getIndicadorFollowOn() {
		return indicadorFollowOn;
	}

	/**
	 * @param indicadorFollowOn
	 *            the indicadorFollowOn to set
	 */
	public void setIndicadorFollowOn(final String indicadorFollowOn) {
		this.indicadorFollowOn = indicadorFollowOn;
	}

	/**
	 * @return the codigoMD5
	 */
	public String getCodigoMD5() {
		return codigoMD5;
	}

	/**
	 * @param codigoMD5
	 *            the codigoMD5 to set
	 */
	public void setCodigoMD5(final String codigoMD5) {
		this.codigoMD5 = codigoMD5;
	}

	/**
	 * @return the indicadorDelegateOn
	 */
	public String getIndicadorDelegateOn() {
		return indicadorDelegateOn;
	}

	/**
	 * @param indicadorDelegateOn
	 *            the indicadorDelegateOn to set
	 */
	public void setIndicadorDelegateOn(final String indicadorDelegateOn) {
		this.indicadorDelegateOn = indicadorDelegateOn;
	}

	/**
	 * @return the pessoaDelegacaos
	 */
	public List<PessoaDelegacao> getPessoaDelegacaos() {
		return pessoaDelegacaos;
	}

	/**
	 * @param pessoaDelegacaos
	 *            the pessoaDelegacaos to set
	 */
	public void setPessoaDelegacaos(final List<PessoaDelegacao> pessoaDelegacaos) {
		this.pessoaDelegacaos = pessoaDelegacaos;
	}

	/**
	 * @return the pessoaDelegacaosDelegadas
	 */
	public List<PessoaDelegacao> getPessoaDelegacaosDelegadas() {
		return pessoaDelegacaosDelegadas;
	}

	/**
	 * @param pessoaDelegacaosDelegadas
	 *            the pessoaDelegacaosDelegadas to set
	 */
	public void setPessoaDelegacaosDelegadas(
			final List<PessoaDelegacao> pessoaDelegacaosDelegadas) {
		this.pessoaDelegacaosDelegadas = pessoaDelegacaosDelegadas;
	}

	/**
	 * @return the vouchers
	 */
	public List<Voucher> getVouchers() {
		return vouchers;
	}

	/**
	 * @param vouchers the vouchers to set
	 */
	public void setVouchers(List<Voucher> vouchers) {
		this.vouchers = vouchers;
	}

	/**
	 * @return the validacaoCloseDreByLogin
	 */
	public boolean isValidacaoCloseDreByLogin() {
		return validacaoCloseDreByLogin;
	}

	/**
	 * @param validacaoCloseDreByLogin
	 *            the validacaoCloseDreByLogin to set
	 */
	public void setValidacaoCloseDreByLogin(boolean validacaoCloseDreByLogin) {
		this.validacaoCloseDreByLogin = validacaoCloseDreByLogin;
	}

	public List<FollowOrcamentoDesp> getFollowOrcamentosDesp() {
		return followOrcamentosDesp;
	}

	public void setFollowOrcamentosDesp(List<FollowOrcamentoDesp> followOrcamentosDesp) {
		this.followOrcamentosDesp = followOrcamentosDesp;
	}
}