/*
 * @(#) Potencial.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Entity gerado a partir da tabela POTENCIAL.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 05/04/2012 10:53:43
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "POTENCIAL")
@NamedQueries({
        @NamedQuery(name = "Potencial.findAll", query = "SELECT t FROM Potencial t"),
        @NamedQuery(name = "Potencial.findAllActive", query = "SELECT t FROM Potencial t"
                + " WHERE t.indicadorAtivo = 'A' ")})
public class Potencial implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "Potencial.findAll".
     */
    public static final String FIND_ALL = "Potencial.findAll";

    /**
     * Constante para NamedQuery "Potencial.findAllActive".
     */
    public static final String FIND_ALL_ACTIVE = "Potencial.findAllActive";

    /**
     * Atributo gerado a partir da coluna POTE_CD_POTEN_CIAL.
     */
    @Id
    @GeneratedValue(generator = "PotencialSeq")
    @SequenceGenerator(name = "PotencialSeq", sequenceName = "SQ_POTE_CD_POTENCIAL", allocationSize = 1)
    @Column(name = "POTE_CD_POTENCIAL", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoPotencial;

    /**
     * Atributo gerado a partir da coluna POTE_SG_POTENCIAL.
     */
    @Column(name = "POTE_SG_POTENCIAL", length = 3)
    private String siglaPotencial;

    /**
     * Atributo gerado a partir da coluna POTE_NM_POTENCIAL.
     */
    @Column(name = "POTE_NM_POTENCIAL", length = 100)
    private String nomePotencial;

    /**
     * Atributo gerado a partir da coluna POTE_IN_ATIVO.
     */
    @Column(name = "POTE_IN_ATIVO", length = 1)
    private String indicadorAtivo;

    /**
     * Sete de clientes.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "potencial")
    private Set<Cliente> clientes = new HashSet<Cliente>(0);

    /**
     * Construtor default.
     */
    public Potencial() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoPotencial
     *            Valor do atributo codigoPotencial;
     */
    public Potencial(final Long codigoPotencial) {
        this.codigoPotencial = codigoPotencial;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoPotenCial
     *            Valor do atributo codigoPotenCial;
     * @param siglaPotencial
     *            Valor do atributo siglaPotencial;
     * @param nomePotencial
     *            Valor do atributo nomePotencial;
     * @param indicadorAtivo
     *            Valor do atributo indicadorAtivo;
     * @param clientes
     *            Valor do atributo clientes;
     */
    public Potencial(final Long codigoPotenCial, final String siglaPotencial,
            final String nomePotencial, final String indicadorAtivo,
            final Set<Cliente> clientes) {
        this.codigoPotencial = codigoPotenCial;
        this.siglaPotencial = siglaPotencial;
        this.nomePotencial = nomePotencial;
        this.indicadorAtivo = indicadorAtivo;
        this.clientes = clientes;
    }

    /**
     * Obtem o valor do atributo codigoPotenCial.<BR>
     * Atributo gerado a partir da coluna POTE_CD_POTEN_CIAL.
     * 
     * @return Valor do atributo codigoPotenCial.
     */
    public Long getCodigoPotencial() {
        return this.codigoPotencial;
    }

    /**
     * Atualiza o valor do atributo codigoPotenCial.<BR>
     * Atributo gerado a partir da coluna POTE_CD_POTEN_CIAL.
     * 
     * @param codigoPotenCial
     *            Novo valor para o atributo codigoPotenCial.
     */
    public void setCodigoPotencial(final Long codigoPotencial) {
        this.codigoPotencial = codigoPotencial;
    }

    /**
     * Obtem o valor do atributo siglaPotencial.<BR>
     * Atributo gerado a partir da coluna POTE_SG_POTENCIAL.
     * 
     * @return Valor do atributo siglaPotencial.
     */
    public String getSiglaPotencial() {
        return this.siglaPotencial;
    }

    /**
     * Atualiza o valor do atributo siglaPotencial.<BR>
     * Atributo gerado a partir da coluna POTE_SG_POTENCIAL.
     * 
     * @param siglaPotencial
     *            Novo valor para o atributo siglaPotencial.
     */
    public void setSiglaPotencial(final String siglaPotencial) {
        this.siglaPotencial = siglaPotencial;
    }

    /**
     * Obtem o valor do atributo nomePotencial.<BR>
     * Atributo gerado a partir da coluna POTE_NM_POTENCIAL.
     * 
     * @return Valor do atributo nomePotencial.
     */
    public String getNomePotencial() {
        return this.nomePotencial;
    }

    /**
     * Atualiza o valor do atributo nomePotencial.<BR>
     * Atributo gerado a partir da coluna POTE_NM_POTENCIAL.
     * 
     * @param nomePotencial
     *            Novo valor para o atributo nomePotencial.
     */
    public void setNomePotencial(final String nomePotencial) {
        this.nomePotencial = nomePotencial;
    }

    /**
     * Obtem o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna POTE_IN_ATIVO.
     * 
     * @return Valor do atributo indicadorAtivo.
     */
    public String getIndicadorAtivo() {
        return this.indicadorAtivo;
    }

    /**
     * Atualiza o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna POTE_IN_ATIVO.
     * 
     * @param indicadorAtivo
     *            Novo valor para o atributo indicadorAtivo.
     */
    public void setIndicadorAtivo(final String indicadorAtivo) {
        this.indicadorAtivo = indicadorAtivo;
    }

    /**
     * Obtem o valor do atributo clientes.<BR>
     * 
     * @return Valor do atributo clientes.
     */
    public Set<Cliente> getClientes() {
        return this.clientes;
    }

    /**
     * Atualiza o valor do atributo clientes.<BR>
     * 
     * @param clientes
     *            Novo valor para o atributo clientes.
     */
    public void setClientes(final Set<Cliente> clientes) {
        this.clientes = clientes;
    }

    /**
     * Método toString.
     * 
     * @see Object#toString()
     * 
     * @return String representando o objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoPotenCial").append("='").append(
                getCodigoPotencial()).append("' ");
        buffer.append("siglaPotencial").append("='")
                .append(getSiglaPotencial()).append("' ");
        buffer.append("nomePotencial").append("='").append(getNomePotencial())
                .append("' ");
        buffer.append("indicadorAtivo").append("='")
                .append(getIndicadorAtivo()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}