/*
 * @(#) ReceitaPlantao.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import org.hibernate.annotations.Type;

import java.math.BigDecimal;

import javax.persistence.*;

/**
 * Entity gerado a partir da tabela RECEITA_PLANTAO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 14/07/2011 14:25:43
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "RECEITA_PLANTAO")
@NamedNativeQueries(@NamedNativeQuery(name = "ReceitaPlantao.updateStatusReceitaPlantao", query = "UPDATE RECEITA_PLANTAO RP " +
				" SET RP.REPL_IN_INTEGRACAO = :revenueStatus," +
				" RP.REPL_CD_ERP_PEDIDO =  :orderID " +
				" WHERE RP.REPL_CD_RECEITA_PLANTAO = :revenueCode ", resultClass = ReceitaPlantao.class))
@NamedQueries({
		@NamedQuery(name = "ReceitaPlantao.findAll", query = "SELECT t FROM ReceitaPlantao t"),

		@NamedQuery(name = "ReceitaPlantao.findByReceitaDealFiscal", query = "SELECT t FROM ReceitaPlantao t "
				+ "JOIN FETCH t.receitaDealFiscal rdf "
				+ "WHERE rdf.codigoReceitaDfiscal = :codigoReceitaDfiscal")
})
public class ReceitaPlantao implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "AjusteReceita.findAll".
	 */
	public static final String FIND_ALL = "ReceitaPlantao.findAll";

	public static final String UPDATE_STATUS_RECEITA_PLANTAO = "ReceitaPlantao.updateStatusReceitaPlantao";
	
	/**
	 * Constante para NamedQuery "AjusteReceita.findByReceitaDealFiscal".
	 */
	public static final String FIND_BY_RECEITA_DEAL_FISCAL = "ReceitaPlantao.findByReceitaDealFiscal";

	/**
	 * Atributo gerado a partir da coluna AJRE_CD_AJUSTE_RECEITA.
	 */
	@Id
	@GeneratedValue(generator = "ReceitaPlantaoSeq")
	@SequenceGenerator(name = "ReceitaPlantaoSeq", sequenceName = "SQ_REPL_CD_RECEITA_PLANTAO", allocationSize = 1)
	@Column(name = "REPL_CD_RECEITA_PLANTAO", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoReceitaPlantao;

	/**
	 * Atributo gerado a partir da coluna REDF_CD_RECEITA_DFISCAL.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REDF_CD_RECEITA_DFISCAL", nullable = false)
	private ReceitaDealFiscal receitaDealFiscal;

	/**
	 * Atributo gerado a partir da coluna AJRE_VL_AJUSTE.
	 */
	@Column(name = "REPL_VL_RECEITA_PLANTAO", precision = 22, scale = 0)
	private BigDecimal valorReceitaPlantao;

	@Column(name = "REPL_IN_INTEGRACAO", length = 1)
	private String indicadorStatus;

	@Column(name = "REPL_CD_ERP_PEDIDO", precision = 22, scale = 0)
	private BigDecimal codigoErpPedido;

	@Column(name = "REPL_IN_INTEG_QB_ONLINE", length = 1)
	private String indicadorIntegradoQBO;

	/**
	 * Construtor default.
	 */
	public ReceitaPlantao() {
	    this.indicadorStatus = "N";
	}
	
	/**
	 * Construtor para quando é necessário exibir uma {@link ReceitaPlantao}
	 * antes dela ser persistida.
	 */
	public ReceitaPlantao(ReceitaDealFiscal receitaDealFiscal) {
		this.receitaDealFiscal = receitaDealFiscal;
		this.valorReceitaPlantao = BigDecimal.ZERO;
		this.indicadorStatus = "N";
	}

	/**
	 * Construtor com preenchimento da entidade.
	 */
	public ReceitaPlantao(final Long codigoReceitaPlantao,
			final ReceitaDealFiscal receitaDealFiscal,
			final BigDecimal valorReceitaPlantao) {
		this.codigoReceitaPlantao = codigoReceitaPlantao;
		this.receitaDealFiscal = receitaDealFiscal;
		this.valorReceitaPlantao = valorReceitaPlantao;
		this.indicadorStatus = "N";
	}

	/**
	 * @return the codigoReceitaPlantao
	 */
	public Long getCodigoReceitaPlantao() {
		return codigoReceitaPlantao;
	}

	/**
	 * @param codigoReceitaPlantao the codigoReceitaPlantao to set
	 */
	public void setCodigoReceitaPlantao(Long codigoReceitaPlantao) {
		this.codigoReceitaPlantao = codigoReceitaPlantao;
	}

	/**
	 * Obtem o valor do atributo receitaDealFiscal.<BR>
	 * Atributo gerado a partir da coluna REDF_CD_RECEITA_DFISCAL.
	 * 
	 * @return Valor do atributo receitaDealFiscal.
	 */
	public ReceitaDealFiscal getReceitaDealFiscal() {
		return this.receitaDealFiscal;
	}

	/**
	 * Atualiza o valor do atributo receitaDealFiscal.<BR>
	 * Atributo gerado a partir da coluna REDF_CD_RECEITA_DFISCAL.
	 * 
	 * @param receitaDealFiscal
	 *            Novo valor para o atributo receitaDealFiscal.
	 */
	public void setReceitaDealFiscal(final ReceitaDealFiscal receitaDealFiscal) {
		this.receitaDealFiscal = receitaDealFiscal;
	}

	/**
	 * @return the valorReceitaPlantao
	 */
	public BigDecimal getValorReceitaPlantao() {
		return valorReceitaPlantao;
	}

	/**
	 * @param valorReceitaPlantao the valorReceitaPlantao to set
	 */
	public void setValorReceitaPlantao(BigDecimal valorReceitaPlantao) {
		this.valorReceitaPlantao = valorReceitaPlantao;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public String getIndicadorStatus() {
		return indicadorStatus;
	}

	public void setIndicadorStatus(String indicadorStatus) {
		this.indicadorStatus = indicadorStatus;
	}

	public BigDecimal getCodigoErpPedido() {
		return codigoErpPedido;
	}

	public void setCodigoErpPedido(BigDecimal codigoErpPedido) {
		this.codigoErpPedido = codigoErpPedido;
	}

	public String getIndicadorIntegradoQBO() {
		return indicadorIntegradoQBO;
	}

	public void setIndicadorIntegradoQBO(String indicadorIntegradoQBO) {
		this.indicadorIntegradoQBO = indicadorIntegradoQBO;
	}
}