/*
 * @(#) TabelaPerfilPadrao.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela TABELA_PERFIL_PADRAO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 04/07/2012 14:23:59
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "TABELA_PERFIL_PADRAO")
@NamedQueries({
        @NamedQuery(name = "TabelaPerfilPadrao.findAll", query = "SELECT t FROM TabelaPerfilPadrao t"
                + " ORDER BY t.dataInicio ASC"),

        @NamedQuery(name = "TabelaPerfilPadrao.findMaxStartDate", query = "SELECT tpp FROM TabelaPerfilPadrao tpp"
                + " WHERE tpp.dataInicio = "
                + "(SELECT MAX(t.dataInicio) FROM TabelaPerfilPadrao t)"),
        @NamedQuery(name = "TabelaPerfilPadrao.findMaxStartDataByCurrency", query = "SELECT tpp FROM TabelaPerfilPadrao tpp "
                + "WHERE tpp.dataInicio = "
                + "(SELECT MAX(t.dataInicio) FROM TabelaPerfilPadrao t WHERE t.moeda.codigoMoeda = ?) "
                + "AND tpp.moeda.codigoMoeda = ?")
                })
public class TabelaPerfilPadrao implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "TabelaPerfilPadrao.findAll".
     */
    public static final String FIND_ALL = "TabelaPerfilPadrao.findAll";

    /** Constante para namedQuery. */
    public static final String FIND_MAX_START_DATE =
            "TabelaPerfilPadrao.findMaxStartDate";
            
/** Constante para namedQuery findMaxStartDataByCurrency. */
    public static final String FIND_MAX_START_DATE_BY_CURRENCY =
            "TabelaPerfilPadrao.findMaxStartDataByCurrency";            

    /**
     * Relacionamento um para muitos.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tabelaPerfilPadrao")
    private List<ItemTabPerPadrao> itemTabPerPadrao =
            new ArrayList<ItemTabPerPadrao>(0);

    /**
     * Atributo gerado a partir da coluna TAPP_CD_TAB_PERFIL_PADRAO.
     */
    @Id
    @GeneratedValue(generator = "TabelaPerfilPadraoSeq")
    @SequenceGenerator(name = "TabelaPerfilPadraoSeq", sequenceName = "SQ_TAPP_CD_TAB_PER_PADRAO", allocationSize = 1)
    @Column(name = "TAPP_CD_TAB_PERFIL_PADRAO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoTabPerfilPadrao;

    /**
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MOED_CD_MOEDA")
    private Moeda moeda;

    /**
     * Atributo gerado a partir da coluna TAPP_NM_TAB_PERFIL_PADRAO.
     */

    @Column(name = "TAPP_NM_TAB_PERFIL_PADRAO")
    private String nomeTabPerfilPadrao;

    /**
     * Atributo gerado a partir da coluna TAPP_DT_INICIO.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "TAPP_DT_INICIO", length = 7)
    private Date dataInicio;

    /**
     * Atributo gerado a partir da coluna TAPP_DT_FIM.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "TAPP_DT_FIM", length = 7)
    private Date dataFim;

    /**
     * 
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tabelaPerfilPadrao")
    private Set<ItemTabPerPadrao> itemTabPerPadraos =
            new HashSet<ItemTabPerPadrao>(0);

    /**
     * Construtor default.
     */
    public TabelaPerfilPadrao() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoTabPerfilPadrao
     *            Valor do atributo codigoTabPerfilPadrao;
     */
    public TabelaPerfilPadrao(final Long codigoTabPerfilPadrao) {
        this.codigoTabPerfilPadrao = codigoTabPerfilPadrao;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoTabPerfilPadrao
     *            Valor do atributo codigoTabPerfilPadrao;
     * @param moeda
     *            Valor do atributo moeda;
     * @param nomeTabPerfilPadrao
     *            Valor do atributo nomeTabPerfilPadrao;
     * @param dataInicio
     *            Valor do atributo dataInicio;
     * @param dataFim
     *            Valor do atributo dataFim;
     * @param itemTabPerPadraos
     *            Valor do atributo itemTabPerPadraos;
     */
    public TabelaPerfilPadrao(final Long codigoTabPerfilPadrao,
            final Moeda moeda, final String nomeTabPerfilPadrao,
            final Date dataInicio, final Date dataFim,
            final Set<ItemTabPerPadrao> itemTabPerPadraos) {
        this.codigoTabPerfilPadrao = codigoTabPerfilPadrao;
        this.moeda = moeda;
        this.nomeTabPerfilPadrao = nomeTabPerfilPadrao;
        this.dataInicio = dataInicio;
        this.dataFim = dataFim;
        this.itemTabPerPadraos = itemTabPerPadraos;
    }

    /**
     * Obtem o valor do atributo codigoTabPerfilPadrao.<BR>
     * Atributo gerado a partir da coluna TAPP_CD_TAB_PERFIL_PADRAO.
     * 
     * @return Valor do atributo codigoTabPerfilPadrao.
     */
    public Long getCodigoTabPerfilPadrao() {
        return this.codigoTabPerfilPadrao;
    }

    /**
     * Atualiza o valor do atributo codigoTabPerfilPadrao.<BR>
     * Atributo gerado a partir da coluna TAPP_CD_TAB_PERFIL_PADRAO.
     * 
     * @param codigoTabPerfilPadrao
     *            Novo valor para o atributo codigoTabPerfilPadrao.
     */
    public void setCodigoTabPerfilPadrao(final Long codigoTabPerfilPadrao) {
        this.codigoTabPerfilPadrao = codigoTabPerfilPadrao;
    }

    /**
     * Obtem o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * 
     * @return Valor do atributo moeda.
     */
    public Moeda getMoeda() {
        return this.moeda;
    }

    /**
     * Atualiza o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * 
     * @param moeda
     *            Novo valor para o atributo moeda.
     */
    public void setMoeda(final Moeda moeda) {
        this.moeda = moeda;
    }

    /**
     * Obtem o valor do atributo nomeTabPerfilPadrao.<BR>
     * Atributo gerado a partir da coluna TAPP_NM_TAB_PERFIL_PADRAO.
     * 
     * @return Valor do atributo nomeTabPerfilPadrao.
     */
    public String getNomeTabPerfilPadrao() {
        return this.nomeTabPerfilPadrao;
    }

    /**
     * Atualiza o valor do atributo nomeTabPerfilPadrao.<BR>
     * Atributo gerado a partir da coluna TAPP_NM_TAB_PERFIL_PADRAO.
     * 
     * @param nomeTabPerfilPadrao
     *            Novo valor para o atributo nomeTabPerfilPadrao.
     */
    public void setNomeTabPerfilPadrao(final String nomeTabPerfilPadrao) {
        this.nomeTabPerfilPadrao = nomeTabPerfilPadrao;
    }

    /**
     * Obtem o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna TAPP_DT_INICIO.
     * 
     * @return Valor do atributo dataInicio.
     */
    public Date getDataInicio() {
        return this.dataInicio;
    }

    /**
     * Atualiza o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna TAPP_DT_INICIO.
     * 
     * @param dataInicio
     *            Novo valor para o atributo dataInicio.
     */
    public void setDataInicio(final Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    /**
     * Obtem o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna TAPP_DT_FIM.
     * 
     * @return Valor do atributo dataFim.
     */
    public Date getDataFim() {
        return this.dataFim;
    }

    /**
     * Atualiza o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna TAPP_DT_FIM.
     * 
     * @param dataFim
     *            Novo valor para o atributo dataFim.
     */
    public void setDataFim(final Date dataFim) {
        this.dataFim = dataFim;
    }

    /**
     * Obtem o valor do atributo itemTabPerPadraos.<BR>
     * 
     * @return Valor do atributo itemTabPerPadraos.
     */
    public Set<ItemTabPerPadrao> getItemTabPerPadraos() {
        return this.itemTabPerPadraos;
    }

    /**
     * Atualiza o valor do atributo itemTabPerPadraos.<BR>
     * 
     * @param itemTabPerPadraos
     *            Novo valor para o atributo itemTabPerPadraos.
     */
    public void setItemTabPerPadraos(
            final Set<ItemTabPerPadrao> itemTabPerPadraos) {
        this.itemTabPerPadraos = itemTabPerPadraos;
    }

    /**
     * @see Object#toString()
     * @return buffer
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoTabPerfilPadrao").append("='").append(
                getCodigoTabPerfilPadrao()).append("' ");
        buffer.append("moeda").append("='").append(getMoeda()).append("' ");
        buffer.append("nomeTabPerfilPadrao").append("='").append(
                getNomeTabPerfilPadrao()).append("' ");
        buffer.append("dataInicio").append("='").append(getDataInicio())
                .append("' ");
        buffer.append("dataFim").append("='").append(getDataFim()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    /**
     * @return the itemTabPerPadrao
     */
    public List<ItemTabPerPadrao> getItemTabPerPadrao() {
        return itemTabPerPadrao;
    }

    /**
     * @param itemTabPerPadrao
     *            the itemTabPerPadrao to set
     */
    public void setItemTabPerPadrao(
            final List<ItemTabPerPadrao> itemTabPerPadrao) {
        this.itemTabPerPadrao = itemTabPerPadrao;
    }

}
