/*
 * @(#) TcePapelAlocacao.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela TCE_PAPEL_ALOCACAO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 25/01/2010 16:33:48
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "TCE_PAPEL_ALOCACAO")
@NamedQueries({
        @NamedQuery(name = "TcePapelAlocacao.findAll", query = "SELECT t FROM TcePapelAlocacao t "
                + "ORDER BY t.dataInicio ASC "),
        @NamedQuery(name = "TcePapelAlocacao.findByPapelAlocacao", 
                query = "SELECT tcpa FROM TcePapelAlocacao tcpa "
                + "WHERE tcpa.papelAlocacao.codigoPapelAlocacao = ? "
                + "ORDER BY tcpa.dataInicio ASC "),
                
        @NamedQuery(name = "TcePapelAlocacao.findMaxStartDateByPapelAlocacao", 
                query = "SELECT tcpa FROM TcePapelAlocacao tcpa "
                + "WHERE tcpa.papelAlocacao.codigoPapelAlocacao = ? "
                + "AND tcpa.dataInicio = "
                + "(SELECT MAX(t.dataInicio) FROM TcePapelAlocacao t "
                + "WHERE t.papelAlocacao.codigoPapelAlocacao = ?) "),
                
        @NamedQuery(name = "TcePapelAlocacao.findByPapelAndDate", 
                query = "SELECT tcpa FROM TcePapelAlocacao tcpa "
                + "WHERE tcpa.papelAlocacao.codigoPapelAlocacao = ? "
                + " AND TRUNC(?) >= TRUNC(tcpa.dataInicio) " 
                + " AND (TRUNC(?) <= TRUNC(tcpa.dataFim) OR tcpa.dataFim is null)")
})                
public class TcePapelAlocacao implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /** Constante para NamedQuery "TcePapelAlocacao.findByPapelAlocacao". */
    public static final String FIND_BY_PAPEL_ALOCACAO = "TcePapelAlocacao.findByPapelAlocacao";

    /** Constante para NamedQuery "TcePapelAlocacao.findMaxStartDateByPapelAlocacao". */
    public static final String FIND_MAX_START_DATE_BY_PAPEL_ALOCACAO = 
        "TcePapelAlocacao.findMaxStartDateByPapelAlocacao";
    
    /** Constante para NamedQuery "TcePapelAlocacao.findByPapelAndDate". */
    public static final String FIND_BY_PAPEL_AND_DATE = 
        "TcePapelAlocacao.findByPapelAndDate";

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "TcePapelAlocacao.findAll".
     */
    public static final String FIND_ALL = "TcePapelAlocacao.findAll";

    /**
     * Atributo gerado a partir da coluna TCPA_CD_TCE_PAPEL_ALOC.
     */
    @Id
    @GeneratedValue(generator = "TcePapelAlocacaoSeq")
    @SequenceGenerator(name = "TcePapelAlocacaoSeq", 
            sequenceName = "SQ_TCPA_CD_TCE_PAPEL_ALOC", allocationSize = 1)
    @Column(name = "TCPA_CD_TCE_PAPEL_ALOC", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoTcePapelAloc;

    /**
     * Atributo gerado a partir da coluna PAAL_CD_PAPEL_ALOCACAO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PAAL_CD_PAPEL_ALOCACAO", nullable = false)
    private PapelAlocacao papelAlocacao;

    /**
     * Atributo gerado a partir da coluna TCPA_DT_INICIO.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "TCPA_DT_INICIO", length = 7)
    private Date dataInicio;

    /**
     * Atributo gerado a partir da coluna TCPA_DT_FIM.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "TCPA_DT_FIM", length = 7)
    private Date dataFim;

    /**
     * Atributo gerado a partir da coluna TCPA_VL_TCE.
     */

    @Column(name = "TCPA_VL_TCE", precision = 22, scale = 0)
    private BigDecimal valorTce;

    /**
     * Construtor default.
     */
    public TcePapelAlocacao() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoTcePapelAloc
     *            Valor do atributo codigoTcePapelAloc;
     * @param papelAlocacao
     *            Valor do atributo papelAlocacao;
     */
    public TcePapelAlocacao(final Long codigoTcePapelAloc,
            final PapelAlocacao papelAlocacao) {
        this.codigoTcePapelAloc = codigoTcePapelAloc;
        this.papelAlocacao = papelAlocacao;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoTcePapelAloc
     *            Valor do atributo codigoTcePapelAloc;
     * @param papelAlocacao
     *            Valor do atributo papelAlocacao;
     * @param dataInicio
     *            Valor do atributo dataInicio;
     * @param dataFim
     *            Valor do atributo dataFim;
     * @param valorTce
     *            Valor do atributo valorTce;
     */
    public TcePapelAlocacao(final Long codigoTcePapelAloc,
            final PapelAlocacao papelAlocacao, final Date dataInicio,
            final Date dataFim, final BigDecimal valorTce) {
        this.codigoTcePapelAloc = codigoTcePapelAloc;
        this.papelAlocacao = papelAlocacao;
        this.dataInicio = dataInicio;
        this.dataFim = dataFim;
        this.valorTce = valorTce;
    }

    /**
     * Obtem o valor do atributo codigoTcePapelAloc.<BR>
     * Atributo gerado a partir da coluna TCPA_CD_TCE_PAPEL_ALOC.
     * 
     * @return Valor do atributo codigoTcePapelAloc.
     */
    public Long getCodigoTcePapelAloc() {
        return this.codigoTcePapelAloc;
    }

    /**
     * Atualiza o valor do atributo codigoTcePapelAloc.<BR>
     * Atributo gerado a partir da coluna TCPA_CD_TCE_PAPEL_ALOC.
     * 
     * @param codigoTcePapelAloc
     *            Novo valor para o atributo codigoTcePapelAloc.
     */
    public void setCodigoTcePapelAloc(final Long codigoTcePapelAloc) {
        this.codigoTcePapelAloc = codigoTcePapelAloc;
    }

    /**
     * Obtem o valor do atributo papelAlocacao.<BR>
     * Atributo gerado a partir da coluna PAAL_CD_PAPEL_ALOCACAO.
     * 
     * @return Valor do atributo papelAlocacao.
     */
    public PapelAlocacao getPapelAlocacao() {
        return this.papelAlocacao;
    }

    /**
     * Atualiza o valor do atributo papelAlocacao.<BR>
     * Atributo gerado a partir da coluna PAAL_CD_PAPEL_ALOCACAO.
     * 
     * @param papelAlocacao
     *            Novo valor para o atributo papelAlocacao.
     */
    public void setPapelAlocacao(final PapelAlocacao papelAlocacao) {
        this.papelAlocacao = papelAlocacao;
    }

    /**
     * Obtem o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna TCPA_DT_INICIO.
     * 
     * @return Valor do atributo dataInicio.
     */
    public Date getDataInicio() {
        return this.dataInicio;
    }

    /**
     * Atualiza o valor do atributo dataInicio.<BR>
     * Atributo gerado a partir da coluna TCPA_DT_INICIO.
     * 
     * @param dataInicio
     *            Novo valor para o atributo dataInicio.
     */
    public void setDataInicio(final Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    /**
     * Obtem o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna TCPA_DT_FIM.
     * 
     * @return Valor do atributo dataFim.
     */
    public Date getDataFim() {
        return this.dataFim;
    }

    /**
     * Atualiza o valor do atributo dataFim.<BR>
     * Atributo gerado a partir da coluna TCPA_DT_FIM.
     * 
     * @param dataFim
     *            Novo valor para o atributo dataFim.
     */
    public void setDataFim(final Date dataFim) {
        this.dataFim = dataFim;
    }

    /**
     * Obtem o valor do atributo valorTce.<BR>
     * Atributo gerado a partir da coluna TCPA_VL_TCE.
     * 
     * @return Valor do atributo valorTce.
     */
    public BigDecimal getValorTce() {
        return this.valorTce;
    }

    /**
     * Atualiza o valor do atributo valorTce.<BR>
     * Atributo gerado a partir da coluna TCPA_VL_TCE.
     * 
     * @param valorTce
     *            Novo valor para o atributo valorTce.
     */
    public void setValorTce(final BigDecimal valorTce) {
        this.valorTce = valorTce;
    }

    /**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoTcePapelAloc").append("='").append(
                getCodigoTcePapelAloc()).append("' ");
        buffer.append("papelAlocacao").append("='").append(getPapelAlocacao())
                .append("' ");
        buffer.append("dataInicio").append("='").append(getDataInicio())
                .append("' ");
        buffer.append("dataFim").append("='").append(getDataFim()).append("' ");
        buffer.append("valorTce").append("='").append(getValorTce()).append(
                "' ");
        buffer.append("]");

        return buffer.toString();
    }

}
