/*
 * @(#) TipoContratoEncargo.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela TIPO_CONTRATO_ENCARGO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 31/05/2011 08:36:36
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "TIPO_CONTRATO_ENCARGO")
@NamedQueries({
        @NamedQuery(name = "TipoContratoEncargo.findAll", query = "SELECT t FROM TipoContratoEncargo t"),
        @NamedQuery(name = "TipoContratoEncargo.findByStartDate", query = " SELECT t FROM TipoContratoEncargo t "
                + " WHERE t.dataInicioVigencia = ? "
                + " AND t.tipoContrato.codigoTipoContrato = ?"),
        @NamedQuery(name = "TipoContratoEncargo.findPrevious", query = "SELECT t FROM TipoContratoEncargo t"
                + " WHERE t.tipoContrato.codigoTipoContrato = ? "
                + " AND TRUNC(t.dataInicioVigencia) = "
                + "     (SELECT MAX(TRUNC(tceBefore.dataInicioVigencia)) "
                + "         FROM TipoContratoEncargo tceBefore "
                + "         WHERE tceBefore.tipoContrato.codigoTipoContrato = ?"
                + "         AND tceBefore.dataInicioVigencia < ?)"),

        @NamedQuery(name = "TipoContratoEncargo.findNext", query = "SELECT t FROM TipoContratoEncargo t"
                + " WHERE t.tipoContrato.codigoTipoContrato = ? "
                + " AND TRUNC(t.dataInicioVigencia) = "
                + "     (SELECT MIN(TRUNC(tceNext.dataInicioVigencia)) "
                + "         FROM TipoContratoEncargo tceNext "
                + "         WHERE tceNext.tipoContrato.codigoTipoContrato = ?"
                + "         AND tceNext.dataInicioVigencia > ?)") })
public class TipoContratoEncargo implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "TipoContratoEncargo.findAll".
     */
    public static final String FIND_ALL = "TipoContratoEncargo.findAll";

    /** Constante para NamedQuery "TipoContratoEncargo.findNext". */
    public static final String FIND_BY_START_DATE = "TipoContratoEncargo.findByStartDate";

    /** Constante para NamedQuery "TipoContratoEncargo.findPrevious". */
    public static final String FIND_PREVIOUS = "TipoContratoEncargo.findPrevious";

    /** Constante para NamedQuery "TipoContratoEncargo.findNext". */
    public static final String FIND_NEXT = "TipoContratoEncargo.findNext";

    /**
     * Atributo gerado a partir da coluna TICE_CD_TIPO_CONT_ENCARGO.
     */
    @Id
    @GeneratedValue(generator = "TipoContratoEncargoSeq")
    @SequenceGenerator(name = "TipoContratoEncargoSeq", sequenceName = "SQ_TICE_CD_TIPO_CONT_ENCARGO", allocationSize = 1)
    @Column(name = "TICE_CD_TIPO_CONTRATO_ENCARGO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoTipoContratoEncargo;

    /**
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TICO_CD_TIPO_CONTRATO", nullable = false)
    private TipoContrato tipoContrato;

    /**
     * Atributo gerado a partir da coluna TICE_DT_INICIO_VIGENCIA.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "TICE_DT_INICIO_VIGENCIA", length = 7)
    private Date dataInicioVigencia;

    /**
     * Atributo gerado a partir da coluna TICE_DT_FIM_VIGENCIA.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "TICE_DT_FIM_VIGENCIA", length = 7)
    private Date dataFimVigencia;

    /**
     * Atributo gerado a partir da coluna TICE_VL_BENEFICIO_PADRAO.
     */

    @Column(name = "TICE_VL_BENEFICIO_PADRAO", precision = 15)
    private BigDecimal valorBeneficioPadrao;

    /**
     * Atributo gerado a partir da coluna TICE_PR_ENCARGO.
     */

    @Column(name = "TICE_PR_ENCARGO", precision = 10)
    private BigDecimal percentualEncargo;

    /**
     * Construtor default.
     */
    public TipoContratoEncargo() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoTipoContratoEncargo
     *            Valor do atributo codigoTipoContratoEncargo;
     * @param tipoContrato
     *            Valor do atributo tipoContrato;
     */
    public TipoContratoEncargo(final Long codigoTipoContratoEncargo,
            final TipoContrato tipoContrato) {
        this.codigoTipoContratoEncargo = codigoTipoContratoEncargo;
        this.tipoContrato = tipoContrato;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoTipoContratoEncargo
     *            Valor do atributo codigoTipoContratoEncargo;
     * @param tipoContrato
     *            Valor do atributo tipoContrato;
     * @param dataInicioVigencia
     *            Valor do atributo dataInicioVigencia;
     * @param dataFimVigencia
     *            Valor do atributo dataFimVigencia;
     * @param valorBeneficioPadrao
     *            Valor do atributo valorBeneficioPadrao;
     * @param percentualEncargo
     *            Valor do atributo percentualEncargo;
     */
    public TipoContratoEncargo(final Long codigoTipoContratoEncargo,
            final TipoContrato tipoContrato, final Date dataInicioVigencia,
            final Date dataFimVigencia, final BigDecimal valorBeneficioPadrao,
            final BigDecimal percentualEncargo) {
        this.codigoTipoContratoEncargo = codigoTipoContratoEncargo;
        this.tipoContrato = tipoContrato;
        this.dataInicioVigencia = dataInicioVigencia;
        this.dataFimVigencia = dataFimVigencia;
        this.valorBeneficioPadrao = valorBeneficioPadrao;
        this.percentualEncargo = percentualEncargo;
    }

    /**
     * Obtem o valor do atributo codigoTipoContratoEncargo.<BR>
     * Atributo gerado a partir da coluna TICE_CD_TIPO_CONTRATO_ENCARGO.
     * 
     * @return Valor do atributo codigoTipoContratoEncargo.
     */
    public Long getCodigoTipoContratoEncargo() {
        return this.codigoTipoContratoEncargo;
    }

    /**
     * Atualiza o valor do atributo codigoTipoContratoEncargo.<BR>
     * Atributo gerado a partir da coluna TICE_CD_TIPO_CONTRATO_ENCARGO.
     * 
     * @param codigoTipoContratoEncargo
     *            Novo valor para o atributo codigoTipoContratoEncargo.
     */
    public void setCodigoTipoContratoEncargo(
            final Long codigoTipoContratoEncargo) {
        this.codigoTipoContratoEncargo = codigoTipoContratoEncargo;
    }

    /**
     * Obtem o valor do atributo tipoContrato.<BR>
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     * 
     * @return Valor do atributo tipoContrato.
     */
    public TipoContrato getTipoContrato() {
        return this.tipoContrato;
    }

    /**
     * Atualiza o valor do atributo tipoContrato.<BR>
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     * 
     * @param tipoContrato
     *            Novo valor para o atributo tipoContrato.
     */
    public void setTipoContrato(final TipoContrato tipoContrato) {
        this.tipoContrato = tipoContrato;
    }

    /**
     * Obtem o valor do atributo dataInicioVigencia.<BR>
     * Atributo gerado a partir da coluna TICE_DT_INICIO_VIGENCIA.
     * 
     * @return Valor do atributo dataInicioVigencia.
     */
    public Date getDataInicioVigencia() {
        return this.dataInicioVigencia;
    }

    /**
     * Atualiza o valor do atributo dataInicioVigencia.<BR>
     * Atributo gerado a partir da coluna TICE_DT_INICIO_VIGENCIA.
     * 
     * @param dataInicioVigencia
     *            Novo valor para o atributo dataInicioVigencia.
     */
    public void setDataInicioVigencia(final Date dataInicioVigencia) {
        this.dataInicioVigencia = dataInicioVigencia;
    }

    /**
     * Obtem o valor do atributo dataFimVigencia.<BR>
     * Atributo gerado a partir da coluna TICE_DT_FIM_VIGENCIA.
     * 
     * @return Valor do atributo dataFimVigencia.
     */
    public Date getDataFimVigencia() {
        return this.dataFimVigencia;
    }

    /**
     * Atualiza o valor do atributo dataFimVigencia.<BR>
     * Atributo gerado a partir da coluna TICE_DT_FIM_VIGENCIA.
     * 
     * @param dataFimVigencia
     *            Novo valor para o atributo dataFimVigencia.
     */
    public void setDataFimVigencia(final Date dataFimVigencia) {
        this.dataFimVigencia = dataFimVigencia;
    }

    /**
     * Obtem o valor do atributo valorBeneficioPadrao.<BR>
     * Atributo gerado a partir da coluna TICE_VL_BENEFICIO_PADRAO.
     * 
     * @return Valor do atributo valorBeneficioPadrao.
     */
    public BigDecimal getValorBeneficioPadrao() {
        return this.valorBeneficioPadrao;
    }

    /**
     * Atualiza o valor do atributo valorBeneficioPadrao.<BR>
     * Atributo gerado a partir da coluna TICE_VL_BENEFICIO_PADRAO.
     * 
     * @param valorBeneficioPadrao
     *            Novo valor para o atributo valorBeneficioPadrao.
     */
    public void setValorBeneficioPadrao(final BigDecimal valorBeneficioPadrao) {
        this.valorBeneficioPadrao = valorBeneficioPadrao;
    }

    /**
     * Obtem o valor do atributo percentualEncargo.<BR>
     * Atributo gerado a partir da coluna TICE_PR_ENCARGO.
     * 
     * @return Valor do atributo percentualEncargo.
     */
    public BigDecimal getPercentualEncargo() {
        return this.percentualEncargo;
    }

    /**
     * Atualiza o valor do atributo percentualEncargo.<BR>
     * Atributo gerado a partir da coluna TICE_PR_ENCARGO.
     * 
     * @param percentualEncargo
     *            Novo valor para o atributo percentualEncargo.
     */
    public void setPercentualEncargo(final BigDecimal percentualEncargo) {
        this.percentualEncargo = percentualEncargo;
    }

    /**
     * @see Object#toString()
     * @return String
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoTipoContratoEncargo").append("='").append(
                getCodigoTipoContratoEncargo()).append("' ");
        buffer.append("tipoContrato").append("='").append(getTipoContrato())
                .append("' ");
        buffer.append("dataInicioVigencia").append("='").append(
                getDataInicioVigencia()).append("' ");
        buffer.append("dataFimVigencia").append("='").append(
                getDataFimVigencia()).append("' ");
        buffer.append("valorBeneficioPadrao").append("='").append(
                getValorBeneficioPadrao()).append("' ");
        buffer.append("percentualEncargo").append("='").append(
                getPercentualEncargo()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
