/*
 * @(#) TipoDespesa.java
 * Copyright (c) 2010 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela TIPO_DESPESA.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 28/04/2010 10:06:23
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "TIPO_DESPESA")
@NamedQueries({
        @NamedQuery(name = "TipoDespesa.findAllActive", query = "SELECT td FROM TipoDespesa td "
                + " WHERE td.indicadorAtivo = 'A' ORDER BY td.nomeTipoDespesa desc"),
        @NamedQuery(name = "TipoDespesa.findByName", query = "SELECT td FROM TipoDespesa td "
                + " WHERE td.nomeTipoDespesa = ? ORDER BY td.nomeTipoDespesa desc") })
public class TipoDespesa implements java.io.Serializable {

    /** Valor do serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** Constante para NamedQuery "TipoDespesa.findAll". */
    public static final String FIND_ALL_ACTIVE = "TipoDespesa.findAllActive";

    /** Constante para NamedQuery "TipoDespesa.findAll". */
    public static final String FIND_BY_NAME = "TipoDespesa.findByName";

    /**
     * Atributo gerado a partir da coluna TIDE_CD_TIPO_DESPESA.
     */
    @Id
    @GeneratedValue(generator = "TipoDespesaSeq")
    @SequenceGenerator(name = "TipoDespesaSeq", sequenceName = "SQ_TIDE_CD_TIPO_DESPESA", allocationSize = 1)
    @Column(name = "TIDE_CD_TIPO_DESPESA", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoTipoDespesa;

    /**
     * Atributo gerado a partir da coluna TIDE_NM_TIPO_DESPESA.
     */

    @Column(name = "TIDE_NM_TIPO_DESPESA", length = 100)
    private String nomeTipoDespesa;

    /**
     * Atributo gerado a partir da coluna TIDE_IN_ATIVO. A=Ativo; I=Inativo;
     */
    @Column(name = "TIDE_IN_ATIVO", length = 1)
    private String indicadorAtivo;

    /** Atributo gerado a partir da tabela DESPESA_MES. */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDespesa")
    private Set<DespesaMes> despesaMeses = new HashSet<DespesaMes>(0);

    /** Atributo gerado a partir da tabela UPLOAD_DESPESA. */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDespesa")
    private List<UploadDespesa> uploadDespesas = new ArrayList<UploadDespesa>(0);

    /**
     * Construtor default.
     */
    public TipoDespesa() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoTipoDespesa
     *            Valor do atributo codigoTipoDespesa;
     */
    public TipoDespesa(final Long codigoTipoDespesa) {
        this.codigoTipoDespesa = codigoTipoDespesa;
    }

    /**
     * Obtem o valor do atributo codigoTipoDespesa.<BR>
     * Atributo gerado a partir da coluna TIDE_CD_TIPO_DESPESA.
     * 
     * @return Valor do atributo codigoTipoDespesa.
     */
    public Long getCodigoTipoDespesa() {
        return this.codigoTipoDespesa;
    }

    /**
     * Atualiza o valor do atributo codigoTipoDespesa.<BR>
     * Atributo gerado a partir da coluna TIDE_CD_TIPO_DESPESA.
     * 
     * @param codigoTipoDespesa
     *            Novo valor para o atributo codigoTipoDespesa.
     */
    public void setCodigoTipoDespesa(final Long codigoTipoDespesa) {
        this.codigoTipoDespesa = codigoTipoDespesa;
    }

    /**
     * Obtem o valor do atributo nomeTipoDespesa.<BR>
     * Atributo gerado a partir da coluna TIDE_NM_TIPO_DESPESA.
     * 
     * @return Valor do atributo nomeTipoDespesa.
     */
    public String getNomeTipoDespesa() {
        return this.nomeTipoDespesa;
    }

    /**
     * Atualiza o valor do atributo nomeTipoDespesa.<BR>
     * Atributo gerado a partir da coluna TIDE_NM_TIPO_DESPESA.
     * 
     * @param nomeTipoDespesa
     *            Novo valor para o atributo nomeTipoDespesa.
     */
    public void setNomeTipoDespesa(final String nomeTipoDespesa) {
        this.nomeTipoDespesa = nomeTipoDespesa;
    }

    /**
     * Obtem o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna TIDE_IN_ATIVO. A=Ativo; I=Inativo;
     * 
     * @return Valor do atributo indicadorAtivo.
     */
    public String getIndicadorAtivo() {
        return this.indicadorAtivo;
    }

    /**
     * Atualiza o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna TIDE_IN_ATIVO. A=Ativo; I=Inativo;
     * 
     * @param indicadorAtivo
     *            Novo valor para o atributo indicadorAtivo.
     */
    public void setIndicadorAtivo(final String indicadorAtivo) {
        this.indicadorAtivo = indicadorAtivo;
    }

    /**
     * Obtem o valor do atributo despesaMeses.<BR>
     * 
     * @return Valor do atributo despesaMeses.
     */
    public Set<DespesaMes> getDespesaMeses() {
        return this.despesaMeses;
    }

    /**
     * Atualiza o valor do atributo despesaMeses.<BR>
     * 
     * @param despesaMeses
     *            Novo valor para o atributo despesaMeses.
     */
    public void setDespesaMeses(final Set<DespesaMes> despesaMeses) {
        this.despesaMeses = despesaMeses;
    }

    /**
     * @return the uploadDespesas
     */
    public List<UploadDespesa> getUploadDespesas() {
        return uploadDespesas;
    }

    /**
     * @param uploadDespesas
     *            the uploadDespesas to set
     */
    public void setUploadDespesas(final List<UploadDespesa> uploadDespesas) {
        this.uploadDespesas = uploadDespesas;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoTipoDespesa").append("='").append(
                getCodigoTipoDespesa()).append("' ");
        buffer.append("nomeTipoDespesa").append("='").append(
                getNomeTipoDespesa()).append("' ");
        buffer.append("indicadorAtivo").append("='")
                .append(getIndicadorAtivo()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
