/*
 * @(#) TipoAjuste.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela TIPO_AJUSTE.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 14/07/2011 14:25:43
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "TIPO_AJUSTE")
@NamedQueries({
        @NamedQuery(name = "TipoAjuste.findAll", query = "SELECT t FROM TipoAjuste t"),

        @NamedQuery(name = "TipoAjuste.findAllActive", query = "SELECT t FROM TipoAjuste t "
                + " WHERE t.indicadorAtivo = 'A' ")

})
public class TipoAjuste implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /** Constante para NamedQuery "TipoAjuste.findAllActive". */
    public static final String FIND_ALL_ACTIVE = "TipoAjuste.findAllActive";

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "TipoAjuste.findAll".
     */
    public static final String FIND_ALL = "TipoAjuste.findAll";

    /**
     * Atributo gerado a partir da coluna TIAJ_CD_TIPO_AJUSTE.
     */
    @Id
    @GeneratedValue(generator = "TipoAjusteSeq")
    @SequenceGenerator(name = "TipoAjusteSeq", sequenceName = "SQ_TIAJ_CD_TIPO_AJUSTE", allocationSize = 1)
    @Column(name = "TIAJ_CD_TIPO_AJUSTE", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoTipoAjuste;

    /**
     * Atributo gerado a partir da coluna TIAJ_NM_TIPO_AJUSTE.
     */

    @Column(name = "TIAJ_NM_TIPO_AJUSTE", nullable = false, length = 100)
    private String nomeTipoAjuste;

    /**
     * Atributo gerado a partir da coluna TIAJ_IN_ATIVO.
     */

    @Column(name = "TIAJ_IN_ATIVO", nullable = false, length = 1)
    private String indicadorAtivo;

    /** Lista de AjusteReceita. */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAjuste")
    private Set<AjusteReceita> ajusteReceitas = new HashSet<AjusteReceita>(0);

    /**
     * Construtor default.
     */
    public TipoAjuste() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoTipoAjuste
     *            Valor do atributo codigoTipoAjuste;
     * @param nomeTipoAjuste
     *            Valor do atributo nomeTipoAjuste;
     * @param indicadorAtivo
     *            Valor do atributo indicadorAtivo;
     */
    public TipoAjuste(final Long codigoTipoAjuste, final String nomeTipoAjuste,
            final String indicadorAtivo) {
        this.codigoTipoAjuste = codigoTipoAjuste;
        this.nomeTipoAjuste = nomeTipoAjuste;
        this.indicadorAtivo = indicadorAtivo;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoTipoAjuste
     *            Valor do atributo codigoTipoAjuste;
     * @param nomeTipoAjuste
     *            Valor do atributo nomeTipoAjuste;
     * @param indicadorAtivo
     *            Valor do atributo indicadorAtivo;
     * @param ajusteReceitas
     *            Valor do atributo ajusteReceitas;
     */
    public TipoAjuste(final Long codigoTipoAjuste, final String nomeTipoAjuste,
            final String indicadorAtivo, final Set<AjusteReceita> ajusteReceitas) {
        this.codigoTipoAjuste = codigoTipoAjuste;
        this.nomeTipoAjuste = nomeTipoAjuste;
        this.indicadorAtivo = indicadorAtivo;
        this.ajusteReceitas = ajusteReceitas;
    }

    /**
     * Obtem o valor do atributo codigoTipoAjuste.<BR>
     * Atributo gerado a partir da coluna TIAJ_CD_TIPO_AJUSTE.
     * 
     * @return Valor do atributo codigoTipoAjuste.
     */
    public Long getCodigoTipoAjuste() {
        return this.codigoTipoAjuste;
    }

    /**
     * Atualiza o valor do atributo codigoTipoAjuste.<BR>
     * Atributo gerado a partir da coluna TIAJ_CD_TIPO_AJUSTE.
     * 
     * @param codigoTipoAjuste
     *            Novo valor para o atributo codigoTipoAjuste.
     */
    public void setCodigoTipoAjuste(final Long codigoTipoAjuste) {
        this.codigoTipoAjuste = codigoTipoAjuste;
    }

    /**
     * Obtem o valor do atributo nomeTipoAjuste.<BR>
     * Atributo gerado a partir da coluna TIAJ_NM_TIPO_AJUSTE.
     * 
     * @return Valor do atributo nomeTipoAjuste.
     */
    public String getNomeTipoAjuste() {
        return this.nomeTipoAjuste;
    }

    /**
     * Atualiza o valor do atributo nomeTipoAjuste.<BR>
     * Atributo gerado a partir da coluna TIAJ_NM_TIPO_AJUSTE.
     * 
     * @param nomeTipoAjuste
     *            Novo valor para o atributo nomeTipoAjuste.
     */
    public void setNomeTipoAjuste(final String nomeTipoAjuste) {
        this.nomeTipoAjuste = nomeTipoAjuste;
    }

    /**
     * Obtem o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna TIAJ_IN_ATIVO.
     * 
     * @return Valor do atributo indicadorAtivo.
     */
    public String getIndicadorAtivo() {
        return this.indicadorAtivo;
    }

    /**
     * Atualiza o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna TIAJ_IN_ATIVO.
     * 
     * @param indicadorAtivo
     *            Novo valor para o atributo indicadorAtivo.
     */
    public void setIndicadorAtivo(final String indicadorAtivo) {
        this.indicadorAtivo = indicadorAtivo;
    }

    /**
     * Obtem o valor do atributo ajusteReceitas.<BR>
     * 
     * @return Valor do atributo ajusteReceitas.
     */
    public Set<AjusteReceita> getAjusteReceitas() {
        return this.ajusteReceitas;
    }

    /**
     * Atualiza o valor do atributo ajusteReceitas.<BR>
     * 
     * @param ajusteReceitas
     *            Novo valor para o atributo ajusteReceitas.
     */
    public void setAjusteReceitas(final Set<AjusteReceita> ajusteReceitas) {
        this.ajusteReceitas = ajusteReceitas;
    }

    /**
     * @see Object#toString()
     * @return string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoTipoAjuste").append("='").append(
                getCodigoTipoAjuste()).append("' ");
        buffer.append("nomeTipoAjuste").append("='")
                .append(getNomeTipoAjuste()).append("' ");
        buffer.append("indicadorAtivo").append("='")
                .append(getIndicadorAtivo()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
