/*
 * @(#) TipoContrato.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela TIPO_CONTRATO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 25/02/2010 11:01:28
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "TIPO_CONTRATO")
@NamedQueries({
        @NamedQuery(name = "TipoContrato.findAll", query = "SELECT t FROM TipoContrato t"),

        @NamedQuery(name = "TipoContrato.findAllActive", query = "SELECT tc FROM TipoContrato tc "
                + "WHERE tc.indicadorAtivo = 'A' ORDER BY tc.nomeTipoContrato") })
public class TipoContrato implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /** Constante para NamedQuery "TipoContrato.findAllActive". */
    public static final String FIND_ALL_ACTIVE = "TipoContrato.findAllActive";

    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "TipoContrato.findAll".
     */
    public static final String FIND_ALL = "TipoContrato.findAll";

    /**
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     */
    @Id
    @GeneratedValue(generator = "TipoContratoSeq")
    @SequenceGenerator(name = "TipoContratoSeq", sequenceName = "SQ_TICO_CD_TIPO_CONTRATO", allocationSize = 1)
    @Column(name = "TICO_CD_TIPO_CONTRATO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoTipoContrato;

    /**
     * Atributo gerado a partir da coluna TICO_NM_TIPO_CONTRATO.
     */

    @Column(name = "TICO_NM_TIPO_CONTRATO", length = 50)
    private String nomeTipoContrato;

    /**
     * Atributo gerado a partir da coluna TICO_SG_TIPO_CONTRATO.
     */

    @Column(name = "TICO_SG_TIPO_CONTRATO", length = 4)
    private String siglaTipoContrato;

    /**
     * Atributo gerado a partir da coluna TICO_IN_ATIVO.
     */

    @Column(name = "TICO_IN_ATIVO", length = 1)
    private String indicadorAtivo;

    /**
     * Atributo gerado a partir da coluna TICO_PR_ALOCAVEL_PADRAO.
     */
    @Column(name = "TICO_PR_ALOCAVEL_PADRAO", precision = 10)
    private BigDecimal percentualAlocavelPadrao;

    /**
     * Atributo gerado a partir da coluna TICO_VL_JORNADA_PADRAO.
     */

    @Column(name = "TICO_VL_JORNADA_PADRAO", precision = 22, scale = 0)
    private BigDecimal valorJornadaPadrao;

    /**
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MOED_CD_MOEDA")
    private Moeda moeda;

    /**
     * Relacionamento um para muitos - TipoContratoEncargo.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContrato")
    @OrderBy("dataInicioVigencia, ASC")
    private List<TipoContratoEncargo> tipoContratoEncargos = new ArrayList<TipoContratoEncargo>(
            0);

    /**
     * Relacionamento um para muitos - Pessoa.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContrato")
    private Set<Pessoa> pessoas = new HashSet<Pessoa>(0);

    /**
     * Relacionamento um para muitos - FatorReajuste.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContrato")
    private Set<FatorReajuste> fatorReajustes = new HashSet<FatorReajuste>(0);

    /**
     * Relacionamento um para muitos - PessoaTipoContrato.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContrato")
    private Set<PessoaTipoContrato> pessoaTipoContratos = new HashSet<PessoaTipoContrato>(
            0);

    /**
     * Construtor default.
     */
    public TipoContrato() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoTipoContrato
     *            Valor do atributo codigoTipoContrato;
     */
    public TipoContrato(final Long codigoTipoContrato) {
        this.codigoTipoContrato = codigoTipoContrato;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoTipoContrato
     *            Valor do atributo codigoTipoContrato;
     * @param nomeTipoContrato
     *            Valor do atributo nomeTipoContrato;
     * @param siglaTipoContrato
     *            Valor do atributo siglaTipoContrato;
     * @param percentualAlocavelPadrao
     *            Valor do atributo percentualAlocavelPadrao;
     * @param valorJornadaPadrao
     *            Valor do atributo valorJornadaPadrao;
     * @param indicadorAtivo
     *            Valor do atributo indicadorAtivo;
     * @param pessoas
     *            Valor do atributo pessoas;
     * @param fatorReajustes
     *            Valor do atributo fatorReajustes;
     * @param pessoaTipoContratos
     *            Valor do atributo pessoaTipoContratos;
     */
    public TipoContrato(final Long codigoTipoContrato,
            final String nomeTipoContrato, final String siglaTipoContrato,
            final String indicadorAtivo,
            final BigDecimal percentualAlocavelPadrao,
            final BigDecimal valorJornadaPadrao,
            final Set<Pessoa> pessoas, final Set<FatorReajuste> fatorReajustes,
            final Set<PessoaTipoContrato> pessoaTipoContratos) {
        this.codigoTipoContrato = codigoTipoContrato;
        this.nomeTipoContrato = nomeTipoContrato;
        this.siglaTipoContrato = siglaTipoContrato;
        this.indicadorAtivo = indicadorAtivo;
        this.percentualAlocavelPadrao = percentualAlocavelPadrao;
        this.valorJornadaPadrao = valorJornadaPadrao;
        this.pessoas = pessoas;
        this.fatorReajustes = fatorReajustes;
        this.pessoaTipoContratos = pessoaTipoContratos;
    }

    /**
     * Obtem o valor do atributo codigoTipoContrato.<BR>
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     * 
     * @return Valor do atributo codigoTipoContrato.
     */
    public Long getCodigoTipoContrato() {
        return this.codigoTipoContrato;
    }

    /**
     * Atualiza o valor do atributo codigoTipoContrato.<BR>
     * Atributo gerado a partir da coluna TICO_CD_TIPO_CONTRATO.
     * 
     * @param codigoTipoContrato
     *            Novo valor para o atributo codigoTipoContrato.
     */
    public void setCodigoTipoContrato(final Long codigoTipoContrato) {
        this.codigoTipoContrato = codigoTipoContrato;
    }

    /**
     * Obtem o valor do atributo nomeTipoContrato.<BR>
     * Atributo gerado a partir da coluna TICO_NM_TIPO_CONTRATO.
     * 
     * @return Valor do atributo nomeTipoContrato.
     */
    public String getNomeTipoContrato() {
        return this.nomeTipoContrato;
    }

    /**
     * Atualiza o valor do atributo nomeTipoContrato.<BR>
     * Atributo gerado a partir da coluna TICO_NM_TIPO_CONTRATO.
     * 
     * @param nomeTipoContrato
     *            Novo valor para o atributo nomeTipoContrato.
     */
    public void setNomeTipoContrato(final String nomeTipoContrato) {
        this.nomeTipoContrato = nomeTipoContrato;
    }

    /**
     * Obtem o valor do atributo siglaTipoContrato.<BR>
     * Atributo gerado a partir da coluna TICO_SG_TIPO_CONTRATO.
     * 
     * @return Valor do atributo siglaTipoContrato.
     */
    public String getSiglaTipoContrato() {
        return this.siglaTipoContrato;
    }

    /**
     * Atualiza o valor do atributo siglaTipoContrato.<BR>
     * Atributo gerado a partir da coluna TICO_SG_TIPO_CONTRATO.
     * 
     * @param siglaTipoContrato
     *            Novo valor para o atributo siglaTipoContrato.
     */
    public void setSiglaTipoContrato(final String siglaTipoContrato) {
        this.siglaTipoContrato = siglaTipoContrato;
    }

    /**
     * Obtem o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna TICO_IN_ATIVO.
     * 
     * @return Valor do atributo indicadorAtivo.
     */
    public String getIndicadorAtivo() {
        return this.indicadorAtivo;
    }

    /**
     * Atualiza o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna TICO_IN_ATIVO.
     * 
     * @param indicadorAtivo
     *            Novo valor para o atributo indicadorAtivo.
     */
    public void setIndicadorAtivo(final String indicadorAtivo) {
        this.indicadorAtivo = indicadorAtivo;
    }

    /**
     * Obtem o valor do atributo percentualAlocavelPadrao.<BR>
     * Atributo gerado a partir da coluna TICO_PR_ALOCAVEL_PADRAO.
     * 
     * @return Valor do atributo percentualAlocavelPadrao.
     */
    public BigDecimal getPercentualAlocavelPadrao() {
        return this.percentualAlocavelPadrao;
    }

    /**
     * Atualiza o valor do atributo percentualAlocavelPadrao.<BR>
     * Atributo gerado a partir da coluna TICO_PR_ALOCAVEL_PADRAO.
     * 
     * @param percentualAlocavelPadrao
     *            Novo valor para o atributo percentualAlocavelPadrao.
     */
    public void setPercentualAlocavelPadrao(
            final BigDecimal percentualAlocavelPadrao) {
        this.percentualAlocavelPadrao = percentualAlocavelPadrao;
    }

    /**
     * Obtem o valor do atributo valorJornadaPadrao.<BR>
     * Atributo gerado a partir da coluna TICO_VL_JORNADA_PADRAO.
     * 
     * @return Valor do atributo valorJornadaPadrao.
     */
    public BigDecimal getValorJornadaPadrao() {
        return this.valorJornadaPadrao;
    }

    /**
     * Atualiza o valor do atributo valorJornadaPadrao.<BR>
     * Atributo gerado a partir da coluna TICO_VL_JORNADA_PADRAO.
     * 
     * @param valorJornadaPadrao
     *            Novo valor para o atributo valorJornadaPadrao.
     */
    public void setValorJornadaPadrao(final BigDecimal valorJornadaPadrao) {
        this.valorJornadaPadrao = valorJornadaPadrao;
    }

    /**
     * Obtem o valor do atributo pessoas.<BR>
     * 
     * @return Valor do atributo pessoas.
     */
    public Set<Pessoa> getPessoas() {
        return this.pessoas;
    }

    /**
     * Atualiza o valor do atributo pessoas.<BR>
     * 
     * @param pessoas
     *            Novo valor para o atributo pessoas.
     */
    public void setPessoas(final Set<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }

    /**
     * Obtem o valor do atributo fatorReajustes.<BR>
     * 
     * @return Valor do atributo fatorReajustes.
     */
    public Set<FatorReajuste> getFatorReajustes() {
        return this.fatorReajustes;
    }

    /**
     * Atualiza o valor do atributo fatorReajustes.<BR>
     * 
     * @param fatorReajustes
     *            Novo valor para o atributo fatorReajustes.
     */
    public void setFatorReajustes(final Set<FatorReajuste> fatorReajustes) {
        this.fatorReajustes = fatorReajustes;
    }

    /**
     * Obtem o valor do atributo pessoaTipoContratos.<BR>
     * 
     * @return Valor do atributo pessoaTipoContratos.
     */
    public Set<PessoaTipoContrato> getPessoaTipoContratos() {
        return this.pessoaTipoContratos;
    }

    /**
     * Atualiza o valor do atributo pessoaTipoContratos.<BR>
     * 
     * @param pessoaTipoContratos
     *            Novo valor para o atributo pessoaTipoContratos.
     */
    public void setPessoaTipoContratos(
            final Set<PessoaTipoContrato> pessoaTipoContratos) {
        this.pessoaTipoContratos = pessoaTipoContratos;
    }

    /**
     * @return the moeda
     */
    public Moeda getMoeda() {
        return moeda;
    }

    /**
     * @param moeda
     *            the moeda to set
     */
    public void setMoeda(final Moeda moeda) {
        this.moeda = moeda;
    }

    /**
     * @return the tipoContratoEncargos
     */
    public List<TipoContratoEncargo> getTipoContratoEncargos() {
        return tipoContratoEncargos;
    }

    /**
     * @param tipoContratoEncargos
     *            the tipoContratoEncargos to set
     */
    public void setTipoContratoEncargos(
            final List<TipoContratoEncargo> tipoContratoEncargos) {
        this.tipoContratoEncargos = tipoContratoEncargos;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoTipoContrato").append("='").append(
                getCodigoTipoContrato()).append("' ");
        buffer.append("moeda").append("='").append(getMoeda()).append("' ");
        buffer.append("nomeTipoContrato").append("='").append(
                getNomeTipoContrato()).append("' ");
        buffer.append("siglaTipoContrato").append("='").append(
                getSiglaTipoContrato()).append("' ");
        buffer.append("indicadorAtivo").append("='")
                .append(getIndicadorAtivo()).append("' ");
        buffer.append("percentualAlocavelPadrao").append("='").append(
                getPercentualAlocavelPadrao()).append("' ");
        buffer.append("valorJornadaPadrao").append("='").append(
                getValorJornadaPadrao()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}