/*
 * @(#) TipoOverhead.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela TIPO_OVERHEAD.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 08/01/2010 11:39:27
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "TIPO_OVERHEAD")
@NamedQueries({
    @NamedQuery(name = "TipoOverhead.findAll", query = "SELECT t FROM TipoOverhead t "
        + "ORDER BY t.nomeTipoOverhead ASC "),
    
    @NamedQuery(name = "TipoOverhead.findAllActive", query = "SELECT t FROM TipoOverhead t "
        + "WHERE (t.indicadorAtivo = 'A') "
        + "ORDER BY t.nomeTipoOverhead ASC ")
})
public class TipoOverhead implements java.io.Serializable {
    
    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    
    /**
     * Constante para NamedQuery "TipoOverhead.findAllActive".
     */
    public static final String FIND_ALL_ACTIVE = "TipoOverhead.findAllActive";
    
    // ========================================================================
    // END
    // ========================================================================

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "TipoOverhead.findAll".
     */
    public static final String FIND_ALL = "TipoOverhead.findAll";

    /**
     * Atributo gerado a partir da coluna TIOV_CD_TIPO_OVERHEAD.
     */
    @Id
    @GeneratedValue(generator = "TipoOverheadSeq")
    @SequenceGenerator(name = "TipoOverheadSeq", sequenceName = "SQ_TIOV_CD_TIPO_OVERHEAD", allocationSize = 1)
    @Column(name = "TIOV_CD_TIPO_OVERHEAD", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoTipoOverhead;

    /**
     * Atributo gerado a partir da coluna TIOV_NM_TIPO_OVERHEAD.
     */

    @Column(name = "TIOV_NM_TIPO_OVERHEAD", length = 50)
    private String nomeTipoOverhead;

    /**
     * Atributo gerado a partir da coluna TIOV_IN_ATIVO.
     */

    @Column(name = "TIOV_IN_ATIVO", length = 1)
    private String indicadorAtivo;

    /**
     * Lista de AlocacaoOverhead.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoOverhead")
    private Set<AlocacaoOverhead> alocacaoOverheads = new HashSet<AlocacaoOverhead>(
            0);

    /**
     * Construtor default.
     */
    public TipoOverhead() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoTipoOverhead Valor do atributo codigoTipoOverhead;
     */
    public TipoOverhead(final Long codigoTipoOverhead) {
        this.codigoTipoOverhead = codigoTipoOverhead;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoTipoOverhead Valor do atributo codigoTipoOverhead;
     * @param nomeTipoOverhead Valor do atributo nomeTipoOverhead;
     * @param indicadorAtivo Valor do atributo indicadorAtivo;
     * @param alocacaoOverheads Valor do atributo alocacaoOverheads;
     */
    public TipoOverhead(final Long codigoTipoOverhead, final String nomeTipoOverhead,
            final String indicadorAtivo, final Set<AlocacaoOverhead> alocacaoOverheads) {
        this.codigoTipoOverhead = codigoTipoOverhead;
        this.nomeTipoOverhead = nomeTipoOverhead;
        this.indicadorAtivo = indicadorAtivo;
        this.alocacaoOverheads = alocacaoOverheads;
    }

    /**
     * Obtem o valor do atributo codigoTipoOverhead.<BR>
     * Atributo gerado a partir da coluna TIOV_CD_TIPO_OVERHEAD.
     * @return Valor do atributo codigoTipoOverhead.
     */
    public Long getCodigoTipoOverhead() {
        return this.codigoTipoOverhead;
    }

    /**
     * Atualiza o valor do atributo codigoTipoOverhead.<BR>
     * Atributo gerado a partir da coluna TIOV_CD_TIPO_OVERHEAD.
     * @param codigoTipoOverhead Novo valor para o atributo codigoTipoOverhead.
     */
    public void setCodigoTipoOverhead(final Long codigoTipoOverhead) {
        this.codigoTipoOverhead = codigoTipoOverhead;
    }

    /**
     * Obtem o valor do atributo nomeTipoOverhead.<BR>
     * Atributo gerado a partir da coluna TIOV_NM_TIPO_OVERHEAD.
     * @return Valor do atributo nomeTipoOverhead.
     */
    public String getNomeTipoOverhead() {
        return this.nomeTipoOverhead;
    }

    /**
     * Atualiza o valor do atributo nomeTipoOverhead.<BR>
     * Atributo gerado a partir da coluna TIOV_NM_TIPO_OVERHEAD.
     * @param nomeTipoOverhead Novo valor para o atributo nomeTipoOverhead.
     */
    public void setNomeTipoOverhead(final String nomeTipoOverhead) {
        this.nomeTipoOverhead = nomeTipoOverhead;
    }

    /**
     * Obtem o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna TIOV_IN_ATIVO.
     * @return Valor do atributo indicadorAtivo.
     */
    public String getIndicadorAtivo() {
        return this.indicadorAtivo;
    }

    /**
     * Atualiza o valor do atributo indicadorAtivo.<BR>
     * Atributo gerado a partir da coluna TIOV_IN_ATIVO.
     * @param indicadorAtivo Novo valor para o atributo indicadorAtivo.
     */
    public void setIndicadorAtivo(final String indicadorAtivo) {
        this.indicadorAtivo = indicadorAtivo;
    }

    /**
     * Obtem o valor do atributo alocacaoOverheads.<BR>

     * @return Valor do atributo alocacaoOverheads.
     */
    public Set<AlocacaoOverhead> getAlocacaoOverheads() {
        return this.alocacaoOverheads;
    }

    /**
     * Atualiza o valor do atributo alocacaoOverheads.<BR>

     * @param alocacaoOverheads Novo valor para o atributo alocacaoOverheads.
     */
    public void setAlocacaoOverheads(
            final Set<AlocacaoOverhead> alocacaoOverheads) {
        this.alocacaoOverheads = alocacaoOverheads;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoTipoOverhead").append("='").append(
                getCodigoTipoOverhead()).append("' ");
        buffer.append("nomeTipoOverhead").append("='").append(
                getNomeTipoOverhead()).append("' ");
        buffer.append("indicadorAtivo").append("='")
                .append(getIndicadorAtivo()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
