/*
 * @(#) UploadArquivo.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.google.common.base.Preconditions;

/**
 * Entity gerado a partir da tabela UPLOAD_ARQUIVO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 12/08/2010 10:25:55
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "UPLOAD_ARQUIVO")
@NamedQueries({ @NamedQuery(name = "UploadArquivo.findAll", query = "SELECT t FROM UploadArquivo t") })
public class UploadArquivo implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "UploadArquivo.findAll".
     */
    public static final String FIND_ALL = "UploadArquivo.findAll";

    /**
     * Atributo gerado a partir da coluna UPAR_CD_UPLOAD_ARQUIVO.
     */
    @Id
    @GeneratedValue(generator = "UploadArquivoSeq")
    @SequenceGenerator(name = "UploadArquivoSeq", sequenceName = "SQ_UPAR_CD_UPLOAD_ARQUIVO", allocationSize = 1)
    @Column(name = "UPAR_CD_UPLOAD_ARQUIVO", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoUploadArquivo;

    /**
     * Atributo gerado a partir da coluna UPAR_CD_AUTOR.
     */

    @Column(name = "UPAR_CD_AUTOR", length = 100)
    private String codigoAutor;

    /**
     * Atributo gerado a partir da coluna UPAR_SG_TABELA_ALVO.
     */

    @Column(name = "UPAR_SG_TABELA_ALVO", length = 4)
    private String siglaTabelaAlvo;

    /**
     * Atributo gerado a partir da coluna UPAR_TX_CAMINHO.
     */

    @Column(name = "UPAR_TX_CAMINHO", length = 150)
    private String textoCaminho;

    /**
     * Atributo gerado a partir da coluna UPAR_NM_ARQUIVO.
     */

    @Column(name = "UPAR_NM_ARQUIVO", length = 240)
    private String nomeArquivo;

    /**
     * Atributo gerado a partir da coluna UPAR_TX_EXT_ARQUIVO.
     */

    @Column(name = "UPAR_TX_EXT_ARQUIVO", length = 240)
    private String textoExtArquivo;

    /**
     * Atributo gerado a partir da coluna UPAR_VL_BYTES.
     */

    @Column(name = "UPAR_VL_BYTES", length = 240)
    private String valorBytes;

    /**
     * Atributo gerado a partir da coluna UPAR_TX_ERRO.
     */

    @Column(name = "UPAR_TX_ERRO", length = 240)
    private String textoErro;

    /**
     * Atributo gerado a partir da coluna UPAR_CD_PADRAO_ARQUIVO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PAAR_CD_PADRAO_ARQUIVO")
    private PadraoArquivo padraoArquivo;

    /**
     * Atributo gerado a partir da coluna UPAR_DT_DATA_HORA_UPLOAD.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPAR_DT_DATA_HORA_UPLOAD", length = 7)
    private Date dataDataHoraUpload;

    /**
     * Lista de RegistroAtividade associada.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "uploadArquivo", cascade = CascadeType.ALL)
    private List<RegistroAtividade> registroAtividades = new ArrayList<RegistroAtividade>(
            0);
    

    /**
     * Lista de PessoaBancoHoras associada.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "uploadArquivo", cascade = CascadeType.ALL)
    private List<PessoaBancoHoras> pessoaBancoHoras = new ArrayList<PessoaBancoHoras>(
            0);

    /**
     * Lista de UploadDespesas associada.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "uploadArquivo", cascade = CascadeType.ALL)
    private List<UploadDespesa> uploadDespesas = new ArrayList<UploadDespesa>(0);
    
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "uploadArquivo", cascade = CascadeType.ALL)
	private List<ApropriacaoPlantao> apropriacaoPlantaos = new ArrayList<ApropriacaoPlantao>(
			0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "uploadArquivo", cascade = CascadeType.ALL)
	private List<ApropriacaoHoraExtra> apropriacaoHoraExtras = new ArrayList<ApropriacaoHoraExtra>(
			0);

	@Transient
	private List<String> errors = new ArrayList<String>(0);

    /**
     * Construtor default.
     */
    public UploadArquivo() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoUploadArquivo
     *            Valor do atributo codigoUploadArquivo;
     */
    public UploadArquivo(final Long codigoUploadArquivo) {
        this.codigoUploadArquivo = codigoUploadArquivo;
    }

    /**
     * Obtem o valor do atributo codigoUploadArquivo.<BR>
     * Atributo gerado a partir da coluna UPAR_CD_UPLOAD_ARQUIVO.
     * 
     * @return Valor do atributo codigoUploadArquivo.
     */
    public Long getCodigoUploadArquivo() {
        return this.codigoUploadArquivo;
    }

    /**
     * Atualiza o valor do atributo codigoUploadArquivo.<BR>
     * Atributo gerado a partir da coluna UPAR_CD_UPLOAD_ARQUIVO.
     * 
     * @param codigoUploadArquivo
     *            Novo valor para o atributo codigoUploadArquivo.
     */
    public void setCodigoUploadArquivo(final Long codigoUploadArquivo) {
        this.codigoUploadArquivo = codigoUploadArquivo;
    }

    /**
     * Obtem o valor do atributo codigoAutor.<BR>
     * Atributo gerado a partir da coluna UPAR_CD_AUTOR.
     * 
     * @return Valor do atributo codigoAutor.
     */
    public String getCodigoAutor() {
        return this.codigoAutor;
    }

    /**
     * Atualiza o valor do atributo codigoAutor.<BR>
     * Atributo gerado a partir da coluna UPAR_CD_AUTOR.
     * 
     * @param codigoAutor
     *            Novo valor para o atributo codigoAutor.
     */
    public void setCodigoAutor(final String codigoAutor) {
        this.codigoAutor = codigoAutor;
    }

    /**
     * Obtem o valor do atributo siglaTabelaAlvo.<BR>
     * Atributo gerado a partir da coluna UPAR_SG_TABELA_ALVO.
     * 
     * @return Valor do atributo siglaTabelaAlvo.
     */
    public String getSiglaTabelaAlvo() {
        return this.siglaTabelaAlvo;
    }

    /**
     * Atualiza o valor do atributo siglaTabelaAlvo.<BR>
     * Atributo gerado a partir da coluna UPAR_SG_TABELA_ALVO.
     * 
     * @param siglaTabelaAlvo
     *            Novo valor para o atributo siglaTabelaAlvo.
     */
    public void setSiglaTabelaAlvo(final String siglaTabelaAlvo) {
        this.siglaTabelaAlvo = siglaTabelaAlvo;
    }

    /**
     * Obtem o valor do atributo textoCaminho.<BR>
     * Atributo gerado a partir da coluna UPAR_TX_CAMINHO.
     * 
     * @return Valor do atributo textoCaminho.
     */
    public String getTextoCaminho() {
        return this.textoCaminho;
    }

    /**
     * Atualiza o valor do atributo textoCaminho.<BR>
     * Atributo gerado a partir da coluna UPAR_TX_CAMINHO.
     * 
     * @param textoCaminho
     *            Novo valor para o atributo textoCaminho.
     */
    public void setTextoCaminho(final String textoCaminho) {
        this.textoCaminho = textoCaminho;
    }

    /**
     * Obtem o valor do atributo nomeArquivo.<BR>
     * Atributo gerado a partir da coluna UPAR_NM_ARQUIVO.
     * 
     * @return Valor do atributo nomeArquivo.
     */
    public String getNomeArquivo() {
        return this.nomeArquivo;
    }

    /**
     * Atualiza o valor do atributo nomeArquivo.<BR>
     * Atributo gerado a partir da coluna UPAR_NM_ARQUIVO.
     * 
     * @param nomeArquivo
     *            Novo valor para o atributo nomeArquivo.
     */
    public void setNomeArquivo(final String nomeArquivo) {
        this.nomeArquivo = nomeArquivo;
    }

    /**
     * Obtem o valor do atributo textoExtArquivo.<BR>
     * Atributo gerado a partir da coluna UPAR_TX_EXT_ARQUIVO.
     * 
     * @return Valor do atributo textoExtArquivo.
     */
    public String getTextoExtArquivo() {
        return this.textoExtArquivo;
    }

    /**
     * Atualiza o valor do atributo textoExtArquivo.<BR>
     * Atributo gerado a partir da coluna UPAR_TX_EXT_ARQUIVO.
     * 
     * @param textoExtArquivo
     *            Novo valor para o atributo textoExtArquivo.
     */
    public void setTextoExtArquivo(final String textoExtArquivo) {
        this.textoExtArquivo = textoExtArquivo;
    }

    /**
     * Obtem o valor do atributo valorBytes.<BR>
     * Atributo gerado a partir da coluna UPAR_VL_BYTES.
     * 
     * @return Valor do atributo valorBytes.
     */
    public String getValorBytes() {
        return this.valorBytes;
    }

    /**
     * Atualiza o valor do atributo valorBytes.<BR>
     * Atributo gerado a partir da coluna UPAR_VL_BYTES.
     * 
     * @param valorBytes
     *            Novo valor para o atributo valorBytes.
     */
    public void setValorBytes(final String valorBytes) {
        this.valorBytes = valorBytes;
    }

    /**
     * Obtem o valor do atributo textoErro.<BR>
     * Atributo gerado a partir da coluna UPAR_TX_ERRO.
     * 
     * @return Valor do atributo textoErro.
     */
    public String getTextoErro() {
        return this.textoErro;
    }

    /**
     * Atualiza o valor do atributo textoErro.<BR>
     * Atributo gerado a partir da coluna UPAR_TX_ERRO.
     * 
     * @param textoErro
     *            Novo valor para o atributo textoErro.
     */
    public void setTextoErro(final String textoErro) {
        this.textoErro = textoErro;
    }

    /**
     * Obtem o valor do atributo dataDataHoraUpload.<BR>
     * Atributo gerado a partir da coluna UPAR_DT_DATA_HORA_UPLOAD.
     * 
     * @return Valor do atributo dataDataHoraUpload.
     */
    public Date getDataDataHoraUpload() {
        return this.dataDataHoraUpload;
    }

    /**
     * Atualiza o valor do atributo dataDataHoraUpload.<BR>
     * Atributo gerado a partir da coluna UPAR_DT_DATA_HORA_UPLOAD.
     * 
     * @param dataDataHoraUpload
     *            Novo valor para o atributo dataDataHoraUpload.
     */
    public void setDataDataHoraUpload(final Date dataDataHoraUpload) {
        this.dataDataHoraUpload = dataDataHoraUpload;
    }

    /**
     * Obtem o valor do atributo registroAtividades.<BR>
     * 
     * @return Valor do atributo registroAtividades.
     */
    public List<RegistroAtividade> getRegistroAtividades() {
        return this.registroAtividades;
    }

    /**
     * Atualiza o valor do atributo registroAtividades.<BR>
     * 
     * @param registroAtividades
     *            Novo valor para o atributo registroAtividades.
     */
    public void setRegistroAtividades(
            final List<RegistroAtividade> registroAtividades) {
        this.registroAtividades = registroAtividades;
    }

    /**
     * Obtem o valor do atributo pessoaBancoHoras.<BR>
     * 
     * @return Valor do atributo pessoaBancoHoras.
     */
    public List<PessoaBancoHoras> getPessoaBancoHoras() {
        return this.pessoaBancoHoras;
    }

    /**
     * Atualiza o valor do atributo pessoaBancoHoras.<BR>
     * 
     * @param pessoaBancoHoras
     *            Novo valor para o atributo pessoaBancoHoras.
     */
    public void setPessoaBancoHoras(
            final List<PessoaBancoHoras> pessoaBancoHoras) {
        this.pessoaBancoHoras = pessoaBancoHoras;
    }

    /**
     * @return the uploadDespesas
     */
    public List<UploadDespesa> getUploadDespesas() {
        return uploadDespesas;
    }

    /**
     * @param uploadDespesas
     *            the uploadDespesas to set
     */
    public void setUploadDespesas(final List<UploadDespesa> uploadDespesas) {
        this.uploadDespesas = uploadDespesas;
    }

    /**
	 * Obtem o valor do atributo apropriacaoPlantaos.<BR>
	 * 
	 * @return Valor do atributo apropriacaoPlantaos.
	 */
	public List<ApropriacaoPlantao> getApropriacaoPlantaos() {
		return this.apropriacaoPlantaos;
	}

	/**
	 * Atualiza o valor do atributo apropriacaoPlantaos.<BR>
	 * 
	 * @param apropriacaoPlantaos
	 *            Novo valor para o atributo apropriacaoPlantaos.
	 */
	public void setApropriacaoPlantaos(
			List<ApropriacaoPlantao> apropriacaoPlantaos) {
		this.apropriacaoPlantaos = apropriacaoPlantaos;
	}

	/**
	 * Obtem o valor do atributo apropriacaoHoraExtras.<BR>
	 * 
	 * @return Valor do atributo apropriacaoHoraExtras.
	 */
	public List<ApropriacaoHoraExtra> getApropriacaoHoraExtras() {
		return this.apropriacaoHoraExtras;
	}

	/**
	 * Atualiza o valor do atributo apropriacaoHoraExtras.<BR>
	 * 
	 * @param apropriacaoHoraExtras
	 *            Novo valor para o atributo apropriacaoHoraExtras.
	 */
	public void setApropriacaoHoraExtras(
			List<ApropriacaoHoraExtra> apropriacaoHoraExtras) {
		this.apropriacaoHoraExtras = apropriacaoHoraExtras;
	}

	/**
     * @see Object#toString()
     * @return representação String do Objeto
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoUploadArquivo").append("='")
				.append(getCodigoUploadArquivo()).append("' ");
        buffer.append("codigoAutor").append("='").append(getCodigoAutor())
                .append("' ");
		buffer.append("siglaTabelaAlvo").append("='")
				.append(getSiglaTabelaAlvo()).append("' ");
        buffer.append("textoCaminho").append("='").append(getTextoCaminho())
                .append("' ");
        buffer.append("nomeArquivo").append("='").append(getNomeArquivo())
                .append("' ");
		buffer.append("textoExtArquivo").append("='")
				.append(getTextoExtArquivo()).append("' ");
        buffer.append("valorBytes").append("='").append(getValorBytes())
                .append("' ");
		buffer.append("textoErro").append("='").append(getTextoErro())
				.append("' ");
		buffer.append("dataDataHoraUpload").append("='")
				.append(getDataDataHoraUpload()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    /**
     * @param padraoArquivo
     *            the padraoArquivo to set
     */
    public void setPadraoArquivo(final PadraoArquivo padraoArquivo) {
        this.padraoArquivo = padraoArquivo;
    }

    /**
     * @return the padraoArquivo
     */
    public PadraoArquivo getPadraoArquivo() {
        return padraoArquivo;
    }

	/**
	 * Adiciona um item na lista de {@link ApropriacaoHoraExtra}.
	 * 
	 * @param apropriacaoHoraExtra
	 *            {@link ApropriacaoHoraExtra}
	 * @return lista de {@link ApropriacaoHoraExtra}
	 */
	public List<ApropriacaoHoraExtra> addApropriacaoHorasExtras(
			final ApropriacaoHoraExtra apropriacaoHoraExtra) {
		Preconditions.checkNotNull(apropriacaoHoraExtra);
		this.apropriacaoHoraExtras.add(apropriacaoHoraExtra);
		return this.apropriacaoHoraExtras;
	}

	/**
	 * Adiciona um item na lista de {@link ApropriacaoPlantao}.
	 * 
	 * @param apropriacaoPlantao
	 *            {@link ApropriacaoPlantao}
	 * @return lista de {@link ApropriacaoPlantao}
	 */
	public List<ApropriacaoPlantao> addApropriacaoPlantaos(
			final ApropriacaoPlantao apropriacaoPlantao) {
		Preconditions.checkNotNull(apropriacaoPlantao);
		this.apropriacaoPlantaos.add(apropriacaoPlantao);
		return this.apropriacaoPlantaos;
	}

	/**
	 * Adiciona um item na lisda de erros do {@link UploadArquivo}
	 * 
	 * @param erro
	 *            {@link String}
	 * @return lista de erros
	 */
	public List<String> addErrors(final String error) {
		this.errors.add(error);
		return this.errors;
	}

	/**
	 * @return the errors
	 */
	public List<String> getErrors() {
		return errors;
	}

	/**
	 * Obtem os erros do arquivo como String. Obs: Salta uma linha a cada item
	 * de erro.
	 * 
	 * @return String
	 */
	public String getErrorsAsString() {
		StringBuilder text = new StringBuilder();
		for (String error : errors) {
			text.append(error + "\n");
		}
		return text.toString();
	}

}