/*
 * @(#) UploadDespesa.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.jsefa.csv.annotation.CsvDataType;
import org.jsefa.csv.annotation.CsvField;

import com.ciandt.pms.csv.util.CsvBigDecimalConverter;
import com.ciandt.pms.csv.util.CsvDateConverter;


/**
 * Entity gerado a partir da tabela UPLOAD_DESPESA.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 29/06/2011 12:47:58
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "UPLOAD_DESPESA")
@NamedQueries({
        @NamedQuery(name = "UploadDespesa.findAll", query = "SELECT t FROM UploadDespesa t"),
        @NamedQuery(name = "UploadDespesa.findByDataMes", query = "SELECT t FROM UploadDespesa t "
                + "WHERE (TRUNC(t.dataLancamento) = TRUNC(?)) "),
        @NamedQuery(name = "UploadDespesa.findByDataMesAndEmpresa", query = "SELECT t FROM UploadDespesa t "
                + "WHERE (TRUNC(t.dataLancamento) = TRUNC(?)) "
                + " AND t.empresa.codigoEmpresa = ? "),
        @NamedQuery(name = "UploadDespesa.findByFilter", query = "SELECT t FROM UploadDespesa t "
                + "JOIN FETCH t.empresa empresa "
                + "JOIN FETCH t.grupoCusto grupoCusto "
                + "JOIN FETCH t.tipoDespesa tipoDespesa "
                + "JOIN FETCH t.moeda moeda "
                + "WHERE (empresa.codigoEmpresa = ? OR ? = 0L) "
                + "  AND (grupoCusto.codigoGrupoCusto = ? OR ? = 0L ) "
                + "  AND (tipoDespesa.codigoTipoDespesa = ? OR ? = 0L) "
                + "  AND (TRUNC(t.dataLancamento) >= TRUNC(?)) "
                + "  AND (TRUNC(t.dataLancamento) <= TRUNC(?)) "
                + "  AND (UPPER(t.textoGrupoDespesa) like '%'||TRIM(UPPER(?))||'%' "
                + "  OR UPPER(t.textoTipoDespesa) like '%'||TRIM(UPPER(?))||'%' ) "
                + "  ORDER BY t.dataLancamento ASC")})
@CsvDataType
public class UploadDespesa implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "UploadDespesa.findAll".
     */
    public static final String FIND_ALL = "UploadDespesa.findAll";

    /**
     * Constante para NamedQuery "UploadDespesa.findByDataMes".
     */
    public static final String FIND_BY_DATA_MES = "UploadDespesa.findByDataMes";

    /**
     * Constante para NamedQuery "UploadDespesa.findByDataMesAndEmpresa".
     */
    public static final String FIND_BY_DATA_MES_AND_EMPRESA =
            "UploadDespesa.findByDataMesAndEmpresa";

    /**
     * Constante para NamedQuery "UploadDespesa.findByFilter".
     */
    public static final String FIND_BY_FILTER = "UploadDespesa.findByFilter";

    /**
     * Atributo gerado a partir da coluna UPDE_CD_UPLOAD_DESPESA.
     */
    @Id
    @GeneratedValue(generator = "UploadDespesaSeq")
    @SequenceGenerator(name = "UploadDespesaSeq", sequenceName = "SQ_UPDE_CD_UPLOAD_DESPESA", allocationSize = 1)
    @Column(name = "UPDE_CD_UPLOAD_DESPESA", unique = true, nullable = false, precision = 18, scale = 0)
    private Long codigoUploadDespesa;

    /**
     * Contador.
     */
    @Transient
    private int count;

    /**
     * Indica se o grupoCusto sera editado.
     */
    @Transient
    private Boolean editGrupoCusto;
    
    /**
     * Indica se o contratoPratica sera editado.
     */
    @Transient
    private Boolean editContratoPratica;

    /**
     * Indica se o tipoDespesa sera editado.
     */
    @Transient
    private Boolean editTipoDespesa;

    /**
     * Indica se a moeda sera editada.
     */
    @Transient
    private Boolean editMoeda;

    /**
     * Indica se a linha de UploadDespesa esta selecionada
     */
    @Transient
    private Boolean isSelected = false;

    /**
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MOED_CD_MOEDA")
    private Moeda moeda;

    /**
     * Atributo gerado a partir da coluna GRCU_CD_GRUPO_CUSTO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GRCU_CD_GRUPO_CUSTO")
    private GrupoCusto grupoCusto;

    /**
     * Atributo gerado a partir da coluna EMPR_CD_EMPRESA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EMPR_CD_EMPRESA")
    private Empresa empresa;

    /**
     * Atributo gerado a partir da coluna TIDE_CD_TIPO_DESPESA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TIDE_CD_TIPO_DESPESA")
    private TipoDespesa tipoDespesa;
    
    /**
     * Atributo que indica se uma linha deve ser importada ou nao.
     */
    @Transient
    @CsvField(pos = 0, required = true)
    private String id;

    /**
     * Atributo que indica se uma linha deve ser importada ou nao.
     */
    @Transient
    @CsvField(pos = 1, required = true)
    private String importRow;

    /**
     * Atributo obtencao do grupoCusto.
     */
    @Transient
    @CsvField(pos = 2)
    private String siglaGrupoCusto;
    
    /**
     * Atributo para obtencao do Nome do Contrato Pratica.
     */
    @Transient
    @CsvField(pos = 3)
    private String nomeContratoPratica;

    /**
     * Atributo para obtencao do tipoDespesa.
     */
    @Transient
    @CsvField(pos = 4)
    private String nomeTipoDespesa;

    /**
     * Atributo gerado a partir da coluna UPDE_TX_GRUPO_DESPESA.
     */
    @Column(name = "UPDE_TX_GRUPO_DESPESA", length = 500)
    @CsvField(pos = 5)
    private String textoGrupoDespesa;

    /**
     * Atributo gerado a partir da coluna UPDE_TX_TIPO_DESPESA.
     */

    @Column(name = "UPDE_TX_TIPO_DESPESA", length = 500)
    @CsvField(pos = 6)
    private String textoTipoDespesa;

    /**
     * Atributo gerado a partir da coluna UPDE_DT_LANCAMENTO.
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "UPDE_DT_LANCAMENTO", length = 7)
    @CsvField(pos = 7, required = true, converterType = CsvDateConverter.class)
    private Date dataLancamento;

    /**
     * Atributo gerado a partir da coluna UPDE_VL_DESPESA.
     */
    @Column(name = "UPDE_VL_DESPESA", precision = 22, scale = 0)
    @CsvField(pos = 8, required = true, converterType = CsvBigDecimalConverter.class)
    private BigDecimal valorDespesa;
    
    /**
     * Atributo para obtencao da moeda.
     */
    @Transient
    @CsvField(pos = 9)
    private String siglaMoeda;

    /**
     * Atributo gerado a partir da coluna UPAR_CD_UPLOAD_ARQUIVO.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UPAR_CD_UPLOAD_ARQUIVO")
    private UploadArquivo uploadArquivo;

    /**
     * Atributo gerado a partir da coluna UPDE_IN_ORIGEM.
     */

    @Column(name = "UPDE_IN_ORIGEM", length = 100)
    private String indicadorOrigem;

    /**
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COPR_CD_CONTRATO_PRATICA")
    private ContratoPratica contratoPratica;

    /**
     * Construtor default.
     */
    public UploadDespesa() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoUploadDespesa
     *            Valor do atributo codigoUploadDespesa;
     */
    public UploadDespesa(final Long codigoUploadDespesa) {
        this.codigoUploadDespesa = codigoUploadDespesa;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoUploadDespesa
     *            Valor do atributo codigoUploadDespesa;
     * @param moeda
     *            Valor do atributo moeda;
     * @param grupoCusto
     *            Valor do atributo grupoCusto;
     * @param empresa
     *            Valor do atributo empresa;
     * @param tipoDespesa
     *            Valor do atributo tipoDespesa;
     * @param textoGrupoDespesa
     *            Valor do atributo textoGrupoDespesa;
     * @param textoTipoDespesa
     *            Valor do atributo textoTipoDespesa;
     * @param dataLancamento
     *            Valor do atributo dataLancamento;
     * @param valorDespesa
     *            Valor do atributo valorDespesa;
     */
    public UploadDespesa(final Long codigoUploadDespesa, final Moeda moeda,
            final GrupoCusto grupoCusto, final Empresa empresa,
            final TipoDespesa tipoDespesa, final String textoGrupoDespesa,
            final String textoTipoDespesa, final Date dataLancamento,
            final BigDecimal valorDespesa) {
        this.codigoUploadDespesa = codigoUploadDespesa;
        this.moeda = moeda;
        this.grupoCusto = grupoCusto;
        this.empresa = empresa;
        this.tipoDespesa = tipoDespesa;
        this.textoGrupoDespesa = textoGrupoDespesa;
        this.textoTipoDespesa = textoTipoDespesa;
        this.dataLancamento = dataLancamento;
        this.valorDespesa = valorDespesa;
    }

    /**
     * Obtem o valor do atributo codigoUploadDespesa.<BR>
     * Atributo gerado a partir da coluna UPDE_CD_UPLOAD_DESPESA.
     * 
     * @return Valor do atributo codigoUploadDespesa.
     */
    public Long getCodigoUploadDespesa() {
        return this.codigoUploadDespesa;
    }

    /**
     * Atualiza o valor do atributo codigoUploadDespesa.<BR>
     * Atributo gerado a partir da coluna UPDE_CD_UPLOAD_DESPESA.
     * 
     * @param codigoUploadDespesa
     *            Novo valor para o atributo codigoUploadDespesa.
     */
    public void setCodigoUploadDespesa(final Long codigoUploadDespesa) {
        this.codigoUploadDespesa = codigoUploadDespesa;
    }

    /**
     * Obtem o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * 
     * @return Valor do atributo moeda.
     */
    public Moeda getMoeda() {
        return this.moeda;
    }

    /**
     * Atualiza o valor do atributo moeda.<BR>
     * Atributo gerado a partir da coluna MOED_CD_MOEDA.
     * 
     * @param moeda
     *            Novo valor para o atributo moeda.
     */
    public void setMoeda(final Moeda moeda) {
        this.moeda = moeda;
    }

    /**
     * Obtem o valor do atributo grupoCusto.<BR>
     * Atributo gerado a partir da coluna GRCU_CD_GRUPO_CUSTO.
     * 
     * @return Valor do atributo grupoCusto.
     */
    public GrupoCusto getGrupoCusto() {
        return this.grupoCusto;
    }

    /**
     * Atualiza o valor do atributo grupoCusto.<BR>
     * Atributo gerado a partir da coluna GRCU_CD_GRUPO_CUSTO.
     * 
     * @param grupoCusto
     *            Novo valor para o atributo grupoCusto.
     */
    public void setGrupoCusto(final GrupoCusto grupoCusto) {
        this.grupoCusto = grupoCusto;
    }

    /**
     * Obtem o valor do atributo empresa.<BR>
     * Atributo gerado a partir da coluna EMPR_CD_EMPRESA.
     * 
     * @return Valor do atributo empresa.
     */
    public Empresa getEmpresa() {
        return this.empresa;
    }

    /**
     * Atualiza o valor do atributo empresa.<BR>
     * Atributo gerado a partir da coluna EMPR_CD_EMPRESA.
     * 
     * @param empresa
     *            Novo valor para o atributo empresa.
     */
    public void setEmpresa(final Empresa empresa) {
        this.empresa = empresa;
    }

    /**
     * Obtem o valor do atributo tipoDespesa.<BR>
     * Atributo gerado a partir da coluna TIDE_CD_TIPO_DESPESA.
     * 
     * @return Valor do atributo tipoDespesa.
     */
    public TipoDespesa getTipoDespesa() {
        return this.tipoDespesa;
    }

    /**
     * Atualiza o valor do atributo tipoDespesa.<BR>
     * Atributo gerado a partir da coluna TIDE_CD_TIPO_DESPESA.
     * 
     * @param tipoDespesa
     *            Novo valor para o atributo tipoDespesa.
     */
    public void setTipoDespesa(final TipoDespesa tipoDespesa) {
        this.tipoDespesa = tipoDespesa;
    }

    /**
     * Obtem o valor do atributo textoGrupoDespesa.<BR>
     * Atributo gerado a partir da coluna UPDE_TX_GRUPO_DESPESA.
     * 
     * @return Valor do atributo textoGrupoDespesa.
     */
    public String getTextoGrupoDespesa() {
        return this.textoGrupoDespesa;
    }

    /**
     * Atualiza o valor do atributo textoGrupoDespesa.<BR>
     * Atributo gerado a partir da coluna UPDE_TX_GRUPO_DESPESA.
     * 
     * @param textoGrupoDespesa
     *            Novo valor para o atributo textoGrupoDespesa.
     */
    public void setTextoGrupoDespesa(final String textoGrupoDespesa) {
        this.textoGrupoDespesa = textoGrupoDespesa;
    }

    /**
     * Obtem o valor do atributo textoTipoDespesa.<BR>
     * Atributo gerado a partir da coluna UPDE_TX_TIPO_DESPESA.
     * 
     * @return Valor do atributo textoTipoDespesa.
     */
    public String getTextoTipoDespesa() {
        return this.textoTipoDespesa;
    }

    /**
     * Atualiza o valor do atributo textoTipoDespesa.<BR>
     * Atributo gerado a partir da coluna UPDE_TX_TIPO_DESPESA.
     * 
     * @param textoTipoDespesa
     *            Novo valor para o atributo textoTipoDespesa.
     */
    public void setTextoTipoDespesa(final String textoTipoDespesa) {
        this.textoTipoDespesa = textoTipoDespesa;
    }

    /**
     * Obtem o valor do atributo dataLancamento.<BR>
     * Atributo gerado a partir da coluna UPDE_DT_LANCAMENTO.
     * 
     * @return Valor do atributo dataLancamento.
     */
    public Date getDataLancamento() {
        return this.dataLancamento;
    }

    /**
     * Atualiza o valor do atributo dataLancamento.<BR>
     * Atributo gerado a partir da coluna UPDE_DT_LANCAMENTO.
     * 
     * @param dataLancamento
     *            Novo valor para o atributo dataLancamento.
     */
    public void setDataLancamento(final Date dataLancamento) {
        this.dataLancamento = dataLancamento;
    }

    /**
     * Obtem o valor do atributo valorDespesa.<BR>
     * Atributo gerado a partir da coluna UPDE_VL_DESPESA.
     * 
     * @return Valor do atributo valorDespesa.
     */
    public BigDecimal getValorDespesa() {
        return this.valorDespesa;
    }

    /**
     * Atualiza o valor do atributo valorDespesa.<BR>
     * Atributo gerado a partir da coluna UPDE_VL_DESPESA.
     * 
     * @param valorDespesa
     *            Novo valor para o atributo valorDespesa.
     */
    public void setValorDespesa(final BigDecimal valorDespesa) {
        this.valorDespesa = valorDespesa;
    }

    /**
     * @return the uploadArquivo
     */
    public UploadArquivo getUploadArquivo() {
        return uploadArquivo;
    }

    /**
     * @param uploadArquivo
     *            the uploadArquivo to set
     */
    public void setUploadArquivo(final UploadArquivo uploadArquivo) {
        this.uploadArquivo = uploadArquivo;
    }

    /**
     * @return the importRow
     */
    public String getImportRow() {
        return importRow;
    }

    /**
     * @param importRow
     *            the importRow to set
     */
    public void setImportRow(final String importRow) {
        this.importRow = importRow;
    }

    /**
     * @return the nomeTipoDespesa
     */
    public String getNomeTipoDespesa() {
        return nomeTipoDespesa;
    }

    /**
     * @param nomeTipoDespesa
     *            the nomeTipoDespesa to set
     */
    public void setNomeTipoDespesa(final String nomeTipoDespesa) {
        this.nomeTipoDespesa = nomeTipoDespesa;
    }

    /**
     * @return the siglaMoeda
     */
    public String getSiglaMoeda() {
        return siglaMoeda;
    }

    /**
     * @param siglaMoeda
     *            the siglaMoeda to set
     */
    public void setSiglaMoeda(final String siglaMoeda) {
        this.siglaMoeda = siglaMoeda;
    }

    /**
     * @return the siglaGrupoCusto
     */
    public String getSiglaGrupoCusto() {
        return siglaGrupoCusto;
    }

    /**
     * @param siglaGrupoCusto
     *            the siglaGrupoCusto to set
     */
    public void setSiglaGrupoCusto(final String siglaGrupoCusto) {
        this.siglaGrupoCusto = siglaGrupoCusto;
    }

    /**
     * @return the id
     */
    public String getId() {
        return id;
    }

    /**
     * @param id
     *            the id to set
     */
    public void setId(final String id) {
        this.id = id;
    }

    /**
     * @return the count
     */
    public int getCount() {
        return count;
    }

    /**
     * @param count
     *            the count to set
     */
    public void setCount(final int count) {
        this.count = count;
    }

    /**
     * @return the editGrupoCusto
     */
    public Boolean getEditGrupoCusto() {
        return editGrupoCusto;
    }

    /**
     * @param editGrupoCusto
     *            the editGrupoCusto to set
     */
    public void setEditGrupoCusto(final Boolean editGrupoCusto) {
        this.editGrupoCusto = editGrupoCusto;
    }

    /**
	 * @return the editContratoPratica
	 */
	public Boolean getEditContratoPratica() {
		return editContratoPratica;
	}

	/**
	 * @param editContratoPratica the editContratoPratica to set
	 */
	public void setEditContratoPratica(Boolean editContratoPratica) {
		this.editContratoPratica = editContratoPratica;
	}

	/**
     * @return the editTipoDespesa
     */
    public Boolean getEditTipoDespesa() {
        return editTipoDespesa;
    }

    /**
     * @param editTipoDespesa
     *            the editTipoDespesa to set
     */
    public void setEditTipoDespesa(final Boolean editTipoDespesa) {
        this.editTipoDespesa = editTipoDespesa;
    }

    /**
     * @return the editMoeda
     */
    public Boolean getEditMoeda() {
        return editMoeda;
    }

    /**
     * @param editMoeda
     *            the editMoeda to set
     */
    public void setEditMoeda(final Boolean editMoeda) {
        this.editMoeda = editMoeda;
    }

    /**
     * @return the indicadorOrigem
     */
    public String getIndicadorOrigem() {
        return indicadorOrigem;
    }

    /**
     * @param indicadorOrigem
     *            the indicadorOrigem to set
     */
    public void setIndicadorOrigem(final String indicadorOrigem) {
        this.indicadorOrigem = indicadorOrigem;
    }

    /**
     * @return the isSelected
     */
    public Boolean getIsSelected() {
        return isSelected;
    }

    /**
     * @param isSelected
     *            the isSelected to set
     */
    public void setIsSelected(final Boolean isSelected) {
        this.isSelected = isSelected;
    }

    public ContratoPratica getContratoPratica() {
		return contratoPratica;
	}

	public void setContratoPratica(ContratoPratica contratoPratica) {
		this.contratoPratica = contratoPratica;
	}

	public String getNomeContratoPratica() {
		return nomeContratoPratica;
	}

	public void setNomeContratoPratica(String nomeContratoPratica) {
		this.nomeContratoPratica = nomeContratoPratica;
	}

	/**
     * @see Object#toString().
     * @return string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("codigoUploadDespesa").append("='").append(
                getCodigoUploadDespesa()).append("' ");
        buffer.append("moeda").append("='").append(getMoeda()).append("' ");
        buffer.append("grupoCusto").append("='").append(getGrupoCusto())
                .append("' ");
        buffer.append("empresa").append("='").append(getEmpresa()).append("' ");
        buffer.append("tipoDespesa").append("='").append(getTipoDespesa())
                .append("' ");
        buffer.append("textoGrupoDespesa").append("='").append(
                getTextoGrupoDespesa()).append("' ");
        buffer.append("textoTipoDespesa").append("='").append(
                getTextoTipoDespesa()).append("' ");
        buffer.append("dataLancamento").append("='")
                .append(getDataLancamento()).append("' ");
        buffer.append("valorDespesa").append("='").append(getValorDespesa())
                .append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
