/*
 * @(#) Voucher.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import com.ciandt.pms.Constants;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Entity gerado a partir da tabela VOUCHER.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 05/09/2012 08:45:33
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VOUCHER")
@NamedQueries({
		@NamedQuery(name = "Voucher.findAll", query = "SELECT t FROM Voucher t"),
		@NamedQuery(name = "Voucher.findByOrcDesp", query = "SELECT t FROM Voucher t "
				+ "WHERE t.codigoOrcDespesa = ?"),
		@NamedQuery(name = "Voucher.findAllNotEmailSend", query = "SELECT t FROM Voucher t "
				+ "WHERE t.indicadorEmailSent = 'N'"
				+ " ORDER BY t.dataUpdate "),
		@NamedQuery(name = "Voucher.findByNumberVoucher", query = "SELECT t FROM Voucher t "
				+ "WHERE t.numeroVoucher = ? "),
		@NamedQuery(name = "Voucher.findOpenVoucherByPessoaAndDate", query = "SELECT v FROM Voucher v "
				+ "JOIN v.pessoa vp "
				+ "WHERE v.indicadorStatus = '"
				+ Constants.STATUS_VOUCHER_OPEN
				+ "' "
				+ "AND v.dataCreation < :dataCreation "
				+ "AND vp.codigoPessoa = :codigoPessoa"),
		@NamedQuery(name = "Voucher.findOpenVoucherByOrcDespAndDate", query = "SELECT v FROM Voucher v"
				+ " WHERE v.indicadorStatus = '"
				+ Constants.STATUS_VOUCHER_OPEN
				+ "'"
				+ " AND v.dataCreation < :dataCreation"
				+ " AND v.orcamentoDespesa = :orcamentoDespesa") })
public class Voucher implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "Voucher.findAll".
	 */
	public static final String FIND_ALL = "Voucher.findAll";

	/**
	 * Constante para NamedQuery "Voucher.findByOrcDesp".
	 */
	public static final String FIND_BY_ORC_DESP = "Voucher.findByOrcDesp";

	/**
	 * Constante para NamedQuery "Voucher.findAllNotEmailSend".
	 */
	public static final String FIND_ALL_NOT_EMAIL_SENT = "Voucher.findAllNotEmailSend";

	/**
	 * Constante para NamedQuery "Voucher.findByNumberVoucher".
	 */
	public static final String FIND_BY_NUMBER_VOUCHER = "Voucher.findByNumberVoucher";

	/**
	 * Constante para NamedQuery "Voucher.findOpenVoucherNewerThanDate".
	 */
	public static final String FIND_OPEN_VOUCHER_BY_PESSOA_AND_DATE = "Voucher.findOpenVoucherByPessoaAndDate";

	/**
	 * Constante para NamedQuery "Voucher.findOpenVoucherByOrcDespAndDate".
	 */
	public static final String FIND_OPEN_VOUCHER_BY_ORC_DESP_AND_DATE = "Voucher.findOpenVoucherByOrcDespAndDate";

	/**
	 * Atributo gerado a partir da coluna VOUC_CD_VOUCHER.
	 */
	@Id
	@GeneratedValue(generator = "VoucherSeq")
	@SequenceGenerator(name = "VoucherSeq", sequenceName = "SQ_VOUC_CD_VOUCHER", allocationSize = 1)
	@Column(name = "VOUC_CD_VOUCHER", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoVoucher;

	/**
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PESS_CD_PESSOA", nullable = false)
	private Pessoa pessoa;

	/**
	 * Atributo gerado a partir da coluna VOUC_NR_VOUCHER.
	 */

	@Column(name = "VOUC_NR_VOUCHER", length = 20)
	private String numeroVoucher;

	/**
	 * Atributo gerado a partir da coluna ORDE_CD_ORC_DESPESA.
	 */

	@Column(name = "ORDE_CD_ORCA_DESPESA", nullable = false, precision = 18, scale = 0)
	private Long codigoOrcDespesa;

	/**
	 * Atributo gerado a partir da coluna ORDE_CD_ORCA_DESPESA.
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ORDE_CD_ORCA_DESPESA", insertable = false, updatable = false)
	private OrcamentoDespesa orcamentoDespesa;

	/**
	 * Atributo gerado a partir da coluna VOUC_IN_STATUS.
	 */

	@Column(name = "VOUC_IN_STATUS", length = 2)
	private String indicadorStatus;

	/**
	 * Atributo gerado a partir da coluna VOUC_VL_USED.
	 */

	@Column(name = "VOUC_VL_USED", precision = 22, scale = 0)
	private BigDecimal valorUsed;

	/**
	 * Atributo gerado a partir da coluna VOUC_VL_CLOSED.
	 */

	@Column(name = "VOUC_VL_CLOSED", precision = 22, scale = 0)
	private BigDecimal valorClosed;

	/**
	 * Atributo gerado a partir da coluna VOUC_IN_RED_FLAG.
	 */

	@Column(name = "VOUC_IN_RED_FLAG", length = 1)
	private String indicadorRedFlag;

	/**
	 * Atributo gerado a partir da coluna VOUC_DT_CREATION.
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VOUC_DT_CREATION", length = 7)
	private Date dataCreation;

	/**
	 * Atributo gerado a partir da coluna VOUC_DT_UPDATE.
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VOUC_DT_UPDATE", length = 7)
	private Date dataUpdate;

	/**
	 * Atributo gerado a partir da coluna VOUC_VL_ISSUED.
	 */

	@Column(name = "VOUC_VL_ISSUED", precision = 22, scale = 0)
	private BigDecimal valorIssued;

	/**
	 * Atributo gerado a partir da coluna VOUC_IN_EMAIL_SENT.
	 */

	@Column(name = "VOUC_IN_EMAIL_SENT", length = 1)
	private String indicadorEmailSent;

	/**
	 * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
	 */

	@Column(name = "COPR_CD_CONTRATO_PRATICA", precision = 18, scale = 0)
	private Long codigoContratoPratica;

	/**
	 * Atributo gerado a partir da coluna VOUC_CD_VOUCHER_GAE.
	 */

	@Column(name = "VOUC_CD_VOUCHER_GAE", precision = 18, scale = 0)
	private Long codigoVoucherGae;

	/**
	 * Atributo gerado a partir da coluna VOUC_IN_SYNC.
	 */

	@Column(name = "VOUC_IN_SYNC", length = 1)
	private String indicadorSync;

	/**
	 * Atributo gerado a partir da coluna VOUC_SG_FONTE_UPDATE.
	 */
	@Column(name = "VOUC_SG_FONTE_UPDATE", length = 2)
	private String acronymSourceUpdate = "";

	/**
	 * Atributo gerado a partir da coluna VOUC_CD_AUTOR_UPDATE.
	 */
	@Column(name = "VOUC_CD_AUTOR_UPDATE", length = 50)
	private String codeAuthorUpdate;

	/**
	 * Atributo gerado a partir da coluna GRPO_CD_GRUPO_CUSTO.
	 */
	@Column(name = "GRCU_CD_GRUPO_CUSTO", precision = 18, scale = 0)
	private Long codigoGrupoCusto;

	/**
	 * Atributo gerado a partir da coluna MOED_CD_MOEDA.
	 */
	@Column(name = "MOED_SG_MOEDA")
	private String siglaMoeda;

	/**
	 * Atributo gerado a partir da coluna VOUC_VL_ISSUED_TB_CURRENCY.
	 */
	@Column(name = "VOUC_VL_ISSUED_TB_CURRENCY", precision = 22, scale = 0)
	private BigDecimal valorIssuedTbCurrency;

	/**
	 * Atributo gerado a partir da coluna VOUC_VL_USED_TB_CURRENCY.
	 */
	@Column(name = "VOUC_VL_USED_TB_CURRENCY", precision = 22, scale = 0)
	private BigDecimal valorUsedTbCurrency;

	/**
	 * Atributo gerado a partir da coluna VOUC_VL_ClOSED_TB_CURRENCY.
	 */
	@Column(name = "VOUC_VL_CLOSED_TB_CURRENCY", precision = 22, scale = 0)
	private BigDecimal valorClosedTbCurrency;

	/**
	 * Construtor default.
	 */
	public Voucher() {
	}

	/**
	 * Obtem o valor do atributo codigoVoucher.<BR>
	 * Atributo gerado a partir da coluna VOUC_CD_VOUCHER.
	 * 
	 * @return Valor do atributo codigoVoucher.
	 */
	public Long getCodigoVoucher() {
		return this.codigoVoucher;
	}

	/**
	 * Atualiza o valor do atributo codigoVoucher.<BR>
	 * Atributo gerado a partir da coluna VOUC_CD_VOUCHER.
	 * 
	 * @param codigoVoucher
	 *            Novo valor para o atributo codigoVoucher.
	 */
	public void setCodigoVoucher(final Long codigoVoucher) {
		this.codigoVoucher = codigoVoucher;
	}

	/**
	 * Obtem o valor do atributo pessoa.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 * 
	 * @return Valor do atributo pessoa.
	 */
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	/**
	 * Atualiza o valor do atributo pessoa.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_PESSOA.
	 * 
	 * @param pessoa
	 *            Novo valor para o atributo pessoa.
	 */
	public void setPessoa(final Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	/**
	 * Obtem o valor do atributo numeroVoucher.<BR>
	 * Atributo gerado a partir da coluna VOUC_NR_VOUCHER.
	 * 
	 * @return Valor do atributo numeroVoucher.
	 */
	public String getNumeroVoucher() {
		return this.numeroVoucher;
	}

	/**
	 * Atualiza o valor do atributo numeroVoucher.<BR>
	 * Atributo gerado a partir da coluna VOUC_NR_VOUCHER.
	 * 
	 * @param numeroVoucher
	 *            Novo valor para o atributo numeroVoucher.
	 */
	public void setNumeroVoucher(final String numeroVoucher) {
		this.numeroVoucher = numeroVoucher;
	}

	/**
	 * Obtem o valor do atributo codigoOrcDespesa.<BR>
	 * Atributo gerado a partir da coluna ORDE_CD_ORC_DESPESA.
	 * 
	 * @return Valor do atributo codigoOrcDespesa.
	 */
	public Long getCodigoOrcDespesa() {
		return this.codigoOrcDespesa;
	}

	/**
	 * Atualiza o valor do atributo codigoOrcDespesa.<BR>
	 * Atributo gerado a partir da coluna ORDE_CD_ORC_DESPESA.
	 * 
	 * @param codigoOrcDespesa
	 *            Novo valor para o atributo codigoOrcDespesa.
	 */
	public void setCodigoOrcDespesa(final Long codigoOrcDespesa) {
		this.codigoOrcDespesa = codigoOrcDespesa;
	}

	/**
	 * Obtem o valor do atributo indicadorStatus.<BR>
	 * Atributo gerado a partir da coluna VOUC_IN_STATUS.
	 * 
	 * @return Valor do atributo indicadorStatus.
	 */
	public String getIndicadorStatus() {
		return this.indicadorStatus;
	}

	/**
	 * Atualiza o valor do atributo indicadorStatus.<BR>
	 * Atributo gerado a partir da coluna VOUC_IN_STATUS.
	 * 
	 * @param indicadorStatus
	 *            Novo valor para o atributo indicadorStatus.
	 */
	public void setIndicadorStatus(final String indicadorStatus) {
		this.indicadorStatus = indicadorStatus;
	}

	/**
	 * Obtem o valor do atributo valorUsed.<BR>
	 * Atributo gerado a partir da coluna VOUC_VL_USED.
	 * 
	 * @return Valor do atributo valorUsed.
	 */
	public BigDecimal getValorUsed() {
		return this.valorUsed;
	}

	/**
	 * Atualiza o valor do atributo valorUsed.<BR>
	 * Atributo gerado a partir da coluna VOUC_VL_USED.
	 * 
	 * @param valorUsed
	 *            Novo valor para o atributo valorUsed.
	 */
	public void setValorUsed(final BigDecimal valorUsed) {
		this.valorUsed = valorUsed;
	}

	/**
	 * Obtem o valor do atributo valorClosed.<BR>
	 * Atributo gerado a partir da coluna VOUC_VL_CLOSED.
	 * 
	 * @return Valor do atributo valorClosed.
	 */
	public BigDecimal getValorClosed() {
		return this.valorClosed;
	}

	/**
	 * Atualiza o valor do atributo valorClosed.<BR>
	 * Atributo gerado a partir da coluna VOUC_VL_CLOSED.
	 * 
	 * @param valorClosed
	 *            Novo valor para o atributo valorClosed.
	 */
	public void setValorClosed(final BigDecimal valorClosed) {
		this.valorClosed = valorClosed;
	}

	/**
	 * Obtem o valor do atributo indicadorRedFlag.<BR>
	 * Atributo gerado a partir da coluna VOUC_IN_RED_FLAG.
	 * 
	 * @return Valor do atributo indicadorRedFlag.
	 */
	public String getIndicadorRedFlag() {
		return this.indicadorRedFlag;
	}

	/**
	 * Atualiza o valor do atributo indicadorRedFlag.<BR>
	 * Atributo gerado a partir da coluna VOUC_IN_RED_FLAG.
	 * 
	 * @param indicadorRedFlag
	 *            Novo valor para o atributo indicadorRedFlag.
	 */
	public void setIndicadorRedFlag(final String indicadorRedFlag) {
		this.indicadorRedFlag = indicadorRedFlag;
	}

	/**
	 * Obtem o valor do atributo dataCreation.<BR>
	 * Atributo gerado a partir da coluna VOUC_DT_CREATION.
	 * 
	 * @return Valor do atributo dataCreation.
	 */
	public Date getDataCreation() {
		return this.dataCreation;
	}

	/**
	 * Atualiza o valor do atributo dataCreation.<BR>
	 * Atributo gerado a partir da coluna VOUC_DT_CREATION.
	 * 
	 * @param dataCreation
	 *            Novo valor para o atributo dataCreation.
	 */
	public void setDataCreation(final Date dataCreation) {
		this.dataCreation = dataCreation;
	}

	/**
	 * Obtem o valor do atributo dataUpdate.<BR>
	 * Atributo gerado a partir da coluna VOUC_DT_UPDATE.
	 * 
	 * @return Valor do atributo dataUpdate.
	 */
	public Date getDataUpdate() {
		return this.dataUpdate;
	}

	/**
	 * Atualiza o valor do atributo dataUpdate.<BR>
	 * Atributo gerado a partir da coluna VOUC_DT_UPDATE.
	 * 
	 * @param dataUpdate
	 *            Novo valor para o atributo dataUpdate.
	 */
	public void setDataUpdate(final Date dataUpdate) {
		this.dataUpdate = dataUpdate;
	}

	/**
	 * Obtem o valor do atributo valorIssued.<BR>
	 * Atributo gerado a partir da coluna VOUC_VL_ISSUED.
	 * 
	 * @return Valor do atributo valorIssued.
	 */
	public BigDecimal getValorIssued() {
		return this.valorIssued;
	}

	/**
	 * Atualiza o valor do atributo valorIssued.<BR>
	 * Atributo gerado a partir da coluna VOUC_VL_ISSUED.
	 * 
	 * @param valorIssued
	 *            Novo valor para o atributo valorIssued.
	 */
	public void setValorIssued(final BigDecimal valorIssued) {
		this.valorIssued = valorIssued;
	}

	/**
	 * Obtem o valor do atributo indicadorEmailSent.<BR>
	 * Atributo gerado a partir da coluna VOUC_IN_EMAIL_SENT.
	 * 
	 * @return Valor do atributo indicadorEmailSent.
	 */
	public String getIndicadorEmailSent() {
		return this.indicadorEmailSent;
	}

	/**
	 * Atualiza o valor do atributo indicadorEmailSent.<BR>
	 * Atributo gerado a partir da coluna VOUC_IN_EMAIL_SENT.
	 * 
	 * @param indicadorEmailSent
	 *            Novo valor para o atributo indicadorEmailSent.
	 */
	public void setIndicadorEmailSent(final String indicadorEmailSent) {
		this.indicadorEmailSent = indicadorEmailSent;
	}

	/**
	 * Obtem o valor do atributo codigoContratoPratica.<BR>
	 * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
	 * 
	 * @return Valor do atributo codigoContratoPratica.
	 */
	public Long getCodigoContratoPratica() {
		return this.codigoContratoPratica;
	}

	/**
	 * Atualiza o valor do atributo codigoContratoPratica.<BR>
	 * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
	 * 
	 * @param codigoContratoPratica
	 *            Novo valor para o atributo codigoContratoPratica.
	 */
	public void setCodigoContratoPratica(final Long codigoContratoPratica) {
		this.codigoContratoPratica = codigoContratoPratica;
	}

	/**
	 * @return the codigoVoucherGae
	 */
	public Long getCodigoVoucherGae() {
		return codigoVoucherGae;
	}

	/**
	 * @param codigoVoucherGae
	 *            the codigoVoucherGae to set
	 */
	public void setCodigoVoucherGae(Long codigoVoucherGae) {
		this.codigoVoucherGae = codigoVoucherGae;
	}

	/**
	 * @return the indicadorSync
	 */
	public String getIndicadorSync() {
		return indicadorSync;
	}

	/**
	 * @param indicadorSync
	 *            the indicadorSync to set
	 */
	public void setIndicadorSync(final String indicadorSync) {
		this.indicadorSync = indicadorSync;
	}

	/**
	 * @return the codigoGrupoCusto
	 */
	public Long getCodigoGrupoCusto() {
		return codigoGrupoCusto;
	}

	/**
	 * @param codigoGrupoCusto
	 *            the codigoGrupoCusto to set
	 */
	public void setCodigoGrupoCusto(final Long codigoGrupoCusto) {
		this.codigoGrupoCusto = codigoGrupoCusto;
	}

	/**
	 * @return the acronymSourceUpdate
	 */
	public String getAcronymSourceUpdate() {
		return acronymSourceUpdate;
	}

	/**
	 * @param acronymSourceUpdate
	 *            the acronymSourceUpdate to set
	 */
	public void setAcronymSourceUpdate(final String acronymSourceUpdate) {
		this.acronymSourceUpdate = acronymSourceUpdate;
	}

	/**
	 * @return the codeAuthorUpdate
	 */
	public String getCodeAuthorUpdate() {
		return codeAuthorUpdate;
	}

	/**
	 * @param codeAuthorUpdate
	 *            the codigoAutorUpdate to set
	 */
	public void setCodeAuthorUpdate(final String codeAuthorUpdate) {
		this.codeAuthorUpdate = codeAuthorUpdate;
	}

	/**
	 * @return the codigoMoeda
	 */
	public String getSiglaMoeda() {
		return siglaMoeda;
	}

	/**
	 * @param codigoMoeda
	 *            the codigoMoeda to set
	 */
	public void setSiglaMoeda(String siglaMoeda) {
		this.siglaMoeda = siglaMoeda;
	}

	/**
	 * @return the valorIssuedTbCurrency
	 */
	public BigDecimal getValorIssuedTbCurrency() {
		return valorIssuedTbCurrency;
	}

	/**
	 * @param valorIssuedTbCurrency
	 *            the valorIssuedTbCurrency to set
	 */
	public void setValorIssuedTbCurrency(BigDecimal valorIssuedTbCurrency) {
		this.valorIssuedTbCurrency = valorIssuedTbCurrency;
	}

	/**
	 * @return the valorUsedTbCurrency
	 */
	public BigDecimal getValorUsedTbCurrency() {
		return valorUsedTbCurrency;
	}

	/**
	 * @param valorUsedTbCurrency
	 *            the valorUsedTbCurrency to set
	 */
	public void setValorUsedTbCurrency(BigDecimal valorUsedTbCurrency) {
		this.valorUsedTbCurrency = valorUsedTbCurrency;
	}

	/**
	 * @return the valorClosedTbCurrency
	 */
	public BigDecimal getValorClosedTbCurrency() {
		return valorClosedTbCurrency;
	}

	/**
	 * @param valorClosedTbCurrency
	 *            the valorClosedTbCurrency to set
	 */
	public void setValorClosedTbCurrency(BigDecimal valorClosedTbCurrency) {
		this.valorClosedTbCurrency = valorClosedTbCurrency;
	}

	/**
	 * Retorna o valor do voucher de acordo com o status atual do mesmo.
	 * 
	 * @return {@link BigDecimal}
	 */
	public BigDecimal getValueFromCurrentStatus() {
		if (this.getIndicadorStatus().equals(Constants.STATUS_VOUCHER_OPEN)) {
			return this.getValorIssued();
		} else if (this.getIndicadorStatus().equals(
				Constants.STATUS_VOUCHER_USED)) {
			return this.getValorUsed();
		} else if (this.getIndicadorStatus().equals(
				Constants.STATUS_VOUCHER_CLOSED)) {
			return this.getValorClosed();
		}

		return BigDecimal.ZERO;
	}

	/**
	 * Obtem o nome do status corrente do voucher.
	 * 
	 * @return {@link String}
	 */
	public String getCurrentStatusName() {
		if (this.getIndicadorStatus().equals(Constants.STATUS_VOUCHER_OPEN)) {
			return "Open";
		} else if (this.getIndicadorStatus().equals(
				Constants.STATUS_VOUCHER_USED)) {
			return "Used";
		} else if (this.getIndicadorStatus().equals(
				Constants.STATUS_VOUCHER_CLOSED)) {
			return "Closed";
		} else if (this.getIndicadorStatus().equals(
				Constants.STATUS_VOUCHER_CANCEL)) {
			return "Cancel";
		} else if (this.getIndicadorStatus().equals(
				Constants.STATUS_VOUCHER_EXPIRED)) {
			return "Expired";
		}
		return "-";
	}

	/**
	 * @return the orcamentoDespesa
	 */
	public OrcamentoDespesa getOrcamentoDespesa() {
		return orcamentoDespesa;
	}

	/**
	 * @param orcamentoDespesa
	 *            the orcamentoDespesa to set
	 */
	public void setOrcamentoDespesa(OrcamentoDespesa orcamentoDespesa) {
		this.orcamentoDespesa = orcamentoDespesa;
	}

	/**
	 * @see Object#toString()
	 * @return buffer
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoVoucher").append("='").append(getCodigoVoucher())
				.append("' ");
		buffer.append("pessoa").append("='").append(getPessoa()).append("' ");
		buffer.append("numeroVoucher").append("='").append(getNumeroVoucher())
				.append("' ");
		buffer.append("codigoOrcDespesa").append("='")
				.append(getCodigoOrcDespesa()).append("' ");
		buffer.append("indicadorStatus").append("='")
				.append(getIndicadorStatus()).append("' ");
		buffer.append("valorUsed").append("='").append(getValorUsed())
				.append("' ");
		buffer.append("valorClosed").append("='").append(getValorClosed())
				.append("' ");
		buffer.append("indicadorRedFlag").append("='")
				.append(getIndicadorRedFlag()).append("' ");
		buffer.append("dataCreation").append("='").append(getDataCreation())
				.append("' ");
		buffer.append("dataUpdate").append("='").append(getDataUpdate())
				.append("' ");
		buffer.append("valorIssued").append("='").append(getValorIssued())
				.append("' ");
		buffer.append("indicadorEmailSent").append("='")
				.append(getIndicadorEmailSent()).append("' ");
		buffer.append("codigoContratoPratica").append("='")
				.append(getCodigoContratoPratica()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}