/*
 * @(#) VoucherHistorico.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity gerado a partir da tabela VOUCHER_HISTORICO.
 *
 * @author Generated by Hibernate Tools 3.6.0
 * @since Feb 14, 2013 4:40:52 PM
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VOUCHER_HISTORICO")
@NamedQueries({ @NamedQuery(name = "VoucherHistorico.findAll", query = "SELECT t FROM VoucherHistorico t") })
public class VoucherHistorico implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * Constante para NamedQuery "VoucherHistorico.findAll".
	 */
	public static final String FIND_ALL = "VoucherHistorico.findAll";

	/**
	 * Atributo gerado a partir da coluna VOHI_CD_VOUCHER_HISTORICO.
	 */
	@Id
	@GeneratedValue(generator = "VoucherHistoricoSeq")
	@SequenceGenerator(name = "VoucherHistoricoSeq", sequenceName = "SQ_VOHI_CD_VOUCHER_HISTORICO", allocationSize = 1)
	@Column(name = "VOHI_CD_VOUCHER_HISTORICO", unique = true, nullable = false, precision = 18, scale = 0)
	private Long codigoVoucherHistorico;

	/**
	 * Atributo gerado a partir da coluna VOUC_CD_VOUCHER.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUC_CD_VOUCHER", nullable = false)
	private Voucher voucher;

	/**
	 * Atributo gerado a partir da coluna VOHI_SG_APP_FONTE.
	 */

	@Column(name = "VOHI_SG_APP_FONTE", length = 2)
	private String siglaAppFonte;

	/**
	 * Atributo gerado a partir da coluna VOHI_DT_HORA.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "VOHI_DT_HORA", length = 7)
	private Date dataHora;

	/**
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN.
	 */

	@Column(name = "PESS_CD_LOGIN", length = 20)
	private String codigoLogin;

	/**
	 * Atributo gerado a partir da coluna VOHI_VL_USED.
	 */

	@Column(name = "VOHI_VL_USED", precision = 22, scale = 0)
	private BigDecimal valorUsed;

	/**
	 * Atributo gerado a partir da coluna VOHI_IN_STATUS.
	 */

	@Column(name = "VOHI_IN_STATUS", length = 2)
	private String indicadorStatus;

	/**
	 * Construtor default.
	 */
	public VoucherHistorico() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * @param codigoVoucherHistorico Valor do atributo codigoVoucherHistorico;
	 * @param voucher Valor do atributo voucher;
	 */
	public VoucherHistorico(final Long codigoVoucherHistorico, final Voucher voucher) {
		this.codigoVoucherHistorico = codigoVoucherHistorico;
		this.voucher = voucher;
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * @param codigoVoucherHistorico Valor do atributo codigoVoucherHistorico;
	 * @param voucher Valor do atributo voucher;
	 */
	public VoucherHistorico(final Long codigoVoucherHistorico, final Voucher voucher,
			final String siglaAppFonte, final Date dataHora, final String codigoLogin,
			final BigDecimal valorUsed, final String indicadorStatus) {
		this.codigoVoucherHistorico = codigoVoucherHistorico;
		this.voucher = voucher;
		this.siglaAppFonte = siglaAppFonte;
		this.dataHora = dataHora;
		this.codigoLogin = codigoLogin;
		this.valorUsed = valorUsed;
		this.indicadorStatus = indicadorStatus;
	}

	/**
	 * Obtem o valor do atributo codigoVoucherHistorico.<BR>
	 * Atributo gerado a partir da coluna VOHI_CD_VOUCHER_HISTORICO.
	 * @return Valor do atributo codigoVoucherHistorico.
	 */
	public Long getCodigoVoucherHistorico() {
		return this.codigoVoucherHistorico;
	}

	/**
	 * Atualiza o valor do atributo codigoVoucherHistorico.<BR>
	 * Atributo gerado a partir da coluna VOHI_CD_VOUCHER_HISTORICO.
	 * @param codigoVoucherHistorico Novo valor para o atributo codigoVoucherHistorico.
	 */
	public void setCodigoVoucherHistorico(final Long codigoVoucherHistorico) {
		this.codigoVoucherHistorico = codigoVoucherHistorico;
	}

	/**
	 * Obtem o valor do atributo voucher.<BR>
	 * Atributo gerado a partir da coluna VOUC_CD_VOUCHER.
	 * @return Valor do atributo voucher.
	 */
	public Voucher getVoucher() {
		return this.voucher;
	}

	/**
	 * Atualiza o valor do atributo voucher.<BR>
	 * Atributo gerado a partir da coluna VOUC_CD_VOUCHER.
	 * @param voucher Novo valor para o atributo voucher.
	 */
	public void setVoucher(final Voucher voucher) {
		this.voucher = voucher;
	}

	/**
	 * Obtem o valor do atributo siglaAppFonte.<BR>
	 * Atributo gerado a partir da coluna VOHI_SG_APP_FONTE.
	 * @return Valor do atributo siglaAppFonte.
	 */
	public String getSiglaAppFonte() {
		return this.siglaAppFonte;
	}

	/**
	 * Atualiza o valor do atributo siglaAppFonte.<BR>
	 * Atributo gerado a partir da coluna VOHI_SG_APP_FONTE.
	 * @param siglaAppFonte Novo valor para o atributo siglaAppFonte.
	 */
	public void setSiglaAppFonte(final String siglaAppFonte) {
		this.siglaAppFonte = siglaAppFonte;
	}

	/**
	 * Obtem o valor do atributo dataHora.<BR>
	 * Atributo gerado a partir da coluna VOHI_DT_HORA.
	 * @return Valor do atributo dataHora.
	 */
	public Date getDataHora() {
		return this.dataHora;
	}

	/**
	 * Atualiza o valor do atributo dataHora.<BR>
	 * Atributo gerado a partir da coluna VOHI_DT_HORA.
	 * @param dataHora Novo valor para o atributo dataHora.
	 */
	public void setDataHora(final Date dataHora) {
		this.dataHora = dataHora;
	}

	/**
	 * Obtem o valor do atributo codigoLogin.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN.
	 * @return Valor do atributo codigoLogin.
	 */
	public String getCodigoLogin() {
		return this.codigoLogin;
	}

	/**
	 * Atualiza o valor do atributo codigoLogin.<BR>
	 * Atributo gerado a partir da coluna PESS_CD_LOGIN.
	 * @param codigoLogin Novo valor para o atributo codigoLogin.
	 */
	public void setCodigoLogin(final String codigoLogin) {
		this.codigoLogin = codigoLogin;
	}

	/**
	 * Obtem o valor do atributo valorUsed.<BR>
	 * Atributo gerado a partir da coluna VOHI_VL_USED.
	 * @return Valor do atributo valorUsed.
	 */
	public BigDecimal getValorUsed() {
		return this.valorUsed;
	}

	/**
	 * Atualiza o valor do atributo valorUsed.<BR>
	 * Atributo gerado a partir da coluna VOHI_VL_USED.
	 * @param valorUsed Novo valor para o atributo valorUsed.
	 */
	public void setValorUsed(final BigDecimal valorUsed) {
		this.valorUsed = valorUsed;
	}

	/**
	 * Obtem o valor do atributo indicadorStatus.<BR>
	 * Atributo gerado a partir da coluna VOHI_IN_STATUS.
	 * @return Valor do atributo indicadorStatus.
	 */
	public String getIndicadorStatus() {
		return this.indicadorStatus;
	}

	/**
	 * Atualiza o valor do atributo indicadorStatus.<BR>
	 * Atributo gerado a partir da coluna VOHI_IN_STATUS.
	 * @param indicadorStatus Novo valor para o atributo indicadorStatus.
	 */
	public void setIndicadorStatus(final String indicadorStatus) {
		this.indicadorStatus = indicadorStatus;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("codigoVoucherHistorico").append("='")
				.append(getCodigoVoucherHistorico()).append("' ");
		buffer.append("voucher").append("='").append(getVoucher()).append("' ");
		buffer.append("siglaAppFonte").append("='").append(getSiglaAppFonte())
				.append("' ");
		buffer.append("dataHora").append("='").append(getDataHora())
				.append("' ");
		buffer.append("codigoLogin").append("='").append(getCodigoLogin())
				.append("' ");
		buffer.append("valorUsed").append("='").append(getValorUsed())
				.append("' ");
		buffer.append("indicadorStatus").append("='")
				.append(getIndicadorStatus()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
