/*
 * @(#) VwAlocacaoRecursoMes.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela VW_ALOCACAO_RECURSO_MES.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 08/10/2009 14:59:53
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VW_ALOCACAO_RECURSO_MES")
@NamedQueries({ 
    @NamedQuery(name = "VwAlocacaoRecursoMes.findAll", query = "SELECT t FROM VwAlocacaoRecursoMes t"),
    
    @NamedQuery(name = "VwAlocacaoRecursoMes.findByRecursoAndDataAlocacao", 
            query = "SELECT vw FROM VwAlocacaoRecursoMes vw"
                + " WHERE vw.id.codigoRecurso = ? "
                + " AND TRUNC(vw.id.dataAlocacaoPeriodo) = TRUNC(?) "),
                
    @NamedQuery(name = "VwAlocacaoRecursoMes.findByMnemonicoAndDataAlocacao", 
            query = "SELECT vw FROM VwAlocacaoRecursoMes vw "
                + " WHERE vw.id.codigoMnemonico = ? "
                + " AND TRUNC(vw.id.dataAlocacaoPeriodo) = TRUNC(?) "),
    @NamedQuery(name = "VwAlocacaoRecursoMes.findByMnemonicoInAndDataAlocacao",
            query = "SELECT vw FROM VwAlocacaoRecursoMes vw "
                + " WHERE vw.id.codigoMnemonico in :people "
                + " AND TRUNC(vw.id.dataAlocacaoPeriodo) = TRUNC(:month) ")
})
public class VwAlocacaoRecursoMes implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    
    /** Constante para NamedQuery "VwAlocacaoRecursoMes.findByRecursoAndDataAlocacao". */
    public static final String FIND_BY_RECURSO_AND_DATA_ALOCACAO = 
        "VwAlocacaoRecursoMes.findByRecursoAndDataAlocacao";
    
    /** Constante para NamedQuery "VwAlocacaoRecursoMes.findByMnemonicoAndDataAlocacao". */
    public static final String FIND_BY_MNEMONICO_AND_DATA_ALOCACAO = 
        "VwAlocacaoRecursoMes.findByMnemonicoAndDataAlocacao";

    /** Constante para NamedQuery "VwAlocacaoRecursoMes.findByMnemonicoInAndDataAlocacao". */
    public static final String FIND_BY_MNEMONICO_IN_AND_DATA_ALOCACAO =
            "VwAlocacaoRecursoMes.findByMnemonicoInAndDataAlocacao";
    
    // ========================================================================
    // END
    // ========================================================================
    
    
    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "VwAlocacaoRecursoMes.findAll".
     */
    public static final String FIND_ALL = "VwAlocacaoRecursoMes.findAll";

    /**
     * Atributo gerado a partir da coluna PR_ALOCACAO_PERIODO_MES.
     */
    @EmbeddedId
    @GeneratedValue(generator = "VwAlocacaoRecursoMesSeq")
    @SequenceGenerator(name = "VwAlocacaoRecursoMesSeq", sequenceName = "SQ_RECU_CD_RECURSO", allocationSize = 1)
    @AttributeOverrides({
            @AttributeOverride(name = "codigoRecurso", 
                    column = @Column(name = "RECU_CD_RECURSO", nullable = false, precision = 18, scale = 0)),
            @AttributeOverride(name = "codigoMnemonico", 
                    column = @Column(name = "RECU_CD_MNEMONICO", length = 50)),
            @AttributeOverride(name = "dataAlocacaoPeriodo", 
                    column = @Column(name = "ALPE_DT_ALOCACAO_PERIODO", length = 7)),
            @AttributeOverride(name = "alocacaoPeriodoMes", 
                    column = @Column(name = "PR_ALOCACAO_PERIODO_MES", precision = 22, scale = 0)) })
    private VwAlocacaoRecursoMesId id;

    /**
     * Construtor default.
     */
    public VwAlocacaoRecursoMes() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param id Valor do atributo id;
     */
    public VwAlocacaoRecursoMes(final VwAlocacaoRecursoMesId id) {
        this.id = id;
    }

    /**
     * Obtem o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna PR_ALOCACAO_PERIODO_MES.
     * @return Valor do atributo id.
     */
    public VwAlocacaoRecursoMesId getId() {
        return this.id;
    }

    /**
     * Atualiza o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna PR_ALOCACAO_PERIODO_MES.
     * @param id Novo valor para o atributo id.
     */
    public void setId(final VwAlocacaoRecursoMesId id) {
        this.id = id;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna o objeto em formato de string
     * 
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
