/*
 * @(#) VwAlocContratoRecursoMes.java
 * Copyright (c) 2010 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela VW_ALOC_CONTRATO_RECURSO_MES.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 13/09/2010 15:32:24
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VW_ALOC_CONTRATO_RECURSO_MES")
@NamedQueries({ 
    @NamedQuery(name = "VwAlocContratoRecursoMes.findAll", query = "SELECT t FROM VwAlocContratoRecursoMes t"),
    @NamedQuery(name = "VwAlocContratoRecursoMes.findByMapaAndPeriod", 
            query = "SELECT t FROM VwAlocContratoRecursoMes t" 
                + " WHERE (t.codigoMapaAlocacao = ? OR t.codigoMapaAlocacao = 0L) " 
                + " AND TRUNC(t.id.dataAlocacaoPeriodo) between TRUNC(?) and TRUNC(?)")
})
public class VwAlocContratoRecursoMes implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** Constante para NamedQuery "VwAlocContratoRecursoMes.findAll". */
    public static final String FIND_ALL = "VwAlocContratoRecursoMes.findAll";

    /** Constante para NamedQuery "VwAlocContratoRecursoMes.findAll". */
    public static final String FIND_BY_MAPA_AND_PERIOD = "VwAlocContratoRecursoMes.findByMapaAndPeriod";
    
    /**
     * Atributo gerado a partir da coluna ACRM_IN_SUPER_ALOCACAO.
     */
    @EmbeddedId
    @GeneratedValue(generator = "VwAlocContratoRecursoMesSeq")
    @SequenceGenerator(name = "VwAlocContratoRecursoMesSeq", 
            sequenceName = "SQ_PESS_CD_LOGIN", allocationSize = 1)
    @AttributeOverrides({
            @AttributeOverride(name = "codigoLogin", 
                    column = @Column(name = "PESS_CD_LOGIN", length = 20)),
            @AttributeOverride(name = "codigoRecurso", 
                    column = @Column(name = "RECU_CD_RECURSO", precision = 18, scale = 0)),
            @AttributeOverride(name = "codigoAlocacaoPeriodo", 
                    column = @Column(name = "ALPE_CD_ALOCACAO_PERIODO", precision = 22, scale = 0))
    })
    private VwAlocContratoRecursoMesId id;

    /** Atributo gerado a partir da coluna PESS_CD_LOGIN. */
    @Column(name = "PESS_CD_LOGIN", length = 20)
    private String codigoLogin;
    
    /** Atributo gerado a partir da coluna PETC_PR_ALOCAVEL. */
    @Column(name = "PETC_PR_ALOCAVEL", precision = 10)
    private BigDecimal percentualAlocavel;

    /** Atributo gerado a partir da coluna MAAL_CD_MAPA_ALOCACAO. */
    @Column(name = "MAAL_CD_MAPA_ALOCACAO", precision = 18, scale = 0)
    private Long codigoMapaAlocacao;

    /** Atributo gerado a partir da coluna COPR_NM_CONTRATO_PRATICA. */
    @Column(name = "COPR_NM_CONTRATO_PRATICA", length = 240)
    private String nomeContratoPratica;

    /** Atributo gerado a partir da coluna ALPE_PR_ALOCACAO_PERIODO. */
    @Column(name = "ALPE_PR_ALOCACAO_PERIODO", precision = 22, scale = 0)
    private BigDecimal percentualAlocacaoPeriodo;

    /** Atributo gerado a partir da coluna ACRM_TOTAL_ALOCACAO. */
    @Column(name = "ACRM_TOTAL_ALOCACAO", precision = 22, scale = 0)
    private BigDecimal totalAlocacao;

    /** Atributo gerado a partir da coluna ACRM_PR_FERIAS. */
    @Column(name = "ACRM_PR_FERIAS", precision = 22, scale = 0)
    private BigDecimal percentualFerias;

    /** Atributo gerado a partir da coluna ACRM_PR_LICENCA. */
    @Column(name = "ACRM_PR_LICENCA", precision = 22, scale = 0)
    private BigDecimal percentualLicenca;

    /** Atributo gerado a partir da coluna ACRM_VL_TOTAL_OH. */
    @Column(name = "ACRM_VL_TOTAL_OH", precision = 22, scale = 0)
    private BigDecimal valorTotalOh;

    /** Atributo gerado a partir da coluna ACRM_IN_SUPER_ALOCACAO. */
    @Column(name = "ACRM_IN_SUPER_ALOCACAO", scale = 0)
    private Integer indicadorSuperAlocacao;
    
    /**
     * Construtor default.
     */
    public VwAlocContratoRecursoMes() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param id Valor do atributo id;
     */
    public VwAlocContratoRecursoMes(final VwAlocContratoRecursoMesId id) {
        this.id = id;
    }

    /**
     * Obtem o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna ACRM_IN_SUPER_ALOCACAO.
     * @return Valor do atributo id.
     */
    public VwAlocContratoRecursoMesId getId() {
        return this.id;
    }

    /**
     * Atualiza o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna ACRM_IN_SUPER_ALOCACAO.
     * @param id Novo valor para o atributo id.
     */
    public void setId(final VwAlocContratoRecursoMesId id) {
        this.id = id;
    }
    
    /**
     * Obtem o valor do atributo codigoLogin.<BR>

     * @return Valor do atributo codigoLogin.
     */
    public String getCodigoLogin() {
        return this.codigoLogin;
    }

    /**
     * Atualiza o valor do atributo codigoLogin.<BR>

     * @param codigoLogin Novo valor para o atributo codigoLogin.
     */
    public void setCodigoLogin(final String codigoLogin) {
        this.codigoLogin = codigoLogin;
    }
    
    /**
     * Obtem o valor do atributo percentualAlocavel.<BR>

     * @return Valor do atributo percentualAlocavel.
     */
    public BigDecimal getPercentualAlocavel() {
        return this.percentualAlocavel;
    }

    /**
     * Atualiza o valor do atributo percentualAlocavel.<BR>

     * @param percentualAlocavel Novo valor para o atributo percentualAlocavel.
     */
    public void setPercentualAlocavel(final BigDecimal percentualAlocavel) {
        this.percentualAlocavel = percentualAlocavel;
    }

    /**
     * Obtem o valor do atributo codigoMapaAlocacao.<BR>

     * @return Valor do atributo codigoMapaAlocacao.
     */
    public Long getCodigoMapaAlocacao() {
        return this.codigoMapaAlocacao;
    }

    /**
     * Atualiza o valor do atributo codigoMapaAlocacao.<BR>

     * @param codigoMapaAlocacao Novo valor para o atributo codigoMapaAlocacao.
     */
    public void setCodigoMapaAlocacao(final Long codigoMapaAlocacao) {
        this.codigoMapaAlocacao = codigoMapaAlocacao;
    }

    /**
     * Obtem o valor do atributo nomeContratoPratica.<BR>

     * @return Valor do atributo nomeContratoPratica.
     */
    public String getNomeContratoPratica() {
        return this.nomeContratoPratica;
    }

    /**
     * Atualiza o valor do atributo nomeContratoPratica.<BR>

     * @param nomeContratoPratica Novo valor para o atributo nomeContratoPratica.
     */
    public void setNomeContratoPratica(final String nomeContratoPratica) {
        this.nomeContratoPratica = nomeContratoPratica;
    }

    /**
     * Obtem o valor do atributo percentualAlocacaoPeriodo.<BR>

     * @return Valor do atributo percentualAlocacaoPeriodo.
     */
    public BigDecimal getPercentualAlocacaoPeriodo() {
        return this.percentualAlocacaoPeriodo;
    }

    /**
     * Atualiza o valor do atributo percentualAlocacaoPeriodo.<BR>

     * @param percentualAlocacaoPeriodo Novo valor para o atributo percentualAlocacaoPeriodo.
     */
    public void setPercentualAlocacaoPeriodo(
            final BigDecimal percentualAlocacaoPeriodo) {
        this.percentualAlocacaoPeriodo = percentualAlocacaoPeriodo;
    }

    /**
     * Obtem o valor do atributo totalAlocacao.<BR>

     * @return Valor do atributo totalAlocacao.
     */
    public BigDecimal getTotalAlocacao() {
        return this.totalAlocacao;
    }

    /**
     * Atualiza o valor do atributo totalAlocacao.<BR>

     * @param totalAlocacao Novo valor para o atributo totalAlocacao.
     */
    public void setTotalAlocacao(final BigDecimal totalAlocacao) {
        this.totalAlocacao = totalAlocacao;
    }

    /**
     * Obtem o valor do atributo percentualFerias.<BR>

     * @return Valor do atributo percentualFerias.
     */
    public BigDecimal getPercentualFerias() {
        return this.percentualFerias;
    }

    /**
     * Atualiza o valor do atributo percentualFerias.<BR>

     * @param percentualFerias Novo valor para o atributo percentualFerias.
     */
    public void setPercentualFerias(final BigDecimal percentualFerias) {
        this.percentualFerias = percentualFerias;
    }

    /**
     * Obtem o valor do atributo percentualLicenca.<BR>

     * @return Valor do atributo percentualLicenca.
     */
    public BigDecimal getPercentualLicenca() {
        return this.percentualLicenca;
    }

    /**
     * Atualiza o valor do atributo percentualLicenca.<BR>

     * @param percentualLicenca Novo valor para o atributo percentualLicenca.
     */
    public void setPercentualLicenca(final BigDecimal percentualLicenca) {
        this.percentualLicenca = percentualLicenca;
    }

    /**
     * Obtem o valor do atributo valorTotalOh.<BR>

     * @return Valor do atributo valorTotalOh.
     */
    public BigDecimal getValorTotalOh() {
        return this.valorTotalOh;
    }

    /**
     * Atualiza o valor do atributo valorTotalOh.<BR>

     * @param valorTotalOh Novo valor para o atributo valorTotalOh.
     */
    public void setValorTotalOh(final BigDecimal valorTotalOh) {
        this.valorTotalOh = valorTotalOh;
    }

    /**
     * Obtem o valor do atributo indicadorSuperAlocacao.<BR>

     * @return Valor do atributo indicadorSuperAlocacao.
     */
    public Integer getIndicadorSuperAlocacao() {
        return this.indicadorSuperAlocacao;
    }

    /**
     * Atualiza o valor do atributo indicadorSuperAlocacao.<BR>

     * @param indicadorSuperAlocacao Novo valor para o atributo indicadorSuperAlocacao.
     */
    public void setIndicadorSuperAlocacao(
            final Integer indicadorSuperAlocacao) {
        this.indicadorSuperAlocacao = indicadorSuperAlocacao;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
