/*
 * @(#) VwAuditFollow.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela VW_PMS_AUDIT_FOLLOW.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 28/06/2011 11:41:58
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VW_PMS_AUDIT_FOLLOW")
@NamedQueries({ 
    @NamedQuery(name = "VwAuditFollow.findByMapaAlocAndDate", 
            query = "SELECT t FROM VwAuditFollow t "
        + "WHERE (t.codigoMapaAlocacao = ?) "
        + "  AND (TRUNC(t.id.dataRevtstmp) = TRUNC(?)) "
        + "ORDER BY t.id.codigoAutor ASC "),
    
    @NamedQuery(name = "VwAuditFollow.findByRecursoAndDate", 
            query = "SELECT t FROM VwAuditFollow t "
        + "WHERE (t.codigoRecurso = ?) "
        + "  AND (TRUNC(t.id.dataRevtstmp) = TRUNC(?)) "
        + "ORDER BY t.id.codigoAutor ASC ")
})
public class VwAuditFollow implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "VwAuditFollow.findByMapaAlocAndDate".
     */
    public static final String FIND_BY_MAPA_ALOC_AND_DATE = "VwAuditFollow.findByMapaAlocAndDate";
    
    /** 
     * Constante para NamedQuery "VwAuditFollow.findByRecursoAndDate".
     */
    public static final String FIND_BY_RECURSO_AND_DATE = "VwAuditFollow.findByRecursoAndDate";

    /**
     * Atributo gerado a partir da coluna AUFL_CD_ALOCACAO_PERIODO.
     */
    @EmbeddedId
    @GeneratedValue(generator = "VwAuditFollowSeq")
    @SequenceGenerator(name = "VwAuditFollowSeq", sequenceName = "SQ_AUFL_CD_REV", allocationSize = 1)
    @AttributeOverrides({
            @AttributeOverride(name = "codigoRev", 
                    column = @Column(name = "AUFL_CD_REV", precision = 18, scale = 0)),
            @AttributeOverride(name = "dataRevtstmp", column = @Column(name = "AUFL_DT_REVTSTMP", length = 7)),
            @AttributeOverride(name = "codigoAutor", column = @Column(name = "AUFL_CD_AUTOR", length = 50))
            })
    private VwAuditFollowId id;
    
    /** Atributo gerado a partir da coluna AUFL_IN_REVTYPE. */
    @Column(name = "AUFL_IN_REVTYPE", length = 1)
    private String indicadorRevtype;

    /** Atributo gerado a partir da coluna AUFL_CD_MAPA_ALOCACAO. */
    @Column(name = "AUFL_CD_MAPA_ALOCACAO", precision = 18, scale = 0)
    private Long codigoMapaAlocacao;
    
    /** Atributo gerado a partir da coluna AUFL_CD_RECURSO. */
    @Column(name = "AUFL_CD_RECURSO", precision = 18, scale = 0)
    private Long codigoRecurso;

    /** Atributo gerado a partir da coluna AUFL_CD_ALOCACAO. */
    @Column(name = "AUFL_CD_ALOCACAO", precision = 18, scale = 0)
    private Long codigoAlocacao;

    /** Atributo gerado a partir da coluna AUFL_CD_ALOCACAO_PERIODO. */
    @Column(name = "AUFL_CD_ALOCACAO_PERIODO", precision = 18, scale = 0)
    private Long codigoAlocacaoPeriodo;
    
    /** Atributo gerado a partir da coluna AUFL_IN_FLAG. */
    @Column(name = "AUFL_IN_FLAG", length = 1)
    private String indicadorFlag;

    /**
     * Construtor default.
     */
    public VwAuditFollow() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param id Valor do atributo id;
     */
    public VwAuditFollow(final VwAuditFollowId id) {
        this.id = id;
    }

    /**
     * Obtem o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna AUFL_CD_ALOCACAO_PERIODO.
     * @return Valor do atributo id.
     */
    public VwAuditFollowId getId() {
        return this.id;
    }

    /**
     * Atualiza o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna AUFL_CD_ALOCACAO_PERIODO.
     * @param id Novo valor para o atributo id.
     */
    public void setId(final VwAuditFollowId id) {
        this.id = id;
    }

    /**
     * @return the indicadorRevtype
     */
    public String getIndicadorRevtype() {
        return indicadorRevtype;
    }

    /**
     * @param indicadorRevtype the indicadorRevtype to set
     */
    public void setIndicadorRevtype(final String indicadorRevtype) {
        this.indicadorRevtype = indicadorRevtype;
    }

    /**
     * @return the codigoMapaAlocacao
     */
    public Long getCodigoMapaAlocacao() {
        return codigoMapaAlocacao;
    }

    /**
     * @param codigoMapaAlocacao the codigoMapaAlocacao to set
     */
    public void setCodigoMapaAlocacao(final Long codigoMapaAlocacao) {
        this.codigoMapaAlocacao = codigoMapaAlocacao;
    }
    
    /**
     * @return the codigoRecurso
     */
    public Long getCodigoRecurso() {
        return codigoRecurso;
    }

    /**
     * @param codigoRecurso the codigoRecurso to set
     */
    public void setCodigoRecurso(final Long codigoRecurso) {
        this.codigoRecurso = codigoRecurso;
    }

    /**
     * @return the codigoAlocacao
     */
    public Long getCodigoAlocacao() {
        return codigoAlocacao;
    }

    /**
     * @param codigoAlocacao the codigoAlocacao to set
     */
    public void setCodigoAlocacao(final Long codigoAlocacao) {
        this.codigoAlocacao = codigoAlocacao;
    }

    /**
     * @return the codigoAlocacaoPeriodo
     */
    public Long getCodigoAlocacaoPeriodo() {
        return codigoAlocacaoPeriodo;
    }

    /**
     * @param codigoAlocacaoPeriodo the codigoAlocacaoPeriodo to set
     */
    public void setCodigoAlocacaoPeriodo(final Long codigoAlocacaoPeriodo) {
        this.codigoAlocacaoPeriodo = codigoAlocacaoPeriodo;
    }
    
    /**
     * @return the indicadorFlag
     */
    public String getIndicadorFlag() {
        return indicadorFlag;
    }

    /**
     * @param indicadorFlag the indicadorFlag to set
     */
    public void setIndicadorFlag(final String indicadorFlag) {
        this.indicadorFlag = indicadorFlag;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}