/*
 * @(#) VwAuditFollowId.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwAuditFollowId generated by hbm2java.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 28/06/2011 11:41:58
 * @version 09/01/19 1.1 10:08:00
 */
@Embeddable
public class VwAuditFollowId implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** Atributo gerado a partir da coluna AUFL_CD_REV. */
    @Column(name = "AUFL_CD_REV", precision = 18, scale = 0)
    private Long codigoRev;

    /** Atributo gerado a partir da coluna AUFL_DT_REVTSTMP. */
    @Column(name = "AUFL_DT_REVTSTMP", length = 7)
    private Date dataRevtstmp;

    /** Atributo gerado a partir da coluna AUFL_CD_AUTOR. */
    @Column(name = "AUFL_CD_AUTOR", length = 50)
    private String codigoAutor;

    /**
     * Construtor default.
     */
    public VwAuditFollowId() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoRev
     *            Valor do atributo codigoRev;
     * @param dataRevtstmp
     *            Valor do atributo dataRevtstmp;
     * @param codigoAutor
     *            Valor do atributo codigoAutor;
     */
    public VwAuditFollowId(final Long codigoRev, final Date dataRevtstmp,
            final String codigoAutor) {
        this.codigoRev = codigoRev;
        this.dataRevtstmp = dataRevtstmp;
        this.codigoAutor = codigoAutor;
    }

    /**
     * Obtem o valor do atributo codigoRev.<BR>
     * 
     * @return Valor do atributo codigoRev.
     */
    public Long getCodigoRev() {
        return this.codigoRev;
    }

    /**
     * Atualiza o valor do atributo codigoRev.<BR>
     * 
     * @param codigoRev
     *            Novo valor para o atributo codigoRev.
     */
    public void setCodigoRev(final Long codigoRev) {
        this.codigoRev = codigoRev;
    }

    /**
     * Obtem o valor do atributo dataRevtstmp.<BR>
     * 
     * @return Valor do atributo dataRevtstmp.
     */
    public Date getDataRevtstmp() {
        return this.dataRevtstmp;
    }

    /**
     * Atualiza o valor do atributo dataRevtstmp.<BR>
     * 
     * @param dataRevtstmp
     *            Novo valor para o atributo dataRevtstmp.
     */
    public void setDataRevtstmp(final Date dataRevtstmp) {
        this.dataRevtstmp = dataRevtstmp;
    }

    /**
     * Obtem o valor do atributo codigoAutor.<BR>
     * 
     * @return Valor do atributo codigoAutor.
     */
    public String getCodigoAutor() {
        return this.codigoAutor;
    }

    /**
     * Atualiza o valor do atributo codigoAutor.<BR>
     * 
     * @param codigoAutor
     *            Novo valor para o atributo codigoAutor.
     */
    public void setCodigoAutor(final String codigoAutor) {
        this.codigoAutor = codigoAutor;
    }

    /**
     * @see Object#equals(Object)
     * 
     * @param other
     *            - outra entidade.
     * 
     * @return retorna a entidade no formato de String
     */
    @Override
    public boolean equals(final Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof VwAuditFollowId)) {
            return false;
        }
        VwAuditFollowId castOther = (VwAuditFollowId) other;

        return ((this.getCodigoRev() == castOther.getCodigoRev()) || (this
                .getCodigoRev() != null
                && castOther.getCodigoRev() != null && this.getCodigoRev()
                .equals(castOther.getCodigoRev())))
                && ((this.getDataRevtstmp() == castOther.getDataRevtstmp()) || (this
                        .getDataRevtstmp() != null
                        && castOther.getDataRevtstmp() != null && this
                        .getDataRevtstmp().equals(castOther.getDataRevtstmp())))
                && ((this.getCodigoAutor() == castOther.getCodigoAutor()) || (this
                        .getCodigoAutor() != null
                        && castOther.getCodigoAutor() != null && this
                        .getCodigoAutor().equals(castOther.getCodigoAutor())));
    }

    /**
     * @see Object#hashCode()
     * 
     * @return retorna o codigo hash do objeto.
     */
    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result
                + (getCodigoRev() == null ? 0 : this.getCodigoRev().hashCode());
        result = 37
                * result
                + (getDataRevtstmp() == null ? 0 : this.getDataRevtstmp()
                        .hashCode());
        result = 37
                * result
                + (getCodigoAutor() == null ? 0 : this.getCodigoAutor()
                        .hashCode());
        return result;
    }

}