/*
 * @(#) VwChbackSoftware.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela VW_MEGA_CHBACK_SOFTWARE.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 13/07/2011 15:17:37
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VW_MEGA_CHBACK_SOFTWARE")
@NamedQueries({
    @NamedQuery(name = "VwChbackSoftware.findAll", query = "SELECT t FROM VwChbackSoftware t"),
    
    @NamedQuery(name = "VwChbackSoftware.findAllByDate", query = "SELECT sosy FROM VwChbackSoftware sosy "
        + " WHERE (TRUNC(sosy.id.dataMes) = TRUNC(?)) ")
})
public class VwChbackSoftware implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "VwChbackSoftware.findAll".
     */
    public static final String FIND_ALL = "VwChbackSoftware.findAll";
    
    /** 
     * Constante para NamedQuery "VwChbackSoftware.findAllByDate".
     */
    public static final String FIND_ALL_BY_DATE = "VwChbackSoftware.findAllByDate";

    /**
     * Atributo gerado a partir da coluna SOSY_NR_UNIDADES.
     */
    @EmbeddedId
    @GeneratedValue(generator = "VwChbackSoftwareSeq")
    @SequenceGenerator(name = "VwChbackSoftwareSeq", sequenceName = "SQ_SOSY_CD_PESSOA", allocationSize = 1)
    @AttributeOverrides({
            @AttributeOverride(name = "codigoLogin", 
                    column = @Column(name = "SOSY_CD_LOGIN", length = 20)),
            @AttributeOverride(name = "dataMes", 
                    column = @Column(name = "SOSY_DT_MES", length = 7)),
            @AttributeOverride(name = "codigoMnemonico", 
                    column = @Column(name = "SOSY_CD_MNEMONICO", length = 7))})
    private VwChbackSoftwareId id;
    
    /** Atributo gerado a partir da coluna SOSY_CD_PESSOA. */
    @Column(name = "SOSY_CD_PESSOA", precision = 18, scale = 0)
    private Long codigoPessoa;
    
    /** Atributo gerado a partir da coluna SOSY_CD_TI_RECURSO. */
    @Column(name = "SOSY_CD_TI_RECURSO", precision = 18, scale = 0)
    private Long codigoTiRecurso;
    
    /** Atributo gerado a partir da coluna SOSY_NR_UNIDADES. */
    @Column(name = "SOSY_NR_UNIDADES", precision = 22, scale = 0)
    private BigDecimal numeroUnidades;

    /**
     * Construtor default.
     */
    public VwChbackSoftware() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param id Valor do atributo id;
     */
    public VwChbackSoftware(final VwChbackSoftwareId id) {
        this.id = id;
    }

    /**
     * Obtem o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna SOSY_NR_UNIDADES.
     * @return Valor do atributo id.
     */
    public VwChbackSoftwareId getId() {
        return this.id;
    }

    /**
     * Atualiza o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna SOSY_NR_UNIDADES.
     * @param id Novo valor para o atributo id.
     */
    public void setId(final VwChbackSoftwareId id) {
        this.id = id;
    }
    
    /**
     * Obtem o valor do atributo codigoPessoa.<BR>

     * @return Valor do atributo codigoPessoa.
     */
    public Long getCodigoPessoa() {
        return this.codigoPessoa;
    }

    /**
     * Atualiza o valor do atributo codigoPessoa.<BR>

     * @param codigoPessoa Novo valor para o atributo codigoPessoa.
     */
    public void setCodigoPessoa(final Long codigoPessoa) {
        this.codigoPessoa = codigoPessoa;
    }
    
    /**
     * Obtem o valor do atributo codigoTiRecurso.<BR>

     * @return Valor do atributo codigoTiRecurso.
     */
    public Long getCodigoTiRecurso() {
        return this.codigoTiRecurso;
    }

    /**
     * Atualiza o valor do atributo codigoTiRecurso.<BR>

     * @param codigoTiRecurso Novo valor para o atributo codigoTiRecurso.
     */
    public void setCodigoTiRecurso(final Long codigoTiRecurso) {
        this.codigoTiRecurso = codigoTiRecurso;
    }
    
    /**
     * Obtem o valor do atributo numeroHorasJornada.<BR>

     * @return Valor do atributo numeroHorasJornada.
     */
    public BigDecimal getNumeroUnidades() {
        return this.numeroUnidades;
    }

    /**
     * Atualiza o valor do atributo numeroUnidades.<BR>

     * @param numeroUnidades Novo valor para o atributo numeroUnidades.
     */
    public void setNumeroUnidades(final BigDecimal numeroUnidades) {
        this.numeroUnidades = numeroUnidades;
    }

    /**
     * @see Object#toString()
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}