/*
 * @(#) VwCompTceFuncionarioId.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwCompTceFuncionarioId generated by hbm2java.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 10/06/2011 15:18:26
 * @version 09/01/19 1.1 10:08:00
 */
@Embeddable
public class VwCompTceFuncionarioId implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "VwCompTceFuncionarioId.findAll".
     */
    public static final String FIND_ALL = "VwCompTceFuncionarioId.findAll";

    /** Atributo gerado a partir da coluna TCFU_CD_PESSOA. */
    @Column(name = "TCFU_CD_PESSOA", nullable = false, precision = 18, scale = 0)
    private Long codigoPessoa;

    /** Atributo gerado a partir da coluna TCFU_CD_LOGIN. */
    @Column(name = "TCFU_CD_LOGIN", length = 15)
    private String codigoLogin;

    /** Atributo gerado a partir da coluna TCFU_DT_MES. */
    @Column(name = "TCFU_DT_MES", length = 8)
    private Date dataMes;

    /**
     * Construtor default.
     */
    public VwCompTceFuncionarioId() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoPessoa
     *            Valor do atributo codigoPessoa;
     */
    public VwCompTceFuncionarioId(final Long codigoPessoa) {
        this.codigoPessoa = codigoPessoa;
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoPessoa
     *            Valor do atributo codigoPessoa;
     * @param codigoLogin
     *            Valor do atributo codigoLogin;
     * @param dataMes
     *            Valor do atributo dataMes;
     */
    public VwCompTceFuncionarioId(final Long codigoPessoa,
            final String codigoLogin, final Date dataMes) {
        this.codigoPessoa = codigoPessoa;
        this.codigoLogin = codigoLogin;
        this.dataMes = dataMes;
    }

    /**
     * Obtem o valor do atributo codigoPessoa.<BR>
     * 
     * @return Valor do atributo codigoPessoa.
     */
    public Long getCodigoPessoa() {
        return this.codigoPessoa;
    }

    /**
     * Atualiza o valor do atributo codigoPessoa.<BR>
     * 
     * @param codigoPessoa
     *            Novo valor para o atributo codigoPessoa.
     */
    public void setCodigoPessoa(final Long codigoPessoa) {
        this.codigoPessoa = codigoPessoa;
    }

    /**
     * Obtem o valor do atributo codigoLogin.<BR>
     * 
     * @return Valor do atributo codigoLogin.
     */
    public String getCodigoLogin() {
        return this.codigoLogin;
    }

    /**
     * Atualiza o valor do atributo codigoLogin.<BR>
     * 
     * @param codigoLogin
     *            Novo valor para o atributo codigoLogin.
     */
    public void setCodigoLogin(final String codigoLogin) {
        this.codigoLogin = codigoLogin;
    }

    /**
     * Obtem o valor do atributo dataMes.<BR>
     * 
     * @return Valor do atributo dataMes.
     */
    public Date getDataMes() {
        return this.dataMes;
    }

    /**
     * Atualiza o valor do atributo dataMes.<BR>
     * 
     * @param dataMes
     *            Novo valor para o atributo dataMes.
     */
    public void setDataMes(final Date dataMes) {
        this.dataMes = dataMes;
    }

    /**
     * @see Object#equals(Object)
     * 
     * @param other - outra entidade.
     * 
     * @return retorna a entidade no formato de String
     */
    @Override
    public boolean equals(final Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof VwCompTceFuncionarioId)) {
            return false;
        }
        VwCompTceFuncionarioId castOther = (VwCompTceFuncionarioId) other;

        return ((this.getCodigoPessoa() == castOther.getCodigoPessoa()) || (this
                .getCodigoPessoa() != null
                && castOther.getCodigoPessoa() != null && this
                .getCodigoPessoa().equals(castOther.getCodigoPessoa())))
                && ((this.getCodigoLogin() == castOther.getCodigoLogin()) || (this
                        .getCodigoLogin() != null
                        && castOther.getCodigoLogin() != null && this
                        .getCodigoLogin().equals(castOther.getCodigoLogin())))
                && ((this.getDataMes() == castOther.getDataMes()) || (this
                        .getDataMes() != null
                        && castOther.getDataMes() != null && this.getDataMes()
                        .equals(castOther.getDataMes())));
    }

    /**
     * @see Object#hashCode()
     * @return retorna o codigo hash do objeto.
     */
    @Override
    public int hashCode() {
        int result = 17;

        result = 37
                * result
                + (getCodigoPessoa() == null ? 0 : this.getCodigoPessoa()
                        .hashCode());
        result = 37
                * result
                + (getCodigoLogin() == null ? 0 : this.getCodigoLogin()
                        .hashCode());
        result = 37 * result
                + (getDataMes() == null ? 0 : this.getDataMes().hashCode());
        return result;
    }

}