/*
 * @(#) VwCompTceFuncionario.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela VW_MEGA_COMP_TCE_FUNCIONARIO.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 10/06/2011 15:18:26
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VW_MEGA_COMP_TCE_FUNCIONARIO")
@NamedQueries({ 
    @NamedQuery(name = "VwCompTceFuncionario.findAll", query = "SELECT t FROM VwCompTceFuncionario t"),
    
    @NamedQuery(name = "VwCompTceFuncionario.findAllByDate", query = "SELECT tcfu FROM VwCompTceFuncionario tcfu "
        + " WHERE (TRUNC(tcfu.id.dataMes) = TRUNC(?)) ")
})
public class VwCompTceFuncionario implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "VwCompTceFuncionario.findAll".
     */
    public static final String FIND_ALL = "VwCompTceFuncionario.findAll";
    
    /** 
     * Constante para NamedQuery "VwCompTceFuncionario.findAllByDate".
     */
    public static final String FIND_ALL_BY_DATE = "VwCompTceFuncionario.findAllByDate";

    /**
     * Atributo gerado a partir da coluna TCFU_VL_TAXA.
     */
    @EmbeddedId
    @GeneratedValue(generator = "VwCompTceFuncionarioSeq")
    @SequenceGenerator(name = "VwCompTceFuncionarioSeq", 
            sequenceName = "SQ_TCFU_CD_PESSOA", allocationSize = 1)
    @AttributeOverrides({
            @AttributeOverride(name = "codigoPessoa", 
                    column = @Column(name = "TCFU_CD_PESSOA", nullable = false, precision = 18, scale = 0)),
            @AttributeOverride(name = "codigoLogin", 
                    column = @Column(name = "TCFU_CD_LOGIN", length = 15)),
            @AttributeOverride(name = "dataMes", 
                    column = @Column(name = "TCFU_DT_MES", length = 8)) })
    private VwCompTceFuncionarioId id;
    
    /** Atributo gerado a partir da coluna TCFU_SG_MOEDA. */
    @Column(name = "TCFU_SG_MOEDA", length = 5)
    private String siglaMoeda;

    /** Atributo gerado a partir da coluna TCFU_VL_SALARIO. */
    @Column(name = "TCFU_VL_SALARIO", precision = 22, scale = 0)
    private BigDecimal valorSalario;

    /** Atributo gerado a partir da coluna TCFU_VL_BENEFICIOS. */
    @Column(name = "TCFU_VL_BENEFICIOS", precision = 22, scale = 0)
    private BigDecimal valorBeneficios;

    /** Atributo gerado a partir da coluna TCFU_NR_HORAS_JORNADA. */
    @Column(name = "TCFU_NR_HORAS_JORNADA", precision = 22, scale = 0)
    private BigDecimal numeroHorasJornada;

    /** Atributo gerado a partir da coluna TCFU_VL_TCE. */
    @Column(name = "TCFU_VL_TCE", precision = 22, scale = 0)
    private BigDecimal valorTce;

    /** Atributo gerado a partir da coluna TCFU_CD_TIPO_CONTRATO. */
    @Column(name = "TCFU_CD_TIPO_CONTRATO", precision = 18, scale = 0)
    private Long codigoTipoContrato;

    /** Atributo gerado a partir da coluna TCFU_VL_TAXA. */
    @Column(name = "TCFU_VL_TAXA", precision = 22, scale = 0)
    private BigDecimal valorTaxa;

    /**
     * Construtor default.
     */
    public VwCompTceFuncionario() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param id Valor do atributo id;
     */
    public VwCompTceFuncionario(final VwCompTceFuncionarioId id) {
        this.id = id;
    }

    /**
     * Obtem o valor do atributo id.<BR>
     * @return Valor do atributo id.
     */
    public VwCompTceFuncionarioId getId() {
        return this.id;
    }

    /**
     * Atualiza o valor do atributo id.<BR>
     * @param id Novo valor para o atributo id.
     */
    public void setId(final VwCompTceFuncionarioId id) {
        this.id = id;
    }
    
    /**
     * Obtem o valor do atributo siglaMoeda.<BR>

     * @return Valor do atributo siglaMoeda.
     */
    public String getSiglaMoeda() {
        return this.siglaMoeda;
    }

    /**
     * Atualiza o valor do atributo siglaMoeda.<BR>

     * @param siglaMoeda Novo valor para o atributo siglaMoeda.
     */
    public void setSiglaMoeda(final String siglaMoeda) {
        this.siglaMoeda = siglaMoeda;
    }

    /**
     * Obtem o valor do atributo valorSalario.<BR>

     * @return Valor do atributo valorSalario.
     */
    public BigDecimal getValorSalario() {
        return this.valorSalario;
    }

    /**
     * Atualiza o valor do atributo valorSalario.<BR>

     * @param valorSalario Novo valor para o atributo valorSalario.
     */
    public void setValorSalario(final BigDecimal valorSalario) {
        this.valorSalario = valorSalario;
    }

    /**
     * Obtem o valor do atributo valorBeneficios.<BR>

     * @return Valor do atributo valorBeneficios.
     */
    public BigDecimal getValorBeneficios() {
        return this.valorBeneficios;
    }

    /**
     * Atualiza o valor do atributo valorBeneficios.<BR>

     * @param valorBeneficios Novo valor para o atributo valorBeneficios.
     */
    public void setValorBeneficios(final BigDecimal valorBeneficios) {
        this.valorBeneficios = valorBeneficios;
    }

    /**
     * Obtem o valor do atributo numeroHorasJornada.<BR>

     * @return Valor do atributo numeroHorasJornada.
     */
    public BigDecimal getNumeroHorasJornada() {
        return this.numeroHorasJornada;
    }

    /**
     * Atualiza o valor do atributo numeroHorasJornada.<BR>

     * @param numeroHorasJornada Novo valor para o atributo numeroHorasJornada.
     */
    public void setNumeroHorasJornada(final BigDecimal numeroHorasJornada) {
        this.numeroHorasJornada = numeroHorasJornada;
    }

    /**
     * Obtem o valor do atributo valorTce.<BR>

     * @return Valor do atributo valorTce.
     */
    public BigDecimal getValorTce() {
        return this.valorTce;
    }

    /**
     * Atualiza o valor do atributo valorTce.<BR>

     * @param valorTce Novo valor para o atributo valorTce.
     */
    public void setValorTce(final BigDecimal valorTce) {
        this.valorTce = valorTce;
    }

    /**
     * Obtem o valor do atributo codigoTipoContrato.<BR>

     * @return Valor do atributo codigoTipoContrato.
     */
    public Long getCodigoTipoContrato() {
        return this.codigoTipoContrato;
    }

    /**
     * Atualiza o valor do atributo codigoTipoContrato.<BR>

     * @param codigoTipoContrato Novo valor para o atributo codigoTipoContrato.
     */
    public void setCodigoTipoContrato(final Long codigoTipoContrato) {
        this.codigoTipoContrato = codigoTipoContrato;
    }

    /**
     * Obtem o valor do atributo valorTaxa.<BR>

     * @return Valor do atributo valorTaxa.
     */
    public BigDecimal getValorTaxa() {
        return this.valorTaxa;
    }

    /**
     * Atualiza o valor do atributo valorTaxa.<BR>

     * @param valorTaxa Novo valor para o atributo valorTaxa.
     */
    public void setValorTaxa(final BigDecimal valorTaxa) {
        this.valorTaxa = valorTaxa;
    }

    /**
     * @see Object#toString()
     * @return retorna a entidade no formato de string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}