/*
 * @(#) VwDealHrsFatFilter.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Entity gerado a partir da tabela VW_DEAL_HRS_FAT_FILTER.
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 21/10/2009 16:11:03
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VW_DEAL_HRS_FAT_FILTER")
@NamedQueries({
    
    @NamedQuery(name = "VwDealHrsFatFilter.findAll", query = "SELECT t FROM VwDealHrsFatFilter t"),
    
    @NamedQuery(name = "VwDealHrsFatFilter.findByFilter", query = "SELECT filter FROM VwDealHrsFatFilter filter "
        + " WHERE (filter.id.codigoNatureza  = ? OR ? = -1L) "
        + " AND (filter.id.codigoCentroLucro = ? OR ? = -1L) "
        + " AND (filter.id.codigoPratica     = ? OR ? = -1L) "
        + " AND (filter.id.codigoCliente     = ? OR ? = -1L) "
        + " AND (filter.id.indicadorVersao   = ? OR ? is null) "
        + " AND (TRUNC(filter.id.dataMes)    = TRUNC(?) OR filter.id.dataMes = ?) "
    )
    
})
public class VwDealHrsFatFilter implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================
    
    /** Constante para NamedQuery "VwDealHrsFatFilter.findByFilter". */
    public static final String FIND_BY_FILTER = "VwDealHrsFatFilter.findByFilter";
    
    // ========================================================================
    // END
    // ========================================================================
    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "VwDealHrsFatFilter.findAll".
     */
    public static final String FIND_ALL = "VwDealHrsFatFilter.findAll";

    /**
     * Atributo gerado a partir da coluna HOFD_IN_VERSAO.
     */
    @EmbeddedId
    @GeneratedValue(generator = "VwDealHrsFatFilterSeq")
    @SequenceGenerator(name = "VwDealHrsFatFilterSeq", sequenceName = "SQ_DEAL_CD_DEAL", allocationSize = 1)
    @AttributeOverrides({
            @AttributeOverride(name = "codigoDeal", 
                    column = @Column(name = "DEAL_CD_DEAL", nullable = false, precision = 18, scale = 0)),
            @AttributeOverride(name = "nomeDeal", 
                    column = @Column(name = "DEAL_NM_DEAL", length = 240)),
            @AttributeOverride(name = "codigoHorasFatDeal", 
                    column = @Column(name = "HOFD_CD_HORAS_FAT_DEAL", precision = 18, scale = 0)),
            @AttributeOverride(name = "dataMes", column = @Column(name = "HOFD_DT_MES", length = 7)),
            @AttributeOverride(name = "codigoCliente", 
                    column = @Column(name = "CLIE_CD_CLIENTE", precision = 18, scale = 0)),
            @AttributeOverride(name = "nomeCliente", column = @Column(name = "CLIE_NM_CLIENTE", length = 100)),
            @AttributeOverride(name = "codigoNatureza", 
                    column = @Column(name = "NACL_CD_NATUREZA", precision = 18, scale = 0)),
            @AttributeOverride(name = "codigoCentroLucro", 
                    column = @Column(name = "CELU_CD_CENTRO_LUCRO", precision = 18, scale = 0)),
            @AttributeOverride(name = "nomeContratoPratica", 
                    column = @Column(name = "COPR_NM_CONTRATO_PRATICA", length = 240)),
            @AttributeOverride(name = "codigoPratica", 
                    column = @Column(name = "PRAT_CD_PRATICA", precision = 18, scale = 0)),
            @AttributeOverride(name = "nomeCentroLucro", 
                    column = @Column(name = "CELU_NM_CENTRO_LUCRO", length = 100)),
            @AttributeOverride(name = "nomePratica", 
                    column = @Column(name = "PRAT_NM_PRATICA", length = 100)),
            @AttributeOverride(name = "nomeNatureza", 
                    column = @Column(name = "NACL_NM_NATUREZA", length = 100)),
            @AttributeOverride(name = "indicadorVersao", 
                    column = @Column(name = "HOFD_IN_VERSAO", length = 2)) })
    private VwDealHrsFatFilterId id;

    /** Valor da receita total. Este valor NÃO vem do banco,
     *  é calculado pela aplicação. */
    @Transient
    private Double valorReceita;
    
    /** Indicador do padrão para exibição de valores 
     * de moeda. Este valor NÃO vem do banco. */
    @Transient
    private String patternCurrency = "";
    
    /**
     * Construtor default.
     */
    public VwDealHrsFatFilter() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param id Valor do atributo id;
     */
    public VwDealHrsFatFilter(final VwDealHrsFatFilterId id) {
        this.id = id;
    }

    /**
     * Obtem o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna HOFD_IN_VERSAO.
     * @return Valor do atributo id.
     */
    public VwDealHrsFatFilterId getId() {
        return this.id;
    }

    /**
     * Atualiza o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna HOFD_IN_VERSAO.
     * @param id Novo valor para o atributo id.
     */
    public void setId(final VwDealHrsFatFilterId id) {
        this.id = id;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna o objeto no formato de string.
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    /**
     * @param valorReceita the valorReceita to set
     */
    public void setValorReceita(final Double valorReceita) {
        this.valorReceita = valorReceita;
    }

    /**
     * @return the valorReceita
     */
    public Double getValorReceita() {
        return valorReceita;
    }

    /**
     * @return the patternCurrency
     */
    public String getPatternCurrency() {
        return patternCurrency + " ";
    }

    /**
     * @param patternCurrency the patternCurrency to set
     */
    public void setPatternCurrency(final String patternCurrency) {
        this.patternCurrency = patternCurrency;
    }

}
