/*
 * @(#) VwEstratificacaoUrResultado.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela VW_ESTRATIFICACAO_UR_RESULTADO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 19/08/2011 11:47:09
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VW_ESTRATIFICACAO_UR_RESULTADO")
@NamedQueries({
        @NamedQuery(name = "VwEstratificacaoUrResultado.findAll", query = "SELECT t FROM VwEstratificacaoUrResultado t"),

        @NamedQuery(name = "VwEstratificacaoUrResultado.findByContratoPraticaAndDataMes", query = "SELECT t FROM VwEstratificacaoUrResultado t "
                + " WHERE t.id.codigoContratoPratica = ? "
                + " AND TRUNC(t.id.dataMes) = TRUNC(?) ")})
public class VwEstratificacaoUrResultado implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "VwEstratificacaoUrResultado.findAll".
     */
    public static final String FIND_ALL = "VwEstratificacaoUrResultado.findAll";

    /**
     * Constante para NamedQuery
     * "VwEstratificacaoUrResultado.findByContratoPraticaAndDataMes".
     */
    public static final String FIND_BY_CONTRATO_PRATICA_AND_DATA_MES =
            "VwEstratificacaoUrResultado.findByContratoPraticaAndDataMes";

    /**
     * Atributo gerado a partir da coluna ESUR_IN_INCONSISTENTE.
     */
    @EmbeddedId
    @GeneratedValue(generator = "VwEstratificacaoUrResultadoSeq")
    @SequenceGenerator(name = "VwEstratificacaoUrResultadoSeq", sequenceName = "SQ_ESUR_CD_CONTRATO_PRATICA", allocationSize = 1)
    @AttributeOverrides({
            @AttributeOverride(name = "codigoContratoPratica", column = @Column(name = "ESUR_CD_CONTRATO_PRATICA", precision = 18, scale = 0)),
            @AttributeOverride(name = "dataMes", column = @Column(name = "ESUR_DT_MES", length = 7)),
            @AttributeOverride(name = "codigoPessoa", column = @Column(name = "ESUR_CD_PESSOA", precision = 18, scale = 0)),
            @AttributeOverride(name = "codigoLogin", column = @Column(name = "ESUR_CD_LOGIN", length = 20))})
    private VwEstratificacaoUrResultadoId id;

    /**
     * Atributo valorTotalAlocado.
     */
    @Column(name = "ESUR_VL_TOTAL_ALOCADO", precision = 22, scale = 0)
    private BigDecimal valorTotalAlocado;

    /**
     * Atributo valorTotalReceitado.
     */
    @Column(name = "ESUR_VL_TOTAL_RECEITADO", precision = 22, scale = 0)
    private BigDecimal valorTotalReceitado;

    /**
     * Atributo valorDiferencaReal.
     */
    @Column(name = "ESUR_VL_DIFERENCA_REAL", precision = 22, scale = 0)
    private BigDecimal valorDiferencaReal;

    /**
     * Atributo valorDiferencaReview.
     */
    @Column(name = "ESUR_VL_DIFERENCA_REVIEW", precision = 22, scale = 0)
    private BigDecimal valorDiferencaReview;

    /**
     * Atributo indicadorInconsistente.
     */
    @Column(name = "ESUR_IN_INCONSISTENTE", length = 1)
    private Character indicadorInconsistente;

    /**
     * Atributo indicadorDiferencaRealNeg.
     */
    @Column(name = "ESUR_IN_DIFERENCA_REAL_NEG", length = 1)
    private Character indicadorDiferencaRealNeg;

    /**
     * Atributo indicadorNaoDefinido.
     */
    @Column(name = "ESUR_IN_NAO_DEFINIDO", length = 1)
    private Character indicadorNaoDefinido;

    /**
     * Atributo codigoMotivoDesvio.
     */
    @Column(name = "ESUR_CD_MOTIVO_DESVIO", precision = 18, scale = 0)
    private Long codigoMotivoDesvio;

    /**
     * Atributo codigoEstratificacaoUr.
     */
    @Column(name = "ESUR_CD_ESTRATIFICACAO_UR", precision = 22, scale = 0)
    private BigDecimal codigoEstratificacaoUr;

    /**
     * Atributo codigoItemEstratUr.
     */
    @Column(name = "ESUR_CD_ITEM_ESTRAT_UR", precision = 18, scale = 0)
    private Long codigoItemEstratUr;

    /**
     * Construtor default.
     */
    public VwEstratificacaoUrResultado() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param id
     *            Valor do atributo id;
     */
    public VwEstratificacaoUrResultado(final VwEstratificacaoUrResultadoId id) {
        this.id = id;
    }

    /**
     * Obtem o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna ESUR_IN_INCONSISTENTE.
     * 
     * @return Valor do atributo id.
     */
    public VwEstratificacaoUrResultadoId getId() {
        return this.id;
    }

    /**
     * Atualiza o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna ESUR_IN_INCONSISTENTE.
     * 
     * @param id
     *            Novo valor para o atributo id.
     */
    public void setId(final VwEstratificacaoUrResultadoId id) {
        this.id = id;
    }

    /**
     * @return the valorTotalAlocado
     */
    public BigDecimal getValorTotalAlocado() {
        return valorTotalAlocado;
    }

    /**
     * @param valorTotalAlocado
     *            the valorTotalAlocado to set
     */
    public void setValorTotalAlocado(final BigDecimal valorTotalAlocado) {
        this.valorTotalAlocado = valorTotalAlocado;
    }

    /**
     * @return the valorTotalReceitado
     */
    public BigDecimal getValorTotalReceitado() {
        return valorTotalReceitado;
    }

    /**
     * @param valorTotalReceitado
     *            the valorTotalReceitado to set
     */
    public void setValorTotalReceitado(final BigDecimal valorTotalReceitado) {
        this.valorTotalReceitado = valorTotalReceitado;
    }

    /**
     * @return the valorDiferencaReal
     */
    public BigDecimal getValorDiferencaReal() {
        return valorDiferencaReal;
    }

    /**
     * @param valorDiferencaReal
     *            the valorDiferencaReal to set
     */
    public void setValorDiferencaReal(final BigDecimal valorDiferencaReal) {
        this.valorDiferencaReal = valorDiferencaReal;
    }

    /**
     * @return the valorDiferencaReview
     */
    public BigDecimal getValorDiferencaReview() {
        return valorDiferencaReview;
    }

    /**
     * @param valorDiferencaReview
     *            the valorDiferencaReview to set
     */
    public void setValorDiferencaReview(final BigDecimal valorDiferencaReview) {
        this.valorDiferencaReview = valorDiferencaReview;
    }

    /**
     * @return the indicadorInconsistente
     */
    public Character getIndicadorInconsistente() {
        return indicadorInconsistente;
    }

    /**
     * @param indicadorInconsistente
     *            the indicadorInconsistente to set
     */
    public void setIndicadorInconsistente(final Character indicadorInconsistente) {
        this.indicadorInconsistente = indicadorInconsistente;
    }

    /**
     * @return the indicadorDiferencaRealNeg
     */
    public Character getIndicadorDiferencaRealNeg() {
        return indicadorDiferencaRealNeg;
    }

    /**
     * @param indicadorDiferencaRealNeg
     *            the indicadorDiferencaRealNeg to set
     */
    public void setIndicadorDiferencaRealNeg(
            final Character indicadorDiferencaRealNeg) {
        this.indicadorDiferencaRealNeg = indicadorDiferencaRealNeg;
    }

    /**
     * @return the indicadorNaoDefinido
     */
    public Character getIndicadorNaoDefinido() {
        return indicadorNaoDefinido;
    }

    /**
     * @param indicadorNaoDefinido
     *            the indicadorNaoDefinido to set
     */
    public void setIndicadorNaoDefinido(final Character indicadorNaoDefinido) {
        this.indicadorNaoDefinido = indicadorNaoDefinido;
    }

    /**
     * @return the codigoMotivoDesvio
     */
    public Long getCodigoMotivoDesvio() {
        return codigoMotivoDesvio;
    }

    /**
     * @param codigoMotivoDesvio
     *            the codigoMotivoDesvio to set
     */
    public void setCodigoMotivoDesvio(final Long codigoMotivoDesvio) {
        this.codigoMotivoDesvio = codigoMotivoDesvio;
    }

    /**
     * @return the codigoEstratificacaoUr
     */
    public BigDecimal getCodigoEstratificacaoUr() {
        return codigoEstratificacaoUr;
    }

    /**
     * @param codigoEstratificacaoUr
     *            the codigoEstratificacaoUr to set
     */
    public void setCodigoEstratificacaoUr(
            final BigDecimal codigoEstratificacaoUr) {
        this.codigoEstratificacaoUr = codigoEstratificacaoUr;
    }

    /**
     * @return the codigoItemEstratUr
     */
    public Long getCodigoItemEstratUr() {
        return codigoItemEstratUr;
    }

    /**
     * @param codigoItemEstratUr
     *            the codigoItemEstratUr to set
     */
    public void setCodigoItemEstratUr(final Long codigoItemEstratUr) {
        this.codigoItemEstratUr = codigoItemEstratUr;
    }

    /**
     * @see Object#toString()
     * @return string
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
