/*
 * @(#) VwFiscalBalance.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import com.ciandt.pms.model.vo.DealFiscalFiscalBalanceRow;

/**
 * Entity gerado a partir da tabela VW_FISCAL_BALANCE.
 * 
 * @author Generated by Hibernate Tools 3.4.0.CR1
 * @since Jun 26, 2014 6:22:36 PM
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VW_FISCAL_BALANCE_ACUMULADO")
@NamedQueries({
		@NamedQuery(name = "VwFiscalBalanceAcumulado.findAll", query = "SELECT t FROM VwFiscalBalanceAcumulado t"),

		@NamedQuery(name = "VwFiscalBalanceAcumulado.findAllByDealFiscal", query = "SELECT t FROM VwFiscalBalanceAcumulado t "
				+ " WHERE t.dealFiscal.codigoDealFiscal = :codigoFiscalDeal "),

		@NamedQuery(name = "VwFiscalBalanceAcumulado.findByMsaAndCliente", query = "SELECT t FROM VwFiscalBalanceAcumulado t "
				+ "WHERE (t.msa.codigoMsa = :codigoMsa OR :codigoMsa is null) "
				+ "AND (t.cliente.codigoCliente = :codigoCliente OR :codigoCliente is null) "),

		@NamedQuery(name = "VwFiscalBalanceAcumulado.findByDealFiscalAndPeriod", query = "SELECT t FROM VwFiscalBalanceAcumulado t "
				+ "WHERE t.dealFiscal.codigoDealFiscal = :codigoDealFiscal "
				+ "AND ((t.dataMes >= :startDate) OR (:startDate IS NULL)) "
				+ "AND ((t.dataMes <= :endDate) OR (:endDate IS NULL)) "),

		@NamedQuery(name = "VwFiscalBalanceAcumulado.findByDealFiscalAndStartDate", query = "SELECT t FROM VwFiscalBalanceAcumulado t "
				+ "WHERE t.dealFiscal.codigoDealFiscal = :codigoDealFiscal "
				+ "AND ((t.dataMes >= :startDate) OR (:startDate IS NULL)) "),

		@NamedQuery(name = "VwFiscalBalanceAcumulado.findPublishedFiscalBalanceByDealFiscal", query = "SELECT SUM(f.totalInvoice) - SUM(f.totalRevenue) AS total_balance "
				+ "FROM VwFiscalBalanceAcumulado f "
				+ "WHERE f.dealFiscal.codigoDealFiscal = :codigoDealFiscal")

})

public class VwFiscalBalanceAcumulado implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "VwFiscalBalanceAcumulado.findAll".
	 */
	public static final String FIND_ALL = "VwFiscalBalanceAcumulado.findAll";

	/**
	 * Constante para NamedQuery "VwFiscalBalanceAcumulado.findAllByMsaAndDealFiscal".
	 */
	public static final String FIND_ALL_BY_DEAL_FISCAL = "VwFiscalBalanceAcumulado.findAllByDealFiscal";
	
	/**
	 * Constante para NamedQuery "VwFiscalBalanceAcumulado.findByMsaAndCliente".
	 */
	public static final String FIND_BY_MSA_AND_CLIENTE = "VwFiscalBalanceAcumulado.findByMsaAndCliente";
	
	/**
	 * Constante para NamedQuery "VwFiscalBalanceAcumulado.findByMsaAndCliente".
	 */
	public static final String FIND_ALL_BY_DEAL_FISCAL_AND_PERIOD = "VwFiscalBalanceAcumulado.findByDealFiscalAndPeriod";
	
	/**
	 * Constante para NamedQuery "VwFiscalBalanceAcumulado.findByDealFiscalAndStartDate".
	 */
	public static final String FIND_BY_DEAL_FISCAL_AND_STARTDATE = "VwFiscalBalanceAcumulado.findByDealFiscalAndStartDate";
	
	/**
	 * Constante para NamedQuery "VwFiscalBalanceAcumulado.findPublishedFiscalBalanceByDealFiscal".
	 */
	public static final String FIND_PUBLICSHED_FISCAL_BALANCE_BY_DEAL_FISCAL = "VwFiscalBalanceAcumulado.findPublishedFiscalBalanceByDealFiscal";

	/**
	 * Id fake "construido" na view.
	 */
	@Id
	@Column(name = "CD_DFISCAL_ACUMULADO", precision = 22, scale = 0)
	private Long codigoFiscalBalanceAcumulado;

	@Column(name = "DT_MES", length = 7)
	private Date dataMes;

	/**
	 * Campo indica se o objecto representa uma Receita ou uma Fatura
	 */
	@Column(name = "FONTE")
	private String fonte;

	@Column(name = "VL_TOTAL_REVENUE", precision = 22, scale = 0)
	private Double totalRevenue;

	@Column(name = "VL_TOTAL_INVOICED", precision = 22, scale = 0)
	private Double totalInvoice;
	
	/**
	 * Atributo gerado a partir da coluna CD_FISCAL_DEAL.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CD_FISCAL_DEAL", nullable = false)
	private DealFiscal dealFiscal;

	/**
	 * Atributo gerado a partir da coluna MSAA_CD_MSA.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSAA_CD_MSA", nullable = false)
	private Msa msa;
	
	/**
	 * Atributo gerado a partir da coluna CLIE_CD_CLIENTE.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIE_CD_CLIENTE", nullable = false)
	private Cliente cliente;

	public Long getCodigoFiscalBalanceAcumulado() {
		return codigoFiscalBalanceAcumulado;
	}

	public void setCodigoFiscalBalanceAcumulado(
			Long codigoFiscalBalanceAcumulado) {
		this.codigoFiscalBalanceAcumulado = codigoFiscalBalanceAcumulado;
	}

	public Date getDataMes() {
		return dataMes;
	}

	public void setDataMes(Date dataMes) {
		this.dataMes = dataMes;
	}

	/**
	 * @return the fonte
	 */
	public String getFonte() {
		return fonte;
	}

	/**
	 * @param fonte the fonte to set
	 */
	public void setFonte(String fonte) {
		this.fonte = fonte;
	}

	public Double getTotalRevenue() {
		return totalRevenue;
	}

	public void setTotalRevenue(Double totalRevenue) {
		this.totalRevenue = totalRevenue;
	}

	public Double getTotalInvoice() {
		return totalInvoice;
	}

	public void setTotalInvoice(Double totalInvoice) {
		this.totalInvoice = totalInvoice;
	}

	/**
	 * Retorna o balance totalRevenue - totalInvoice.
	 * 
	 * @return Double
	 */
	public Double getBalance() {
		return this.totalRevenue - this.totalInvoice;
	}

	/**
	 * @return the msa
	 */
	public Msa getMsa() {
		return msa;
	}

	/**
	 * @param msa the msa to set
	 */
	public void setMsa(Msa msa) {
		this.msa = msa;
	}

	/**
	 * @return the dealFiscal
	 */
	public DealFiscal getDealFiscal() {
		return dealFiscal;
	}

	/**
	 * @param dealFiscal the dealFiscal to set
	 */
	public void setDealFiscal(DealFiscal dealFiscal) {
		this.dealFiscal = dealFiscal;
	}

	/**
	 * @return the cliente
	 */
	public Cliente getCliente() {
		return cliente;
	}

	/**
	 * @param cliente the cliente to set
	 */
	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	/**
	 * Converte o objeto para um {@link DealFiscalFiscalBalanceRow}.
	 * 
	 * @return {@link DealFiscalFiscalBalanceRow}
	 */
	public DealFiscalFiscalBalanceRow toDealFiscalFiscalBalanceRow() {
		DealFiscalFiscalBalanceRow d = new DealFiscalFiscalBalanceRow();

		d.setMoeda(this.dealFiscal.getMoeda());
		d.setBalanceDate(this.dataMes);
		d.setTotalInvoiced(this.totalInvoice);
		d.setTotalRevenue(this.totalRevenue);
		d.setPublishedFiscalBalance(this.getBalance());

		return d;
	}
}