/*
 * @(#) VwHrsCargoId.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwHrsCargoId generated by hbm2java
 *
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 20/06/2012 16:01:38
 * @version 09/01/19 1.1 10:08:00
 */
@Embeddable
public class VwHrsCargoId implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /** 
     * Constante para NamedQuery "VwHrsCargoId.findAll".
     */
    public static final String FIND_ALL = "VwHrsCargoId.findAll";

    @Column(name = "CARG_CD_CARGO", nullable = false, precision = 18, scale = 0)
    private Long codigoCargo;

    @Column(name = "CARG_NM_CARGO", length = 200)
    private String nomeCargo;

    @Column(name = "CARG_IN_ATIVO", length = 1)
    private String indicadorAtivo;

    /**
     * Construtor default.
     */
    public VwHrsCargoId() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoCargo Valor do atributo codigoCargo;
     */
    public VwHrsCargoId(Long codigoCargo) {
        this.codigoCargo = codigoCargo;
    }

    /**
     * Construtor com preenchimento da entidade.
     * @param codigoCargo Valor do atributo codigoCargo;
     * @param nomeCargo Valor do atributo nomeCargo;
     * @param indicadorAtivo Valor do atributo indicadorAtivo;
     */
    public VwHrsCargoId(Long codigoCargo, String nomeCargo,
            String indicadorAtivo) {
        this.codigoCargo = codigoCargo;
        this.nomeCargo = nomeCargo;
        this.indicadorAtivo = indicadorAtivo;
    }

    /**
     * Obtem o valor do atributo codigoCargo.<BR>

     * @return Valor do atributo codigoCargo.
     */
    public Long getCodigoCargo() {
        return this.codigoCargo;
    }

    /**
     * Atualiza o valor do atributo codigoCargo.<BR>

     * @param codigoCargo Novo valor para o atributo codigoCargo.
     */
    public void setCodigoCargo(final Long codigoCargo) {
        this.codigoCargo = codigoCargo;
    }

    /**
     * Obtem o valor do atributo nomeCargo.<BR>

     * @return Valor do atributo nomeCargo.
     */
    public String getNomeCargo() {
        return this.nomeCargo;
    }

    /**
     * Atualiza o valor do atributo nomeCargo.<BR>

     * @param nomeCargo Novo valor para o atributo nomeCargo.
     */
    public void setNomeCargo(final String nomeCargo) {
        this.nomeCargo = nomeCargo;
    }

    /**
     * Obtem o valor do atributo indicadorAtivo.<BR>

     * @return Valor do atributo indicadorAtivo.
     */
    public String getIndicadorAtivo() {
        return this.indicadorAtivo;
    }

    /**
     * Atualiza o valor do atributo indicadorAtivo.<BR>

     * @param indicadorAtivo Novo valor para o atributo indicadorAtivo.
     */
    public void setIndicadorAtivo(final String indicadorAtivo) {
        this.indicadorAtivo = indicadorAtivo;
    }

    /**
     * @see Object#equals(Object)
     */
    @Override
    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof VwHrsCargoId))
            return false;
        VwHrsCargoId castOther = (VwHrsCargoId) other;

        return ((this.getCodigoCargo() == castOther.getCodigoCargo()) || (this
                .getCodigoCargo() != null
                && castOther.getCodigoCargo() != null && this.getCodigoCargo()
                .equals(castOther.getCodigoCargo())))
                && ((this.getNomeCargo() == castOther.getNomeCargo()) || (this
                        .getNomeCargo() != null
                        && castOther.getNomeCargo() != null && this
                        .getNomeCargo().equals(castOther.getNomeCargo())))
                && ((this.getIndicadorAtivo() == castOther.getIndicadorAtivo()) || (this
                        .getIndicadorAtivo() != null
                        && castOther.getIndicadorAtivo() != null && this
                        .getIndicadorAtivo().equals(
                                castOther.getIndicadorAtivo())));
    }

    /**
     * @see Object#hashCode()
     */
    @Override
    public int hashCode() {
        int result = 17;

        result =
                37
                        * result
                        + (getCodigoCargo() == null ? 0 : this.getCodigoCargo()
                                .hashCode());
        result =
                37
                        * result
                        + (getNomeCargo() == null ? 0 : this.getNomeCargo()
                                .hashCode());
        result =
                37
                        * result
                        + (getIndicadorAtivo() == null ? 0 : this
                                .getIndicadorAtivo().hashCode());
        return result;
    }

}
