/*
 * @(#) VwHrsCargo.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela VW_HRS_CARGO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 20/06/2012 16:01:38
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VW_HRS_CARGO")
@NamedQueries({
        @NamedQuery(name = "VwHrsCargo.findAll", query = "SELECT t FROM VwHrsCargo t"),
        @NamedQuery(name = "VwHrsCargo.findByName", query = "SELECT t FROM VwHrsCargo t WHERE t.id.nomeCargo = ?"),
        @NamedQuery(name = "VwHrsCargo.findByCodigo", query = "SELECT t FROM VwHrsCargo t WHERE t.id.codigoCargo = ?"),
        @NamedQuery(name = "VwHrsCargo.findAllActive", query = "SELECT t FROM VwHrsCargo t WHERE t.id.indicadorAtivo = 'S' " 
                    +   "ORDER BY t.id.nomeCargo")
})
public class VwHrsCargo implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "VwHrsCargo.findAll".
     */
    public static final String FIND_ALL = "VwHrsCargo.findAll";

    /**
     * Constante para NamedQuery "VwHrsCargo.findByName".
     */
    public static final String FIND_BY_NAME = "VwHrsCargo.findByName";

    /**
     * Constante para NamedQuery "VwHrsCargo.findByCodigo".
     */
    public static final String FIND_BY_CODIGO = "VwHrsCargo.findByCodigo";
    
    /**
     * Constante para NamedQuery.
     */
    public static final String FIND_ALL_ACTVE = "VwHrsCargo.findAllActive";

    /**
     * Atributo gerado a partir da coluna CARG_IN_ATIVO.
     */
    @EmbeddedId
    @GeneratedValue(generator = "VwHrsCargoSeq")
    @SequenceGenerator(name = "VwHrsCargoSeq", sequenceName = "SQ_CARG_CD_CARGO", allocationSize = 1)
    @AttributeOverrides({
            @AttributeOverride(name = "codigoCargo", column = @Column(name = "CARG_CD_CARGO", nullable = false, precision = 18, scale = 0)),
            @AttributeOverride(name = "nomeCargo", column = @Column(name = "CARG_NM_CARGO", length = 200)),
            @AttributeOverride(name = "indicadorAtivo", column = @Column(name = "CARG_IN_ATIVO", length = 1))})
    private VwHrsCargoId id;    

    /**
     * Construtor default.
     */
    public VwHrsCargo() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param id
     *            Valor do atributo id;
     */
    public VwHrsCargo(final VwHrsCargoId id) {
        this.id = id;
    }

    /**
     * Obtem o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna CARG_IN_ATIVO.
     * 
     * @return Valor do atributo id.
     */
    public VwHrsCargoId getId() {
        return this.id;
    }

    /**
     * Atualiza o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna CARG_IN_ATIVO.
     * 
     * @param id
     *            Novo valor para o atributo id.
     */
    public void setId(final VwHrsCargoId id) {
        this.id = id;
    }

    /**
     * @see Object#toString()
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }


    
    

}
