/*
 * @(#) VwItemReceitaId.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwItemReceitaId generated by hbm2java.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 28/12/2009 10:06:13
 * @version 09/01/19 1.1 10:08:00
 */
@Embeddable
public class VwItemReceitaId implements java.io.Serializable {

    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "VwItemReceitaId.findAll".
     */
    public static final String FIND_ALL = "VwItemReceitaId.findAll";

    /**
     * Atributo gerado a partir da coluna PESS_CD_PESSOA.
     */
    @Column(name = "PESS_CD_PESSOA", precision = 18, scale = 0)
    private Long codigoPessoa;

    /**
     * Atributo gerado a partir da coluna ALPE_PR_ALOCACAO_PERIODO.
     */
    @Column(name = "ALPE_PR_ALOCACAO_PERIODO", precision = 5)
    private BigDecimal percentualAlocacaoPeriodo;

    /**
     * Atributo gerado a partir da coluna PEVE_CD_PERFIL_VENDIDO.
     */
    @Column(name = "PEVE_CD_PERFIL_VENDIDO", nullable = false, precision = 18, scale = 0)
    private Long codigoPerfilVendido;

    /**
     * Atributo gerado a partir da coluna PEVE_VL_PERFIL_VENDIDO.
     */
    @Column(name = "PEVE_VL_PERFIL_VENDIDO", precision = 22, scale = 0)
    private BigDecimal valorPerfilVendido;

    /**
     * Atributo gerado a partir da coluna ALPE_DT_ALOCACAO_PERIODO.
     */
    @Column(name = "ALPE_DT_ALOCACAO_PERIODO", length = 8)
    private Date dataAlocacaoPeriodo;
    
    /**
     * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA.
     */
    @Column(name = "COPR_CD_CONTRATO_PRATICA", precision = 18, scale = 0)
    private Long codigoContratoPratica;
    
    /**
     * Atributo gerado a partir da coluna ALOC_CD_ALOCACAO.
     */
    @Column(name = "ALOC_CD_ALOCACAO", nullable = false, precision = 18, scale = 0)
    private Long codigoAlocacao;

    /**
     * Atributo gerado a partir da coluna ITRE_PER_DESPESA.
     */
    @Column(name = "ITRE_PER_DESPESA", precision = 15)
    private BigDecimal percentualDespesa;

    /**
     * Construtor default.
     */
    public VwItemReceitaId() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param codigoPessoa
     *            Valor do atributo codigoPessoa;
     * @param percentualAlocacaoPeriodo
     *            Valor do atributo percentualAlocacaoPeriodo;
     * @param codigoPerfilVendido
     *            Valor do atributo codigoPerfilVendido;
     * @param valorPerfilVendido
     *            Valor do atributo valorPerfilVendido;
     * @param dataAlocacaoPeriodo
     *            Valor do atributo dataAlocacaoPeriodo;
     * @param codigoContratoPratica
     *            Valor do atributo codigoContratoPratica;
     * @param codigoAlocacao
     *            Valor do atributo codigoAlocacao;
     */
    public VwItemReceitaId(final Long codigoPessoa,
            final BigDecimal percentualAlocacaoPeriodo,
            final Long codigoPerfilVendido,
            final BigDecimal valorPerfilVendido, final Date dataAlocacaoPeriodo,
            final Long codigoContratoPratica, final Long codigoAlocacao) {
        this.codigoPessoa = codigoPessoa;
        this.percentualAlocacaoPeriodo = percentualAlocacaoPeriodo;
        this.codigoPerfilVendido = codigoPerfilVendido;
        this.valorPerfilVendido = valorPerfilVendido;
        this.dataAlocacaoPeriodo = dataAlocacaoPeriodo;
        this.codigoContratoPratica = codigoContratoPratica;
        this.codigoAlocacao = codigoAlocacao;
    }

    /**
     * Obtem o valor do atributo codigoPessoa.<BR>
     * 
     * @return Valor do atributo codigoPessoa.
     */
    public Long getCodigoPessoa() {
        return this.codigoPessoa;
    }

    /**
     * Atualiza o valor do atributo codigoPessoa.<BR>
     * 
     * @param codigoPessoa
     *            Novo valor para o atributo codigoPessoa.
     */
    public void setCodigoPessoa(final Long codigoPessoa) {
        this.codigoPessoa = codigoPessoa;
    }

    /**
     * Obtem o valor do atributo percentualAlocacaoPeriodo.<BR>
     * 
     * @return Valor do atributo percentualAlocacaoPeriodo.
     */
    public BigDecimal getPercentualAlocacaoPeriodo() {
        return this.percentualAlocacaoPeriodo;
    }

    /**
     * Atualiza o valor do atributo percentualAlocacaoPeriodo.<BR>
     * 
     * @param percentualAlocacaoPeriodo
     *            Novo valor para o atributo percentualAlocacaoPeriodo.
     */
    public void setPercentualAlocacaoPeriodo(
            final BigDecimal percentualAlocacaoPeriodo) {
        this.percentualAlocacaoPeriodo = percentualAlocacaoPeriodo;
    }

    /**
     * Obtem o valor do atributo codigoPerfilVendido.<BR>
     * 
     * @return Valor do atributo codigoPerfilVendido.
     */
    public Long getCodigoPerfilVendido() {
        return this.codigoPerfilVendido;
    }

    /**
     * Atualiza o valor do atributo codigoPerfilVendido.<BR>
     * 
     * @param codigoPerfilVendido
     *            Novo valor para o atributo codigoPerfilVendido.
     */
    public void setCodigoPerfilVendido(final Long codigoPerfilVendido) {
        this.codigoPerfilVendido = codigoPerfilVendido;
    }

    /**
     * Obtem o valor do atributo valorPerfilVendido.<BR>
     * 
     * @return Valor do atributo valorPerfilVendido.
     */
    public BigDecimal getValorPerfilVendido() {
        return this.valorPerfilVendido;
    }

    /**
     * Atualiza o valor do atributo valorPerfilVendido.<BR>
     * 
     * @param valorPerfilVendido
     *            Novo valor para o atributo valorPerfilVendido.
     */
    public void setValorPerfilVendido(final BigDecimal valorPerfilVendido) {
        this.valorPerfilVendido = valorPerfilVendido;
    }

    /**
     * Obtem o valor do atributo dataAlocacaoPeriodo.<BR>
     * 
     * @return Valor do atributo dataAlocacaoPeriodo.
     */
    public Date getDataAlocacaoPeriodo() {
        return this.dataAlocacaoPeriodo;
    }

    /**
     * Atualiza o valor do atributo dataAlocacaoPeriodo.<BR>
     * 
     * @param dataAlocacaoPeriodo
     *            Novo valor para o atributo dataAlocacaoPeriodo.
     */
    public void setDataAlocacaoPeriodo(final Date dataAlocacaoPeriodo) {
        this.dataAlocacaoPeriodo = dataAlocacaoPeriodo;
    }
    
    /**
     * Obtem o valor do atributo codigoContratoPratica.<BR>

     * @return Valor do atributo codigoContratoPratica.
     */
    public Long getCodigoContratoPratica() {
        return this.codigoContratoPratica;
    }

    /**
     * Atualiza o valor do atributo codigoContratoPratica.<BR>

     * @param codigoContratoPratica Novo valor para o atributo codigoContratoPratica.
     */
    public void setCodigoContratoPratica(final Long codigoContratoPratica) {
        this.codigoContratoPratica = codigoContratoPratica;
    }
    
    /**
     * Obtem o valor do atributo codigoAlocacao.<BR>

     * @return Valor do atributo codigoAlocacao.
     */
    public Long getCodigoAlocacao() {
        return this.codigoAlocacao;
    }

    /**
     * Atualiza o valor do atributo codigoAlocacao.<BR>

     * @param codigoAlocacao Novo valor para o atributo codigoAlocacao.
     */
    public void setCodigoAlocacao(final Long codigoAlocacao) {
        this.codigoAlocacao = codigoAlocacao;
    }
    
    

    /**
	 * @return the percentualDespesa
	 */
	public BigDecimal getPercentualDespesa() {
		return percentualDespesa;
	}

	/**
	 * @param percentualDespesa the percentualDespesa to set
	 */
	public void setPercentualDespesa(BigDecimal percentualDespesa) {
		this.percentualDespesa = percentualDespesa;
	}

	/**
     * @see Object#equals(Object)
     * 
     * @param other
     *            Valor do atributo other;
     * @return true se os objetos sao iguais, caso contrário retorna false
     */
    @Override
    public boolean equals(final Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof VwItemReceitaId)) {
            return false;
        }
        VwItemReceitaId castOther = (VwItemReceitaId) other;

        return ((this.getCodigoPessoa() == castOther.getCodigoPessoa()) || (this
                .getCodigoPessoa() != null
                && castOther.getCodigoPessoa() != null && this
                .getCodigoPessoa().equals(castOther.getCodigoPessoa())))
                && ((this.getPercentualAlocacaoPeriodo() == castOther
                        .getPercentualAlocacaoPeriodo()) || (this
                        .getPercentualAlocacaoPeriodo() != null
                        && castOther.getPercentualAlocacaoPeriodo() != null && this
                        .getPercentualAlocacaoPeriodo().equals(
                                castOther.getPercentualAlocacaoPeriodo())))
                && ((this.getCodigoPerfilVendido() == castOther
                        .getCodigoPerfilVendido()) || (this
                        .getCodigoPerfilVendido() != null
                        && castOther.getCodigoPerfilVendido() != null && this
                        .getCodigoPerfilVendido().equals(
                                castOther.getCodigoPerfilVendido())))
                && ((this.getValorPerfilVendido() == castOther
                        .getValorPerfilVendido()) || (this
                        .getValorPerfilVendido() != null
                        && castOther.getValorPerfilVendido() != null && this
                        .getValorPerfilVendido().equals(
                                castOther.getValorPerfilVendido())))
                && ((this.getDataAlocacaoPeriodo() == castOther
                        .getDataAlocacaoPeriodo()) || (this
                        .getDataAlocacaoPeriodo() != null
                        && castOther.getDataAlocacaoPeriodo() != null && this
                        .getDataAlocacaoPeriodo().equals(
                                castOther.getDataAlocacaoPeriodo())))
                && ((this.getCodigoContratoPratica() == castOther
                        .getCodigoContratoPratica()) || (this
                        .getCodigoContratoPratica() != null
                        && castOther.getCodigoContratoPratica() != null && this
                        .getCodigoContratoPratica().equals(
                                castOther.getCodigoContratoPratica())))
                && ((this.getCodigoAlocacao() == castOther.getCodigoAlocacao()) || (this
                        .getCodigoAlocacao() != null
                        && castOther.getCodigoAlocacao() != null && this
                        .getCodigoAlocacao().equals(
                                castOther.getCodigoAlocacao())));
    }

    /**
     * @see Object#hashCode()
     * @return HashCode do Objeto
     */
    @Override
    public int hashCode() {
        int result = 17;

        result = 37
                * result
                + (getCodigoPessoa() == null ? 0 : this.getCodigoPessoa()
                        .hashCode());
        result = 37
                * result
                + (getPercentualAlocacaoPeriodo() == null ? 0 : this
                        .getPercentualAlocacaoPeriodo().hashCode());
        result = 37
                * result
                + (getCodigoPerfilVendido() == null ? 0 : this
                        .getCodigoPerfilVendido().hashCode());
        result = 37
                * result
                + (getValorPerfilVendido() == null ? 0 : this
                        .getValorPerfilVendido().hashCode());
        result = 37
                * result
                + (getDataAlocacaoPeriodo() == null ? 0 : this
                        .getDataAlocacaoPeriodo().hashCode());
        result = 37
                * result
                + (getCodigoContratoPratica() == null ? 0 : this
                        .getCodigoContratoPratica().hashCode());
        result = 37
                * result
                + (getCodigoAlocacao() == null ? 0 : this.getCodigoAlocacao()
                        .hashCode());
        return result;
    }

}