/*
 * @(#) VwPmsCustoEmbutidoPv.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela VW_PMS_CUSTO_EMBUTIDO_PV.
 * 
 * @author Generated by Hibernate Tools 3.4.0.CR1
 * @since 16/10/2013 15:43:56
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VW_PMS_CUSTO_EMBUTIDO_PV")
@NamedQueries({
		@NamedQuery(name = "VwPmsCustoEmbutidoPv.findAll", query = "SELECT t FROM VwPmsCustoEmbutidoPv t"),
		@NamedQuery(name = "VwPmsCustoEmbutidoPv.findByClobAndMes", query = "SELECT t FROM VwPmsCustoEmbutidoPv t "
				+ "WHERE t.id.codigoContratoPratica = ? "
				+ "AND t.id.dataAlocacaoPeriodo = ?"
				+ "ORDER BY t.id.dataAlocacaoPeriodo") })
public class VwPmsCustoEmbutidoPv implements java.io.Serializable {

	/**
	 * Valor do serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constante para NamedQuery "VwPmsCustoEmbutidoPv.findAll".
	 */
	public static final String FIND_ALL = "VwPmsCustoEmbutidoPv.findAll";
	
	/**
	 * Constante para NamedQuery "VwPmsCustoEmbutidoPv.findByClobAndMes".
	 */
	public static final String FIND_BY_CLOB_DATAMES = "VwPmsCustoEmbutidoPv.findByClobAndMes";

	/**
	 * Atributo gerado a partir da coluna TOTAL.
	 */
	@EmbeddedId
	@GeneratedValue(generator = "VwPmsCustoEmbutidoPvSeq")
	@SequenceGenerator(name = "VwPmsCustoEmbutidoPvSeq", sequenceName = "SQ_COPR_CD_CONTRATO_PRATICA", allocationSize = 1)
	@AttributeOverrides({
			@AttributeOverride(name = "codigoContratoPratica", column = @Column(name = "COPR_CD_CONTRATO_PRATICA", precision = 18, scale = 0)),
			@AttributeOverride(name = "dataAlocacaoPeriodo", column = @Column(name = "ALPE_DT_ALOCACAO_PERIODO", length = 7)),
			@AttributeOverride(name = "codigoMoeda", column = @Column(name = "MOED_CD_MOEDA", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "", column = @Column(name = "TOTAL", precision = 22, scale = 0)) })
	private VwPmsCustoEmbutidoPvId id;

	/**
	 * Construtor default.
	 */
	public VwPmsCustoEmbutidoPv() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param id
	 *            Valor do atributo id;
	 */
	public VwPmsCustoEmbutidoPv(VwPmsCustoEmbutidoPvId id) {
		this.id = id;
	}

	/**
	 * Obtem o valor do atributo id.<BR>
	 * Atributo gerado a partir da coluna TOTAL.
	 * 
	 * @return Valor do atributo id.
	 */
	public VwPmsCustoEmbutidoPvId getId() {
		return this.id;
	}

	/**
	 * Atualiza o valor do atributo id.<BR>
	 * Atributo gerado a partir da coluna TOTAL.
	 * 
	 * @param id
	 *            Novo valor para o atributo id.
	 */
	public void setId(VwPmsCustoEmbutidoPvId id) {
		this.id = id;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
