/*
 * @(#) VwPmsFinancials.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela VW_PMS_FINANCIALS.
 * 
 * @author Generated by Hibernate Tools 3.6.0
 * @since 24/01/2013 19:16:44
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VW_PMS_FINANCIALS")
@NamedQueries({
		@NamedQuery(name = "VwPmsFinancials.findAll", query = "SELECT t FROM VwPmsFinancials t"),

		@NamedQuery(name = "VwPmsFinancials.findByClobAndDataMes", query = "SELECT t FROM VwPmsFinancials t "
				+ " WHERE t.id.codigoContratoPratica = ? "
				+ " AND TRUNC(t.id.mes) = TRUNC(?) ") })
public class VwPmsFinancials implements java.io.Serializable {

	/** Valor do serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Constante para NamedQuery "VwPmsFinancials.findAll". */
	public static final String FIND_ALL = "VwPmsFinancials.findAll";

	/** Constante para NamedQuery "VwPmsFinancials.findAll". */
	public static final String FIND_BY_CLOB_AND_DATAMES = "VwPmsFinancials.findByClobAndDataMes";

	/**
	 * Atributo gerado a partir da coluna R_UR_MEDIO.
	 */
	@EmbeddedId
	@GeneratedValue(generator = "VwPmsFinancialsSeq")
	@SequenceGenerator(name = "VwPmsFinancialsSeq", sequenceName = "SQ_COPR_CD_CONTRATO_PRATICA", allocationSize = 1)
	@AttributeOverrides({
			@AttributeOverride(name = "codigoContratoPratica", column = @Column(name = "COPR_CD_CONTRATO_PRATICA", precision = 18, scale = 0)),
			@AttributeOverride(name = "mes", column = @Column(name = "DT_MES", length = 8)),
			@AttributeOverride(name = "totalFteProjetado", column = @Column(name = "P_TOTAL_FTE", precision = 22, scale = 0)),
			@AttributeOverride(name = "avgUrProjetado", column = @Column(name = "P_AVG_UR", precision = 22, scale = 0)),
			@AttributeOverride(name = "totalReceitaProjetado", column = @Column(name = "P_TOTAL_RECEITA", precision = 22, scale = 0)),
			@AttributeOverride(name = "totalFteReceitado", column = @Column(name = "R_TOTAL_FTE", precision = 22, scale = 0)),
			@AttributeOverride(name = "totalReceitaReceitado", column = @Column(name = "R_TOTAL_RECEITA", precision = 22, scale = 0)),
			@AttributeOverride(name = "urMedioReceitado", column = @Column(name = "R_UR_MEDIO", length = 40)) })
	private VwPmsFinancialsId id;
	
	

	/**
	 * Construtor default.
	 */
	public VwPmsFinancials() {
	}

	/**
	 * Construtor com preenchimento da entidade.
	 * 
	 * @param id
	 *            Valor do atributo id;
	 */
	public VwPmsFinancials(final VwPmsFinancialsId id) {
		this.id = id;
	}

	/**
	 * Obtem o valor do atributo id.<BR>
	 * Atributo gerado a partir da coluna R_UR_MEDIO.
	 * 
	 * @return Valor do atributo id.
	 */
	public VwPmsFinancialsId getId() {
		return this.id;
	}

	/**
	 * Atualiza o valor do atributo id.<BR>
	 * Atributo gerado a partir da coluna R_UR_MEDIO.
	 * 
	 * @param id
	 *            Novo valor para o atributo id.
	 */
	public void setId(final VwPmsFinancialsId id) {
		this.id = id;
	}

	/**
	 * @see Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}