/*
 * @(#) VwPmsFinancialsId.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * VwPmsFinancialsId generated by hbm2java.
 * 
 * @author Generated by Hibernate Tools 3.6.0
 * @since 24/01/2013 19:16:44
 * @version 09/01/19 1.1 10:08:00
 */
@Embeddable
public class VwPmsFinancialsId implements java.io.Serializable {

	/** Valor do serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Constante para NamedQuery "VwPmsFinancialsId.findAll". */
	public static final String FIND_ALL = "VwPmsFinancialsId.findAll";

	/**
	 * Atributo gerado a partir da coluna COPR_CD_CONTRATO_PRATICA. Codigo do
	 * Contrato_Pratica
	 */
	@Column(name = "COPR_CD_CONTRATO_PRATICA", precision = 18, scale = 0)
	private Long codigoContratoPratica;

	/** Atributo gerado a partir da coluna DT_MES. */
	@Temporal(TemporalType.DATE)
	@Column(name = "DT_MES", length = 8)
	private Date mes;

	/** Atributo gerado a partir da coluna MOED_CD_MOEDA. */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOED_CD_MOEDA", nullable = false)
	private Moeda moeda;

	/** Atributo gerado a partir da coluna P_TOTAL_FTE. */
	@Column(name = "P_TOTAL_FTE", precision = 22, scale = 0)
	private BigDecimal totalFteProjetado;

	/** Atributo gerado a partir da coluna P_AVG_UR. */
	@Column(name = "P_AVG_UR", precision = 22, scale = 0)
	private BigDecimal avgUrProjetado;

	/** Atributo gerado a partir da coluna P_TOTAL_RECEITA. */
	@Column(name = "P_TOTAL_RECEITA", precision = 22, scale = 0)
	private BigDecimal totalReceitaProjetado;

	/** Atributo gerado a partir da coluna R_TOTAL_FTE. */
	@Column(name = "R_TOTAL_FTE", precision = 22, scale = 0)
	private BigDecimal totalFteReceitado;

	/** Atributo gerado a partir da coluna R_TOTAL_RECEITA. */
	@Column(name = "R_TOTAL_RECEITA", precision = 22, scale = 0)
	private BigDecimal totalReceitaReceitado;

	/** Atributo gerado a partir da coluna R_UR_MEDIO. */
	@Column(name = "R_UR_MEDIO", precision = 22, scale = 0)
	private BigDecimal urMedioReceitado;

	/** Flag para indicar se o VwPmsFinancials possui revenue. */
	@Transient
	private boolean hasRevenue = Boolean.FALSE;

	/**
	 * Construtor default.
	 */
	public VwPmsFinancialsId() {
	}

	/**
	 * @return the codigoContratoPratica
	 */
	public Long getCodigoContratoPratica() {
		return codigoContratoPratica;
	}

	/**
	 * @param codigoContratoPratica
	 *            the codigoContratoPratica to set
	 */
	public void setCodigoContratoPratica(final Long codigoContratoPratica) {
		this.codigoContratoPratica = codigoContratoPratica;
	}

	/**
	 * @return the mes
	 */
	public Date getMes() {
		return mes;
	}

	/**
	 * @param mes
	 *            the mes to set
	 */
	public void setMes(final Date mes) {
		this.mes = mes;
	}

	/**
	 * @return the moeda
	 */
	public Moeda getMoeda() {
		return moeda;
	}

	/**
	 * @param moeda
	 *            the moeda to set
	 */
	public void setMoeda(final Moeda moeda) {
		this.moeda = moeda;
	}

	/**
	 * @return the totalFteProjetado
	 */
	public BigDecimal getTotalFteProjetado() {
		return totalFteProjetado;
	}

	/**
	 * @param totalFteProjetado
	 *            the totalFteProjetado to set
	 */
	public void setTotalFteProjetado(final BigDecimal totalFteProjetado) {
		this.totalFteProjetado = totalFteProjetado;
	}

	/**
	 * @return the avgUrProjetado
	 */
	public BigDecimal getAvgUrProjetado() {
		return avgUrProjetado;
	}

	/**
	 * @param avgUrProjetado
	 *            the avgUrProjetado to set
	 */
	public void setAvgUrProjetado(final BigDecimal avgUrProjetado) {
		this.avgUrProjetado = avgUrProjetado;
	}

	/**
	 * @return the totalReceitaProjetado
	 */
	public BigDecimal getTotalReceitaProjetado() {
		return totalReceitaProjetado;
	}

	/**
	 * @param totalReceitaProjetado
	 *            the totalReceitaProjetado to set
	 */
	public void setTotalReceitaProjetado(final BigDecimal totalReceitaProjetado) {
		this.totalReceitaProjetado = totalReceitaProjetado;
	}

	/**
	 * @return the totalFteReceitado
	 */
	public BigDecimal getTotalFteReceitado() {
		return totalFteReceitado;
	}

	/**
	 * @param totalFteReceitado
	 *            the totalFteReceitado to set
	 */
	public void setTotalFteReceitado(final BigDecimal totalFteReceitado) {
		this.totalFteReceitado = totalFteReceitado;
	}

	/**
	 * @return the totalReceitaReceitado
	 */
	public BigDecimal getTotalReceitaReceitado() {
		return totalReceitaReceitado;
	}

	/**
	 * @param totalReceitaReceitado
	 *            the totalReceitaReceitado to set
	 */
	public void setTotalReceitaReceitado(final BigDecimal totalReceitaReceitado) {
		this.totalReceitaReceitado = totalReceitaReceitado;
	}

	/**
	 * @return the urMedioReceitado
	 */
	public BigDecimal getUrMedioReceitado() {
		return urMedioReceitado;
	}

	/**
	 * @param urMedioReceitado
	 *            the urMedioReceitado to set
	 */
	public void setUrMedioReceitado(final BigDecimal urMedioReceitado) {
		this.urMedioReceitado = urMedioReceitado;
	}

	/**
	 * @return the hasRevenue
	 */
	public boolean isHasRevenue() {
		return hasRevenue;
	}

	/**
	 * @param hasRevenue
	 *            the hasRevenue to set
	 */
	public void setHasRevenue(final boolean hasRevenue) {
		this.hasRevenue = hasRevenue;
	}

}