/*
 * @(#) VwPmsReceitaResultado.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity gerado a partir da tabela VW_PMS_RECEITA_RESULTADO.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 19/01/2012 09:51:22
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VW_PMS_RECEITA_RESULTADO")
@NamedQueries({
        @NamedQuery(name = "VwPmsReceitaResultado.findAll", query = "SELECT t FROM VwPmsReceitaResultado t"),
        @NamedQuery(name = "VwPmsReceitaResultado.findByDataMes", query = "SELECT t FROM VwPmsReceitaResultado t"
                + " WHERE t.id.dataAlocacaoPeriodo = ?")})
public class VwPmsReceitaResultado implements java.io.Serializable {

    /** Valor do serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** Constante para NamedQuery "VwPmsReceitaResultado.findAll". */
    public static final String FIND_ALL = "VwPmsReceitaResultado.findAll";

    /** Constante para NamedQuery "VwPmsReceitaResultado.findByDataMes". */
    public static final String FIND_BY_DATA_MES =
            "VwPmsReceitaResultado.findByDataMes";

    /**
     * Atributo gerado a partir da coluna TOTAL_RECEITA.
     */
    @EmbeddedId
    @GeneratedValue(generator = "VwPmsReceitaResultadoSeq")
    @SequenceGenerator(name = "VwPmsReceitaResultadoSeq", sequenceName = "SQ_COPR_CD_CONTRATO_PRATICA", allocationSize = 1)
    @AttributeOverrides({
            @AttributeOverride(name = "codigoContratoPratica", column = @Column(name = "COPR_CD_CONTRATO_PRATICA", nullable = false, precision = 18, scale = 0)),
            @AttributeOverride(name = "nomeContratoPratica", column = @Column(name = "COPR_NM_CONTRATO_PRATICA", length = 240)),
            @AttributeOverride(name = "codigoMoedaPadrao", column = @Column(name = "MOED_CD_MOEDA_PADRAO", nullable = false, precision = 18, scale = 0)),
            @AttributeOverride(name = "siglaMoeda", column = @Column(name = "MOED_SG_MOEDA", length = 10)),
            @AttributeOverride(name = "dataAlocacaoPeriodo", column = @Column(name = "ALPE_DT_ALOCACAO_PERIODO", length = 7)),
            @AttributeOverride(name = "fte", column = @Column(name = "TOTAL_FTE", precision = 22, scale = 0)),
            @AttributeOverride(name = "receita", column = @Column(name = "TOTAL_RECEITA", precision = 22, scale = 0))})
    private VwPmsReceitaResultadoId id;

    /**
     * Construtor default.
     */
    public VwPmsReceitaResultado() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param id
     *            Valor do atributo id;
     */
    public VwPmsReceitaResultado(final VwPmsReceitaResultadoId id) {
        this.id = id;
    }

    /**
     * Obtem o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna TOTAL_RECEITA.
     * 
     * @return Valor do atributo id.
     */
    public VwPmsReceitaResultadoId getId() {
        return this.id;
    }

    /**
     * Atualiza o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna TOTAL_RECEITA.
     * 
     * @param id
     *            Novo valor para o atributo id.
     */
    public void setId(final VwPmsReceitaResultadoId id) {
        this.id = id;
    }

    /**
     * @see Object#toString().
     * 
     * @return toString
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}