/*
 * @(#) VwReceitaFilter.java
 * Copyright (c) 2008 Ci&T Software S/A.
 * All Rights Reserved.
 */
package com.ciandt.pms.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Entity gerado a partir da tabela VW_RECEITA_FILTER.
 * 
 * @author Generated by Hibernate Tools 3.2.4.GA
 * @since 28/12/2009 16:11:03
 * @version 09/01/19 1.1 10:08:00
 */
@Entity
@Table(name = "VW_RECEITA_FILTER")
@NamedQueries({

        @NamedQuery(name = "VwReceitaFilter.findAll", query = "SELECT t FROM VwReceitaFilter t"),

        @NamedQuery(name = "VwReceitaFilter.findByFilter", query = "SELECT filter FROM VwReceitaFilter filter "
                + " WHERE (filter.id.codigoNatureza  = ? OR ? = -1L) "
                + " AND (filter.id.codigoCentroLucro = ? OR ? = -1L) "
                + " AND (filter.id.codigoPratica     = ? OR ? = -1L) "
                + " AND (filter.id.codigoCliente     = ? OR ? = -1L) "
                + " AND (filter.id.indicadorVersao   = ? OR ? is null) "
                + " AND (TRUNC(filter.id.dataMes)    = TRUNC(?) OR filter.id.dataMes = ?) ")

})
public class VwReceitaFilter implements java.io.Serializable {

    // ========================================================================
    // BEGIN - Coloque aqui o codigo manual
    // ========================================================================

    /** Constante para NamedQuery "VwReceitaFilter.findByFilter". */
    public static final String FIND_BY_FILTER = "VwReceitaFilter.findByFilter";

    // ========================================================================
    // END
    // ========================================================================
    /**
     * Valor do serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constante para NamedQuery "VwReceitaFilter.findAll".
     */
    public static final String FIND_ALL = "VwReceitaFilter.findAll";

    /**
     * Atributos.
     */
    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "codigoContratoPratica", 
                    column = @Column(name = "COPR_CD_CONTRATO_PRATICA", 
                            nullable = false, precision = 18, scale = 0)),
            @AttributeOverride(name = "nomeContratoPratica", 
                    column = @Column(name = "COPR_NM_CONTRATO_PRATICA", length = 240)),
            @AttributeOverride(name = "codigoReceita", 
                    column = @Column(name = "RECE_CD_RECEITA", precision = 18, scale = 0)),
            @AttributeOverride(name = "dataMes", 
                    column = @Column(name = "RECE_DT_MES", length = 7)),
            @AttributeOverride(name = "codigoCliente", 
                    column = @Column(name = "CLIE_CD_CLIENTE", precision = 18, scale = 0)),
            @AttributeOverride(name = "nomeCliente", 
                    column = @Column(name = "CLIE_NM_CLIENTE", length = 100)),
            @AttributeOverride(name = "codigoNatureza", 
                    column = @Column(name = "NACL_CD_NATUREZA", precision = 18, scale = 0)),
            @AttributeOverride(name = "codigoCentroLucro", 
                    column = @Column(name = "CELU_CD_CENTRO_LUCRO", precision = 18, scale = 0)),
            @AttributeOverride(name = "codigoPratica", 
                    column = @Column(name = "PRAT_CD_PRATICA", precision = 18, scale = 0)),
            @AttributeOverride(name = "nomeCentroLucro", 
                    column = @Column(name = "CELU_NM_CENTRO_LUCRO", length = 100)),
            @AttributeOverride(name = "nomePratica", 
                    column = @Column(name = "PRAT_NM_PRATICA", length = 100)),
            @AttributeOverride(name = "nomeNatureza", 
                    column = @Column(name = "NACL_NM_NATUREZA", length = 100)),
            @AttributeOverride(name = "indicadorVersao", 
                    column = @Column(name = "RECE_IN_VERSAO", length = 2)) })
    private VwReceitaFilterId id;

    /**
     * Valor da receita total. Este valor NÃO vem do banco, é calculado pela
     * aplicação.
     */
    @Transient
    private Double valorReceita;

    /**
     * Indicador do padrão para exibição de valores de moeda. Este valor NÃO vem
     * do banco.
     */
    @Transient
    private String patternCurrency = "";

    /**
     * Construtor default.
     */
    public VwReceitaFilter() {
    }

    /**
     * Construtor com preenchimento da entidade.
     * 
     * @param id
     *            Valor do atributo id;
     */
    public VwReceitaFilter(final VwReceitaFilterId id) {
        this.id = id;
    }

    /**
     * Obtem o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna RECE_IN_VERSAO.
     * 
     * @return Valor do atributo id.
     */
    public VwReceitaFilterId getId() {
        return this.id;
    }

    /**
     * Atualiza o valor do atributo id.<BR>
     * Atributo gerado a partir da coluna RECE_IN_VERSAO.
     * 
     * @param id
     *            Novo valor para o atributo id.
     */
    public void setId(final VwReceitaFilterId id) {
        this.id = id;
    }

    /**
     * @see Object#toString()
     * 
     * @return retorna o objeto no formato de string.
     */
    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(
                Integer.toHexString(hashCode())).append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    /**
     * @param valorReceita
     *            the valorReceita to set
     */
    public void setValorReceita(final Double valorReceita) {
        this.valorReceita = valorReceita;
    }

    /**
     * @return the valorReceita
     */
    public Double getValorReceita() {
        return valorReceita;
    }

    /**
     * @return the patternCurrency
     */
    public String getPatternCurrency() {
        return patternCurrency + " ";
    }

    /**
     * @param patternCurrency
     *            the patternCurrency to set
     */
    public void setPatternCurrency(final String patternCurrency) {
        this.patternCurrency = patternCurrency;
    }

}
